### PR TITLE
See No Evil, Hear No Evil, Speak No Evil

### PR DESCRIPTION
**Pull request by LordFowl**
Drones are now unable to see carbon/human mobs, living/silicon mobs, and living/bot mobs. They can still see living/simple_animal mobs.
Drones are now unable to identify the source of any voices not uttered by another drone. They will still hear the message, but it's source will be "unknown".

Edit; all in accordance to their third law:

> 3. Interact with no humanoid or synthetic being. that is not a fellow maintenance drone.

Stipulation; e-magged or otherwise hacked drones will be able to see and hear all man once more.
Stipulation 2; Construction drones are totally free from these restrictions, as they lack a non-interaction law.

I attempted to make the system for this as accessible as possible for anything else that might want to override a mob's image perspectively, in particular possibly hallucinations?

### CODE REVIEW

**Comment by NanakoAC** [comment]
i oppose this change personally. One of the most enjoyable parts of playing a drone is being able to do things while quietly observing the crew. the experience is already isolating enough, i dont see the need to make it moreso

**Comment by Rickymadenson** [comment]
Aim mentioned an issue which I seemed to agree with the most. You see, maintenance drones tend to help set up the engine when engineers are not present or even when they ARE. They won't be able to tell who did what in the Engine room when they're unable to see what steps those guys have finished so far. Same goes for anything else related to engineering and having crew involved in it. I forsee a future of lots of of maintenance drone smashing simply because "it didn't fukken listen to me hurr hurr" and that will likely make the role a pain to play. On Nanako'd opinion, personally I don't see that as much of an issue. You can always play a regular crew member, observe as a ghost or play a mouse? Howevee, I also see what you mean by the isolated part, but that can be easily fixed if you just play another role.

**Comment by LordFowl** [comment]
I don't see it. Being unable to see people does not mean you can't see what stage the engine isat. Drones can still hear and understand relevant information, they just have no understanding that it came from crew

**Comment by SirFruitcakes** [comment]
I was against this at first, but the alarming amount of people who don't realise that Drones are interacting by acknowledging their existence has changed my mind. I've been called out in a round through LOOC for repairing damage to the Station. 'Drone you're breaking your laws by repairing that window.' even when as far as the Drone was concerned, they weren't even there. I could understand if they were doing something with the window, like removing it properly, or repairing it, but they weren't repairing, changing it, or anything. They just broke it (Destroyed, glass shards all over the floor) to enter illegally, not that a Drone should care about how you enter, only that the damage is there, which is how I normally interpret it. I'm saying some very specific people are abusing the fact that Drones can see them to try to get them in trouble for their non-interact Law. I don't mind if this goes through.

Oh, and Nanako, while you're entirely right that's a fun part about Drones, if it actually interferes with being able to play them properly, something isn't right with it. ATM Drones being able to see people both encourages memery as well as encourages people to break their laws. I would be against removing radio and making them not able to tell who speaks over it though.

**Comment by MarinaGryphon** [comment]
I still think this isn't a good idea. It pointlessly isolates the maintenance drone role, adds a layer of complexity for no extra gain, and interferes with normal, non-law-breaking operation (i.e. engine setup as mentioned before).

**Pull request closed without merging**
