### PR TITLE
Reverts Reagent Temperature Code

### PR DESCRIPTION
**Pull request by Geevies**
Reverts all of the Reagent Temp Code PRs, there are too many too mention.
It also removes some parts of what other people added onto it manually.
What it says on the tin. Currently it also removes some chemicals that relied on Phoron Salts, and I believe Zo'rane Fire may also be uncraftable, but I can probably fix that soon enough.

### CODE REVIEW

**Comment by Geevies** [comment]
!wip

**Comment by Geevies** [comment]
Alright, I've ran into two issues. One, vending machines don't vend anymore. Two, taste doesn't work anymore. If anyone has any bright ideas, go ahead and give 'em here.

**Comment by alsoandanswer** [comment]
Maybe you can go back to burger's PRs and see what he replaced with tempcode. And then copy paste back the deleted code.

**Comment by MarinaGryphon** [comment]
Why is this being done, exactly?

**Comment by alsoandanswer** [comment]
> Why is this being done, exactly?

Well, we'd want a clean slate to properly port in a better temperature system, and integrating a new one would be probably much easier than fixing the current, shitty one.

**Comment by Geevies** [comment]
Moondancer is also currently fixing TempCode. If she succeeds in correcting it completely, that PR will absolutely be better than this one, then I'll also close this one. For now, I'll keep poking around in this one to see if it fixes the "chemicals not hurting mobs when splashed on them" issue.

**Comment by SonicGotNuked** [comment]
Yeah, if it was alone, I wouldn't have an issue because of the drink stuff... but phoron salts is a thing.

Should make a feedback thread.

**Comment by skull132** [comment]
Stale and ow.

**Pull request closed without merging**
