### PR TITLE
Animal Control

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
Removes all station pets except Crusher, infirmary cat. A ship's cat is fine. The rest are mostly just stupid. Columbo is genuinely broken. Ginny is hostile wildlife. Foxes are not pets. Ian is ugly. They are constantly killed by airlocks or minor changes in the atmosphere or being clicked with the wrong item.

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Comment by KingOfThePing** [comment]
I heavily disgree. If you dont like the sprites - provide  better ones. "I don't like it, thus we removed it" is not good.

Ian is just a dog, a prime mascot. 
Crusher's a cat, also prime mascot material.
Ives is a hivebot, it uses a piece of (mostly ignored) lore.
Ginny is a space carp, a prominent piece of hostile fauna, but domesticated.
Chauncey is a fox, arguably the worst fitting one, but represents Command, smart, sly and idk what else.

You are free to not like it, everyone is free to disagree with your dislike towards it. Should not be merged or even considered to remove these.

If, at all, sprites should be updated since arguably, Chauncey and Ian are from the stone age.

**Comment by TheDanseMacabre** [comment]
> I heavily disgree. If you dont like the sprites - provide better ones. "I don't like it, thus we removed it" is not good.
> 
> Ian is just a dog, a prime mascot. Crusher's a cat, also prime mascot material. Ives is a hivebot, it uses a piece of (mostly ignored) lore. Ginny is a space carp, a prominent piece of hostile fauna, but domesticated. Chauncey is a fox, arguably the worst fitting one, but represents Command, smart, sly and idk what else.
> 
> You are free to not like it, everyone is free to disagree with your dislike towards it. Should not be merged or even considered to remove these.
> 
> If, at all, sprites should be updated since arguably, Chauncey and Ian are from the stone age.

Crusher is not removed by this PR. Ives is also not removed by this PR - because Ives is not mapped into the Horizon at all, which should tell you just how much people care about Ives, considering nobody has even noticed. The Horizon is not a petting zoo, it is a workplace - and for the most part, the pets are largely ignored by the crew at large. Frankly, the only ones I ever see people interact with are Crusher and maybe Columbo. They do mostly interfere with roleplay, however - it seems like every other round we have to deal with pets being killed by random things and going through the motions of "Oh, no, Chauncey has been crushed by an airlock again!" There is not a universal sense of love for the ship pets.

**Comment by Sinfulbehaviors** [comment]
Literally why? People by and large like the pets. I've never seen ANYONE complain about them.

**Comment by niennab** [comment]
A feedback thread is likely best for a huge change such as this.

**Review by Ben10083 — CHANGES_REQUESTED** [review]
Code is fine but needs a changelog

**Comment by Zelmana** [comment]
First your strip Columbo of his rank, nullifying the reference to detective Columbo, now we are discussing removing all pets?

Columbo is a working dog, not a pet. They are useful in plenty of s security situations and can and has been used many times effectively.

What gives you the authority to remove something because "it's stupid" if you remove these I will PR them back because "they're cool"

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
disregard my last review. this PR needs a changelog.

**Review by JohnWildkins — CHANGES_REQUESTED** [review]
Changelog and feedback thread.

**Comment by TheDanseMacabre** [comment]
> Changelog and feedback thread.

ok I made one https://forums.aurorastation.org/topic/17248-pr-14173-thread/

**Pull request closed without merging**
