### PR TITLE
3/4 sprites for some old stuff

### PR DESCRIPTION
**Pull request by Blundir**
Ports a bunch of TG and TGMC sprites (some were edited by me) to replace some of the ancient flat/isometric sprites. Look in icon differences for more info.  This pr touches up ore box, centrifuge, coin press, pipe dispenser and some others.

### CODE REVIEW

**Comment by Blundir** [comment]
!review

**Review by atteria — COMMENTED** [review]
Looks like a frame of the seed extractor animation got moved into the plant data disk somehow.

**Comment by Blundir** [comment]
ugh... weird

**Comment by atteria** [comment]
Looks like there's an issue report on IDB2 that looks pretty similar?
Must be IDB2.

**Review by atteria — APPROVED** [review]

**Review by alsoandanswer — APPROVED** [review]

**Review by SleepyGemmy — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
