### PR TITLE
Cultist Memory

### PR DESCRIPTION
**Pull request by Geevies**
* Converted how Vampire and Changeling variables are handled on the backend, let me know if there's something funky.
* Cultists can now memorize up to three runes, and can scribe them at will without a tome, at the cost of taking three times longer to do so. Check the Cultists tab in the top right.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Review by Arrow768 — CHANGES_REQUESTED** [review]
`Cultists can now memorize up to three runes, and can scribe them at will without a tome, at the cost of taking three times longer to do so. Check the Cultists tab in the top right.`
This change will lead to security having to kill all cultists if they wish to prevent cultists from escaping confinement as each cultist can remember one of the runes that can be used to escape confinement.
Due to cult being a team gamemode this change is not wanted.
(Having to kill a antagonist to prevent them from escaping confinement should not be the only way to neutralize a antagonist)

**Comment by MarinaGryphon** [comment]
> `Cultists can now memorize up to three runes, and can scribe them at will without a tome, at the cost of taking three times longer to do so. Check the Cultists tab in the top right.`
> This change will lead to security having to kill all cultists if they wish to prevent cultists from escaping confinement as each cultist can remember one of the runes that can be used to escape confinement.
> Due to cult being a team gamemode this change is not wanted.
> (Having to kill a antagonist to prevent them from escaping confinement should not be the only way to neutralize a antagonist)

I believe they can still be neutralised/deconverted by the Chaplain. Ways to neutralise antagonists without permanently removing them from the round/that involve others outside of Security are better than just locking someone in solitary, I think.

**Comment by Geevies** [comment]
!review

**Review by JohnWildkins — APPROVED** [review]
oh yeah, it's big brain time

**Comment by Geevies** [comment]
to comment on what arrow said, i've only made certain runes memorizable. i've selected ones i think won't be able to aid someone with escaping

**Review by fernerr — APPROVED** [review]
Tested the affected antags, seems to work, though something can always slip through ofcourse.

**Pull request merged**
