### PR TITLE
Kills spesscafe

### PR DESCRIPTION
**Pull request by nerocavalier**
* Spesscafe Dark Blend is now renamed Ganymede Dark Blend

### CODE REVIEW

**Comment by nerocavalier** [comment]
!review

**Review by Jaraci — APPROVED** [review]
Lore approval...

**Review by Casper3667 — APPROVED** [review]

**Review by TheDanseMacabre — APPROVED** [review]
Extremely based PR

**Comment by Caelphon** [comment]
I don't understand the need for a change? Can you walk me through it?

**Comment by Arrow768** [comment]
DNM until the above is answered.

**Comment by Jaraci** [comment]
Maybe I wasn't clear enough. I am human lore staff and asked for the PR.

1. Spesscafe is "spess" + Nescafé. Why do I even have to explain this? Am I being pranked?
2. I suggested Ganymede as it's consistent with upcoming human lore. It wasn't pulled out of a hat -- but even if it was, it would be better than Spesscafe is.
3. Not a single other one of these mini food/drink loreification PRs has gotten tangled up like this, and I'm actually seriously irritated that we can get to the stage of needing a DNM on something that's so obviously out of place. This is like asking why anyone would PR a change to the name of valid salad or 4no Raisins.

I didn't think I'd need to provide more explanation for a one word de-spessification PR than I would for any of my own PRs that actually change something, but there you go. Does that help?

**Pull request closed without merging**
