### PR TITLE
Western Bar Expansion

### PR DESCRIPTION
**Pull request by WickedCybs**
This makes the ship a little bigger by expanding the western bar area to the left by one tile. I've done this so the part of the bar where the bartenders hang out can mirror each other, as the western bit was cramped and needed whoever was manning it to move constantly if they were to serve more than just coffee.

image

image

image

image

image

### CODE REVIEW

**Comment by WickedCybs** [comment]
!review

**Comment by WickedCybs** [comment]
I tweaked the main bar area a bit more too, mainly swapping where the dispenser machines on the western bit were.

image

This makes the dispenser on each end pretty close to each other, but it looks better I think.

**Comment by WickedCybs** [comment]
I need to expand the scope of this and change the chaplains office, as it was brought to my attention that the shields will block the mass driver again.

**Comment by WickedCybs** [comment]
The chapel continues to be a not easily solved problem, since there's not a lot of room when it comes to moving the mass driver.

**Comment by WickedCybs** [comment]
I removed the mass driver's shield diffuser. I think it's fine for the chaplain to need to request the shields to go down.

**Review by NonQueueingMatt — APPROVED** [review]

**Review by JohnWildkins — APPROVED** [review]

**Pull request merged**
