### PR TITLE
Adds Morgan Black Prosthesis

### PR DESCRIPTION
**Pull request by ParadoxSpace**
Made out of faux-wood, but I won't blame you if you fluff yours as real wood.
image

image

image

image

image

image

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
!review

**Comment by Geevies** [comment]
you pushed the example changelog by mistake

**Comment by KingOfThePing** [comment]
weren't these rejected ages ago?

**Comment by ParadoxSpace** [comment]
fixed thanks jade

**Comment by Arrow768** [comment]
What has been changed since this has been closed here?
#6050

**Comment by ParadoxSpace** [comment]
Respectfully, nothing. there wasn't any actual hard requirements asked of me on the previous PR, it was just my points mostly being ignored and 'plastic and aluminum is a better material for prosthetics' when we have carbon fiber prosthetics, prosthetics with holographic displays, and steel prosthetics in general
i didn't feel the need to change anything about it because being an efficient material and shit wasn't the point of the prosthetic line. i dunno if i can call 'not the point' on a PR but that wasn't the point.

**Comment by alsoandanswer** [comment]
> I have concerns about how an entirely wood exterior prosthetic moves but whatever, I guess that's just [REDACTED]

I think "because it looks cool" is a good enough argument. Just say it's just polycarbonwhatever space material with a wooden laminate finish, like a fancy car dashboard interior.

**Comment by skull132** [comment]
If you want scrappy or poor prosthetics, then find some which fit our visual style better.
If you want to port some high-end prosthetics made of faux wood, then: they wouldn't be generally accessible and I still question how many would want them to look like pirate shit from the 1800s.
And in general, I don't think a direct, "Lol pirates" reference is a good fit for us.

**Pull request closed without merging**
