### PR TITLE
Timed PlaySound Proc

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR adds a timed playsound proc named "playsound_in" which lets you use the playsound proc after a set amount of time has passed.

example usage:
`playsound_in(src, 'sound/example.ogg', 50, FALSE, time = 1 SECOND)`

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Review by mikomyazaki — COMMENTED** [review]
Being a proc is fine. But it has no need to be really. Could make it a macro instead?

**Comment by SleepyGemmy** [comment]
RE: [message.](https://github.com/Aurorastation/Aurora.3/pull/13943#pullrequestreview-973027429)
\-----

> Being a proc is fine. But it has no need to be really. Could make it a macro instead?

making it a macro makes it give `incorrect number of macro arguments` as an error.

**Comment by NonQueueingMatt** [comment]
Superseded by #13938

**Review by alsoandanswer — APPROVED** [review]

**Review by JohnWildkins — APPROVED** [review]

**Pull request merged**
