### PR TITLE
Reducing Diona limb regen by half

### PR DESCRIPTION
**Pull request by Sindorman**
This PR is made by request and discussion of @ParadoxSpace and Neinbox. Reduces Diona limb regen from 10 minutes to 5 minutes.

### CODE REVIEW

**Comment by Arrow768** [comment]
Not a fan of it.
It is a pretty severe buff to diona.
They already have the ability to regenerate limbs on their own and I do not believe that the time for this needs to be reduced to 5 minutes.

**Comment by ParadoxSpace** [comment]
It didn't have any time at all before. Ten minutes is an absurdly long time in ss13. If I pretty much bathe myself in radiation and light I shouldn't have to emote for 10 minutes about it.

**Comment by Sindorman** [comment]
@Arrow768 IT was approved by Neinbox, Diona lore dev.

**Comment by skull132** [comment]
> Arrow768 IT was approved by Neinbox, Diona lore dev.

Approval from a lore dev does not mean we get to overlook balance. Let this be clear. Balance is ultimately our responsibility.

Anyways, to extrapolate a bit. Currently the process only requires a lump sum of radiation and sets the hunger modifier to be a bit more severe. But after that, there is no checks to make sure you have enough energy to keep regenerating the limb. This makes the action in question very passive and relatively cheap, in terms of resources. So you pay with time instead.

It might be an idea to instead make the process require energy constantly, and fail if none is about? After that, you could make it faster, yes.

**Comment by Sindorman** [comment]
Neinbox Decided to keep things as they are

**Pull request closed without merging**
