### PR TITLE
Air alarm icon improvements, 3/4ths edition

### PR DESCRIPTION
**Pull request by Generalcamo**
image

Air alarm screens now glow in the dark.

This also makes the fan animation an overlay, and it is only animating when it is heating or cooling a room. This means you now have an at-a-glance method of telling if it's working or not!

### CODE REVIEW

**Comment by Generalcamo** [comment]
!review

**Review by SleepyGemmy — APPROVED** [review]

**Comment by Generalcamo** [comment]
IconDiffBot2 is very broken ATM. Ignore it, I have proof that the icons are set up correctly, and do not have random fire alarm sprites in them:
image

**Comment by FluffyGhoster** [comment]
I believe you should clear the overlays on destroy, if you're adding them

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
How often does a room need to heat/reheat?
My main concern is room heating/reheating happens so sparsely that the animation will not be seen by anyone.

If so, please just leave the fan animation as-is.

**Comment by Generalcamo** [comment]
> How often does a room need to heat/reheat?
> My main concern is room heating/reheating happens so sparsely that the animation will not be seen by anyone.

Pretty common. Everytime a room:
- Is on fire
- Has any machines running
- Someone adjusts the thermostat (there is a canon piece on conflicts started through this)

This is more common in the cold rooms, mainly:
- Server room
- Telecoms
- Freezer
- Morgue

I do not believe this animation will rarely be played at all. Plus the air alarm uses a significant amount of power to do this, and there's no reason for a fan to exist on the air alarm anyway except when it is heating/cooling a room as it is a passive device, not an active device unless it is heating or cooling.

**Review by alsoandanswer — APPROVED** [review]
Sure.

**Pull request merged**
