### PR TITLE
Unapologetic Medieval Buffs

### PR DESCRIPTION
**Pull request by ParadoxSpace**
To fight the new scourge of Christendom, NanoTrasen employees have found out how to craft simple wooden shields out of wood, and to block common threats such as beanbags, rubber bullets, and stunshots.

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
!review

**Comment by ParadoxSpace** [comment]
The buckler now needs a wooden donut and steel fittings in order to be made.

**Comment by OneOneThreeEight** [comment]
long as it doesn't block lethal shot its all gucci

**Comment by Pacmandevil** [comment]
mirror sheilds that deflect lasers when

**Comment by ParadoxSpace** [comment]
out of scope

**Pull request merged**
