### PR TITLE
Vomit Based Gameplay Addition

### PR DESCRIPTION
**Pull request by Geevies**
You will now throw up into disposal bins, sinks, and toilets if you're within range of them, instead of onto the floor, you fucking animal.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by Geevies** [comment]
you're not my mom, kyres

**Comment by LadyFowls** [comment]
Make it a choice, if I wanna vomit on the floor I should vomit on the floor

**Comment by Geevies** [comment]
Stand away from the vomit receptacle if you want to hurl on the floor. You have to be right next to it to trigger it.

**Comment by alsoandanswer** [comment]
I think they want a yes/no prompt for vomiting in receptacles.

Anyway this will improve RP since I've always vomited on the FLOOR of the sink instead of actually into the sink because my character's a paste eater
 
Also, you have a choice. You can still vomit on the floor, if that's what people are worried about.

**Comment by alsoandanswer** [comment]
Geeves, make a feedback thread

**Comment by Geevies** [comment]
I'm not going to make a yes/no prompt.

Feedback thread: https://forums.aurorastation.org/topic/12943-vomit-rangefinders-the-pr-the-feedback-thread/

**Pull request merged**
