### PR TITLE
Fixes hair style choices not checking for gender restrictions

### PR DESCRIPTION
**Pull request by Alberyk**
What it says in the title.

### CODE REVIEW

**Comment by TheDocOct** [comment]
This is such a longstanding "bug" that I would argue it has become more of a feature. Despite the fact that the functionality may have been intended at some point, it hasn't existed for a long, long time to my knowledge- with my limited git and DM experience, I can't even find a direct attempt to maintain the functionality beyond general codebase touch-ups earlier than a commit now nearing [_five and a half years old,_](https://github.com/Aurorastation/Aurora.3/commit/e1167219778ff3b90270296612f60ace681730fe) and that is still a refactor of the entire character setup rather an an attempt to implement gender-specific hair in particular, the last of which I could find being [8 years ago.](https://github.com/Aurorastation/Aurora.3/commit/de6eb16e1aeca7cb62c86394a34ab2b439ac620c)

If you still want to drag this back into force, I would like to ask for a feedback thread first, for gathering feedback from the community that will have to deal with what will effectively be brand new restrictions to the vast majority of the active playerbase.

**Comment by OneOneThreeEight** [comment]
Seconding feedback thread. It's one thing for xenos to have this feature specifically for sexual dimorphism's sake, but _hair_ itself is not really gendered, it's choice of growth half the time.

**Review by alsoandanswer — APPROVED** [review]

**Comment by Alberyk** [comment]
If people want the hairstyles of a certain species to be unlocked to all genders, they can do that in another pr by removing the var. This pr is needed for another pr in question. This is indeed fixing a bug, because some hairs do have gender restrictions and they do not work.

**Review by Geevies — CHANGES_REQUESTED** [review]
this'll affect a bunch of characters, so i believe a PR that removes the restriction from already active hairstyles should be merged in conjunction with this one. i'll start making that PR rn

**Review by Geevies — APPROVED** [review]

**Pull request merged**
