### PR TITLE
Removes Tripping in High Heels

### PR DESCRIPTION
**Pull request by lavillastrangiato**
Read this description before you make any remarks.

"La Villa Strangiato," I already hear you saying. "High heels are impractical! Removing this debuff would make SECURITY OFFICERS wear heels! Doctors would wear heels too! Heels are hard to run in; that's just a fact!" Why do I never see this argument with oxford shoes? Oxford shoes SUCK ASS to run in, yet I see the occasional spiffy Idris officer wearing them. And that's not bad! But the only time I've ever seen people get up in arms about "impractical shoes" is with heels. Which, given that it is The Girl Shoe, is something I find mildly sexist.

"But La Villa Strangiato, saying it's sexism isn't relevant, heeled shoes are still impractical and nobody would ever wear them to work." Listen. As A Woman(TM), I don't like wearing high heels on the reg because I find them sort of uncomfortable to wear. But there are *plenty* of women who wear them all the time, and wear them to work! Now obviously, a lot of workplace dress codes like working as a security guard, or an engineer, would prohibit you from wearing heeled shoes because OSHA stuff. But if you are, say, a female bridge crewman, or a physician (yes, GPs wear heels, *my own GP does*), or even a researcher who doesn't do anything wacky, then it is perfectly within the bounds of reason and normalcy to wear some tasteful low heels.

"But nobody can run in heels--" There is an entire race in Australia where a bunch of people run in stilettos. Which are the thinnest heel. I guarantee you there are people who can run in heels and they are more numerous than you think.

As a final statement, we are a roleplay server and we have dress codes that exist to standardize our uniform. If someone is violating these dresscodes, you tell them to stop ICly or you ahelp it. I do not like this double-standard that is applied exclusively to The Girl Clothes, and that they *make you more vulnerable to attack and injury*, which is why I am getting rid of it.

### CODE REVIEW

**Comment by lavillastrangiato** [comment]
!review

**Review by DreamySkrell — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Review by SleepyGemmy — APPROVED** [review]

**Review by Geevies — APPROVED** [review]

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
actually its to balance heels being able to be used as a makeshift weapon, since it has a higher than average force, does more damage on a stomp attack and is considered a sharp item, making it able to eyestab as well

just remove the extra damage and this removal will be ok

**Comment by lavillastrangiato** [comment]
On VSCode, someone commented in that section that the reason you tripped in heels was because you were "running in impractical shoes", which I have already explained at length why it is ridiculous. In addition, Alberyk in his original PR (#7288)  explicitly compared their features to screwdrivers, another tool that is about as accessible as high heels, given every crewmember on the ship can access them in tool storage.

I don't see why they should be nerfed, given that these are incredibly negligible damage values that are matched by a very easily accessible tool.

**Comment by FluffyGhoster** [comment]
>But there are plenty of women who wear them all the time, and wear them to work!

Do they run at full sprint and as fast as those who do not?


>But if you are, say, a female bridge crewman, or a physician (yes, GPs wear heels, my own GP does), or even a researcher who doesn't do anything wacky, then it is perfectly within the bounds of reason and normalcy to wear some tasteful low heels.

Do they run around? Because a GP do not, an emergency room doctor does not wear heels (iirc here they are explicitly not permitted, because they can slip on fluids etc., since they have lower grip on the terrain than shoes that have full contact, and yes that also goes for oxford shoes, though of course the larger the contact surface, the better the grip, all else equal), I do not know what an equivalent to a BC would be, possibly some office worker? If so, they don't usually run like their life depend on it either
You are describing jobs (excluding the emergency room doctor, but as outlined above they do not wear high heels while doing that function) that don't need to run generally, so the tripping mechanic would not even apply to them walking around as usual, so it isn't analogous


>There is an entire race in Australia where a bunch of people run in stilettos. Which are the thinnest heel. I guarantee you there are people who can run in heels and they are more numerous than you think.

You mean the race where people trip and fall, as seen in https://www.youtube.com/watch?v=EJABBlCYXIU ?


>On VSCode, someone commented in that section that the reason you tripped in heels was because you were "running in impractical shoes", which I have already explained at length why it is ridiculous.

Someone commenting something on vscode (I guess you mean in a commit?) doesn't mean that it is the reason, and even less the sole reason, why something is there


>compared their features to screwdrivers, another tool that is about as accessible as high heels, given every crewmember on the ship can access them in tool storage.

A screwdriver uses an item/backpack slot or 5 inventory points (for the combitool), you have to go out of your way to acquire it, and generally have a reason to keep it on you; on the other hand, this item does not take any space that you could use for anything else but other shoes (the boots slot), and costs 1 inventory point (I think?)


>I don't see why they should be nerfed, given that these are incredibly negligible damage values that are matched by a very easily accessible tool.

If they are negligible, it shouldn't be a problem to bring them in line with all the other shoes either, also the eye damage (`/obj/item/proc/eyestab(mob/living/carbon/M, mob/living/carbon/user)`) is not dependent on the object damage value, each hit has a 50% chance to apply paralysis and weakening you


As a side note, this change was already proposed and rejected in #11941 

For how I personally see it, this can be solved with one of these options:
- Add the same logic to the oxford shoes, this is the option I would prefer the most, it's a nice little mechanical difference versus a sea of identical things with a different sprite, name and description
- Increase the slowdown and remove the tripping, to reflect that you would not run as fast as you could with those on, for the average person
- Bring the shoes in line with every other shoes

**Comment by lavillastrangiato** [comment]
>As a side note, this change was already proposed and rejected in https://github.com/Aurorastation/Aurora.3/pull/11941

image

**Pull request merged**
