### PR TITLE
C4 Explosives

### PR DESCRIPTION
**Pull request by Geevies**
* Replaced Merc TTVs with bundles of C4 with a unique activation method.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by skull132** [comment]
what's the actual range of these things...?

**Comment by NonQueueingMatt** [comment]
Don't think I like this. TTVs are part of many merc gimmicks simply because they prevent security from rushing you down.

**Comment by skull132** [comment]
Denied. TTVs are betterer, unless the C4 ends up mimicking the behaviour to a large degree.

**Pull request closed without merging**
