### PR TITLE
Fixes some bugs with the Vaurcesian food

### PR DESCRIPTION
**Pull request by desvenlafaxine**
Namely, the sprite not showing up for the Caprician coffee, and the filtered k'ois not showing its proper name.

### CODE REVIEW

**Comment by desvenlafaxine** [comment]
!bugfix

**Comment by desvenlafaxine** [comment]
!review

**Review by Casper3667 — CHANGES_REQUESTED** [review]
You changed the example changelog rather than making a new one.

**Comment by desvenlafaxine** [comment]
> 
> 
> You changed the example changelog rather than making a new one.

Think it's fixed now.

**Review by Casper3667 — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
