### PR TITLE
Recolours the HeavySec borg to be blue

### PR DESCRIPTION
**Pull request by LordFowl**

### CODE REVIEW

**Comment by Lohikar** [comment]
Can we have a picture please?

**Comment by LordFowl** [comment]
http://i.imgur.com/BC8bTtr.png?1

@NanakoAC Comparing it to sleeksecurity is a fruitless endeavour, because it is far too bright. Bloodhound is the best comparison, because it is the OG recolour of security cyborgs that I did aeons ago.

**Comment by NanakoAC** [comment]
obsoleted by #1588 

I've standardised all the sec borgs to be a common tone that should be agreeable, taking into account your feedback RE: the previous spiderborg colors

**Comment by LordFowl** [comment]
Kindly do not add flags to PRs unless they need them.

**Comment by skull132** [comment]
Nanako's PR was merged now, as it uses the same shades of blue already out for the Bloodhound, thus filling your suggestion.

**Pull request closed without merging**
