### PR TITLE
Updates to Atmos machinery for new Gasses

### PR DESCRIPTION
**Pull request by furrycactus**
Updates a lot of atmos machinery (sensors/filters/scrubbers, etc.) to be able to recognise a good chunk of the new gasses added with the INDRA.

To-do:

- [x] Get the new gasses properly listed on gas sensors.
- [x] Get the new gasses properly listed on filters.
- [x] Get new canister designs for the new gasses.
- [x] Map in a really small area in Atmospherics with empty canisters of each new gas so they have somewhere to drain to properly if they end up in the Horizon's scrubber system. They don't need massive tanks like the other gasses.

Images below.

image

image

image

Had to scoot the ladder a tiny bit.

### CODE REVIEW

**Comment by furrycactus** [comment]
!wip

**Comment by furrycactus** [comment]
!review

**Review by FluffyGhoster — APPROVED** [review]
lgtm, but I would reformat the canisters list, so that it's

```
/obj/item/canister/whatever
    [variables]
/obj/item/canister/whatever/Initialize()
    [whatever]

/obj/item/canister/whatever2
    [variables]
/obj/item/canister/whatever2/Initialize()
    [whatever]
```

Instead of

```
/obj/item/canister/whatever
    [variables]

/obj/item/canister/whatever/Initialize()
    [whatever]
/obj/item/canister/whatever2
    [variables]

/obj/item/canister/whatever2/Initialize()
    [whatever]
```
Basically, grouping together the canister with its initialization proc

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by furrycactus** [comment]
Why am I cursed with camera c_tag variables from maps I haven't even touched going bonkers

**Comment by furrycactus** [comment]
I don't understand why exoplanet testing failed with the merge bot but it was fine on my last commit.

**Comment by furrycactus** [comment]
I'm just going to redo this entirely before I go insane.

**Pull request closed without merging**
