### PR TITLE
Adds "Getmoreans" as a whitelist playable race

### PR DESCRIPTION
**Pull request by TehFlaminTaco**
Adds the living cans, "Getmoreans" as a playable race.

Positive Traits:
+Immune to Oxygen, Toxin, and Radiation effects
+Has no eyes, so is immune to flashing / welding
+Resistant to Temperature damage
+No internal organs to look after. Just a Sweet-tasting Fizzy sludge.
+Feels no pain
+Doesn't need to eat/drink
Negative Traits:
-VERY weak to brute-force
-Cannot be cloned
-Low pay
-No head, Cannot wear headsets / helmets / masks
-Brand is always recognizable. Cannot hide their face.
-Cannot consume pills/liquids to gain their benefits. (Still weak to injections)

Character editor with custom logo

Other logo type

In-game

```
In cooperation with Robust Industries, LLC, the Getmore Chocolate Corperation attempted to produce a genetically modified line of sodas in order to dynamically appeal to customers. The Result? Getmoreans. A sentient line of soda products with human features, these human-can hybrides are famous for speaking corperate double speak, and generally being creepy. Instead of organs, they have a sweet tasting yet fizzy syrup that seems to serve the same functions. Because of this, things like temperature and radation have little effect on the cans, but being made of thin aluminum makes them extra weak to punches.
```

Getmoreans are the race of Can-people we've all been waiting for. Human-can hybrids that are proud of their brand, whatever absurd thing that may be. They lack a head, or anything resembling organs, and instead rely on their "Life Juice", the sweet-tasting fizzy fluid inside them which seems to serve multiple purposes within the Getmorean.

The name Getmorean stems from Getmore, the company who created them alongside Robust Industries in an attempt to make a new dynamic line of softdrinks. As such, Getmoreans are also typically trained in "Corporate Doublespeak", a twist on Basic which seems to be saying nothing in particular, but business professionals swear by.

The Average Getmorean names them-selves like a flavour of softdrink (Typically things like "Lemon Swirl" or more esoteric things), but the rare Getmorean will try to have a human name, to match the rest of their features. Getmoreans are also soully masculine, and cannot naturally reproduce. All Getmoreans are produced at Getmore's Getmorean Production Facilities™.

Getmoreans are usually loud, self-confident, and arrogant, with strong brand-loyalty to their own flavour, and Getmore. As they are technically products of Getmore, their contract reflects this, and they receive reduced pay.

### CODE REVIEW

**Comment by BurgerLUA** [comment]
Looks like you have a few cache files or whatever from midi to piano in here. Please delete them from the branch.

**Comment by LordFowl** [comment]
Why exactly do we need or want another jokey adminbus race?

**Comment by nerdass** [comment]
sunset overdrive reference?

**Comment by skull132** [comment]
no.jpg

**Pull request closed without merging**
