### PR TITLE
Disruptor Nerf

### PR DESCRIPTION
**Pull request by Geevies**
* Standard disruptors now have enough charge capacity for 8 shots in general, lethal shots no longer drain more.
* Lethal disruptor shots now do 20 burn damage, down from 30.
* Lethal disruptor shots no longer pass through windows and grilles.
* Stun disruptor shots now do 25 agony damage, down from 45.

Feedback thread: https://forums.aurorastation.org/topic/15240-feedback-disruptor-nerf/

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
You basically took a sledgehammer to a nail and that's not the way to solve this problem. You can't just lower every single stat something has and expect it to be a good idea.

A little bit of maths shows the problem here. Eight shots on stun * 20 agony = `160` total agony damage which is barely enough to drop one person in armor. This is assuming you hit all shots anyway. Which is not a good idea.

You want to pick out the strongest thing here (the nonlethals and the amount of lethal shots, namely) and adjust those. Don't go nuclear on the nerfs because that's just not the way to go about it.

**Comment by Geevies** [comment]
Remember to use the assigned feedback thread to give feedback.

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
That was not an opinion. This PR is not going in as is period, and it's the consensus of **ALL** maintainers.

**Comment by Geevies** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]
I guess this is fine now, even if I'm still apprehensive about it.

**Review by skull132 — APPROVED** [review]

**Pull request merged**
