### PR TITLE
Adds plate carriers, restyles all current station armor to plate carriers, turns arm guards and leg guards into accessories.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
The aim of this PR is to create modular armor that works better with accessories and to add the possibility for faction items to be appended to armor, while also allowing the possibility for more varied armor sets in the future. In addition, this PR also solves the curse of having to remove your shoes and gloves to put on leg guards by making them into accessories!

To-do:

- [x] Maybe make blood_overlay_type into a generic variable on all accessories so we can use it for armor.
- [x] Replace all defunct types.
- [x] Remove all defunct icons (ballistic/ablative/yadayada)
- [x] Give heads of staff the generic armor plate.
- [x] Other stuff that I'm forgetting.

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Comment by NonQueueingMatt** [comment]
!wip

**Comment by NonQueueingMatt** [comment]
! review

**Comment by NonQueueingMatt** [comment]
!review

**Review by Geevies — APPROVED** [review]

**Review by Doxxmedearly — APPROVED** [review]

**Pull request merged**
