### PR TITLE
ERT is now based on deterministic probability mathematics with a marginal error ratio of +-5 : 30

### PR DESCRIPTION
**Pull request by LordFowl**
ERT, when called via a keycard, will conduct a probability check based on percentage of crew dead, percentage of antagonists vs crew, with a base percentage of 20. Should this probability check succeed, ERT will be called as normal. Should it fail, the ERT will be called in roughly 30 minutes post fact, give or take 5 minutes.

https://forums.aurorastation.org/viewtopic.php?f=18&t=10284&start=10

- [ ] Testing

### CODE REVIEW

**Comment by BurgerLUA** [comment]
This fucking scared me, misread as "ERT has a 10% chance to fail." given the suggestions thread. This is a good compromise.

I'm a little skeptical with it being a 25-35 minute delay, however, but I don't know.

**Comment by flimango** [comment]
I'm not a fan of ERT being randomly called up to 30 minutes late if a check doesn't pass. I'd much rather ERT had a hardline limit of say, 10-15 minutes. The ghosts and everyone would still spawn in as normal, and be able to go through gear checks and whatnot, form a plan,etc. However, they'd be prevented from launching the shuttle (unless an admin intervenes), until the time limit is reached.

**Comment by Ezuo** [comment]
Flimango's idea is good. Just stop the shuttle itself from launching, instead of stopping the ERT spawning. You also need to take into account that the ERT actually gearing up and getting on station can already take a good 10-15 minutes depending.

**Comment by Aboshebab96** [comment]
I feel there will be a lot of cases where crew may not be dead but still in need of ERT support. 

This also makes little sense to me, considering ERT teams on response duty are QRF. They're sitting around on standby until called upon.

**Comment by flimango** [comment]
Abo brings up a good point that I mentioned in modchat when this was first being discussed. Sometimes the crew calls ERT for emergencies that aren't related to security at all, for example, a medical ERT during a massive viral outbreak (this is rare, yes, but a possibility). In that case, we'd possibly have minimal crew casualties, but still require ERT immediately. It wouldn't be much help to anyone if they showed up 35 minutes later.

**Comment by OneOneThreeEight** [comment]
Yet ERT should not be treated as a definitive "oh shit" button. The crew should make more of an avid attempt at fixing their own problems rather than relying on ghost roles to do it for them.

Remember that I suggested this as a middle-ground between keeping the system as toxic as it currently is versus outright lobbying to remove the ability to call it naturally at all.

**Comment by LordFowl** [comment]
Even when the crew calls an ERT for an emergency other than a security violation there is always a good chance that communication fails somehow and a "medical ERT" ends up being 3 ERT in security RIG and one guy in an engineering RIG. Another consideration I have planned is possibly diversifying the ERT into three different calls - security aid, medical aid, and engineering aid, that forces the ERT to actually comply with the reason they're called for. That's for a future PR however.

**Comment by Arrow768** [comment]
Technically I dont see an issue.
Lets wait for the feedback from the mins.

**Comment by Arrow768** [comment]
Vetoed by Headmins.

**Pull request closed without merging**
