### PR TITLE
Allow Trashcats and Guwan to wear galoshes.

### PR DESCRIPTION
**Pull request by Kaedwuff**
Galoshes are no longer species restricted, and once more, all janitors can look equally stupid in yellow rubber  boots.

### CODE REVIEW

**Comment by MarinaGryphon** [comment]
This was intentional. Maybe add "toeless galoshes" or something?

**Comment by Kaedwuff** [comment]
They're giant rubber yellow boots.  By what measure does that indicate they are tight fitting and inflexible, and doesn't it seem kind of counterproductive to add a giant hole to the front of boots intended to keep your feet dry and unslipped?

It's fine like this.  We don't need to make toeless variants to clutter up the closet.  The only thing I would agree with here would be making a separate 'claw fitting' set of galoshes, but they'd basically look the same so what's the point?

**Comment by SleepyWolfe** [comment]
If anything, at least give the ability to cut off the toes with wirecutters.

**Comment by Arrow768** [comment]
Sounds reasonable enough.

**Pull request merged**
