### PR TITLE
Unapologetic Diona Nerfs

### PR DESCRIPTION
**Pull request by ParadoxSpace**
The time has come.

Nymphs now have a *lot* less health, and need more nutrition to reform.

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
!review

**Comment by Chada-1** [comment]
What this'll lead to is Nymphs p. much getting instantly killed by Crew while they're trying to roleplay. 25 damage is 2-3 hits from anything (Or 1 hit from any real weapon) stacked with Nymphs having stuncode (That can stack apparently??? to form a sorta makeshift crit state) and a p. slow regeneration of health.

**Comment by Cnaym** [comment]
Your nerf has a critical error in that you can form a gestalt before reaching the nutrition level, you'll be missing an arm for example. As such I do not mind it much, just figured I'd let you know.
The Nymph HP should be more than a single hit by most weapons. They are still surviving in harsh environments, and not rats.

**Comment by ParadoxSpace** [comment]
There's an actual shitload of weapons that do under 25 damage. Rats have 5 health.
Nymphs have more health than just the one because once they die, they go to the next nymph from the split.

**Comment by Yonnimer** [comment]
A better solution would be to have freshly split nymphs to start with less health, or it scales based on biomass. This effects all diona nymphs, making them very easy to kill.  It becomes a lore issue when a dionae is forcefully split then immediately goes back to what they were doing. They are meant to act damaged, not the same.

**Comment by Chada-1** [comment]
> There's an actual shitload of weapons that do under 25 damage. Rats have 5 health.
> Nymphs have more health than just the one because once they die, they go to the next nymph from the split.

Rats are not expected to roleplay and are not selectively grown or whitelist locked, they're actually encouraged to run away at the first sight of Crew, have no mechanics relying on them, and are not a good comparison for nymphs in any way.
Nymphs are not always part of a gestalt.

**Comment by Cnaym** [comment]
> Rats are not expected to roleplay and are not selectively grown or whitelist locked,...
Wrong. Nymphs can grow into a full gestalt without whitelist. The system's broken, selectively grown also does not fit when you can always looc the gardener to get one.
Expected to roleplay does not protect you from those that do not do and since the mentality is that a typing indicator does not protect you from getting attacked, I will stick to the argument that this is not a balanced or well thought out change.
It's a nerf, without a good reason for why we need one.
Yonni had a good idea, this would force a fresh split swarm to run and hide. The thing is that they already have to do that if they wish to RP that traumatic event. This does not need a code change.

**Comment by Chada-1** [comment]
> > Wrong. Nymphs can grow into a full gestalt without whitelist. The system's broken, selectively grown also does not fit when you can always looc the gardener to get one.
This still sets them apart massively from a rat since there still has to be a conscious effort from Crew to have one exist, so they're not just things that'll overrun the Station and cause mayhem without someone at least enabling them to. That's the main difference there.
> > Expected to roleplay does not protect you from those that do not do and since the mentality is that a typing indicator does not protect you from getting attacked, I will stick to the argument that this is not a balanced or well thought out change.
You mean those that don't want to roleplay with the Nymph? That's true, but that's also why Nymphs if they're expected to roleplay should have much higher health than a rat and not be able to be killed in 2-3 hits/1 hit from most if not all real weapons. That's my point 👀

**Comment by Yonnimer** [comment]
An alternative is being discussed with the headdevs/maintainers.

**Comment by Yonnimer** [comment]
Something paradox and I found, there's currently a bug where nymphs are actually immortal. We're looking into getting it fixed.

**Comment by Sindorman** [comment]
> Something paradox and I found, there's currently a bug where nymphs are actually immortal. We're looking into getting it fixed.

I found same bug and fixed it. It mostly occurs when nymph is marked as internal to Diona, then its life is not processed, therefore the code that makes it die never is executed. If you PM me details on how you were able to reproduce it I can find exact location of problem and post a fix

**Comment by Yonnimer** [comment]
https://forums.aurorastation.org/topic/13937-unapologetic-diona-nerfs/

**Pull request merged**
