### PR TITLE
Removes Cloaks

### PR DESCRIPTION
**Pull request by Arrow768**
As promised by @skull132 in #5474: Here is the PR to remove the cloaks.

This just removes them from the loadout, so they can still be acquired via alternative ways.

https://forums.aurorastation.org/viewtopic.php?f=21&t=12208&p=108405

### CODE REVIEW

**Comment by skull132** [comment]
Here's the point about cloaks and other accessory shit. _There's a point at which something is too much._ And IMO that point is well reached when we start dressing up in garb which doesn't really fit well within the environment we're meant to represent. That being a closed, indoor facility.

While I understand that customization is a decent part of making your character, again, that has to be applied with actual reason. There's been PR upon PR of relatively acceptable fashion stuff which greatly enables said customization, so sniping out something more egregious than the rest isn't really an issue.

**Comment by shedya** [comment]
I suggest making cloaks available at the wardrobe in maintenance, and perhaps on the surface level something. An ideal solution, in my opinion, is to replace lockers on the surface with clothing vendors, and make the cloaks a premium items, making them uncommon and actually cool like they're supposed to be.

**Comment by MarinaGryphon** [comment]
Just increase the point cost to discourage people from selecting them. If you wear a cloak, you don't get to bring your lunchbox, special boots, prized necklace, trading cards, other trading cards, and Ian shirt, too.

**Comment by MarinaGryphon** [comment]
Also, is this an out of season April Fool's joke? I can't even imagine Skull saying "fashion has gone too far" with a straight face.

**Comment by ParadoxSpace** [comment]
Jackboot asked me to post the following, and I quote
"Department cloaks allow cultural and personal expression while the character still being immediately identifiable as to what their department is. The benefits of showing and not telling characters while also still showcasing visual department membership combine into a benefit.

They are also culturally present in several factions so their representation on station further reinforces the cosmopolitan nature of tau ceti.

As I told arrow, for safety security cloaks would be fine being gone but the other departments should continue to have them available for the cultures where they are present.

But the departmental colors to me shows a narrative of nt profiting off the fashion of the incoming cultures. "

I would also like to ask @skull132 if it'd be okay if instead of removing them, to fit the above I could make a PR to change the cloaks to have NT logos on them.

**Comment by OneOneThreeEight** [comment]
> There's a point at which something is too much. And IMO that point is well reached when we start dressing up in garb which doesn't really fit well within the environment we're meant to represent. That being a closed, indoor facility.

Yet with the NBT the idea of it being a 'closed, indoor facility' may not matter, depending on the turnout of how the environments are going to be in the future.

Likewise, I don't see the issue of cloaks, though. If people still wear uniforms with them I don't have an issue with them.

**Comment by ToasterStrudes** [comment]
The same could be said about a huge majority of the items in space station, like, why would my character need a sombrero, or chaps, cowboy boots, or anything of the likes. 

Its just something to make characters look cool and different, the game wouldn't be as interesting if we all just wore default clothes. Let us pizzazz things up with cloaks and stuff.

**Comment by BurgerLUA** [comment]
This might be snowflaky but I feel allowing some xenos to spawn with cloaks as a loadout item are appropriate. I can see Vaurca wearing them.

**Comment by MarinaGryphon** [comment]
I would be okay with this if we removed a majority of the other similar departmental items, as well as some plain silly things. Certain hats. The natural philosopher's wig. Chaps, cowboy boots, *ponchos.* Ponchos are effectively worse-looking cloaks, and departmental versions of those have existed since 2016.
Also, since it was stated that this is supposed to be a revert, that means it's on hold for at least a month. I think this should be tagged with "do not merge" as well as "requires feedback".

**Comment by LordFowl** [comment]
Cloaks were added in the September devmerge. The revert safety period has long ended.

**Comment by Kaedwuff** [comment]
This feels like something that should have a feedback thread, rather than just being something that Skull has decreed is going to happen.

This also doesn't provide any 'alternate ways' for cloaks to be acquired, it flat out removes them from the loadout with no recompensatory additions.  How are people supposed to get them if you remove them from the only reliable place to get them?

**Comment by ParadoxSpace** [comment]
Feedback thread soon, fellow stalker.

**Comment by Arrow768** [comment]
I do not appreciate the implications made by @MarinaGryphon especially after I mentioned in a discussion, in which they participated, that I did not put up a feedback topic for it, because I did not get around to it but will do so.

As these implications are baseless and attacking my person instead of arguing on the technical aspects of the PR the comment has been deleted.

**Comment by skull132** [comment]
PR to be merged while we clean up the rest of the fashion issues.

Reasons being:
* the sprites are not of good quality;
* they make you look like royalty and do not generally fit the work _aesthetic_.

**Comment by ParadoxSpace** [comment]
kms

**Pull request merged**
