### PR TITLE
Ports SStyping from Nebula.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
Credit to Spookerton as they are the original coder (to my knowledge).

- Added a new subsystem to handle speech bubbles.
- Fixed speech bubbles persisting when they shouldn't.
- Added different styles of speech bubbles for ghosts, animals, machines.
- Speech indicators now work with the command bar.

Additionally ports the set_invisibility observ.

### CODE REVIEW

**Review by alsoandanswer — APPROVED** [review]
Very nice.

**Review by RyverStyx — APPROVED** [review]

**Comment by remona-minett** [comment]
Based on what I saw in a round (cnd-aq0 if needed...) it seems like people generally thought that either a selection between "synthetic/organic typing indicator"s in the character setup, or "TTS only" be what shows the synthetic typing box, would be good. It looks like it reveals hidden shells or, really mostly, tends to affect anyone who simply doesn't sound 'robotic' as a synthetic.

**Comment by FlamingLily** [comment]
There was also the idea floated of custom typing indicators for each language and I think that could be an interesting way to add a little flavour, but until that point I think IPCs at a minimum shouldn't have the machine typing indicator. Cyborgs, AI, pAI, probably fine to have it, but IPCs are meant to be, in lore, more of a human analogue than any of the others and unless using TTS specifically, most people (especially shell players) would assume their voices to be indistinguishable from humans.

**Comment by NonQueueingMatt** [comment]
immagine
added a pref

**Review by Arrow768 — APPROVED** [review]

**Comment by remona-minett** [comment]
At a guess it looks like this makes typing indicators stuck on or off, the toggle doesn't function anymore. It worked the round before this was merged, and didn't work during the testmerge either. I forgot to mention it.

**Pull request merged**
