### PR TITLE
Clip-On Radios

### PR DESCRIPTION
**Pull request by 1Sparky1**
Adds Clip-On Radios, which can be equipped to both ear or wrist slots, always appearing on the body, clipped onto your uniform or jacket.

### CODE REVIEW

**Comment by 1Sparky1** [comment]
!review

**Comment by Greenjoe12345** [comment]
Will this need a database update as it's touching character save stuff?

**Comment by 1Sparky1** [comment]
> Will this need a database update as it's touching character save stuff?

I'm not 100% certain on this, so Devs will know better than me, but I don't think so. It just adds a new option to an existing field.

**Review by Arrow768 — APPROVED** [review]

**Comment by Arrow768** [comment]
> Will this need a database update as it's touching character save stuff?

Good catch, but no it didnt, because headset choice is saved in the [db field](https://github.com/Aurorastation/Aurora.3/blob/master/SQL/migrate-2023/V001__Schema_2023_08_16.sql#L381) `headset_choice`, which is a `TINYINT`.

The value of `OUTFIT_CLIPON`, which is within the [range of the datatype](https://mariadb.com/kb/en/tinyint/)

**Review by Geevies — APPROVED** [review]

**Pull request merged**
