### PR TITLE
Replaces the FR Hardsuits with Voidsuits

### PR DESCRIPTION
**Pull request by senorsapo**
feedback thread: https://forums.aurorastation.org/topic/19459-replaces-the-fr-hardsuits-with-voidsuits-feedback-thread
\-
As said in the title. I believe that this PR is fair due to powercreeping and balance concerns.
\-
*edited by SleepyGemmy @ 2023-11-11: added feedback thread link. removed mention of feedback thread being able to be created at request.*

### CODE REVIEW

**Comment by senorsapo** [comment]
!review

**Review by DreamySkrell — APPROVED** [review]
changes look fine

**Comment by bigbucceesfan96** [comment]
Considering the whole point of the hardsuit is to make an EVA rescue feasible, I don't really understand this change. Removing the rescue rig also removes all of the tools it provides to carry out that role without having to play a scavenger hunt and scoop up those pieces of kit around the ship at the start of every round.

**Comment by Eyeveri** [comment]
I'd like to see a feedback thread for this, as this is a pretty big change to the way FR is played.

**Review by FluffyGhoster — APPROVED** [review]
Code (or map in this case) looks fine

A feedback thread should be opened to discuss the merits and demerits of this balance change, given that hardsuits have modules to help with movement and rescue that are unavailable in softsuits; please, explain in said thread your reasoning for the suggested balance change

**Comment by Greenjoe12345** [comment]
Wouldn't this need a suit cycler so nonhuman FRs can get their suit changed, considering voidsuits do not autofit to species like hardsuits do?

**Review by alsoandanswer — APPROVED** [review]

**Review by DreamySkrell — DISMISSED** [review]
> Wouldn't this need a suit cycler so nonhuman FRs can get their suit changed, considering voidsuits do not autofit to species like hardsuits do?

actually yeah

**Comment by Greenjoe12345** [comment]
> > Wouldn't this need a suit cycler so nonhuman FRs can get their suit changed, considering voidsuits do not autofit to species like hardsuits do?
> 
> actually yeah

I also wonder if they should have jetpacks there or not, or just lose the ability for flight unless they get a jetpack from EVA.

**Comment by senorsapo** [comment]
@DreamySkrell I believe the changes stated are not needed, as a suit cycler already exists.

Capture

**Review by DreamySkrell — APPROVED** [review]
huh, I'm blind, I did not see the suit cycler

**Comment by NonQueueingMatt** [comment]
Not needed.

**Pull request closed without merging**
