### PR TITLE
Another small gravity update

### PR DESCRIPTION
**Pull request by Sindorman**
- Changes malf gravity malfunction ability to only work for a specific area in which AI eye is looking at.

- The ability now counts for people who have magboots on and will not affect them.

- AI core no longer falls if it is anchored. Meaning it won't get damage from its own ability

- Updated Malf manual to include new abilities and some old one too.

### CODE REVIEW

**Comment by Sindorman** [comment]
!review

**Comment by Kaedwuff** [comment]
Doesn't the warning mean that everyone will have a the time to lay down and thus avoid most if not all of the damage?

Or  does this not happen with the throw up and down ability?

**Comment by Sindorman** [comment]
The warning and time is intentional to let people still avoid it. However in your example people will receive damage. Laying down won't reduce is as the ability already counts them as laying down when used, hence why they receive moderate damage rather than breaking bones.

**Comment by Kaedwuff** [comment]
Because it at least floor them and maybe stun them briefly? If it doesn't deal that much damage then it has to do something to them like make them drop their weapons and let a borg drag them off or something.

**Comment by Sindorman** [comment]
Well, it makes your float for 3 seconds and then slams you on the ground dealing 30-60 brute depending on stuff. Plus it stuns you for a bit from fall as per usual fall mechanics and also drops stuff from your hands

**Pull request merged**
