### PR TITLE
Loadout QoL - unavailable items grayed out and at end of list, culture and origins under items

### PR DESCRIPTION
**Pull request by DreamySkrell**
image
image
image

changes:
  - rscadd: "Unavailable items in the loadout (restricted for jobs, origins, cultures, or factions) are grayed out and appear at the bottom/end of the list."
  - rscadd: "Culture and origin restrictions appear under items, same as job restrictions."

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!review

**Review by SleepyGemmy — COMMENTED** [review]
consider clarifying what the requirements/restrictions for items are.
e.g. `(Role: Janitor) (Faction: NanoTrasen) (Origin: Empire of Dominia)`

**Comment by DreamySkrell** [comment]
> consider clarifying what the requirements/restrictions for items are. e.g. `(Role: Janitor) (Faction: NanoTrasen) (Origin: Empire of Dominia)`

image
Done.

.


> remove the duplicate entries from items. i.e. 
> image

Ehh. I don't think it's really worth it. This is caused by different origins/cultures having the same names, like `culture/dominia` and `culture/dominian_unathi`.

To remove duplicates, would have to basically copy the list of origins/cultures on each item, to use only those whose names do not appear, or something like that - which means possible performance impact maybe, as this could be done for a lot of items potentially, but dunno. I could do this if it's really desired, but I'm not really feeling it personally.

**Review by SleepyGemmy — APPROVED** [review]
PR looks fine.

**Review by alsoandanswer — APPROVED** [review]
Impressive, very based.

**Pull request merged**
