### PR TITLE
adds new airlock and firedoor sounds

### PR DESCRIPTION
**Pull request by alsoandanswer**
ported from chompstation

also fixes the names of the airlocks because they were unnamed for some reason

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Review by NonQueueingMatt — COMMENTED** [review]
Some sounds don't fit and continue going even after the door is visibly closed, so it seems odd. Overall I think I like these sounds more, though. `sound/machines/airlock/vault1c.ogg`, `sound/machines/airlock/cmd3c.ogg`, `sound/machines/airlock/sci1c.ogg`.

I feel like `sound/machines/airlock/eng1o.ogg` and the associated close sound iare too intense for opening glass airlocks. If anything they should be reserved for engine room doors, or specifically non-glass doors.

 I also find it odd that the glass doors at the start of the bridge have a more intense sound, and visibly sound harder than the captain's door, despite being glass doors.

Cargo doors sound out of place. A bit too much for my tastes.

In comparison to these sounds the medical airlocks also seem out of place with how much less noisy they are, but I figure that's intentional. Not sure if I'm a fan of it or not, but I think I like it. 

All in all I'm not sure if having different sounds for every airlock is a good idea. I think this would be much better if we took the best sounds, put them on all the airlocks, and then specifically changed the sounds of important things like vault doors, EVA airlocks, blast doors, maintenance doors.

**Comment by alsoandanswer** [comment]
Whoops. Command glass airlocks were using vault sounds.

Still, I think different sounds for each department adds to immersion. We already have different ambience, and after a while the airlock sounds get a little samey and it kind of gets tuned out anyway

If you're still hesitant on putting them in, I suggest a test merge as a dip stick for the sounds - see how people like them.

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
I think we'll have to do away with departmental-airlock based sounds. Please standardize the sounds across all airlocks unless they clearly serve a different purpose (e.g maintenance, vault) or look very different.

**Comment by NonQueueingMatt** [comment]
Unfinished. Reopen when ready.

**Pull request closed without merging**
