### PR TITLE
Reduces the plasma cutter main rate

### PR DESCRIPTION
**Pull request by Alberyk**
What the title says, it was really high, having around 15% of instakilling someone on the first hit, if aiming at head, and 30% of chance of cutting a leg or arm at the first hit, this should reduce those chances. The main feature also takes in consideration the armor. So, plasma cutters are far more effective against less armored foes, limbs and xenos at all.

### CODE REVIEW

**Comment by OneOneThreeEight** [comment]
The maim rate seems to not check for armor, either.

**Comment by Arrow768** [comment]
I played around with the yesterday on my Testserver and it took usually 1-2 hits to remove a limb.

**Comment by Alberyk** [comment]
The other maim_rate sources will also be changed, which is only the anti material rifle bullet, it seems.

**Comment by Pacmandevil** [comment]
did someone say linear regression

**Comment by Alberyk** [comment]
The maim calculation now takes in consideration the armor.

**Pull request merged**
