### PR TITLE
Merges Physician and Surgeon Into One Role

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR merges physician and surgeon into one role.

feedback thread:
https://forums.aurorastation.org/topic/16983-thou-not-special-anymore-medical-job-changes/

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Comment by EmperorJayJay** [comment]
Gem Presents:

No More Surgeons

**Comment by Roostercat12** [comment]
This should have a feedback thread first, given it can mess with some characters a lot.

**Comment by courierbravo** [comment]
I would like for there to be a feedback thread for this. I have a lot to say, and github is not the place to say it.

**Comment by alsoandanswer** [comment]
https://forums.aurorastation.org/topic/16983-thou-not-special-anymore-medical-job-changes/

Thread here. It's kind of old, but relevant.

**Comment by Arrow768** [comment]
This has been polled and discussed by the maintainers.
The option to merge the jobs did not have a majority in the votes and the maintainer did not decide to go forward with the merge regardless.
Therefore the PR is being closed.

**Pull request closed without merging**
