### PR TITLE
Fixes Bag Masks

### LINKED ISSUE #14980: Bags Strap Issues
- "normal" straps are 2 pixels thick instead of 1 pixel thick (masking issue?).
- "hidden" straps still show the shoulderpiece (i.e. where the strap goes over the shoulder).

### PR DESCRIPTION
**Pull request by SleepyGemmy**
title.
fixes #14980.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!bugfix

**Comment by SleepyGemmy** [comment]
!review

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
the satchel, duffel and courier bag are **supposed** to have 2 wide pixel straps for the thin version, just like their old counterparts.

**Comment by SleepyGemmy** [comment]
add a 2-pixel strap then. out of scope for this PR.

**Comment by SleepyGemmy** [comment]
> the satchel, duffel and courier bag are **supposed** to have 2 wide pixel straps for the thin version, just like their old counterparts.

image
image

**Comment by alsoandanswer** [comment]
*courier bag, not satchel my bad

also you forgot to define OUTFIT_THIN

**Comment by alsoandanswer** [comment]
Thin and normal use the same masks still.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
