### PR TITLE
[WIP] Adds a spawnable Rat King

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Overview
Spawning as a mouse gives a 25% chance to spawn as a rat king. Only 1 rat king can spawn per round.

## WIP
Rat king needs to be tested to see if their abilities still work.

### CODE REVIEW

**Comment by Chada-1** [comment]
25% is far too much, you can spawn as a mouse every 5 minutes if you ghost. That'll lead to Ratking in the first 30 minutes for a single mouser to potentially in the first 10 minutes for multiple.

**Comment by Pacmandevil** [comment]
I'd make it a 7% chance per client on roundstart or something instead of per mouse spawn

**Comment by BurgerLUA** [comment]
Okay how is this.
25% chance for it to be able to be in the round in the first place.
10% chance per mouse spawn.

**Comment by Chada-1** [comment]
That works but personally I think that may even be a tad too rare. Maybe give it 50% with a 10% per mouse?

**Comment by SonicGotNuked** [comment]
I think you should make a suggestion thread for something rather controversial that could be added. It would avoid cluttering the github.

**Comment by BurgerLUA** [comment]
closing this because I'm not interested in it that much and neither is the community

**Pull request closed without merging**
