### PR TITLE
Manifest UI size and format improvement

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Made the manifest UI bigger and the table elements a little better aligned.

image

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!review

**Comment by alsoandanswer** [comment]
Honestly, if the jobs are going to be right-aligned, the names should be left-aligned.

**Comment by FluffyGhoster** [comment]
> Honestly, if the jobs are going to be right-aligned, the names should be left-aligned.

I tried with left aligned too, but it seemed worse to me, leaving a column of space in between, so i moved it to center-ish.

**Comment by FluffyGhoster** [comment]
image
Adjusted the background of the sections a bit

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
