### PR TITLE
Adds a new robolimb.

### PR DESCRIPTION
**Pull request by ParadoxSpace**
Adds the faux-wood Morgan Black prosthesis.
image

image

image

image

image

### CODE REVIEW

**Comment by skull132** [comment]
Would these be common access to all, or adminspawn only?

**Comment by ParadoxSpace** [comment]
Common access.

**Comment by skull132** [comment]
Then I have one question: literally why. Why would any self-respecting cybernetics corporation do this.

**Comment by ParadoxSpace** [comment]
Either,
A) To create a more affordable cyberlimb (for people in need, likely Frontiersmen), that while still possessing the utility of a prosthetic, lacks such expensive design features as 
A1) The silver and status lights of the Bishop limbs.
A2) The expensive high-powered servos and heavy armor plating of Industrial limbs.
A3) The graphene nanoweave of Zeng-Hu limbs.
A4) The expensive synthskin of the Shell limbs.


Or
B) To create a luxury-looking cyberlimb that may or may not be expensive. Wood is a common luxury symbol irl. Cheap cars even use plastic disguised as wood. https://en.wikipedia.org/wiki/Morgan_Motor_Company
See the Morgan, which have a steel chassis, but an ash wood frame.

These aren't real wood solely because carving, shaping, and polishing the wood would be useless when the heavy stresses a limb would go through would just warp them with age, and make them look ugly later.

**Comment by SleepyWolfe** [comment]
I, for one, have plenty of low-income characters from under-developed worlds that could definitely use these. hell yeah.

**Comment by skull132** [comment]
Surely we can think of a more modern, practical design for these legs. Should also be considered that wood is _not_ a cheap material. Plastics and aluminium are. And both can easily be forged into more complex shapes which are more ergonomic than a peg leg.

**Comment by ParadoxSpace** [comment]
That's why it isn't wood. It's faux-wood. Y'know, like the plastic wood used in cars?

**Comment by LordFowl** [comment]
Not a big fan. As the PR description indicates quite strongly, this is just a pirate joke. It's time to cut back on the items that are just jokes for the sake of making jokes.

**Comment by ParadoxSpace** [comment]
It is not just a pirate joke.

**Comment by dragoslava** [comment]
https://d3h6k4kfl8m9p0.cloudfront.net/uploads/2012/10/Untitled-21.jpg

I believe he is meaning for it to look more like this, which is decently acceptable as there are chars who are opposed to cybernetics for personal views (IE some unthai)

**Comment by ParadoxSpace** [comment]
I have updated the PR description to be less meme.

**Comment by skull132** [comment]
Updating the description doesn't do anything to solve my qualms. Even if it were faux-wood, it would still be more expensive than just using aluminium or a plastic.

Why not make it more like a running blade prosthetic? It'll look like it actually fits the setting properly, and will remain (relatively) cheap to manufacture, as opposed to fully articulated ones.

**Comment by ParadoxSpace** [comment]
We have a running blade prosthetic.
And as I said, it's a plastic. A plastic disguised as a wood. Like the plastic in my minivan right now that is disguised as a wood.

**Comment by VTCobaltblood** [comment]
I don't see why this couldn't be a religious item originally manufactured by and for unathi, and then spread over to Dominians, but JB's input is required.

**Comment by OneOneThreeEight** [comment]
The Zeng-Hu model prosthetics have running-blade legs already.

**Comment by VTCobaltblood** [comment]
Jackboot says wood prosthetics should only be in NBT. So this can be closed. @skull132

**Comment by skull132** [comment]
@ParadoxSpace is this your final offer for this PR, can it be closed or will you be making adjustments?

**Comment by ParadoxSpace** [comment]
If you want, I could make it made of aluminum.

**Comment by ben10083** [comment]
Is this still active or?

**Comment by Sindorman** [comment]
Open it again when it is ready

**Pull request closed without merging**
