### PR TITLE
Idris caps can now be flipped

### PR DESCRIPTION
**Pull request by flpfs**
When flipped they didn't show a flipped in-hand or mob sprite, now they do.

### CODE REVIEW

**Comment by flpfs** [comment]
!bugfix
!review

**Comment by flpfs** [comment]
!bugfix

**Comment by alsoandanswer** [comment]
https://github.com/Aurorastation/Aurora.3/pull/10123

Addressed here already

**Comment by NonQueueingMatt** [comment]
Depreciated.

**Pull request closed without merging**
