### PR TITLE
increase baton

### PR DESCRIPTION
**Pull request by OneOneThreeEight**
Buffs telebaton to original values. Tested already: it works well enough.

### CODE REVIEW

**Comment by NanakoAC** [comment]
why didn't you add the disarming things too? Legs only seems a bit limiting.

Also, weaken is in whole seconds, thats a 10 second stun, which seems a bit much.

**Comment by OneOneThreeEight** [comment]
Re: disarming, because the code for it is a mess and instantly disarming an item out of someone's hand for minimal risk is cheesy. It would effectively make telescopic baton users dominate other users of CQC weapons, such as those with stun batons or e-swords. There's very few sources of hand armor, as opposed to, say, legs, chest, head, lower body. It's committed out just to show the baseline of the original.

Also, weird, thought I lowered that to 5. I can fix that.

**Comment by NanakoAC** [comment]
You do realise that Weaken knocks someone over, right? And knocking someone over causes them to drop everything they're holding.
If you're allowing that, allowing disarming too is far from cheesy, and would make a lot of sense

I don't see any problem with dominating gun users in melee, if they're bad enough to let you get close.

**Comment by OneOneThreeEight** [comment]
"There's very few sources of hand armor,"

enough said

**Comment by Arrow768** [comment]
No changelog present. DNM until fixed

**Comment by OneOneThreeEight** [comment]
apparently my yml needed to be included in the initial commit to start with, this is aggravating.

**Comment by LordFowl** [comment]
You can make a new commit to this exact same repository (patch-1) containing only your changelog .yml, and it will be included in the PR.

**Comment by OneOneThreeEight** [comment]
fixed this shit @Arrow768

**Comment by OneOneThreeEight** [comment]
@skull132 review please

**Comment by skull132** [comment]
I will whenever I review the others as well. Usually around Thursday/Friday.

**Comment by OneOneThreeEight** [comment]
:ok_hand:

**Comment by NanakoAC** [comment]
this has been sitting here for a long time

**Comment by OneOneThreeEight** [comment]
for about over a month now, this has been sitting.

**Pull request merged**
