### PR TITLE
Re-adds the maidbot sprite.

### PR DESCRIPTION
**Pull request by MarinaGryphon**
* Re-enables the maidbot sprite for service module cyborgs.
* We're mature enough to have straight-faced conversations about poop mechanics, we can handle maidbots.
* Also, Abo requested it back or something. 😜

### CODE REVIEW

**Comment by Lohikar** [comment]
Ha ha.

**Comment by Pacmandevil** [comment]
hahah

**Comment by Pacmandevil** [comment]
Except poop actually added something that was at least vaguely justifiable

**Comment by MarinaGryphon** [comment]
are you actually serious right now

**Comment by Pacmandevil** [comment]
I have never been more serious in my life

**Comment by Lohikar** [comment]
Waste management actually adds something other than memes.

**Comment by MarinaGryphon** [comment]
ALSO JUST TO MAKE IT CLEAR I'M NOT RESIGNING BECAUSE OF THIS, THIS WAS MEANT AS A MEME

**Pull request closed without merging**
