### PR TITLE
Do You Like Fishsticks?

### PR DESCRIPTION
**Pull request by Crosarius**
I added non-toxic fish fillets so that races other than Unathi can eat seafood. Recipes are compatible with both carp fillets and fish fillets. Bear in mind that you can still use carp fillets to cook those same dishes, and ones using carp will still be poisonous!

There is no visible distinction between fish dishes that have been made with fish fillets, and those made with carp fillets, so watch out!

I also added 7 fish fillets to the freezer box in the kitchen freezer. I would also like to add a fish-fillet crate to the cargo ordering database, but from my understanding that isn't something that I have the power to do.

Fish fingers and fish and chips are now made in the deep fryer. The recipe for fish and chips has not been changed, however fish fingers now requires just a single battered fish piece, instead of egg and flour etc.

**Update**
Codewise, what I've done is I have added a snack type called fish, which contains both carpmeat and fish fillets, and modified all fish related recipes to require "fish," accepting either one of these recipes.

### CODE REVIEW

**Comment by Crosarius** [comment]
!review

**Comment by Crosarius** [comment]
Travis likes fishsticks!

**Comment by alsoandanswer** [comment]
hm.
how about two different food items. one that uses carp in it's name and fish in the other.

e.g. carp burger is toxic variant, fish burger is non-toxic.
might as well. you're already doubling the recipes anyway.

**Comment by Crosarius** [comment]
> hm.
> how about two different food items. one that uses carp in it's name and fish in the other.
> 
> e.g. carp burger is toxic variant, fish burger is non-toxic.
> might as well. you're already doubling the recipes anyway.

I'm only doubling the recipes. Doing what you suggest would mean doubling the food item results in food/snacks. There's no reason to have duplicates of each meal when the reagent carryover handles the toxicity on its own.

**Comment by alsoandanswer** [comment]
ahhh. ok then.

was a little confusing with the "however" in
>They will both result in the same food item, however because of reagent transfer in the recipe code, the carp version of the recipe will include carp toxin.

having carp and fish being repeated so many times has turned my brain to mush.

**Comment by Crosarius** [comment]
wait i just had a big brain idea hold on

**Comment by Crosarius** [comment]
I have eliminated all of the superfluous duplicated recipes by taking a leaf out of the meat book, and turning fish into its own type. These recipes just want "fish", which is satisfied by either carp fillets or fish fillets. The end result works great. This was the elegant solution that escaped my grasp at first. I made sure to run this, made sure to tidy up any references to the old location of carpmeat in snacks, what I'd done in the biogenerator, and also updated my map so that it wasn't referencing the old fish fillets that I'd put in the freezer. 

It's ready.

**Comment by Crosarius** [comment]
I have further streamlined my code by moving fish fingers to the deep fryer, and changing the recipe to 1 piece of battered fish. I also moved the fish & chips recipe to the fryer as well, but the ingredients remain the same.

**Pull request merged**
