### PR TITLE
Holodecks with random programs

### PR DESCRIPTION
**Pull request by DreamySkrell**
changes:
  - tweak: "If at least two engineers are present, Horizon's holodecks load random programs 5 minutes into the round."

Why? Currently they start just kinda sad and empty. We have lots of pretty holodeck programs, and I'm sure there are people who aren't even aware they exit, and don't care to check. I like to think this change would maybe occasionally pique the interest of passerby's or whatever to check out the programs.

Also it just looks nice as decoration, even if no one's using the holodecks.

They load only if at least two engineers are present, so they don't drain power on deadpop, where engines may not be set up yet (or ever).

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!review

**Review by Arrow768 — DISMISSED** [review]
Make sure to check if a program is loaded first

**Comment by SleepyGemmy** [comment]
don't the holodecks pull quite a bit of power when in use?

**Comment by DreamySkrell** [comment]
> Make sure to check if a program is loaded first

addressed in most recent commit

**Review by NonQueueingMatt — APPROVED** [review]

**Review by SleepyGemmy — APPROVED** [review]

**Pull request merged**
