### PR TITLE
[broken] Adds a ladder between bridge maint and bar maint

### PR DESCRIPTION
**Pull request by DreamySkrell**
image

Adds a ladder between Horizon's top deck bridge maint and middle deck bar maint

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!review

**Review by SleepyGemmy — APPROVED** [review]
mapping looks fine.

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by DreamySkrell** [comment]
Merge conflict resolved.

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
dirty PR. check the "Files Changed" tab for further information.

**Comment by DreamySkrell** [comment]
holy shit

**Comment by DreamySkrell** [comment]
Closing because the merge got broken or something. Remade the PR in #14975.

**Pull request closed without merging**
