### PR TITLE
Lowers giant spider health

### PR DESCRIPTION
**Pull request by Yonnimer**
Changes brown spider health to 80, from 200.

For reference, hunter(black spiders) have 120, white(nurses) have 40.

### CODE REVIEW

**Comment by Yonnimer** [comment]
!review

**Comment by Yonnimer** [comment]
I assumed hunters were meant to be the tanky spiders, not the brown spiders @NonQueueingMatt 

If the brown ones are meant to be the tanks then i'll close this.

**Comment by NonQueueingMatt** [comment]
They are

**Comment by Yonnimer** [comment]
👍

**Pull request closed without merging**
