### PR TITLE
AI shell no longer shows up on end of round text.

### LINKED ISSUE #13191: AI Shell appears on end of round text
Isn't a player so probably shouldn't appear.

image

### PR DESCRIPTION
**Pull request by Afya212**
Title
Fixes #13191

### CODE REVIEW

**Comment by Afya212** [comment]
!bugfix

**Comment by Afya212** [comment]
!review

**Review by Ben10083 — COMMENTED** [review]
ditto.

**Review by NonQueueingMatt — APPROVED** [review]
A bit hardcoded, but this isn't terrible.

**Pull request merged**
