### PR TITLE
Chem Bottles, Beakers and Medcup Resprites

### PR DESCRIPTION
**Pull request by VisVirific**
* Removes the Eris-style Chemical Bottles, Beakers (normal, large, cryostasis, and bluespace), and Medcup sprites
* Replaces them with a new style of Chemical Bottles, Beakers (etc), and Medcup sprites that fits Aurora more
* Tweaks the Vial sprite to be more consistent with the new sprites
* Moves the Medcup code from ``.../food/drinks.dm`` to ``.../glass.dm``, being repathed to ``.../glass/beaker/medcup``

**Beaker Sprites** (05/05/2022 Edit: Outdated. See below for updated previews)

Top Row- Classic | Middle Row- Aurora | Bottom Row- Eris

**Beaker Lids** (05/05/2022 Edit: Outdated. See below for updated previews)

**Chemical Bottle Sprites** (05/05/2022 Edit: Outdated. See below for updated previews)

Top Row- Classic | Middle Row- Aurora | Bottom Row- Eris
The new mini bottle and the 4th bottle (from left to right) have an invisible outline for convenience

**Chemical Bottles Lids** (05/05/2022 Edit: Outdated. See below for updated previews)

**In-Game Preview** (05/05/2022 Edit: Outdated. See below for updated previews)

### CODE REVIEW

**Comment by VisVirific** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by VisVirific** [comment]
**Minor Bottle Tweaks**

**Review by SleepyGemmy — APPROVED** [review]
code looks fine as far as i can see.

**Comment by Doxxmedearly** [comment]
By changing the medcup's path to glass/beaker, you also allow it to have a lid put in it. Either this is going to need a lid icon or you'll need to make it so it can't have a lid put on it (Which, given the purpose of a med cup, is probably the better solution). Probably best to just make it return on attack_self(). 

Also you'll want to make the volume 15 again or document that you're increasing the volume of the med cup in the changelog, too.

**Comment by VisVirific** [comment]
> By changing the medcup's path to glass/beaker, you also allow it to have a lid put in it. Either this is going to need a lid icon or you'll need to make it so it can't have a lid put on it (Which, given the purpose of a med cup, is probably the better solution). Probably best to just make it return on attack_self().

Got it! I do not remember why I decided spriting a lid and label to a med cup to be the best option instead of just return on ``attack_self()``

> Also you'll want to make the volume 15 again or document that you're increasing the volume of the med cup in the changelog, too.

SHIT I FORGOT TO CHANGE BACK TO 15 FUCK (put in 20 to make sure the reagent filling was doing things correctly)

**Review by Doxxmedearly — APPROVED** [review]
All good! Love the sprites, nice work as always.

**Review by alsoandanswer — COMMENTED** [review]
Some problems I have with the beakers, still

- beakers and medicine cup have had their "lips" removed, please add them back
- medicine cup no longer looks like a medicine cup, it looks like a tinier beaker now.
- cryostasis beaker has been changed back to old design - the change to make it look like a small beaker was entirely intentional. it's to improve readability - it has the same capacity as a small beaker.
- beakers have always been blue on aurora, and they should remain that way in order to not blend in with the already grey tables.
- reagents in the bottles are pillowshaded.

I'm trying to move away from the "old" Aurora style (which isn't even a style, it's just the un-updated SS13 baseline sprites). So these kinds of Eris/Bay style sprites will not fit in at first, but eventually will once enough changes have been made.

**Comment by VisVirific** [comment]
@alsoandanswer 
Before I address any of those points, I need you to answer me this:

Why didn't you bring these up through DMs like when you had mentioned the thing with the chem bottles the day I put up the PR, or when I finally managed to tweak them?

**Comment by VisVirific** [comment]
@alsoandanswer 
Please answer my question before I can address any of the points.
>Why didn't you bring these up through DMs like when you had mentioned the thing with the chem bottles the day I put up the PR, or when I finally managed to tweak them?

**Comment by alsoandanswer** [comment]
Sorry, should've done this from the start. Just wanted to make it so other devs could understand what I was requesting as well.

**Comment by VisVirific** [comment]
> Sorry, should've done this from the start. Just wanted to make it so other devs could understand what I was requesting as well.

Thank you for answering. I'll address the points.

>* beakers and medicine cup have had their "lips" removed, please add them back

I'll see what I can do about the **beakers**, while the original medicine cup (which was also unique to Aurora) didn't have them. Considering it is supposed to look like a small cup, I really don't think the lips would fit

>* medicine cup no longer looks like a medicine cup, it looks like a tinier beaker now.

It's because it follows the color scheme of the beakers with the measurement markers on the left. If I can get the lips for the beakers done and readjust the color palette, it'll look more distinct while not completely out of place within Medical.

>* cryostasis beaker has been changed back to old design - the change to make it look like a small beaker was entirely intentional. it's to improve readability - it has the same capacity as a small beaker.

Same capacity and yet it's hard to tell how much of something it has, which could be argued to have the same problem as the original Cryostasis Beaker where you had no real way of seeing how much it had. Yes, I know it has reagent filling sprites for when it's 80% to 100% full, but it's not much of an improvement.

Additionally making it look identical as a beaker shape wise detracts from how it unique it looked as a more technological piece of equipment than generic glassware.

But if you're absolutely sure about this, then I can refit it into beaker, but metal with a looping animation to keep consistency, as it is apparently the intention.

>* beakers have always been blue on aurora, and they should remain that way in order to not blend in with the already grey tables.

I'll see what I can do about the color palette.

>* reagents in the bottles are pillowshaded.

I'll see about cleaning the reagent filling color. I had done it like this to try giving it more depth and help emphasize the shape, while not intruding on the outlines of the bottles themselves (like how the old reagent filling for the bottles did. Only inside, no touching the outlines).

**Comment by VisVirific** [comment]
Just a heads up. My laptop's been doing weird shit again. I've managed to make some of the adjustments after fighting my laptop with tooth and nail, but progress is still going to be really slow until I figure out what's wrong with it this time

**Readjusted colors for Beakers (normal and large plus the "lips") and Medicine Cup**

**Review by JohnWildkins — APPROVED** [review]
does a little trolling (green checkmark)

**Pull request merged**
