### PR TITLE
'Borg AI law phrasing fixes.

### PR DESCRIPTION
**Pull request by Chada-1**
Changed serve and protect a little bit. This should make it more clear and it removes the distinction between regular Crew and Company Contractors

### CODE REVIEW

**Comment by Chada-1** [comment]
!review

**Comment by Chada-1** [comment]
!bugfix

**Comment by Kaedwuff** [comment]
I don't understand what the difference between these two phrasings is. Staff and assigned crew mean exactly the same thing, when just uses more words. Anything about contractors.

**Comment by Chada-1** [comment]
> I don't understand what the difference between these two phrasings is. Staff and assigned crew mean exactly the same thing, when just uses more words. Anything about contractors.

Before, crew and 'NanoTrasen Staff' created an intentional separation between general non-NT staff and NT staff, I've been convinced to remove that element of the rework, and so I'm just altering it back to work exactly how it used to with more clear phrasing.

**Pull request merged**
