### PR TITLE
Allows Maintenance Drones to pull disposal pipes.

### PR DESCRIPTION
**Pull request by Baa14453**
### This change intends to make Maintenance Drones more practical, despite breaking the laws of physics
Maintenance Drones are unable to pull disposal pipe.
This is because the pipes are size 10, and drones cannot pull anything larger than themselves, (they're size 3).

Law-wise it makes no sense to change this, however it is impractical and makes it impossible for maintenance drones to repair Disposal Pipe, which is one of the most annoying breakages on station, spreading litter in the crew's departments, engineers have to drag over the whole dispensary etc.

So, why not just ignore the laws of physics and let Maintenance Drones pull the pipe that's almost four times as large as they are?

If you look at the current code, it looks like someone's already tried to https://github.com/Aurorastation/Aurora.3/blob/master/code/modules/mob/living/silicon/robot/drone/drone.dm#L330
This doesn't work though because when it calls the parent proc a further check for size is done.

In that sense this is technically a bugfix >.>

Credit to @Sindorman for basically writing the new Proc for me.

See PR #6303 for related tales.

If this doesn't make it through I'll make another pull request to remove this proc altogether, because it's not doing anything.

### CODE REVIEW

**Comment by Baa14453** [comment]
> This still shouldnt really be a thing as it makes little sense. Borgs can or should be the ones doing it not drones. With this logic of it being convenient, we should let people move mechs or other large immobile objects

I believe the practicalities of moving disposal pipe outweighs the gravitational massacre here.

Allowing someone to move a mech would affect their usage, negating their abilities. Mechs are distinctly designed to be big machines for heavy lifting, combat, or other arduous tasks. They're visibly large and bulky machines, you can even hear them moving from a distance. If a human could push a mech out of the way it would tragically clash with their purpose, and be very immersion breaking.

I don't consider disposal pipe with the same regard; their size is not so relevant to their purpose. It's true, in-game they are probably quite large (being able to fit an entire person inside), but I've personally never considered them as such. It's just a disposal pipe, once it's back installed and working under the floor it will be hidden away, and I don't have to think about it further. Maybe I won't even mind if the drone steals some of my metal sheets on the way out.
If I saw a drone dragging a disposal pipe it wouldn't bother me, I'd only be grateful that the chemist's empty Space Drugs bottles wouldn't keep hitting me on the head.

Cyborgs can already move and install disposal pipe, I'm not negating that fact and I think they do a great job. However, cyborgs have many responsibilities, perhaps the HOP's ID Modification computer has exploded and damaged the disposal pipe, it's causing all sorts of issues that really ruins the janitors day. There is possibly an engineering cyborg rolling around, but it's busy reinforcing the AI's core because an Atmospheric Technician with an axe is having too much fun.

Repair and improvement is the single job of a maintenance drone, but it's unable to complete it's task, the wooden flooring, windows, computer and cabling is all back but it can't fix that pipe, it has to leave the floor exposed, the job unfinished, hoping someone bigger and more time on their hands can hobble their way over and seal the deal.

**Comment by Baa14453** [comment]
!review

**Comment by alsoandanswer** [comment]
Suspension of disbelief : It makes sense for a drone to be pulling disposals pipes. 
Even if it's rolling it around ala flintstones style. 

Gameplay : I don't think any major grief can happen. I'm pretty sure anything stupid will be stopped by an admin. Other than giving engies less to do. 

Honestly, just give the players more credit for their intelligence. I barely see drones anyway.

**Comment by Sindorman** [comment]
This obviously needs a feedback thread. Please do not comment here unless it is about code.

@Baa14453 please make a thread in Projects subforum and post a link to it here.

**Comment by HeyBanditoz** [comment]
Why is the subjective opinion of a maintainer a blocking code review?

**Comment by Baa14453** [comment]
Thread here https://forums.aurorastation.org/topic/11865-allow-maintenance-drones-to-pull-disposal-pipe/

**Comment by Baa14453** [comment]
Thread here: https://forums.aurorastation.org/topic/11865-allow-maintenance-drones-to-pull-disposal-pipe/
I put it in the wrong place though, so it might get moved, not sure if that will break the URL but I'll check later.

**Comment by skull132** [comment]
> Why is the subjective opinion of a maintainer a blocking code review?

1. Not a maintainer.
2. Because it is easier for maintainers to make note of blocking reviews than a trail of comments.

**Comment by MarinaGryphon** [comment]
I wasn't aware we were allowed to leave subjective feedback reviews as blocking changes? I'll do so in the future.

**Comment by SoundScopes** [comment]
Add /obj/item/pipe to the pull_list as some of the pipes are listed as size 4

**Comment by Baa14453** [comment]
:tada:

**Pull request merged**
