### PR TITLE
Removal of Sovl: Moves k'ois bars to the Zo'ra Soda machine

### PR DESCRIPTION
**Pull request by feartheblackout**
Was the survival of your new players worth it, chat?

Requires approval/feedback from Vaurca lore. @desvenlafaxine

### CODE REVIEW

**Comment by feartheblackout** [comment]
!review

**Comment by DreamySkrell** [comment]
I think it's fine as currently

**Comment by Stev-the-third** [comment]
This seems reasonable to me? The idea of having noob-traps because it's "funny" is kinda strange.

**Comment by desvenlafaxine** [comment]
I don't really agree because the k'ois bars aren't made by Zo'ra Soda and the bars themselves are filtered. There's a hacked vending machine item that has non-filtered k'ois bars, but the bars from the machine shouldn't kill you or give you mycosis. Unless they have phoron for some reason.

**Comment by lavillastrangiato** [comment]
image

**Comment by Sniblet** [comment]
Vaurca lore forgets that k'ois bars say they have bonus phoron injected into them in their description :pensive:
Filtered k'ois bars have enough phoron to kill easily. Organic k'ois bars will kill you with phoron before they kill you with k'ois. No k'ois food is safe to eat because phoron is bad for you.

**Comment by CyberSpyXD** [comment]
The Zo'ra soda machine has always had the misconception spread about it that you'll die if you buy anything from it. I think actually having an item in it that can hurt people isn't the best idea, although as of now the lore doesn't really fit for the bars to be in it anyway.

The filtered bars do still kill people without medical treatment. That said, the organic bars are very devastating due to the actual pure kois in it.

**Pull request closed without merging**
