### PR TITLE
Added the ability for Science to print DNA and wireless-controlled firing pins

### PR DESCRIPTION
**Pull request by FluffyGhoster**
DMDoc'd the firing pin code, some cleanups.
Added the ability for Science to print DNA and wireless-controlled firing pins.
Removed the clown firing pin.

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!review

**Review by DreamySkrell — APPROVED** [review]

**Comment by Arrow768** [comment]
Not sure why this should be testmerged

**Comment by Arrow768** [comment]
Also MD as the ability to print firing pins was intentionally not given to science due to them printing large amounts of weapons before the introduction of firing pins

**Comment by FluffyGhoster** [comment]
> Not sure why this should be testmerged
> Also MD as the ability to print firing pins was intentionally not given to science due to them printing large amounts of weapons before the introduction of firing pins

It's testmerged alongside the removal of the crew armory so they can supply the crew with weapons, in lieu of the crew armory, when the situation calls for it

**Review by Geevies — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
Pins are available via Operations and we prefer to keep it that way. Pins that only work in science exist for testing.

**Pull request closed without merging**
