### PR TITLE
adds more barsigns

### PR DESCRIPTION
**Pull request by ParadoxSpace**
The Wretched Hive, Maid Cafe, The Lightbulb, Cyber Sylph, A Modern & Progressive Tavern, Vlad's Salad Bar, Famous Dan's Bar & Grill, Blue Oyster, Prole's Preferred, Bar of Broken Heros, The Social Lubricator, The Chem Lab, The Old Cock Inn, Slippery Shots, The Hive and The Nest.

some images. i cannot add gifs for some reason.

image

image

image

### CODE REVIEW

**Comment by VTCobaltblood** [comment]
Remove the maid, sylph and progressive. Maid is a meme, sylph is way too visually striking, progressive doesn't fit the setting (2460, hello?).

**Comment by ParadoxSpace** [comment]
no, barsigns are meant to be visually distinctive, and please stop memeposting in my pr.

**Comment by ParadoxSpace** [comment]
why remove the maid cafe?

**Comment by Arrow768** [comment]
The slyph will go in on a provisional basis.
I´ll need to see how it looks ingame (As the provided is not sufficient for that)

**Pull request merged**
