### PR TITLE
AI Internal Computing Device access.

### PR DESCRIPTION
**Pull request by Magisterium2022**
Added AI Internal Computing Device access to a number of programs, such as the Command and Control program, which it was previously unable to interface with.

### CODE REVIEW

**Comment by Magisterium2022** [comment]
!review

**Comment by FluffyGhoster** [comment]
MD because I don't think the AI should have access to any of those programs, besides maybe the docking and teleporter one

**Review by FluffyGhoster — APPROVED** [review]
Code is fine however

**Review by Geevies — APPROVED** [review]

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
Issues we have with this PR:

1. The account database probably can't even be used by the AI due to it needing an ID card inserted.
2. Same goes for the ID card changing program - how is that one supposed to work?

**Pull request closed without merging**
