### PR TITLE
[READY FOR REVIEW] Deletes every instance of /weapon AND compiles!

### PR DESCRIPTION
**Pull request by LordFowl**
The rise of the machines is upon us. Automation reigns supreme.

To-do

- [x] Everything - subtypesof(/weapon)

### CODE REVIEW

**Comment by Arrow768** [comment]
It might compile, but it conflicts

**Comment by LordFowl** [comment]
Ah, but that is where you are wrong young grasshopper! Now featuring conflict-free merging!

**Comment by Pacmandevil** [comment]
does not compile

**Comment by Arrow768** [comment]
Well yes, now its conflict free. But you have fake news in your title. Its not compling.

**Comment by LordFowl** [comment]
Pacmandevil broke into my house and inserted a worm into my servers with the help of the arch-spy Nanako. I take no fault for the errors committed today.

**Comment by Pacmandevil** [comment]
fails travis.

**Comment by LordFowl** [comment]
Do not befoul my PR with your inaccurate assumptions, foolish maintainer-kin. This PR compiles perfectly.
It just runtimes a little.

**Comment by Pacmandevil** [comment]
PR completely disregarded due to the shameful act of thumbs-upping your own PR

**Comment by Pacmandevil** [comment]
conflicts.

**Comment by LordFowl** [comment]
I blame github.

**Pull request closed without merging**
