### PR TITLE
fixes #9758, #9684, #7803

### LINKED ISSUE #7803: Robots become permanently confused when blasted by psionics
Due to robots not processing confusion like other mobs.

### LINKED ISSUE #9684: Beepksy Smash is now Ethanol
Title is what it is, tried to make the drink but it just makes pure Ethanol so I think one of the two needs to change in order to fix this, used so much iron just to realise I couldn't make it cause it always made Ethanol...

### LINKED ISSUE #9758: Detective 9mm Magazine
The Detective's flash 9mm magazines are written as (9mm) instead of (9mm Flash), which can lead to some confusion.

### PR DESCRIPTION
**Pull request by MarinaGryphon**
* Fixes #9758 
* Fixes #9684; mispathed, oops
* Fixes #7803 by not adding confusion to synthetics hit by blindstrike.

### CODE REVIEW

**Comment by MarinaGryphon** [comment]
!bugfix

**Comment by MarinaGryphon** [comment]
!review

**Review by mikomyazaki — APPROVED** [review]

**Comment by mikomyazaki** [comment]
Needs a changelog though 👍

**Review by NonQueueingMatt — APPROVED** [review]
Changelog...........................

**Comment by MarinaGryphon** [comment]
> Changelog...........................

bugfix????????

**Comment by NonQueueingMatt** [comment]
> 
> 
> > Changelog...........................
> 
> bugfix????????

Bugfixes still need changelogs, look at that "changelog required" tag

**Comment by mikomyazaki** [comment]
Use the 'bugfix' tag.

**Comment by MarinaGryphon** [comment]
!bugfix

**Review by mikomyazaki — APPROVED** [review]

**Pull request merged**
