### PR TITLE
Fixes Taj Cloak Hoods

### PR DESCRIPTION
**Pull request by MarinaGryphon**
Please check how the procs you use function before you use them.

### CODE REVIEW

**Comment by MarinaGryphon** [comment]
!bugfix

**Comment by MarinaGryphon** [comment]
!review

**Comment by VTCobaltblood** [comment]
*scream

vt man bad

**Comment by MarinaGryphon** [comment]
this is even more of a screwup than i thought it was brb

**Comment by MarinaGryphon** [comment]
ok so it turns out it was not your fault

**Pull request merged**
