### PR TITLE
Changes fireaxe to only cleave when wielded

### PR DESCRIPTION
**Pull request by Geevies**
As an engineering main that had to make use of the fireaxe to deal with biohazards, it got old fast when someone entered your range while you were swinging and you decapitate them with the might of Zeus. That can still happen, but, if you know you're gonna be swinging when people are around, you can do it with only one hand to prevent multi-decapitation.

Besides, how well can you drive a fireaxe through multiple bodies if you're only using one arm?

Sidenote: I wanted to do this with other weapons as well, but my brain is simply too small to comprehend what the hell's going on with half of them, so, I'm just sticking with the fireaxe for now.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by alsoandanswer** [comment]
You can just CTRL+F and use Find All to find all cleave procs to find every weapon that uses cleave.
Although it WILL be very time consuming changing every weapon one by one.

**Comment by Geevies** [comment]
That's not the issue I ran into. Weapons like the zweihander have special properties because it has extra range when wielded. The longsword also cleaves, despite not being wieldable. I think just changing the 'non-weapon' fireaxe is a good enough compromise. The chainsaw uses the same ruleset.

**Comment by Pratepresidenten** [comment]
I thought it was already made this way to only cleave while wielded?

**Comment by Geevies** [comment]
Nope!

image

I thought it already worked like that too, but it seems we got confused between the fireaxe and the chainsaw.

**Pull request merged**
