### PR TITLE
Z Level Conscientious Dark Lords of Destruction

### PR DESCRIPTION
**Pull request by LordFowl**
The great dark lords, Nar'Sie and Singuloth, now respect multi-z. Nar'Sie will move up/down to match it's target Z. Singularity will move up/down whenever it fails to move laterally, or to chase it's singularity beacon.

Singularity will also consume _everything_ above and below it.

As a bonus, supermatter cascades will also spread vertically.

### CODE REVIEW

**Comment by Lohikar** [comment]
This doesn't break normal singulo/tesla containment, right?

**Comment by LordFowl** [comment]
Tesla is completely unchanged.

**Comment by skull132** [comment]
Still tho. Do they break containment or not?

**Comment by LordFowl** [comment]
The z-level behaviour for the singularity will now only come into effect at stage 5, the same stage it starts to break containment.

The tesla remains unchanged.

**Pull request merged**
