### PR TITLE
Remove the mention of Zippo in our codebase

### PR DESCRIPTION
**Pull request by TheGoret**
Zippo has been replaced by flip lighter, to avoid copyright issues. Custom items were also renamed.

### CODE REVIEW

**Comment by TheGoret** [comment]
!review

**Comment by alsoandanswer** [comment]
I think this is unneccessary

**Comment by Kaedwuff** [comment]
> I think this is unneccessary

I see zero reason why we should be using any actual brand names in our imaginary future setting. We should be able to recognize what an object is without associating it with specific corporation that exist in real life.

**Comment by TheGoret** [comment]
> 
> 
> I think this is unneccessary

I wanted to add crocs, but we told me we couldn't use the name because it is a company. I used Zippo as an example, and we told me that it was oldcode and a problem. To avoid problems, even if its unlikely, I think it is necessary to change it.

**Comment by alsoandanswer** [comment]
The clogs are a new addition - these have been already in-game for a while.

**Comment by TheGoret** [comment]
Just because it already exist doesn't make it okay. Geeves and Matt told me to go for it. https://i.imgur.com/YCUik4o.png
https://i.imgur.com/LnrZxrz.png

**Comment by Alberyk** [comment]
Good to go when map conflicts are fixed.

**Comment by Menown** [comment]
The space twinkies remain safe..................... for now.

**Comment by NonQueueingMatt** [comment]
Some shit went wrong with the space ruins folder. Rebasing to master should fix it.

**Comment by TheGoret** [comment]
i hate my life. zippos will shamefully stay, fuck it.

**Pull request closed without merging**
