### PR TITLE
Warehouse submap expansion and bugfix

### PR DESCRIPTION
**Pull request by courierbravo**
Adds 18* new warehouse submap variants. Also, fixes a medical locker not having medical supplies in it.

### CODE REVIEW

**Comment by courierbravo** [comment]
!review

**Comment by DreamySkrell** [comment]
image
these two should be removed, cause it's kinda arbitrary why only specifically PRA and ZORA have warehouse submaps, and I wouldn't like to see 30 more submaps for every culture

**Comment by DreamySkrell** [comment]
image
`/obj/random/kitchen_staples` and especially `/obj/random/booze` are used here so they should have readable sprites

see `\icons\obj\random.dmi` - in case of booze, just get some plain booze bottle, and apply the rainbow mask thing on it in photoshop or something - this is going to take like half a minute

**Comment by DreamySkrell** [comment]
image
should really use a random vendor spawner - should be coded in if it doesn't exist already

**Comment by DreamySkrell** [comment]
image
should really use a random canister spawner - should be coded in if it doesn't exist already

**Comment by DreamySkrell** [comment]
image
don't think the warehouse should spawn with spider webs - like presumably it's in constant use for storing stuff, especially now that with submaps it's not just sitting empty all the time as before

and especially shouldn't have hostile greimorians

**Comment by DreamySkrell** [comment]
image
there are two submaps that are the same here (with the vendors)

**Comment by DreamySkrell** [comment]
image
image
`/obj/random/finances` used here can spawn like, expensive stuff/cash, I don't think it should spawn in the warehouse just on a rack, up for anyone to just pocket it

**Comment by DreamySkrell** [comment]
everything else looks fine I think

**Comment by DreamySkrell** [comment]
image
also here it should be using `/obj/random/mre` instead of `/obj/random/mre/dessert`

**Comment by courierbravo** [comment]
- PRA and Zo'ra - These two aren't arbitrary, they're the two factions I associate most with Biesel, especially non human working class Biesel. Since the ship is Biesel built/registered, I think its perfectly in theme to see something like this.
- Kitchen and Booze - I guess I can do that, but thats not my area of focus. Maybe that can be its own separate PR, I'd rather not address it in this one.
- Venders and Canisters - I didn't use or make randoms for a reason, I wanted those ones specifically.
- Greimorian - The warehouse already has hostile mobs as a start of round threat. I specifically chose the bombardier because of its relative lack of danger posed, compared to any other greimorian or even the space bats or flying drones that spawn in cargo. Additionally, the webbing is for the theming of the greimorian, not to suggest that its been sitting for awhile. Grems make webs cause they're gross spider things.
-Will change the doubled warehouse spawn. Unintentional leftover from when I was sorting the various submaps I made into either department related or non department related. Will also chance the finance spawn, I misunderstood what the description suggested and didn't think to check the code for what exactly it spawns. 
-MRE Desert - Picked that one intentionally. I thought it would be neat to see a bunch of a component instead of the whole MRE itself. MRE components are sold individually (at least where I'm from) so I think its still kosher.

**Comment by courierbravo** [comment]
replaced duplicate with a janitor themed submap, and replaced the finances random spawner with 3 coin spawners.

**Comment by DreamySkrell** [comment]
> PRA and Zo'ra - These two aren't arbitrary, they're the two factions I associate most with Biesel, especially non human working class Biesel. Since the ship is Biesel built/registered, I think its perfectly in theme to see something like this.

I hold onto my previous thought and requested change. If anything, it would make more sense to have biesel and/or corpo stuff, more than PRA or Zo'ra stuff. There is a place for nation themed stuff, but I think the warehouse is not it.

> Kitchen and Booze - I guess I can do that, but thats not my area of focus. Maybe that can be its own separate PR, I'd rather not address it in this one.

Fine I guess. I meant it more as a "would really be nice" rather than "required".

> Venders and Canisters - I didn't use or make randoms for a reason, I wanted those ones specifically.

Fine I guess. I meant it more as a "would really be nice" rather than "required". Though the most ideal would be a mix of random and non-random canisters.

> Greimorian - The warehouse already has hostile mobs as a start of round threat. I specifically chose the bombardier because of its relative lack of danger posed, compared to any other greimorian or even the space bats or flying drones that spawn in cargo. Additionally, the webbing is for the theming of the greimorian, not to suggest that its been sitting for awhile. Grems make webs cause they're gross spider things.

Hostile mobs already do spawn as part of filling crates, yes, but they have very low chances, (if I am reading the code right), 3% chance per crate for bats/bees/etc, and 3% global chance for actually dangerous mobs like the grem hunter. Dangerous mobs in submaps like here circumvent that chance system altogether.

> Will change the doubled warehouse spawn. Unintentional leftover from when I was sorting the various submaps I made into either department related or non department related. Will also chance the finance spawn, I misunderstood what the description suggested and didn't think to check the code for what exactly it spawns.

Sounds good.

> MRE Desert - Picked that one intentionally. I thought it would be neat to see a bunch of a component instead of the whole MRE itself. MRE components are sold individually (at least where I'm from) so I think its still kosher.

Sounds good.

**Comment by DreamySkrell** [comment]
Actually, thinking about it now, the crates in these warehouse submaps should be normal plain crates, instead of the rainbow loot crates.

As the normal plain crates are filled with a curated list of items fit for the warehouse (like recently had drugs removed from it). While the loot crate was always more intended for offships, and can spawn crazy stuff, including guns, drugs, even the breacher unathi hardsuit.

Yes, I put the rainbow loot crates there initially, mistakenly.

**Comment by courierbravo** [comment]
Removed the PRA, Zo'ra, and greimorian themed submaps. Also altered the changelog to reflect current state

**Review by DreamySkrell — APPROVED** [review]

**Review by FluffyGhoster — APPROVED** [review]

**Pull request merged**
