### PR TITLE
Polishes and Tweaks Xenobiology

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR polishes and tweaks xenobiology by improving the flow and making it look more like a lab.

## screenshots
<details>
<summary>🖼️ click to view</summary>

### before
image
**figure 1:** before.

### after
image
**figure 2:** after.
</details>

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Comment by alsoandanswer** [comment]
cremator room should have dark tile floors, honestly

**Review by DreamySkrell — APPROVED** [review]
I think it's nice, but I agree that the cremator room should be dark tiles and no color

**Review by FluffyGhoster — APPROVED** [review]
lgtm

**Pull request merged**
