### PR TITLE
Adds a couple of new gun sprites

### PR DESCRIPTION
**Pull request by Alberyk**
This pr adds new sprites for the blaster guns, gauss thumper, pump shotgun, ion rifle, disruptor guns, and laser rifle. Sprites were made by kyres.

### CODE REVIEW

**Review by Geevies — APPROVED** [review]

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
There are a few issues with the guns I'd like to be addressed.

1. Proportions
These are excessively glaring on the comparison between blasters and the larger weapons such as rifles and shotguns. Here's an example with real life images for comparison.
dreammaker_gQKUq2lK82

Speaking of which, the stocks for the rifles and shotguns - they've been resized to be even LESS proportionate for some reason.

dreammaker_eWFocSOaWT

dreammaker_xOvcsevFXu

dreammaker_hX65M84Zh0

2. Color.
I'm not particularly against changing the color to silver. Hell, I'd give it a hand-wave if it was used by some contractors and stuff. But these are supposed to be generic weapons - used by most, if not everyone, so a black/dark brown color scheme meant it could be incorporated into most outfits without sticking out - i.e, security and mercs can both equip the weapons without them looking strange.

3. Outlines/Shading.
They aren't even internally consistent.

dreammaker_Hq8oSepIY8

4. Readability
The old ion gun - the blue heavily contrasted with the black of the gun, making it ever more obvious. Same with the red of the carbine - at a glance, it was immediately apparent which gun did which. 

dreammaker_2P8aJcGvu5

Speaking of which, the gauss thumper looks even further from it's counterpart as a coilgun.

dreammaker_L2EXbRI8e3

**Comment by TheDanseMacabre** [comment]
@alsoandanswer I'd like to point out that the "dithering" is likely checkering, which is a common way to add texture to parts of a firearm that your hand is going to come into contact with. The sec .45, for example, also has checkering.

**Comment by kyres1** [comment]
@alsoandanswer 

Point one : As said before, I am not making every pistol itty bitty for the sake of being proportionate to guns which all are constrained to the 32x32 tile size. This is not seen by me as some sort of sacrifice, I rather like the fact that pistols have finer details expanded by the fact that they're not 6 pixels long as a byproduct of needing to be proportionate with larger guns. Further, it's hard as fuck to click on the .45s much less something _even smaller._ 

Point two : Security largely wears black and dark blue. Officers wearing the white upper shirt uniform are few and far between, if you intend to use that, but their vests are black and grey anyway - that's not even regarding arm guards, which are largely very dark colored. Furthermore, the weapons resprited are armory weapons - you'll almost never see them in the hands of anybody but people utilizing the armory (with the exception of the ion rifle, which is utilized by mercs and raiders), which is unsurprisingly overwhelmingly security. Tl;dr on this point : security uses these guns. Security is black. These colors clash with black, and are far more visible. 

Your best hope of seeing a pump shotgun in combat right now is picking up on a total of 11-12 pixels protruding from the left/right side of a sprite. As for the TCFL guns, they also are very rarely seen outside of TCFL hands - and thus, contrast heavily with TCFL gear, being silver and saturated brown.

Point three : Outlines will be fixed to be consistent. 

Point four : Don't see the issue. It looks perfectly readable to me.

Point five : Neither of them look like a "coil gun" by any stretch of the imagination. The new sprite looks fine. If you think otherwise, just say so.

**Comment by alsoandanswer** [comment]
1.
You have a bad habit of fighting the medium that is the 32x32 restriction of SS13. You are actively shooting yourself in the foot in getting better at making sprites by forcing a larger resolution. Another problem is the fixation on finer details. Pixel art differs from traditional art, and this is one of the things you need to sacrifice, or else the rest of the sprite suffers as a result. Miscellaneous things can be put in descriptions and flavor text. It is not that important.

Clickability is a non-issue, we can add a transparent layer surrounding the gun. Not to mention that a rifle is substantially more powerful than a blaster - gameplay readability wise, it makes sense that size is proportional to power. 

2.
Security isn't black - it's white and blue.
Now, only when they are equipped with armor and vests they ARE black.
Now, there's a correlation between danger and color - black means they're armed, and dangerous.
Not to mention the fact that these guns are black means they look alright in most hands - in and out of security.
Cargo can just as easily order guns and weapons as well.
4.
Cyan and white do not contrast. They're heavily contrasting for a reason - so you can see your shots left at a glance.

5.
image
This is an example to what I'm referring to.
The removal of sharp edges and replacing them with round ones conflicts with shape theory, so it looks much less menacing as a weapon.

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
above

**Review by skull132 — APPROVED** [review]

**Pull request merged**
