### PR TITLE
ADDS RAGIN' MAGES

### PR DESCRIPTION
**Pull request by chaoko99**
Do keep in mind that I have never played ragin' mages. I always assumed it was "more wizards".

### CODE REVIEW

**Comment by Pacmandevil** [comment]
what could possibly go wrong

**Comment by Arrow768** [comment]
Now, whats the difference to wizard ?

**Comment by Lohikar** [comment]
There's more than one wiz/mage spawned.

**Comment by Arrow768** [comment]
As if a single one of them is not bad enough.

**Comment by Pacmandevil** [comment]
Statistically the more wizards you have the spicier the round gets

**Comment by Alberyk** [comment]
Ragin' mages should create more wizard over time/when the other wizards dies.

**Comment by Pacmandevil** [comment]
Then it is simply not ragin' mages

**Comment by chaoko99** [comment]
That seems... Odd and somewhat awkward to code. I'm probably going to make the mode about a group of many, statistically weaker magi... Buuuut.. Eh. Who knows.

**Comment by chaoko99** [comment]
I'm willing to drop it to 4 max, but no fewer.

**Comment by OneOneThreeEight** [comment]
The mixed secret game modes were intended to add more flavor and variety to rounds with the unintended consequence of often causing a chaotic shitshow.

This suggestion only posits to make the round into a chaotic shitshow. This is arguably much worse than mixed secret. Don't add it.

**Comment by chaoko99** [comment]
Yeah whatever I don't care.

**Pull request closed without merging**
