### PR TITLE
Gargoyle voidsuit resprite

### PR DESCRIPTION
**Pull request by hazelrat**
This implements a resprite of the regular Gargoyle voidsuit, the SFA variant, and the SSMD variant, full credit to shqvelheaded on discord for the sprites. This also adds a unique variant for the SPLF, which I intend to use for https://github.com/Aurorastation/Aurora.3/pull/20197.

Not all of the Gargoyle variants have been resprited, but most of the ones that are accessible ingame short of using the uplink, and are extant factions in the setting, have been.

image

### CODE REVIEW

**Comment by hazelrat** [comment]
!review

**Comment by Butterrobber202** [comment]
I do not mean to be a downer, but while the quality of the sprite is good. That is a **very** deep and rich green. I think it would look better of it had the military green it currently has, or a similar color to the one on the left.

**Comment by hazelrat** [comment]
> I do not mean to be a downer, but while the quality of the sprite is good. That is a **very** deep and rich green. I think it would look better of it had the military green it currently has, or a similar color to the one on the left.

Committed modified versions of the sprites with colours closer to the versions in live, see OP.

**Review by alsoandanswer — APPROVED** [review]
Looks good to me.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
