### PR TITLE
Removes tipping

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
This removes the tip system from the game. It's functionally pointless and frequently posts entirely non-functional, outdated, or outright gamey tips. It serves no purpose and nobody seems interested in maintaining it, so I'm removing it.

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Review by alsoandanswer — COMMENTED** [review]
Danse, stop removing things that could be useful if it was simply updated with relevant information. This is like throwing out a vending machine because the snacks inside are expired.

**Comment by TheDanseMacabre** [comment]
> Danse, stop removing things that could be useful if it was simply updated with relevant information. This is like throwing out a vending machine because the snacks inside are expired.
Feel free to make a PR to update them if you so wish. Nothing I've removed "could be useful" if it was simply updated, and frankly this isn't relevant to the PR at all.

**Comment by FlamingLily** [comment]
> Feel free to make a PR to update them if you so wish.

We can't, they're configs. Someone with access to the server has to do it.

**Comment by Arrow768** [comment]
> > Feel free to make a PR to update them if you so wish.
> 
> 
> 
> We can't, they're configs. Someone with access to the server has to do it.

You can make a PR to update the example tips.
Upon merge they just have to be copied over into the actual config.

**Comment by Arrow768** [comment]
Will be discussed by the maintainers

**Review by Arrow768 — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
Don't really like this. I think the tip system is cute. Would be better to update them rather than just kill it.

**Comment by Arrow768** [comment]
Closed as not wanted.

**Pull request closed without merging**
