### PR TITLE
Combustion Chamber Expansions

### PR DESCRIPTION
**Pull request by WickedCybs**
The PR changed in scope, so the main notable changes are going to be that cameras have been added to each combustion chamber and that the starboard propulsion section has an airlock leading to space. The less notable but still handy change is that the airlocks underneath the interior blast doors to each combustion chamber are now linked to a bolt control, and that door now starts bolted. It originally was unbolted and had no contorl.

image

### Original PR stuff below. Not very relevant anymore.

At the moment, the combustion chambers look like this.

image

The problem as I saw it is that you have only a single airlock/blast door combo between you and a potentially firey doom. It's actually quite easy for something to go wrong there. We've had plenty of propulsion accidents with it being set on fire or just getting vented. My solution was adding an airlock in-between the actual combustion chamber if for whatever reason it needed to be accessed to remove some of the risk. If you really wanted to sabotage it or use it in some way, it's still easy to do that. This change should just hopefully have people be able to do these things without fear, and it's also just a lot more sensible in my opinion.

image

image

Something in particular that I'll note is that the blast door within the airlock itself is covering an exposed space tile. It's so the airlock itself can be purged after use without compromising the main combustion chamber. There's also an added camera in the chambers to monitor progress too and an an airlock leading to space added to the starboard propulsion area.

### CODE REVIEW

**Comment by WickedCybs** [comment]
!review

**Comment by mikomyazaki** [comment]
> We've had plenty of propulsion accidents with it being set on fire or just getting vented.

Due to people accidentally opening the chamber, or due to people overheating the chamber and melting the walls?

I think it's okay to allow people to make mistakes with the propulsion chamber. If they're ignoring the signs and not thinking about what the purpose of the doors is, then they can die and learn for next time. Also I'm concerned that making them easier to access this way will increase the likelihood they are used for executions (we have seen this happen a couple of times already with the current setup).

**Review by mikomyazaki — COMMENTED** [review]
When testing locally I found that the air didn't vent from the interior airlock into space properly. Does it work for you? I'm unsure if it is some sort of config setting.

**Comment by WickedCybs** [comment]
> > We've had plenty of propulsion accidents with it being set on fire or just getting vented.
> 
> Due to people accidentally opening the chamber, or due to people overheating the chamber and melting the walls?
> 
> I think it's okay to allow people to make mistakes with the propulsion chamber. If they're ignoring the signs and not thinking about what the purpose of the doors is, then they can die and learn for next time. Also I'm concerned that making them easier to access this way will increase the likelihood they are used for executions (we have seen this happen a couple of times already with the current setup).

Discussed this with Myazaki over discord. I'd like to go forward with the current design, although if the prevailing thought is the same I will change the airlock in favour of an alternate idea more similar to the combustion chamber on server as-is.

One aspect of this PR that I also think I must comment on is whether this will make executions via the combustion chamber easier to do. I think it would, though I've attempted to mitigate this with the very cramped interior. I believe it wouldn't be _much_ easier though and that executions via the burn chamber would be a definite ahelp if it becomes the most "obvious" course of action for Command. I'll be watching this aspect closely, because if it turns out I'm wrong with my thoughts here I will quickly either revert this part of the PR or implement measures that make this much harder.


> When testing locally I found that the air didn't vent from the interior airlock into space properly. Does it work for you? I'm unsure if it is some sort of config setting.

It did work for me most of the time, although in certain cases it wouldn't vent the room at all as you experienced. I believe this is a bug rather than a mapping issue and thus unavoidable. Despite that conclusion, I'm still looking into it and seeing whether it'd be worth having the system like this, as it is. Some alternative ideas were discussed in Discord that I've been meaning to try.

**Comment by WickedCybs** [comment]
Removed the purge function since on continual revisiting, the bug where atmos wouldn't drain happened far too often for it to be useful.

At the moment my current ideas are leaving the airlock as is, having safely venting it mean also venting the main combustion chamber itself (could be desired to add some consequences) or removing the "airlock" totally. I'm going with leaving the airlock in for now even if it's not as useful anymore, since I'm curious to see how players might end up working with this.

**Comment by WickedCybs** [comment]
!wip

**Comment by WickedCybs** [comment]
Made it work via bolts.

**Comment by WickedCybs** [comment]
!review

**Review by Arrow768 — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
