### PR TITLE
Adds a rattling emote for Attendants

### PR DESCRIPTION
**Pull request by hazelrat**
At request of bug lore, adds a *rattle audible emote available exclusively to Vaurca Attendants. 

[Sound origin.](https://uppbeat.io/sfx/rattlesnake-tail-shake-aggressive/6100/21239) As far as I know this shouldn't require attribution.

### CODE REVIEW

**Comment by hazelrat** [comment]
!review

**Review by FluffyGhoster — APPROVED** [review]

**Review by Geevies — CHANGES_REQUESTED** [review]
having looked into Uppbeat's licensing scheme and their paid plans, plus what they deem 'Uppbeat' credits being 'one video per download', i'm not entirely convinced we'll be able to distribute it permanently via git, especially not without attributions

is it possible that the vaurca team could get the same sound from a source with better outlined licensing?

**Comment by hazelrat** [comment]
@Geevies New sound added from [here](https://pixabay.com/sound-effects/snake-rattle-sound-hq-240150/), license [here](https://pixabay.com/service/license-summary/).

**Review by DreamySkrell — APPROVED** [review]
high priority need this merged ASAP

**Pull request merged**
