### PR TITLE
Replaces the pickaxes in Research EVA prep with mining drills

### PR DESCRIPTION
**Pull request by Leudoberct1**
With the changes to research levels, a mining drill can be produced straight away at roundstart with no research required. Because of this, I feel like it's justifiable for the pickaxes in the EVA prep area to be replaced with standard mining drills.

### CODE REVIEW

**Comment by Leudoberct1** [comment]
!review

**Comment by KasparoVy** [comment]
Aww. I liked carrying around a big ass pickaxe.

**Comment by fernerr** [comment]
Well, there's always spare pickaxes in the excavations closets if you prefer that option.

**Comment by KasparoVy** [comment]
Not quite sure what closets you mean but I'm glad to hear there'll still be pickaxes around

**Comment by Leudoberct1** [comment]
There's closets in research EVA prep that by default spawn with pickaxes.

**Comment by Leudoberct1** [comment]
Closing this so I can re-make it.

**Pull request closed without merging**
