### PR TITLE
Adds new Dionae accents

### PR DESCRIPTION
**Pull request by Yonnimer**
Adds a handful of new Dionae accents

### CODE REVIEW

**Comment by Yonnimer** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]
sus srs

**Review by Llywelwyn — APPROVED** [review]
`` text_tag = "SUS"``

NYA was changed as an accent tag in a different pr to avoid people memeing about it, this one stood out to me as similar but idk probably doesn't matter

**Comment by Yonnimer** [comment]
Removed the sus tag by changing some things around,

**Pull request merged**
