### PR TITLE
Fresher Refreshments

### PR DESCRIPTION
**Pull request by MarinaGryphon**
* Attempts a fix for lunchboxes randomly losing their drinks.
* Attempts a fix for not being able to spawn with diona nymph lunchboxes.

### CODE REVIEW

**Comment by MarinaGryphon** [comment]
!bugfix

**Comment by MarinaGryphon** [comment]
!review

**Comment by skull132** [comment]
"Attempts to fix."

Big thonk. This isn't even that hard to test locally. Does it fix it or not?

**Comment by Geevies** [comment]
@MarinaGryphon Attention needed.

**Pull request closed without merging**
