### PR TITLE
 Smartfridges : Unwrenchable By Regular Wrench

### PR DESCRIPTION
**Pull request by alsoandanswer**
title

You now need to use impact wrench or better.

Stops powergaming medical players from breaking into chemistry constantly.

If you want to do this ask engineering. Either that or break into the kitchen.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by alsoandanswer** [comment]
!bugfix

**Review by Arrow768 — CHANGES_REQUESTED** [review]
Imho it would be better to add wires that need to be pulsed to "deploy" some wheels.

Tying it to a specific wrench-type only requires that a powergamer obtains specific item.

**Comment by alsoandanswer** [comment]
> Imho it would be better to add wires that need to be pulsed to "deploy" some wheels.
> 
> Tying it to a specific wrench-type only requires that a powergamer obtains specific item.

Hm, how about making it so not disconnecting the power just makes it shock you when you try to move it?

**Comment by Generalcamo** [comment]
This introduces a rather arbitrary restriction. Regular wrenches can unwrench entire wall girders, but not refrigerators? I would either expand this functionality to a broad range of logical structures, or do what arrow proposed.

**Pull request closed without merging**
