### PR TITLE
Removed Clerical, merged it into the Mining Module which is now Supply

### PR DESCRIPTION
**Pull request by Chada-1**
Just as it says on the tin, merged the Clerical 'borg module into Mining, re-branded the Mining Module to be 'Supply', just like the Supply department.

This was done for a multitude of reasons that'd probably be fit for a feedback thread if this proves controversal, but it can be summed up as: Clerical useless, Mining useful. Clericals niche (paperwork) is useful, but clerical itself is useless. So Clerical+Mining=More useful

Also gave Research and Service the Clerical tools too.

Feedback Thread [Here.](https://forums.aurorastation.org/topic/14739-merging-the-borg-clerical-module-into-others/)

### CODE REVIEW

**Comment by Chada-1** [comment]
!review

**Comment by alsoandanswer** [comment]
Clerical is paperwork bot. It's kind of useless by design. No replace.

It's basically the HoP but Borg. Functionally useless other than giving people IDs but roleplay wise eez important.

**Comment by Chada-1** [comment]
> Clerical is paperwork bot. It's kind of useless by design. No replace.
> 
> It's basically the HoP but Borg. Functionally useless other than giving people IDs but roleplay wise eez important.
If it's useless by design then we really shouldn't have it Wezzy, it's not worth keeping when there are a grand total of 2-3 'borgs per round.

**Comment by alsoandanswer** [comment]
Add clerical modules to Service as well and should be gucci.

**Comment by Chada-1** [comment]
> Add clerical modules to Service as well and should be gucci.

Will do, will add the stuff to Research too.

**Comment by Chada-1** [comment]
Closing this to re-open a new branch where I don't remove Clerical since I've been convinced to keep it.

**Pull request closed without merging**
