### PR TITLE
Map - Fixes, IA office, slight modifications.

### PR DESCRIPTION
**Pull request by Juani2400**
This is mostly a fix for all the minor mapping bugs that people has
reported. It also covers the request for a new IA office and does a few
very minor modifications to the station's layout, almost unnoticeable.
Biggest changes are listed below:

- Fix: Camera-Monitor network at Interrogation. #587
- Fix: APC connection at Cargo.
- Fix: Granted Chef access to the door at the Garden.
- Rework: IA Office.
- Rework: Power network in Cargo and surroundings.

Really hope I haven't fucked up while using Github. Also, I used MapMerge this time.

### CODE REVIEW

**Comment by Lohikar** [comment]
Baymerge changes a lot of the map, it might be a good idea to base map changes off of `development` instead of `master`.

**Comment by Juani2400** [comment]
This one includes fixes for the current map. It's not intended to be used after Baymerge, as I take most of the bugs are already fixed in the version we'll use after the merge.

**Comment by LordFowl** [comment]
If your map changes have done any significant changes to how a room actually looks, or changes something that can't really be described effectively (IA rework), please include pictures.

**Comment by Juani2400** [comment]
While I'm not completely happy with the result of the rework of the IA office, the space is tight and only so much could be done: http://imgur.com/82mjf3G

There should be no more _significant_ changes in this commit.

**Comment by NanakoAC** [comment]
I have to agree with lohikar, baymerge going into master is imminent. We can't be merging changes that are not based on or compatible with it. And if  these things are changed by the upcoming code then merging this would be pointless.

**Comment by Juani2400** [comment]
If the baymerge is happening really soon, then it's completely fine not to merge this. I don't know the current progress of the code, so I can't tell. I'll leave it open. Feel free to close it if it's happening really soon.

These are just a few bug fixes and minor reworks, shouldn't be much of a problem if not merged.

**Comment by Lohikar** [comment]
Baymerge is likely happening some time this week.
The IA office change might be worth re-doing on the baymerge map, but you may have to re-do it from scratch as baymerge does change the IA's office slightly.

**Comment by Juani2400** [comment]
I'll work on it as soon as it's merged. 👍

**Pull request closed without merging**
