### PR TITLE
Map fixes and detective access changes

### LINKED ISSUE #2870: [NEW MAP] Solar Array Wiring
Aurora-6's solar arrays have five power cables that are facing East instead of West.
image

Aurora-5's Beta arrays on the Tcomms have five solar panels that don't seem to have wiring on them.
image

Both of these result in the panels not being detected on the console in their respective maintenance rooms.

Thanks for the good work!

### LINKED ISSUE #2897: [New Map] One mining conveyor belt piece has a bad ID
I couldn't for the life of me figure out the typo, the `id`s on this and neighbouring pieces look similar. But copy-pasting worked.

https://kama.skullnet.me/index.php/s/X88Igz1XBCqPjQs

### PR DESCRIPTION
**Pull request by Alberyk**
Fixes some messed up directions such as the map on the surface level and a newscaster in the cargo bay
Removes the extra holodeck console
Fixes #2897 (probably)
Fixes #2870
Fixes a broken camera at the vault
Fixes command doors at the bridge being named wrong
Removes the forensic access from the detective, and changes the access of his officer so the csi can't get inside
Fixed some areas of telecomms having roofs where they are not supossed to do

(yes, I used the mapmerge)

### CODE REVIEW

**Comment by Lohikar** [comment]
> 366k diff
this is fine

**Comment by skull132** [comment]
And you said TGM was the way to go 😏

**Comment by skull132** [comment]
Merge dev into your branch, that should fix travis.

**Comment by Alberyk** [comment]
Done.

**Pull request merged**
