### PR TITLE
Gives zipties a purpose to exist

### PR DESCRIPTION
**Pull request by Alberyk**
Adds elastic var of the cable cuffs to the zipties, allowing them to cuff people inside hardsuits, unlike regular cuffs, and adds a box of them to the nonlethal crate at cargo.

Also, purges the boxes.dmi of shortened paths.

### CODE REVIEW

**Comment by Lohikar** [comment]
I don't suppose boxes have a `fill()` proc like lockers do, do they?

**Comment by Alberyk** [comment]
Seems not.

**Comment by LordFowl** [comment]
Why would cablecuffs be unable to cuff those in hardsuits?

**Comment by Alberyk** [comment]
Cable cuffs seems to be a really downgraded and ghetto version of the regular handcuffs, besides of their supossed flexibillity I don't still see why they should be able to handcuff people inside hardsuit, while zipties are probably better designed to this. Besides, as the pr states, this is giving a feature to zipties, that is now nothing but worse handcuffs with different sprites.

**Comment by LordFowl** [comment]
A cable cuff is basically just rope. It has adjustable size, and could very easily cuff someone in a hardsuit with this in mind.

As I understand it, the original intended advantage of zipties would have been their stackability. If this is not pursued, then indeed they are just worse handcuffs with a different sprite. At that point, instead of shuffling features around, would it not be better to just remove them wholesale?

**Comment by Alberyk** [comment]
Alright, I believe that cable coils can keep their elastic var.

**Pull request merged**
