### PR TITLE
Removes an unused species

### PR DESCRIPTION
**Pull request by Alberyk**
This pr removes resomi from the code, as they are not used anywhere.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
Thank you

**Comment by Sindorman** [comment]
Changelog it please tho

**Comment by Alberyk** [comment]
I don't really think that a changelog is needed when this has no real effect on gameplay.

**Comment by Sindorman** [comment]
@Alberyk Changes that do not affect gameplay are called `backend` in changelog

**Pull request merged**
