### PR TITLE
Station Nerfs, the Grimdark Update

### PR DESCRIPTION
**Pull request by LordFowl**
This PR nerfs several aspects of the station and their ability to attain supplies, altogether creating a grittier existence.

General overview of changes:
- The entire station is dirtier. Everywhere except the bridge now experiences the random dirt generation was previously restricted to maintenance.
- The entire station is darker. Lights have a higher chance of spawning broken.
- The entire station remains dirtier. Humans track dirt faster and the janitor has less supplies to clean it up.
- The entire station is poorer. Accounts have been reduced drastically. Humans will now be fortunate to spawn with over 2,000 credits if they're in a well-paid job, and xenos will experience even more dire wages. Departmental accounts have been cut in half.
- The entire station is less well-equipped. The armory has less gear overall. They no longer have ion rifles, and only have a partial ablative suit. One energy carbine has been removed, along with the pump action shotguns. Both laser rifles have been replaced with Tajara imported icelance rifles. The vault's stock has been liquidated and replaced with rations. In addition, janitorial and engineering supplies have been sorely undercut.
- The station is less healthier. Medical supplies are scarcer, and an entire OR has been dismantled and sold to recuperate overdue debts.
- The entire station is hungrier. Vendors now no longer dispense food, except for a meager supply of bread and jerky, in addition to a somewhat bulkier supply of food vouchers, which can be redeemed at the kitchen. They are also made of edible and (mostly) non-toxic paper. The booze-o-mat now dispenses a lot less drinks, and all soft-drink vendors now only dispense 2 of each drink. Many vendors don't even work anymore.
- Cargo is less capable. The prices of many items in cargo have been increased.
- Merchants are more ameniable. The chance of merchants appearing have been increased to 80% per round.

Ultimately this PR seeks to make a grittier and darker experience.
Todo;

- [ ] Rebalance vendors.
- [ ] Redistribute engineering's electrical supplies.
- [ ] Half departmental accounts.
- [ ] Adjust config only changes (cargo prices, merchant spawn chance)
- [ ] Implement tracking dirt faster.
- [ ] Redistribute medical supplies.
- [ ] Remove bodyscanners and health scanners.
- [ ] Sanity check turf initializer
- [ ] Test changes.

### CODE REVIEW

**Comment by BurgerLUA** [comment]
It begins.

**Comment by iamlcarus** [comment]
I'd love this.
Especially the medical changes, assuming you add a way to diagnose internal bleeding.
The stethoscope was suggested.
Other than that, with scanners removed, medical players would actually be required to use critical thinking and diagnose issues through means other than lazily slapping in a scanner. Since I'm pretty sure any other medical condition can be diagnosed without a scanner through some means.

**Comment by VTCobaltblood** [comment]
Feedback thread?

**Comment by skull132** [comment]
That is. A lot of shit to shove into a PR. For one.

**Comment by NiftyBaby** [comment]
Yeah uh. If we're the number two station why are we staffed like an outpost NT utterly forgot about.

**Comment by OneOneThreeEight** [comment]
Usually there needs to be a good justification for removing even a single feature from the game especially if its removal does more harm than good to gameplay.

This is a pretty ridiculous amount of effort investment just to remove things. All of this will only suit to drive people from the server by unnecessarily adding tedium with no tradeoff.

**Comment by LordFowl** [comment]
@skull132, all of the changes are related, ergo they all belong in one PR. Divvying it all into seperate PRs will just make it harder to revert later, in addition.

**Comment by resilynn** [comment]
Give me a good lore reason for this first.

**Comment by LordFowl** [comment]
That is not an excuse to harass the loredevs either. They are obliged to release things according to their own schedules.

**Comment by ParadoxSpace** [comment]
pwease rewax, mowe infowmation wiw come soon >w<

**Comment by BurgerLUA** [comment]
A feedback thread is needed. It would be nice to have one before the weekend.

**Comment by LordFowl** [comment]
If lore wants to create a meta-feedback thread, that is their choice, but I will note that is typically not done. This PR is simply waiting for a few final decisions to be made before it's ready to be finished.

**Comment by MarinaGryphon** [comment]
No changelog was added, why was the changelog tag removed?

**Comment by LordFowl** [comment]
Because this is a temporary PR that will be reverted at a predetermined time. Changelogs are a matter of permanent record.

**Comment by TehFlaminTaco** [comment]
Nah don't nope out the feedback thread idea. This is a big thing, a big thing that extends more to just the Loredevs, it's a community thing. I like this grmdarkier station, but I feel we definitely need the community to be okay with it, **And not write it off as "Just wait, we have things in the works"**

**Comment by LordFowl** [comment]
No.

**Comment by Warbidon** [comment]
One issue that I have with removing the body and health scanners means that it is impossible to tell if a patient has ~low~ blood (70-80%), as there is no direct way to find out health percentages without either a health scanner or such besides asking the person if they feel lightheaded. which would require perogative from the physician in figuring out a person state.

**Comment by ComradeCorbyn** [comment]
I'd love these changes, especially the medical ones. It'll give the Psychiatrist something else to do, which is actually diagnose patients instead of sit in the Psych ward being all depressed. However, there may need to be a few more indicators or certain damages as well.

**Comment by Ratvar** [comment]
EMP rifle loss sounds like direct IPC/borg buff
Will antags get similiar grimdark nerfs, or shall revolver traitor become unstoppable?

**Comment by Warbidon** [comment]
> > [SNIP]

80% blood 20-30 oxygen deprivation damage. this is not high enough to proc the "pale skin" debuff. I didn't realize that organ damage  specifically (low respiration, low heartbeat was diagnosed by a stethoscope), but that only leaves the issue that it is virtually impossible to tell if a patient has 20% blood loss by a medical staff member through game mechanics alone.

**Comment by Chada-1** [comment]
Fowl, could you make a milestone, with a lot of different PRs achieving this, to make reverting them all just a matter of rolling back that milestone? This would also enable picking and choosing what gameplay elements to include as a form of minimal effort tweaking. Up to you but this would solve the problem people have if it's feasible.

**Pull request closed without merging**
