### PR TITLE
Removes pepperspray and telebaton stun

### PR DESCRIPTION
**Pull request by Alberyk**
-removes pepperspray instant stun if the mouth is not covered, instead it will cause pain
-removes telebaton stun when aiming for the legs, the telebaton will now deal halloss when attacking in disarm intent

Those changes are in the same line as the flash stun removal, stunbatons and etc.

Feedback thread: https://forums.aurorastation.org/viewtopic.php?p=102122

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
The end of the era of instant stuns

**Comment by BurgerLUA** [comment]
This crusade to remove stuns only works if you actually properly rework the mechanics, however the only additional change here is an accidental newline inclusion.

Before, all the mechanics with stun in them were balanced around the fact that the mechanics had stun in them. Simply removing the stun mechanic is like removing a bottom edge piece of a jenga tower; it's going to come crashing down on you if you don't know what you're doing.

I strongly suggest putting in some time to add something else to pepperspray and/or some additional ways for security to peacefully take down perps with non-lethal force.

**Comment by Alberyk** [comment]
Pepperspray already does something; it causes halloss when you breath it and blinds people.

**Comment by Arrow768** [comment]
A feedback topic and vote is needed.

**Comment by OneOneThreeEight** [comment]
I, for one, am glad we are finally following the footsteps of our Baystation kindred.

**Comment by Arrow768** [comment]
Imho the telebaton should offer something else if instastun is removed.
Possibly halos like the stunbaton, ....
Otherwise it´s just a fancy beatingstick

**Comment by Alberyk** [comment]
Replaced the telebaton stun with dealing halloss damage, with reduction based on armor, when on disarm intent.

**Comment by OneOneThreeEight** [comment]
👍

**Comment by skull132** [comment]
_Hnrg_ the vote on this wasn't clearly worded. Majority (71/21) against on the server, but the vote can't be considered directly representative.

**Comment by skull132** [comment]
Well okay. Let's bite the bullet on _this_ one.

**Pull request merged**
