### PR TITLE
A Multi-Z Away Site: The Blue River

### PR DESCRIPTION
**Pull request by WickedCybs**
Ports an away site from Baystation with various changes made. This is a site that appears as an arctic planet on the overmap. It contains a map with an abandoned ship on the surface and a strange blue river underneath.

The site is multi-z and Matt included fixes into it so those will work, since they were bugged until now.

### CODE REVIEW

**Comment by WickedCybs** [comment]
!wip

**Comment by WickedCybs** [comment]
!review

**Comment by WickedCybs** [comment]
Technically ready, though there's a bug with the Intrepid leaving it's back shuttle parts in open space that should be taken care of before merge.

**Comment by WickedCybs** [comment]
Alright there's no issues anymore I believe.

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
