### PR TITLE
Adds a testing pen to the upstairs virology lab.

### PR DESCRIPTION
**Pull request by fernerr**
After observing a number of rounds and gathering some feedback, having no way to test on monkeys in the upstairs lab by default doesn't work out that well, as the biochemists simply take a monkey cube with them up to the lab to avoid the long walking distance downstairs. This adds a single testing pen to the new lab.

https://i.imgur.com/1e7QgOh.png

Feedback thread: https://forums.aurorastation.org/topic/11591-adding-a-testing-pen-to-the-upstairs-virology-lab/

### CODE REVIEW

**Comment by fernerr** [comment]
!review

**Comment by Sindorman** [comment]
I am honestly against idea of having any sort of testing inside of lab that creates viruses. Because I think that it is a function of sublevel virology lab. Another things is that currently there is very small way of accidentally spread virus while developing it, but if you test it on subject's that adds risk of contamination and require to you be able to quarantine two places instead of one. Because wasn't the reason why we moved all virus equipment from virology lab to separate place to add ability on working on the while main virology lab is under lockdown? Otherwise it will take away original intent, wouldn't it?

**Comment by fernerr** [comment]
As I said, they already do the testing inside of the lab upstairs to avoid the annoyingly long walking distance. This makes that procedure safer.
Both areas can already be locked down, and antibodies can be sent directly to the quarantine area downstairs via disposal.
Medical overall is something I'm currently working on, to make it less bloated and more appealing. This will tide things over till then.

**Comment by Sindorman** [comment]
But they shouldn't test it there. The way it is supposed to work is one person creates thing, then they send it down through disposals to proper sublevel testing area. I think if you move disposals delivery intake from medical main level to upstairs biology lab, it should encourage them send items down to sublevel and test it there. I think they shouldn't test anything inside of lab where they create more viruses.

**Comment by fernerr** [comment]
How things are supposed to work and what happens in the reality of the game are two different things, To begin with I agreed with your viewpoints, but after watching things play out ingame, and gathering feedback, It doesn't work out that way. Also I already doubled up the disposal intake, there's one in the new lab, as well as downstairs on the main level.

**Pull request merged**
