### PR TITLE
Pool and Construction Site Remap, Widespread map polish and smaller additions of suggested things

### PR DESCRIPTION
**Pull request by fernerr**
- Remapped the Pool/Fitness Center, the construction level. Shuffled around the surface washroom, adjusted surface cryo.
pool10
Special thanks to Gemspark for the idea of the original layout/further feedback and help.
fitness3
(Staircase goes up to a rooftop running track above the pool.)
con3

- Renamed and moved around some areas to fit better.
- Added cameras to some areas missing them.
- Added an exterior airlock to the fore of engineering and to the telecoms ladder shaft.
- Adjusted the merchant shuttle dock slightly.
- Added blast doors to purge the atmosphere of individual anomaly isolation cells, added a monitor to look through the cell cameras. Added a proper storage area for potential artifacts/anomalies once they've been researched. Made the anomaly isolation air alarms not report their status to the alarm monitor, not causing annoyance for engineering.
- Adjusted the toxins chambers to be a bit less prone to melting.
- Added light switches in a number of areas missing them.
- Fixed a number of minor bugs around the map, missing shutters, wrongly pixel shifted things, objects with the wrong icon state, etc.
- Added a mine cart at cargo interstitial.
- Fixed the psychiatry isolation room monitor.
- Made the small investigations maintenance area actually count as maintenance.

- Added paramedic access to mining.

If you've got ideas/feedback/concerns for this pr or future mapping, feel free to dm me on discord, there's also the minor map suggestions thread on the forums which I frequently visit. https://forums.aurorastation.org/topic/8983-minor-mapping-suggestions/page/4/

### CODE REVIEW

**Comment by fernerr** [comment]
!review

**Comment by fernerr** [comment]
!review

**Comment by fernerr** [comment]
!review

**Comment by alsoandanswer** [comment]
oop, merge error

**Pull request merged**
