### PR TITLE
Makes stun talismans stun

### LINKED ISSUE #14875: Cult Talismans don't work
As far as I can tell, Incapacitation Talismans do not work. They can be made as per normal, but if used, they are expended and do nothing. Ideally, they should work as per their description, stunning, blinding, and so on so forth to the target, when used. While I cannot confirm this, apparently other talismans also do not function.

Yonnimer and Sadkermit confirmed in AOOC that in their experience, all talismans don't work and that incapacitation talismans in particular do not work, respectively.

To reproduce this bug: Draw an incapacitation rune and a talisman creation rune next to each other. Put a piece of paper on the talisman creation rune. Click it. Take the resulting piece of paper. Click it next to a non-cultist. Watch as nothing happens, even though it activates (and you say words).

### PR DESCRIPTION
**Pull request by DreamySkrell**
partially fixes #14875

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!bugfix

**Comment by DreamySkrell** [comment]
!review

**Review by SleepyGemmy — APPROVED** [review]

**Review by KingOfThePing — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
Not a bugfix, this was intentional behaviour.

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]
If they are used in combat again, its a easy revert

**Pull request merged**
