### PR TITLE
Remove stale halloween jokes

### PR DESCRIPTION
**Pull request by Alberyk**
This pr removes the candy bars, with some really funny names, that were added under the excuse of being halloween and were never removed.

### CODE REVIEW

**Comment by BurgerLUA** [comment]
pls no this is the only good thing i've ever contributed

**Comment by OneOneThreeEight** [comment]
The "seasonal" pumpkin spice lattes may also need removed, since the season for Halloween is over.

**Comment by MarinaGryphon** [comment]
I will not allow the candy bars and Pumpkin Spice to be another maidbot. This will not stand!

**Comment by BurgerLUA** [comment]
turn them into maint loot and add omnizine to them and i will approve this

**Comment by Alberyk** [comment]
I am sure you can find those in the cargo food boxes or something.

**Pull request merged**
