### PR TITLE
Custodial Closet and Disposals QoL Remap

### PR DESCRIPTION
**Pull request by SleepyGemmy**
a remap of the custodial closet and the disposals room, whilst still keeping the same structural layout. the pr adds some QoL stuff like a labeller to the equipment room and utilizes the cramped space better, while at the same time making it feel more open. it also adds cool details like decals. a disposals loop was also added to deck 1 so operations can send stuff to custodial and the workshop.

everything is playtested and works like it should (since commit da8047c).

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Review by mikomyazaki — APPROVED** [review]

**Comment by SleepyGemmy** [comment]
new door type reverted, will make it into a atomic PR instead.

**Review by mikomyazaki — APPROVED** [review]

**Review by NonQueueingMatt — COMMENTED** [review]
I meant to approve this

**Comment by SleepyGemmy** [comment]
gem mapping.

**Pull request merged**
