### PR TITLE
Security no longer has access to non-Security cameras on code green.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
As per title. Security now only has full camera access on code blue and above.

This is to stop idle validhunting with people randomly browsing cameras and just so happening to call out some shit happening in the chef's freezer at 00:10.

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Review by JohnWildkins — APPROVED** [review]

**Review by mikomyazaki — APPROVED** [review]

**Review by Doxxmedearly — APPROVED** [review]

**Comment by TheDanseMacabre** [comment]
The security discord's retaliation if this PR is merged will be swift and merciless.

**Comment by SleepyGemmy** [comment]
> The security discord's retaliation if this PR is merged will be swift and merciless. You have been warned. Expect us.

yes...
we will send ickysoup to spam your DM's with cat images... 😈

**Review by SleepyGemmy — APPROVED** [review]

**Review by Ben10083 — COMMENTED** [review]
So this only gives security access to security network? I feel thats a bit too restrictive, why not give them access to the hallway cameras as well, doesnt really make sense to lock the hallway cameras.

**Comment by mikomyazaki** [comment]
> So this only gives security access to security network? I feel thats a bit too restrictive, why not give them access to the hallway cameras as well, doesnt really make sense to lock the hallway cameras.

I don't think it changes who can access the security cameras at all.

**Pull request merged**
