### PR TITLE
Configurable awaysites / exoplanets loading

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Added the ability to configure if away sites and exoplanets are loaded/generated, budgets, and other settings regarding them.
Minor refactor of some comments.
Resolved an exception for exoplanets generation when archetypes are exhausted.

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]
would it be possible for it to have it be turned off by default for runtime? would be much better for testing things quickly

**Comment by FluffyGhoster** [comment]
> would it be possible for it to have it be turned off by default for runtime? would be much better for testing things quickly

Copy the config file over from the examples and flip the `true` to `false` and it's off by default, that's exactly the idea why I made this

**Review by NonQueueingMatt — COMMENTED** [review]
Not sure if it's too intuitive having a config override and also a map-dependent variable for the away site budget

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
