### PR TITLE
Fixing Ling Once and For All

### PR DESCRIPTION
**Pull request by Geevies**
* Lings now deal heavy damage to all body parts when absorbing DNA, instead of killing and husking. The target now has a chance of surviving.
* Lings now start with 12 genome points instead of 5.
* Lings can now evolve a bone launcher that contains 15 pieces of bone shrapnel. It deals as much damage as a medium pistol bullet, and the launcher disappears once the shrapnel is used up.
* Ling armblades now cleave when attacking.

Let me know if I need to change any of the numbers, maintainers.

Also the bone launcher sprite is a Colt as a placeholder until the PR is approved or closed.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by Butterrobber202** [comment]
one request if its possible. The Changeling "death trance" doesn't appear to be dead anymore with the invention of brainmed. Still has a pulse when checked, and isn't flagged to not do automated emotes like *vomit *cough *gasp.

**Comment by Generalcamo** [comment]
That's not relevant to this PR. Bay made some fixes that can be ported over. This PR touches on another mechanic.

**Comment by TheDanseMacabre** [comment]
If the target isn't killed, how does this impact the internal hivemind and morphs?

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
This PR basically removes morphs and the hivemind -- is that intentional? I think morphs at the very least should be made into a ghostrole similar to borer, to be honest.

**Comment by SleepyGemmy** [comment]
hivemind and morphs were a "bandaid" to the player for being killed, if the player doesn't die now then those features are no longer needed.

**Comment by Geevies** [comment]
too lazy to continue with this one, if anyone sees changes here they like, feel free to grab 'em

**Pull request closed without merging**
