### PR TITLE
New IPC antennae

### PR DESCRIPTION
**Pull request by ParadoxSpace**
A sleek double set.

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
!review

**Comment by ParadoxSpace** [comment]
image

looks smth like this

**Comment by Geevies** [comment]
I'd like to vote for dismissal.

**Comment by skull132** [comment]
Categorical "No" from me.

**Comment by KingOfThePing** [comment]
Nice cat ears, comrade

**Comment by ParadoxSpace** [comment]
why a categorical no @skull132

**Comment by NonQueueingMatt** [comment]
This is a no from me too.

**Comment by ParadoxSpace** [comment]
why.

**Comment by BoryaTheSlayer** [comment]
Sleek triangular antennae that totally carry no resemblance to cat ears whatsoever. That is what you are saying, right?

**Comment by ParadoxSpace** [comment]
they aren't **meant to be cat ears.** they're **just triangular.**

**Comment by Doxxmedearly** [comment]
https://i.gyazo.com/bba1c51e2f4a6dd9afccf13d883da620.png
You really gonna be tryin' to lie to us like that?

**Comment by ParadoxSpace** [comment]
i can't rename the branch.

**Comment by niennab** [comment]
I have to say no to this. I'm fine with it spawning in maintenance but not found in the load out.

**Comment by NonQueueingMatt** [comment]
This is being closed until the loredev's requests are fulfilled.

**Pull request closed without merging**
