### PR TITLE
Changes Orion Miner and Hangar Tech Uniforms

### PR DESCRIPTION
**Pull request by RyverStyx**
image

Changes Orion Miner and Hangar Tech Uniforms so they aren't just recolors of Hephaestus. Kept the existing Mechanist uniform.

### CODE REVIEW

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
This isn't needed
.
This removes the emblematic cargo vest from the technician uniform and the identifying supply yellow from both uniforms.

The style of overalls is already in use by hydroponicists.

Also, breaks the shading convention.

**Comment by RyverStyx** [comment]
> This isn't needed . This removes the emblematic cargo vest from the technician uniform and the identifying supply yellow from both uniforms.
> 
> The style of overalls is already in use by hydroponicists.
> 
> Also, breaks the shading convention.

The cargo vest shouldn't be part of the base uniform since there are already vests as overwear.

The style is most certainly not used by hydroponicists.

The shading can be fixed if others agree.

**Comment by NonQueueingMatt** [comment]
What even is the shading convention? I agree with Ryver here, but I don't exactly what the shading convention refers to.

**Review by JohnWildkins — APPROVED** [review]

**Comment by RyverStyx** [comment]
Shading addressed.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
