### PR TITLE
Decompiler Tweaks

### PR DESCRIPTION
**Pull request by Doxxmedearly**
Decompiler now plays a noise when used to decompile small pests. _Cronch._

Also adjusted the decompiler to be used on more pests besides rats and lizards. It now handles simple mobs up to size 3 (which includes tindalos, diyaab, yithian, etc). This will help bots keep things clean. 

I've excluded cats specifically (size 2.5) because we really don't need maint drones memeing around sucking up station pets. Dogs (even puppies) are excluded by default due to size.

### CODE REVIEW

**Comment by Doxxmedearly** [comment]
!review

**Comment by Pratepresidenten** [comment]
pls put broken bottles into the "Can decompile" pile. I will give you one erp token.
(Unless it is already here, Im a code dumdum)

**Comment by alsoandanswer** [comment]
are broken syringes included or nah

**Comment by Doxxmedearly** [comment]
Probably not. Honestly after talking with Wildkins I'll probably rehaul the whole list and make it tidier. But it's out of the scope of this PR, since it was mostly for mobs and sounds (and now bottles).

**Pull request merged**
