### PR TITLE
You can now lock lockers with alt click

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
title

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Comment by Pratepresidenten** [comment]
Fuck yeah!

**Comment by runecap** [comment]
why was this not already in anyways

**Comment by DronzTheWolf** [comment]
Don't do it, this makes it so you can't bring up the tile menu to search for contents of a locker.

**Comment by VTCobaltblood** [comment]
Click the tile then

**Comment by NonQueueingMatt** [comment]
just altclick the tile and not the locker...?

**Pull request merged**
