### PR TITLE
Fix client view rotation

### PR DESCRIPTION
**Pull request by Lohikar**
Fixes lighting bugs associated with client view rotation + re-enables associated verbs & the hallucination rotation effect.

### CODE REVIEW

**Comment by skull132** [comment]
Merge conflicted from your stats PR.

**Comment by skull132** [comment]
Okay. Can you be evil. And add a config and admin editable (`R_FUN`) option for setting default client rotation and locking it to this? So we can force people to play the game from a specific direction :D

**Comment by Lohikar** [comment]
Alright.

**Comment by Lohikar** [comment]
Turns out this breaks a lot of shit. Not worth fixing all those icons.

**Pull request closed without merging**
