### PR TITLE
Ports graph/node framework from Baystation12

### PR DESCRIPTION
**Pull request by mikomyazaki**
Decided to submit this PR for review to reduce the size of my eventual pipe refactor PR.

Plans are to use this to refactor pipenets/powernets, and maybe to create a storyteller system that will rely on a storyline stored as a graph.

Initialized before atoms because pipes will want to queue themselves in it as they are initialized... but that may change to a LateInitialize thing.

To Do:
- [x] Add extra checks on New graphs to make sure they are sane
- [x] Work out what priority SSgraphs should be

Originally by @PsiOmegaDelta with some small additions. Thanks Psi!

### CODE REVIEW

**Comment by mikomyazaki** [comment]
Reopening to test with a rebase onto current master.

**Comment by mikomyazaki** [comment]
Decided to submit this PR for review to reduce the size of my eventual pipe refactor PR.

**Comment by mikomyazaki** [comment]
!review

**Comment by mikomyazaki** [comment]
!review

**Comment by mikomyazaki** [comment]
Marking with DNM because this is not actually used for anything in its current state. This only needs to be merged when my pipes refactor is ready to go, and that will take some time.

Reviews welcome!

**Review by Geevies — APPROVED** [review]
don't see anything obviously wrong

**Comment by NonQueueingMatt** [comment]
Reopen when ready.

**Pull request closed without merging**
