### PR TITLE
Fixes a Typo in the Tool Belt's Name

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR fixes a typo in the tool belt's name.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Comment by SleepyGemmy** [comment]
!bugfix

**Review by alsoandanswer — APPROVED** [review]

**Review by JohnWildkins — APPROVED** [review]
least esoteric code

**Comment by Arrow768** [comment]
The current name "tool-belt" is the established name since 10 years.
I do not see a reason to change this. (Especially not as a "bugfix")
image

Therefore closed as not wanted.

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
