### PR TITLE
Unathi Resprite

### PR DESCRIPTION
**Pull request by Aticius**
A brand spankin' new resprite for Unathi to touch up their sprites and add some more detail and flavor to their sprites. Guaranteed to upset _someone._ 

Adds a new marking for female Unathi to buff up their waist, if they so choose.

### CODE REVIEW

**Comment by Aticius** [comment]
Travis. BEHAVE.

**Comment by Aticius** [comment]
!review

**Comment by KasparoVy** [comment]
Would really dig a comparison side-by-side fashion showcase sort of deal so we can get a load of these lit lizards

**Comment by KasparoVy** [comment]
Fuk preview images I guess, oh well.

**Pull request merged**
