### PR TITLE
Implements the Wage Gap

### PR DESCRIPTION
**Pull request by LordFowl**
Modifies the money available in employee accounts in the following way based on gender;
Females make 80% of the normal wage they would have received
Neuters or genderless make 70% of the normal wage they would have received.

This applies in addition to RNG, species mods, loyalty mods, and job mods.

### CODE REVIEW

**Comment by LordFowl** [comment]
nani the fuck

**Comment by ComradeCorbyn** [comment]
542 years in the future and we have a wage gap. not to say that it's not impossible, but looking at the circumstances, i'd say that gender-based discrimination is practically non-existent in humanity as well as race-based discrimination. 

the closest thing to this that i could think of happening would likely be species based discrimination, with vaurca and stinky tajarans making the least amount of money compared to humans and skrells.

**Comment by LordFowl** [comment]
It is 442 years in the future. Please read the lore.

**Comment by ComradeCorbyn** [comment]
still 442 years in the future. think we'll still have the wage gap 400 years from now?

**Pull request closed without merging**
