### PR TITLE
QoL tweaks to Xenoarchaeology

### PR DESCRIPTION
**Pull request by Leudoberct1**
This makes some QoL tweaks to Xenoarchaeology to make life easier on them.

This'll be in the changelog too, but I figured I'd list them there:
- Changes the remote control of the isolation chamber air alarms to be set to on, so you don't have to walk in and do it yourself.
- Adds a sulphuric acid dispenser (some artifacts are activated by splashing them with acid)
- Adds a door bolt button to the harvesting room (all the other isolation chambers have one)

### CODE REVIEW

**Comment by Leudoberct1** [comment]
!review

**Comment by KingOfThePing** [comment]
praise be

**Comment by Leudoberct1** [comment]
Fixed the air alarms with some help with coding from Geeves. So, to change the remote control setting of an air alarm, don't use the remote_control var, use rcon_setting. 1 for off, 2 for auto, 3 for on. Tested it and it works.

**Comment by Leudoberct1** [comment]
After doing some work on mapping in Xenoarch to resize it and add somethings, I'm going to close this PR, as the things this adds will be incorporated into the new PR incoming.

**Pull request closed without merging**
