### PR TITLE
Ti'Rakqi freighter fixes, tweaks, and additions

### PR DESCRIPTION
**Pull request by DreamySkrell**
image

```
changes:
  - rscadd: "Adds a xu'xi gas inhaler."
  - rscadd: "Ti'Rakqi Freighter. Adds a hidden cargo compartment."
  - bugfix: "Ti'Rakqi Freighter. Fixes external waypoints."
  - bugfix: "Ti'Rakqi Freighter. Fixes the engineer role being named 'medic'."
  - tweak: "Ti'Rakqi Freighter. Tweaks the shuttle so the rest of the hangar can be accessed."
  - tweak: "Ti'Rakqi Freighter. Reshuffles and tweaks the floors, decorations, and the like, rearranges some things."
  ```

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!bugfix

**Comment by DreamySkrell** [comment]
!review

**Comment by WickedCybs** [comment]
Mapping looks fine. Two more landmarks at the fore and aft might be cool to add, if you think that's a good idea.

**Comment by Butterrobber202** [comment]
skrell stamp of approval

**Comment by DreamySkrell** [comment]
Added two more exterior landmarks, aft and fore. Dunno why I forgot about those.

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
