### PR TITLE
Adds a Himean Industrial Rig

### PR DESCRIPTION
**Pull request by crunchypretzels**
Adds a Himean industrial rig, obtainable via the voidsuit modkit. It is functionally identical to the base variant.
image
Schwann liked it, at least. The image above also is slightly outdated, but I'm so tired as to not give a damn about three pixels of color on the pauldrons.

### CODE REVIEW

**Comment by crunchypretzels** [comment]
!review

**Review by Alberyk — CHANGES_REQUESTED** [review]
Icons are either put in the wrong place or have the wrong name, which is causing travis to fail. Also the modkit won't work because it checks if the item being modified is a clothing piece.

**Comment by crunchypretzels** [comment]
> 
> 
> Icons are either put in the wrong place or have the wrong name, which is causing travis to fail. Also the modkit won't work because it checks if the item being modified is a clothing piece.

The modkit works fine, as the rig control module is a back clothing piece. I don't know if this is actually why it works, but it does; unless there's some arcane reason as to why it works on my test server compared to live, this should be a non-issue.

As for the icons I've got no idea. Adding wippies tag while I find that out.

**Comment by crunchypretzels** [comment]
!wip

**Comment by crunchypretzels** [comment]
!review

**Review by Alberyk — CHANGES_REQUESTED** [review]
Looks like I was wrong. But there is another small issue. Due to how the kit is coded, using it in a rig does not use the kit like it is intended, so you can keep changing the rig back and forth. This can probably be abused.  You should add a check to see if the item being used on is a rig and then remove all of the kit's charges.

**Comment by NonQueueingMatt** [comment]
You need to merge master into your branch for Drone to pass.

**Review by JohnWildkins — APPROVED** [review]

**Comment by crunchypretzels** [comment]
Closing this while I redo some stuff. Honestly, I'd forgotten it was open!

**Pull request closed without merging**
