### PR TITLE
Biesel farm

### PR DESCRIPTION
**Pull request by CactusMouth**
Hey, this is my first PR in Aurora, so if I do something wrong do tell me.

This is a small farm in Biesel, containing a hut and farm, and a radioactive crash site next to it. Some basic loot for the players like a rifle with ammo, axe within the closet and the like.
StrongDMM-2024-04-23 18 49 48

I'm also  **attempting** to make an area for this so that the stove works without powering the entire plane, so if you have any feedback in the meantime, do let me know! 

UPDATE: Changelog added, along with the removal of the Radiation. 
StrongDMM-2024-04-24 16 32 11

### CODE REVIEW

**Comment by lavillastrangiato** [comment]
I would not suggest a "radioactive crash site" on one of the most populated planets in the Orion Spur. This is something that gets noticed.

You're also using the wrong damage decals for that crash site; a couple of them are wood damage decals.

Don't make your ruin site perfectly square; I forget how right now, but you can use transparent turf tiles to use the tiles from the exoplanet so it looks a little more naturalistic.

You will also need a changelog, which can be found within your HTML folder. Check out the README file to learn what a changelog is, since you seem to know how Git works.

**Comment by CactusMouth** [comment]
> I would not suggest a "radioactive crash site" on one of the most populated planets in the Orion Spur. This is something that gets noticed.
> 
> You're also using the wrong damage decals for that crash site; a couple of them are wood damage decals.
> 
> Don't make your ruin site perfectly square; I forget how right now, but you can use transparent turf tiles to use the tiles from the exoplanet so it looks a little more naturalistic.
> 
> You will also need a changelog, which can be found within your HTML folder. Check out the README file to learn what a changelog is, since you seem to know how Git works.

Thanks for the advice, I'll get it updated soon.

**Comment by CactusMouth** [comment]
!review

**Comment by DreamySkrell** [comment]
> > Don't make your ruin site perfectly square; I forget how right now, but you can use transparent turf tiles to use the tiles from the exoplanet so it looks a little more naturalistic.

> Thanks for the advice, I'll get it updated soon. I've ensured the tiles are the same with those on Biesel though.

image

LVS meant there by the transparent turf tiles `/turf/template_noop`.
When generating planets and ruins, these turfs on ruins are replaced with planet's turfs (or rocks, or vegetation, or etc), which means it's going to look a lot smoother and more natural even if the ruin spawns inside a mountain or a lake.

Other than this, the ruin looks good.

**Review by Eyeveri — APPROVED** [review]

**Comment by FluffyGhoster** [comment]
Merge master (update master first)

**Comment by CactusMouth** [comment]
> Merge master (update master first)

Should be done now.

**Comment by FluffyGhoster** [comment]
> > Merge master (update master first)
> 
> Should be done now.

You didn't push the merge or something, because I don't see it having the updated CI

**Comment by NonQueueingMatt** [comment]
reopen when the CI is updated

**Pull request closed without merging**
