### PR TITLE
Ranger ship updates

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
WIP. Adds a non-box shuttle and a power system. Will need a little bit more work before it can be merged, though

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!wip

**Comment by Greenjoe12345** [comment]
wouldn't it be better to have the shuttle dock flush with the ship so you can board/exit without needing to go through the airlocks every time?

**Comment by RoboticVodka** [comment]
> wouldn't it be better to have the shuttle dock flush with the ship so you can board/exit without needing to go through the airlocks every time?

It would absolutely be less hassle, but also -soul.

**Comment by NonQueueingMatt** [comment]
Stale

**Pull request closed without merging**
