### PR TITLE
Visor Sunglasses + HUDs

### PR DESCRIPTION
**Pull request by WickedCybs**
Originally was just going to be a port of the bay medical visors, but I expanded the scope, tweaked the sprites and made some more versions that will be unique to Aurora, like a security variant as well as on and off states to make them function similarly to the aviators.

This is still in progress since I might make a few more variations. Also need to actually add them to the code and have them selectable.

This is the medical visor.
image
image

Further Edit: 

The three variants.
image

### CODE REVIEW

**Comment by WickedCybs** [comment]
Technically finished but need to decide now if this is worth adding, for myself.

**Comment by Geevies** [comment]
> 
> 
> Technically finished but need to decide now if this is worth adding, for myself. I might have been looking back at them with rose tinted glasses (no pun intended).

it looks good imo

**Comment by NonQueueingMatt** [comment]
I like them. Don't see why not.

**Comment by WickedCybs** [comment]
!review

**Review by Geevies — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
