### PR TITLE
Bandana recolour

### PR DESCRIPTION
**Pull request by AmoryBlaine**
Recolours the three bandanas, and makes the obj sprite a bit more reasonable. If it's not liked, I'll redo it again.

### CODE REVIEW

**Comment by AmoryBlaine** [comment]
!review

**Comment by alsoandanswer** [comment]
shading could be improved

**Comment by AmoryBlaine** [comment]
image

This is what it looks like. Or did you mean the obj sprites? Yeah, they're, mostly just to go in line with all the other 'cloth' items. The headdress sprites, the armbands, ect.

**Comment by SleepyWolfe** [comment]
what if you just made it recolourable instead of selectable from those 3

**Comment by AmoryBlaine** [comment]
> 
> 
> what if you just made it recolourable instead of selectable from those 3

That can come later once someone wants to help me code that, since all I currently know is swapping out icons LOL

**Pull request merged**
