### PR TITLE
Residential Deck Stairwell and EVA Tweaks

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR moves the residential lifts to deck 1, adds a residential stairwell to the central stairwell on deck 1, and remaps EVA.

## changes
- moves the residential lifts to deck 1 next to the main elevator.
- adds a residential deck stairwell on deck 1 in the central stairwell.
- moves the auxiliary custodial closet to where the old residential lifts used to be.
- adds a second door to EVA directly opposite of the elevator for easier and more obvious access.
- remaps EVA, making it more suited for expeditions.
- tweaks the auxiliary hangar, pilot room, and the security substation to make better use of space.

## screenshots
<details>
<summary>🖼️ click to view</summary>

image
**figure 1:** the new residential lifts location.

image image

**figure 2:** the new residential deck stairwell (mockup) | figure 2.1: the actual temporary implementation.

image
**figure 3:** the new auxiliary custodial closet location.

image
**figure 4:** the new washroom.

image
**figure 5:** the new EVA area.

image
**figure 6:** aux hangar after tweaks.
</details>

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Comment by TheDanseMacabre** [comment]
Why do we need more pointless sit-down areas that won't be used? We already have fifty.

**Comment by SleepyGemmy** [comment]
> Why do we need more pointless sit-down areas that won't be used? We already have fifty.

tweaked.

**Review by WickedCybs — APPROVED** [review]
I tested it and all criticism aside, it works and I don't see anything missing.

My only nitpick is I think it might not be a good idea for the residential stairwell to be a thing that's mapped in. People might get inside and it could be a little confusing to run into a fake airlock you can't use.

image

**Comment by SleepyGemmy** [comment]
> My only nitpick is I think it might not be a good idea for the residential stairwell to be a thing that's mapped in. People might get inside and it could be a little confusing to run into a fake airlock you can't use.

replaced it with fake shutters in case i want to map it in in the future as a fully functioning thing. (i.e. the space is reserved.)

**Review by Alberyk — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
