### PR TITLE
Unapologetic Vaurca Buffs

### PR DESCRIPTION
**Pull request by LordFowl**
Vaurca now spawn with additional phoron reserves in their internal tank, K'ois and K'ois products supply more phoron when consumed, and K'ois bars are cheaper in the vending machines altogether hopefully rendering the mechanic less of a round-determining chore while keeping it an appreciable mechanic.

Added a new Vaurca beverage to the cola vendors, and K'ois paste to the bartender's soft drink dispenser.

Added a new plant gene, TRAIT_SPOROUS, which results in the affected plant spreading spores when it reaches a new harvest cycle, whenever it is harvested, and has a chance to do so when it dies. These spores contain both all of the reagents in a plant as well as the possibility of spawning new versions of the plant.  K'ois spawns with such a trait.

### CODE REVIEW

**Comment by BurgerLUA** [comment]
Seems like a good thing to have especially when there isn't always a gardener or an atmospheric technician on the station. Dionaea have emergency flares, so it would make sense for Vaurca to have an emergency item for themselves.

**Comment by Lohikar** [comment]
Does not compile.

**Comment by Arrow768** [comment]
According to the lore team (especially the varca maintainer) the prices for the kois bar should be kept as is and the the price for the kois punch increased to 90 credits

**Comment by LordFowl** [comment]
Players have complained that the price is prohibitively expensive. These items are still among the most expensive items there are - I ask that the lore team consider their position from a gameplay standpoint.

**Comment by BurgerLUA** [comment]
Could always balance it by making the K'ios bars a generally last resort idea to eat, or introducing a cheaper alternative. It will give the Vaurca proper nutrition however it should contain something that would hinder a Vaurca eating it as it's low-grade or watered down with chemical substitutes.

**Comment by skull132** [comment]
Sent to Sleepy for approval.

**Comment by Bygonehero** [comment]
On average players seem to start with more than 60 credits, with very few instances of anyone starting lower. Vaurca are the only marginalized species really, and our mechanics should reflect that. I do want players to be able to at least on average afford one item from a vendor, so I think 60 credits is a fair cost for the kois bar and drink.

**Comment by LordFowl** [comment]
Prices adjusted accordingly.

**Pull request merged**
