### PR TITLE
Reduces cost of Journalism app to 2 GQ

### PR DESCRIPTION
**Pull request by feartheblackout**
title

### CODE REVIEW

**Comment by feartheblackout** [comment]
!review

**Comment by FluffyGhoster** [comment]
Why is it being reduced, though?

**Comment by feartheblackout** [comment]
> Why is it being reduced, though?

The download speed on PDAs is very slow. It takes a few minutes just to download the program as it currently stands at 6 GQ.

**Review by DreamySkrell — APPROVED** [review]

**Comment by FluffyGhoster** [comment]
The problem with reducing the cost is, it also allows for more programs to be stored on a PDA, and I am not sure on the balance implications since this program is like a camera access; Why not simply put it in the preset of the Journalist? That way the Journalist doesn't have to download it at all, it's preinstalled in his PDA

**Review by FluffyGhoster — APPROVED** [review]

**Pull request merged**
