### PR TITLE
Learner Slot Increase

### PR DESCRIPTION
**Pull request by Geevies**
* Engineering apprentice, lab assistant, and medical intern slots have been increased by one, for a total of 3.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Review by Chada-1 — APPROVED** [review]

**Review by fernerr — APPROVED** [review]

**Comment by Aboshedab** [comment]
Why is security exempt?

**Comment by fernerr** [comment]
> Why is security exempt?

Out of the learner roles, an additional cadet slot would boost security's oftentimes overly large department with another able body. The other learner roles do not affect game balance in the same way.

**Comment by Aboshedab** [comment]
> > Why is security exempt?
> 
> Out of the learner roles, an additional cadet slot would boost security's oftentimes overly large department with another able body. The other learner roles do not affect game balance in the same way. That's what I assume their reasoning is either way.

Understandable.

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
