### PR TITLE
(this is a bugfix) pax liturgica fixes

### LINKED ISSUE #16839: [Bug]: Kvass bottles lack empty sprite
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

The recently added bottles of Neubach Original Kvass have no sprite when emptied, turning them invisible.

I haven't tried any of the other new Dominian drinks yet to know if this is an isolated case or if they all need to be looked at.

### How to reproduce

1. Drink/pour out an entire bottle of kvass
2. hey why can't I use my hand there isn't anything in i--oh

### Round ID

_No response_

### Staff ckey

_No response_

### PR DESCRIPTION
**Pull request by crunchypretzels**
fixes #16839

Adjusts the shading on the Zavodskoi capes. The suit sprites were using an outdated version.
Adds empty versions of the Dominian drinks.
Fixes a missing wine glass.

any other issues blease ping me on Discord

### CODE REVIEW

**Comment by crunchypretzels** [comment]
!review

**Comment by crunchypretzels** [comment]
!bugfix

**Comment by crunchypretzels** [comment]
!review

**Comment by crunchypretzels** [comment]
!bugfix

**Review by alsoandanswer — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Review by SleepyGemmy — APPROVED** [review]

**Pull request merged**
