### PR TITLE
Replaces big air tank sprites.

### PR DESCRIPTION
**Pull request by Belsima**
images

From the Eris. Putting this up essentially to see if people like Eris sprites or not.

### CODE REVIEW

**Comment by skull132** [comment]
Retargeted into development, as master is only for fixes.

**Comment by Belsima** [comment]
My bad! Still new at this. I'll aim for dev with all my next PRs.

**Comment by Belsima** [comment]
Closing to rebase to dev and fix.

**Comment by Lohikar** [comment]
We rebased it for you, no change is required on your end.

**Comment by skull132** [comment]
Ye it was meant to read:

> [I] retargeted [this PR] into development, as master is only for fixes.

**Pull request closed without merging**
