### PR TITLE
Fix messages not being bolded for nearby ghosts if the speaker is inside a location (held pAIs, inside exosuits, etc)

### PR DESCRIPTION
**Pull request by AlaunusLux**
Title. Performance concerns here, since this is called for each observer each time a message is sent. Not sure if get_area or get_turf is more performant.

May not be worth it if it effects performance.

### CODE REVIEW

**Comment by AlaunusLux** [comment]
!bugfix

**Comment by AlaunusLux** [comment]
!review

**Comment by AlaunusLux** [comment]
I did some tests, running each statement a thousand times each time a message was sent. 

It doesn't seem to make a difference, each test taking 0.17 seconds, or .2 seconds, or similar. 
Every now and then there is a variance of .01s or so, I suppose based on background tasks, and each method has taken longer than the other two at least once. The largest variance observed was +.03s for get_turf, once.

image

**Comment by FluffyGhoster** [comment]
Merge master to fix the CI

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
