### PR TITLE
adds ninja hardsuit selection

### PR DESCRIPTION
**Pull request by kyres1**
A new hardsuit selection for ninjas, basically. Adds ninja equipped variants to all included RIGs. Most of these are just variants of their equipped version, sometimes with a gun and always a door hacker. Most of these RIGs can **not** use ninja modules, meaning that you can't salvage the batshit OP modules from the ninja RIG to be a teleporting meme in a breacher. 

Also, adds a mounted plasma gun for RIGs. It's used nowhere besides this selection.

The full selection is below.

meme

### CODE REVIEW

**Comment by OneOneThreeEight** [comment]
incredibly cool with massive RP potential, recommend the feedback thread tho

**Comment by kyres1** [comment]
!review

**Comment by Kaedwuff** [comment]
If I'm understanding this correctly, you are adding me as complete replacement to the ninja rig? And you can't transfer its modules to the new one you pick?

Sure, okay. But you kind of skipped out on the breacher suit having anything to start out with. It doesn't matter if you're a walking tank all you can do is walk around, inject yourself with chemicals, and see through walls. I would consider adding a few toys so it's not objectively the worst rig to spend all of your telecrystals on.

**Comment by kyres1** [comment]
> Some kind of weapon would help too, or a way to penetrate walls. It is called a _breacher_ suit

A drill will do, will do that soon.

**Comment by kyres1** [comment]
Going to be working an einstein RIG and a loadout into this by human lore request. It is unrelated to the rest of the PR and will be used for events in the very near future.

**Pull request merged**
