### PR TITLE
Golden Deep ghostrole remap

### PR DESCRIPTION
**Pull request by hazelrat**
**This is up for review.**

- Remaps the Golden Deep ghostrole to be better.
- Includes new uniforms for menial Golden Deep synthetics, and new Golden Deep voidsuits.
- Includes the clothes dyer, a new item that changes the colour of recolourable clothing to whatever the user wishes. Adds it exclusively to the Golden Deep ship, so the merchant can customise their drip as much as if they were in the loadout, since pretty much all of the newer GD clothing is recolourable. Works for both the regular colour and the accent colour.
- Uses submaps for the warehouse.
- A few semi-empty spaces exist right now which will be filled once the sprites for what's going to go there are complete, particularly in the great hall.
- The armoury is intended to be pretty strong - it's a cargo freighter with very valuable cargo, so you have an unusually hard fight to get said cargo if you board. It contains a laser rifle, a combat shotgun (with a box of EMP shells, notably, with the idea that the Hoplan should be particularly good at restraining other synthetics), two energy glaives, and two pistols intended for the Hoplan. There are also two machine pistols and two energy carbines, intended for if the Hoplan wish to arm the rest of the crew.
- Adds the ship to Valley Hale - has the OK from lore, as far as I know.

### CODE REVIEW

**Comment by hazelrat** [comment]
!wip

**Comment by hazelrat** [comment]
!review

**Comment by DreamySkrell** [comment]
image
pipes

**Comment by DreamySkrell** [comment]
image
spawn point need name change

**Comment by hazelrat** [comment]
@DreamySkrell Both implemented!

**Review by DreamySkrell — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
