### PR TITLE
Making skills useful

### PR DESCRIPTION
**Pull request by Sindorman**
This PR make's character skills actually be applied in the game. The idea is that skills will not give you penalty, but rather slight advantages. Example is if you are wrenching an atmos pipe, you will have reduced delay depending on your level of construction skill and atmos skill. Delay reductions range from 0 to 45%.

**New skills**:

- Prospecting - reduces delays with mining equipment

- sanitizing - reduces delays with doing cleaning

**Current skills that gives you advantage**:

- Construction: reduces delay for constructing or repairing anything that has delays

- Electrical: reduces delay installing/uninstalling cables or circuits, boards.

- EVA: reduces delays getting into RIG, sealing/unsealing RIG and how long it takes to climb up using acutators

- Forencsincs: currently reduces delay of using microscope

- Devices: reduces delay for constructing mechs, hacking devices that are not computers, using debugger, use pin extractor, hacking secure breifcase, instaling RIG modules, placing warp beacon,  performing maintenance on borgs/drones, resetting breaking box,  . Also reduces time it takes for IPC to brute force Vaurca puzzle box.

- Computer: reduces delay it takes to use hacktool.

- Medical: reduces delay for applying spliter, injection, inhalers, breather, CPR,  yank out object, undislocate limb.

- Chemistry: reduces delay on makeshift worksatation chemistry table.

- Botany: reduces all of hydroponics delays like bees, trays, etc.

- Cleaning: reduces delays for cleaning microwave, replacing light bulb replacer, using soap, mopping, washing hands, washing things, using rag.

- Cooking: reduces delay for cutting animal hide

- Prospecting: reduces delay for pumping KA, mining turfs, rocks, chiseling, using scanner, ladders, placing warp beacon.

- Atmos: reduces delay of welding/wrenching atmospheric devices and pipes. Stacks with construction skill reduction

- Weapons: reduces delay to plant c4, plant landmines, unjam gun, crank icelance, draw crossbow, reload leyon pistol. When firing with weapons the accuracy is buffed based on skill

- Combat: reduces time to pin someone to the ground, time to takes to slit throat, time to dislocate joins(stacks with medical skill), time to trample. Adds a chance to block someone's attack based on skill.

- Engines: reduces time it takes to weld field generators(stacks with construction skill)

- Pilot: reduces time to climb in the mech, how long it takes to use clamp, how long it takes to use mining drill

TODO:

- [x] Give accuracy increase based on Weapons skill

- [x] Add chance to block melee attack based on combat skill

- [ ] Add penalties for low skill

- [ ] Add limit to how many skills points people can have based on age and species

### CODE REVIEW

**Comment by Sindorman** [comment]
Any suggestions for more things that should be affected by skills or tweaks to delay are welcome

**Comment by KasparoVy** [comment]
Niiice.

**Comment by Sindorman** [comment]
!review

**Comment by NonQueueingMatt** [comment]
As I've already said on discord; **skills being only buffs is a no-go.** That's too gamey for my liking and only serves to raise the average task times. This is also incompatible with combat skills, where there being no debuffs matters the most. There also need to be limitations to how many skills you can take and this has to depend on the species and age.

**Comment by Alberyk** [comment]
As I said; this also need to add a limit to how many people can get, and I believe that the point should increase with how old your character is and also in relation to their species. For example: humans can get one point in five years, while skrell would require ten or so years to get the same number of points, but they can pick a higher age.

**Comment by Sindorman** [comment]
I will implement your both requests.

**Comment by NonQueueingMatt** [comment]
PR's been dead for two months plus full of conflicts. Closing.

**Pull request closed without merging**
