### PR TITLE
Wearable wet floor sign

### PR DESCRIPTION
**Pull request by alsoandanswer**
You can now wear the wet floor sign.
Also tidies up some code here and there.
Adds some descriptions too.

It provides extremely minor armor.

6pkDG5MkUa

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by alsoandanswer** [comment]
!review

**Comment by alsoandanswer** [comment]
!review

**Comment by alsoandanswer** [comment]
!review

**Comment by KasparoVy** [comment]
Lmao, hell yeah. Modern space fashion

**Pull request merged**
