### PR TITLE
Adds a wall under the pharmacy's SmartFridge

### PR DESCRIPTION
**Pull request by sheeplets**
People keep unwrenching it to gain access and do chemistry-related things that they shouldn't.

### CODE REVIEW

**Comment by sheeplets** [comment]
!bugfix

**Review by FluffyGhoster — CHANGES_REQUESTED** [review]
Grinding down premade pills to have them in a more convenient form, as well as dispensing from premade containers (when available), are perfectly valid options, you'd need to put an empty cartridge dispenser and a grinder somewhere to mantain that. Perhaps upstairs, since noone uses most of it anyways.

**Comment by Roostercat12** [comment]
Pills can be dissolved in 1u of Inaprovaline and have the same effect as crushing them in the grinder

**Review by NonQueueingMatt — APPROVED** [review]

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]

**Comment by NonQueueingMatt** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]

**Comment by FluffyGhoster** [comment]
I didn't knew pills could be dissolved in inaprovaline, though it sounds less involved (aka more boring) than grinding down pills, so i'm ambivalent on that alternative, but it's just a personal preference.

Either way, walls cannot be under the fridge (or any other item), the UT will not let such a map state through, you need to put the fridge somewhere else if you want a wall there.

**Comment by sheeplets** [comment]
avatars-GujBa8wkGP1FmylY-OLjg5Q-t240x240

Thanks, Kyres.

**Pull request closed without merging**
