### PR TITLE
Fixes the SCC Agent Uniform Sprite.

### PR DESCRIPTION
**Pull request by WickedCybs**
The left facing sprite of the SCC uniform had its sleeve rolled up on its normal state. The rest of the uniform showed unrolled sleeves. I fixed that by giving them back their sleeve there.

### CODE REVIEW

**Comment by WickedCybs** [comment]
!bugfix

**Comment by WickedCybs** [comment]
!review

**Comment by WickedCybs** [comment]
Example. This is its non-rolled up state.

image

**Comment by WickedCybs** [comment]
Screen Shot 2021-05-25 at 9 00 14 PM

I am getting this error for now, so I think it needs to wait a few hours.

**Review by Casper3667 — APPROVED** [review]

**Review by Geevies — APPROVED** [review]

**Pull request merged**
