### PR TITLE
Added a TCFL gear crate, and revamped the Dominia crate

### PR DESCRIPTION
**Pull request by Generalcamo**
The TCFL crate allows mercs, revs, and other antagonists to gear up as if they were part of the TCFL. Maybe your group decided to steal the gear, or you went rogue, or you are legitimate but given bad orders, this crate allows you to make up a story. This crate is geared towards offensive firepower at the cost of defensive capability; this is the only group crate and single crate with rigs for everyone, but these are the worst combat rigs in the game and there are no voidsuits. You have armor as an alternative option but it is not the greatest armor. To make up for this, you have a decent amount of firepower available, plus energy shields and energy knives for everyone. 

The Dominia crate was rather lacking, having no uniforms and no ranged weapons. These were added a few months ago in preparation for a future off-ship; these have been incorporated into the Dominia crates. Your sidearm options are lacking, but you have a guaranteed melee weapon available. Effectively it's a more melee-focused Sol crate.

While doing this, I noticed the Eridani crate had the SCC Combipistol. This was replaced with two X7s as current lore does not support the EPMCs getting the combipistol. I also granted them EPMC uniforms to more properly dress as an Eridani outfit.

### CODE REVIEW

**Comment by Generalcamo** [comment]
!review

**Comment by Generalcamo** [comment]
!wip

**Comment by Generalcamo** [comment]
I was requested to add the new voidmens' suits as well. This will require a bit of time while I get things cleaned up to allow this to be made into a paint kit.

**Comment by Generalcamo** [comment]
!review

**Review by Alberyk — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
