### PR TITLE
Skrell can now speak Sol Common

### PR DESCRIPTION
**Pull request by VTCobaltblood**
Loredev request.

### CODE REVIEW

**Comment by LordFowl** [comment]
Currently the assumption is that every species gets a unique language. Things like "Well, the Skrell and humans are so buddy buddy, doesn't it make sense that Skrell should be able to speak Sol Common" falls apart entirely when you realize the same justification can be made quite easily for _any_ species to speak Sol Common, or any other non-biologically restricted language. Until the loredevs either decide that every species should be able to speak every language I don't see this as an equitable change.

Additionally, doesn't this just further the idea that Skrell are just humans, but slightly better?

**Comment by VTCobaltblood** [comment]
I'd prefer if this was discussed in the lore channel and not this PR - it wasn't my initiative to open this. 
Also, skrell can also stomp and kick now. Loredev request too.

**Comment by LordFowl** [comment]
PR pertinent discussion is not held in discord. You are free to create a feedback thread.

**Comment by VTCobaltblood** [comment]
I don't see why this needs a feedback thread - if it does need such, I'd prefer it's created by loredevs rather than me, because it's not me who's proposing this feature. Sleepy was already asking around discord about this and the response was generally positive.

**Comment by ParadoxSpace** [comment]
https://forums.aurorastation.org/topic/11186-give-skrell-sol-common/

**Comment by SleepyWolfe** [comment]
Please keep this frozen until the next human loredev/current maintainer decides on this. thanks

**Comment by VTCobaltblood** [comment]
Separating skrell martial arts into a separate PR

**Comment by Arrow768** [comment]
Closing this PR as each species should have it´s own unique language that can not be used by other species unless they acquire some kind of device that allows them to understand this language.
Naturally such a device should be rather expensive and uncommon.

The preferred option to implement this would be the aforementioned implants.

An acceptable alternative would be to create a intermediate language between sol common and skrell which would grant a partial understanding of sol / skrell if learned by skrell / humans. (Like we have with SiikTau).

Feel free to reopen / recreate the PR once either of these options has been implemented.

**Pull request closed without merging**
