### PR TITLE
Insulated Stungloves retain their Siemens coefficient

### PR DESCRIPTION
**Pull request by Ezuo**
Changes the code for gloves of the yellow and fyellow type to retain their Siemens coefficient after wires have been added to them. Also a changelog file.

### CODE REVIEW

**Comment by skull132** [comment]
Could you explain the reasoning for this? It's not a bug, for one. Adding wires to something will very much make it conduct electricity, hence the spike. Plus, it's also a pretty good trade-off.

**Comment by Ezuo** [comment]
Well, its a tweak. I marked it as such in the change log. Never said it was a bug.

As for the reasoning, I'd assume that insulated gloves are made of/are lined with a material that blocks electric current. That's why they are insulated. The wires and power cell are purely external constructions on top of this material, so none of it should pass through to the user.

It makes sense that electrical feedback going the opposite direction would make the gloves more conductive, but only to the exterior. If the gloves are made of insulated material, this shock should dissipate as normal.

**Comment by skull132** [comment]
That's not how wiring and conductivity works, though. It doesn't much care for the direction of the current (unless you start using fun things, like diodes, but we're only discussing wires and insulation).

The reason why adding wires to gloves makes them more conductive is that you have a set of wires with exposed ends either taped to the surface of your gloves, or running through the inside. In the latter case, you've basically made holes in your insulating fabric through which current can jump. In the former case, you are left with two wires with exposed ends dangling somewhere around your wrist. Which can also end in your electrocution. (You won't insulate them, as you're expecting to hook them up to a battery later on.)

**Comment by skull132** [comment]
Ye, sorry, we decided that this is not in favour of balanced gameplay.

If you wish to give it another shot, I'd suggest putting up a suggestion thread and seeing if the community wants this. Until then, the staff decision is a "No", however.

**Pull request closed without merging**
