### PR TITLE
Crayon Sprite Fix

### LINKED ISSUE #17809: [Bug]: Crayons have no sprite in the box
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Unsure if the crayons have a sprite outside of the box, however, those inside the box are not there. 

image
image

### How to reproduce

1. Obtain box of crayons
2. See spriteless crayons
3.  Optional: Check description of box to make sure it has the crayons in it and isn't a deceptively empty box

### Round ID

All of them

### Staff ckey

_No response_

### PR DESCRIPTION
**Pull request by Acetrea**
Fixes #17809

### CODE REVIEW

**Comment by Acetrea** [comment]
!bugfix

**Comment by Acetrea** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]
You know, since they're all a crayon subtype, you can just set the icon from the crayon parent.

**Comment by Acetrea** [comment]
> You know, since they're all a crayon subtype, you can just set the icon from the crayon parent.

Yeah... that would be better/simpler in case more crayons are added later. I'll change it to that.

**Pull request merged**
