### PR TITLE
Another PR in the Uniform Saga

### PR DESCRIPTION
**Pull request by alsoandanswer**
1. Adds the old grey PMCG uniforms as an alt option.
2. Accessories relating to PMCG have been updated with new pallete. Old grey accessories are alt options.
3. PMCG Medical has gotten the same treatment as PMCG Security.
4. Adds alternate corporate detective uniforms similar to the old alternate detective uniform.

Anyway, that should be the long and short of it.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by sheeplets** [comment]
image

This was one of the most requested EPMC holdovers we re-added, and I'd appreciate if we kept it.

**Comment by alsoandanswer** [comment]
> image
> 
> This was one of our most requested EPMC holdovers, I'd appreciate if we kept it.

It is ridiculously out of place compared to every other EPMC sprite. If you could suggest a suitable adjustment, I'll be happy to change it.

**Comment by sheeplets** [comment]
> It is ridiculously out of place compared to every other EPMC sprite. If you could suggest a suitable adjustment, I'll be happy to change it.

The PMCG is a diverse corp with a number of different subcontractor groups, it's feasible they aren't 100% uniform and the new outfits looking the way they do now is entirely and intentionally by your own doing. Nevermind that this one in particular was readded by the request of Aurora's playerbase. It's not "ridiculously out of place", you made it out of place. Despite us voicing our opinions that we liked them as they were, and despite criticisms given about the new scheme you chose. I like this one, and I'd like it to stay as an alternative alongside your own design. Not to speak ill of the baseline. Other people have mirrored similar sentiments in the past and you've either ignored them outright or met them halfway with your own changes to placate them so they'd throw their hands up and say "okay, fine".

I've asked the human lore team and it's my understanding you haven't sought their input on these at all. It reeks of bad faith and gives the impression that you do what you want, when you want, regardless of what anyone else wants. I don't agree that changes are necessary just because you demand them, I think it's fine as it is now.

**Comment by VisVirific** [comment]
> It is ridiculously out of place compared to every other EPMC sprite. If you could suggest a suitable adjustment, I'll be happy to change it.

We have a lot of "ridiculously out of place" sprites that either a) Don't Match, b) Are Very Old, c) Temporary Placeholders that nobody bothered to touch. This specific argument as well I find funny considering you also tried to port the [Tau Ceti Station Skrell resprites](https://github.com/Aurorastation/Aurora.3/pull/14369) when it clearly didn't fit in Aurora.

This uniform is, like sheeplets said, one of the most requested EPMC holdovers. Intentionally removing it after everything feels like you have a grudge and you _personally_ want it gone without consulting anyone else about it, regardless of everything that has been said. It's one thing to remove something for removal sake. It's another to remove it **again** after it's been **re-added** on purpose. Even more so that you still didn't mention the removal of that uniform **AGAIN**.

I'd recommend keeping it as an alternative option, like how you are currently keeping literally every single other uniform as an Alt Option. The ``epmc_emt`` is still distinguishable as different from the security uniforms as well, especially considering that the ``epmc_ft`` and ``pmc_invest`` are practically the same

**Comment by alsoandanswer** [comment]
the uniform has been added back in the previous commit
the highlights have simply been changed to blue

alright that is all

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
/obj/item/clothing/glasses/sunglasses/sechud/pmc/alt no worn sprite
/obj/item/clothing/glasses/sunglasses/sechud/aviator/pmc/alt no object sprite
/obj/item/clothing/under/rank/medical/psych/pmc/alt no object or worn sprite
/obj/item/clothing/head/surgery/pmc/alt no object or worn sprite
/obj/item/clothing/under/rank/medical/surgeon/pmc/alt no object or worn sprite

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
