### PR TITLE
Vaurca Bridge Crew

### PR DESCRIPTION
**Pull request by DreamySkrell**
changes:
  - tweak: "Allows Vaurca Bridge Crew."

it is illegal to deny vaurca bc

I'd be willing to code anything else if needed to make this happen. Like for example, C'thur have the loyalty implants in Nrallak that put them in hibernation if they get conflicting orders. Perhaps SCC bugs could get something similar even if only just as fluff.

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
This will need lore approval

**Comment by desvenlafaxine** [comment]
Hi, just so it doesn't look like this PR is a meme...

I wanted Vaurca to be bridge crew before the introduction of the Horizon and I had some discussions with Cael I think and some maintainers where this could be possible. However, at the end it was decided against because it was deemed that bridge crew would have authority while in expeditions. I didn't push it further because the Horizon had yet to be introduced and it seemed reasonable.

However, it looks like this has changed. Maybe it's because there's more heads of staff playing all time now, but from what I've seen (and from what other players say as well), bridge crew don't really have any authority. They're helmsmen—it's like arguing Wesley had authority on the Enterprise because he sat next to Picard. Therefore, I do think Vaurca bridge crew are definitely a possibility now. 

I'm aware of balancing species racism and gameplay. I do want Vaurca to be enjoyable to more people and have more options without overstepping a hard boundary (actual heads of staff). I also don't think Breeders should be bridge crew and I'll never push it. But we have seasoned Vaurca pilots, especially Zo'ra Warriors that fought in the old TCFL, and I think it's fair the let the bugs fly now.

**Comment by DreamySkrell** [comment]
lore approved

**Review by FluffyGhoster — APPROVED** [review]
Lore signed it off
Up to maintainers for acceptance

**Comment by Bear-the-bare** [comment]
> However, it looks like this has changed. Maybe it's because there's more heads of staff playing all time now, but from what I've seen (and from what other players say as well), bridge crew don't really have any authority.

To be clear this has not changed. Without a head of staff present, the bridge crew holds authority over the away team.

**Comment by FluffyGhoster** [comment]
Adding update wiki tag as the wiki will need to be updated to reflect what indicated by Bear above, if this PR gets accepted

**Review by Geevies — APPROVED** [review]
i like this

**Comment by NonQueueingMatt** [comment]
Our concern with this is that vaurcae can be biologically forced to obey an entity, and so it doesn't really make sense for them to receive authority on flying the SCC's flagship. This also introduces rather niche scenarios that would make additional restrictions necessary (like commanding expeditions or being given authority by the XO if needed).

**Pull request closed without merging**
