### PR TITLE
Make Mobs with the FLB hairstyle trip occasionally

### PR DESCRIPTION
**Pull request by Pacmandevil**
_No Description provided_

### CODE REVIEW

**Comment by Ezuo** [comment]
+1

**Comment by verywhiterabit** [comment]
= fan

**Comment by CompleteGarbage** [comment]
god bless space america

**Comment by Zuhayr** [comment]
You should check `lying` do they don't fall over while already on the ground.

**Comment by printer16** [comment]
I'm almost certain this is a meme PR.

**Comment by NonQueueingMatt** [comment]
cleanse the FLBs

**Comment by chaoko99** [comment]
I wonder if it'd be possible to bloody the FLB when someone walks in blood?

**Comment by TheGreatJorge** [comment]
I bet it totally would. But why stop there?

**Comment by OneOneThreeEight** [comment]
Printer is clearly a weeb. +100 support.

**Comment by HeyBanditoz** [comment]
Very important PR. Merge ASAP.

**Comment by Mark9013100** [comment]
👍

**Comment by Pacmandevil** [comment]
Lohi's PR now boyes

**Comment by skull132** [comment]
GarnAboo agree that the PR is too meme. Will be closing tomorrow if there's no reasonable objection.

**Comment by chaoko99** [comment]
I'm probably going ot just remove the fucking hairstyle at some point. You should not be able to have something like that in medical. You shouldn't be able to in Security. Cargo? Fuck off. Science? Fuck off. Engineering? You would literally be fired if you didn't get scalped first by your own retardation.

There is literally no reason that should be in the game. Save for maybe wizards or some shit.

**Comment by HeyBanditoz** [comment]
Give this man a medal.

**Comment by chaoko99** [comment]
You're indirectly enabling bad RP, by not making these shitty things unappealing.

**Comment by HeyBanditoz** [comment]
I am?
What are you even on about?

**Comment by Pacmandevil** [comment]
> I'm probably going ot just remove the fucking hairstyle at some point. You should not be able to have something like that in medical. You shouldn't be able to in Security. Cargo? Fuck off. Science? Fuck off. Engineering? You would literally be fired if you didn't get scalped first by your own retardation.

> There is literally no reason that should be in the game. Save for maybe wizards or some shit.


> You're indirectly enabling bad RP, by not making these shitty things unappealing.


I'd say these are good enough points. I'd like to hear Garn's / Abo's reasoning to how this is more of a meme than the thing it discourages.

**Comment by chaoko99** [comment]
>I am? What are you even on about?
Meant to hit edit, not reply.

**Comment by HeyBanditoz** [comment]
It happens. All good.

**Comment by skull132** [comment]
> I'd say these are good enough points. I'd like to hear Garn's / Abo's reasoning to how this is more of a meme than the thing it discourages.

No, they aren't good enough reasons to implement a meme to combat a meme. The fact that this community's management does not wish to approach these issues in the manner you see appropriate was clearly established in the discussion about finger-snapping breaking off fingers -- this is very much the same approach, and thus the same verdict applies.

If you have an issue with this hair style, then please propose more becoming solutions. Like:
* Shortening the hair on the sprite.
* Removing the hair style all together.

**Comment by Pacmandevil** [comment]
Except that this barely counts as a meme, and actually makes sense.

Removing it would piss off the people who actually use it, but this is just a discouragement, and not even a Valid one. there's probably only a few jobs who actually run around enough for this to happen on average.

**Comment by skull132** [comment]
> Removing it would piss off the people who actually use it, but this is just a discouragement, and not even a Valid one. there's probably only a few jobs who actually run around enough for this to happen on average.

It's nice that I also brought up a solution which doesn't remove it, though. Literally just cut the sprite to end at about the small of the back.

**Comment by skull132** [comment]
Well it's been 2 days since, and nothing new has come up. So bye PR.

**Pull request closed without merging**
