### PR TITLE
Adds a docking location to the mercenary shuttle and more

### PR DESCRIPTION
**Pull request by Alberyk**
Adds a dock at arrivals for the mercenary shuttle to dock, also places the admin shuttle to a dock in the bridge. 

Also, fixes the belt at robotics at last and adds a hull shield to engineering. And adds a hacked candy vending to the wizard base and ninja spawn, together with a suit cooling unit for ipc ninjas.

newcopshuttlenewmap

### CODE REVIEW

**Comment by LordFowl** [comment]
And of course provide new images of the changes.

**Comment by Alberyk** [comment]
And the admin shuttle docked:
adminshuttle

**Comment by LordFowl** [comment]
You don't really need to reduce the merc shuttle down to having only 1 door. It having two doors is fine, it's just that one of them will open towards a window when it docks at the station.

**Comment by Alberyk** [comment]
Changes done.

**Pull request merged**
