### PR TITLE
Off-Duty Vaurca Breeders

### PR DESCRIPTION
**Pull request by RustingWithYou**
As the title describes, Vaurca Breeders can now join as off-duty crew members.

This will require Vaurca lore approval, as well as potentially restricting the species by command whitelist if deemed necessary.

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
only breeders can select hive citizenships right?

**Comment by connorjg1** [comment]
> only breeders can select hive citizenships right?

Breeders are the only ones that can select them yeah.

**Review by Arrow768 — CHANGES_REQUESTED** [review]
This needs to be further restricted.

Ideally it would be restricted only to characters who have played in the previous round as consular, but that might be too much work.

If thats not possible it needs to be limited to command whitelist holders.

**Comment by Arrow768** [comment]
I am concerned that this change will drastically increase the presence of Vaurca breeders.
Depending on what happens after the PR is merged it might get reverted again.

**Comment by RustingWithYou** [comment]
> This needs to be further restricted.
> 
> Ideally it would be restricted only to characters who have played in the previous round as consular, but that might be too much work.
> 
> If thats not possible it needs to be limited to command whitelist holders.

I don't know if there is a way to restrict a species by command whitelist, I looked into that. If there is I would be more than happy to just restrict the species to prevent potential Breedertide, though the fact that it's already behind a whitelist should help curtail that IMO.

**Comment by Arrow768** [comment]
> If that's not doable without something on the config end of things I can close this.

We have the ability to require a whitelist for certain jobs, but that applies to every species joining the job.
-> So we would have to whitelist assistant/visitor with the command whitelist, obviously that's not an option.

A code solution would have to be implemented. (either hard-coded or by expanding the whitelist config system)

**Comment by RustingWithYou** [comment]
> > If that's not doable without something on the config end of things I can close this.
> 
> We have the ability to require a whitelist for certain jobs, but that applies to every species joining the job. -> So we would have to whitelist assistant/visitor with the command whitelist, obviously that's not an option.
> 
> A code solution would have to be implemented. (either hard-coded or by expanding the whitelist config system)

What I was thinking was restricting Vaurca Breeder as a species behind a Head of Staff whitelist, which I'm unsure as to whether or not is currently possible.

**Comment by Geevies** [comment]
I did a little research and I think we might be able to restrict breeders to having both the vaurca and command whitelists by editing the 'ss13_whitelist_statuses' SQL table to have both the vaurca and command flags set.

Then we modify the whitelist check in 'whitelist.dm' line 118 to be a bitflag AND check like so:
image

I'm entirely unfamiliar with SQL and the inner workings of bitflag checks though, so I won't be able to contribute more than this idea here.

**Comment by RustingWithYou** [comment]
Given that this will require SQL-side stuff, I'll be closing it until buglore wants to work all that shit out.

**Pull request closed without merging**
