### PR TITLE
Shafted

### PR DESCRIPTION
**Pull request by LordFowl**
Ladders now have proper open-space shafts. Their sprite has been edited to remove the faux-hole, and also the down sprite is now at the same vertical pixel adjustment as the up sprite, so it looks kinda like they connect.

For security's sake, you can no longer fall down an openspace if there is a ladder on the openspace tile. Strangelly enough there was already code for not falling down if there was a ladder _below_ you.

Added flight to some simple mobs that had been excluded from Alberyk's initial runthrough (parrots, bees, bats, and shades.)

The purpose of this PR is that you can now fly up ladder shafts.

### CODE REVIEW

**Comment by Lohikar** [comment]
One concern I have with openturf ladders is that people can drop objects down them on-top of whoever is climbing them, without the person below having any warning.

**Comment by NanakoAC** [comment]
@Lohikar how is that a concern? That sounds awesome and a worthy gameplay feature to have

**Comment by Lohikar** [comment]
Are you aware of the insane damage scaling atm? Last I checked you could headgib someone with metal rods.

**Comment by LordFowl** [comment]
If that is true, that is because metal rods themselves have ridiculously good stats as throwable weapons. Them, along with floor tiles, rank high in the bible of the arsenal of the would-be robuster. As it stands, it is only logical that people can drop things down onto those climbing a ladder.

**Comment by Arrow768** [comment]
Dropping stuff on people climbing up ladders sounds fair.

But it should not be a game ender unless the item dropped down is exceptionally heavy (i.e. moveable machinery like the shield gen)

**Comment by skull132** [comment]
Balancing dropped stuff should be done, but in a different PR probably. Because weee, it's ridiculous atm.

**Pull request merged**
