### PR TITLE
Prevents AIs from right-click "inspecting" stuff they shouldn't be able to see

### PR DESCRIPTION
**Pull request by Amunak**
Title. Basically prevents AIs from cheating by looking outside of their camera coverage using the right-click popup menu.

I have tested that it doesn't break build menu (though you should probably use it when aghosted anyway).

### CODE REVIEW

**Comment by Amunak** [comment]
!bugfix
!review

**Comment by Amunak** [comment]
!bugfix (I think)

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
This solution isn't really good. This proc would be running every time someone moves their mouse to a different turf, which happens a LOT. I'm not sure how else to do it, but what I do know is that this isn't a good way of doing it.

**Comment by Amunak** [comment]
Yeah I know, it's not ideal. Unfortunately there is no other way really - Byond doesn't have a way to display that stupid pop-up menu conditionally.

I was also worried about the performance impact but it seemed immeasurable. And since at the basic level it's just a single type and property check (everything else runs only for a single client usually - the AI, and even then it's just some fairly simple prop checks except for the visualnet proc, and that runs only when you cross between a regular turf and the obfuscated one) I think it shouldn't be an issue.

The only alternative is to, like, not display the turfs at all, making them black, which is less cool (and I don't even know how that works).

Maybe it could be testmerged and performance measured?

**Comment by Amunak** [comment]
I've also opened [a suggestion](http://www.byond.com/forum/post/2628747) on Byond forums to implement a better way to control this, but who knows when (or if) that'll happen.

**Comment by Arrow768** [comment]
Going to close this as not wanted due to the performance implications.

If there is a way to do this without the performance impact, then we will reconsider it.
But as is, this isnt something we are going to merge.

**Pull request closed without merging**
