### PR TITLE
Lets toolbelts hold duct tape, removes hand drills from cargo toolbelts

### PR DESCRIPTION
**Pull request by Forester40**
* Tool belts can now hold duct tape.
* Tool belts from cargo no longer spawn with a hand drill in them.

The PR that added hammers to the game, #12505, made hammers spawn in /obj/item/storage/belt/utility/full (the toolbelts you get from cargo), which made it spawn with 8 items in it when it only has 7 storage slots.
Instead of fixing this by removing the hammer from the belt, I think we should remove the hand drill instead, since I think it's weird anyway that the belt spawns with both a drill and the tools that it replaces, and that it spawns with upgraded tools instead of only the regular ones.

### CODE REVIEW

**Comment by Forester40** [comment]
!bugfix

**Comment by Forester40** [comment]
!review

**Comment by Forester40** [comment]
bloat

**Comment by alsoandanswer** [comment]
You seem to be merging your master branch from your fork.
You have not made a branch, this will mess up your git.

**Comment by Forester40** [comment]
Oh. Thanks.

**Pull request closed without merging**
