### PR TITLE
Unathi Hand Tweaks: Ultimate Scalie Edition

### PR DESCRIPTION
**Pull request by WickedCybs**
I noted some minor issues with the hand sprites Unathi have.  I have done what I can to fix them, and brought the claws (hand) pattern that directly affected the hands in line with how it looks as well.

The image below will show what the changes are. Old on the left, new on the right.

image

### CODE REVIEW

**Comment by WickedCybs** [comment]
!review

**Comment by alsoandanswer** [comment]
It would be much easier to tell what the difference is when the unathis are the same color.

**Comment by WickedCybs** [comment]
> It would be much easier to tell what the difference is when the unathis are the same color.

Updated the image, they are the same now.

**Review by Geevies — APPROVED** [review]

**Review by alsoandanswer — APPROVED** [review]

**Comment by KasparoVy** [comment]
Awesome. I remember seeing this tried at Para a few years ago (insta shot down) but with the continual improvements to Unathi here they look proper cool

**Pull request merged**
