### PR TITLE
Materials And Medical Stacks

### PR DESCRIPTION
**Pull request by alsoandanswer**
Resprites materials and medical stacks. Adjusts sounds for advanced medical kits. Ported from /tg/ and Eris, mostly. Rest by yours truly.

Also removes space klot. R.I.P., you unobtainable sweet prince.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by granodd** [comment]
The medical materials look alright, though trauma packs changing to red instead of green will be a bit disorienting at first.

The mineral material sheets however I'm not really feeling. Their style really juts out in comparison to the other sprites that exist on Aurora at the moment. In addition the way they're designed makes them look very squared and rigid; shaving their corners could make them look less sharp and squared, in addition to widening their sprites.

The phoron sheets seem fine, but the diamond ones which I've had the experience of playing with on Eris are not really all that great. They're small and a little difficult to click on and are a bit difficult to identify as diamonds. While on Eris I'd always mistake them for the liquid bags we have on Aurora.

**Review by SleepyGemmy — COMMENTED** [review]
consider changing the medical brute/bandaid stacks from red to green to match as-is currently.

**Comment by alsoandanswer** [comment]
> The medical materials look alright, though trauma packs changing to red instead of green will be a bit disorienting at first.

i changed the coloring so it'd be color coded to finally match up with whatever their treating; red for brute and yellow for burn.

> The mineral material sheets however I'm not really feeling. Their style really juts out in comparison to the other sprites that exist on Aurora at the moment. In addition the way they're designed makes them look very squared and rigid; shaving their corners could make them look less sharp and squared, in addition to widening their sprites.

yeah i agree the style kind of sticks out but that's just part and parcel of trying to piecemeal in improving the artstyle of aurora rather than trying to sprite everything in one fell swoop.

i really want to dispell the myth of the "aurora style". up until now there has not been any actual directed movement of the server's arstyle, so it's really hard to say that our current hodgepodge of codersprites and ancient /tg/ sprites can be even considered that way. at the moment, i'm trying to work towards an *actual* thought out artstyle, and this is one of the concessions we're going to have to make; temporary sticky-outness.

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
