### PR TITLE
Orion Mobile Station Revamp

### PR DESCRIPTION
**Pull request by Ben10083**
Various tweaks and improvements to the Orion Express Ship

- [x] New Docking Arm (with starboard and port)
- [x] Airlocks now use markers
- [x] Touchup area and add missing items to improve experience
- [x] Make new bugs to provide new contributors easy work

### CODE REVIEW

**Comment by Ben10083** [comment]
!wip

**Comment by Ben10083** [comment]
!review

**Comment by DreamySkrell** [comment]
image
can't have pipes of the same type ("normal" ones in the middle) on the same tile (even if they're different color like here basic gray and purple)
they are going to form one pipe net (or cause some other unexpected behavior)

**Comment by DreamySkrell** [comment]
image

**Comment by DreamySkrell** [comment]
image

**Comment by DreamySkrell** [comment]
image

**Comment by DreamySkrell** [comment]
image

**Comment by Ben10083** [comment]
@DreamySkrell fixed

**Review by DreamySkrell — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
