### PR TITLE
TCFL V1.25

### PR DESCRIPTION
**Pull request by Ben10083**
Various adjustments to TCFL shuttle and ghost role for improvements. 

- Peacekeepers now have webbing that their pilot has, giving them more inv space
- TCFL Medbay had a minor redesign
- Given them maglocks
- Building materials placed in ship

### CODE REVIEW

**Comment by Ben10083** [comment]
!review

**Comment by WickedCybs** [comment]
I don't recommend giving them the webbing harness, I implemented that specifically for the pilots as it goes with their flight suits. You should go for the brown/black pouches or standard webbing as that's what the non-pilot ERT uses.

**Comment by Ben10083** [comment]
> I don't recommend giving them the webbing harness just because the pilot has it, I implemented that specifically for the pilots as it goes with their flight suits. It does not fit with the rest. You should go for the brown/black pouches or standard black/brown webbing as that's what the rest of the TCFL would use.

It has been done.

**Comment by Doxxmedearly** [comment]
You may also wish to address some issues with the ship kitchen in this: 1) No sink, 2) No reagent grinder, 3) The kitchen windoor does not allow access (At least for Legionnaires)

**Comment by Ben10083** [comment]
> You may also wish to address some issues with the ship kitchen in this: 1) No sink, 2) No reagent grinder, 3) The kitchen windoor does not allow access (At least for Legionnaires). Up to you, obv.

I agreed, thanks for heads up regarding windoor btw, I fixed that, and added sink. Won't add grinder though, no space.

**Review by JohnWildkins — APPROVED** [review]
Be a real chad and recompile the map as TGM
(open in StrongDMM -> File -> Preferences -> File Format TGM -> Save the map)

**Comment by Ben10083** [comment]
> Be a real chad and recompile the map as TGM (open in StrongDMM -> File -> Preferences -> File Format TGM -> Save the map)

Anything for you

**Pull request merged**
