### PR TITLE
Hos Loadout Tweaks

### PR DESCRIPTION
**Pull request by SophieMint**
- Allows heads of security to take faction uniforms as SCC.

### CODE REVIEW

**Comment by SophieMint** [comment]
!bugfix

**Comment by SophieMint** [comment]
!review

**Comment by SophieMint** [comment]
!wip

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by SophieMint** [comment]
!review

**Review by SleepyGemmy — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
Not going to be merged as it's weird for heads of security to wear officer uniforms. They're part of the SCC so they should be wearing SCC uniforms, bar exceptions written in the security uniform SOP.

The zavodskoi uniform being wearable by heads of security is an oversight and should be fixed.

**Pull request closed without merging**
