### PR TITLE
Makes crew copied holograms a better copies

### PR DESCRIPTION
**Pull request by Karolis2011**
Just take a look at those gifs
GIF1
GIF2

I am still not sure how to fell about it coping current state of mob.

### CODE REVIEW

**Comment by Lohikar** [comment]
Isn't this usable for the AI to meta what any crewmember is holding or wearing, regardless of camera coverage?

**Comment by Karolis2011** [comment]
Well, could be used... But I don't think there is better solution other than keeping copy of whole mob or calling multiple times gFI during setup... Or there could be a check if that mob is seen on cameras, so it wouldn't be so meta.

**Comment by Lohikar** [comment]
That needs to be solved before this can be merged, imo. The visual improvement isn't worth the potential meta. 

Visnet has a proc to check if a mob sis visible, pretty sure.

**Comment by skull132** [comment]
IMO, this is relatively fine. Specially with the `near_camera` check now added.

**Pull request merged**
