### PR TITLE
Adds new accent tag sprites.

### PR DESCRIPTION
**Pull request by alsoandanswer**
Title.

dreammaker_h0kOmyfa8O

Also adds a blank template and letters. Use them. Or I will kill you.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by Snakebittenn** [comment]
I would prefer 'FED' over 'JAR' tbh

**Comment by Alberyk** [comment]
Lower-Harr'masir Siik'maas (the tajara_low_harr icon) should not share the NKA flag here, the old icon, the two guns, was likely fine as it is.

**Comment by alsoandanswer** [comment]
dreammaker_kehMsRPEPB

'JAR' changed to 'NRM', since it's Nral'Malic, after all. 'FED' was too generic.

and lower HAR, well. it's a gun again.

**Comment by alsoandanswer** [comment]
Should note that my naming process usually avoids generic organizational terms like 'Republic' and 'Federation' because they're likely to be used many times.

Usually, if there is a specific name, it will be used first.

If no specific name is present, then the leading organisation will be used (i.e, PRA used for Republican Siik'Maas)

If they share common ancestry or are close dialects or each other, they will share the same acronym to show connection but with different designs to distinguish them.

**Pull request merged**
