### PR TITLE
Junkfood Tweaks + Lottery Ticket Tweaks

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Overview
- Lottery tickets now contain 3 scratches per card, but with reduced winnings.
- Lottery tickets now take longer to scratch.
- Improved effects of lottery tickets, including sound and voice.

- Skrell Snacks no longer have shortening.
- Beef Jerky and Raisins no longer have palm oil.
- Cheese Honkers have reduced MSG.
- Bread Tubes only have 1 unit of shortening.
- Meat Pies have reduced MSG.
- Cured Hams have increased MSG.

### CODE REVIEW

**Comment by ProbablyMenown** [comment]
Change cured hams to steamed hams and you've got yourself a PR.

**Comment by BurgerLUA** [comment]
I am so glad I wasn't the only one who thought of that

**Comment by BurgerLUA** [comment]
It's literally this: https://www.youtube.com/watch?v=itAOGRiYRLI

**Comment by skull132** [comment]
> Lottery tickets now contain 3 scratches per card, but with reduced winnings.
> Lottery tickets now take longer to scratch.
> Improved effects of lottery tickets, including sound and voice.

This seems kinda unrelated to the rest. 🤔

**Pull request merged**
