### PR TITLE
Ai VOX System

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Added the AI VOX system from TG, the AI now has a VOX Announcement verb where it can announce things in pseudo-TTS.
The sounds for the VOX are under sound/AI/vox_fem/, copy pasted from TG.

### Asset Licenses
The following assets that **have not** been created by myself are included in this PR:

| Path | Original Author | License |
| --- | --- | --- |
| sound/AI/vox_fem/* | tgstation | GNU AGPL v3 |

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!review

**Comment by MortalRed** [comment]
Hard pass. TTS is an extremely LRP feature, ripe for abuse, and just sounds like shit to be honest, further exacerbated by the fact that it is forced on whether you like it or not.

**Comment by TheDanseMacabre** [comment]
Echoing Redshirt's complaints. The fact of the matter is that this is loud, disruptive, and obnoxious. It doesn't belong here.

**Comment by alsoandanswer** [comment]
I think it's fine. A little reactionary to call it LRP because we haven't seen it used in a HRP enviroment yet.

Really, the only problem is implementation, which having a hundred .ogg files isn't preferable.

**Comment by Arrow768** [comment]
The question if this PR is suitable for a HRP/LRP server or not is something that doesnt need to be discussed here.

**Comment by MortalRed** [comment]
> if you read the code you will see that they only play if you have your preference on, otherwise they do not,

Read and checked it, disabling vox disables every other sound effect.

**Comment by FluffyGhoster** [comment]
> > if you read the code you will see that they only play if you have your preference on, otherwise they do not,
> 
> Read and checked it, disabling vox disables every other sound effect.

It does not look like it would, it is only checked against the VOX itself and the announcement sound, as a search on the codebase shows:

image

**Comment by MortalRed** [comment]
> It does not look like it would, it is only checked against the VOX itself and the announcement sound, as a search on the codebase shows:

I've checked in-game, it does not show up in any of the menus.

**Comment by FluffyGhoster** [comment]
> > It does not look like it would, it is only checked against the VOX itself and the announcement sound, as a search on the codebase shows:
> 
> I've checked in-game, it does not show up in any of the menus.
> 
> Also side note, but I don't like the idea of giving the AI a clearly gendered voice.

Yes, it does, you have to click the "Show SFX Preference Panel" and then in it you have "Toggle Message SFX".

If you could please stop commenting with objectively false statements, repeatedly, about what the code does or does not do, that would be fantastic.

**Comment by MortalRed** [comment]
The "Toggle Message SFX" button that also mutes other sounds?

**Comment by FluffyGhoster** [comment]
> The "Toggle Message SFX" button that also mutes other sounds?

image
You keep giving me reasons to consider your comments are not in good faith. I have already explained that it's only used for the VOX and the announcement sound effect, and as you can see above, the only thing this verb does is toggle that.

**Comment by NonQueueingMatt** [comment]
Unwanted. The system isn't ideal and if we go the TTS direction (which is unlikely because of the LRP connotations) it should be a dynamic system rather than words from a word-list.

**Pull request closed without merging**
