### PR TITLE
Resprites a bunch of items in tajara_items.dmi

### PR DESCRIPTION
**Pull request by atteria**
Resprited fur scarves, tajaran cloaks, tajaran fancy outfits, and the raakti shariim uniform since it was a derivative of the previous.

taj items resprite showcase
<details><summary>Previous showcase image</summary>
<p>

taj items resprite

</p>
</details>

### CODE REVIEW

**Comment by Greenjoe12345** [comment]
While I like this overall, I'm not too big a fan of those skirts being made shorter
image
image
compared to the old one

**Review by Alberyk — APPROVED** [review]

**Comment by atteria** [comment]
> I'm not too big a fan of those skirts being made shorter
I only noticed I did this at about the last step of this PR. I'll see about lengthening them, I think I can get even more depth out of the skirt doing that.

**Review by alsoandanswer — APPROVED** [review]
You forgot to type !review

**Comment by SleepyGemmy** [comment]
!review

**Review by SleepyGemmy — APPROVED** [review]

**Pull request merged**
