### PR TITLE
Removes xenomorphs

### PR DESCRIPTION
**Pull request by Alberyk**
Xenomorphs are pretty much badly done and don't really fit at all. This pr fully removes the human type ones, alongside with the infection, eggs and facehuggers.

### CODE REVIEW

**Comment by Coalf** [comment]
I fully support this, at this point even the staff can't be trusted to run decent events with this. It's just horrible and bad, no reason for this to exist. The roleplay quality always dips horrendously and the only defense people can muster up is "We only have it once a year."
Well, everyone, had their wisdom teeth chiseled out of their mouth once too, don't mean they want to repeat it.

**Comment by ParadoxSpace** [comment]
I disagree. It's not good code, or a good event.

**Comment by NonQueueingMatt** [comment]
"Improve not remove" just leads to code rotting in the codebase.

If someone cares about it they'll bring it back.

**Comment by Sindorman** [comment]
Huh, I needed Xenomorph code base for Necromorphs. I guess I will extract whatever I need from it.

Aurora will have Necromorphs as signature instead of Xenomorphs

**Pull request merged**
