### PR TITLE
Fixes Barsign & Cyberplants

### PR DESCRIPTION
**Pull request by ParadoxSpace**
The barsign is no longer visible from the backroom, yes, even the Cyber Sylph one. To cover for the arcade machines I had to move, holoplants have been added. These can be changed from different plant sprites by interacting with an empty hand, and color can be changed by walking over them. Potted plants now go over mobs, for hiding. There is a 20% chance for each potted plant (I have added more across the station for a more comfy feel) to be replaced by cyberplants. A big shoutout to my homie @NanakoAC for helping me fix the barsign, and for the plant improvements in https://github.com/discordia-space/CEV-Eris/pull/1711. On the next part, a water cooler has been added in the Security desk room, and the medical lobby. Cargo now has a soda dispenser much like engineering. A secret beer keg has been added to Engineering as well. 

Feedback Topic:
https://forums.aurorastation.org/topic/11261-a-needlessly-large-feedback-thread/

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
[plants](https://i.imgur.com/Xf0ifqi.gifv)

**Comment by VTCobaltblood** [comment]
Nuclear PRs please?

**Comment by ParadoxSpace** [comment]
nah

**Comment by Conspiir** [comment]
The problem with not separating these is you have a bug fix mixed in with new features, which have different wait times. Can't push the fix without pushing the other stuff which… will take longer.

**Comment by VTCobaltblood** [comment]
There are a _ton_ of changes in this PR, most of them unrelated to each other. But apparently Paradox is "ready to wait" and won't let his mapping changes go. /shrug

**Comment by ParadoxSpace** [comment]
[screaming]

**Comment by ParadoxSpace** [comment]
https://forums.aurorastation.org/topic/11261-a-needlessly-large-feedback-thread/

**Comment by ParadoxSpace** [comment]
ok now what

**Pull request closed without merging**
