### PR TITLE
Bridge Crew Corporate Journalist Changes

### PR DESCRIPTION
**Pull request by alsoandanswer**
- Bridge Crew renamed to Steward (with alt-title Pilot)

Name change mainly due to it being lengthy and double barreled, while also being a terrible indicator of their actual job duties.

For instance, their duties far exceed **just** sitting on the bridge, and they handle a lot of other tasks on the ship, such as planning expeditions, being the XO's assistants, etc. etc.

New names chosen on conditions of being gender-neutral, short, not double-barelled and not requiring abbreviation.
(Which should be reserved for Heads of Department, which are important enough that they need them.)

- Moved to Service Department

Command Support department has a myriad of problems, namely giving the false impression that whatever job that resided in it had much more authority than said job actually had. 

After a few movements and removals of the jobs within, Bridge Crew still remained in said vestigial department. Which also fed into the idea of them sitting on the Bridge or in or near Command all day, which should not be the case.

The name "Command Support" implies that their dutes revolve around Command, which isn't the case, they can behave independently from Command - it's just that they so happen to overlap with them the most.

With this change, it will be an easier association that they are above all else, still under the XO, and their duties exceed Command.

Important : **Bridge Crew are mechanically unchanged.**

- Corporate Journalist now accessible for all jobs, moved to Civilian

A rather simple change. Moved them to be in line with Corporate Liaisons - No longer under the jurisdiction of the XO, but under company officials, and opened them up for all corporations (barring SCC.) Should open up more roleplay opportunities for them.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by Eyeveri** [comment]
I'm not sure if I'm able to do this, but I'd really like to see a feedback thread opened. There was some extensive discussion in the discord code-dungeon.

**Comment by Greenjoe12345** [comment]
seconding on wanting a feedback thread on this.

**Comment by NonQueueingMatt** [comment]
Unwanted. This makes a job a lot more relevant in the grand scheme of things when it should be cool (you're piloting a flagship, and you're also the XO's right-hand-man!).

**Pull request closed without merging**
