### PR TITLE
New Ian sprite

### PR DESCRIPTION
**Pull request by alsoandanswer**
by walterje.

dreammaker_LjVSakau4i

### CODE REVIEW

**Comment by KingOfThePing** [comment]
:walter:

**Comment by alsoandanswer** [comment]
!review

**Comment by niennab** [comment]
What about the one I've been working on and starting to PR? Is that just it? I really wish there was some communication sent my way.

**Comment by alsoandanswer** [comment]
> What about the one I've finished and starting to PR? Is that just it? I really wish there was some communication sent my way.

Oops, I didn't know you were still working on it.
I'll close this once you open yours.

**Comment by niennab** [comment]
> Oops, I didn't know you were still working on it. I'll close this once you open yours.
Gotcha, thank you. I've put up the PR

**Pull request closed without merging**
