### PR TITLE
Add Hanboks and Hair

### PR DESCRIPTION
**Pull request by niennab**
Added a sleeveless and short sleeve colorable male hanbok.
Minor change to female hanbok (regular + pink).
Added the tress shoulder double, punk chelsea alt, fade manbun, fade clean, fade clean low hair styles.
Minor changes to sleeze and straightlong hair.

testexample

### CODE REVIEW

**Comment by niennab** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by niennab** [comment]
The belt changing along with the uniform is intended. Another belt and moving the other Hanboks over can be addressed in a later PR.
The sleeveless hanbok and short sleeve hanbok are different coats historically, so no.

**Comment by listerla** [comment]
On the adjustments to the female hanboks; shape is a great change but they likely shouldn't be mirrored on side view.

image

Note how the details in the front view, which go down to the right of the outfit, are now visible on the left view.

**Comment by niennab** [comment]
Good catch, thanks! It's been fixed.

**Review by listerla — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
