### PR TITLE
Supermatter no longer earrapes engineers

### PR DESCRIPTION
**Pull request by alsoandanswer**
basically reverts #8357 

probably would work better with tweaking, but I'd rather get this over with first

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by furrycactus** [comment]
Is reverting #8357 going to bring back the loud sound loops, like the kitchen deep fryer earraping chefs?

**Comment by Doxxmedearly** [comment]
Do some investigating on this. I took a look on it after I made my post.
Turns out the power var doesn't really get very high even after 30 emitter shots. Even varediting it to like 800 and to 0 didn't seem to change much. Not sure if this really is the issue but hopefully you've done some testing on it to make sure.
We might be better served with using a better sound.

**Comment by alsoandanswer** [comment]
closing until i cant figure something else out

**Pull request closed without merging**
