### PR TITLE
Diona Consuming Air

### PR DESCRIPTION
**Pull request by ParadoxSpace**
They can now do it whenever. Still stops when you're full on nutrition.

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
!review

**Comment by NonQueueingMatt** [comment]
Why is this being done?

**Comment by ParadoxSpace** [comment]
Yonni/Sleepy said they'd be okay with it, and it really doesn't make /any/ sense that Dionae would feel bad about doing it to where it needs to be hardcoded.

**Comment by skull132** [comment]
Can we have a real big think about this for just a moment.

Diona can form massive exo-planets. They can survive in a setting without air, or any atmosphere for that matter. At which point, them getting "nutrition" or energy via light makes sense. Adding "Air" as a source of nutriment seems arbitrary, surely, if not inconsistent.

**Comment by Sindorman** [comment]
> Can we have a real big think about this for just a moment.
> 
> Diona can form massive exo-planets. They can survive in a setting without air, or any atmosphere for that matter. At which point, them getting "nutrition" or energy via light makes sense. Adding "Air" as a source of nutriment seems arbitrary, surely, if not inconsistent.

Currently Diona can consume air for nutrition only when they are low on it. And it has to be enabled. Paradox is trying to make it enabled by default.

**Comment by Yonnimer** [comment]
Hi, lore is fine with removing the restriction disallowing them from consuming air while not only on low nutrition. So long as it doesn't cause any issues of course.

**Comment by Arrow768** [comment]
DNM due to the concerns voiced by skull, which I agree with.

**Pull request closed without merging**
