### PR TITLE
QOL changes to the AI's lawset

### PR DESCRIPTION
**Pull request by Chada-1**
Not much to say, added some more info to the law phrasings, made unauthorized/authorized personnel used for both law 1 and law 4 for consistency, and added 'onboard NanoTrasen facilities' instead of just 'onboard'. 

Other than that, the two biggest change is just adding 'To the best of your ability' to law 1 and 2 so that there's a degree of error allowed in the lawset, and a POSSIBLE change to law 3 following feedback, but I may scrap that if it's deemed undesirable.

### CODE REVIEW

**Comment by Chada-1** [comment]
!review

**Comment by Chada-1** [comment]
Made a new change, "Protect NanoTrasen personnel onboard NanoTrasen facilities and refrain from harming sapient life." to address issues raised of the AI and 'borgs stonewalling Crew from interacting with antagonists.

**Comment by SenpaiShadow** [comment]
"Safeguard and ensure to the best of your ability, only authorised personnel gain access to areas of high security or importance to the **Station** and its operation."

It wont be a station forever so a neutral term instead of Station should be picked.
Aside from that I will talk this over with Prate and come back with feedback regarding the law changes.

**Comment by Chada-1** [comment]
> "Safeguard and ensure to the best of your ability, only authorised personnel gain access to areas of high security or importance to the **Station** and its operation."
> 
> It wont be a station forever so a neutral term instead of Station should be picked.
> Aside from that I will talk this over with Prate and come back with feedback regarding the law changes.

Done, also, law 3 is contentious but if you decide not to go with it, I have another phrasing that maintains the current way it works but in a more polished phrasing that we could use instead, but that's up to you, since the new law 3 is meant to address feedback on the thread. That alternate phrasing is. "Protect Sapient life onboard Stellar Corporate Conglomerate facilities."

**Comment by Chada-1** [comment]
Scrubbed law 3 similarly to what it was before after feedback. Still should hopefully curb the behavior the rephrasing was meant to solve.

**Review by Geevies — APPROVED** [review]
fine codewise, up to maintainers whether it's mergeable tho

**Review by Doxxmedearly — APPROVED** [review]
As above

**Comment by CRISPR-core** [comment]
While this QoL update is _basically_ just the old lawset with new words for NanoTrasen, it looks good enough to not make me inwardly die whenever security wants science entrance to apprehend the xenobiologist making hostile slimes again. Phew. 

+1

**Review by Arrow768 — CHANGES_REQUESTED** [review]
The laws need to continue to use the `current_map.` variables.

**Comment by Chada-1** [comment]
> The laws need to continue to use the `current_map.` variables.

Should be done tho I wanted the recent the new Corp changes to be represented in the laws too

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
