### PR TITLE
Longer-lasting cigarettes

### PR DESCRIPTION
**Pull request by Jaraci**
Halves the burn rate of most non-special cigarettes, as well as halves the amount of reagents sucked out every time you take a drag from them. Currently, cigarettes get smoked through passively in just under 1m30s, which seems (and feels) extremely quick. I didn't touch any of the cigarettes with custom burn rates, since some of them appear to be antag-related stuff and I didn't want to fuck with balance or whatever.

Also, I fixed a grammatical error in the Europan zippo lighter's description.

### CODE REVIEW

**Comment by Jaraci** [comment]
!review

**Review by WickedCybs — APPROVED** [review]

**Review by JohnWildkins — APPROVED** [review]

**Comment by Geevies** [comment]
i just wanna check if lasting longer makes nicotine not work correctly or something, i'll ask my resident expert

**Comment by Jaraci** [comment]
> i just wanna check if lasting longer makes nicotine not work correctly or something, i'll ask my resident expert

Please do. My testing wasn't comprehensive by any means, I just made sure it roughly doubled the time it took for them to go out, since Matt suggested it might be strange even with declchem (whatever that is). I didn't really look into nicotine effects -- I wasn't aware there actually were any beyond the addiction messages or whatever, anyway

**Comment by Geevies** [comment]
resident expert said it should be fine so it should be fine let's go

**Pull request merged**
