### PR TITLE
Fixes tramp freighter hangar and shuttle airlocks/docks

### PR DESCRIPTION
**Pull request by DreamySkrell**
Fixes tramp freighter hangar and shuttle airlocks/docks

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!bugfix

**Comment by DreamySkrell** [comment]
!review

**Comment by RustingWithYou** [comment]
These fixes are included in #18214 IIRC

**Comment by DreamySkrell** [comment]
😩 I did not see that PR

**Pull request closed without merging**
