### PR TITLE
New furniture sprites

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
Swaps chairs, wooden chairs, office chairs, stools, and comfy chair sprites with versions from Bay. Not quite sure if I've gotten it right, but it looks workable as-is.

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Comment by SleepyGemmy** [comment]
spritesheet.

image

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
you will need to update "chair_item" and "chair_item_preview" to the new sprites. easiest way would be to take the regular chair's west facing sprite and rotate it the same way the "chair_item" is.

**Comment by SleepyGemmy** [comment]
personally, i like the older comfy chairs more. the new ones look like the bridge pilot chairs and look very small. i like the new regular chairs, though.

**Comment by KingOfThePing** [comment]
These look very out of place and honestly, quite bad. I prefer the old sprites.

**Comment by alsoandanswer** [comment]
Bay's chairs don't fit our server, unfortunately.

I suggest porting /tg/'s stools and chairs instead.

**Comment by desvenlafaxine** [comment]
[Here are some stools I tried to port a while ago, if you need reference for /tg/ style stools](https://github.com/Aurorastation/Aurora.3/pull/12540).

**Pull request closed without merging**
