### PR TITLE
Warehouse Access

### PR DESCRIPTION
**Pull request by Geevies**
* The warehouse is now access locked to the Ops Manager, Hangar Technician, Janitor, and First Responder roles. This means that Shaft Miners and Machinists no longer have access to it.
* Removed the Operations Lift, adjusted all the rooms it used to occupy.
* Added a few more crates to the warehouse.

I think this is for the best, as this limits warehouse gameplay (trademark pending) to Hangar Technicians, and prevents roles with already-established gameplay loops from intruding there.

Deck One
image

Deck Two
image

Deck Three
image

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by DreamySkrell** [comment]
I don't really have an opinion on the access itself
but the way the stairs access is restricted is really strange and fucked

the windoors should be at the upper deck at least so it's not super awkward going down the stairs to see you don't have access and then back up again

**Comment by NonQueueingMatt** [comment]
the PR idea is good but I'm not really a fan of how the access is handled there, it looks super awkward

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
(this was discussed on discord) (ping me on discord when this is fixed)

Do not cut off deck 3 ops from deck 2. There should be stairs to go up there.

**Comment by Greenjoe12345** [comment]
> (this was discussed on discord) (ping me on discord when this is fixed)
> 
> Do not cut off deck 3 ops from deck 2. There should be stairs to go up there.

That, or the lift being restored, I made a concept for how it could be lined up.
image

**Comment by Geevies** [comment]
> (this was discussed on discord) (ping me on discord when this is fixed)
> 
> Do not cut off deck 3 ops from deck 2. There should be stairs to go up there.

this was the suggested change
image
image

tried it out, with multiple different objects, but just can't get it looking good in the space provided
image
image

it's just too much effort for something that really just doesn't get used, so i'm not going to try it again

**Comment by Greenjoe12345** [comment]
Keeping the ops lift would be best, I would think. Removing it doesn't feel right.

**Pull request closed without merging**
