### PR TITLE
Space Fauna Lethality Tweak

### PR DESCRIPTION
**Pull request by Geevies**
* Space fauna, such as carp and reavers, have slightly less armor penetration and no longer have smart melee, meaning they won't dodge attacks anymore.
* Added metal rods, a medkit, and machetes to the Spark and mining bay.

I believe space fauna are overtuned still, even after the nerfs. The 0.5s thinking, combined with high damage and dodging made them unfairly punishing for miners who stumble around in the dark, far from any medbay. This seeks to resolve that issue by reducing the damage while buffing the defense.

The focus should be on mining instead of bootleg DOOM gameplay. If you believe these changes are a little too heavy-handed, try spawning and fighting two reavers in a mining voidsuit on your private server.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]
I don't really like buffing the mining rig but I guess it's whatever

**Comment by FluffyGhoster** [comment]
I don't think this large nerf of the animals is needed, especially buffing the mining rig; the armor penetration of those animals got reduced between a third and half of the value

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
Armour buffs need to go. With the mob nerfs they're all going to do like 3-5 damage to the new armour.

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
