### PR TITLE
Compresses sound files for the rsc.

### PR DESCRIPTION
**Pull request by FirinMaLazors**
I wanna cram more songs into the jukebox, so I'm making the sound files smaller by reducing their bitrate to 8khz, mixing down to stereo, and using a 16-bit format where possible

### CODE REVIEW

**Comment by FirinMaLazors** [comment]
!WIP

I'll work on the other files too.

**Comment by FirinMaLazors** [comment]
!review

**Comment by FirinMaLazors** [comment]
Forgot to mention... I listened to parts of each song in the sounds/music and sounds/music/recordplayer until I was satisfied that the compression did not change the quality in any noticeable way.  I then applied the .ogg -> .ogg quality 0 conversion to the ambience files; no bitrate change on them, since I couldn't do it in batches (annoyingly).

**Comment by alsoandanswer** [comment]
I don't think reducing quality and changing to stereo is too good for quality

Also, why are you modifying ambience sounds? Isn't this only for the jukebox?

Anyway I don't really think memory is a problem for us. A few KB here and there doesn't really do much performance wise.

**Comment by FirinMaLazors** [comment]
> 
> 
> I don't think reducing quality and changing to stereo is too good for quality
> 
> Also, why are you modifying ambience sounds? Isn't this only for the jukebox?
> 
> Anyway I don't really think memory is a problem for us. A few KB here and there doesn't really do much performance wise.

@alsoandanswer Ahhh derp... why did I say mixing down to stereo?  I meant mono, lol.  Blah.

Anyway, I walked back the mono-mixing, and just started doing what I could to reduce the file size without affecting the quality in any way that I could hear.  This wound up being generally just getting the files down to a 22050 bitrate if they were higher than that and exporting them as .ogg, quality 0.

The reasoning is that @Arrow768 stated that one of the main constraints to adding new music to the jukebox is the size of the rsc file, the one that players have to download upon joining the server for the first time and after their cache is cleared.  (The other constraint is licensing.)  Right now the rsc is about 125MB; looking inside of it with https://git.nexisonline.net/voidsploit/Krampus, /music/sounds and /music/ambience were the biggest folders.  The compression I did to what was in /sounds shaved about 19 MB off the rsc file size, while what I did to /ambience shaved off about 6 MB.  If "125 MB" is taken as a soft convention of how big the rsc is allowed to get, then I just freed up 25 MB for other purposes (such as jukebox songs!).

**Comment by Baa14453** [comment]
Can you wait for #9942 ? I've updated some of the files as you with original copies to be higher quality as well as compressing them

**Comment by FirinMaLazors** [comment]
Sure @Baa14453 !  I'll close this PR then.

**Pull request closed without merging**
