### PR TITLE
New skrell sprites

### PR DESCRIPTION
**Pull request by alsoandanswer**
From TauCetiStation. Resprited hairstyles and beards by myself.

image

Honestly, this has been a pain in the ass. Species icons definitely need a good sorting out, which I'm not going to do right now.

sIPv1m8Lgz

Just look at this beautiful [PLURAL]!

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by NonQueueingMatt** [comment]
I have to say, these excessively shaded species sprites **do not fit at all.**

**Comment by NonQueueingMatt** [comment]
This is also unwanted by the skrell team, so I'm closing this.

**Comment by FlamingLily** [comment]
Imho and it's a bit late, but they look good.

Just. None of the other species sprites fit.

**Pull request closed without merging**
