### PR TITLE
Removes Battlemonsters

### PR DESCRIPTION
**Pull request by Doxxmedearly**
Nobody plays it, and nobody has really ever played it since its addition to the server. Lord knows I and a few people tried to drum up interest, but to no success. It's just wasted space at this point. We don't need the vendors taking up mapping space, and we don't need an entire subsystem and 20-odd .dm files dedicated to something totally ignored by the players.

The system isn't very interesting or fun, and the card spawns were odd. It was a cool idea, but right now there's literally no reason to keep it.

"Improve don't remove" crowd can dm me their address so I can fight them in the street. If something interesting gets added later on to take its place, cool. Doesn't mean we need to keep this. We gave it several years with no interest. Time to send it to the shadow realm. 

All the mapping changes are removing the battlemonsters arena from the holodeck, as well as the vending machines. Also when I loaded the maps in strongDMM, it automatically found and removed a lot of objects that no longer existed, because god knows how long its been since anyone touched these maps. So. That's why it's huge.

### CODE REVIEW

**Comment by Doxxmedearly** [comment]
!review

**Review by SleepyGemmy — APPROVED** [review]

**Review by Arrow768 — CHANGES_REQUESTED** [review]
Invalid map changes.
The problem there is that the path of objects has been *changed*.
Therefore strongdmm can not find the objects in question. (i.e. chairs)
By just removing them you made it much more difficult to fix that in the future (as someone would have to look up a past revision of the map to figure out what was placed were and then replace it with the current path.

There are two options:
- Only remove the battle monsters from the map
- Update the paths of the objects that have been renamed properly

**Comment by Doxxmedearly** [comment]
I'm sure as hell not remapping all of that nonsense, so I will leave the areas untouched.

**Comment by TheDanseMacabre** [comment]
I don't really see the harm in keeping them. You do see people who like them every once in a while. However, I probably won't ever use them myself so I suppose it shouldn't matter to me.

**Review by mikomyazaki — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]
Looks good but the PR will be discussed by the maintainers possibly requiring additional stats beforehand to determine if its still in regular use or not.

**Comment by Doxxmedearly** [comment]
Yeah I'd prefer if we got some actual stats before it goes through, too.

**Comment by Doxxmedearly** [comment]
I am going to revisit this another time and/or when we get stats.

**Pull request closed without merging**
