### PR TITLE
Gets rid of arcade sounds

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
Title

Way too loud and obnoxious, lowering the volume didn't really help because of how GLARING the sound effect is.

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Comment by Mwahahahaha** [comment]
I mean I'm fine with this either way but aren't arcades _meant_ to be loud and obnoxious?

**Comment by alsoandanswer** [comment]
yeah don't flat out remove it just turn it into a toggle

this was exactly the same with drop sounds and everything became OK when there was a toggle for it too.

**Comment by NonQueueingMatt** [comment]
I'm not gonna lie I cant be fucked to do that for arcade sounds.

**Pull request closed without merging**
