### PR TITLE
Vampire adjustments

### PR DESCRIPTION
**Pull request by skull132**
Adjusts the following:
* Hypnotise buffed to last slightly longer, and to silence the target, to make it worth the blood cost and activation time
* Scaling and datum adjusted to make more vamps in rounds (1 vamp per 50 players is unreal)
* Frenzy gets removed at a faster rate while draining blood
* Fixed a bug where thralls got vampire powers

### CODE REVIEW

**Comment by NanakoAC** [comment]
I'm not quite understanding the scaling coefficient. Why did a value of 8 result in 1 vamp per 50?
from 8 to 7 doesn't seem like much of a change, what numbers do you expect to see from this?

Personally i'd say we should aim for 4 vampires with a full server, so maybe one per 10-13 players

**Comment by NanakoAC** [comment]
Also, those round descriptions, when are they ever used?
The short round description sounds dumb. Space-transylvania ? I recall you wrote some new vampire lore.

extended_round_description is way better, but its also quite clearly written for changelings not vampires, imo.

**Comment by skull132** [comment]
I honestly don't even remember what on Earth the controls the antag spawns. I was looking it up for ages when dealing with traitor scaling, but erm, I very quickly erased it from my memory. Something that'll do more work, I imagine, is the initial_spawn_target, as that's how many it'll _try_ to spawn by default. Though, that value _should_ be changed at runtime, due to playercount.

Alternatively, I can turn all single style antags modes into auto-traitor, so the fucky spawn during init commands aren't as relevant.

As for space-transylvania, I forgot about that little description! It's the thing shown when the roundmode is declared, to everyone. Fixing it in a sec.

**Comment by NanakoAC** [comment]
having vamp and changeling work like autotraitor seems like a good idea. May as well throw away normal traitor mode entirely in that case

If you're tweaking those things though, i think autotraitor is a little excessive right now, and should select fewer traitors in dense times

**Pull request merged**
