### PR TITLE
Wer6 Skrell Head adornments

### PR DESCRIPTION
**Pull request by Fire-and-Glory**
Github spooks Wer6 so I am uploading (and coding) these Skrell head adornments in their stead.

I will note that I have _not_ been able to test them regarding choosing and spawning with them from custom loadout due to unrelated wackiness, but I have no reason to believe that they wouldn't work.

### CODE REVIEW

**Comment by NanakoAC** [comment]
can you possibly roll in this one too, i made sprites a while ago http://forums.aurorastation.org/viewtopic.php?f=25&t=5574

**Comment by Fire-and-Glory** [comment]
I'm not really sure how custom items work, and the custom item app doesn't seem to be accepted, so uh, not really.

Alberyk has been handling custom items so if it does get accepted then they'll probably deal with it.

**Comment by Alberyk** [comment]
The item in question, was already added as a custom item, it is in the pull request related to those.

**Comment by skull132** [comment]
Merge errors. Potentially from merging #484 ?

**Comment by Fire-and-Glory** [comment]
Actually it wasn't taking kindly to merging with the master branch because master branch had scrubs added on it.

**Comment by skull132** [comment]
Still conflicted.

**Comment by Fire-and-Glory** [comment]
Not sure what's up, then, we can try this again on the next dev cycle.

**Pull request closed without merging**
