### PR TITLE
Bottom deck AI core gone

### PR DESCRIPTION
**Pull request by DreamySkrell**
image
image

it served no use, only taking up space

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!review

**Comment by FluffyGhoster** [comment]
That's where the AI shell is located at roundstart, I do not see it on the mapdiff, where did you move the AI shell to?

**Comment by DreamySkrell** [comment]
> That's where the AI shell is located at roundstart, I do not see it on the mapdiff, where did you move the AI shell to?

image

idk why mapdiffbot is not rendering doors

**Comment by FluffyGhoster** [comment]
> > That's where the AI shell is located at roundstart, I do not see it on the mapdiff, where did you move the AI shell to?
> 
> image
> 
> idk why mapdiffbot is not rendering doors

Ah, I see it now

I do not think that's a good placement, it's the easiest path for someone to get in and card the AI, and it would be blocking the door unless the AI moves it or it gets destroyed; I am also not sure why there's a suit cycler in this room that's supposed to only have synthetics inside, perhaps remove the suit cycler and put the shell there?

**Comment by DreamySkrell** [comment]
> > > That's where the AI shell is located at roundstart, I do not see it on the mapdiff, where did you move the AI shell to?
> > 
> > 
> > image
> > idk why mapdiffbot is not rendering doors
> 
> Ah, I see it now
> 
> I do not think that's a good placement, it's the easiest path for someone to get in and card the AI, and it would be blocking the door unless the AI moves it or it gets destroyed; I am also not sure why there's a suit cycler in this room that's supposed to only have synthetics inside, perhaps remove the suit cycler and put the shell there?

image

it's not a suit cycler it's the robot storage thingy they use to cryo 😩

**Review by FluffyGhoster — APPROVED** [review]

**Comment by SleepyGemmy** [comment]
the PR touches the shuttles. is that intentional?

**Comment by DreamySkrell** [comment]
> the PR touches the shuttles. is that intentional?

that is not intentional, and honestly no idea how that even happened

some kind of bad merge? idk.......

thank you for catching it

**Comment by DreamySkrell** [comment]
image
image

these are the only changes according to mapdiffbot now so it should be good (I hope)

**Review by CyberSpyXD — APPROVED** [review]

**Comment by Arrow768** [comment]
i am a bit unsure as that makes it a bit easier to blow up the Ai with a bomb from below.
But I guess we´ll see if that becomes a pattern

**Review by SleepyGemmy — APPROVED** [review]

**Pull request merged**
