### PR TITLE
Better factions and contractors

### PR DESCRIPTION
**Pull request by skull132**
Intent of this PR: make factions actually matter.

How we're going to do this:
- [x] Make factions limit job choices.
- [x] Make factions have alternative loadouts that override job uniforms
- [ ] ~Make factions give you additional gear (badges or whatever).~
- [x] Make factions be visible in the employment records.
- [x] Revert existing faction loadout options or put them behind a preference, in favour of new shit.

Misc TODOs:
- [x] Blurbs and logos for all factions from lore.
- [x] Job lists per faction from lore.
- [ ] ~Faction and job sanitization.~

### CODE REVIEW

**Comment by skull132** [comment]
Current state: https://cloud.skullnet.me/s/A7Pnwe8X7LjcYFj

**Comment by Sun-Sam-San** [comment]
so how is this going to work with https://github.com/Aurorastation/Aurora.3/pull/6489

**Comment by skull132** [comment]
> so how is this going to work with #6489

It's not. Your PR is a basic data addition PR. It adds no mechanics nor has any relevancy on this one.

The "faction" lists, as they stand, will be removed for being useless. The new list will be composed of a concentrated subset that the lore team is currently attempting to hash out under my direction.

**Comment by skull132** [comment]
!review

**Comment by skull132** [comment]
https://cloud.skullnet.me/s/tCQJ2dCZqSKK8fy

**Comment by Arrow768** [comment]
I´d recommend to setup a specific fraction just for the merchant job, so people dont get accidently selected for on station jobs if they ready up as merchants (and vice versa)

**Pull request merged**
