### PR TITLE
Music Metadata Update

### PR DESCRIPTION
**Pull request by Baa14453**
This change is intended to fulfil the licensing requirements and/or provide metadata for as much of the SS13 music as I can. At the same time I've replaced many of the songs with original files to get a higher quality version.and recompressed them.

### main.ogg
Title: another_drone.wav
Artist: the_semen_incident
Source: https://freesound.org/s/66097/
License: Creative Commons 0 

### space.ogg
Title: Endless Space Expanded
Artist: SolusLunes
Source: https://www.newgrounds.com/audio/listen/74946
License: Attribution 3.0 Unported (CC BY 3.0) 

### 1.ogg
Title: Tracking Device
Artist: Valve
Source: https://store.steampowered.com/app/323140/HalfLife_2_Soundtrack/
License: I could not find any license specified.

### b12_combined_start.ogg
Title: b12 Combined Start
Artist: Toady One
Source: http://www.bay12games.com/dwarves/
License: Public Domain

### song_game.ogg
Title: Untitled
Artist: Toady One
Source: http://www.bay12games.com/dwarves/
License: Public Domain

### battlemonsters_theme.ogg
Title: battlemonsters_theme.ogg
Artist: Burger (Discord ID: Burger#3948)
Source: https://github.com/Aurorastation/Aurora.3/pull/5141
License: GNU Affero General Public License version 3

### traitor.ogg
Title: Absconditus
Artist: ZhayTee
Source: https://bandcamp.zhaytee.net/album/minerva-metastasis-ost
License: [Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)](https://creativecommons.org/licenses/by-nc-sa/3.0/) 

### song_game.ogg
Title: Clouds of Fire
Artist: Hector / dMK
Source: BBS distributed by the  Digital Music Kings, no longer accessible but an archive exists here: https://modarchive.org/index.php?request=view_by_moduleid&query=73980
I've located the artist just waiting confirmation for them to let me plug their stuff.
License: Public Domain

### title1.ogg
Title: flip-flap
Artist: X-CEED of eNDZEIt & aPPeNDIx | Wojciech Panufnik 
Source: Probably another BBS song, archive available here: http://aminet.net/package/mods/xceed/Flipflap
Metadata says to ask the artist if you want to use, so I've messaged them waiting reply.
License: Copywright Wojciech ("X-CEED") Panufnik - [Custom License details here](http://aminet.net/package/mods/xceed/Flipflap).

### title2.ogg
Title: Robocop.mp3
Artist: Remix by Cboyardee / Chef Boyardee | Original by Jonathan Dunn
Source: The Dilbert 2 Youtube video, lost to time.
License: Unknown

### CODE REVIEW

**Comment by Baa14453** [comment]
!wip

**Comment by alsoandanswer** [comment]
https://www.newgrounds.com/audio/listen/67583

Space ambience comes from here

**Comment by Baa14453** [comment]
> https://www.newgrounds.com/audio/listen/67583
> 
> Space ambience comes from here

It's the right song but the timing doesn't add up, ours is 3:33 SolusLunes' is 1:09 maybe someone edited it or we're using a remix or something?

**Comment by Baa14453** [comment]
Let me know if you can tell any difference in quality from my compressed versions I can easily raise the bitrate until we get it right

**Comment by Baa14453** [comment]
1.ogg is a bit weird, the original version was almost 40 seconds shorter?
Other than that they seem very very similar, it was just the credits song from Half Life 1
Not sure how Valve feel about us using it, probably indifferent, couldn't find any license information anywhere on Steam.

**Comment by Baa14453** [comment]
b12_combined_start is literally a combination of dwarf fortress intro sound files, I tried to concatenate them to re-create it but there's some extra mixing in there so instead I've just compressed it and added metadata.

song_game.ogg is also from dwarf fortress it's unchanged from it's original file, I didn't touch the metadata just compressed it.

All asset files for dwarf fortress are public domain, see the attach readme.txt that was with them.
[readme.txt](https://github.com/Aurorastation/Aurora.3/files/5211871/readme.txt)

**Comment by Baa14453** [comment]
Something's wrong I can feel it
image
Travis pls ;q;

**Comment by Baa14453** [comment]
ok 1.ogg is definitely different.

**Comment by Baa14453** [comment]
I found it, 1.ogg is a remix of the HL1 credits song by Valve for Half Life 2, it's a part of their soundtrack, it's called Tracking Device

**Comment by Baa14453** [comment]
Traitor.ogg was easy, someone told me what it was on Youtube. It's part of the OST for the HL2 mod Minerva Metastasis, I've downloaded a new version from the artists' bandcamp and compressed it down to 61k. This file is actually larger than the previous because it was compressed to 45k, I dare not compress it further anyway.

**Comment by Baa14453** [comment]
Cool I managed to contact the author of Clouds of Fire
There's nothing to compress in this file though and converting it into an ogg file just makes it larger so I'll leave it as-is since it works anyway

**Comment by Baa14453** [comment]
The artist of Clouds of Fire has no license they want to apply so I've marked it as Public Domain.

**Comment by Baa14453** [comment]
Space Asshole's metadata is in-tact and the quality is fine so I'm not going replace it.
The original file can be found here if required: http://downloads.idlethumbs.net/music/chrisremo_spaceasshole.mp3

**Comment by Baa14453** [comment]
Last thing I need for this PR is an original version of title2, trying to contact the artist for that because ours is pretty poor quality, probably extracted straight from the youtube video.

**Comment by Baa14453** [comment]
No reply from Chef Boyardee so I'm using a new version of title2 I got from this youtube video: <https://www.youtube.com/watch?v=vHo7npmGcHU>
Seems much higher quality anyway

**Comment by Baa14453** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by Baa14453** [comment]
:tada:

**Pull request merged**
