### PR TITLE
Adds two more disabilities

### PR DESCRIPTION
**Pull request by ParadoxSpace**
Total colorblindness and good old regular blindness.

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
!review

**Comment by Kaedwuff** [comment]
I'm not sure what jobs you can logically perform on station while blind. That might be too far.

**Comment by Arrow768** [comment]
After discussion with the mins, blindness needs to be mechanically restricted to visitors or removed.

**Comment by ParadoxSpace** [comment]
how about remove

**Pull request merged**
