### PR TITLE
Fixes the trash compactor

### LINKED ISSUE #16231: [Bug]: The Crusher is not chushing.
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

When attempting to use the crusher, I activate the chrusher control, Initialize and see the two pistons and one airlock associated.

I start the crusher and the warning sounds emit and the lights turn yellow but the pistons don't move. After a few seconds there is a message "The hydraulic pump in the trash compactor spins faster and shuts down a few moments later."

### How to reproduce

_No response_

### Round ID

_No response_

### Staff ckey

_No response_

### PR DESCRIPTION
**Pull request by meep109**
The trash compactor currently can't be used because of piping blocking it. I've tweaked the placing of the piping so that the trash compactor can be used again.  

Thanks to ShakyJake for helping me with this

Fixes #16231

### CODE REVIEW

**Comment by meep109** [comment]
!review

**Comment by meep109** [comment]
Idk how to link issues but this would fix  issue #16231

**Review by atteria — CHANGES_REQUESTED** [review]
Looks like you've accidentally reverted the Spark remap.

**Comment by Doxxmedearly** [comment]
Merge master and it should fix the above

**Comment by meep109** [comment]
What I did should fix it

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Doxxmedearly — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
