### PR TITLE
Moves forgotten Diona hair/facial hair styles to body markings

### PR DESCRIPTION
**Pull request by feartheblackout**
title. im pretty sure i got all of them but let me know if i missed any

### CODE REVIEW

**Comment by feartheblackout** [comment]
!review

**Comment by feartheblackout** [comment]
!bugfix

**Comment by Arrow768** [comment]
I am not sure how this is a bugfix when new icons for new styles are added

**Comment by feartheblackout** [comment]
technically speaking they are old styles. i marked it as bugfix because it was not intentional to leave them out of my previous PR and it would be the fastest way to get them reimplemented

**Review by FluffyGhoster — APPROVED** [review]

**Review by Geevies — APPROVED** [review]

**Pull request merged**
