### PR TITLE
Adds onmob sprites for wristbound computers

### PR DESCRIPTION
**Pull request by alsoandanswer**
you can flip which wrist it's worn on too, I guess.
\
dreamseeker_Wg1a2SFX8i
dreammaker_vnPmdZaPK5

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by Geevies** [comment]
the new colours don't look as good as the previous ones, imo

**Comment by alsoandanswer** [comment]
> 
> 
> the new colours don't look as good as the previous ones, imo

just reusing the PDA colors. it's for consistency's sake.

**Comment by Geevies** [comment]
we're planning on removing PDAs eventually, so making the sprites look worse to look like them is probably a bad idea

**Comment by alsoandanswer** [comment]
> we're planning on removing PDAs eventually, so making the sprites look worse to look like them is probably a bad idea

radio headsets also use the same colors.

anyway, if we want our own artstyle,  we need to start changing stuff, especially here when these wristbounds are clearly ported from somewhere.

look geeves i really respect you as a coder but my hands are tied here. 
It's very clear that we don't want to port sprites, 
but providing nebulous feedback with literally nothing constructive other than 
"old ones looked better" and "looks worse" when i'm trying to make our own artstyle is not helping

**Comment by Geevies** [comment]
This looks like it's grayscaled to be colored by assigning a hex value to its color
image
image
image
image

This is removing color for no reason, making everything look dull and uninteresting
image

This blue seems a bit cartoonish, whilst the old one looked more grounded, the "gold" stripe giving it a command look
image

**Review by fernerr — APPROVED** [review]

**Comment by Arrow768** [comment]
> radio headsets also use the same colors.
> 
> anyway, if we want our own artstyle, we need to start changing stuff, especially here when these wristbounds are clearly ported from somewhere.

Given that I dont have an issue with changing the colors.
Consistency should be created/maintained if possible, so changing either the modular computers or the headsets with the goal of them having a common coloring scheme is reasonable.

**Pull request merged**
