### PR TITLE
Adding the captain voidsuit

### PR DESCRIPTION
**Pull request by Alberyk**
In this update:

- Remove all mess that is the captain armor
- Add a voidsuit version
- Removes the extra armor from the locker
- Fix them in the map

### CODE REVIEW

**Comment by NanakoAC** [comment]
you removed it twice, from two seperate files. What gives? Was it defined twice?
i dont see how thats even possible without compile errors

**Comment by Alberyk** [comment]
Because, it existed in twice different files, one in space suits and other in armor, that was somewhat needless.

**Comment by Nadrew** [comment]
The later definition would override anything set inside of it that's not set inside of the first definition. In DM you can define a datum as many times as you want in the code, whether it be to add more variables/etc elsewhere in the code or override the initial definition entirely.

**Comment by Nadrew** [comment]
Also, wouldn't the captain be better off with a hardsuit rig like the other heads?

**Comment by Alberyk** [comment]
Probably, but, hardsuits are really sprite expensive, and the most important point of this pr is cleaning up really old content that was not updated with the time. A captain hardsuit can be added later after some discussion related to it.

**Comment by skull132** [comment]
I think a personal voidsuit for him is fine: he has no direct need for a specialized RIG (unlike the RD or CE).

**Pull request merged**
