### PR TITLE
Update, 12JUL2016

### PR DESCRIPTION
**Pull request by skull132**
TODO:
- [x] Test airlock hatches
- [x] Test alcohol - Read #530 for more details
- [x] Test meteor event
- [x] Test held mobs further
- [x] Map in Chauncey
- [x] Break markup and report issues with it
- [x] Test the notification/welcome screen functionality

Any player is free to go onto the testing server and test stuff that's noted above. Once you have suggestions, issues, or positive reports, please reply here or create a new issue on the Issues tab. (Leave a comment if everything works as intended, but report an issue in case something is broken.)

### CODE REVIEW

**Comment by Code2200** [comment]
Emergency shutter icon lags during opening - The bottom clip thing  is the last thing to open when the shutter is opened.

**Comment by Aurum22** [comment]
Meteors properly begin striking 3 minutes after the event starts. 

A hull shield (100m, 0.1 Renwick, Max Rate Capacitor), seems to prevent the overwhelming majority of the damage. 

I ran three meteor events on one shield without taking it down and the most that happened was a hit on the unshielded toxins test area, a single broken airlock door & window at arrivals, and a hit on an external airlock near security. 

You can audibly differentiate shield impacts from hull impacts.

Shields themselves barely decrease in strength, even after a multitude of hits (they show as unstable in the generator but are essentially just as effective) since they recharge fast. Turning the shield off and then on shows the shield as stable again.

I encountered one anomalous event: A meteor seemingly struck mining, causing shutters to drop and atmosphere to vent, however, when I investigated via aghost, no damage to any of the walls or windows could be found in that area or any adjacent areas.

Also, when repairing airlocks associated with a control panel such as the ones in arrival, doors that have their electronics replaced or repaired lose their connection to the control panel. I do not know if this is a known bug.

**Comment by Aurum22** [comment]
The new hatches on the airlocks work well. They are fast and do not impede movement. They work whether a door is bolted or not. 

They do not seem to transfer atmosphere (so a drone can safely enter a vented room without an inflatable).

The sound effect appears to trigger properly. 

The hatch disappears from the door sprite when opening- I do not know if this is just a WIP or intentional.

**Comment by Bedshaped** [comment]
#474 isn't working correctly. It's connecting okay but it isn't compiling the list of templates properly.

**Comment by Arrow768** [comment]
I´ll look into 474

**Pull request merged**
