### PR TITLE
Fixes some SSAssets issues.

### PR DESCRIPTION
**Pull request by MarinaGryphon**
- Fixes an infinite recursion in vendor spritesheet code.
- Fixes missing placeholder item sprites causing SSassets warnings.
- Assets now load after SSplants.
- Removes the now-useless delayed asset load variable.

### CODE REVIEW

**Comment by MarinaGryphon** [comment]
fuck you too vscode

**Comment by MarinaGryphon** [comment]
!review

**Comment by MarinaGryphon** [comment]
https://i.imgur.com/hteOZIJ.png proof it works

**Comment by MarinaGryphon** [comment]
!bugfix

**Review by Geevies — APPROVED** [review]

**Review by JohnWildkins — APPROVED** [review]
i hate seeds

**Pull request merged**
