### PR TITLE
Removes the Schoolgirl Uniform

### PR DESCRIPTION
**Pull request by Arrow768**
As it sais on the tin

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
For why?

**Comment by alsoandanswer** [comment]
these are extremely valuable costumes for the theater in the bar, please don't remove

**Comment by Kaedwuff** [comment]
> these are extremely valuable costumes for the theater in the bar, please don't remove

Do we really need the theater though? What does it contribute?

**Comment by VTCobaltblood** [comment]
The theater is fine. We just need to remove some specific costumes from it. Though, I wouldn't be opposed to removing it wholesale, or replacing aaaaall the maint clothing with something interesting.

**Comment by Kaedwuff** [comment]
Maybe we can actually get around to removing the clown costume....

**Comment by AmoryBlaine** [comment]
Reminder, I am spriting nearly everything, and am currently trying to make some of the meme clothing less offensive visually and cooperate with my grand aesthetic. So yeah, remove this sorta stuff if you want to. Just expect me to whine to have it re-added later.

**Comment by alsoandanswer** [comment]
Feedback thread please

**Comment by skull132** [comment]
> Feedback thread please

We really don't need a feedback thread to remove something which is clearly a meme (see the description) and only available via cargo.

**Pull request merged**
