### PR TITLE
Horizon mapping - deck three checkpoints

### PR DESCRIPTION
**Pull request by courierbravo**
Adds checkpoints to deck three, and shuffles around the 2 spare lockers.
Adds another xenogun to the horizon. Now theres three security have access to, and one xenobiology has access to.
Fixed some wonky areas i noticed.
Makes the deck two checkpoint a little nicer looking.

### CODE REVIEW

**Comment by courierbravo** [comment]
!review

**Comment by DreamySkrell** [comment]
As discussed on discord, I do not like the idea of docking arm security checkpoints.
- We should encourage interactions and roleplay, and checkpoints with shutters can be used to do exactly the opposite, to gatekeep visitors from interacting with the rest of the ship.
- Security already dominates a huge chunk of gameplay, and I do not think they should get more of that. A security checkpoint means that security can hold up any visitors, search them, and deny entry if they find anything they consider "illegal".
- Antags like mercs or raider may have a harder and even slower time getting onto horizon, if they now have to go through a checkpoint. Getting a gimmick going is slow as hell already, and a checkpoint will not make it any faster.
- I've seen people say that security should be bwoinked for just closing the shutters, or for camping the checkpoints during antag rounds. Being bwoinked for things that make perfect sense IC. I am against adding things that are "bwoink traps" like that, where using a thing like it's realistically intended to gets you bwoinked.

**Comment by courierbravo** [comment]
> As discussed on discord, I do not like the idea of docking arm security checkpoints.
> 
>     * We should encourage interactions and roleplay, and checkpoints with shutters can be used to do exactly the opposite, to gatekeep visitors from interacting with the rest of the ship.
> 
>     * Security already dominates a huge chunk of gameplay, and I do not think they should get more of that. A security checkpoint means that security can hold up any visitors, search them, and deny entry if they find anything they consider "illegal".
> 
>     * Antags like mercs or raider may have a harder and even slower time getting onto horizon, if they now have to go through a checkpoint. Getting a gimmick going is slow as hell already, and a checkpoint will not make it any faster.
> 
>     * I've seen people say that security should be bwoinked for just closing the shutters, or for camping the checkpoints during antag rounds, or for ordering a secoff to guard the checkpoint. I agree that these should be bwoinkable, but these are bwoinks for things that make perfect sense IC. I am against adding things that are "bwoink traps" like that, where using a thing like it's realistically intended to, gets you bwoinked.
> 
>     * Not sure if shutters can be destroyed, but if they require a C4 to get through them, then these checkpoints should not have shutters. And there should be only one set of shutters, not two, at least.

These concerns, while valid, are hypothetical. I don't believe that just because these _can_ be used to stifle RP is a good argument against them. The ship guns can do that all the same, and yet we have those. Just because something can be used negatively doesn't mean its guaranteed to be used that way, or a good reason to not incorporate it. 
Security already searches visitors for anything that is illegal, as written and dictated by CCIA. Antags like Mercs and Raiders have multiple ways of entering the ship beyond the docking arm. They can walk 5 tiles to the left, put up a couple inflatables, and break a window. They can just not announce they're here until they're here. EVA or Explosives is a pretty low bar, since both options are provided to mercs at no cost, and to raiders with small cost. 
The checkpoint is no more a trap than the armory is. There's no reason to employ security measures on code green like having the shutters down or the armory open. We already have checkpoints, and historically used checkpoints, with little to no issue. And what issues were had, moderation was there to tell people to knock it off.

**Comment by DreamySkrell** [comment]
My opinion's unchanged. I do not think docks checkpoints are a good idea at all.

But as discussed on discord a while ago, shutters need to be destroyable and deconstructable in ways other than C4 or whatever, before this is merged.

**Comment by courierbravo** [comment]
Hazelrat is working on that, as seen in #19969 
The plan as discussed in the devcord is to merge some kind of way to destroy them other than C4, then merge this.

**Pull request closed without merging**
