### PR TITLE
Gives the TCFL Away Ship the Constitution

### PR DESCRIPTION
**Pull request by Ben10083**
As the title says, placed the Biesel versebook on the ship for those more patriotic Legionnaires.

image

### CODE REVIEW

**Comment by Ben10083** [comment]
image

**Comment by Ben10083** [comment]
!review

**Comment by EmperorJayJay** [comment]
God bless biesel

**Review by KingOfThePing — APPROVED** [review]
god bless the republic

**Review by alsoandanswer — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
