### PR TITLE
Various Changes

### LINKED ISSUE #2025: Warrants authorized by the AI use the default spawn name instead of the AI's chosen name
Game ID bNL-dp3X

In this case, I spawned with the name 'GREP', and set my name to 'E.C.O.M.' using the name popup box that appears. When placing a test warrant for an unrelated reason, I noted the bug:

github

### PR DESCRIPTION
**Pull request by Arrow768**
A bug:
* Synthetics are no longer able to authorize warrants. Fixes #2025 

Various requests from the suggestions forum:
* Removed bootknives from custom loadouts
* Added crowbars to all borg modules that were missing them.
* Removed flashbangs from the officer lockers and the security vending machine

Some other things:
* Warden access is now required to access the armory with the flashbangs, heavy vests, ...
* Fixed a issue with udp logging (wrong text in a log message)
* .45s now spawn in the officer lockers
* Flares now spawn in the officer lockers
* The crate containing the door locks has been relocated
* Added cadet lockers with essential cadet gear
* Replaced two officer lockers with two cadet lockers, so there are now 4 officer and 2 cadet lockers in security
* Warrant assistant now shows Location / Suspect for the search warrants (instead of only the location)

Testing ToDo:
- [ ] Check if boot knives are removed from the loadout
- [ ] Check if flashbangs are removed from the officer lockers and the vending machine
- [ ] Check if the AI / Synthetics are no longer able to authorize warrants
- [ ] Ensure that the Warden / HoS are still able to do so
- [ ] Check if the crowbar is available for all borg modules

### CODE REVIEW

**Comment by printer16** [comment]
Can you get some feedback on this? Specifically "Warden access is now required to access the armory with the flashbangs, heavy vests, ...". I'd say move flashbangs back one more but keep access on this part of the armory unrestricted. It contains biohazard suits, bomb suits, barriers, door locks, and rubber pistols.  I and others really disagree with locking this off behind warden access as they aren't too terribly dangerous to warrant them being locked off behind warden access. If you really want, I'd suggest throwing flashbangs into the wardens office or into the tactical vendor that is in the tactical part of the armory. The heavy vests could be relocated as well, but there isn't much use in locking off that entire part of the armory to warden access.

**Comment by Arrow768** [comment]
The issue we have is that security rushes most hostage situations right now.
These things have been ahelped, but it hasnt really helped.

The main tools used in these hostage situations are located in the normal armoury.
By taking away the general access to the armoury and limiting them being handed out it is quite likely that security will stop rushing these situations as they have a lack of the tools needed to "throw-shoot-bang-cuff".

Going through the list of items in the armory:
- Heavy Armor Vests - Only needed if you have a heavily armed opponent
- Bomb Suit - Only needed during a bomb threat (usually implies a code blue or higher)
- BioHazard Suit - Rarely ever gets used.
- Barricades - Riot situation (usually implies a code blue)
- Flashbangs - Tactical Tool for use in planned assaults
- Door Locks - Usually required only in very specific situations.
- .45 Pistols - A more lethal alternative to the taser. (Useful if facing a enemy equipped with emp grenades, ...)

Almost all of these tools have a use in very special situations.
Most normal situations can be handled with the tools available in the officers lockers.
And if you want something from the armoury, just go talk to the warden.

I suspect that the reason for you comment are the .45s
I don't see what's so terrible talking to the warden and requesting a .45.
It allows them to keep track of everything going in and out of the armoury and restock items as needed.
Also we didn't have .45s previously and security was doing just fine.
(We also didn't have the issue that security rushed most of the hostage situations)

**Comment by printer16** [comment]
Alright. How about this, remove the box of the flashbangs from in there, toss them into the tactical vendor as non-contraband and still apply the warden access to the door you are wanting to? No real harm in it after thinking about it. Also, it would make more sense to put them into a tactical vendor instead of on a shelf in the non-tactical armory, considering they are tactical items.

**Comment by NanakoAC** [comment]
I'm with printer here, the unsecured armoury has always been called that for a reason, it contains nonlethal gear which is of vital use to a security force. This change will be heavily hated by the playerbase and i dont see a need for it

Locking this door has infact been suggested  in the past, and proved unpopular. Jackboot weighed in on it https://forums.aurorastation.org/viewtopic.php?p=61577#p61577

And restricting flashbangs... Just why? They're pretty important for fighting blobs and a handy nonlethal asset to have for a variety of situations

But the most important thing is those rubber bullet pistols. They're a median point between tasers and lethal weapons, and they're an officer's first line of defense to  stand a chance against an antag. Pistols aren't going to kill anyone with rubber, but they at least allow a skirmish and to force people to retreat.  
Without even that, i predict you're going to see even more instances of antags ganking sec officers. And you're going to never see those pistols used again .There's literally no point in them, if you've got a warden to open the armoury he's probably doing it for lethal weapons.

I'd say this kind of balance change needs some public discussion first. And as pointed out, it infact HAS had that discussion, i'd argue the results were weighted against doing it.

**Comment by Arrow768** [comment]
Flashbangs will be restricted.
There has been a threat about it. Administrators have requested it. It is going to happen.

As mentioned previously almost everything in the armoury is for use against special threats.
Be it bombs, riots, whatever.
The only thing from the armoury that sees regular use today are the rubber pistols.
But as mentioned above you can still get them. Just ask the warden.
And if there is no warden present you can just refer up the chain of command or to the AI.

Two more things to note:
* You are, again, quoting out of context. The threat you linked is about setting a guideline of what items security is allowed to wear on what alert levels. I have not seen a mention in there that the armoury should receive a access restriction nor have I seen a statement against it (If there is, please PM me with a link to it, because then I have overseen it)
* There has been a discussion about this in the staff discord channel which you choose not to participate in.

**Comment by NanakoAC** [comment]
Fine i saw the thread about flashbangs.

But i don't agree on the armoury.
I'm in discord every day, its a constant stream of information which is a struggle to keep up with. Nobody informed me such discussion was taking place, theres no reason to assume absence was a conscious choice.

Who exactly approved this decision? Because as linked above in that thread, which is entirely relevant and within context, the community doesn't seem to want this. What you're doing here will have the same effect that the OP of that thread wanted, and that several people argued against. They are the same issue

**Comment by Arrow768** [comment]
Armory

Lockers now contain flares by default
Lockers now have a 70% chance to contain a .45
Removed the .45s from the armoury
Relocated the Crate containing the door locks

**Comment by Arrow768** [comment]
After discussing with the mins, there have been a few more changes:
There is now a cadet locker for the cadets.
Officer lockers now have a 100% chance to contain a .45
Replaced two officer lockers with cadet lockers for a total of 4 officer and 2 cadet lockers

**Pull request merged**
