### PR TITLE
Taking damage or attacking remove stealth.

### PR DESCRIPTION
**Pull request by Akrilla**

### CODE REVIEW

**Comment by Akrilla** [comment]
Apart from the animation when taking decloaking from taking damage, this works fine.

**Comment by skull132** [comment]
My main issue with the way you accomplished this is that `INVISIBILITY_LEVEL_TWO` is used in other cases as well.

Maybe simply expand all of these if conditions to include `&& back && istype(back, /obj/item/weapon/rig)`. This way, we check whether or not the invisibility is the result of a RIG being used.

**Comment by Akrilla** [comment]
The ninja code also does invisiblity like that this, though.

**Comment by skull132** [comment]
And ninja wears a RIG. A ninja RIG! `/obj/item/weapon/rig/light/ninja`

**Pull request closed without merging**
