### PR TITLE
Allows drones to screw things. Fixes #8650

### LINKED ISSUE #8650: Maintenance Drones cannot screw things
Maintenance drones cannot screw, they definitely used to be able to.

Probably because they do not have a screwdriver, but they do have an empty spot in their inventory.
Coincidence?

Maybe...
image

### PR DESCRIPTION
**Pull request by Baa14453**
I was going to write some weird story about a drone wanting to screw a window but I gave up.
Fixes #8650.

(sorry for two commits to change one line)

### CODE REVIEW

**Comment by Baa14453** [comment]
!review

**Comment by Baa14453** [comment]
got you some sweet pics

## After
Screenshot from 2020-04-12 23-30-38

**Comment by Menown** [comment]
Phrasing.

**Comment by Baa14453** [comment]
!bugfix

**Pull request merged**
