### PR TITLE
Idris Ordering Terminals

### PR DESCRIPTION
**Pull request by Casper3667**
An idris ordering terminal. It lets a chef/barkeep set the menu, people can pick & choose if they wish and then pay and get a receipt along with a ticket to hand to the chef. Making the lives just slightly easier whenever the HoP decides food costs credits.
It is mapped in by the bar and kitchen.

image
image
image
image
image
image

### CODE REVIEW

**Comment by Casper3667** [comment]
!wip

**Comment by Casper3667** [comment]
!review

**Review by Geevies — APPROVED** [review]

**Comment by Casper3667** [comment]
So last night I was sent a new sprite by Someone Random so that got thrown in with an animation and slightly updated receipts.
image
image

**Comment by Karolis2011** [comment]
So this is same thing as Quik-pay just stationary?

**Comment by Casper3667** [comment]
> So this is same thing as Quik-pay just stationary?

In a way, yes. It was inspired by the quikpay but some of the differences includes how the screens are, the fact it is id based, always goes to civilian account and the fact that rather than the chef setting what each person buys from the quikpay, this one will print a ticket (last image, right paper) that can be given to them so they can see waiting orders without being interrupted by having to input it all themselves.
So in essence a stationary, quikpay inspired machine that the customers use rather than the chef.

**Review by Alberyk — APPROVED** [review]

**Review by Geevies — APPROVED** [review]

**Comment by Arrow768** [comment]
They should be mapped in

**Comment by Casper3667** [comment]
> They should be mapped in

They are, by kitchen & bar

**Comment by Casper3667** [comment]
and I realised I never made a comment mentioning that. My bad

**Pull request merged**
