### PR TITLE
Gives Investigators Holding Cell Access

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR gives investigators access to the holding cells.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!bugfix

**Comment by SleepyGemmy** [comment]
!bugfix

**Comment by SleepyGemmy** [comment]
wrong label out of habit.

**Comment by SleepyGemmy** [comment]
!review

**Comment by N8-Toe** [comment]
Been playing alot more investigator lately, I think this would be a good change as it would allow them to interview people during their processing, or more easily collect evidence from them. I wouldn't see this as any form of power creep as they are not getting access to the prison "proper"

**Review by NonQueueingMatt — APPROVED** [review]

**Review by JohnWildkins — APPROVED** [review]

**Pull request merged**
