### PR TITLE
AI Programs such as Command and Communications now work

### PR DESCRIPTION
**Pull request by Ben10083**
AI programs added in a previous PR were not given the correct flags. Teleport program removed as it was not needed + useless (only usable for nearby teleporter)

### CODE REVIEW

**Comment by Ben10083** [comment]
!review

**Comment by Ben10083** [comment]
!bugfix

**Review by Arrow768 — CHANGES_REQUESTED** [review]
AI Access to the accounts db is not desired.

**Comment by Ben10083** [comment]
> AI Access to the accounts db is not desired.

Requested change done. Accounts removed from AI computer @Arrow768

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
