### PR TITLE
The Milsurpening

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
Adds a flak jacket, helmet, camo fatigues, and a boonie cap. The plan I have for the flak gear and fatigues is to have it added as a cheap thing you can order from cargo, or potentially to be integrated as armor that can be ordered by revheads. The flak gear is better than nothing, but is inferior to just about any other sort of normal armor.

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Comment by skull132** [comment]
Not a fan of items being added without being integrated into the game. They tend to be left to rot and around as "Just because".

**Comment by TheDanseMacabre** [comment]
@skull132 I plan to have them added to cargo and will be talking to Alberyk about it after this is merged. I'm also going to make a part II PR that adds this gear to antag uplinks.

**Comment by NonQueueingMatt** [comment]
> 
> 
> @skull132 I plan to have them added to cargo and will be talking to Alberyk about it after this is merged. I'm also going to make a part II PR that adds this gear to antag uplinks.

Do this now, in this PR

**Comment by TheDanseMacabre** [comment]
I'm going to re-do this some other time, maybe...

**Pull request closed without merging**
