### PR TITLE
Overloader balance tweaks

### PR DESCRIPTION
**Pull request by hazelrat**
Halves the price of overloaders from 200 to 100. Free IPCs are an economically disadvantaged group so something aimed at them probably shouldn't be so expensive.

Triples the amount of time overloaders last. 30 seconds was too short a time for meaningful roleplay to occur, especially given how much they cost.

### CODE REVIEW

**Comment by hazelrat** [comment]
!rveiew

**Comment by hazelrat** [comment]
!review

**Review by FluffyGhoster — APPROVED** [review]

**Review by Geevies — APPROVED** [review]
just needs the ipc team to sign off on it i think

**Comment by NobleRow** [comment]
I am lore guy and I approve this message.

**Pull request merged**
