### PR TITLE
Intrepid changes and fixes.

### LINKED ISSUE #14036: The Intrepid's air cyclers are too slow due to them using the shuttle's air pressure tank in stead of a separate air canister.
All other airlock cyclers use a half-filled air canister because that design facilitates the fastest cycling. With a whole pipenet and a pressure tank, the intrepid cyclers have too much volume to work with and take forever. They need a separate pipenet with just a half-filled canister.

### PR DESCRIPTION
**Pull request by GrayRachnid**
Changes a few issues I saw with the intrepid

- Cyclers are no longer slow as hell
- The cargo bay exit is now 4 tiles larger to accommodate its role as a cargo bay exit
- Lost the armory in exchange for more space. The two weird guns are now just in the cockpit in a locker
- The ramp and the railings are gone. The floor just transitions to wood now
- Took out a water tank, a crate and the ore box in exchange for some space that people can park stuff in
- Replaced the welding and electrical closets with two tool closets(these have RNG tools) because having two closets that pilots can't open is silly
- Removed the second thrusters console. Don't need more than one.

Downsides. Some walls had to go. The only thing between the engine/atmos compartments and space are the shuttle part structures. They keep the air off.

image

https://user-images.githubusercontent.com/6613514/169996279-c63ea5de-1e68-4014-a118-cb0f593be63e.mp4

https://user-images.githubusercontent.com/6613514/169996289-55505a40-5103-4729-8527-c00881fbbc7c.mp4

New cycling timers. Compared to the old ones, they are a complete minute faster. They can also be forced at 30 seconds with little downside. Of course, you can factor in lag as well and they're still a lot faster.

closes #14036 

If you'd like me to make further changes to it please tell me now while i'm still touching it up
### IC changelog
`After months of use and feedback, the engineers of the Horizon have taken into account what needs to be changed on the Intrepid and have modified it accordingly.`

### CODE REVIEW

**Comment by GrayRachnid** [comment]
!wip

**Comment by GrayRachnid** [comment]
oh motherfucker strongdmm did something to all the pipes in atmos ARRRRRGH i'll figure this out after sleep

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by GrayRachnid** [comment]
!wip

**Comment by GrayRachnid** [comment]
!ready

**Comment by GrayRachnid** [comment]
!review

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
