### PR TITLE
Adds Synthmeat Reagent

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Overview
Unathi were immune to the negative effects of eating junkfood because unathi aren't affected by nutrient effects. This PR fixes it so that synthetic meat is added to every junkfood item.

It also fixes a bug where random truffles didn't exist, and rebalances biomeat from the biogenerator.

### CODE REVIEW

**Comment by BurgerLUA** [comment]
!review

**Comment by JackBewt** [comment]
Unathi loredev and loremaster protest. One of the buffs of Unathi is their ability to eat meat otherwise dangerous to non-Unathi due to their evolution as carnivorous predators. If they can consume the raw flesh of toxin-riddled spiders and be fine, then they can eat junk-food made of synthetic meat and be fine. This is an intended feature of the race. Meat of any kind is fine, plant nutrients of any kind (excluding synthetic **meat**) are not.

**Comment by BurgerLUA** [comment]
Synthetic Meat is still meat. It's produced by mixing blood and clonexadone together. It's lab grown meat and not as nutritious, so unathi shouldn't get a benefit from it.

**Comment by BurgerLUA** [comment]
What you're proposing is pseudoscience. Unathi wouldn't have evolved to negate the effects of synthetic meat because synthetic meat has only existed since NanoTrasen's first contact. I would agree with you if the meat gave toxins or something but this is synthetic meat. It's supposed to fill you up but not be nutritious. It's like eating ricecakes, when you eat them you're given the illusion of being full however you'll get hungrier once it passes.

**Comment by JackBewt** [comment]
If I was flashing my badge I wouldn't be giving you my entire justification based on game design.

I know how hunger and nutrition works. I am talking from the perspective of feature and game balance.
Unathi are designed as carnivores. They can eat meat with no problem. Allowing them eat toxic spider flesh and toxic space carp flesh perfectly fine but then getting sick when they eat synthetic meat is the definition of intuitive design. The buffs and debuffs of the unathi are clear, concise, easy to understand, and you know what you're getting. 

"They can eat meat normally toxic to other species except synthetic meat which is a type of meat that gives toxins to Unathi"

Miss me with this clause-based dieting

**Comment by JackBewt** [comment]
" I would agree with you if the meat gave toxins or something but this is synthetic meat" is what I was responding to.

All I can say is meat is meat is meat is meat as far as unathi dieting is concerned.

**Comment by LordFowl** [comment]
Wouldn't it make more sense to simply have Unathi be effected by nutriment effects? I don't see any particular reason they wouldn't be except by a code inefficiency hearkening from the days of only nutriment existing without subtypes.

**Comment by Matthew951** [comment]
Why would it not make sense that the protein in synthetic meat is the same as the protein found in other meat? Synthetic meat IS real meat - it's just grown in a different medium. "Synthetic" does not mean "fake" - it only describes the method by which it was made.

**Comment by BurgerLUA** [comment]
Synthmeat could be add with fillers and bad cuts of protein. See how pink slime is made.

**Comment by JackBewt** [comment]
@LordFowl If Unathi are affected by nutrition affects would this have them struggle to eat bad meats?

And even if the synthmeat is a scary evil filler lab-grown slab of unholy abomitable meat, Unathi would still be fine eating it for gameplay purposes. Meat. Is meat. Is meat. Is meat.

**Comment by Arrow768** [comment]
For the reasons explained via discord, that PR will be closed.

**Pull request closed without merging**
