### PR TITLE
Tweaks Examination Code

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR clarifies the purpose of the extended description available on objects in the game and merges the cult description variable into the antag one.
this PR is a continuation of #13712.

## changes
- renames "desc_fluff" to "desc_extended", to better reflect its purpose.
- merges "desc_cult" with "desc_antag". removes "desc_cult".

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Comment by NonQueueingMatt** [comment]
This feels like it's trying to solve a problem that doesn't exist. We really don't need this much micro specification in description variables.

**Comment by SleepyGemmy** [comment]
> This feels like it's trying to solve a problem that doesn't exist. We really don't need this much micro specification in description variables.

fair! ill prob remove the cult desc variable, merge it into antag, and remove the newly added desc_humour variable.

**Comment by KingOfThePing** [comment]
Why does this have to be done? Meaning, why change this in the first place?

**Comment by SleepyGemmy** [comment]
> Why does this have to be done? Meaning, why change this in the first place?

comment addressed over DMs.

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by SleepyGemmy** [comment]
!bugfix

**Pull request merged**
