### PR TITLE
Weapon, pickaxe and shield resprite (and a bunch of other stuff)

### PR DESCRIPTION
**Pull request by alsoandanswer**
this resprites some weapons, 

namely the butterfly knife and switchblade to not be comically oversized 
(you know, they're...concealable.)
tweaks some other sprites too, like the handles of polearms and the stunbaton
this doesn't change how they look from afar, they're practically the same in glance value
riot shield taken from Eris (and tactical shield is a modified version of that)
made ebarrier use same colors as eshield (this makes more sense, honestly)

also bibles have been given a touch-up

edit : putting pictures for skull
https://i.imgur.com/srTLOho.png
https://i.imgur.com/fEUD2FO.png
https://i.imgur.com/1LfXwUL.png

### CODE REVIEW

**Comment by alsoandanswer** [comment]
stupid merge error.

**Comment by alsoandanswer** [comment]
!review

**Comment by alsoandanswer** [comment]
!review

**Comment by skull132** [comment]
Pictures motherfucking please. There's a guideline for this.

**Comment by Alberyk** [comment]
I think that arcane tomes might be missing if you deleted the icon from weapons.dmi, you will need to go to ritual.dm and change the icon var there.

**Comment by alsoandanswer** [comment]
@skull132 added pics for you

**Comment by alsoandanswer** [comment]
!review

**Pull request merged**
