### PR TITLE
Unapologetic Camera Nerfs

### PR DESCRIPTION
**Pull request by ParadoxSpace**
Deletes a number of cameras across the board for illicit roleplay or whatever else.
Also adds a few more shutters to Cargo.

**DOWNSTAIRS**
long term artifact storage
supplies storage (xenoarch)
xenobiology storage
data compilation office
medical staff facilities
quarantine autopsy
main morgue/autopsy lab is up for debate
engineering downstairs storage/break room
all substations
sub-acutes (patient dorms)

**MAIN LEVEL**
robotics morgue
lower cargo warehouse
all break rooms besides engineering
substations
engineering fore exterior airlock cams
main custodial closet
evidence storage stairs
evidence storage
solitary cells
research maintenance airlock
bottom 3 bar tables (mos eisley cantina aesthetics)
useless camera at combined operating theater (before you get to an OR)
pre/post-op
temporary morgue
psych wing staircase (near break room and CMO office)
command restroom
hallway north of sec (to the east of the briefing room)
interrogation room (not the monitoring one. for hitting them in the testes.)
bridge auxiliary office
bridge cryo storage
engineering fore exterior hallway
all locker rooms
camera outside medical break rooms (redundant)
main level cryo
garden east room
rep backroom
medbay hallway outside substation
cryogenics control room
head offices except the captain's but put cams outside them
visitation, you can have an officer there
chaplain backroom
solitary cells
journalist office

**UPSTAIRS LEVELS / CONSTRUCTION**
psychiatry closet
room right before isolation room
the rest of the construction level
cargo construction room/camera outside
all substations

**SURFACE**
all substations
inside the locker room
dorms
possibly the conference room, up for debate
custodial closet
possibly part of the upstairs warehouse as well
vacant office
maybe aux tool storage
that thin sliver of camera in the changing room
running track (atleast the room with the staircase)
the pool tbh (there's a lifeguard seat already)
cryo
that little hall right east of the garden but west of cryo

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
!review

**Comment by Arrow768** [comment]
List the changes on github.
And list all the changes. 
As is some changes are undocumented.

**Comment by Sindorman** [comment]
Question: is removal of cameras intended to help antags remain undetected from AI/people? Or is it for non-antags?

**Comment by ParadoxSpace** [comment]
What changes are these, @Arrow768?

**Comment by Arrow768** [comment]
As mentioned on discord: The one I noticed was the chaplains office.
Double-check the map files for changes and ensure that all changes are listed directly on github (and not on a external document)

**Comment by ParadoxSpace** [comment]
This should be it
MAIN LEVEL
robotics morgue
lower cargo warehouse
all break rooms besides engineering
substations
engineering fore exterior airlock cams
main custodial closet
evidence storage stairs
evidence storage
solitary cells
research maintenance airlock
bottom 3 bar tables (mos eisley cantina aesthetics)
useless camera at combined operating theater (before you get to an OR)
pre/post-op
temporary morgue
psych wing staircase (near break room and CMO office)
command restroom
hallway north of sec (to the east of the briefing room)
interrogation room (not the monitoring one. for hitting them in the testes.)
bridge auxiliary office
bridge cryo storage
engineering fore exterior hallway
all locker rooms
camera outside medical break rooms (redundant)
main level cryo	
garden east room
rep backroom
medbay hallway outside substation
cryogenics control room
head offices except the captain's but put cams outside them
visitation, you can have an officer there
chaplain backroom
solitary cells
journalist office

UPSTAIRS LEVELS / CONSTRUCTION
autopsy lab
psychiatry closet
room right before isolation room
the rest of the construction level
cargo construction room/camera outside
all substations

DOWNSTAIRS
long term artifact storage
supplies storage (xenoarch)
xenobiology storage
data compilation office
medical staff facilities
quarantine autopsy
main morgue/autopsy lab is up for debate
engineering downstairs storage/break room
all substations
sub-acutes (patient dorms)

SURFACE
all substations
inside the locker room
dorms
possibly the conference room, up for debate
custodial closet
possibly part of the upstairs warehouse as well
vacant office
maybe aux tool storage
that thin sliver of camera in the changing room
running track (atleast the room with the staircase)
the pool tbh (there's a lifeguard seat already)
cryo
that little hall right east of the garden but west of cryo

**Comment by Sindorman** [comment]
@ParadoxSpace Could you reply to my question?

**Comment by ParadoxSpace** [comment]
It was already answered in the OP. It's for anyone, as well as trimming of redundant cams.

**Comment by Arrow768** [comment]
After discussion with the other headdevs/mins this is being closed as excessive.

**Pull request closed without merging**
