### PR TITLE
Pre spawned pills, now show amount of reagen

### PR DESCRIPTION
**Pull request by NortonDK**
This pull will make all the pre spawned pills around the station show how much of the reagent is in the pill. just like when the chemist makes em.

### CODE REVIEW

**Comment by NortonDK** [comment]
!review

**Comment by Fire-and-Glory** [comment]
Probably should not target master since it is not a bugfix.

I kind of feel like this is going to do something unintended somewhere else, are the pills still named normally when produced in chemistry?

**Comment by NortonDK** [comment]
This file should only touch the pre made pills, the one made in chemistry are completely new spawned, i will also move this to dev

**Comment by Fire-and-Glory** [comment]
I guess it'll probably be fine then.

**Comment by LordFowl** [comment]
If you are going to target dave  you should probably base from dave

**Pull request closed without merging**
