### PR TITLE
unifies unathi hair lists

### PR DESCRIPTION
**Pull request by ParadoxSpace**
Unathi now have the same hair as they do facial hair, and vice versa. This allows basically any combo. I mostly did this to have a dorsal frill and side frills at the same time.

### CODE REVIEW

**Comment by VTCobaltblood** [comment]
Goonstation hair layering when

**Comment by ParadoxSpace** [comment]
WYCI

**Comment by ParadoxSpace** [comment]
ree

**Comment by ParadoxSpace** [comment]
!review

**Comment by ParadoxSpace** [comment]
I'm like 99.9% sure it needs two files to function.

**Comment by Arrow768** [comment]
Please try what I mentioned on github

**Comment by ParadoxSpace** [comment]
as an update, which i DM'd arrow with days ago, what he mentioned on discord did not work. still needs two files.

**Comment by ParadoxSpace** [comment]
ready

**Pull request merged**
