### PR TITLE
Fixes ghosts being able to launch drop pods

### LINKED ISSUE #17089: [Bug]: Ghosts can launch drop pods
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

Ghosts can launch drop pods  onto the horizon, such as those in the centcom z level.

### How to reproduce

1. Go somewhere with a drop pod as a ghost, such as the TCFL base.
2. click the drop pod
3. you can use the buttons and it will launch the drop pod despite you being a ghost.
4. The empty drop pod arrives onto the ship.

### Round ID

_No response_

### Staff ckey

_No response_

### PR DESCRIPTION
**Pull request by DreamySkrell**
Fixes ghosts being able to launch drop pods

fixes #17089

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!bugfix

**Comment by DreamySkrell** [comment]
!review

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
needs a check for staff ghosts

**Review by Alberyk — APPROVED** [review]

**Comment by DreamySkrell** [comment]
> needs a check for staff ghosts

addressed

**Review by SleepyGemmy — APPROVED** [review]

**Pull request merged**
