### PR TITLE
Unapologetic Changeling Arm Blade Buff

### PR DESCRIPTION
**Pull request by Butterrobber202**
Changeling Armblades now have AP. That's pretty much it. They are still weaker than E-swords, but sec armor won't full stop them now. 

First PR in a hot minute.

### CODE REVIEW

**Comment by Butterrobber202** [comment]
oml I forgot .yml

**Comment by Butterrobber202** [comment]
!review

**Comment by Butterrobber202** [comment]
local village idiot was editing his master branch.

**Comment by Butterrobber202** [comment]
ok, reverted those other changes. No sneaky additions from me.

**Review by FluffyGhoster — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
