### PR TITLE
Adhomai ruins and People's Station fix and tweaks

### PR DESCRIPTION
**Pull request by Alberyk**
-tweaks some of the adhomai's ruins zones and mapping to take into consideration stuff like weather
-replaces the people's station windows with the newer ones
-expand the people's station hangar so the intrepid can land inside once again

### CODE REVIEW

**Comment by DreamySkrell** [comment]
image
this shuttle does not follow shuttle standards - it can't dock to anything like this, and should be using docking airlock markers

**Comment by DreamySkrell** [comment]
image
for visiting shuttles, use docks instead of hangars
this is unusable by most shuttles (other than horizon's - and even then only one horizon's shuttle can visit this)

there should also be more shuttle landmarks in space (rn there's only one, should be at least four)
and more external access airlocks (rn there's only a tiny 1-tile one by the solars)

**Comment by DreamySkrell** [comment]
all of the ghostroles should have welcome_text set, who do they answer to, what they are supposed to do (or not allowed to do), etc

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
as above

**Comment by DreamySkrell** [comment]
image

there are shuttle window spawner variants now, and they should be used in place of the boring black metal window frame spawners

see civilian yacht or scc scout for examples

both the raider and the other shuttle var subtypes should also have shuttle window subtypes, as these walls are used in a lot of places so it would be nice to have them defined in code

**Review by DreamySkrell — APPROVED** [review]

**Review by Geevies — APPROVED** [review]
code lgtm

**Pull request merged**
