### PR TITLE
Massive rec area remap into double holodecks

### PR DESCRIPTION
**Pull request by kyres1**
This PR takes the existing recreational area and moves its areas into holodeck presets, and doubles the size of the holodeck. It also adds a secondary holodeck, and a lot more holodeck utilities - like the ability to tint or lock your holodeck (which can be bypassed by command access), and the ability to use a holomenu-like sign at the door to let people know what the occasion is inside. The lights inside the holodeck can also be completely turned off or on with spotlights inside. Holodeck APCs are also now on an independent area as well, in case power priority is there for whatever reason.

Also, all service department staff can now lock the holodeck control panel, as well as command.

This PR is going to move the self destruct and command bunker somewhere else on deck 3. I haven't concluded on where, or began to move it yet.

Here's the remap in its entirety (pink lines are basically just open deck, where the entire 10km of rec area was removed);

holodeck

Noteworthy presets that are done include a tribunal alternative chapel, a Konyang noodle shop on the water, a Moghresian jungle and space basketball.

Some images of the usage of the holodeck(s),

Adhomian campfire,
image

Konyang noodle shop,
image

Moghresian jungle (with waving flag!)
image

Dominian tribunal alt-chapel (ripped straight from the Dominian corvette, basically)
image

Also, "fake" assets are now uniformly placed away into a "props" area of effects. That way we can stop leaving map and event props laying everywhere in our icon folder.

To-do 
- [x] Remaining unique holodeck presets (biesel using montparnasse sprites, venus, hopefully some callisto sprites, maybe some extras)
- [x] Figure out where the fuck to put the self destruct and bunker
- [x] Changelog

### CODE REVIEW

**Comment by kyres1** [comment]
!wip

**Comment by Greenjoe12345** [comment]
I wonder if the decks could be made larger so the holo chess board can actually be a proper size, or would that be too hard of a job to fit in?

**Comment by kyres1** [comment]
> I wonder if the decks could be made larger so the holo chess board can actually be a proper size, or would that be too hard of a job to fit in?

Yes. I think the chess board is not really worth the headache to fit into this already strained area

**Comment by Greenjoe12345** [comment]
Fair enough, Though in addition to this I'm wondering where things such as the nuke, command bunker and Patience the tree have been moved to? The latter is less important but the other two are rather important

**Comment by kyres1** [comment]
> Fair enough, Though in addition to this I'm wondering where things such as the nuke, command bunker and Patience the tree have been moved to? The latter is less important but the other two are rather important

The PR comment says that it is going to be moved but has not been decided yet

**Comment by lavillastrangiato** [comment]
So you're just going to remove all of that rec area and not put anything there? I'm not going to try and pull the weight of B-B-B-BUT I LIKED THE GYM but I do think it's a little wacky that the SCCV's flagship just got its pool and gym removed.

**Comment by lavillastrangiato** [comment]
DELETED MY OLD COMMENT BECAUSE YOU DID SAY THAT YOU'D BE ADDING (gym pool etc) IN THE HOLODECK but I still have a few questions.

Like, why this leads to the first deck. Why is this hole here?
image

I also want to point out that you shaved off a lot of the Horizon's third deck before deciding on where to put the bunker and the self-destrust sequence. IDK, to me it feels like you could probably move the holodecks up a bit and keep the bunker/self-destruct in generally the same spot as they were originally. I would even go so far as to suggest you could merk the gym and replace it with a holodeck, but keep the pool.

**Comment by Greenjoe12345** [comment]
> 

Kinda agree that the pool, at least should be kept, yes.

**Comment by Greenjoe12345** [comment]
Also regarding this, I had a bit of an idea for where Patience the tree could be moved to which I had an idea to work with in a different PR, but this could work together with it, possibly

**Comment by kyres1** [comment]
> Like, why this leads to the first deck. Why is this hole here? image

Holes are a commonly requested feature. Z-levels are sparsely used and the less holes we have, the worse off we are. Though that particular position is kind of crap because I didn't realize it was a straight drop to deck 1 in another area from the other holes; meaning it's prone to atmos problems, which is annoying. It'll be fixed.

> I also want to point out that you shaved off a lot of the Horizon's third deck _before_ deciding on where to put the bunker and the self-destruct sequence. IDK, to me it feels like you could probably move the holodecks up a bit and keep the bunker/self-destruct in generally the same spot as they were originally. I would even go so far as to suggest you could merk the gym and replace it with a holodeck, but keep the pool.

I can't move these positions without better reasoning, sorry. I am doing this primarily to bring gameplay closer to what is ultimately a very distant and sparsely utilized area of the map. The first idea was moving this formerly-really-important roleplay location to the unimportant rooms that occupy the space they should be in; being the CIC and self destruct.

Neither the CIC or self destruct actively or even in practice contribute roleplay by merit of being in a central position. On the other hand, if you're lounging around in a holo-gym alone, the likelihood of people running into you in one of the most easily-accessible halls we have is very beneficial.


> Also regarding this, I had a bit of an idea for where Patience the tree could be moved to which I had an idea to work with in a different PR, but this could work together with it, possibly

If it moves it to deck two, sure. I'm trying to avoid deck two as much as possible here because of map conflicts. Until your PR goes up I'll have Patience placed somewhere before I flag it for review

**Comment by alsoandanswer** [comment]
This needs a feedback thread

**Comment by kyres1** [comment]
https://forums.aurorastation.org/topic/18167-rec-area-remap-feedback/

> This needs a feedback thread

**Comment by kyres1** [comment]
!review

**Comment by kyres1** [comment]
Arrow requested that the CIC have less public access and mild rearrangement of the existing locales. So this needs changes until that's done

**Comment by kyres1** [comment]
Bunker and scuttle terminal were moved north of the crew armory, which was resized and now faces the hallway directly.

image

Crew armory is roughly the same size as before with the foyer chopped down a bit and exposed to the hallway. Maintenance continues to be an even more consistent loop around deck 3.

image

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
