### PR TITLE
Adds a automated ferry

### PR DESCRIPTION
**Pull request by Greenjoe12345**
Adds a small automated ferry to the Horizon's docks. It can be piloted by anyone, due to it being an autopilot control system, but can only be set to land or dock at nearby locations, and cannot freely fly on the overmap.

### CODE REVIEW

**Comment by Greenjoe12345** [comment]
!review

**Comment by DreamySkrell** [comment]
adding `maintainer discussion` label cause I'm not sure if we want another shuttle 
(that can be piloted by anyone and not just BCs/xenoarchs/etc)

**Comment by Butterrobber202** [comment]
> adding `maintainer discussion` label cause I'm not sure if we want another shuttle (that can be piloted by anyone and not just BCs/xenoarchs/etc)

not the pr author, but I think the intended goal of this pr is so BCs don't have to play ferryman and get to RP their normal stuff when we're at a location like konyang.

**Comment by Greenjoe12345** [comment]
> > adding `maintainer discussion` label cause I'm not sure if we want another shuttle (that can be piloted by anyone and not just BCs/xenoarchs/etc)
> 
> not the pr author, but I think the intended goal of this pr is so BCs don't have to play ferryman and get to RP their normal stuff when we're at a location like konyang.

Correct

**Comment by NonQueueingMatt** [comment]
Unwanted. We don't want a shuttle that everyone can pilot (even if it's just a ferry) and this poses gameplay problems - anyone could take it, fly down, and evade security while also being in ship range still.

**Pull request closed without merging**
