### PR TITLE
Diona / Nymph language learning and messages

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Changed raw html to macros in diona_base.dm.
Reduced learning points needed for nymphs to learn a language from 3 to 1.
Changed language learnt text to 'You have learned a little bit more about the X language'.
Changed blood sucking input prompt to '[user] just drained some of your blood, including some of your memory. Tell us something about yourself...'.

Implemented based on suggestion https://forums.aurorastation.org/topic/18229-very-minor-but-substantial-diona-nymph-learning-adjustments/#comment-164711

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!review

**Comment by Yonnimer** [comment]
Lore has given their approval for this

**Review by alsoandanswer — APPROVED** [review]

**Comment by Arrow768** [comment]
What happens if a Diona detaches a Nymph, that Nymph absorbs a few languages and then gets re-integrated into the Diona?
-> Do those languages transfer over?

**Comment by FluffyGhoster** [comment]
> What happens if a Diona detaches a Nymph, that Nymph absorbs a few languages and then gets re-integrated into the Diona? -> Do those languages transfer over?

I believe it does

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
