### PR TITLE
Space Mall!

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
This PR adds a civilian station. It features shopping areas, a food court, hotel rooms, pool, and slot room. Generally just a chill away site for people to visit and roleplay with the staff.

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Comment by alsoandanswer** [comment]
I took a look at this and this doesn't really feel like a mall. It lacks a lot of division and separation and partitioning of areas as well. This is more of a hallway with rooms. You'd have to run the entire length of the mall if you want to use the last dorm room. It should be more symmetrical.

For example, the "dorms". Shouldn't it be like a hotel or something? And the pool should probably have a gantry or something, or attached to the pool.

I feel like you could take any floor plan from a real-life shopping mall, and it would make more sense.

Shutter doors could also be used to "close" unused shops, like real life. Also, more variety. Like, there could be a coffee shop, a food court, a cafe, a fast food shop...anything goes.
At the moment, this mall doesn't really offer much above what we already have on the Horizon. We could use more variety in stores too; a clothing store, a tech store, hell, a gun store. 'Murica.

**Comment by alsoandanswer** [comment]
Screenshot_2022-07-05-11-50-33-00_6f8f7a6a69f2aa2976412416ecb84f7a
a hastily made rough idea of what im talking about

**Comment by TheDanseMacabre** [comment]
>I took a look at this and this doesn't really feel like a mall. It lacks a lot of division and separation and partitioning of areas as well. This is more of a hallway with rooms. You'd have to run the entire length of the mall if you want to use the last dorm room. It should be more symmetrical.

For example, the "dorms". Shouldn't it be like a hotel or something? And the pool should probably have a gantry or something, or attached to the pool.

I feel like you could take any floor plan from a real-life shopping mall, and it would make more sense.

Shutter doors could also be used to "close" unused shops, like real life. Also, more variety. Like, there could be a coffee shop, a food court, a cafe, a fast food shop...anything goes.
At the moment, this mall doesn't really offer much above what we already have on the Horizon. We could use more variety in stores too; a clothing store, a tech store, hell, a gun store. 'Murica.

It isn't actually a space mall. I just call it that. It's more like a rest stop and a motel combined. And they aren't dorms, they are hotel rooms. Saying it should be bigger and have more stores feels like a bad idea when it's going to be nearly impossible to fill an away site that's any larger than this with ghostroles. I don't think we actually need a full-sized mall away site, this should be perfectly adequate for our purposes.

**Comment by alsoandanswer** [comment]
If it's akin to a motel, the layout's kinda weird. Like. You need to go through reception to use the stores? There should be probably individual toilets for each room too.. Anyway. Here's a revised version. 
Screenshot_2022-07-05-13-36-59-45_6f8f7a6a69f2aa2976412416ecb84f7a

**Comment by TheDanseMacabre** [comment]
I don't really plan on changing the layout at all.

**Comment by listerla** [comment]
Is it intentional that nearly every role, including custodian, is human-only?

I also don't believe that allow_appearance_change needs to be set for each child of shopkeeper given it is set for shopkeeper itself; ditto with the species restrictions if intended to be human-only.

**Review by Alberyk — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
