### PR TITLE
Hatch fix, sleek medbay icons, icon selection update

### LINKED ISSUE #1773: Medical and rescue drones icon
Rescue modules have the option to become the rescue (green) drone icon and chemical (orange) icon.
Medical modules also have the option to become the rescue (green) drone icon and chemical (orange) icon.

With how the modules are currently equipped and the extra surgery (red) drone icon, it should be that rescue can only pick the green icon and medical the red or orange one.

### PR DESCRIPTION
**Pull request by AgentWhatever**
* Added a chemistry and surgery varient of the sleek cyborg icons
* Fixed that annoying issue with the open cyborg hatch witout battery
having a random pixel
* Medborgs can now choose sleek medic or chemist and drone medic or
chemist
* Rescueborgs can now only select either one sleek or drone icon

Fixes #1773

### CODE REVIEW

**Comment by AgentWhatever** [comment]
Did a better job in describing the icon selection fix in the bug report and the changelog.

* medic can now choose between the drone or sleek medic (red) or chemist (orange) variants. Rescue can only select the sleek or drone rescue (green) variant

**Comment by NanakoAC** [comment]
please post pictures of these new themes

**Comment by AgentWhatever** [comment]
https://puu.sh/u5GC9/79c0b99a57.png Sleek colors match the drone ones

**Comment by AgentWhatever** [comment]
I just noticed the heavy med and science borgs use the same icon. Not anymore
https://puu.sh/u5Jey/247d24d61e.png

**Comment by skull132** [comment]
Rebased onto dev, as it's not a bugfix.

**Pull request merged**
