### PR TITLE
This Is Not An April Fool's PR

### PR DESCRIPTION
**Pull request by LordFowl**
If you think it is, it isn't. Go away.

Adds slime-people:
"In the grim darkness of the far future there is only war. In orbit above the pitiful empires of man a million drums beat in perfect unison. War! War! War! The enslaving Kocasslani, a threat once thought diminished to irrelevancy, have returned. They have not spent these past years since their defeat in idleness - they have modified their spirits and their bodies to perfection using dark magic and NanoTrasen slime research stolen from slimified Xenobiologists, becoming the dreadful aberration: The Neo-Kocasslani. Their gelatinous bodies have transcended their previous mortal weaknesses, at only the cost of their immortal soul. With the demonic power of Satan on their side, all else shall crumble. Even now the Sol Alliance and the Jargon Federation lie in smoking ruins - Tau Ceti is next. Employed on NanoTrasen stations for their admirable work ethics and can-do attitudes, Neo-Kocasslani are a common sight throughout space, frequently praised for their good manners, reliability, intelligence, cannibalism, and innovation."

### CODE REVIEW

**Comment by OneOneThreeEight** [comment]
Noooo. These were removed for a reason.

You also stole my species spit idea for a concept that doesn't make a whole lot of sense.

**Comment by LordFowl** [comment]
Ah-ah-ah! It was an April Fool's PR all along!

**Comment by Pacmandevil** [comment]
we know your lies, fowl - this was naught but a failed attempt to get anime slime girls into the game

**Comment by LordFowl** [comment]
If you actually played you would've known this was nothing but a complete success.

**Pull request closed without merging**
