### PR TITLE
Adds new var to APCs that determines if they will trigger power alarms or not

### PR DESCRIPTION
**Pull request by Llywelwyn**
rscadd: "Added a new var to APCs that determines if they will trigger power alarms or not."

var/trip_alarm = TRUE // Determines if this APC will trip power alarms or not

made primarily for use in derelict away sites that will lose power, but have a network that can be powered by crew once they arrive - as it stands, away sites with an APC that has lost power will always appear on the power alarm monitor

### CODE REVIEW

**Comment by Llywelwyn** [comment]
!review

**Comment by Llywelwyn** [comment]
> It would be better to have some solution that checks if the alarm is being observed by someone on a connected z level, and/or by an alarm monitor that belongs to that ship.

I would agree with that - however, it's not something I have enough familiarity with to get done in a reasonable amount of time any time soon, so if this isn't something we want at all for the time being then feel free to close.

**Comment by NonQueueingMatt** [comment]
> > It would be better to have some solution that checks if the alarm is being observed by someone on a connected z level, and/or by an alarm monitor that belongs to that ship.
> 
> I would agree with that - however, it's not something I have enough familiarity with to get done in a reasonable amount of time any time soon, so if this isn't something we want at all for the time being then feel free to close.

Unfortunately, yeah, the ideal solution is what Myazaki wants. I do not believe it would be too hard to do what he mentioned, so you probably can take a crack at it.

**Comment by Llywelwyn** [comment]
> > > It would be better to have some solution that checks if the alarm is being observed by someone on a connected z level, and/or by an alarm monitor that belongs to that ship.
> > 
> > 
> > I would agree with that - however, it's not something I have enough familiarity with to get done in a reasonable amount of time any time soon, so if this isn't something we want at all for the time being then feel free to close.
> 
> Unfortunately, yeah, the ideal solution is what Myazaki wants. I do not believe it would be too hard to do what he mentioned, so you probably can take a crack at it.

Sounds g. I'll close and take a look if/when I have some time aside.

**Pull request closed without merging**
