### PR TITLE
Additional Medical Lobby Lighting

### PR DESCRIPTION
**Pull request by Ben10083**
https://github.com/Aurorastation/Aurora.3/pull/19779 likely removed the light at Medical Lobby due to layering weirdness, but I am adding it back because the lobby is now too dark.

image

### CODE REVIEW

**Comment by Ben10083** [comment]
!review

**Comment by DreamySkrell** [comment]
can't have overlapping lights and wall-mountable machinery (in this case the vending machine)

they're going to overlap in game and look bad

the lights are shifted on init into the wall, so it only looks fine in strongdmm

**Comment by Ben10083** [comment]
> can't have overlapping lights and wall-mountable machinery (in this case the vending machine)
> 
> they're going to overlap in game and look bad
> 
> the lights are shifted on init into the wall, so it only looks fine in strongdmm

tried moving it somewhere else
image
Still has some overlap, but just having no lights is also a no go as it currently looks like this otherwise
image

If you have better ideas to get better lighting contact me over discord

**Comment by courierbravo** [comment]
idk how it got removed from when I made the map edit, but what I did was put a floor light in front of the vending machine. Then used a half outline to fill in the other side of the tile. Like so, 
image

**Comment by Ben10083** [comment]
image

**Comment by Ben10083** [comment]
image
peopled asked for it flipped

**Review by DreamySkrell — APPROVED** [review]

**Review by Geevies — APPROVED** [review]

**Pull request merged**
