### PR TITLE
Security remap

### PR DESCRIPTION
**Pull request by Eyeveri**
Hi! I've remapped deck 2 Security to make it more consolidated. For the longest time I have felt that the Head of Securities office was in a very obtuse place. The armory was oddly organized and shaped, and the equipment room was pretty cramped. So, I decided to go ahead and remap it all. Attached below are a few photos of the proposed changes. 

- Images

Armory
Bathroom
Communal
Equipment
HoS
Overall

### CODE REVIEW

**Comment by Eyeveri** [comment]
!review

**Comment by Eyeveri** [comment]
I dunno what that first commit is. I probably clicked something without realizing it. Sorry @alsoandanswer !

**Comment by Greenjoe12345** [comment]
The bathrooms now being all the way across the department from the locker room seems a bit.. odd, 
image
and this diagonally-only connected wall section feels a bit off to me too
image
could easily be fixed by putting a wall there

**Comment by DreamySkrell** [comment]
Sorry, but I really do not like this. I think current brig is fine, and does not need a remap like this.

> Hi! I've remapped deck 2 Security to make it more consolidated. For the longest time I have felt that the Head of Securities office was in a very obtuse place. The armory was oddly organized and shaped, and the equipment room was pretty cramped. So, I decided to go ahead and remap it all. Attached below are a few photos of the proposed changes.

Currently HoS office is in a central place near the entrance to the brig. It makes it easy to host guests and hang around near or at the brig entrance, where non-sec people might potentially be. Your remap puts the HoS office literally at the end of the brig, furthest from the entrance, and the most isolated from everyone and anything. We do not want security to be even more insular and isolated than they tend to be currently.

Current armory layout is weird, sure, but your remap makes it even weirder and more cramped, not less, as it becomes that Z shape.

Current locker/equipment room is cramped, yes. But it's supposed to be - sec officers are supposed to gear up and go somewhere else, and not hang around there. But even then, I disagree that current locker room is cramped. It's a 5x7 room, pretty big.

**Comment by Eyeveri** [comment]
> Sorry, but I really do not like this. I think current brig is fine, and does not need a remap like this.
> 
> > Hi! I've remapped deck 2 Security to make it more consolidated. For the longest time I have felt that the Head of Securities office was in a very obtuse place. The armory was oddly organized and shaped, and the equipment room was pretty cramped. So, I decided to go ahead and remap it all. Attached below are a few photos of the proposed changes.
> 
> Currently HoS office is in a central place near the entrance to the brig. It makes it easy to host guests and hang around near or at the brig entrance, where non-sec people might potentially be. Your remap puts the HoS office literally at the end of the brig, furthest from the entrance, and the most isolated from everyone and anything. We do not want security to be even more insular and isolated than they tend to be currently.
> 
> Current armory layout is weird, sure, but your remap makes it even weirder and more cramped, not less, as it becomes that Z shape.
> 
> Current locker/equipment room is cramped, yes. But it's supposed to be - sec officers are supposed to gear up and go somewhere else, and not hang around there. But even then, I disagree that current locker room is cramped. It's a 5x7 room, pretty big.

It's okay if you don't agree, I truly appreciate the feedback. 

Sure, it is convenient now for the HoS to be able to host people - but the office should be in a more "secure" and consolidated area. Historically it has always been close to the Armory. I will add a "waiting" area outside of the office to encourage more people to meet and be able to wait. It isn't even possible for people to really wait for the HoS because the current hallway is so small. 

The armory is more compact now, this is true, but it is better organized and easier to get in and get out. The three wide Blast doors is also historically from the old Aurora Armory, and will be easier to function with. I can attempt to make it more "half and half" if you think it'd be better but, the idea was that the armor would be accessed first, and THEN the firearms. 

I went around to a lot of people and sought out feedback. I had a "large" Equipment room mapped, a much smaller one and then this one - and most people that I spoke with said they preferred this one.

**Comment by Eyeveri** [comment]
> The bathrooms now being all the way across the department from the locker room seems a bit.. odd, image and this diagonally-only connected wall section feels a bit off to me too image could easily be fixed by putting a wall there

I put the bathrooms at the current HoS spot because they are closer to the "public" area of Security, and will not cause the lobby-watching officers to walk across the department to AFK on a toilet. 

Also, I will fix the wall right now.

**Comment by Eyeveri** [comment]
Closing this PR as I have decided to just remap the entirety of deck 2 security. Toodles!

**Pull request closed without merging**
