### PR TITLE
Removes Weapons

### PR DESCRIPTION
**Pull request by Arrow768**
Removes /obj/item/weapon and turns it into /obj/item

### CODE REVIEW

**Comment by alsoandanswer** [comment]
holy shit what we bay now bois

**Comment by Sindorman** [comment]
Question. Why? 
From design point of view it is good to have weapon as subclass, since it is different mechanical than generic item.

**Comment by Arrow768** [comment]
> Question. Why?
> From design point of view it is good to have weapon as subclass, since it is different mechanical than generic item.

Sure, that would make sense from a design point of view, _if there were a mechanical difference._
As the only real mechanical difference is used exclusively by trays (which was a /obj/item/weapon) there is no reason to retain /weapon

**Comment by skull132** [comment]
> Question. Why?
> From design point of view it is good to have weapon as subclass, since it is different mechanical than generic item.

In practice, the `weapon` subclass is a dud. There is no behaviour inherit or uniform to children of it.

**Comment by alsoandanswer** [comment]
whoops sorry about this

**Comment by Geevies** [comment]
image

I'm going to need a Trial Developer to check these files for things that have been sneaked in.

**Pull request merged**
