### PR TITLE
Small telecommunications layout tweak, and fixed camera blindspots in the bridge and telecomms

### PR DESCRIPTION
**Pull request by hazelrat**
Added new cameras to the HR room, the XO's office, the conference room, telecommunications, the third deck area just outside of the HR room, and the INDRA office, to resolve several inconvenient blind spots for the ship AI. 

Slightly remapped telecommunications to make it more symmetrical and appealing, including normalising every gap between server racks to one tile, aligning all the vents horizontally, and expanding the east wall so it doesn't awkwardly cave in on one of the racks. 

image

Additionally, tweaked the maints just outside of telecommunications to be more uniform with the rest of the Horizon's maintenance tunnels, and made the master grid line more intuitive. The wiring was odd as a leftover from a previous mapping change, and I'm not honestly sure why this area was using full sized lights - nowhere else in maintenance uses them afaik, so if there was a reason for that, let me know!

image

### CODE REVIEW

**Comment by hazelrat** [comment]
!review

**Comment by WilliamMurdoch** [comment]
> Added new cameras to the HR room...

It would be preferred by CCIA that there isn't a camera added into the HRA office. The waiting area outside is fine as long as it can't see the inside of the office when the windows are dimmed, but the office itself should be without a camera.

**Comment by hazelrat** [comment]
> > Added new cameras to the HR room...
> 
> It would be preferred by CCIA that there isn't a camera added into the HRA office. The waiting area outside is fine as long as it can't see the inside of the office when the windows are dimmed, but the office itself should be without a camera.

Done!

**Comment by hazelrat** [comment]
Realised I did a dumb, telecommunications cameras have been returned to motion cameras and now belong to the Command, Security, and Tcomsat networks, rather than just to Command. Previously the third network was 'Telecommunications', which the telecomms camera console didn't actually recognize and doesn't seem to be standard for tcomms cameras in the code - so now the tcomms camera console works as intended.

**Review by NonQueueingMatt — APPROVED** [review]

**Review by FluffyGhoster — APPROVED** [review]

**Pull request merged**
