### PR TITLE
Combat Flailing Tweak

### PR DESCRIPTION
**Pull request by Geevies**
* You no longer hit pipes, vents, scrubbers, or cables if you're clicking on harm intent.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by GMR25** [comment]
I'll miss the 1/100 of some guy hitting a live wire and frying himself to death mid-combat.

**Comment by alsoandanswer** [comment]
You should probably check for instances where people want to hit inanimate objects to damage things rather than accidentally clicking them instead of trying to hurt someone

Mostly applicable for melee weapons, ranged weapons can ignore this

**Comment by FluffyGhoster** [comment]
As above, there's cases where people want to hit objects to destroy them, and should be able to; this seems to prevent it

**Pull request closed without merging**
