### PR TITLE
Mining Shuttle APC Access Tweak

### LINKED ISSUE #14070: Miners do not have access rights too the shuttles APC
This results in almost certain death should the shuttle hit an ion cloud or the power runs out, we are given a battery to swap it out with aboard the shuttle but no access too use it.

### PR DESCRIPTION
**Pull request by Ben10083**
Fixes #14070 

Turns out miners were supposed to have access but req_access wasn't set to null.

### CODE REVIEW

**Comment by Ben10083** [comment]
!bugfix

**Comment by WickedCybs** [comment]
> Fixes #14070
> 
> Turns out miners were supposed to have access but req_access wasn't set to null.

They're supposed to have access, but setting it to null means everyone would be able to unlock it I believe? That's not what I intended for the mining pod. It should be accessible only to the miners, the bridge crew and engineering.

**Comment by NonQueueingMatt** [comment]
Do what Cybs said.

**Comment by Ben10083** [comment]
Fixed. Also added bridge access to intrepid APC since apparently that was also needed.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
