### PR TITLE
Hand labeller change

### PR DESCRIPTION
**Pull request by LordFowl**
- tweak: "Hand-labellers now modify an object's description instead of it's name, and each label overrides previous labels."

### CODE REVIEW

**Comment by Fire-and-Glory** [comment]
I would ah, not think that'd be quite so good.

I for one label syringes with whatever medicine that I get in them if bottles are tight, syringe filled with bicardine labeled as bicardine like the inaprovaline and spaceacillin syringes, etc.

**Comment by Bedshaped** [comment]
Agree with @Fire-and-Glory

**Comment by LordFowl** [comment]
That is still possible, it simply requires more observation. This method is more flexible and lenient than the current method, and much cleaner as well.

**Comment by skull132** [comment]
Going to have to agree with the rest.

It'd be better to give the obj super-parent a var/label, and to have it modify that, if nothing else is available. That way you wouldn't be able to string labels together, you simply override the existing one, and would also be able to completely remove them.

**Pull request closed without merging**
