### PR TITLE
Goodbye, old friend (removing Aurora map)

### PR DESCRIPTION
**Pull request by FluffyGhoster**
https://youtu.be/GwgNS23SiXM

```
Hear my words and know the fate that awaits you. Once, this station was a beacon of Bisellian might, a testament to our unyielding dominion over the stars. Its halls sang with the glories of humanity, its walls bore witness to our victories. But now, it is a shadow of its former self, a relic of an age long past.

Decadence has taken root where duty once stood firm. The stench of decay wafts through these corridors, a vile mockery of our former greatness. We have allowed ourselves to become weak, complacent, a festering wound in the heart. For this, there can be no forgiveness, no mercy. We have failed what the God-Emperor Dorn's demands.

In the name of the God-Emperor, Exterminatus has been pronounced upon you. Know that this is not a punishment, but a purification. The fires that will consume it are the cleansing flames of the righteous wrath. Its names will be forgotten, the deeds erased.

This is the end, and yet, it is a beginning.

Look to the heavens and behold its doom. The dawn is upon it. Burn, Aurora, and may your death be a testament to the eternal glory of Biesel. Dorn protects, but He also judges. And His judgment is final.
```

Removed the old Aurora map, it is broken and keeps causing issues and wasted time trying to keep it from not failing tests (and take up time in the CI).

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
Short testmerge to ensure nothing imploded

!review

**Review by NonQueueingMatt — APPROVED** [review]
aw hell nah

**Review by DreamySkrell — APPROVED** [review]
aw hell yea

**Review by alsoandanswer — APPROVED** [review]
kill it

**Comment by pochetoo** [comment]
https://www.youtube.com/watch?v=WChTqYlDjtI

**Pull request merged**
