### PR TITLE
Radio Recolouration

### PR DESCRIPTION
**Pull request by Geevies**
* Headsets' object sprites have been changed to fit their departmental colours.

image

Feedback thread:
https://forums.aurorastation.org/topic/14999-feedback-radio-recolouration/

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by alsoandanswer** [comment]
:walter:

use the colors from the departmental softcaps please

**Comment by Geevies** [comment]
These are going to match the wristbounds of https://github.com/Aurorastation/Aurora.3/pull/10206.

**Comment by alsoandanswer** [comment]
then change the wristbounds as well?

**Comment by Geevies** [comment]
Having taken a look, it seems the colours fit the soft caps already.

image

Please forward any other requests to the feedback thread here:
https://forums.aurorastation.org/topic/14999-feedback-radio-recolouration

**Review by furrycactus — APPROVED** [review]

**Comment by furrycactus** [comment]
Same as I mentioned on the other one.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
