### PR TITLE
Right Side Up

### PR DESCRIPTION
**Pull request by Geevies**
* Hitting rest will now make you lie down instantly.
* Floating chat messages will now appear properly above resting humanoids.

### CODE REVIEW

**Comment by Geevies** [comment]
!bugfix

**Comment by Geevies** [comment]
!review

**Comment by alsoandanswer** [comment]
can't people abuse their hitbox by spamming rest?

IC'ly, it's justified because your getting on your knees and lying down instead of yeeting yourself to the pavement

**Comment by Geevies** [comment]
you can't attack or move while laying down, so you're changing your hitbox to the effect of that, which is.. an idea, i guess?

i never saw it as that, i just saw it as Life being slow as hell to make sure our 32bit system doesn't explode

**Comment by alsoandanswer** [comment]
i still think there should be at least a spam limiter. a simple sleep or timer.

**Review by JohnWildkins — CHANGES_REQUESTED** [review]
very good and cool but there should be a delay like wezzy said

**Review by JohnWildkins — APPROVED** [review]

**Pull request merged**
