### PR TITLE
Ports Unathi hairstyles + tails, removes human hair

### PR DESCRIPTION
**Pull request by listerla**
Sources: https://github.com/VOREStation/VOREStation/pull/14614 https://github.com/PolarisSS13/Polaris/pull/8754 https://github.com/PolarisSS13/Polaris/pull/9170

Not yet lore approved.

Also removes human hair because a past maintainer told me that its presence was an oversight.

### Asset Licenses
The following assets that **have not** been created by myself are included in this PR:

| Path | Original Author | License |
| --- | --- | --- |
| icons\mob\human_face\unathi_hair.dmi | Pawn (Baystation 12), [MistakeNot4892](https://github.com/MistakeNot4892) (Polaris), [Heroman3003](https://github.com/Heroman3003) (VOREStation) | CC BY-SA 3.0 |
| icons\mob\species\unathi\tail.dmi | [Greenjoe12345](https://github.com/Greenjoe12345) (Polaris) | CC BY-SA 3.0 |

### CODE REVIEW

**Comment by listerla** [comment]
!review

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
Keep the unathi mohawk, it isn't a human hair.

**Comment by DreamySkrell** [comment]
isn't unathi_elvis also unathi hair

**Comment by listerla** [comment]
> isn't unathi_elvis also unathi hair

No, it's taken from facial_elvis in the human hairs.

**Review by alsoandanswer — APPROVED** [review]

**Pull request merged**
