### PR TITLE
Chloral Rebalance

### PR DESCRIPTION
**Pull request by Kaedwuff**
Chloral hydrate is a very easy drug to make with any chemistry lab, and is incredibly debilitating.  It does not seem to matter how much we try to enforce not powergaming, people will continue to premake small batches for use in 'self defense' and antagonist hunting.  It is far too easy to shut someone down with this because even the smallest of doses cripple the target.

As a result, I am submitting this PR to re-balance the power of Chloral hydrate.

-Chloral hydrate no longer applies the 'weaken' effect (the one that makes you fall over paralyzed and helpless within seconds of being injected with it)
-Instead, a hefty 'drowziness' debuff is applied shortly after injection, which can cause the victim to periodically fall asleep for brief periods.  As a result, they are capable of attempting to stagger away somewhere to safety once they realize what happened
-Chloral hydrate does not knock you out unless the dosage is higher than 5u.  This makes it harder for people to charge you with a harm-intent syringe to instantly take you down, and gives you more time to react to it if they do.

Despite all of this, chloral still remains significantly stronger than soporific.  It WILL knock you flat, given enough time and a dosage of more than 5u.  It is just no longer an instant win chemical.

### CODE REVIEW

**Comment by Kaedwuff** [comment]
Oops. Mistake.

**Comment by Kaedwuff** [comment]
!review

**Comment by Arrow768** [comment]
Eh, that would make soporific (a diluted version of CH) more potent that CH.

For comparison 
Soporific:
```
	if(dose < 1)
		if(dose == metabolism * 2 || prob(5))
			M.emote("yawn")
	else if(dose < 1.5)
		M.eye_blurry = max(M.eye_blurry, 10)
	else if(dose < 5)
		if(prob(50))
			M.Weaken(2)
		M.drowsyness = max(M.drowsyness, 20)
	else
		M.sleeping = max(M.sleeping, 20)
		M.drowsyness = max(M.drowsyness, 60)
```
CH:
```
	if(dose == metabolism)
		M.confused += 2
		M.drowsyness += 2
	else if(dose < 5)
		M.drowsyness = max(M.drowsyness, 30)
		M.eye_blurry = max(M.eye_blurry, 10)
	else
		M.sleeping = max(M.sleeping, 30)
```

**Comment by skull132** [comment]
Closing. See Arrow's comment, it would render CH largely useless in favour of sopo. Alternate suggestions welcome.

**Pull request closed without merging**
