### PR TITLE
Station to Ship

### PR DESCRIPTION
**Pull request by CampinKiller24**
Changes references of station in the sentencing consoles and alert level changes to ship

### CODE REVIEW

**Comment by CampinKiller24** [comment]
!review

**Comment by Greenjoe12345** [comment]
There's a dynamic thing you can put in that'll say station or ship depending on what map is loaded, might be better to use that

**Comment by io-util** [comment]
> There's a dynamic thing you can put in that'll say station or ship depending on what map is loaded, might be better to use that

Yeah, exactly what Greenjoe said. There is a `station_type` var within a map that defines whether it is a ship, station or whatever else someone creative can think of some day.

https://github.com/Aurorastation/Aurora.3/blob/530c7530b993a713f49f62fc1c95f61ba5ff6d19/maps/_common/mapsystem/map.dm#L38

In example of the Horizon, it's ship of course:

https://github.com/Aurorastation/Aurora.3/blob/530c7530b993a713f49f62fc1c95f61ba5ff6d19/maps/sccv_horizon/code/sccv_horizon.dm#L33

I'd highly suggest using that variable everywhere station/ship should be mentioned @CampinKiller24

**Comment by CampinKiller24** [comment]
I'm not really sure of the need to make it dynamic, I can't think of any rounds where we've been on a station and can charge people/change the alert level since switching to NBT. Not that I'm necessarily opposed, I'm just not sure what there is to gain, with it already hardcoded as station at the moment.

**Review by Arrow768 — APPROVED** [review]
The relevant config files need to be updated on merge

**Comment by FluffyGhoster** [comment]
> I'm not really sure of the need to make it dynamic, I can't think of any rounds where we've been on a station and can charge people/change the alert level since switching to NBT. Not that I'm necessarily opposed, I'm just not sure what there is to gain, with it already hardcoded as station at the moment.

We could have back map rotation one day, we could be on a station during events, it can be decided to use another term (eg. vessel), sure it's not a big deal to hear ship or station, but since we're at it, what do we have to lose in putting the correct variable to get the station type from?

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
