### PR TITLE
Throw mode cursor icon

### PR DESCRIPTION
**Pull request by DreamySkrell**
2023-07-23--dreamseeker_10948_CzqFIOs38c

2023-07-19--dreamseeker_10935_nqr4xjMQpC

- cursor icon changes when throw mode is turned on
- turns back to normal when turned off
- ~~coder sprite~~ 
- sprite from top gif made by Atteria @atteria

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!review

**Review by alsoandanswer — COMMENTED** [review]
Oh man, that sprite.

Would it be possible to keep the system cursor while just having a "Throw" underlay?

**Comment by DreamySkrell** [comment]
> Oh man, that sprite.
> 
> Would it be possible to keep the system cursor while just having a "Throw" underlay?

Doesn't look like it would be possible.

It seems that the default value for `client.mouse_pointer_icon` is null (or it's not set, dunno), which means it's using the system cursor. My PR sets that value to a sprite, and then sets it to initial (null/empty) value when throw mode is turned off. If we want it to be consistent, we could provide our own cursor icons to be used always, instead of the system cursor.

Though, the throw mode icon doesn't necessarily have to be a cursor. It could be an animated circle, or whatever other sprite we would like.

**Review by NonQueueingMatt — APPROVED** [review]
Mechanically fine, just get a new sprite from a spriter for the love of God.

**Review by Arrow768 — APPROVED** [review]

**Review by SleepyGemmy — APPROVED** [review]

**Pull request merged**
