### PR TITLE
beer.

### PR DESCRIPTION
**Pull request by Sniblet**
Adds 2 periods to the end of 2 identical item descriptions ingame
.

### CODE REVIEW

**Comment by Sniblet** [comment]
!review required

**Review by KingOfThePing — APPROVED** [review]
groundbreaking beer developments

**Review by SleepyGemmy — APPROVED** [review]

**Comment by WickedCybs** [comment]
Soul

**Review by WickedCybs — APPROVED** [review]

**Review by FluffyGhoster — APPROVED** [review]

**Review by ScheveningenZonn — APPROVED** [review]
beer

**Pull request merged**
