### PR TITLE
Toggle cover lock for Borgs

### PR DESCRIPTION
**Pull request by TheGoret**
Add the ability for stationbounds to unlock themselves their own covers.

### CODE REVIEW

**Comment by TheGoret** [comment]
!review

**Comment by Lemonylight** [comment]
To note is that Research modules already have a dedicted borg cover unlock/lock item.

**Comment by veraknocks** [comment]
too much flexibility to borgs. keeping it restricted access is 👌

**Comment by SonicGotNuked** [comment]
I would make a feedback thread.

**Comment by Sindorman** [comment]
https://forums.aurorastation.org/topic/11937-give-the-ability-for-borgs-to-unlock-their-covers/

**Comment by Sindorman** [comment]
Author decided to discontinue project

**Pull request closed without merging**
