### PR TITLE
Gun Merchant ERT

### PR DESCRIPTION
**Pull request by Geevies**
* Added a gun merchant ERT, an ERT consisting of two gun merchants, who will provide firearms to the crew, up front, or after payment.

### CODE REVIEW

**Comment by Geevies** [comment]
!runtime

**Comment by Geevies** [comment]
well that's a bad omen

**Comment by Geevies** [comment]
!review

**Review by fernerr — COMMENTED** [review]
A cute addition, some ideas to perhaps make it even better:

 - Vary up the visual parts of their outfit, to make them stand out a bit more and giving them a wallet, like the raider one. https://github.com/Aurorastation/Aurora.3/blob/05f51bdc73618ba7c6ea060318802b1c7f6bdd66/code/datums/outfits/outfit_antag.dm#L168
 - The crates the guns spawn in could be /obj/structure/closet/crate/secure/weapon locked to the distress id (access_distress/112) to provide some safety against thieves. Remember to have them locked by default.
 - As they have a lot of crates to move, perhaps giving them a tug might be apt.
 - An additional crate with some shop supplies, paper/pen/clipboard(to make receipts/contracts), labeler to mark guns, a secure briefcase, some steel/plastic/glass to setup tables.

And maybe the welcome message should make it more clear that you're there to make a profit, not risk your lives. To lessen the chance of them just picking out the best guns for themselves and becoming Rambo.
With enough escalation they could help directly ofcourse, but it should never be the first go-to.

**Review by fernerr — APPROVED** [review]

**Review by Arrow768 — CHANGES_REQUESTED** [review]
The current implementation is not suitable to be added as a stand alone ERT.

Most situations that require a ERT have caused or are due to a personell shortage.
Therefore a ERT needs to provide additional warm bodies to combat a specific threat.

**Pull request closed without merging**
