### PR TITLE
Trenchcoat resprite, security jacket resprite and locker content edits 

### PR DESCRIPTION
**Pull request by AmoryBlaine**
- Replaces all of the old trenchcoats, adds new trenchcoats.
- Detective/Forensic trenchcoats look the same as normal trenchcoats, but keep their defense stats
- No more technicolour.

### CODE REVIEW

**Comment by AmoryBlaine** [comment]
!review

**Comment by AmoryBlaine** [comment]
!wip

**Comment by AmoryBlaine** [comment]
!review

**Comment by AmoryBlaine** [comment]
I don't even know what's conflicting

**Comment by KasparoVy** [comment]
Trenchcoat mafia

**Comment by AmoryBlaine** [comment]
I have no idea what the conflict is. I'll redo it all to weed out the conflict.

**Pull request closed without merging**
