### PR TITLE
Replaces the armory ion with a service rifle, and more!

### PR DESCRIPTION
**Pull request by Geevies**
* The armory Ion rifle has been replaced by the NanoTrasen MK43 Service rifle, loaded with rubber rounds, with an extra spare magazine.
* Swapped 7.62mm and 5.56mm round damage values to make more sense. Also reduced the 5.56mm AP damage a minor amount.
* Added rubber 5.56mm rounds, added miniturized haywire 5.56mm rounds.
* Allowed the rubber rounds to be printed in an autolathe, the lethals in a hacked one.
* RnD can produce haywire rounds for the MK43 once they have reached a sufficient tech level.

As for the non-player facing side. I made new sprites for rubber rifle rounds, and emp rifle rounds. Feel free to make use of them in the future, they're pretty generic.

### CODE REVIEW

**Comment by Geevies** [comment]
Just gonna give this some rigorous tests before I slapped the review label on it.

**Comment by ParadoxSpace** [comment]
What is this meant to solve.
It's an ion rifle that you're never sure of what it's loaded with, which is still a one click solution to a whole lot of things, and an ion rifle that can be reloaded on the go and can't be emp'd to disable it. Haywire rounds are stronger than ion shots as is. Literally why.

**Comment by Geevies** [comment]
Updated stuff, should be less angry security haters around.

**Comment by Geevies** [comment]
!review

**Pull request closed without merging**
