### PR TITLE
Nanomachines, Son

### PR DESCRIPTION
**Pull request by Geevies**
* Added a new job, Nanomachine Technician. Its workplace is above the medical lobby, take the stairs. Check the wiki for more info.
* Reduced the size of research slips.
* Moved the raider shuttle landmark that used to be on the interstitial level to the main level, to the west of science.

Inspired by /tg/'s Nanites system, though I didn't look too much into it. Was easier to just make my own version with theirs in mind.
Credits to: Schwann for a lot of the item descriptions, Stryker for the Research Slip's sprite, /tg/ for letting me steal their processor and cloning scanner sprites (thanks Oranges, love you).

The list of changes is way too large to fit into a conventional changelog, so I just made the wiki page for the role as it would appear on the wiki if merged: https://wiki.aurorastation.org/index.php?title=Geeves/Sandbox

If there are any code questions, ask them below and I will try to answer them here. Any non-code questions can be directed to my DMs at Geeves#8863 on discord.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Review by JohnWildkins — CHANGES_REQUESTED** [review]
Technically seems fine, don't see any particular issues when in use.
I do have a few concerns though:
 - I feel like the end-user should have some control or readout at least of what they have inside them. Especially since it's entirely possible to have more deterioration than regen, they should be able to, say, turn off their bio-computer program because they would really rather have their blood come back.
 - Jumping off of that, the scanner should absolutely list which nanomachine programs are loaded.
 - Mapping-wise, I'm not entirely sold on the recovery lounge being deeper in the office, and it definitely needs to be slightly better lit.
 - There should probably be some kind of status message to the player indicating their disorientation and infusion sickness, as it's otherwise not obvious unless you do something that triggers clumsy/disorient (or you notice that you're slower).

My other big concern is that I'm not entirely sure this fits as a mechanic. It feels a little too TG, and also right now as a job the NanoTech doesn't really have a lot to do other than load people up with two of five (seven?) programs. There's definitely room to expand it mechanically so I'm not as worried about that, but I'm just not sure if it's a good fit for Aurora. I'd definitely swing it past the lore purples if you haven't already, since it feels significant enough to hear their say.

**Comment by Geevies** [comment]
- `I feel like the end-user should have some control or readout at least of what they have inside them.`
At the moment of infusion, they get a readout of which programs they have. I don't want to give them the exact values at that moment because keeping it obtuse gives the Technician some breathing room for shenanigans.

- `turn off their bio-computer program because they would really rather have their blood come back.`
I think having this much control over the programs would be way too powerful, since you'd just frontload all the powerful programs and turn them off until you need them, rather than having to carefully select programs that work together from the moment of infusion.

- `Jumping off of that, the scanner should absolutely list which nanomachine programs are loaded.`
I don't want a situation similar to untagged shells where someone with a health scanner can just run around and check everyone and immediately know what they're decked out with. The idea is for the scanner to tell you that someone has or doesn't have it, you yourself need to convince them to come to the chamber so you can get a readout of what they have.

- `but I'm just not sure if it's a good fit for Aurora`
Me neither, but I think it opens a lot of avenues for RP, where you can discuss nanomachines with your technician, do consultations, do post-infusion RP, and maybe even have some traitory things happen up in the workshop. There are plenty of novel experiences to be had, me-thinks. We'll have to testmerge or something to be able to see the scope of changes this addition this will make to the server. My #1 goal during this was to NOT make it like genetics.

- `I'd definitely swing it past the lore purples if you haven't already, since it feels significant enough to hear their say.`
Yeah, already done so.

**Review by JohnWildkins — APPROVED** [review]
Code-wise it seems solid enough, you know my concerns already and it's just an agree-to-disagree situation. Final implementation yes/no is on the m*intainers

**Review by Casper3667 — CHANGES_REQUESTED** [review]
So after doing some testing I have a few requests:
- The current place for the nanomachine tech (between FR & medical intern) could be moved slightly or the color changed as it currently breaks up the department color in the job selection.
- If I open the nanomachine chamber ui before climbing in, I am able to inject myself with nanomachines.
- The question mark out for `flush nanomachine cluster` doesn't give a popup hint unlike the rest.

Smaller requests but not really blocking for my approval:
- Maybe add a light switch to the small hallway outside the nanomachine workshop.
- Make the nanomachine scanner attachable to the belt slot like a health analyzer.
- Possibly add a vending machine to the recovery room so patients can get more food.

**Pull request closed without merging**
