### PR TITLE
Lore Description for Monkey Cubes and Boxes

### PR DESCRIPTION
**Pull request by CyberSpyXD**
As titled. It sets the idea that the cubed animals aren't exactly the same as their regular counterparts. This might be something for lore to decide though, not me. So this PR should probably stay up for a bit.

For those too scared of clicking the "files changed" section. The description is as follows.

"The manufacture of a cubed animal produces subjects that are similar but have marked differences compared to their ordinary cousins. Higher brain functions are all but destroyed and the life expectancy of the cubed animal is greatly reduced, with most expiring only a few days after introduction with water."

### CODE REVIEW

**Comment by CyberSpyXD** [comment]
!review

**Comment by FluffyGhoster** [comment]
I think this description, particularly the last part, would be an additional hinderance to people doing fun experiments that involve monkeys ("Those who use them should always remember that they are still alive and should be treated as humanely as possible.") than there already is

**Comment by CyberSpyXD** [comment]
> I think this description, particularly the last part, would be an additional hinderance to people doing fun experiments that involve monkeys ("Those who use them should always remember that they are still alive and should be treated as humanely as possible.") than there already is

There is already a clause in the animal cruelty charge that using them "appropriately" in research experiments does not constitute animal cruelty. That said, I could insert an additional sentence reminding readers that they're here to die and be used in experiments. 

And regarding the animal cruelty charge, what constitutes "inappropriate" can be argued. Things like straight up torture or just callously flushing your experiments in disposals could be considered it.  I don't see the description as anything other than a restatement of what's expected already, personally.

I am interested in hearing from research players, though. So for anyone else reading, feel free to ping me on discord if you have an opinion on this. Whether it should go in, not go in or be reworded.

**Comment by CyberSpyXD** [comment]
@FluffyGhoster 

Ended up revising this anyway by cutting out the last sentences. You can tell me how the below sounds without the rest.

"The manufacture of a cubed animal produces subjects that are similar but have marked differences compared to their ordinary cousins. Higher brain functions are all but destroyed and the life expectancy of the cubed animal is greatly reduced, with most expiring only a few days after introduction with water."

**Review by FluffyGhoster — APPROVED** [review]
Sounds good to me

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
