### PR TITLE
Shuttle re-haul, escape pods and other stuff

### LINKED ISSUE #5962: TCFL pods are bugged to all heck
TCFL pods are super janky. Apparently as a 'vehicle', you're capable of buckling onto them but you can't unbuckle from it. The buckling feature should be removed.

The single-click feature seems to work OK, but it also bugs out and traps people into the pod if they try to enter a pod with another occupant inside it already.

Furthermore, you can 'throw' objects while contained within the drop-pod, which will inevitably contain the item in a pocket dimension in the void.

They have no eject feature from the outside, which makes matters worse if you're trying to help someone trapped in one without admin assistance.

### PR DESCRIPTION
**Pull request by Sindorman**
In this PR I am updating shuttles on CC, Summary so far:

- Merchant shuttle has been expanded in length in order to make more room for removed racks

- Middle racks have been removed to make 3 tile walkway for customers

- Merchant shuttle now has windows blastdoors to protect from outside intruders and a button on the bridge

- Merchant shuttle has an airlock blastdoor to protect from unwanted customers, and a button on the bridge for it.

- Added an energy net turret and turret control panel to the shuttle, the turret is located in the middle of shuttle and can be accessed with merchant access.

- Fixed access for Merchant Nanomeds.

- Improved design of shuttle to make it look better

- Added O2 cabinet to the airlock of the shuttle.

- Fixed engines on all CC shuttles, some where backwards and off

- Fixes #5962

TODO:

- [x] Finish escape pods retrieval shuttle

- [x] Test escape pods retrieval shuttle and escape pods

- [x] Add 3 more pods to civilian level

- [x] Rework pods mechanics to allow choose destination. Either Shuttle, space or if emagged - mercs place. 

- [x] Rework pods if overloaded - have a chance to crash.

- [ ] Make IC changelog

- [x] Remake Escape shuttles scoop ship into TCFL combat ship and move TCFL to it. (Ferner)

### IC changelog
`It is possible and encouraged (for changes that will have a larger impact on players) to write a ic changelog and add it to the PR description.
This changelog will be pushed to the newscasters when the PR is merged`

### CODE REVIEW

**Comment by Sindorman** [comment]
Reason why CC has this crap ton of diffs is because originally I deleted whole area with escape pods, so MM2 changes all keys.

**Comment by Sindorman** [comment]
Preview of the Merchant shuttle shuttle

**Comment by LordFowl** [comment]
What is an "escape pods retrieval shuttle" and why do we need one?

**Comment by Sindorman** [comment]
Currently escape pods land in asteroid belt where some ships crashed. On Exodus they usually dock to the separate shuttle. So I am adding back that shuttle, but I am making it look better. It will be size of old area.

**Comment by LordFowl** [comment]
I see. I'm rather partial to the current method myself. Escape pods are fringe mechanic and I always thought that them immediately being ejected with pinpoint accuracy to a shuttle was strange, especially considering the remoteness of the station. Hence the common trope of the escape pod waiting in the asteroid field.

**Comment by Sindorman** [comment]
Well my idea is that shuttle picks them up, Hence why in my imolementation they do not but end up inside of the hanger for a ship. This ship will be relatively large and I am still debading if it should have military look or civilian because clearly in case of emergency you would probably want to s need a patrol ship just in case. What do you think?

**Comment by Sindorman** [comment]
Merchant preview

**Comment by Sindorman** [comment]
Escape pods retrieval shuttle preview

**Comment by Sindorman** [comment]
Feedback thread https://forums.aurorastation.org/topic/11177-updating-cc-level-shuttlesmore-info-in-the-topic/

**Comment by Sindorman** [comment]
This will be a base PR for #5779 
So the ship will be extended into base of operations by FL.

**Comment by Sindorman** [comment]
Fuck this merge conflict was huge

**Comment by Sindorman** [comment]
Still working on this, @fernerr Is going to map TCFL base into ship. I will work on finishing pods code mechanics

**Comment by Sindorman** [comment]
TCFL base has been remade into a ship by Ferner with new awesome looking shuttle and new sprites for TCFL equipment and pods
https://i.imgur.com/6r4zWT5.png

**Comment by ben10083** [comment]
I can't really see it well with pic, but is there room for the tcfl commander office? If so, please show a picture.

**Comment by Sindorman** [comment]
TCFL ship base
pTH180t_d

**Comment by fernerr** [comment]
Let me know when and I'll fix the conflicts.

**Pull request closed without merging**
