### PR TITLE
Unapologetic Quartermaster Buffs

### PR DESCRIPTION
**Pull request by ParadoxSpace**
Grants the Quartermaster a single telescopic baton in their locker, to tame the unruly.

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
!review

**Comment by Geevies** [comment]
powercreep

**Comment by skull132** [comment]
uh.

_What._

**Comment by skull132** [comment]
To catch my jaw up from off the ground.

Instead of giving them a flash, which is the nominal weapon of self-defence issued to most _heads of staff._ Let's give them a _lethal_ weapon.

**Comment by ParadoxSpace** [comment]
The flash is of no help to fend off unruly miners, anyone that breaks in the warehouse, carp, spiders, viscerators, etc. Plus, it's more thematic.

**Comment by Kaedwuff** [comment]
> The flash is of no help to fend off unruly miners, anyone that breaks in the warehouse, carp, spiders, viscerators, etc. Plus, it's more thematic. The Captain and HoS have them too.

The quartermaster should be calling security for unruly miners, not using a baton on them. This is silly and dumb.

**Pull request closed without merging**
