### PR TITLE
Renames Emergency Singularity Beacon

### PR DESCRIPTION
**Pull request by furrycactus**
Renames the Emergency Singularity Beacon in Engineering Hard Storage to "Emergency Tesla Beacon", so it's a bit clearer.

### CODE REVIEW

**Comment by furrycactus** [comment]
!review

**Comment by Sindorman** [comment]
Why, it works for both singularity and Tesla?

**Comment by furrycactus** [comment]
It works for both, but the Tesla is generally seen a lot more than the Singularity on the Aurora. The actual item is still called a singularity beacon, I just renamed the instance of the one in storage so people know.

**Comment by furrycactus** [comment]
Closing because I had to shift all my shit to a new computer and I'm bad at git

**Pull request closed without merging**
