### PR TITLE
Added floor lighting fixtures, and tweaked the light sprites

### PR DESCRIPTION
**Pull request by Generalcamo**
This PR replaces most instances of lighting fixtures on railings, with floor lights. These accept the standard light bulbs and light tubes, but are placed into the floor instead of on a wall.

Floor tube fixtures ported from CEV Eris, with modifications from myself to work with Aurora's light fixture code. EDIT: The small floor light sprite was a quick make from atteria, with modifications from myself for in-game usage.
image

This PR now also incorporates the light sprites made by Gem for #15393:
image

In addition, a distinct sprite for the spotlight has been added, which is now buildable:
image

### Asset Licenses
The following assets that **have not** been created by myself are included in this PR:

| Path | Original Author | License |
| --- | --- | --- |
| icons/obj/lights.dmi | SpadesSlick (CEV Eris) | AGPL3 |

### CODE REVIEW

**Comment by Generalcamo** [comment]
!review

**Review by Arrow768 — CHANGES_REQUESTED** [review]
Given that the only option to setting them up (outside mapping; as cargo is not an option for built stuff) they need to be buildable

**Comment by Generalcamo** [comment]
!wip

**Comment by Generalcamo** [comment]
!review

**Review by Arrow768 — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
