### PR TITLE
Removes lethal shotguns ammo from the armory and some modules from the vault

### PR DESCRIPTION
**Pull request by Alberyk**
-removes the shotgun slugs and shells from the armory's lockers:
https://forums.aurorastation.org/viewtopic.php?f=18&t=9567
https://forums.aurorastation.org/viewtopic.php?f=18&t=9527

Removes thermal and combat injector from the vault, replacing them with other modules.

### CODE REVIEW

**Comment by sdtwbaj** [comment]
-1 because of the vault changes, thermals specifically are used as a counter to antags who have thermals as well, or the wizard who has xray options.

tbh the shotgun thing doesn’t matter, just get them printed from cargo or science, but the vault changes seem bad to me.

**Comment by Alberyk** [comment]
Thermals are way too strong, you can get xray vision by other means if that is an issue.

**Comment by SirCatnip** [comment]
Why not just remove the slugs and keep the more balanced buckshot? No memegib capabilities but the shotgun still actually has some use that way.

**Comment by Arrow768** [comment]
As I mentioned above I am not sure just removing the slugs helps.
There are certain wardens that set up a lathe in the armory regularly.
If they need slugs, they can just print them from the lathe.

**Pull request merged**
