### PR TITLE
Adjustments to Wizard Spells

### PR DESCRIPTION
**Pull request by Kaedwuff**
The Flesh to Stone spell has been slightly adjusted:
-It now lasts 90 seconds (1.5 minutes), instead of 480 (8 minutes)  
-To compensate, it has had its range slightly increased. (3 -> 5)

This makes it less of a last ditch defense and more of a general use disable, while also not forcing the player to endure 8 agonizing minutes of effectively being unconscious, possibly to be zapped right back into it the moment they break free if the wizard is still nearby.  Too many people ghost in frustration with the original implementation of this spell. 

Note that is is a full 30 seconds more than the actual cooldown of the spell.  It still remains viable as a re-applicable single target disable, only you can have periods in between statueing them where you can make demands/talk/threats etc.  You know, roleplay, instead of just leaving them helpless as a statue for a geological epoch.  When it lasted 8 minutes it was fairly viable to go around turning the entire security team into statues, or other shitty behavior.

Additionally:
The Baleful Polymorph spell is no longer silently blocked by numerous antag types.  Only wizards remain immune to it, largely because their shit is so intrinsically tied to irreplaceable clothing that it's kind of bullshit to have them all lose it because of one spell.  Changelings, cultists, and vampires, however, have no particular reason they need to be immune to it, and this behavior for the spell often causes confused wizards to be murdered.

Feedback Thread https://forums.aurorastation.org/viewtopic.php?f=18&t=11992

### CODE REVIEW

**Comment by MarinaGryphon** [comment]
Did you make sure that Baleful Polymorph doesn't strip the player of their antag status, unless that's intended?

**Comment by Alberyk** [comment]
What happened was that it would change the character's mind role or something, need to check if it still does.

**Comment by Kaedwuff** [comment]
I was the person who originally reported vampires losing their antag abilities with polymorphed.  I was told it was fixed.

I really hope that the 'fix' wasn't just to make them immune to baleful polymorph.  That's not a fix, it's a hacky solution ;I

**Comment by Arrow768** [comment]
You still need to verify and confirm that antags effected by blaeful polymorph dont loose the status.
Other than that the changes are good.

**Pull request merged**
