### PR TITLE
Lazarus Injector fix

### PR DESCRIPTION
**Pull request by Throwbots**
* Please describe the intent of your changes in a clear fashion.
* Please make sure that, in the case of mapping changes, you include images of these changes in the PR's description.
* Please make sure to mark your PR as wip or review required by making a comment with !wip or !review required

### IC changelog
`It is possible and encouraged (for changes that will have a larger impact on players) to write a ic changelog and add it to the PR description.
This changelog will be pushed to the newscasters when the PR is merged`

### CODE REVIEW

**Comment by Throwbots** [comment]
!review

**Comment by Alberyk** [comment]
What exactly is this fixing?

**Comment by Doxxmedearly** [comment]
> What exactly is this fixing?

When the faction gets set to "neutral", the revived animal will hunt down antags, since their faction is set to something different. It creates antag-sniffing pets. 
It probably should just set faction to initial(faction) though, or null it out, since null faction simple mobs don't attack anything.

**Comment by alsoandanswer** [comment]
making a new PR with an actual changelog.

**Pull request closed without merging**
