### PR TITLE
Renames Medical Resident to Medical Intern, lowers age to 18.

### PR DESCRIPTION
**Pull request by JohnWildkins**
title

https://forums.aurorastation.org/topic/15035-lowering-the-minimum-age-for-medical-resident

### CODE REVIEW

**Comment by JohnWildkins** [comment]
!review

**Review by Alberyk — CHANGES_REQUESTED** [review]
You need to rename the spawn points at the map too, and any loadout item.

**Comment by Parazoid** [comment]
See [this forum post](https://forums.aurorastation.org/topic/15035-lowering-the-minimum-age-for-medical-resident) for the discussion on this.

**Comment by JohnWildkins** [comment]
> 
> 
> You need to rename the spawn points at the map too, and any loadout item.

were it so easy
thankfully vscode comes with a find and replace button so this only took slightly more effort than i originally thought

**Review by Chada-1 — APPROVED** [review]

**Review by Geevies — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
