### PR TITLE
BioChemist Creation (Bring The Hand Sanitizer)

### PR DESCRIPTION
**Pull request by JackBewt**
Merging Virologist and Chemist into a new role: BioChemist. Pharmacist will be kept as alt title. Description is here:
https://forums.aurorastation.org/viewtopic.php?p=91882#p91882

Once code is done, mapping will need to be done to put the virologist equipment into the chemlab. The sublevel is kept for isolation but the equipment itself can be in the same lab.

### CODE REVIEW

**Comment by skull132** [comment]
RIP

**Comment by JackBewt** [comment]
still learning haha >not dev

**Comment by JackBewt** [comment]
Back in dev

**Comment by skull132** [comment]
I mean, this still requires a lot more work. 🤔 

You need to edit the job datum, for one. Delete both the chemist and virologist ones, and create a new merged one.

**Pull request closed without merging**
