### PR TITLE
Animal Cafe Holodeck

### PR DESCRIPTION
**Pull request by Ben10083**
image

### CODE REVIEW

**Comment by Ben10083** [comment]
!review

**Comment by Ben10083** [comment]
image

**Review by Arrow768 — APPROVED** [review]

**Comment by Arrow768** [comment]
To quote a friend of mine: "I have concerns about the sanitary situation in those animal cafes"

But the code is fine.

**Review by FluffyGhoster — APPROVED** [review]
Vol. 1

**Comment by DreamySkrell** [comment]
image
misplaced object

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
.

**Review by DreamySkrell — APPROVED** [review]

**Pull request merged**
