### PR TITLE
Agent whatever soundstuffs

### PR DESCRIPTION
**Pull request by AgentWhatever**
The announcement system just got an upgrade.
Also made the delta siren more concerning.
And made a custom slightly annoying sound for the night mode announcement.

### CODE REVIEW

**Comment by skull132** [comment]
> Also made the delta siren more concerning.

More concerning than an air raid siren. Hmmmmm.

**Comment by AgentWhatever** [comment]
mmmhmmm
https://soundcloud.com/agent-whatever/siren

**Comment by Fire-and-Glory** [comment]
I _like_ it!

I won't when I'm playing and I have to listen to it but whatever

**Comment by AgentWhatever** [comment]
More to come, too

**Pull request merged**
