### PR TITLE
Konyang: Pirates!

### PR DESCRIPTION
**Pull request by RustingWithYou**
Adds two Konyang ruins with ghostroles for pirates - an outpost with a working shuttle and a moonshine still/drug lab in the jungle. Also adds clothes for said pirates.

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Comment by DreamySkrell** [comment]
image
Why not use the wooden doors like they are on most other Konyang maps?

image
Like even in the other map in this PR

**Comment by DreamySkrell** [comment]
image
Move shuttle landmark one tile to the left so it follows the shuttle/dock guidelines

**Comment by DreamySkrell** [comment]
image
give the moonshines some food, tools, maybe like a full stack of steel and wood, so they can do anything other than just brew moonshine
also are these beer kegs? replace with sake and/or mead barrels maybe

**Comment by DreamySkrell** [comment]
image
what does the FIRE thing do? if it is a fire and it burns people, it probably should not be there, idk

**Comment by DreamySkrell** [comment]
image
add this to the point verdant map inside the rocks on the basement/sewers z-level - these pirates won't spawn without point verdant so it's fine
on the CC z-level it won't be unmapped after the arc ends and will just take up space

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
see comments above - sorry, I was supposed to get to this before but I kind of was busy and also forgot :skull:

**Comment by RustingWithYou** [comment]
> image what does the FIRE thing do? if it is a fire and it burns people, it probably should not be there, idk, cause like when the shuttle takes off these fires would stay and it'd just be random files in the middle of the jungle then lol

The fire effect scorches the ground.

**Comment by DreamySkrell** [comment]
image
Revert this accidental moving of this shuttle landmark. It belongs to the Spark.

**Comment by RustingWithYou** [comment]
> image Revert this accidental moving of this shuttle landmark. It belongs to the Spark.
> 
> After this is fixed I will approve

Addressed

**Review by DreamySkrell — APPROVED** [review]

**Pull request merged**
