### PR TITLE
Adhomian Expansion Pack: Body Patterns and Tweaks

### PR DESCRIPTION
**Pull request by WickedCybs**
Adjusts Tajara body patterns and adds in a few new and unused ones that were left in the file. Many of the patterns now colour better, look a bit cleaner and no longer give the species a plantigrade appearance. The native footwear was changed to be in line with the overall Tajara sprite as well

Here are a few example pictures https://imgur.com/a/OqmZxQC.

This is my first PR and I'm reasonably confident about it. Will note that the colorbands pattern hasn't been touched as Unathi use it too. I will likely make an improved version later.

### CODE REVIEW

**Comment by WickedCybs** [comment]
!review

**Review by Geevies — APPROVED** [review]

**Comment by WickedCybs** [comment]
Sorry for the late changes. Realized a few things. It would be in my best interest to label taj specific patterns properly so they don't get mixed up, so I have done this. Other than that, had some redundant patterns bloating the menu, those are now removed.

**Review by Alberyk — APPROVED** [review]

**Comment by WickedCybs** [comment]
This PR was merged recently https://github.com/Aurorastation/Aurora.3/pull/10887 and they modify the same file so I'm going to have to adjust this, believe.

**Comment by WickedCybs** [comment]
!wip

**Comment by WickedCybs** [comment]
https://github.com/Aurorastation/Aurora.3/pull/10908 

Needed to make a new PR entirely.

**Pull request closed without merging**
