### PR TITLE
Constructionmerge

### PR DESCRIPTION
**Pull request by constatinus**
The useless construction borg is removed, and the engineering one gets its experimental welder, drill and the borg factory on malfunction.

### CODE REVIEW

**Comment by constatinus** [comment]
Yeah, but, the end message was that borgs should be highly specialized. I disagree with this idea, but if the dev team think so, rescue and surgery should be kept as they are. However, what about construction? Its a almost totally useless module because it has no wirecutters and something else I think, and the best way to fix this is i think to just remove it and give some of its modules to engineering.

**Comment by Soultheif96** [comment]
Not a coder but I will say that no, we should not remove the role of construction module given that it is much better to use this over the other when it comes to repairs. I suggest that a feedback post would be made before making such decision.

**Comment by constatinus** [comment]
https://forums.aurorastation.org/topic/13008-engiborg-merge-with-construction-and-other/

**Comment by NonQueueingMatt** [comment]
Inactive author, conflicts unsolved.

**Pull request closed without merging**
