### PR TITLE
Tool Resprite

### PR DESCRIPTION
**Pull request by Geevies**
* Ported and tweaked sprites for: Toolbelts, Belt Overlays, Welding Tools, Impact Wrench, Air Analyzer, T-ray Scanner, Flamethrower, Multitool.

Ported (and tweaked) from: https://github.com/BeeStation/BeeStation-Hornet/pull/2487

### Pictures:
Tools:
image

Utility Belt (Alt /w Overlays)
image

Utility Belt
image

Utility Belt (Alt)
image

Utility Belt (CE)
image

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by Geevies** [comment]
The Impact Wrench is flipped like this:
image

**Review by JohnWildkins — APPROVED** [review]
Overall cool and working. However --

I'm not a huge fan of the t-ray scanner + multitool. They kinda just look like the same device, and while I'm sure eventually you'd easily pick them out (one is L-shaped, obviously), without prior knowledge they aren't really distinct.

Also, the impact wrench has the same problem the old sprite had - it's basically impossible to tell the screw / wrench setting apart on this sprite, because it's about 4 px difference.

**Comment by Geevies** [comment]
> 
> I'm not a huge fan of the t-ray scanner + multitool. They kinda just look like the same device, and while I'm sure eventually you'd easily pick them out (one is L-shaped, obviously), without prior knowledge they aren't really distinct.

Not much to be done about it, I think it's just something players will have to get used to. This won't be an issue for new players.

> 
> Also, the impact wrench has the same problem the old sprite had - it's basically impossible to tell the screw / wrench setting apart on this sprite, because it's about 4 px difference.

I might convert it to use the maptext system in the future, simply displaying an S or a W. Out of scope for this PR, tho.

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
