### PR TITLE
Combines bar and kitchen into bistro, moves hydroponics south.

### PR DESCRIPTION
**Pull request by FirinMaLazors**
See changelog.

### CODE REVIEW

**Comment by FirinMaLazors** [comment]
!review

**Comment by FirinMaLazors** [comment]
I messed up the previous PR, so here's another one.

**Review by fernerr — CHANGES_REQUESTED** [review]
Will need time to look over the mapping aspects of this.

**Comment by FirinMaLazors** [comment]
!wip

**Comment by FirinMaLazors** [comment]
!review

**Comment by FirinMaLazors** [comment]
!wip
Need to fix the cameras.

**Comment by FirinMaLazors** [comment]
!review

**Review by fernerr — CHANGES_REQUESTED** [review]
Apologies for the long wait.
I applaud you for your efforts here, I see you've put a lot of passion into this project and I respect that. And it's of good quality for a new mapper, I however have some thoughts on various things.

One big problem, which is a problem with our current bar/kitchen setup too is airzones.
While there's emergency shutters, this whole area in red is still techinically connected.
If one part gets exposed to space, it has to process all of these tiles until finally causing widespread venting to most of the public areas on the station. 
unknown

Now for a more design related criticism
Our current station has a problem with feeling too big, people can feel isolated and it can feel a lot emptier than it should be.

While your design of the kitchen and particularly bar counters does invite interaction on their own, I do feel them being moved so far east of the civilian hallway actually can have the opposite effect, as a lot of traffic passes through it, and the hallway on its own will feel a lot emptier as well.
scrnshot1 - Copy
As for solutions, if you look upon this following image, you have two hallways in close proximity running perpendicular in red, and 'dead space' marked in purple.

My more radical proposal would be to combine these hallways into one, perhaps widened, so to pass through service you would have to pass through the common eating/drinking areas as well. As for the dead spaces, they're dead in the way that their positioning isn't of as much concequence, and they can be moved away, or to another z-level if need be(either up or down, or both, could even make an overlook), as some of them occupy high value land from an interaction point of view.

The back of the kitchen and particularly all of hydroponics shouldn't need to be this isolated when you have some of these front facing areas occupied by private rooms that I feel will already be seldomly used.
scrnshot1
Of course there's a balance to be had being always in view, vs having areas one can go back to to and get a bit of breathing room from the other station crew, but that can be accounted for.

Now for some specific details.
I don't feel airlocks should be placed in a way that they're not leaning against either a wall or glass.
airlock
Two wide tables feel a bit awkward, and chairs shouldn't go under shutters. I'm not sure I like the shutter placement here either, they stand out a lot.
tables
While a shop is a cute idea in theory, I don't see that it'd get a lot of use, like the one we had in the past or the commissary and it's so small already that a crewmember could setup one themself.
shop
Making bees something you can get by default, with their own enclosure feels unneccesary, The station shouldn't be equipped with everything they need at roundstart when they can obtain these items through other means. Same with the extra animal crates, emergency lights and jukebox for example. Things become less special if they're something you get to use/see every single round without fail.
bees and livestock
Again, I admire the effort and passion that has gone into this, you've done great here and I don't want you to feel discouraged, I just feel it could be even better in some ways.
Hit me up on discord, either in #code_dungeon or dms if you have questions or require feedback on something. Any time.

If anyone unrelated to this pr have any thoughts/problems with my review, contact me directly as this wouldn't be the place to argue about that.

**Comment by NonQueueingMatt** [comment]
Map conflicts, unaddressed changes, etc. Reopen when ready.

**Pull request closed without merging**
