### PR TITLE
Major Remap: Science Remap/AI Core Remap

### PR DESCRIPTION
**Pull request by Eyeveri**
Hello! 

With this Remap my intent is simple. I want to make the science department feel more like a department.

Steps taken - 
1. Make science feel more like a department, under guidance of a few science players.
2. Merge xenobiology and xenobotany to have a shared working lab/disection area. The sub-departments themselves will not be shared.
3. Improve the size and layout of the RnD lab.
4. Give the RnD lab a circuitry area.
5. Provide an actual secure area for the RnD servers, rather than a random hallway.
6. Allow for more use of exploratory chemistry for Antagonists by isolating it slightly. 
7. Allow for more use of telescience for antagonists (and regular players) by giving it an isolated but larger workspace.
8. Relocate the AI to a location that minimizes the footprint of the core, but still maintains a level of security.
9. Provide an accessible cyborg charging area/AI Shell spawn that is not connected to the core.

Feedback thread can be found here - https://forums.aurorastation.org/topic/20220-feedback-scienceai-remap-wip/#comment-174311

**Here are all of the completed areas** 

Total AI Core redesign and relocation -
aicore

Cyborg spawn relocation
cyborg

A dissection theater so the xenobiologist/arch/botanist/scientists can teach lab assistants how to operate on monkeys, protos, slimes, etc. Courtesy of 50_Noob
dissection

Exploratory Chemistry
exploratorychem

Hazardous containment for those specimens that aren't holdable in the xenobio lab. Complete with a window to offer some further interaction. The walls are only reinforced which an arm blade can pierce through, as can a hulked vampire, horror form ling, etc. 
Hazardouscontainment

New RnD, RD office, Meeting room, and little break area. Complete with a circuitry suite.
rnd

New Telescience. Blast doors are there for some RP purposes, nothing more really. 
telescience

Went back to the old Equipment room essentially, because telescience was moved back to D2
xenoarch equipment room

"New" xenoarch secure storage. (See above)
xenoarch storage

New Xenobiology layout. I have some content changes coming soon. Courtesy of 50_Noob
xenobio

A new foyer with some lab space to allow for the xenobiologist to work in an area not surrounded by beasts trying to eat them. Courtesy of 50_Noob.
xenobiofoyer

A new layout of Xenobotany to assist with feeling more like a lab than a botanical garden. 
xenobot

Combined Xenological studies foyer so xenobotany and xenobiology can work together a bit more. Open to normal scientists as well
xenologicalstudies

### CODE REVIEW

**Comment by Eyeveri** [comment]
!wip

**Comment by DreamySkrell** [comment]
image
why add floor here (in selected rectangle)?
remove it, there's just heat exchanging pipes and/or open space under it

**Comment by DreamySkrell** [comment]
image

warning stripes should be on the edges of the floor/hull, to be consistent with the rest of the top deck

**Comment by DreamySkrell** [comment]
image
replace one of the borg cryopods whatever thingies with one mech charger
cause as it is, there is no public access mech charger on bottom deck

**Comment by DreamySkrell** [comment]
image

**Comment by DreamySkrell** [comment]
is mapmerge and iconmerge tools to solve conflicts

**Comment by DreamySkrell** [comment]
image
should be dark tile under door here instead of bluegrid

**Comment by DreamySkrell** [comment]
image
remove icon_state from this door

**Comment by DreamySkrell** [comment]
image

top deck floors are inconsistent with mid deck, reach out too far, or too little

top deck floors should be in line with the hull below

**Comment by DreamySkrell** [comment]
image
all these grates should be undamaged

**Comment by DreamySkrell** [comment]
image
disposal pipes are wrong here
and the xenobotany external disposal is not connected to its pipe

disposal pipes currently are layered wrong (under... turfs) and that should be fixed too at some point, not necessarily in this PR

**Comment by DreamySkrell** [comment]
image
image
I think these two cells would look a ton better with added walls there

**Comment by DreamySkrell** [comment]
image
remove icon_state set on this pump

**Comment by DreamySkrell** [comment]
image
floating light bulb here

**Comment by DreamySkrell** [comment]
image
missing light here

**Comment by DreamySkrell** [comment]
image
I think it would be very nice if xenobio had a matching maint exit like xenobot does

**Comment by DreamySkrell** [comment]
image
image
image

wires

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
.

**Comment by Eyeveri** [comment]
All changes have been addressed

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
