### PR TITLE
Fixes Announcer mob nonexistent var, Initialize hint and Destroy return

### PR DESCRIPTION
**Pull request by Amunak**
Didn't quite make it to #10474.

### CODE REVIEW

**Comment by Amunak** [comment]
!bugfix

**Comment by MarinaGryphon** [comment]
PLEASE remove line 21 or it won't compile.

**Comment by Amunak** [comment]
> PLEASE remove line 21 or it won't compile.

It has been removed in this PR

**Comment by Amunak** [comment]
!review

**Review by JohnWildkins — APPROVED** [review]
real compiler hours

**Review by MarinaGryphon — APPROVED** [review]

**Pull request merged**
