### PR TITLE
Replaces EUM with the overhauled Hieroaetheria

### PR DESCRIPTION
**Pull request by sadkermit**
Replaces all things EUM with the overhauled Hieroaetheria.

icons
icons2
icons3
Above accent icons by Caelphon.
icons4
Hieroaetherian accent icon by Hollyhock.

### CODE REVIEW

**Comment by sadkermit** [comment]
!wip pending any final tweaks from lore

**Comment by sadkermit** [comment]
!wip
pending any final tweaks from lore

**Comment by sadkermit** [comment]
!review

**Comment by sadkermit** [comment]
!wip
im silly

**Comment by sadkermit** [comment]
!review

**Comment by FluffyGhoster** [comment]
Diona and Skrell lore will likely need to sign this off first, IRT descriptions, names, aide options and the sort

**Comment by sadkermit** [comment]
this has been discussed by both dionae and skrell lore who have approved all of the changes

**Review by FluffyGhoster — APPROVED** [review]

**Pull request merged**
