### PR TITLE
Detective cleansing

### PR DESCRIPTION
**Pull request by Moonyman**
- Removed all of the noir items from the detective's office and moved them to the loadout:
	Zippo from the starting loadout
	Trenchcoats, fedoras and flask from the locker
	Replaced the TV console camera with a normal console camera
	Replaced the locker sprite with a normal security secure locker sprite

Awaiting sprite for a new detective jacket to compensate for the loss of default pocket space

Relevant suggestion thread: (https://forums.aurorastation.org/viewtopic.php?f=18&t=11152)

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
I don't exactly recall positive feedback on that thread. Why is this PR up?

**Comment by Moonyman** [comment]
You can reread the thread. The link was provided in the PR description

**Comment by ParadoxSpace** [comment]
Your counting is off. Very. Very off.

**Comment by Moonyman** [comment]
the suggestion link is right there

**Comment by ParadoxSpace** [comment]
I'm counting exactly two four, two explicit -1s, and a bunch of 'but why.' Are you reading this correctly?

**Comment by Moonyman** [comment]
- Zundy "Sounds fine to me to be honest" - one for
- yourself "Instead of ham handed, barbaric removal, just put a different set of gear in another locker for a more modern aesthetic" - two for (if you want to retract your statement should've posted. I can't read minds, only text)
- Kaed "I totally support removing them" - three for
- Saudus "If removing the flask etc from standard loadout even marginally improves RP variety, I think it should be done" - four for
- Amory "I'm in favour for moving the style of the trench coats out of being locked to Detective purely to allow everyone to be able to choose them in the loadout" - five for

- UM "-1" - one against

schev and sytic with general statements, not counting them

JB initially opposed, later "I suppose your argument is reasonable when you phrase it in that way, MO_oNyMan." did not count him as either

No idea how you're counting but it doesn't seem to add up on your side

**Comment by ParadoxSpace** [comment]
I doubt your literacy, as I certainly did not support 'Removed all of the detective's noir items:'

**Comment by Moonyman** [comment]
It may come as a surprise at this point but the PR does not "remove all the detective's noir items" but moves them to the loadout. And even if you're changing your mind and declare you're opposed to this that would be 4 for and 2 against

**Comment by ParadoxSpace** [comment]
Except you're removing the trenchcoat.

**Comment by Moonyman** [comment]
there are brown and grey trenchcoats in the loadout already. I'll see if they are different from detective's trenchcoats and if they are - think of a way to get them in.

Sytic posted literally a couple of minutes ago with reasoning "don't remove the coat and fedora pls" which isn't even what the PR does. Stating "you should wear a formal dress on the job" is shockingly enough not disagreeing not sure how anyone could count it as one. If you could cite what exactly in schev's posts indicates he's totally against the suggestion i would strongly urge you to show it to everyone. Otherwise what you're trying to push here is lacking any sort of basis

**Comment by JMJ99** [comment]
nothing is getting removed, you will just need to have it in your loadout. Reread the suggestion

**Comment by LordFowl** [comment]
Suggestion threads are not a democracy, and PRs undergo their own review process. Counting for's and against's is banal, but if you _must_ find some way to spend your time do it elsewhere. The GitHub is for code review primarily.

**Comment by Moonyman** [comment]
@skull132 The sprites are still being made, no idea when they will be ready. And yes, i could put the trenchcoat somewhere in investigation maint. Should they be armored or just mundane clothes with old sprites?

**Comment by skull132** [comment]
@Moonyman If they're in globally accessible maint, unarmored. If they're in a place only sec can get to, armored. Or maybe put the set into the detective's safe (I think he has one?), at which point, also armored.

**Comment by Moonyman** [comment]
d0
d1
d2
d3
dg
dg0
dg1
dg2
dg3
Sprites sprites sprites

**Comment by Moonyman** [comment]
@skull132 the secret room in security maint was built. Both old trenchcoats armored were placed there. New sprite was made and put in place, it's technically playable now if the jacket sprite is fine. Things that still need to be done but are not critical to the functionality (probably will get to doing those some time later in a week or two, getting sick of god damn spriting):
- Hand carry icon for the jacket
- Coathanger icon for the jacket
- Different colour scheme icon variant for the jacket
- Vaurca variant icon for the jacket

**Comment by Arrow768** [comment]
Screenshot of the mapping changes please

**Comment by Moonyman** [comment]
image

**Comment by MarinaGryphon** [comment]
Adding a reference item as the new default undoes any good you may be doing by making noir no longer the default.

**Pull request merged**
