### PR TITLE
Makes the Blueriver ship into a shuttle

### PR DESCRIPTION
**Pull request by RustingWithYou**
Makes the EERV Eureka from the bluespace river away site into a flyable overmap shuttle.

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Comment by FluffyGhoster** [comment]
Merge master to fix the CI

**Review by Eyeveri — CHANGES_REQUESTED** [review]
The only thing I have found that is an issue (for me) is this 
image
re-route the pipes up through the door so they're repairable/accessible in game and you're golden from what I can tell.

**Comment by RustingWithYou** [comment]
> The only thing I have found that is an issue (for me) is this image re-route the pipes up through the door so they're repairable/accessible in game and you're golden from what I can tell.

Rerouted the pipes - some of them are still through walls due to how the shuttle is laid out but the majority of them are accessible now.

**Comment by DreamySkrell** [comment]
image


add to the transit area /obj/effect/step_trigger/teleporter


image


like this

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
as above

**Comment by Eyeveri** [comment]
image
Piping should look more along the lines of this. 

I don't believe the fuel lines interfere with the supply and scrubber lines. 

Also what's this down here? Is this intentionally left open? 
image

**Review by Eyeveri — CHANGES_REQUESTED** [review]
As above

**Comment by NonQueueingMatt** [comment]
stale

**Pull request closed without merging**
