### PR TITLE
Wildlands uniforms

### PR DESCRIPTION
**Pull request by 1Sparky1**
Adds a Wildlands Squadron FR uniform. Alters the Wildlands Security uniform to include PMCG blue accents, rather than black ones.

FR:
wlfr

ISD:
wls

### CODE REVIEW

**Comment by 1Sparky1** [comment]
Before anyone says anything, I see the stray pixel. Gimme a sec.

**Comment by 1Sparky1** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]
Nice work.

**Review by SleepyGemmy — APPROVED** [review]

**Comment by TheDanseMacabre** [comment]
Not sure how much my opinion counts, but I did the original WS uniform and I think the blue edit looks really odd. It clashes with the other colors and imo just looks bad.

**Comment by alsoandanswer** [comment]
> Not sure how much my opinion counts, but I did the original WS uniform and I think the blue edit looks really odd. It clashes with the other colors and imo just looks bad.

The blue highlights are mainly there to signify that they are under PMCG authority. Under any other circumstance, such as in ghost roles and third-party ships, they are not required.

**Comment by Clem-The-Duck** [comment]
> > Not sure how much my opinion counts, but I did the original WS uniform and I think the blue edit looks really odd. It clashes with the other colors and imo just looks bad.
> 
> The blue highlights are mainly there to signify that they are under PMCG authority. Under any other circumstance, such as in ghost roles and third-party ships, they are not required.

It just makes the uniform look worse though. Why cant we just leave it the way it was? Why does the highlight HAVE to be a bright blue that clashes so spectacularly with the colour?

**Review by Generalcamo — APPROVED** [review]

**Review by Generalcamo — APPROVED** [review]
Code is fine, but up to team re: sprite

**Comment by RustingWithYou** [comment]
So, I recently made a PMCG uniform with the highlights, and while I understand people's reasoning for wanting them, I think that in this case the colors just clash extremely badly.

If you want to go ahead with implementing this, I'd recommend keeping the original coloration and just adding PMCG blue accents on the cuffs similar to what I did in #17114, as both of these have way too much pale blue which feels out of place in contrast to the darker and relatively subdued green. Alternatively, you could try using the PMCG logo gold instead, which might fit better with the overall color scheme.

That being said, I think it's worthy of further community and/or maintainer discussion whether or not PMCG highlights should be required for subcontractor uniforms at all, and I think that a feedback thread would be a good idea both for this PR and for the wider concept in general.

**Comment by 1Sparky1** [comment]
Requesting this doesn't get merged rn, pending a decision on [this.](https://forums.aurorastation.org/topic/18920-formalise-pmcg-subcontractor-uniform-standard/)

**Comment by 1Sparky1** [comment]
I am making the decision to close this; Regardless of whether the sprite team supports the change, I'm not interested in making it with so much controversy, nor in retroactively editing the sprite in a way the original artist dislikes.

**Pull request closed without merging**
