### PR TITLE
puts back in rig sounds that aren't copyright

### PR DESCRIPTION
**Pull request by alsoandanswer**
is literally the door bolting sound recycled. so should be no problem.

also puts back in the clown shoes fix.

forgot to ask in the revert PR because am unga.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Review by Geevies — CHANGES_REQUESTED** [review]
The recycled bolt sounds don't sound good, having played some of them. Having them be in airlocks and in much smaller airlocks, with no change in sound, also sounds awful. Try to find another sound.

**Comment by alsoandanswer** [comment]
> 
> 
> The recycled bolt sounds don't sound good, having played some of them. Having them be in airlocks and in much smaller airlocks, with no change in sound, also sounds awful. Try to find another sound.

this isn't a code issue, though.

**Comment by Geevies** [comment]
I know.

**Comment by NonQueueingMatt** [comment]
I have to agree, I'm not keen on using the bolting sounds here

**Review by NonQueueingMatt — APPROVED** [review]

**Review by fernerr — APPROVED** [review]

**Pull request merged**
