### PR TITLE
Adds Class E Kinetic Accelerators to Mining's Secure Lockers

### PR DESCRIPTION
**Pull request by Geevies**
What it says in the title. I tested it out on my server and it felt pretty good, definitely a step up from the pickaxe. If any of the mining players want to give me feedback or more stuff to add, hit me up at Geeves#8863 on discord.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by Sindorman** [comment]
I do not think this is a good idea to put KA into gear. Given that you can buy it. I would replace pickaxe with basic drill

**Comment by Conspiir** [comment]
Technically you can buy basic drills as well. They would be about equal as far as use. 

Though, having a KA actually in the locker makes the KA book in the locker make a lot more sense now that I think about it.

**Comment by Sindorman** [comment]
Having manual for KA in lockers is not reason to put them there. Imho this needs to be changed to basic drills.

Starting with KAs is a big powercreep, as we want progress system. Not a system where you start one tier away from last tier

**Comment by Conspiir** [comment]
Class E is nowhere near last tier. Every piece of it would have to be replaced to get something useful. A Class E is a compact, pump recharging, standard converter with a focusing chip. It hits one rock at a time, costs 200 points in the vendor. A basic drill is very much the same. You would have to replace it to get something useful. It hits one rock at a time, and costs 200 points in the vendor. A drill also has the bonus of being able to dig sand.

That's pretty much what I see as far as equal use. After a first load, a miner is going to research to beg for something useful either way, and the scientists may deign to supply it if they are feeling merciful.

**Comment by Sindorman** [comment]
At that point drill is slightly superior. Why give them drill?

**Comment by sheeplets** [comment]
> At that point drill is slightly superior. Why give them drill?

You shouldn't. The drill is just a pickaxe that takes one longer swing instead of four shorter ones, takes even longer to dig out debris piles, and has a shovel built into it. It's barely an upgrade and more like a crappy Swiss army knife for your belt slot. Mining with either is tedious, mind-numbing, and unenjoyable. It's the reason why the "shovel meta" exists, because for a lot of people standing in one place and digging a 3x3 is more engaging than digging veins. It feels like an actual chore, and it shouldn't. Adding Class E's would be a godsend just for sanity's sake given that using one at the very least feels good for the player. Even then, it's laughably bad compared to anything Research can make and would get trashed as soon as you have enough to upgrade. You said you were concerned about progression? Don't be, there really is none. Your other tool choices just aren't choices. R&D _is_ your progression. You rush a KA or use garbage, fall behind, and have Research players upset at you for not delivering enough on time. The resonators are dangerous and break bones (even through RIGs) if you lag out or mis-step into the field, plasma cutters eat too much Phoron/RIG charge to be reliable, and the diamond pickaxe makes so many waste rocks that it can double the time it takes for your yields to process. The diamond drill, on the other hand, is surprisingly viable but it's a massive waste of materials. The department is just broken in general, both ICly and OOCly. This PR really is only a quality of life change that serves to make it less painful from roundstart, and helps latejoiners make up for lost time. That being said I'd love to see some kind of overhaul in the future to actually fix things.

Sorry to be so long-winded on Git of all places. I don't really know how to condense this better.

**Pull request merged**
