### PR TITLE
Bar / Kitchen Overhaul

### PR DESCRIPTION
**Pull request by Arrow768**
Revives Burgers Bar / Kitchen overhaul #4969

### CODE REVIEW

**Comment by BurgerLUA** [comment]
130k deletions for the main level

:thinking:

**Comment by Arrow768** [comment]
grafik

**Comment by LordFowl** [comment]
Is there any reason the bar backroom uses the secure-hatch style airlock?

**Comment by Arrow768** [comment]
Not really no. What type should be used instead ?

**Comment by LordFowl** [comment]
One would imagine it would just use the standard green civilian airlock.

**Comment by BurgerLUA** [comment]
That's very odd. I recall the hatch being the green one in the first place. Are there any serious map conflicts that caused that or did you try to recreate it?

**Comment by MarinaGryphon** [comment]
Yet another change by Burger to the map that removes/doesn't add a cooking oil tank to the kitchen. When will this madness end?
This is a good change. I especially like the stage in the bar. Maybe we could have a microphone there in the future, or something, so we can have people doing standup in the bar and getting booed.

**Comment by Arrow768** [comment]
The airlock has been changed to a green civilian one.

@MarinaGryphon There is a oiltank in the freezer.
Also the position of the oiltank and the icecart in the above screenshot have been swapped

**Comment by Arrow768** [comment]
A screenshot of the updated version:
grafik

**Comment by BurgerLUA** [comment]
a cig machine seems to be missing

**Comment by Arrow768** [comment]
grafik

**Pull request merged**
