### PR TITLE
Ports 8 hairstyles from Citadel 

### PR DESCRIPTION
**Pull request by listerla**
From https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/6109

To address the elephant in the room; yes, these are reference hairs. I think they should get in anyway because they look good, we don't have enough good hairstyles, and we literally have Vegeta hair titled 'Vegeta' ingame already. I can rename them if you suggest new names, if that is preferred. I just couldn't think of any.

Accidentally deleted the branch. Oopsies! Old PR: https://github.com/Aurorastation/Aurora.3/pull/19204

### CODE REVIEW

**Comment by listerla** [comment]
!review

**Comment by Stev-the-third** [comment]
It somewhat feels as if all five of these hairstyles should just be "Blank 1 - 5", since they're so similar. (Or at least the bottom 4, unsure about the top one.) 
image

**Comment by DreamySkrell** [comment]
As Stev above says. They are pretty similar so yes, they should have a name like "XXX 1", "XXX 2", ... etc. Better for organization.

**Comment by FluffyGhoster** [comment]
Agreed, should name them like `something 1/2/3/4/5 [...]`

**Review by Arrow768 — CHANGES_REQUESTED** [review]
As mentioned by others: the hairstyles are so similar that they should have a similar name to be able to locate them easier

**Comment by listerla** [comment]
> As mentioned by others: the hairstyles are so similar that they should have a similar name to be able to locate them easier

Done. I left the top hair of the 5 with a different name as I feel it differs enough. This could be changed.

**Comment by listerla** [comment]
My Github Desktop was having issues, but I think I've done it now.

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Geevies — APPROVED** [review]

**Pull request merged**
