### PR TITLE
Courier's Helpers mk2

### PR DESCRIPTION
**Pull request by courierbravo**
Adding a series of new shuttles and buildings to use for events. Along with some bugfixes for the mk1. 
Adding some more guidelines as well.

### CODE REVIEW

**Comment by courierbravo** [comment]
!wip

**Comment by DreamySkrell** [comment]
ping me on discord when this is ready for review

**Comment by courierbravo** [comment]
Will do, I can have it done here soon (within a week). I had to take an unscheduled break due to irl issues.

**Comment by courierbravo** [comment]
!review

**Comment by courierbravo** [comment]
Map freeze, consider this on pause for now.

**Comment by courierbravo** [comment]
closing due to merge conflict resolving causing a headache

**Pull request closed without merging**
