### PR TITLE
BayMerge - Up to Master-MAR2016

### PR DESCRIPTION
**Pull request by skull132**
What it says on the tin.

May we all pay the price for our sins.

TODO:
- [x] Resolve all compile errors (about 5 left).
- [x] Resolve all merge conflicts.
- [x] Resolve all TODO-MERGE tags.

### CODE REVIEW

**Comment by skull132** [comment]
Travis hasn't even touched this before the errors get cleared, apparently.

**Comment by NanakoAC** [comment]
How are we supposed to review this? Git can't even load most of the differences or files

**Comment by skull132** [comment]
@NanakoAC Well. You really can't. I'll use the, "Yes, i am madmin and want merge this," button once it's less than stupid.

**Comment by NanakoAC** [comment]
well, looking through the list of included commits as best i can, two things came to mind:

1. Merging construction and engineering borgs. i dont agree with that, could you exclude that?
2. Inspecting the inventories of held animals: sounds like it'd cause problems and is entirely unneccessary

**Comment by skull132** [comment]
Funny story with the merging of construction and engineering borgs. They used to be the same: in old code, there was only an engineering borg.

Whichever borg had the RCD was originally deemed the superior model, with the other one being labelled as completely worthless. I wonder what the public opinion is now a days.

**Pull request merged**
