### PR TITLE
Removed various set backgrounds

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Removed various set backgrounds, that sleeps and can resume at the end of the tick, causing tick overtimes

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!wip

**Comment by FluffyGhoster** [comment]
!review

**Comment by NonQueueingMatt** [comment]
I don't particularly trust removing set background from Life() but we'll see how it goes?

**Review by alsoandanswer — APPROVED** [review]

**Comment by FluffyGhoster** [comment]
> I don't particularly trust removing set background from Life() but we'll see how it goes?

Problem is, with the background option it sprinkles sleeps around the proc by itself, the problem is that you do not control when it sleeps and when it resumes, so it can queue 500 mobs that all wake up at the end of the tick, causing a tick overrun; if this process is too heavy, we can throw some tick checks in, but we likely don't want the engine, unaware of everything, to decide when to wake up the proc; that's my current hypothesis, at least

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
