### PR TITLE
Only syndicate force gloves can strong grab now

### PR DESCRIPTION
**Pull request by Alberyk**
The strong grab feature from the force glove just makes them an insta win in any fight you can reach your target, making any force gloves pretty much bullshit together with the bay grab system. This changes that you can only do the strong grabs with syndicate version of the force gloves

### CODE REVIEW

**Comment by DatBrry** [comment]
i support this, hell it was my idea. where's my credit?

**Comment by Butterrobber202** [comment]
approved

**Comment by skull132** [comment]
Can you think of something else fun and useful they could do? Cuz. plz. I want them to be useful.

**Comment by SonicGotNuked** [comment]
Honestly, yes, the strong grab is really powerful. I don't believe a nerf will do good for them though. They are EXTREMELY easy to get with a couple minutes of RnD with no materials. Just make them require materials and actually stuff instead of 400 units of metal.

**Comment by Alberyk** [comment]
They can still shove people around, skull, and the antag ones have melee combat amplification. Other solution to keep the strong grab would be increase their material costs at rd.

**Comment by skull132** [comment]
Can you maybe make only the combat ones have strong grab? Or maybe nerf it so that you don't go insta-strong-grab, but have to grab, and it halves your grab upgrade time?

**Comment by LordFowl** [comment]
>skull doesn't think melee amplification and flying disarms are useful

**Pull request merged**
