### PR TITLE
No Round End

### PR DESCRIPTION
**Pull request by Arrow768**
No longer displays a message and votes for transfer if the mercs/raiders move their shuttle back to the base.

### CODE REVIEW

**Comment by ThatGuyGW** [comment]
Should this PR also remove the text block that says "Returning to base will end the current mission" when mercs try to return to base?

**Comment by NiftyBaby** [comment]
Will this be for heisters too? Finally, we can regroup for just a little bit without completely borking the round.

**Comment by Arrow768** [comment]
Since it seems there is a bit of a misunderstanding what the base is for:
Returning to the base means that the raiders/mercs are done with what they do as mode_end and post_game will be active and the cleanup of the mode will be executed.

The base is definitly not meant as a "the station cant get to us area".
Therefore the gamemode cleanup will be updated to set all the shuttle computers of the applicable mode into a non-functional state and a despawner (cryo) will be added to the bases which will be unlocked once the post state is entered.

**Comment by Kaedwuff** [comment]
If you're making it so you can't go back and forth between the base anymore, then you need to notate that in the change log. Possibly make sure that it's indicated in game somewhere if it isn't already.

Because people do use it as a rest stop, and it's going to be very frustrating to them if it's suddenly doesn't work as well anymore without any particular notice.

**Comment by Arrow768** [comment]
It is already indicated in the game as you have to press return to home twice to actually return home and confirm that you want to end your mission
However it was not implemented until now. 
(See the removed to do line)

**Pull request merged**
