### PR TITLE
Default self-diagnostics on help intent

### PR DESCRIPTION
**Pull request by VTCobaltblood**
changes: 
  - tweak: "Species that can self-diagnose now do so instantenously and instead of examining themselves for injuries."

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
Explain the need for this change.

**Comment by Sindorman** [comment]
This is a knee-jerking PR. You need to wait 30 months before posting this. Or original author @ParadoxSpace can post any changes in the meantime.

**Comment by LordFowl** [comment]
That policy is for reverts. This is not a revert.

**Comment by Arrow768** [comment]
Technically the knee jerk revert policy only exists for revert PRs.
As this is not a revert PR, the policy does not apply.
However as I want to how that new feature turns out ingame and if there is an actual need to tweak it, this will be marked as DNM for a while

**Pull request closed without merging**
