### PR TITLE
Fixes intern jumpsuits and NT phys and psych jumpsuits.

### LINKED ISSUE #13989: Invisible NT Uniforms
The uniforms of the NT physician, medical intern, and psychiatrist are all invisible on the loadout screen.

invisibleman

### PR DESCRIPTION
**Pull request by RisingValiant**
Makes NT and PMC intern jumpsuits visible when worn.

See Title, Fixes #13989

### CODE REVIEW

**Review by Llywelwyn — APPROVED** [review]

**Comment by RisingValiant** [comment]
!bugfix

**Comment by RisingValiant** [comment]
!review

**Comment by alsoandanswer** [comment]
Changelog, please.

Go to the 'html' file, copy+paste 'example.yml', and edit accordingly. 

Don't forget your username, and change the filename.

**Comment by RisingValiant** [comment]
Done! Sorry I missed it the first time.

**Review by alsoandanswer — APPROVED** [review]

**Review by JohnWildkins — APPROVED** [review]

**Review by mikomyazaki — APPROVED** [review]

**Pull request merged**
