### PR TITLE
RIG Charging

### PR DESCRIPTION
**Pull request by Geevies**
* You can now climb into recharging stations to charge your RIG if you're wearing one on your back.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by NonQueueingMatt** [comment]
This is going to conflict. It's already ported in #10245.

**Review by MarinaGryphon — APPROVED** [review]
> This is going to conflict. It's already ported in #10245. 

That PR has been open for about two months now and still has changes that need to be made. Also, it's a huge PR. I don't see anything wrong with splitting that part out into another PR?

As for the code: `\The [reference]` is always redundant at the start of a string—yes, even if it uses `SPAN_WHATEVER()`. (Likewise, `\the [reference]` is always redundant, but it's not used in this PR.) I don't think it's worth not approving over, but this is something to keep in mind.

**Comment by NonQueueingMatt** [comment]
> 
> 
> > This is going to conflict. It's already ported in #10245.
> 
> That PR has been open for about two months now and still has changes that need to be made. Also, it's a huge PR. I don't see anything wrong with splitting that part out into another PR?
> 
> As for the code: `\The [reference]` is always redundant at the start of a string—yes, even if it uses `SPAN_WHATEVER()`. (Likewise, `\the [reference]` is always redundant, but it's not used in this PR.) I don't think it's worth not approving over, but this is something to keep in mind.

It's literally testmerged

**Comment by Arrow768** [comment]
Closing this in favour of #10245

**Pull request closed without merging**
