### PR TITLE
Enhanced Vision Aug Fix

### LINKED ISSUE #12554: Selecting the Zeng-Hu vision enhanced retinas also gives you the sightlights aug, free of charge

### PR DESCRIPTION
**Pull request by VisVirific**
* Fixes #12554

I kind of doubt the lights were intentional. At least there's no "it's not a bug" in the report.

### CODE REVIEW

**Comment by VisVirific** [comment]
!bugfix

**Comment by VisVirific** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]
My vision is augmented.

**Review by mikomyazaki — CHANGES_REQUESTED** [review]
If you change a proc so all it does is call its parent, you can just completely delete the proc.

**Comment by VisVirific** [comment]
> If you change a proc so all it does is call its parent, you can just completely delete the proc.

I am still terribly afraid of changing/removing code lines, hence I didn't just yeet the entire thing. Although now I yote the entire initialize proc. Hopefully I'll get more used to doing this sorta thing in the future

**Review by mikomyazaki — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
