### PR TITLE
Stuttering markup fix with a side of refactor

### LINKED ISSUE #997: Using italics/bold while stuttering can produce broken HTML
As an example:

`[Common] Kahal Nazkiin stutters, "<i><b-b>M-Med-dical-l. T-T-T-To. F-F-Fuc-ck-king. Ar-rr-rr-rr-rr-rrr-riv-val-ls-s!</i></b-b>"`

### PR DESCRIPTION
**Pull request by JohnWildkins**
Fixes #997.

- Stuttering no longer breaks markup tags or produces broken HTML. Scream in bold while fading out of pain-crit to your hearts content.
- Stuttering is now (vaguely) more realistic, and there are more variations in stuttering. As stuttering condition gets more severe, those affected will start to pause, hold on syllables, or repeat entire words, rather than just stuttering the start of a word.
- oh and also stutter() now actually takes into account the stuttering variable that, up until now, was functionally irrelevant beyond being a binary "are they stuttering" flag

back-end:
- All stuttering is now handled by stutter() (fmr. NewStutter()) - the old stutter proc was wiped off of the earth. All stutter handling is piped through get_stuttered_message().
- stutter() has been refactored to use regex replacement instead of copytext and if chaining, mainly because it makes not deleting markup tags much, much easier. Also it no longer sanitizes input because it's only called from already sanitized functions and all that did was break markup
- In that same vein, because it makes things easier and makes more logical sense, say-processing has been changed slightly:
  - markup tags aren't processed until after stuttering is processed; this is mostly to make ignoring markup easier in the stutter code
  - emotes are now found using restrictive regex now so bold markup won't be confused for emotes and vice versa, regardless of their order in the say processing

### CODE REVIEW

**Comment by JohnWildkins** [comment]
!review

**Comment by JohnWildkins** [comment]
dnm while I refactor some more and delete stutter() off of this earth, while allowing for newstutter() to be more potent

**Comment by SonicGotNuked** [comment]
bless

**Comment by JohnWildkins** [comment]
okay that's more or less done now, OP updated, no need for DNM anymore

**Pull request merged**
