### PR TITLE
The Visible Hand - Golden Deep Merchant Ship

### PR DESCRIPTION
**Pull request by RustingWithYou**
Adds a new ship, belonging to the Golden Deep. The ship has five ghostroles - three non-whitelisted owned synthetics, and two Golden Deep merchants who own the vessel.

The ship can spawn in most of the Coalition and Biesel sectors, as well as Haneunim.

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Comment by DreamySkrell** [comment]
Honestly, the layout is not very optimal:
- Are these merchants supposed to fly out to other places (like Horizon) to trade? That would be very annoying, as the shuttle and the warehouse with crates, are basically on the opposite ends of the ship. That's potentially a lot of crate dragging.
- The single-tile-wide hallway in the middle really does not help with the previous point. It should be two-wide, or ideally three-wide.
- Are other parties (like Horizon's Intrepid) supposed to fly to these merchants to trade? Currently they have only one dock for other shuttles, at the (what I assume is) shop front. So that means at most only one shuttle can dock there... actually, I do not think we have even one third party shuttle that would have a east-west oriented airlock like that. So everyone would have to EVA, which is annoying, especially when dragging cargo. (Even with shuttle rotation added, which I am currently working on, Horizon's shuttles would probably not be rotatable, and could not dock to that east-west dock).
- The shop front itself. It would be also very annoying to trade there, as it very tight and there is no space to present the wares.
- Need more external airlocks, beyond just the dock. I would expect at least one near the engines on both sides.
- Also the warehouse with the crates, is super tight and cramped, with no space to organize things.
- I do not see any actual living spaces? Like yeah these are robots so they don't need beds, but would the two rich merchants not have any personal rooms for themselves, where they store their belongings and valuables? There is that room with wooden floor and carpets, but like, idk, it looks more like a office or something. Especially with the suit cyclers (?) and ATMs inside.
- Is that the merchant computer thingy near the bridge? Did you test if it actually works in game, and does not interfere with the actual merchant's stuff? I would be very surprised if it worked fine just like that.

In general this ship seems very "utilitarian" - I can't find a better word to describe this, but I mean that it only has like, things needed for gameplay, and does not have much "flavor" or decorations. It does not really feel "Golden Deep" to me, cause like if the gold floors were to be replaced with normal steel ones, it'd look like a any normal merchant ship.

If you would be fine with it, I could get the map locally, rearrange the layout to how I could imagine it to look and play better, and we could discuss it on the staffcord or something.

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
see comments above

**Comment by RustingWithYou** [comment]
> Honestly, the layout is not very optimal:
> 
> * Are these merchants supposed to fly out to other places (like Horizon) to trade? That would be very annoying, as the shuttle and the warehouse with crates, are basically on the opposite ends of the ship. That's potentially a lot of crate dragging.
> * The single-tile-wide hallway in the middle really does not help with the previous point. It should be two-wide, or ideally three-wide.
> * Are other parties (like Horizon's Intrepid) supposed to fly to these merchants to trade? Currently they have only one dock for other shuttles, at the (what I assume is) shop front. So that means at most only one shuttle can dock there... actually, I do not think we have even one third party shuttle that would have a east-west oriented airlock like that. So everyone would have to EVA, which is annoying, especially when dragging cargo. (Even with shuttle rotation added, which I am currently working on, Horizon's shuttles would probably not be rotatable, and could not dock to that east-west dock).
> * The shop front itself. It would be also very annoying to trade there, as it very tight and there is no space to present the wares.
> * Need more external airlocks, beyond just the dock. I would expect at least one near the engines on both sides.
> * Also the warehouse with the crates, is super tight and cramped, with no space to organize things.
> * I do not see any actual living spaces? Like yeah these are robots so they don't need beds, but would the two rich merchants not have any personal rooms for themselves, where they store their belongings and valuables? There is that room with wooden floor and carpets, but like, idk, it looks more like a office or something. Especially with the suit cyclers (?) and ATMs inside.
> * Is that the merchant computer thingy near the bridge? Did you test if it actually works in game, and does not interfere with the actual merchant's stuff? I would be very surprised if it worked fine just like that.
> 
> In general this ship seems very "utilitarian" - I can't find a better word to describe this, but I mean that it only has like, things needed for gameplay, and does not have much "flavor" or decorations. It does not really feel "Golden Deep" to me, cause like if the gold floors were to be replaced with normal steel ones, it'd look like a any normal merchant ship.
> 
> If you would be fine with it, I could get the map locally, rearrange the layout to how I could imagine it to look and play better, and we could discuss it on the staffcord or something.

I've made the addition of some airlocks and reshuffled the ship to make the warehouse-shuttle journey easier - as well as expanding the warehouse to give it some more space. I mentioned it in staffcord, but the merchant console should work fine, it's a subtype meant to work with golden deep access - same way that Alb did it with the NKA merchant ship and that I did it with the Guild merchant ship. I'd still appreciate your input on stuff like the docking ports and general aesthetic, however.

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by DreamySkrell** [comment]
> I've made the addition of some airlocks and reshuffled the ship to make the warehouse-shuttle journey easier - as well as expanding the warehouse to give it some more space. I mentioned it in staffcord, but the merchant console should work fine, it's a subtype meant to work with golden deep access - same way that Alb did it with the NKA merchant ship and that I did it with the Guild merchant ship. I'd still appreciate your input on stuff like the docking ports and general aesthetic, however.

@RustingWithYou Sorry, I've been busy lately, and couldn't get to your ship, but I have DMd you on discord with more stuff.

**Review by DreamySkrell — APPROVED** [review]

**Pull request merged**
