### PR TITLE
Fixes Shutter Button in Hangar

### PR DESCRIPTION
**Pull request by SleepyGemmy**
fixes the EVA recharging bay shutter button controlling the research EVA shutter instead.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Comment by SleepyGemmy** [comment]
!bugfix

**Comment by Ben10083** [comment]
While you are there, can you fix the workshop office shutters? No one mapped in a button

**Review by JohnWildkins — APPROVED** [review]

**Comment by SleepyGemmy** [comment]
> While you are there, can you fix the workshop office shutters? No one mapped in a button

yeah sure.

**Pull request merged**
