### PR TITLE
Fix Powernet Cross Between Main Grid & Civillian Surface Subnet

### PR DESCRIPTION
**Pull request by Crosarius**
### IC changelog
Removed wire crossover between the mains powernet and the civilian surface subnet, which was occurring in the emergency service dock.

### CODE REVIEW

**Comment by Crosarius** [comment]
!review

**Comment by Crosarius** [comment]
My first mapping PR. Please be gentle.

**Comment by Crosarius** [comment]
Before: 
image

After: 
image

Also I removed some superfluous mains cabling from the area aft of where these changes were made.

**Comment by Crosarius** [comment]
> Well done on your first mapping pr, I do have something I need to point out though.
> 
> As most maintenance apcs run on the main grid, that pattern should be continued here.
> Which means keeping the mains cable, but that can be done without having the main grid and civilian net cables connecting, like so for example:
> cables

I see! I wasn't aware of the convention. Good catch! Thank you.

**Comment by Crosarius** [comment]
Okay, I did it. I also decided to fix something that I noticed previously, where the cable going from the telecommunications satellite to civilian surface mains just... ends under the airlock. It's not even a knot, it's just loose cable. I connected this up to the civilian surface mains grid. Let me know if that's a problem. I also updated the changelog to reflect this. (You can see where this is with the green arrow.)

image

**Comment by fernerr** [comment]
!bugfix

**Comment by furrycactus** [comment]
Agreed, well done on all this stuff. You also beat me to making the PR after that round as well, so thank you on that front as well.

**Pull request merged**
