### PR TITLE
bandages and heterochomia markings

### PR DESCRIPTION
**Pull request by Greenjoe12345**
Adds a bunch of markings, most are in the form of fake bandages, which could be used if your character was injured previously and you want to show this with bandaged injuries.
Also adds heterochomia as a marking, so you can have two different colored eyes. This has been approved by Unathi, Taj and Shell loredevs (the three nonhuman races it can be put on)

### CODE REVIEW

**Comment by Greenjoe12345** [comment]
!review

**Comment by desvenlafaxine** [comment]
I guess what worries me the most is that heterochromia is a really rare condition that's often abused in a snowflake fashion. I don't want to see half of the station with different colored eyes just because it makes you unique and uwu

**Comment by Greenjoe12345** [comment]
the marking can also be used for less rare things such as a missing or blinded eye

**Review by Casper3667 — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Comment by Arrow768** [comment]
> I guess what worries me the most is that heterochromia is a really rare condition that's often abused in a snowflake fashion. I don't want to see half of the station with different colored eyes just because it makes you unique and uwu

Its gonna be interesting to pull stats about that in a few months

**Pull request merged**
