### PR TITLE
Adds a new cafe garden

### PR DESCRIPTION
**Pull request by TheDocOct**
Adds a new garden area appended to the third-deck cafe for extra RP space, particularly for nature enjoyers. This new garden space features an uncaged Patience. You can now lay in the grass and against the side of the trunk for that casual outdoorsy passive RP.

image

Her former location has been occupied by an additional Stargazer, which has been moved to a public area, also for the promotion of RP. You can now stare at and speculate about the path of the Horizon with your friends while seeing the cool sprites representing our current sector.

image

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
As I said in Gem's PR, which removed around a third of the open space on the map, I am really not a fan of us gradually getting rid of all the verticality the map has. We have gone from there being a large number of open spaces all throughout the ship, to essentially just having the one open section in the central area, and after this PR we'll have a few small spaces, presumably to be removed at a later date. Please don't do this. Verticality is good, we don't need to get rid of it. At this rate all of it'll be gone by August.

**Comment by TheDocOct** [comment]
I don't really see the issue with this specific PR. I specifically retained open spaces within the central stargazer area, and open spaces all around the edge of the garden. Mobility, in terms of what areas are vertically accessible, is effectively unchanged. If you're worried about visibility, the look-down verb is always available.

I also agree that the verticality of the map is a strong advantage, but I legitimately do not think this strongly affects it.

**Comment by TheDocOct** [comment]
!review

**Review by KingOfThePing — APPROVED** [review]

**Comment by alsoandanswer** [comment]
Don't like the additional Stargazer, honestly. Takes away much of the gravitas of the other one. Having two big landmarks in one place means they'll have to wrestle each other for attention, too.

Also, navigation. I know people will get used to the map layout eventually, but it helps to have unique landmarks. It just makes getting around and finding stuff, and it sure did for me when I was starting off on Horizon. Like, I can go "Look for the tree, and your department will be nearby" and "The bridge has a huge star-map, you can't miss it!"

**Comment by TheDocOct** [comment]
Well. That didn't work.

**Pull request closed without merging**
