### PR TITLE
Updates power.dmi to be up to snuff.

### PR DESCRIPTION
**Pull request by alsoandanswer**
Old sprites didn't sit well with me.

Breaker box and SMES taken from Eris, and power generator from /tg/. Power cell rack by yours truly.

Tried to make APCs holograms, but couldn't particularly work because it had to open up for the battery cells.

They aren't particularly stylized, are pretty generic and won't be seen by most players (bar engineering), so I feel these changes won't be too much of a leap.

### CODE REVIEW

**Review by Arrow768 — DISMISSED** [review]
At a first glance it looks like the directional sprites for the APCs are gone.

**Comment by alsoandanswer** [comment]
> At a first glance it looks like the directional sprites for the APCs are gone.

Addressed

**Comment by Greenjoe12345** [comment]
I am not a fan of a number of these. Some are fine, but others, like the APC and the wire sprites, are going backwards to what we've had in the past. The current APC and wire coils are fine as they are, I would think.

**Comment by Arrow768** [comment]
Could you post a screenshot that shows the changed items in the game.
So its possible to see them with a bit more "context".

**Comment by alsoandanswer** [comment]
dreamseeker_YDXV9wNUe9

**Review by NonQueueingMatt — DISMISSED** [review]
Don't change the wire sprites. Rest looks fine? Not a fan of the ports, though.

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Casper3667 — APPROVED** [review]

**Pull request merged**
