### PR TITLE
coalition culture victory: new food and drinks

### PR DESCRIPTION
**Pull request by crunchypretzels**
We're back at it again.

This PR adds:

- Three new alcoholic drinks; the Xanan 2275 and Saint-Jacques Black Label, and a Gadpathurian take on feni derived from [WITHHELD].
- No less than **nine** new canned drinks, ranging from flavors of canned tea to a non-alcoholic variation of kvass, as well as a new cocktail, the Stag Hunt, and a new variant of canned beer for our Coalition loyalists out there.
- A staggering **eighteen** new snack foods, ranging from Xanan papad crackers and foy biscuits to Himean liquorice and Vysokan pemmican bars.
- A hysterical **ten** new dishes for enterprising Xanan chefs, with home favorites like curry or crozets or imported sandwiches and a new little meat pie.
- Two new mugs; Galatea and Xanu Prime.

image

### CODE REVIEW

**Comment by crunchypretzels** [comment]
!wip

**Comment by crunchypretzels** [comment]
!review

**Comment by FluffyGhoster** [comment]
```
Error: SSGarbage HARDDEL: Beginning search for references to a /obj/item/reagent_containers/food/drinks/cans/beer/earthmover.
Error: SSGarbage HARDDEL: Refcount for /obj/item/reagent_containers/food/drinks/cans/beer/earthmover: 7
Error: SSGarbage HARDDEL: Finished searching globals
Error: SSGarbage HARDDEL: Finished searching native globals
Error: SSGarbage HARDDEL: Found /obj/item/reagent_containers/food/drinks/cans/beer/earthmover [0x2002a1a] in list World -> /obj/item/storage/box/fancy/yoke/earthmover [0x2002a19] -> cans (list).
Error: SSGarbage HARDDEL: Finished searching atoms
Error: SSGarbage HARDDEL: Found /obj/item/reagent_containers/food/drinks/cans/beer/earthmover [0x2002a1a] in list Datums -> /datum/controller/subsystem/garbage [0x210001ab] -> queues (list) -> /list (list) -> /list (list).
Error: SSGarbage HARDDEL: Finished searching datums
Error: SSGarbage HARDDEL: Finished searching clients
Error: SSGarbage HARDDEL: Completed search for references to a /obj/item/reagent_containers/food/drinks/cans/beer/earthmover.
[world_runtime.log]: WORLD: ## TESTING: GC: -- [0x2002a1a] | /obj/item/reagent_containers/food/drinks/cans/beer/earthmover was unable to be GC'd -- (ref count of 3)
WORLD: ## TESTING: GC: -- [0x2002a1a] | /obj/item/reagent_containers/food/drinks/cans/beer/earthmover was unable to be GC'd -- (ref count of 3)
```
This has to be fixed before it can be merged

**Comment by crunchypretzels** [comment]
>this may fix the issue
Untitled

**Comment by DreamySkrell** [comment]
For the future, please keep mapping changes out of big PRs like this one. Add the recipes and vendor first, and then add the vendor to maps in another PR.

The changelog does not mention that the vendor was added to horizon and the coc ranger ship.

**Review by DreamySkrell — APPROVED** [review]

**Pull request closed without merging**
