### PR TITLE
Main Elevator Escape Hatch

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR adds a emergency escape hatch to the main elevator on deck 1, to allow people to avoid being crushed.
engineers, atmos. technicians, and first responders have access. the inside is one-way access.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Review by Arrow768 — APPROVED** [review]

**Comment by Arrow768** [comment]
Should probably add one to the rnd elevator too while you are are at it

**Comment by SleepyGemmy** [comment]
good idea.

**Comment by SleepyGemmy** [comment]
not needed, there's climbable railings behind it.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
