### PR TITLE
Unapologetic CCIA Buffs

### PR DESCRIPTION
**Pull request by TheDocOct**
Creates a new public conference room on the public surface level, featuring a public-access door with a bridge-access button for bolting the room down from the inside only, allowing heads of staff and CCIA to conduct private meetings while not allowing crew or antagonists that have not gotten to the point of gaining command access from abusing the area as an unintended holdout.

In order to place the conference room without encroaching on the merchant shuttle, the surface level atmospherics equipment was slightly shrunk and moved into the surface engineering storage room, which was rearranged to accommodate this.

The surface command "Head of Staff Preparation" room was renamed, rearranged, recolored, and slightly shrunk to be "Command Dock Monitoring".

Minor change made to the roof of the station to accommodate new conference room.

1wsqvny
shupxv2

Done largely at the behest of CCIA input, but keeping DNM until more feedback has been gained.

Also includes a fix for wiring at the roof solars, because I couldn't figure out how to separate it from this PR and it's not important enough to bother figuring it out.

### CODE REVIEW

**Comment by ben10083** [comment]
The conference room having maint access could lead to some trouble, maybe shrink the conference room to be much smaller, like maybe have main table to 2x2 with chairs surrounding it. After all if heads of staff want to have a meeting they have a meeting room across from.captain's office.

**Comment by TheDocOct** [comment]
Changed the conference room's windows to be tinted. Demonstrated in attached video, in addition to clarification on bolting- written, I'll explain: both the entrance door and maintenance door are bolted by the bolt door, and the bolt button is restricted to bridge access, NOT the entrance door, which is public access.

lxzsr20 - imgur

**Comment by TheDocOct** [comment]
Feedback from the majority of the active CCIA team and some other various community members was positive with some requests for some minor changes, some of which were worked in- overall, the team seems pretty happy with it, so I'm good moving it forward.

**Comment by TheDocOct** [comment]
!wip

**Comment by TheDocOct** [comment]
!review

**Pull request merged**
