### PR TITLE
New Atmospherics Sprites

### PR DESCRIPTION
**Pull request by Geevies**
* Updated the vent pump and vent scrubber sprites.

### CODE REVIEW

**Comment by Geevies** [comment]
IconDiffBott has a white pixel in the top left corner, dunno why. It's a bug with the bot.

**Comment by Geevies** [comment]
!review

**Comment by alsoandanswer** [comment]
shouldn't map_scrubber_on be moving?

**Comment by fernerr** [comment]
map_scrubber_on is only seen in the map editor.

**Comment by alsoandanswer** [comment]
the last frame of the vent_scrubber_on sprite should for the map_scrubber on sprite 

as of now it's literally one blue pixel

**Comment by fernerr** [comment]
Not sure how I feel about these replacements, Here's a comparison though.
6iwfTW0EpT
S46QDeylR6

**Comment by alsoandanswer** [comment]
Yeah I feel old ones are better.

**Comment by Doxxmedearly** [comment]
Scrubbers having an on animation, while super cool looking, are pretty distracting. 
Vents look good tho.
Sizes are pretty nifty.

**Comment by Geevies** [comment]
Sprites have been tweaked following feedback.

**Comment by Doxxmedearly** [comment]
Looks good, but don't most sprite changes require a feedback thread?

**Comment by skull132** [comment]
> 
> 
> Looks good, but don't most sprite changes require a feedback thread?

The hell they do.

Also, personally, I like the current vents more, but the new scrubbers more.

**Comment by alsoandanswer** [comment]
Personally I don't think these sprites are a step-up in any way, they're practically on-par.

I don't see any reason to add these for other than change for changes sake.

**Comment by NonQueueingMatt** [comment]
I like both of these more than the current ones.

**Pull request closed without merging**
