### PR TITLE
HoS voidsuit swapout

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
Maybe a bit of a stretch, but worth a try. This replaces the ugly HoS voidsuit with a hazard hardsuit. I think it's a good idea, and the hazard hardsuit really isn't that strong at all.

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Comment by KingOfThePing** [comment]
Is the sprite a placeholder or is this intended to merge as is?

**Comment by SleepyGemmy** [comment]
if you're going to replace the HoS voidsuit with a hardsuit, please create a variant of the hardsuit with colours that identify it as the HoS' hardsuit.

**Comment by NonQueueingMatt** [comment]
Don't think it should be the combat hardsuit straight up. It should be visually identifiable as a security (and, more specifically, the head of security's) hardsuit.

**Pull request closed without merging**
