### PR TITLE
Lawgiver rename

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
The lawgiver has been renamed to be the "advanced combi-pistol", an SCC weapon.

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Comment by GMR25** [comment]
Forgive me if I'm wrong, but doesn't this thing spawn in the Eridani group crate for Mercenaries? Wouldn't it be more suited to be reflavoured to an Eridani design?

**Comment by SleepyGemmy** [comment]
@GMR25 EPMC is part of PMCG which is part of SCC, its not outlandish that the eridani crates would contain a SCC weapon.

**Review by SleepyGemmy — APPROVED** [review]

**Comment by Butterrobber202** [comment]
danse removing all references and cool names...

**Comment by TheDanseMacabre** [comment]
> Forgive me if I'm wrong, but doesn't this thing spawn in the Eridani group crate for Mercenaries? Wouldn't it be more suited to be reflavoured to an Eridani design?

I don't think it does. If it does, that's a ludicrously strong weapon to have spawn in a merc weapon crate.

**Comment by TheTrollDoctor** [comment]
This will also need coordination with the Tajaran lore team, the NKA has the Lawgiver (or a derivative thereof) as one of its notable national weapons.

**Comment by TheDanseMacabre** [comment]
> This will also need coordination with the Tajaran lore team, the NKA has the Lawgiver (or a derivative thereof) as one of its notable national weapons.

They're aware of it.

**Review by Alberyk — APPROVED** [review]

**Review by JohnWildkins — APPROVED** [review]
I don't want to know why this has the Mapping: Aurora tag

**Pull request merged**
