### PR TITLE
Lets the Representative access the command break room.

### PR DESCRIPTION
**Pull request by FirinMaLazors**
Per Nodders on the Discord.

### CODE REVIEW

**Comment by fernerr** [comment]
I wouldn't be against giving both the consular and rep access to the command break room and the bridge conference room. These rooms are barely used as it is and makes sense thematically, as their positions are treated to a bit of opulence already.

**Comment by FirinMaLazors** [comment]
!review

**Comment by FirinMaLazors** [comment]
Also per Connor1 on the discord.

**Review by Arrow768 — APPROVED** [review]
Technically this PR is alright.

However the limited access to the command facilities was/is intentional.
They only have access to the command areas, because their shuttle docks at the command dock.

Will therefore be discussed between the maintainers if that is wanted.

**Comment by FirinMaLazors** [comment]
Works for me.  Let me know if/when you want me to give it a go, or if yall want to take it over.  Consular access may need to be added in addition to the Liaison's, if it's going to be added.

**Comment by Arrow768** [comment]
Breakroom / Conference Room Access for both is good to go.
The rest (shuttle cockpit, bunker, command maint, ...) is a nogo.

**Review by fernerr — CHANGES_REQUESTED** [review]
Remove acccess where needed, and add consular access to the conference room and breakroom and it'll be good to go.

**Comment by NonQueueingMatt** [comment]
Stale.

**Pull request closed without merging**
