### PR TITLE
Allows wintercoats to be hanged

### PR DESCRIPTION
**Pull request by flpfs**
Resolves issue #9718

### CODE REVIEW

**Comment by cumivo** [comment]
!bugfix

**Comment by cumivo** [comment]
!review

**Comment by cumivo** [comment]
Alright sprites need to be added too so !wip

**Review by skull132 — APPROVED** [review]

**Comment by skull132** [comment]
OKAY APPARENTLY I'M A DUMBASS.

**Comment by skull132** [comment]
Just reopen this or create a new PR when you're done. Apologies for reading the tags properly.

**Pull request merged**
