### PR TITLE
Removes Burger

### PR DESCRIPTION
**Pull request by MarinaGryphon**
* Fixes cocktails being extremely, lethally hot (issue #5702)
* Fixes splashing reagent containers on chem heaters

### CODE REVIEW

**Comment by MarinaGryphon** [comment]
!bugfix

**Comment by VTCobaltblood** [comment]
Does this, by any chance, fix ice instantly melting?

**Comment by MarinaGryphon** [comment]
> Does this, by any chance, fix ice instantly melting?

It does now. That wasn't a bug, but it's changed to take about 116 seconds to completely melt (or freeze).

**Comment by MarinaGryphon** [comment]
!review

**Comment by skull132** [comment]
@MarinaGryphon can you tell me the difference between specific heat and fallback specific heat real quick?

**Comment by MarinaGryphon** [comment]
> @MarinaGryphon can you tell me the difference between specific heat and fallback specific heat real quick?

@skull132 Specific heat is the final specific heat value for that reagent and subtypes. Fallback specific heat is only used if something doesn't have a recipe to determine it from, and so it doesn't mess with subtypes that do have recipes.
The only reagent with explicitly defined specific heat (not fallback specific heat) should be water, as the water to ice and ice to water recipes caused an infinite loop.

**Pull request merged**
