### PR TITLE
Bare-clawed Unathi footstep sounds.

### PR DESCRIPTION
**Pull request by Crosarius**
This PR will add barefoot walking sounds for Unathi. Their claws will make a clicky sound when they walk around. The sound files are lightweight, and should be less than 75 kilobytes total.

The claw clicks are bespoke, sourced from a family dog and edited for clarity and noise reduction.
The footstep noises beneath are from walk_indoor_barefoot.mp3 by dragonmin -- https://freesound.org/s/554592/ -- License: Creative Commons 0

https://github.com/Aurorastation/Aurora.3/assets/30341877/322a9767-ba2c-41df-82ae-21a7f80816ac

### CODE REVIEW

**Comment by Crosarius** [comment]
!wip
I want to get feedback from people on whether this is too stupid/annoying or not.

**Comment by Crosarius** [comment]
Greatly improved the sound effect based on feedback I've gotten from people I've shown this to. I have added some barefeet footstep sounds sourced from walk_indoor_barefoot.mp3 by dragonmin -- https://freesound.org/s/554592/ -- License: Creative Commons 0
The latest video is here: 
https://github.com/Aurorastation/Aurora.3/assets/30341877/c34814cc-716c-42c0-8c49-1df2aa4cf36c

**Comment by Crosarius** [comment]
https://github.com/Aurorastation/Aurora.3/assets/30341877/fcaac823-21c9-4d2a-9618-61f680c78049

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by Crosarius** [comment]
!review

**Review by Arrow768 — APPROVED** [review]

**Review by FluffyGhoster — APPROVED** [review]

**Pull request merged**
