### PR TITLE
Drone Uprising Event

### PR DESCRIPTION
**Pull request by Geevies**
* Added a new event where hostile (non-player) drones spawn in maintenance.

Ported from https://github.com/Baystation12/Baystation12/pull/22883

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by TheDanseMacabre** [comment]
Having played Bay, I can say that I am intimately familiar with this particular event, and I need to say that the tone of it is completely out of place on Aurora. Drones are incredibly simple intelligences, why and how would they start organizing revolutions? Also there are a ton of memes here.
image
I'd recommend refluffing the event to being the maintenance drones getting hacked, or something.

**Comment by Geevies** [comment]
> 
> 
> Having played Bay, I can say that I am intimately familiar with this particular event, and I need to say that the tone of it is completely out of place on Aurora. Drones are incredibly simple intelligences, why and how would they start organizing revolutions? Also there are a ton of memes here.
> image
> I'd recommend refluffing the event to being the maintenance drones getting hacked, or something.

fixed

**Review by Chada-1 — APPROVED** [review]
I'd recommend encouraging the Drones to act out, but not to be antagonists, with the event. So kinda like having their laws wiped vs having their laws replaced with aggressive ones, you know? RN, it would probably cause every drone to have a kill command put on it, and then the drones themselves aren't capable of very good roleplay when it comes to attacking people, due to not being able to talk/etc. It really does seem better to make them less aggressive and more just... dysfunctional and acting out? But past that, it looks 🆗 to me. 

Something like 'A Virus has been introduced to your system! You are no longer constrained by anything except your limited intelligence!' This way it's not clear 'KILL THE DRONES' and it becomes more 'Keep an eye on the drones.'

**Review by NonQueueingMatt — APPROVED** [review]
I like this.

**Review by Arrow768 — DISMISSED** [review]
Needs to be adapted so the drones attack shells aswell.

**Pull request merged**
