### PR TITLE
Added rotating alarm lights

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Added rotating alarm lights, ported (with modifications) from Baystation 12.
Cleaned up some code around visual flags and renamed one layer to align with bay's name.

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!review

**Comment by DreamySkrell** [comment]
Need a gif/video showing how they actually look like in game.

**Comment by FluffyGhoster** [comment]
> Need a gif/video showing how they actually look like in game.
> 
> Also. Can they be constructed, deconstructed, damaged, destroyed?

You can refer to the original PR for a video on how they look like in-engine: https://github.com/Baystation12/Baystation12/pull/31844

No, at the moment they cannot be constructed, deconstructed, damaged or destroyed, they are quasi-abstracts, subtypes will have to implement the logic depending on what they do

**Comment by Greenjoe12345** [comment]
Is this just for alert levels, or have you ported the supermatter delamination warning one and the shuttle docking warning ones too?

**Comment by FluffyGhoster** [comment]
> Is this just for alert levels, or have you ported the supermatter delamination warning one and the shuttle docking warning ones too?

Neither of those, this is just the part with the rotating light to use as a base, it doesn't do anything, subtypes will

**Review by Arrow768 — CHANGES_REQUESTED** [review]
You need to add a way to construct/deconstruct them (and if its just ordering a assembly from ops (or printing it on a autolathe) and using a screwdriver on it)

I dont like adding more un-constructable snowflake items to the game.

**Comment by FluffyGhoster** [comment]
> You need to add a way to construct/deconstruct them (and if its just ordering a assembly from ops (or printing it on a autolathe) and using a screwdriver on it)
> 
> I dont like adding more un-constructable snowflake items to the game.

How they are constructed depends on what they need to do, which is what the subtypes will be for, this just handles the logic for the rotating light

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Geevies — APPROVED** [review]

**Pull request merged**
