### PR TITLE
Removes negative slowdown from the loadout off-worlder RIG

### PR DESCRIPTION
**Pull request by Jaraci**
See title. This is an oversight introduced by #13038, I think.

### CODE REVIEW

**Comment by Jaraci** [comment]
!bugfix

**Review by JohnWildkins — APPROVED** [review]
nerfing humans? smh, taj mains these days...

**Review by KingOfThePing — APPROVED** [review]

**Comment by Dreamykass** [comment]
I do not like this. And I think this should be a matter of balance now, and not a bugfix, as it's been a long while like that from the looks of it.

I've been playing my hangar tech offworlder in the past 2 weeks, more than 1 round a day. I very much enjoy the speed boost that the ESS (currently) provides, and I think it's a nice bit of utility that you get, in exchange for taking up the whole backpack slot. It's good balance, I think. I'd be pretty sad to see this go.

Especially so if #13427 was also to be merged. Offworlders get some serious debuffs compared to normal humans, and get only some minimal and very situational buffs. Speed isn't really useful for combat or chasing antags, as offworlders are heavily discouraged from these anyways.

**Review by NonQueueingMatt — APPROVED** [review]
Items that give you a -1 slowdown from the loadout should not really exist, plus this was unintended.

**Pull request merged**
