### PR TITLE
Updates to Atmos machinery for new Gasses 2.0

### PR DESCRIPTION
**Pull request by furrycactus**
It's #17702. Provided everything works, can this be made to bypass the waiting period?

- [x] Fix the exoplanet_testing issue.

### CODE REVIEW

**Comment by furrycactus** [comment]
I'm going feral.

**Comment by furrycactus** [comment]
!wip

**Comment by DreamySkrell** [comment]
image
I really do not like how this removes some of the bottom deck maintenance. It cuts off access to that airlock behind the AI core to non-engineers, and also the ladder is supposed to be general maintenance access, but now it leads into an atmos-only room.

**Comment by DreamySkrell** [comment]
image
Isn't a disposals pipe missing here?

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
See previous comments. At the very least that disposals pipe should be fixed (unless it's just mapdiffbot2 not rendering it), and that public access ladder should not lead into an atmos-access room.

**Comment by furrycactus** [comment]
Removed the map changes. Not sure why the tags for Aurora and Runtime mapping are still there. Also seems that the sleeping_agent/nitrous_oxide change was messing with the exoplanet stuff. Not sure how to fix that so I just reverted it.

**Comment by furrycactus** [comment]
!review

**Comment by furrycactus** [comment]
Wait I forgot to re-add the canister sprites. Hold on.

**Review by DreamySkrell — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
