### PR TITLE
Fixes medal onmobs

### LINKED ISSUE #8437: Medal of Captaincy Sprite borked
I do this for Wezzy to fix this Mezzy.
The medal is a yellow square visible from all sides. Somewhat borked.

### PR DESCRIPTION
**Pull request by alsoandanswer**
Fixes #8437

probably

I think it's probably a problem with the preview thing but doesn't hurt right

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by NonQueueingMatt** [comment]
You didn't change the icon state for the whiteheart medal.

**Comment by alsoandanswer** [comment]
> You didn't change the icon state for the whiteheart medal.

Whoops typo ill fix that

**Comment by alsoandanswer** [comment]
!review

**Pull request merged**
