### PR TITLE
Xenobiology serum sprite fixes/changes

### PR DESCRIPTION
**Pull request by listerla**
Literally just made each one use a different bottle sprite, and directed them to the proper files so they're not invisible.

### CODE REVIEW

**Comment by listerla** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]

**Comment by listerla** [comment]
!bugfix

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
make sure they're contained sprites, and set item_state = "bottle"

**Comment by listerla** [comment]
these are just using pre-existing sprites from here: https://github.com/Aurorastation/Aurora.3/pull/17231

will set item_state

**Comment by alsoandanswer** [comment]
> these are just using pre-existing sprites from here: #17231
> 
> will set item_state

oh, i mean set contained_sprites = TRUE, to make sure the game knows that the item_state is in the same file and display the inhands properly

**Comment by listerla** [comment]
oh, ty! i didnt know that was a thing

**Review by alsoandanswer — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
