### PR TITLE
Spawning as someone who needs wheelchairs on the Odin spawns you in a wheelchair

### LINKED ISSUE #9608: Leg Amputation Spawn Bug
Round ID: b8t-a4DV
Spoke with: Alberyk once and Yonnimer twice.

I created a new character and decided she would have one fully amputated leg, one partially amputated. After looking through the loadout selector for a wheelchair and finding none, I assumed that when I loaded into the game I would automatically be spawned in with one.

I spawned on the arrival shuttle, and my character was standing. . . . With no legs. That caused a great fuss in my chatlog of "she screams, she collapses, she screams, she collapses." I got that to stop by making her rest, then contacted AdminHelp. 
Alberyk spawned in a wheelchair, which I was able to get the character buckled into and roll onto the transport to the station. They said that it may be because the character still had a partial leg and that may be the problem of the spawn. Upon arrival to the station however, I found my character could only hold items in her right hand. As soon as I clicked the left hand, the chatlog said "She cannot do that in this state." This would've been fine as I could make due with one usable hand... but the game also would not let me interact with the elevator button.

Second AdminHelp. Yonnimer was able to teleport the character to cryo so I could respawn.
I immediately fixed the legs to both be amputated, hoping this would fix the problem.
Nope. Same thing. No wheelchair, standing on legs that don't exist, screaming and collapsing. Yadda yadda.

Third AdminHelp. Yonnimer teleported me again and suggested I make the bug report after I cryo'd the character.

---
Seeing as the character creator gives players an option to make characters have amputated extremities, I would say the best fix would be to auto-spawn a wheelchair for those. I don't know how that would be implemented or if I can be, but the second solution I believe would be to add a wheelchair to the loadout options.

Thank you for your time. Hope this is a easy, fixable issue. -Quinn

---
EDIT: Also mentioned in chat  #9423

### PR DESCRIPTION
**Pull request by Hockaa**
Fixes #9608 (and #9423 by technicality, since it was because spawning on the Odin didn't trigger the H.equip_wheelchair() proc until you walked through an AutoDrobe rather than just being an issue with only one leg being amputated.)

### CODE REVIEW

**Comment by Hockaa** [comment]
!review

**Comment by Hockaa** [comment]
!bugfix

**Comment by mikomyazaki** [comment]
Does this not spawn an extra wheelchair when they go over the autodrobe?

**Comment by Hockaa** [comment]
> Does this not spawn an extra wheelchair when they go over the autodrobe?

When I tested it, it didn't. Though I should've checked to see if it just had me riding two wheelchairs at the same time, (Not sure if that's possible, but better safe than sorry) so I'll go check it now.

**Comment by Hockaa** [comment]
Just checked it - only spawns one wheelchair from what I can see and I'm going to be honest, I have no idea what stops it from spawning a duplicate, which makes me feel like I should add like a boolean check or something on the equip_wheelchair proc, something like:

```
if(!SpawnedInChair)
    [the code lines that creates and buckles the chair]
    SpawnedInChar = TRUE
```

Does this sound like a good idea?

**Comment by alsoandanswer** [comment]
If I were to harbour a guess, it would be that there's already a check in the spawn wheelchair proc.

Other than that, doesn't spawn cause user's already in the wheelchair. (ala user.put_in_hands, if there's something in your hands, dont put anything new there)

**Comment by Hockaa** [comment]
> Wheelchairs make stance_damage zero, due to handle_stance().

There's the ticket - probably should've checked that on other files when I noticed it in the proc. Lesson learned for next time - thanks guys.

**Pull request merged**
