### PR TITLE
Lighter tweaks

### PR DESCRIPTION
**Pull request by shedya**
Zippo messages are no longer red. For those who want to opt out of the zippo flavor text spam, but still have a lighter at loadout, the cheap lighter has been added in there. The zippo's description has been tweaked so that it's slightly more obvious that it's going to spam flavor messages.

### CODE REVIEW

**Comment by BurgerLUA** [comment]
!review

**Comment by shedya** [comment]
Why does this require feedback? This is an extremely minor change

**Comment by BurgerLUA** [comment]
It doesn't really. Red text is generally reserved for warning/danger text, which indicates that something bad happens.

**Comment by shedya** [comment]
Well, it wasn't the /warning/ red, it was a weird light-orange color called "rose", VERY similar to red. Still extremely distracting, especially at the bar.

**Comment by shedya** [comment]
!review

**Pull request merged**
