### PR TITLE
NT Muffin Sprite Fix

### LINKED ISSUE #17800: [Bug]: NT Muffin has no sprite
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

image

No sprite assigned to the NtMuffin  /obj/item/reagent_containers/food/snacks/nt_muffin

### How to reproduce

1: Make muffin
2: No Sprite

### Round ID

All of them

### Staff ckey

Alberyk

### PR DESCRIPTION
**Pull request by Acetrea**
Fixes #17800

### CODE REVIEW

**Comment by Acetrea** [comment]
!bugfix

**Comment by Acetrea** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]

**Review by DreamySkrell — APPROVED** [review]

**Review by FluffyGhoster — APPROVED** [review]

**Comment by DreamySkrell** [comment]
Fix this:

Error OD0404 at code/modules/cargo/bounties/chef.dm:141:8: Type /obj/item/reagent_containers/food/snacks/nt_muffin does not exist

**Review by SleepyGemmy — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]

**Review by Arrow768 — CHANGES_REQUESTED** [review]
If you update the path of the item, you also need to update the maps

**Comment by Acetrea** [comment]
!review

**Pull request merged**
