### PR TITLE
Uueoa-Esa, Part 5: Away Sites

### PR DESCRIPTION
**Pull request by RustingWithYou**
Adds four away sites for the Uueoa-Esa sector, two of which have ghostroles.
These are, in no particular order:
Abandoned tourism platform and smuggler outpost in orbit of Omgolo
The IHSS Reclamation

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Review by Eyeveri — DISMISSED** [review]
Hey, great maps overall. The code looks fine to me (@DreamySkrell should take a more indepth look as I am still learning), just a couple of requests.

In the omgolo_tourist map, you only have a single area dedicated to the entire "relaxation platform". I think taking the time to make a few more areas, and wire a functioning powernet with some sort of disposal system would be beneficial to adding the atmosphere of it being useable. 
The same with the smuggler platform. I recognize that it is supposed to be derelict so it's not required for that one. 

Mandatory Changes: 
- Every door on all three of the maps is lacking a firedoor. Please add this. 
- Separate areas for the tourist platform.
- Powernet for the tourist platform. (More than the one you have now)

Suggested Changes: 

- Disposal system for the tourist platform and the IHSS reclamation.
- Add more decorations, maybe some vending machines and decals to the IHSS and tourist map because they both have a LOT of deadspace/seem very empty for places that are (presumably) meant to be lived in/used often. 
- Consider adding windows to the rooms in the tourist area.
- Lots of deadspace with the metal-foam filler, is this needed? You could cut down on the station size by just closing the deadspace if not. 

Thanks!

**Comment by RustingWithYou** [comment]
> Hey, great maps overall. The code looks fine to me (@DreamySkrell should take a more indepth look as I am still learning), just a couple of requests.
> 
> In the omgolo_tourist map, you only have a single area dedicated to the entire "relaxation platform". I think taking the time to make a few more areas, and wire a functioning powernet with some sort of disposal system would be beneficial to adding the atmosphere of it being useable. The same with the smuggler platform. I recognize that it is supposed to be derelict so it's not required for that one.
> 
> Mandatory Changes:
> 
> * Every door on all three of the maps is lacking a firedoor. Please add this.
> * Separate areas for the tourist platform.
> * Powernet for the tourist platform. (More than the one you have now)
> 
> Suggested Changes:
> 
> * Disposal system for the tourist platform and the IHSS reclamation.
> * Add more decorations, maybe some vending machines and decals to the IHSS and tourist map because they both have a LOT of deadspace/seem very empty for places that are (presumably) meant to be lived in/used often.
> * Consider adding windows to the rooms in the tourist area.
> * Lots of deadspace with the metal-foam filler, is this needed? You could cut down on the station size by just closing the deadspace if not.
> 
> Thanks!

Mandatory changes have been addressed, will look at the optional ones when I get the chance.

**Comment by Eyeveri** [comment]
> Mandatory changes have been addressed, will look at the optional ones when I get the chance

I'll re-review when I am home today.

**Comment by DreamySkrell** [comment]
image
all of these away site maps should be 255x255

**Comment by DreamySkrell** [comment]
image
image

there are shuttle window spawner variants now, and they should be used in place of the boring black metal window frame spawners

see civilian yacht or scc scout for examples

both the raider and the other shuttle var subtypes should also have shuttle window subtypes, as these walls are used in a lot of places so it would be nice to have them defined in code

**Comment by DreamySkrell** [comment]
image

I'm sorry, but this needs more work to make it good

It does not at all look like a industrial complex... there's not much to do here actually.
There's a ton of mining equipment, but nothing to actually mine, not even an airlock to go outside.

I think I did an okay job with my Crystal Planet Outpost to make it feel like a planet away site - though that one was not intended for miners to mine stuff, so this Tret outpost would need the walls to have minerals - but iirc the old blueriver map has walls with minerals.

**Comment by DreamySkrell** [comment]
merge from master

**Comment by DreamySkrell** [comment]
image
I feel a tiny kitchen could be nice so they can cook the kois they can grow in the hydroponics
or at least use `/obj/structure/closet/crate/freezer/kois` and `/obj/structure/closet/crate/freezer/kois/rations`

**Comment by DreamySkrell** [comment]
image
stations, especially abandoned, should use normal non-shuttle walls, as shuttle walls are harder to damage/destroy/deconstruct

**Comment by DreamySkrell** [comment]
image

this does not really look like abandoned, it's kinda fresh and pristine and perfectly clean and arranged
it should show at the very least *some* environmental storytelling as to hint at why it was abandoned
I would expect more dirt and things left on tables and floors

I think I do a good job with abandoned stuff, like my Abandoned Industrial Station or Abandoned Propellant Depot, so could look at those for ideas

**Comment by DreamySkrell** [comment]
image

the hangar is using fake unsimulated blast doors, when they should just be blast doors without a connected button

but...

it should be external docks instead, not a hangar, so many ships of different orientations and shapes can visit it, instead of just one in the hangar

it should at the very least have some storage space, some little maint space maybe, cause it does not really feel like a place people would live in or visit

the exterior could use a bit more love too, like some lattices or the like, nav lights, etc

**Comment by DreamySkrell** [comment]
image
no windows on engines

**Comment by DreamySkrell** [comment]
image
this station is kinda unnecessarily huge - what is the point of having both the outer AND inner hallways? they're kinda redundant

**Comment by DreamySkrell** [comment]
image
sensors and IFF in space area so they won't get power - should be (for example) bridge area on top of them

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
.

**Comment by RustingWithYou** [comment]
> image
> 
> I'm sorry, but this needs more work to make it good. Like honestly it does not look fun or interesting to play in or to visit it.
> 
> It does not at all look like a industrial complex... there's not much to do here in general, and very little flavor or fluff to make it look like it's Tret and Vaurca and Industry and Mining are here. There's a ton of mining equipment, but nothing to actually mine, not even an airlock to go outside. Both the interior and the exterior are featureless and barren.
> 
> I think I did an okay job with my Crystal Planet Outpost to make it feel like a planet away site - though that one was not intended for miners to mine stuff, so this Tret outpost would need the walls to have minerals - but iirc the old blueriver map has walls with minerals.
> 
> I can elaborate more on how I could suggest to improve it, on discord, if you'd like. I have some ideas but I don't want to impose them on your vision I guess and tell you "this is how it should look like"

The intent is largely to work like one of the mining station maps, where they get on the shuttle & mine elsewhere. As for Vaurca flavoring, we don't have a lot of stuff for that in general.

**Comment by RustingWithYou** [comment]
> I find the second option much more interesting, and thinking about it now, I could do it if you'd like, cause it sounds like a interesting mapping project cause we don't have anything like that already. I could have it ready before the arc, since there's at least a month still cause we're not even in Adhomai yet.

This would be appreciated, I'm pretty busy with IRL stuff RN and not 100% sure when I'll get a chance to work on these so if you want to help with them feel free.

**Comment by DreamySkrell** [comment]
I will do Tret stuff in <https://github.com/Aurorastation/Aurora.3/pull/19054>

**Comment by Eyeveri** [comment]
When the rest of Dreamy's changes are met, I'll re-approve. I think most of this is generally fine.. but I share concerns about the playability of some of the maps - but Dreamy has already outlined all of it.

**Comment by DreamySkrell** [comment]
request review or comment when everything is fixed and ready for review again

**Review by DreamySkrell — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
