### PR TITLE
Docks computer program.

### PR DESCRIPTION
**Pull request by DreamySkrell**
image

- [x] initial impl
- [x] make sure it's wanted
- [x] make it a modular computer program
- [x] provide a way to reconnect if somehow the computer loses connection to the overmap ship thing
- [x] console sprites for the the program
- [x] rename the navpoints so they are consistent and make sense
- [x] ship renaming so antags (and the merchant) can rename their ship for whatever gimmick they like
- [x] better default names for antag/merchant ships (so burglar ship is not named "Burglar Pod" etc)
- [ ] maybe add this to ships other than horizon (maybe)
- [ ] maybe do something about the double hangar bay navpoints (generic + burglar/ert on the same spot)

Ship renames:
- "Agent Shuttle" -> "SCC Shuttle"
- "Merchant Shuttle" -> "ICV Enterprise"
- "Burglar Pod" -> "Water Bear"
- "Mercenary Shuttle" -> "ICV Raskolnikov"

Feedback here or on discord in the code dungeon.

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!wip

**Comment by DreamySkrell** [comment]
!review

**Comment by Eyeveri** [comment]
Question. Is there anyway for you to make it so that the names of the antag ships and merchant ship are randomized?

**Comment by DreamySkrell** [comment]
> Question. Is there anyway for you to make it so that the names of the antag ships and merchant ship are randomized?

Yes, but Matt told me to just give them a single default name each, cause the names can be changed in game anyways.
So the default names are basically just so if the antags forget to change them, they are not found out the first minute after they dock.

**Review by Alberyk — APPROVED** [review]

**Pull request closed without merging**
