### PR TITLE
Adds the gigashatter proc

### PR DESCRIPTION
**Pull request by Geevies**
* Gave Admins a gigashatter proc, which will fracture every single bone in your body. Fear the wrath of the redname.

Admins, you can call this proc by VVing a human mob, going to "call proc", then typing in 'gigashatter', then press finished and OK.

image

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by Geevies** [comment]
Would the Head Devs fire me if I added High Priority to this?

**Comment by NonQueueingMatt** [comment]
Why not add it to the VV dropdown?

**Comment by Kaedwuff** [comment]
I was trying to think what purpose this would serve other than admin fuckery, but then I thought, you know, it might be interesting for setting up a severely injured person during events and stuff.

**Pull request merged**
