### PR TITLE
Converts the diona accent into Rootsong and Voidsong.

### PR DESCRIPTION
**Pull request by TheStryker**
As the name suggests, it breaks down the current diona (SNG) into rootsong (RSG) and voidsong (VSG) to better reflect diona lore.
All sprites and flavor texts done by Caelphon.
image

### CODE REVIEW

**Review by Chada-1 — APPROVED** [review]

**Comment by alsoandanswer** [comment]
Hey, if your PR is ready, don't forget to comment !review.

**Comment by TheStryker** [comment]
!review

**Review by JohnWildkins — APPROVED** [review]
tree

**Review by NonQueueingMatt — APPROVED** [review]
I can't wait to see all o

**Pull request merged**
