### PR TITLE
Reduces warding sphere sheath and business card holder loadout cost to zero

### PR DESCRIPTION
**Pull request by feartheblackout**
Just seemed unfair to me to have to sacrifice two loadout points when one item isn't even as effective without the other.

### CODE REVIEW

**Comment by feartheblackout** [comment]
!review

**Comment by Alberyk** [comment]
What the sphere has to do with the card holder?

**Comment by feartheblackout** [comment]
> What the sphere has to do with the card holder?

They're unrelated, but what they share in common is that they are both useless without another loadout item (warding sphere for the sheath, business card for the card holder).

**Comment by Alberyk** [comment]
Can't you make the sheath spawn with a sphere inside?

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
if each item forms a necessary pair, they should spawn together.

**Pull request closed without merging**
