### PR TITLE
Deck 1 Res. E.V.A., Sec. Chp., and Deck 2 Mech Bay QoL and Fixes

### LINKED ISSUE #13598: No Access Requirements to Get Into Xenoarcheology
title. reported on the discord so i don't know the full details.

### PR DESCRIPTION
**Pull request by SleepyGemmy**
fixes #13598.
- moves the mech bay maintenance door up a few tiles.
- makes it so both roboticists (i.e. machinists) and research can access the mech bay.
- adds a button to the outside for the shutters, with appropiate access requirements.
- adds some visual polish to the deck 1 area below the mech bay.
- fixes some access requirements on the maintenance doors so that engineering can use the maintenance passthrough area in the area mentioned on the point above.
- adds windoors and fixes access requirements in the xenoarch area so that people can't mess with xenoarch's things.
- remaps research eva to streamline it and moves the research substation to above xenoarcheology.
- remaps the security checkpoint so its usable as a checkpoint, remaps the hangar slightly so that people can't just walk around it if it's in use.

everything is playtested and works like it should (since commit 1b0d02e).

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Comment by Ben10083** [comment]
If you are doing this, can you give the interior doors in the mech bay access reqs as well? Last I checked they are all access.

**Comment by Arrow768** [comment]
`makes it so both roboticists (i.e. machinists) and research can access the mech bay.`
That is a nogo, as the machinists are part of a different department.

**Comment by SleepyGemmy** [comment]
closing the pr and making it atomic, i.e. only moving the maint door up.

**Comment by Arrow768** [comment]
And I confused the areas, so that is fine

**Review by Arrow768 — APPROVED** [review]

**Comment by SleepyGemmy** [comment]
draft while i sort out the merge conflict.

**Comment by SleepyGemmy** [comment]
lmao

**Comment by SleepyGemmy** [comment]
deleted the PR. i'll remake it at some point.

**Comment by SleepyGemmy** [comment]
deleted the PR. i'll remake it at some point.

**Comment by SleepyGemmy** [comment]
deleted the PR. i'll remake it at some point.

**Pull request closed without merging**
