### PR TITLE
Removes the Disabled Rat Entry From the Ghostspawner Menu

### LINKED ISSUE #13351: Rat Ghost Spawner Entry Shows to Players
if it is disabled, it shouldn't be visible to players, only staff.

### PR DESCRIPTION
**Pull request by Greenjoe12345**
Rats no longer show on the ghostspawn menu, they've been unselectable for years now, just sitting there, and now this removes them from showing at all. If admins wanted to enable them the option is still there.
fixes #13351

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Comment by SleepyGemmy** [comment]
probably not a proper solution. refer to #13347.
i.e. rats being disabled is a config option and their ghost spawner entry showing up despite being disabled in the config is what should be solved.

**Review by SleepyGemmy — COMMENTED** [review]
probably not a proper solution. refer to https://github.com/Aurorastation/Aurora.3/pull/13347.
i.e. rats being disabled is a config option and their ghost spawner entry showing up despite being disabled in the config is what should be solved.
or, if you want to disable rats directly on the entry instead of in the config, then you should remove the relevant config things as well.

**Comment by Greenjoe12345** [comment]
fixes #13351

**Comment by NonQueueingMatt** [comment]
Disabled roles should probably just not show up for players instead.

**Pull request closed without merging**
