### PR TITLE
New (old) Aviator Sprites.

### PR DESCRIPTION
**Pull request by NotSchwann**
The new aviator sprites don't look great, in my opinion, and the original PR received enough negative feedback to warrant a revert to the old non-opaque sprites. This push request does that, but leaves the rest of the sprites intact. I've added off states for HUDs that did not already have them, as a note.

### CODE REVIEW

**Comment by NotSchwann** [comment]
!review

**Comment by alsoandanswer** [comment]
>PR received enough negative feedback to warrant a revert to the old non-opaque sprites.

The negative feedback was about the antennae.
Please find relevant feedback to support your claim, because as I see it, you are the only one concerned about this, being the only one to provide negative feedback on aviator opacity.

**Comment by NotSchwann** [comment]
> > PR received enough negative feedback to warrant a revert to the old non-opaque sprites.
> 
> The negative feedback was about the antennae.
> Please find relevant feedback to support your claim, because as I see it, you are the only one concerned about this, being the only one to provide negative feedback on aviator opacity.

In the interest of fairness, would you like a feedback thread so we can gather opinions on the old aviators versus the new ones? If it turns out I am a lone maniac ranting about aviators, I will happily close this push and accept the resprited aviators.

**Comment by NotSchwann** [comment]
https://forums.aurorastation.org/topic/13773-feedback-new-vs-old-aviators/ Feedback thread, as per request @Arrow768

**Comment by NotSchwann** [comment]
The icon conflicts are becoming a problem so I'm starting from scratch.

**Pull request closed without merging**
