### PR TITLE
Hammertail Manufacturing Station

### PR DESCRIPTION
**Pull request by RustingWithYou**
Adds a new away site, a Hammertail Smiths manufacturing station complete with several ghostroles.

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Comment by beepbopbeepbop** [comment]
A great ghostspawn that I will definitely see myself enjoying in the near future, though there are some small things that could hopefully be addressed before it gets merged...

The hydrogen chamber here being converted to an air mix chamber, due to the size of the distro network, and the lack of necessity for more than a single hydrogen canister in the shuttle.
image

The replacement of the old air tank here with a pipe running off from the scrubber line that leads to a vent in space, to more easily dispose of contaminants, rather than having to drag the canister out into space and empty it manually.
image

And finally, I was wondering if the small solar panel farm and single nuclear generator are enough to fully sustain all the high power usage this station has?

**Comment by DreamySkrell** [comment]
image
fake unsim walls here
replace with actual blast doors (without a button linked)

**Comment by DreamySkrell** [comment]
image
all of these asteroid walls and floors should be the simulated variants

**Comment by DreamySkrell** [comment]
image
this is a space station, so there should be firedoors under every door
and some in the long hallway in the middle too

**Comment by DreamySkrell** [comment]
image
is this cash on the floor actually put in the safe on spawn? huh

**Comment by DreamySkrell** [comment]
image
image
should use colored shuttle windows

**Comment by DreamySkrell** [comment]
image
NOT REQUIRED / OPTIONAL:
I think the base would be a ton better with some maint space around it, in places outlined in red.
It would look better and more lived in, and also be more functional if someone were to invade it.
Cause right now it's sorta just a simple straight long hallway with stuff going to the sides.
Maintenance tunnels would make it more interesting to defend and attack, with alternate routes and the like.

**Comment by DreamySkrell** [comment]
image
need like any kind of spare and inconspicuous clothing
could be unathi clothing
could be human/generic like ponchos or overalls or jumpsuits or whatever

cause right now they only have hammertail jumpsuits, and it's going to be a bit hard for them to try to sell stuff and stay covert
while dressed in these red jumpsuits with insignia on with swords, looking sus af
it's fine if they spawn in those ofc, but they need more clothing options

**Pull request closed without merging**
