### PR TITLE
Void Identification Stuff

### PR DESCRIPTION
**Pull request by Geevies**
* Added LED collars. It produces faint light but will be very bright on your character sprite. Can be worn on uniforms, voidsuits, and armor. Can change color by using in-hand. Mapped a box into EVA and the warden's office.
* Mapped a box of electro-tether devices into EVA.
* Tweaked electro-tethers to have less bright beams the farther away the users are from eachother.

image
image

### CODE REVIEW

**Comment by KingOfThePing** [comment]
Yo, this is radical

**Review by DreamySkrell — APPROVED** [review]

**Comment by SleepyGemmy** [comment]
please map one into the crew armoury as well. would be cool.

**Review by SleepyGemmy — APPROVED** [review]

**Comment by SleepyGemmy** [comment]
please map one into the crew armoury as well. would be cool.

**Comment by GMR25** [comment]
Would it be possible to see these in Cargo Orders in the future? This shit would be sweet for some rave/party gimmicks.

**Comment by SleepyGemmy** [comment]
> Would it be possible to see these in Cargo Orders in the future? This shit would be sweet for some rave/party gimmicks.

you can request this to Arrow or in the forum thread.

**Pull request merged**
