### PR TITLE
Y̵͏ò̕u ͏͟B̷ét̢҉te̸r͘ ̵Wa͟͢͠ţc̛͡h҉ ͘͟͢Òut͠ (Holiday Decor)

### PR DESCRIPTION
**Pull request by furrycactus**
December is almost here! Decoration time!

- Grass tiles around the station have been replaced with snow for the winter-y feel (sorry fellow southern hemisphere guys, sandy summer Christmas theme next year hopefully).
- Door wreathes have been added to airlocks in public halls and spaces, as well as department entrances, head of staff offices, and break rooms.
- Holiday lights have been placed in excess on windows and some walls in the areas previously mentioned above.
- The bar layout has been moved around, there's a table around a christmas tree in there now, with presents underneath it.

### CODE REVIEW

**Comment by furrycactus** [comment]
We need this in on December 1st, **super** important, yes.

**Comment by furrycactus** [comment]
!review

**Comment by alsoandanswer** [comment]
Now all that's missing is replacing the ship's ambience with annoying christmas muzak
https://www.youtube.com/watch?v=d2tx5NHDcHA

**Comment by KingOfThePing** [comment]
aaaaaaaaaaaAAAAAAAAAAAAA

**Comment by furrycactus** [comment]
Don't merge yet because I'm getting some last minute stuff from Doxxmedearly

**Comment by furrycactus** [comment]
Okay there we go YEET

**Comment by furrycactus** [comment]
To clarify what Doxxmedearly added:
-Removed trash and added new items to list of contents for xmas gifts. 
-Cleaned up the list of gift givers by removing some memes and adding new names
-Gifts will spawn randomly as small, medium, or large.

**Pull request merged**
