### PR TITLE
More MedSci Sprites

### PR DESCRIPTION
**Pull request by furrycactus**
Adds more of the Medical and Science uniform sprites. Still have stuff to do. My understanding of code is pretty limited so if anyone knows how to do any of the things I'm trying to do, please comment and tell me how. Otherwise, I'll keep trying to get them working. Also please if any merciful coder feels like looking over any changes out of the kindness of their heart while I'm working on this, _please_ point out anything that might be broken or wrong.

- [x] Make Biochemists spawn with the correct shoes.

- [x] Make Research Directors spawn with the new jumpsuit if no alternate clothing is picked in the loadout.

- [x] Make Xenoarchaeologists spawn with the new jumpsuit if no alternate clothing is picked in the loadout.

- [x] Get the alt. research uniforms in the loadout.

### CODE REVIEW

**Comment by furrycactus** [comment]
Jesus Christ touching the Exodus made the additions/deletions jump right up.

**Comment by furrycactus** [comment]
Huh. I dunno why it requested Skull

**Comment by TheGoret** [comment]
who the hell is travis

**Comment by furrycactus** [comment]
That bot that does checks you goober

**Comment by furrycactus** [comment]
I've decided I'll do the dispenser in a separate PR.

**Comment by furrycactus** [comment]
!review

**Pull request merged**
