### PR TITLE
Sparky's Bugfix Trilogy

### PR DESCRIPTION
**Pull request by Sparkyhotdog**
Fixes a bunch of minor problems I'd noticed in-game.

**Changes:** 
  - bugfix: "You no longer pick up or drop plates and bowls when you finish them with cutlery."
  - bugfix: "Mass spectrometers now show the IC name for any reagents, not their object path."
  - bugfix: "Diona nymphs now have the default diona accent."

### CODE REVIEW

**Comment by Sparkyhotdog** [comment]
!bugfix

**Comment by Sparkyhotdog** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]
Be sure to reference any relevant issues.

**Comment by Sparkyhotdog** [comment]
There aren't any issue reports, so....

**Review by mikomyazaki — APPROVED** [review]

**Pull request merged**
