### PR TITLE
Removes footprints in the ash

### PR DESCRIPTION
**Pull request by LordFowl**
Removes footprints from ash turf. They were ugly, poorly implemented, and generally a mistake. God forgive me.

### CODE REVIEW

**Comment by Pacmandevil** [comment]
They'd probably look decent if they had their own footprint sprites, instead of ones designed for use in blood with a color value attached.

**Comment by Lohikar** [comment]
Probably also help if they didn't hover in mid-air on openspaces.

**Comment by ben10083** [comment]
perhaps the best idea would be to improve them instead of removing them, I personally think they are good since they allow security to be able to track antags when they escape into space. 

...although I do NOT like how they tracking indoors, it is very ugly.

**Comment by LordFowl** [comment]
If I ever improve them, which is not a distant possibility, it will probably be usimg literally none of this code or spriting.

**Comment by Pacmandevil** [comment]
that's a fair point. it'd probably be loads better to not hook into the already existing blood stuff at all in this situation

**Comment by chaoko99** [comment]
I suggest using TGstation's footprints for dirt.

**Pull request merged**
