### PR TITLE
Glass(Wario)ware

### PR DESCRIPTION
**Pull request by alsoandanswer**
Reverts Beakers from "Aurora Style" change.

Moves inhands to be contained sprites.

Improves sprites for syringes, autoinjectors, DNA injectors, Lazarus injectors.
They should look better and be more consistent (all with a 45 degree tilt)

### CODE REVIEW

**Comment by Roostercat12** [comment]
But why? The sprites have been changed to this in the past, and were immediately replaced with the current sprites because the current ones are simply better. These ones clash with our artstyle far more - which was why the current ones were put in place to begin with.

**Comment by alsoandanswer** [comment]
> But why? The sprites have been changed to this in the past, and were immediately replaced with the current sprites because the current ones are simply better. These ones clash with our artstyle far more - which was why the current ones were put in place to begin with.

The current sprites were added in a completely unwanted PR with zero coordination with any of the spriters.

I really don't like to say this, but I feel that a SPRITER DEVELOPER should have more say in the artstyle than a contributor.

**Comment by Roostercat12** [comment]
For one thing, this is an open source project. Anyone can contribute and it is not on them to inform developers of everything they do because that is precisely what the github log is for. In fact, it was looked over by developers and put in anyway and has STAYED that way for well over a year. Secondly, if you really feel that these sprites are better - which I personally feel they are not - make a feedback thread and ask people which is better.

**Comment by alsoandanswer** [comment]
> For one thing, this is an open source project. Anyone can contribute and it is not on them to inform developers of everything they do because that is precisely what the github log is for.

Yes? I understand that, I'm just giving my rationale on why I'm doing this reversion.

>In fact, it was looked over by developers and put in anyway and has STAYED that way for well over a year.

I don't think this matters. None of the reviewers were spriters. I can't really fault them for not mulling over the implications of artstyle or whatever, because it's literally not their job.

>Secondly, if you really feel that these sprites are better - which I personally feel they are not - make a feedback thread and ask people which is better.

I don't really see the point of making a feedback thread. These sprites are planned to be part of a greater artstyle shift in future and comparing it to present sprites is counterproductive.

**Comment by Roostercat12** [comment]
The artstyle you are arguing for is currently non-existent. Saying it is 'for the artstyle' makes no sense when these are, for one thing, a port, and secondly, none of this other 'artstyle' stuff is really being shown. Currently it is just a blanket reason to pass PRs through. Saying the artstyle will 'change for the future' is also not really supporting it here since it has been said a million and one times in the past and still hasn't really taken form.

I think there is every reason to put this on a feedback thread. These sprites have been put in before, they were replaced and the replaced sprites have been on the server for well over a year. You are now reverting them for an 'artstyle' that currently effectively just consists of ports on your end. There should be a feedback thread to see if people even want this since it is what they are going to be using from here on out.

In fact, this is the exact same excuse that you used on the 'unwanted' PR that replaced these sprites: https://github.com/Aurorastation/Aurora.3/pull/13399

**Comment by alsoandanswer** [comment]
> 
We had a (admittedly premature) testmerge of the new turf sprites in our new artstyle, with a feedback thread *you* commented on.

We *have* a new artstyle. It's being worked on. It's why I'm doing this PR again.

**Comment by granodd** [comment]
If you insist to bring back the Eris style of the bottles and beakers: make them smaller. They were changed before hand partially because they clashed with everything else a lot, but also because they were so laughably large it made working in chemistry more tedious.

Also add more bottle variation, as Eris style only has one sprite for that.

**Comment by alsoandanswer** [comment]
> If you insist to bring back the Eris style of the bottles and beakers: make them smaller. They were changed before hand partially because they clashed with everything else a lot, but also because they were so laughably large it made working in chemistry more tedious.

Yeah, no problem.

> Also add more bottle variation, as Eris style only has one sprite for that.

My original PR already added more variants, but I can add more if you need.

**Comment by alsoandanswer** [comment]
!review

**Pull request closed without merging**
