### PR TITLE
Local contributor goes insane, removes loadout after clothing PRs

### PR DESCRIPTION
**Pull request by VTCobaltblood**
#5996 except I hope I'll actually have this done.
Removes loadout bloat wherever possible. Some items are removed to be made maint spawns or sold in a vendor, others are made recolorables to reduce the amount of really long lists. 

- [ ] Get a sprite for the department wear vendor and map it in
- [ ] More maintenance spawns
- [ ] Port pants from my previous PR
- [ ] Uncontain sprites to reduce file clutter
- [ ] Test everything like crazy
- [ ] Make a changelog
- [ ] Fix shit
- [ ] Remove more shit

A second PR will follow this one re-spriting some loadout items that are to be removed due to being ugly as hell, if so desired.

### CODE REVIEW

**Comment by LordFowl** [comment]
The PR you’ve linked to is finished. How embarrassing! This PR deletes a little too much.

**Comment by VTCobaltblood** [comment]
Except it's abandoned in the depths of 2nd page hell.

**Comment by LordFowl** [comment]
As was its objective. Many of the loadout itens are already available in game, abd the PR’s intent was not to affect that. I also find the comment “does little to reduce bloat, but just makes the loadout standard compliant”... That’s how bloat works, hun

**Comment by VTCobaltblood** [comment]
> Many of the loadout itens are already available in game, abd the PR’s intent was not to affect that.

No lol. In fact, unlike my own PR and in particular the commit that will be coming literally in a second after this comment, you haven't removed any items that are already available in-game via lockers. 
You have removed ugly and outlandish items, but have you removed truly unnecessary items? I fail to see any effort in that regard in your PR.

**Comment by GMR25** [comment]
Isn't it a tad unrealistic to expect someone to have to re-purchase their uniform/accessories every single shift they go to work? I understand there's a crusade against customization, but this is simply ridiculous and immersion-breaking at best.

Unless this is part of some greater scheme involving persistent purchases/outfits between rounds, I don't see how locking uniforms behind vendors improves anything in regards to gameplay and player enjoyment.

**Comment by VTCobaltblood** [comment]
>  re-purchase their uniform

Where. I didn't put any uniforms in the vendor. Uniforms that I removed from the loadout were removed for 2 reasons:

1. They are already available in the lockers;
2. They're against the security uniform regulation.

>  unrealistic to expect someone to have to re-purchase accessories every single shift they go to work

Since the economy is non-persistent, this is not an issue. This is made to make loadout more readable, as well as solve the issue of winter coats not being acceptable NT wear while still making them available for jobs that need them due to cold temperatures.

**Comment by GMR25** [comment]
> 2. They're against the security uniform regulation.

How would the navy sec uniforms be considered against uniform regulation? What purpose does removing them from loadout and making them either vendor or (even worse) RNG-spawn only serve? You're removing one of the few aesthetically pleasing and valid uniform alternatives for a department that has piss-poor customization options as is.

> Since the economy is non-persistent, this is not an issue.

Going to my previous statement, the current 'economy' is heavily RNG-based. One round you can be sitting on a decent amount, the next you can't buy a few drinks. Loadout alleviated this by allowing people to personalize without having to fight over items in maintenance/vendors, or hoping the merchant was selling it.

I can only hope there would be a feedback thread on this in the near future.

**Comment by VTCobaltblood** [comment]
> How would the navy sec uniforms be considered against uniform regulation?

No personal clothing items on security personnel. I interpret that as "don't pick anything that's not in a corporate locker." 

> You're removing one of the few aesthetically pleasing and valid uniform alternatives for a department that has piss-poor customization options as is.

I am aware. 

> Going to my previous statement, the current 'economy' is heavily RNG-based. 

Hence why the items in that vendor are pretty cheap for a clothing item. I don't doubt that even an intern role could afford those. 

> Loadout alleviated this by allowing people to personalize without having to fight over items in maintenance/vendors, or hoping the merchant was selling it.

The loadout is still here. The title is a joke, y'know. Maybe you should read the PR contents.

**Comment by VTCobaltblood** [comment]
By the way, I also consider claiming a "crusade against customization" very funny to be used against me in particular because I've added a _shitton_ of clothing items into the loadout personally.

**Comment by GMR25** [comment]
> No personal clothing items on security personnel. I interpret that as "don't pick anything that's not in a corporate locker."
> I am aware. There is nothing indicating they are valid, though.

Being in the loadout presently is the indicator that they're valid, much as some wouldn't like to admit. If they weren't, they'd have never been in there in the first place. The cadet uniforms were even updated to be visually different, in mind of the navy uniforms (the arm stripe being different).

> The loadout is still here. The title is a joke, y'know. Maybe you should read the PR contents.

I have, seeing that the above uniform set is going into maintenance RNG is exactly my case.

**Comment by VTCobaltblood** [comment]
> Being in the loadout presently is the indicator that they're valid, much as some wouldn't like to admit.

Some like CCIA which I asked about this?

**Comment by ParadoxSpace** [comment]
It's absolutely stupid for what is clearly a part of the Security uniform sets to be counted as a 'personal item.' It's absolutely stupid to take them out of the loadout as well.

**Comment by VTCobaltblood** [comment]
> It's absolutely stupid for what is clearly a part of the Security uniform sets to be counted as a 'personal item.' 

Such are CCIA words.

**Comment by JMJ99** [comment]
To clarify, the Security uniform directive is intended to prevent ugly or ridiculous items such as cloaks or wigs being worn by security personel. This does not include items such as the alternate uniforms(Navy, corporate etc.) or the winter and dress jacket from being worn.

**Comment by Sindorman** [comment]
This discussion need to go either discord of forums.

**Pull request closed without merging**
