### PR TITLE
BAPI - spacemandmm dmm reading

### PR DESCRIPTION
**Pull request by DreamySkrell**
More bapi work, docs, etc.

The actual changes seen from DM side, is that all maps are parsed and checked by spacemandmm. It does not really add much safety for us, as everyone uses strongdmm anyways (which uses spacemandmm), but I will need to do that anyways in future work.

The bapi call is on every map in the maploader, so if it does not work, if it crashes or panics or whatever, we'll see it immediately (cause the maps don't load). It should work fine, though, unless the setup is wrong. I wrote more about safety and other things in readme text file in rust/bapi dir.

So, yeah. The point of this PR is to do something meaningful with bapi, and see if the whole workflow and setup and everything works correctly, before doing any further work in future PRs.

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!build_bapi

**Comment by DreamySkrell** [comment]
!build_bapi

**Comment by DreamySkrell** [comment]
!build_bapi

**Review by Arrow768 — APPROVED** [review]

**Comment by DreamySkrell** [comment]
!build_bapi

**Comment by DreamySkrell** [comment]
!build_bapi

**Comment by DreamySkrell** [comment]
!build_bapi

**Comment by DreamySkrell** [comment]
!build_bapi

**Comment by DreamySkrell** [comment]
!review

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
