### PR TITLE
Replace all mentions of Gorlex Marauders with Hammertail Smiths

### PR DESCRIPTION
**Pull request by Generalcamo**
Per [this post,](https://forums.aurorastation.org/topic/18955-the-gorlex-marauders-a-polite-galaxy-is-an-armed-galaxy/page/2/#comment-169694) the intended canonization app for Gorlex Marauders has a new name. This reflects that by replacing all mentions of Gorlex Marauders with Hammertail Smiths.

### CODE REVIEW

**Comment by Generalcamo** [comment]
!review

**Review by FluffyGhoster — APPROVED** [review]

**Comment by DreamySkrell** [comment]
I do not think generic antag gear should be connected to any place in the lore. I wouldn't want to see crew pointing out that some random mercs are using unathi pirate gear, so they must be pirates too.

**Comment by Generalcamo** [comment]
The whole intention of that canon app was to provide our own replacement of the Gorlex Marauders. This PR implements it since it was accepted. As for assuming they are unathi pirates, considering they export across the spur, that would be a stretch:

> By now, arms and armor by the Hammertail Smiths can be found in the hand of any criminal, wherever they are, so long as they can afford them, or get their hands on it in another way. [...] Despite it all, they continue to grow, produce, and sell all over the Spur.

**Comment by RustingWithYou** [comment]
Unathi lore approved.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
