### PR TITLE
Wrecked Idris Transport

### PR DESCRIPTION
**Pull request by RustingWithYou**
Adds a new away site, a wrecked Idris Incorporated high-value transport ship.

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
image

Add some lattices or something to connect the different parts, cause right now it looks kinda silly - they'd just drift off into space if they're not held together somehow.

**Comment by lavillastrangiato** [comment]
I think it would also give the site more sovl if you added miscellaneous debris everywhere. Some of the walls around the main ring could be broken, there could be a few bits of glass, money, a limb, floating off into space, some stray lattices, maybe another Environmental Storytelling Skeleton.

**Comment by RustingWithYou** [comment]
> image
> 
> Add some lattices or something to connect the different parts, cause right now it looks kinda silly - they'd just drift off into space if they're not held together somehow.

With the way the ship's been designed with pieces having drifted apart, connecting them is difficult to make look good. The ship pieces still being so close together might be unrealistic, but I think it works for the general sort of nature of the site. I might add some lattices around the edges of the damaged bits, though.

**Review by DreamySkrell — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
