### PR TITLE
Makes IV drips not dense objects

### PR DESCRIPTION
**Pull request by ParadoxSpace**
just qol. makes IV drips walkable through.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
That's the worst changelog I've ever seen.

**Comment by skull132** [comment]
I would label this as power creep and say no. A QoL change would be making it so that an IV drip that's attached to someone could move with them, for example. This is little more than removing a legitimate and an organic obstacle from gameplay.

**Comment by Sindorman** [comment]
@skull132 I suggested making like if you drag IV on yourself it would take x amount of time for you to "move aside IV, go through and put it back". With people of non-help intent having chance of disconnecting attached IV as they move

**Comment by skull132** [comment]
Closing as power creep/not explained well enough. There are other solutions to this issue, if need be.

**Comment by ParadoxSpace** [comment]
how is that power creep tho

**Pull request closed without merging**
