### PR TITLE
RenegadeBuff

### PR DESCRIPTION
**Pull request by AveryThePanda**
Adds an uplink to Renegades, 15 TC. Checkmate, Traitors.

### CODE REVIEW

**Comment by AveryThePanda** [comment]
!review

**Comment by bearschwanz** [comment]
Does this not just make renegade traitor with a more linear gimmick and less TC? What is the IC reasoning to them having TC in the first place?

**Comment by Alberyk** [comment]
Might as well remove renegades.

**Comment by NonQueueingMatt** [comment]
I really think that this just makes renegades into a worse traitor, and that point, like Alb said, you may as well remove them.

**Comment by Arrow768** [comment]
Closing this after a discussion with the maintainers.
The point of the renegades is not to be (worse) traitors.
We have traitors for that purpose.

**Pull request closed without merging**
