### PR TITLE
Firearm, Ammo, and Medical Storage Resprites

### PR DESCRIPTION
**Pull request by AmoryBlaine**
- Resprites a number of weapons, magazines.
- Re-adds (?) Medical storage sprites which were either not added during the MedSci resprite, or were but then got rolled back somehow. 
- .45 rubber magazines now have their own sprite.

### CODE REVIEW

**Comment by AmoryBlaine** [comment]
!review

**Comment by AmoryBlaine** [comment]
> 
> 
> The detective and antag revolver should not have the same sprite.

The detective revolver was replaced. It's just there-- because. Not sure why, actually. But yes, only the antag revolver is in play, and used now.

**Comment by NonQueueingMatt** [comment]
If it's unused it should be removed tbh.

**Comment by AmoryBlaine** [comment]
!wip

**Comment by AmoryBlaine** [comment]
!review

**Pull request merged**
