### PR TITLE
Crematorium Additions

### PR DESCRIPTION
**Pull request by furrycactus**
- Added a crematorium to the Chapel and to the Medical Morgue. It struck me as a little odd the only one was in Xenobiology, given that some people have cremation in their post-mortem instructions.

image

301437653-fb53b7cb-48aa-440c-8f75-0af9115bd854

### CODE REVIEW

**Comment by furrycactus** [comment]
Hold up, I misread the wiki about the autopsy stuff.

**Comment by furrycactus** [comment]
!wip

**Comment by nauticall** [comment]
maybe putting a crematorium on top of wooden floorboards is not such a good idea... you should probably make the room made of steel tiles instead

**Comment by furrycactus** [comment]
Adjusted the floors in the Chapel storage to be metal ones. Also added a crate of materials (wood, glass, steel, bronze) to actually make urns from if someone is cremated. Otherwise the ashes just sit on the floor until someone awkwardly sweeps them away.

image
image

**Comment by furrycactus** [comment]
Updated the main comment with up-to-date screenshots and such.

**Comment by furrycactus** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
