### PR TITLE
Milk Alternatives

### PR DESCRIPTION
**Pull request by Kaedwuff**
Per player requests, adds the first part of recipes that use alternatives to regular milk.

Bug milk is finished, soy milk coming soon.

### CODE REVIEW

**Comment by Conspiir** [comment]
Is there no easier way to do this other than doubling (tripling, with soy) every milk recipe?

**Comment by Kaedwuff** [comment]
As far as I'm aware, there really isn't. You can't make a recipe take alternate ingredients with this code, each version of the recipe has to be its own entry.

**Comment by Sindorman** [comment]
Is this WIP?

**Comment by Conspiir** [comment]
I suppose the question must now be:

Is the feature _worth_ it? 

It isn't so much the creation of new things as it is creating a niche and doubling a lot of code to do it. There's no real change in the results that I see aside from a descriptor on some that tells you it's made of not-milk, though the result would look the same, so I'm uncertain how you could tell what milk it was made from. I do wish there was some way to just have beetle milk and soymilk considered "milk" when put in a microwave or oven or something. I have no idea how to do it, though, and you're probably right about spaghetti code. It might be better to have recipes just for beetle milk, which surely has some properties that make it good for Offworlder-Favorite Foods™, whatever those are (I don't know much about Offworlders, can you tell?) and would be cool to add as faction foods.

I'm also a bit worried. Did you test all of these? The chocolate bar one in particular sticks out at me. The other two types have an /on_reaction, but yours doesn't. 

I think the one I'm happiest with is the bugshake. It adds flair, like meatshakes.

**Comment by Geevies** [comment]
@Kaedwuff Would you like to continue working on this / set this as ready to review?

**Comment by skull132** [comment]
No tags and inactive since forever. Reopen and tag if you want this processed.

**Pull request closed without merging**
