### PR TITLE
Setting up characters during rounds

### PR DESCRIPTION
**Pull request by ArcBotSS13**

### CODE REVIEW

**Comment by skull132** [comment]
Real quick, has this been tested?

**Comment by ArcBotSS13** [comment]
Yeah I tested it, but I never tested it with the SQL saves enabled in the config. Shouldn't be a difference though.

**Comment by skull132** [comment]
Mhm, it shouldn't be. As long as the hyperlinks work for selecting, saving, loading, whatever. I'm hoping you tested it beyond simply opening up the menu.

**Comment by ArcBotSS13** [comment]
Don't merge it just yet, going to test it a bit more then comment on this or PM you on discord when it's done.

**Pull request closed without merging**
