### PR TITLE
Adds pneumalin to combat likely offships

### PR DESCRIPTION
**Pull request by Catrly**
It's so incredibly easy to damage your lungs in this game. Internals, airlock issues, maneuvers. This adds 2x auto-inhalers to offships with medical bays/combat capabilities to try and make the EVA side a bit less painful. The exception to this is the SFA, where I removed their surgery kit and gave them full ghetto tools instead to better suit their current lore position.

### CODE REVIEW

**Comment by DreamySkrell** [comment]
image
remove/revert banana peel removal from this PR as it is touching offships mainly

**Comment by DreamySkrell** [comment]
image
fix changelog

**Comment by DreamySkrell** [comment]
image
remove `example copy.yml`

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
as above

**Comment by Catrly** [comment]
Did that do it?

> as above

Did that do it?

**Comment by Catrly** [comment]
Howww do I go about doing this?

**Pull request closed without merging**
