### PR TITLE
Adds the overgrown miningstation awaysite

### PR DESCRIPTION
**Pull request by Yonnimer**
Title^

### CODE REVIEW

**Comment by Yonnimer** [comment]
> please re-save the map file as a TGM file you can do this by opening it in StrongDMM and going to File > Preferences > Save Format > TGM, and then re-saving the file and committing the changes

Should be done

**Comment by Yonnimer** [comment]
!review

**Comment by Yonnimer** [comment]
Offset the navpoints a bit and added a third one

**Review by JohnWildkins — CHANGES_REQUESTED** [review]
`maps/away/generic/overgrown_mining_station.dm` needs to be ticked / included in `aurorastation.dme` for this to actually load

Several places have air-filled tiles exposed to vacuum (actually it's basically the entire station) which will cause an absolute ton of atmospheric processing on roundstart

if you merge master into your branch and then push that, it will run the away site unit test (assuming you've done the aurorastation.dme change as well) and it will list out all the tiles that have air but shouldn't; replace them with airless variants (you may have to add some to the code if they don't exist already, just copy another airless tile and change it to fit the tile you need)

**Comment by Yonnimer** [comment]
> `maps/away/generic/overgrown_mining_station.dm` needs to be ticked / included in `aurorastation.dme` for this to actually load
> 
> Several places have air-filled tiles exposed to vacuum (actually it's basically the entire station) which will cause an absolute ton of atmospheric processing on roundstart
> 
> if you merge master into your branch and then push that, it will run the away site unit test (assuming you've done the aurorastation.dme change as well) and it will list out all the tiles that have air but shouldn't; replace them with airless variants (you may have to add some to the code if they don't exist already, just copy another airless tile and change it to fit the tile you need)

Assuming thiswas all done correctly, it should be good.

**Review by JohnWildkins — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
