### PR TITLE
Changes some parts of forensic

### PR DESCRIPTION
**Pull request by Casper3667**
A bunch of mostly small changes to ease the life of forensics or  help with sorting out their lab.

Added a locked vialbox to the forensic lab so that dangerous chems can be safely stored, alongside with some layout changes such as a new closet to contain some of the many items in the lab. It also adds a new luminol refiller should the case be that an investigator runs out of luminol during their investigation

An extra bodybag box has also been given to forensics so each investigator has one, alongside with another paper scanner in the office for the same reason.

The forensic lab ringer now also clearly indicate the call is coming from forensic, should an investigator have connected their pda to the ringer.

The forensic lab has been given an evidence box in the new closet.

Paperscanners were allowed to fit in filling cabinets given their purpose and the fact both clipboards and photo albums were already permitted in them.

Also replaced a no smoking sign in the security reception with a notice board on request.

To complete the autopsy trays, a vial and syringe were added to the items it start with, as they were already permitted to be put in it.

A button was also added to the investigations office near the chairs to allow people to enter the office without forcing the investigator to get out of their chair.

### CODE REVIEW

**Comment by Casper3667** [comment]
!review

**Comment by Greenjoe12345** [comment]
could you add one way exit access to the lab and office too? I believe that was something they lack?

**Comment by Casper3667** [comment]
At a quick glance, other offices don't appear to generally allow it. I'll add it to the lab tomorrow however.

**Comment by Casper3667** [comment]
> could you add one way exit access to the lab and office too? I believe that was something they lack?

the forensic lab doors now lets anyone exit the lab. Evidence storage remains fully access restricted and entering the lab still requires access.

**Review by Geevies — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
