### PR TITLE
Changes the placement of some items in the uplink

### PR DESCRIPTION
**Pull request by printer16**
Rearranges some items in the uplink datums so they all go from least expensive to most expensive. It appears that most items were already placed like that.

### CODE REVIEW

**Comment by Lohikar** [comment]
Maybe these should be explicitly sorted instead of just using whatever order the compiler dumps them in?

**Comment by skull132** [comment]
Sorting might be better, yes. Reference autolathe?

**Comment by skull132** [comment]
Or check the collections.dm in helper datums.

**Comment by Lohikar** [comment]
Alternately just a simple alphabetical sort via. TimSort.

**Comment by printer16** [comment]
It appears it's already sorted `sortTim(category.items, /proc/cmp_uplink_item, FALSE)`

**Comment by skull132** [comment]
Then this shouldn't even change anything 🤔

**Comment by printer16** [comment]
Mostly for the code side of things. Better to have them organized as they mostly seem to be minus these few exceptions.

**Pull request merged**
