### PR TITLE
Adds colorable hazard vests to the loadout

### PR DESCRIPTION
**Pull request by feartheblackout**
As the changelog says, the first variation just has yellow stripes, whereas the alternate has both colorable vest _and_ stripes.
image
image

### CODE REVIEW

**Comment by feartheblackout** [comment]
!review

**Comment by alsoandanswer** [comment]
There is already a hazard vest selection in the loadout. Also, it is considered a job uniform item, so it shouldn't be recolorable anyway (So people don't circumvent the corporate color-scheme).

**Comment by feartheblackout** [comment]
Echoing my reasoning stated in https://github.com/Aurorastation/Aurora.3/pull/19681#issuecomment-2244273566 for why hazard vests, similarly, should be allowed more freedom in customization.

**Review by FluffyGhoster — APPROVED** [review]
Code is fine

**Review by DreamySkrell — APPROVED** [review]
I think this is fine.

Even if unwanted for the loadout, should at least be added for offships/etc too.

**Pull request merged**
