### PR TITLE
Glass Floors

### PR DESCRIPTION
**Pull request by Lohikar**
WIP

### CODE REVIEW

**Comment by SilenceInsider** [comment]
What's not finished tho?

**Comment by Lohikar** [comment]
No construction, no deconstruction, no way to break beyond just falling on them.

**Comment by BotBOREALIS** [comment]
Icons with diff:
<details><summary>icons/turf/smooth/glass.dmi</summary>

Key | Old | New | Status
--- | --- | --- | ---
damage50||damage50|Created
1-nw||1-nw|Created
3-i||3-i|Created
4-se||4-se|Created
4-i||4-i|Created
2-ne||2-ne|Created
3-f||3-f|Created
3-w||3-w|Created
1-n||1-n|Created
4-e||4-e|Created
floor_glass||floor_glass|Created
1-i||1-i|Created
3-s||3-s|Created
4-s||4-s|Created
2-f||2-f|Created
damage75||damage75|Created
1-f||1-f|Created
2-e||2-e|Created
2-n||2-n|Created
3-sw||3-sw|Created
1-w||1-w|Created
4-f||4-f|Created
2-i||2-i|Created
damage25||damage25|Created
</details>
<details><summary>icons/turf/smooth/glass_reinf.dmi</summary>

Key | Old | New | Status
--- | --- | --- | ---
damage50||damage50|Created
1-nw||1-nw|Created
3-i||3-i|Created
4-se||4-se|Created
4-i||4-i|Created
2-ne||2-ne|Created
3-f||3-f|Created
3-w||3-w|Created
1-n||1-n|Created
4-e||4-e|Created
floor_glass||floor_glass|Created
1-i||1-i|Created
3-s||3-s|Created
4-s||4-s|Created
2-f||2-f|Created
damage75||damage75|Created
1-f||1-f|Created
2-e||2-e|Created
2-n||2-n|Created
3-sw||3-sw|Created
1-w||1-w|Created
4-f||4-f|Created
2-i||2-i|Created
damage25||damage25|Created
</details>

**Comment by Lohikar** [comment]
Abandoned.

**Pull request closed without merging**
