### PR TITLE
Navigation consoles, 10mm pistols

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
Adds some nav consoles throughout the ship, changes the crew arm .45s to 10mm pistols

### CODE REVIEW

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
duplicate paperbins.

image

**Comment by TheDanseMacabre** [comment]
!review

**Review by SleepyGemmy — APPROVED** [review]
mapping looks good.

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
Why are the .45s being changed to 10mms? That's a gigantic nerf.

**Review by NonQueueingMatt — APPROVED** [review]
Guess we can give the 10mms a try.

**Review by Arrow768 — CHANGES_REQUESTED** [review]
I would still like the question by Matt answered.

**Pull request closed without merging**
