### PR TITLE
Loot & Plunder, For The Goddess - The Kazhkz Privateer Ship

### PR DESCRIPTION
**Pull request by RustingWithYou**
Adds a House Kazhkz privateer ship, complete with ghostroles. This was meant to be finished when the Horizon was still in the Badlands, but I forgot about it and then we had a mapping freeze. Better late than never, I guess.

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Comment by TheDanseMacabre** [comment]
might be worth putting the compact francisca on the little fighter thing, will probably look neater

**Comment by DreamySkrell** [comment]
image

- There should be more external airlocks on the ship than just the two little ones. So the ship can be entered from more than just one side, and does not require long spacewalks. Consider places I marked with red X.
- Add some lattices or catwalks on the outside so spacewalks around the straight and smooth hull are not pain.
- External airlocks should be the bigger two-tile wide door variants (tiny one tile external airlocks would be fine if they weren't the only ones there).
- Consider some more visual variety on the hallways. Now they're just really huge empty featureless hallways with the orange squares everywhere.
- Consider filling up the foamed up space (+empty hallways) with some "utility" or storage rooms that have little function, but may bring at least a bit variety.
- (You could ping me in the code_dungeon for help, or I could take your map, do some changes to show what I mean here and give it back later.)

**Comment by RustingWithYou** [comment]
> might be worth putting the compact francisca on the little fighter thing, will probably look neater

Probably, yeah. It didn't exist when I started this map, but I'll take a look at it.

**Comment by RustingWithYou** [comment]
> image
> 
> * There should be more external airlocks on the ship than just the two little ones. So the ship can be entered from more than just one side, and does not require long spacewalks. Consider places I marked with red X.
> * Add some lattices or catwalks on the outside so spacewalks around the straight and smooth hull are not pain.
> * External airlocks should be the bigger two-tile wide door variants (tiny one tile external airlocks would be fine if they weren't the only ones there).
> * Consider some more visual variety on the hallways. Now they're just really huge empty featureless hallways with the orange squares everywhere.
> * Consider filling up the foamed up space (+empty hallways) with some "utility" or storage rooms that have little function, but may bring at least a bit variety.
> * (You could ping me in the code_dungeon for help, or I could take your map, do some changes to show what I mean here and give it back later.)

Hey, I don't know your Discord @ but I do broadly agree, I remember I was thinking about the halls prior to the mapping freeze. If you were to make some of the changes you have in mind on the map I'd appreciate it

**Comment by DreamySkrell** [comment]
image

With the newest changes this looks much better I think, both visually and functionally. To make it even better, I would suggest the above stuff. It's just suggestions of course, you don't have to implement them.

**Review by NonQueueingMatt — APPROVED** [review]

**Review by DreamySkrell — APPROVED** [review]

**Review by DreamySkrell — APPROVED** [review]

**Pull request merged**
