### PR TITLE
Multi-Z Warehouse

### PR DESCRIPTION
**Pull request by Geevies**
* Added another level to the cargo warehouse.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by Arrow768** [comment]
Have you checked if the camera at the "north" side of the upper warehouse can reach all the way to the "south" ?

**Comment by Geevies** [comment]
There's two cameras, so I don't really consider that a problem

image

**Comment by Arrow768** [comment]
Didn't see that second camera.

**Pull request merged**
