### PR TITLE
Eridani Loadout Items Re-Additions

### PR DESCRIPTION
**Pull request by VisVirific**
* Re-adds most of the Eridani Private Military Contractor items that were in the loadout
* Adds a new PMCG Armband, made by the same person who organized and cleaned and reworked the current PMCG sprites, Memescope! (Thanks Memescope!)
* All loadout items are restricted in accordance to the faction they belong to, so all exclusive to the PMCG in general.
* Fixes some inconsistent naming with the PMCG items, also fixes the EPMC Asset Protection ERT IDs and uniforms.

**EPMC items in general** (plus PMGC Armband)

**EPMC items in the Loadout**

(Security Cadets can also choose the EPMC security uniforms. That gif is a bit outdated)

### CODE REVIEW

**Comment by VisVirific** [comment]
!review

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
1. EMT enroaches on Zavodskoi uniform palette. Please change this.
2. The PMCG beret and softcap is already very similar to the existing ones.
I can't see much of a difference to warrant their re-addition.
3. Modify the other uniforms to match the color palette. If you still desire the beret and softcap, change them too.
Palette to be used is existing PMCG blue and black shades found on warden hat.

**Comment by WickedCybs** [comment]
> 1. EMT enroaches on Zavodskoi uniform palette. Please change this.
> 2. The PMCG beret and softcap is already very similar to the existing ones.
>    I can't see much of a difference to warrant their re-addition.
> 3. Modify the other uniforms to match the color palette. If you still desire the beret and softcap, change them too.
>    Palette to be used is existing PMCG blue and white, and black shades found on warden hat.l brim.

Does enforcing them to look like they're wearing the generic PMCG attire/colours not totally defeat the point of the idea the PMCG is a varied and diverse group of contractors? The EPMCs are also plenty distinctive as is even compared to Zavodskoi in my opinion.

If it will be a big issue, I would run this by the community as they're the ones who will be seeing and using these items.

**Comment by VisVirific** [comment]
> 1. EMT enroaches on Zavodskoi uniform palette. Please change this.

Considering the EMT uniform is VERY DISTINCTLY different from ANY Zavodskoi style uniform, fully barring the reds just because another uniform uses feels like a bad faith take on the player's intelligence to distinct between uniforms.

>     2. The PMCG beret and softcap is already very similar to the existing ones.
>        I can't see much of a difference to warrant their re-addition.
The entire purpose of this PR is to re-add all of the items that were removed without any changelog or mention whatsoever, which will also fix the rest of the bugs of wrong pathing and naming of specific items because of the sudden removal and half assed readjustment to the affected items (considering the various bugfixes, documented or not).

>     3. Modify the other uniforms to match the color palette. If you still desire the beret and softcap, change them too.
>        Palette to be used is existing PMCG blue and white, and black shades found on warden hat.l brim.
> existing PMCG blue and white

That's why the PMCG labcoats are blue and black?

**Comment by RyverStyx** [comment]
> * EMT enroaches on Zavodskoi uniform palette. Please change this.
> * The PMCG beret and softcap is already very similar to the existing ones.
>   I can't see much of a difference to warrant their re-addition.
> * Modify the other uniforms to match the color palette. If you still desire the beret and softcap, change them too.
>   Palette to be used is existing PMCG blue and white, and black shades found on warden hat.l brim.

I think most people who play the game want these changes. The removal did not go over well with those who played these corps and should not have happened in the first place.

**Review by JohnWildkins — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
