### PR TITLE
Chem Adjustments, Fixes, and Additions

### PR DESCRIPTION
**Pull request by Doxxmedearly**
- rscadd: "Added Pneumalin, a medication that is targeted to fix lung damage, which should decrease reliance on peridaxon. Make it by using a 1:1:1 ratio of cough syrup, copper, and arithrazine. Overdoses above 15u, causing a dangerous drop in a person's pulse."
  - rscdel: "Removed inaprovaline. Replaced all bottles and syringes with norepinephrine. Itching and cramps are now relieved by norepinephrine."
  - tweak: "Dylovene is now less effective at treating hallucinations. Use synaptizine."
  - tweak: "Adipemcina no longer relies on or affects a person's nutrition level to function."
  - tweak: "Removed adrenaline effects from norepinephrine."
  - tweak: "Kelotane no longer processes if dermaline is in a person's system."
  - bugfix: "Dermaline now recovers the proper amount of burn damage, instead of being equivalent to kelotane."
  - bugfix: "Deltamivir will no longer cause organ-boiling fevers at 20u dosage. It will still cause a slight fever, so keep that in mind!"
TODO:
- [x] Test

### CODE REVIEW

**Comment by Doxxmedearly** [comment]
!wip

**Comment by Doxxmedearly** [comment]
!review

**Comment by furrycactus** [comment]
Just a couple of suggestions that have no real weight:
- Maybe swap out arithrazine for pulmodeiectionem, since it seems a bit odd that an anti-radiation medicine fixes lungs.
- Maybe name it something else like Pneumalin (thanks vrow), because Pulmodemcina is really similar to the lung-emptier reagent and might cause a lot of confusion.

**Comment by Doxxmedearly** [comment]
sure aight. Not that half the med combinations make sense anyway.

**Pull request merged**
