### PR TITLE
Replaces atmospherics sprites.

### PR DESCRIPTION
**Pull request by Belsima**
image

From the Eris and FTL.

Note that if these are unwanted, do NOT close the PR.

If Phoron is wanted to be orange, I can make it so. If the tanks aren't wanted, I can just make it the siphon and the scrubbers.

I just don't like the huge and oddly square tanks we have now.

### CODE REVIEW

**Comment by Lohikar** [comment]
Would prefer the canisters be removed from this, are you still up for editing this?

**Comment by Belsima** [comment]
Orange or purple canister?

**Comment by Lohikar** [comment]
Both, a revert to old canisters.

**Comment by TheGreatJorge** [comment]
If those canisters were reverted, then the only thing changed would be the big scrubber sprite, if I get that correctly. Which I have nothing against.

**Comment by skull132** [comment]
Down arrows have spoken, old cans better cans. Sorry!

**Pull request closed without merging**
