### PR TITLE
No Roundstart Nuke

### PR DESCRIPTION
**Pull request by Geevies**
* The merc nuke has been replaced with a combat exosuit.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by Snakebittenn** [comment]
A combat exosuit is infinitely worse than the nuke. A single ion rifle shouldn't defeat what should be a merc's endgame. You should start a feedback thread.

**Comment by Geevies** [comment]
Feedback thread: https://forums.aurorastation.org/topic/14656-no-roundstart-nuke-feedback/

**Comment by Arrow768** [comment]
Closing this PR after a discussion with the maintainers as not wanted.

**Pull request closed without merging**
