### PR TITLE
Fixes for PDA cartridge notifications

### PR DESCRIPTION
**Pull request by Bedshaped**
Includes a fix for #402

### CODE REVIEW

**Comment by Bedshaped** [comment]
I hope it worked this time... too tired to stick around.

**Comment by Bedshaped** [comment]
This includes a fix for #402

**Comment by NanakoAC** [comment]
You included your new IPC screen, thats cool. I'm sure nobody will have an issue with it. but it's a good idea to mention these things in the PR text, sneaking hidden changes in isn't a good idea

**Comment by Bedshaped** [comment]
Lord Lag said it was okay to make multiple changes in one PR. It's in the changelog but I thought the title would just be for the main things changed; I'll add everything in future.

**Comment by skull132** [comment]
Merge conflict present. Probably with sprite_accessories.dm coming from the merging of pull #393 .

DNM until resolved.

**Pull request closed without merging**
