### PR TITLE
Adds body markings, hairstyles, and a modified tie-hair verb to Skrell

### PR DESCRIPTION
**Pull request by Llywelwyn**
- rscadd: "Added the 'adjust-headtails' verb to Skrell, found in the IC tab."
  - rscadd: "Added the following body markings to Skrell: gills, beakmouth, tearstains, and dart frog markings."
  - rscadd: "Added the following hairstyles to Skrell: emo for regular and long headtails, behind for long headtails, and expressive headtails."
  - tweak: "Tweaked the order of headtail styles in the hair selection menu for better organisation. They're now organised by general length for ease when adjusting style."

image
image
image

### CODE REVIEW

**Review by RyverStyx — COMMENTED** [review]
Can you restrict the tear stains by subspecies possibly? (Only axiori get axiori and only Xiialt get Xiialt?)

**Comment by Llywelwyn** [comment]
> Can you restrict the tear stains by subspecies possibly? (Only axiori get axiori and only Xiialt get Xiialt?)

@RyverStyx,

For sure. Xiallt have access to "axiori eyes" body marking rn, so I didn't bother to restrict it since they could use axiori eyes + axiori tearstains that way. But I can make them species-specific if preferred.

**Comment by RyverStyx** [comment]
> 

You’re right 🤯 Keep Xiialts access to the axiori ones but remove the axiori access to the Xiialt one. Good catch!

**Comment by Llywelwyn** [comment]
!wip

**Comment by Llywelwyn** [comment]
!review

**Review by RyverStyx — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
