### PR TITLE
Stasis surgery, begone

### PR DESCRIPTION
**Pull request by sheeplets**
- Removes the ability to perform surgery on lifeform stasis units.

The ICU's stasis beds are almost a direct improvement over our dedicated operating tables, offering a 10x stasis factor. Both of them have a 100% success rate for surgical steps while the only thing the stasis units lack is their own anesthetic. That's something you can very easily remedy by dragging over an IV stand with a tank and mask hookup.

The fact that we figured out we could do it to begin with is cool, but people are neglecting the now-obsolete OR's in favor of operating on high-priority patients in the middle of the ICU instead. It's even something that gets prepped for at round-start. It's hilariously broken and needs to go.

### CODE REVIEW

**Comment by sheeplets** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]
This should probably be a science department upgrade to operating tables

**Comment by granodd** [comment]
> This should probably be a science department upgrade to operating tables

I could agree with this if only to help make science feel a bit more relevant in terms of doing research to upgrade things.

**Comment by desvenlafaxine** [comment]
They should be removed. They're a port from TG, where they're already too OP, but needed because everybody kills each other immediately. I don't think they fit our server, and lately, it's really hard to die during treatment unless neglected—make medical tough again.

I don't think nobody asked for them, they were just ported and some thought they were cool on the Aurora. However, back then they weren't mapped in: science had to make them. Now we have two of them right off the bat (even on TG, they need to be made in most maps) and we have a lot of gamer meds available too. They really are excessive.

**Review by SleepyGemmy — APPROVED** [review]

**Pull request merged**
