### PR TITLE
Replaced the /tg/ syndicate logo in the uplink with the Hammertail Smiths logo

### PR DESCRIPTION
**Pull request by Generalcamo**
This replaces the /tg/ syndicate logo in the uplink, which is not canon, with the newly added Hammertail Smiths.

Original logo by sketchalicious. SVG conversion by dessysalta with cleanup by GeneralCamo

image

### CODE REVIEW

**Comment by Generalcamo** [comment]
!review

**Comment by FluffyGhoster** [comment]
Antagonists aren't canon, so this isn't really a problem; also, why do you want to use the logo of a specific, canon, unathi faction for generic antag UI background?

**Comment by Generalcamo** [comment]
They're black marketeers that export their product across the spur. They are not unathi-specific, merely unathi-originated.

**Comment by MortalRed** [comment]
It also looks cooler than the Syndicate logo, which is good enough in my book.

**Comment by DreamySkrell** [comment]
unwanted - uplink should be as generic as possible

**Pull request closed without merging**
