### PR TITLE
Magiclash

### PR DESCRIPTION
**Pull request by Geevies**
* Added Magiclash, a gamemode where a wizard and a team of raider mages spawn.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Review by Amunak — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
I'm not keen on adding another wizard gamemode to the pile. It's already a very immersionbreaking, tiring gamemode and I cannot see this ending up as anything more than 'magiclash with 1 more wizard on the raiders' team' most of the time.

**Comment by Arrow768** [comment]
> I'm not keen on adding another wizard gamemode to the pile. It's already a very immersionbreaking, tiring gamemode and I cannot see this ending up as anything more than 'magiclash with 1 more wizard on the raiders' team' most of the time.

I concur with that.
We should finally get on with the gamemode rework instead of adding yet another mixed gamemode of questionable quality.

**Comment by NonQueueingMatt** [comment]
Reasoning above.

**Pull request closed without merging**
