### PR TITLE
Bugfix - yellow dress

### LINKED ISSUE #1075: Yellow Dress sprite non-functional
The jumpsuit item "yellow dress" appears to have no sprite showing when worn, and instead displays small red text by the head.
bugreport dress

### PR DESCRIPTION
**Pull request by SierraKomodo**
Fixes #1075

### CODE REVIEW

**Comment by SierraKomodo** [comment]
Wasn't able to find anything that referenced the bridesmaid_s sprite, and the sprite design clearly matched that of the dress_yellow icon sprite.

**Comment by SierraKomodo** [comment]
Could have sworn I told it to merge into development when I made this pull request

**Comment by SierraKomodo** [comment]
Ooookay so this pull request is doing some really weird things. Gonna close this, consult Skull, and re-post this after figuring out how these work and when I'm less tired.

**Comment by Bedshaped** [comment]
You need to rebase your branch

**Comment by SierraKomodo** [comment]
After discussing this with Skull, I've got this sorted out.

**Pull request closed without merging**
