### PR TITLE
No Heel Trip

### PR DESCRIPTION
**Pull request by Geevies**
* Running in heels will no longer trip you.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Review by Doxxmedearly — APPROVED** [review]

**Comment by Butterrobber202** [comment]
I really don't see a need for this. It's pretty easy just to take off the heels and run shoeless. Barring glass shards, it would be no issue.

**Review by JohnWildkins — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]
Technically alright, but will be discussed if that's wanted.

**Comment by Arrow768** [comment]
The PR has been discussed by the maintainers.

We have no interest in reverting this mechanic as it is easy enough to avoid tripping while running.
In addition it helps to limit certain unwanted character types.

**Pull request closed without merging**
