### PR TITLE
Toxins Remap

### PR DESCRIPTION
**Pull request by BurgerLUA**
Feedback Thread: https://forums.aurorastation.org/viewtopic.php?f=21&t=12025

Swag

# Overview
Remaps toxin to be a significantly more pleasing area to work in. Everything was tested thoroughly, save for the doppler array which should be easy to fix if anything is broken. 

## Noteworthy changes
- High power binoculars were added. No longer will you have to rely on cameras that will always break to do your testing.
- The APC was moved to be in a smarter location. No more will engineers have to make the long trek to repair that bomb range.
- The tachyon-doppler array was added for epenis purposes. It broadcasts its results over common, like other servers.

Swag2

### CODE REVIEW

**Comment by BotBOREALIS** [comment]
Icons with diff:
<details><summary>icons/obj/computer.dmi</summary>

Key | Old | New | Status
--- | --- | --- | ---
(old) engineeringcameras|(old) engineeringcameras||Removed
(old) engineeringcameras0|(old) engineeringcameras0||Removed
(old) engineeringcamerasb|(old) engineeringcamerasb||Removed
old_cons||old_cons|Created
old_cons-off||old_cons-off|Created
old_cons-broken||old_cons-broken|Created
</details>

**Comment by Arrow768** [comment]
_Looks a bit like featurecreep_

**Comment by BurgerLUA** [comment]
!review

**Comment by Arrow768** [comment]
make sure there is a holopad and a newscaster

**Comment by BurgerLUA** [comment]
https://i.imgur.com/eKiVZFg.png

Latest product.

**Comment by ParadoxSpace** [comment]
this shape is literally of a vibrator

**Comment by Pacmandevil** [comment]
It's clearly a reference to the cactus from the all time top selling video game super mario bros 2, Paradox. get your mind out of the gutter

**Pull request merged**
