### PR TITLE
Fixes NanoTrasen Typos

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR fixes the typo of "Nanotrasen" to NanoTrasen.
nothing should break as this PR doesn't touch any code or paths (except for a single sprite).

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Comment by SleepyGemmy** [comment]
!bugfix

**Review by KingOfThePing — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Review by listerla — APPROVED** [review]

**Review by Arrow768 — CHANGES_REQUESTED** [review]
Don't modify the existing changelog.

**Comment by SleepyGemmy** [comment]
> Don't modify the existing changelog.

it is intentional.

**Comment by SleepyGemmy** [comment]
> Don't modify the existing changelog.

it is intentional.

**Comment by SleepyGemmy** [comment]
> Don't modify the existing changelog.

fixed and addressed.

**Pull request merged**
