### PR TITLE
'Toggle Helmet' action button for voidsuits

### PR DESCRIPTION
**Pull request by JohnWildkins**
Voidsuits now have a 'Toggle Helmet' button just like Toggle Helmet Light or Toggle Magboots.

Full credit to Kasuobes and Baystation12/Baystation12#15923, for coming up with a much more elegant solution than I could in ten minutes.

t3IuKFipGt

### CODE REVIEW

**Comment by JohnWildkins** [comment]
!review

**Comment by Fire-and-Glory** [comment]
I don't think having a big button for removing your helmet on a space suit is the wisest choice, I gotta say, particularly next to all the buttons you want to use in space.

**Comment by NonQueueingMatt** [comment]
It has been on bay for a shitton of time and there hasnt been a single instance of misclicks.

**Comment by Fire-and-Glory** [comment]
I guess it'll be fine, then.

**Pull request merged**
