### PR TITLE
Unifies access amongst the heads of staff

### PR DESCRIPTION
**Pull request by Arrow768**
Removes the following access from the HoP:
- Forensics
- AI Upload
- Morgue
- Security Equipment
- Securit Holding
- Vault

Adds the following access to the RD:
- EVA
- Engineering
- Medical
- Construction
- External Airlocks

Adds the following access to the CMO:
- Engineering
- Construction
- Research

Adds the following access to the CE:
- Research
- Medical

### CODE REVIEW

**Comment by skull132** [comment]
buffs RD. Can agree.

**Comment by Juani2400** [comment]
What about maintenance access? Some heads have it, some don't. CMO doesn't have it, while its paramedics do.

**Comment by Arrow768** [comment]
The CMO already has maint access.

**Comment by TheGreatJorge** [comment]
I didn't play in a long time... But for example to me, this feature looks like one of those that could use a test run and people giving feedback after that. Because who knows how this can turn out.

**Comment by OneOneThreeEight** [comment]
Seems fine.

Some maintenance doors are locked behind another form of access the CMO is seemingly lacking for some airlocks, which is why the CMO finds themselves often trapped in maintenance.

**Comment by skull132** [comment]
Submitted to admins for review.

**Pull request merged**
