### PR TITLE
Juggernaut Buff

### PR DESCRIPTION
**Pull request by NanakoAC**
Result of observing a cult round today, where an outnumbered cultist in a corner managed to create a juggernaut, only for it to be unceremoniously gunned down by a detective with a laspistol.

Me and garnascus agreed these things are far too weak

Increases their health from 250 to 400

Reduces the damage they take from reflected lasers:
Juggernauts have a built in laser reflecting mechanic, which causes beams to bounce off them. its pretty neat. but they still take half the damage and it wasnt saving him even with almost every shot reflected.

So ive reduced the damage they take from those, from 50% to 20%

This buff is more conservative than i had planned, but it should suffice combined with the laser rebalance in another PR

### CODE REVIEW

**Comment by Arrow768** [comment]
Currently: 250hp / (40*0.5) -> 12.5 Shots needed
After the Buff: 450hp / (30*0.2) -> 75 Shots needed

**Comment by NanakoAC** [comment]
what are these numbers, i didnt use 450

**Comment by skull132** [comment]
He meant 400.

Still goes to 66.(6), though.

**Comment by LordFowl** [comment]
66 laser shots is absolutely ridiculous. That is several laser rifle's worth of ammunition, all for one unit. (This is of course presuming that every shot hits in the first place, and that the juggernaut never uses its already extant shield ability, etc etc.)

**Comment by skull132** [comment]
Inclined to agree.

Also, cult quite regularly has more than 1 of these.

**Comment by NanakoAC** [comment]
i'm aware thats a lot. the idea here is - don't use lasers on them. The numbers are also wrong though, the reflection has a (80 - round(P.damage/3)) chance of triggering, so some full damage shots are getting through. ill do some math..

**Comment by NanakoAC** [comment]
More accurate (not perfect) numbers, factoring in the chance for reflection to not proc
pre buff:  100 = 26.6 dpshot, 9.39 shots to kill
post buff 13.2 dpshot, 30 shots to kill

This doesnt seem bad to me. That's 1.5 full laser rifles, if you're bad enough to use a weapon that they're strong against. They have no special resistance to ballistic weaponry, and will still go down somewhat quickly if you bring out an automatic rifle.

**Comment by LordFowl** [comment]
With a laser rifle with 30 damage, as proposed by your other PR, that would be a 70% chance of reflection, which is very high indeed. Despite their supposed weakness to lasers that exists already, juggernauts have proven themselves more than able to kill. I do not think such a radical increase in their ability is really necessary.

**Comment by NanakoAC** [comment]
i accounted for that and factored it in, the numbers above reflect all of the things you just said

**Comment by skull132** [comment]
> pre buff: 100 = 26.6 dpshot, 9.39 shots to kill
> post buff 13.2 dpshot, 30 shots to kill

Still seems a little high. There's a set of calculations you can run to figure out how likely someone is to kill a jugg with that many shots, provided the hit chance is 30% success rate.

**Comment by NanakoAC** [comment]
yes it is high, thats the intention. Its meant to be prohibitively high so that you use a different weapon. I'm not really concerned with making them killable by lasers. The reflection mechanic provides a solid IC explanation for why shooting it isn't working, so it doesn't feel incongruous (compared to say, pumping lasers into a blob)

**Pull request merged**
