### PR TITLE
Planes & Layers part 1: The Re-Layering

### PR DESCRIPTION
**Pull request by Generalcamo**
This is part 1 of a project to, eventually, bring the render planes system from /tg/ and bay into Aurora. This is a prerequisite and blocker for many things the development team and community want to have, and this was long overdue.

Many objects have been re-assigned layers, which are now thoroughly defined. Maps have had their custom layer defines purged, as we should be moving away from this in favor of saner definitions in the base items.

This should be a test-merge due to the sheer amount of layers changed, which will very likely create issues that I cannot possibly discover and debug in a reasonable amount of time myself.

### CODE REVIEW

**Comment by Generalcamo** [comment]
!wip

**Comment by Generalcamo** [comment]
Probable merge conflict with #16104, as that makes changes to layers. This should not be testmerged until that PR is finished and merged.

**Comment by Generalcamo** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
inactive

**Pull request closed without merging**
