### PR TITLE
Removes Limitless & Hollow Purple

### PR DESCRIPTION
**Pull request by RustingWithYou**
Both the Limitless psionic level and the funny anime reference power were added for adminbus, but can be accessed in normal gameplay through various bugs. I have tried and failed to find the source of or fix these bugs, so I made this PR to prevent John Shitter from getting the 'end your round and everyone in the immediate vicinity's round' power.

Partially addresses #17043, though stronger than intended powers can still appear for borers.

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Comment by FluffyGhoster** [comment]
Removing the ability isn't a proper solution to it being pickable to those who should not be able to

**Comment by granodd** [comment]
I'd suggest commenting it out for the time being until a fix is found.

**Comment by RustingWithYou** [comment]
> Removing the ability isn't a proper solution to it being pickable to those who should not be able to

I said that, but ultimately I have been unable to find a fix for this and the ability itself is something that can be removed without much consequence. This doesn't fix the root problem, but it stops the worst symptom of it - namely players accidentally getting a cool new ability and killing themselves + several other people with it, as happened in a round earlier today.

Removing a power which isn't meant to appear outside of adminbus is not a huge loss, given that admins already have any number of verbs for killing people/blowing things up.

**Comment by RustingWithYou** [comment]
closing as the bug was found

**Pull request closed without merging**
