### PR TITLE
Renames the Rescue Axe

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR renames the rescue axe to "emergency multipurpose axe".

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Comment by NonQueueingMatt** [comment]
Not sure what the point is. The new name is unwieldier and uglier.

**Comment by SleepyGemmy** [comment]
not pursuing this anymore.

**Comment by SleepyGemmy** [comment]
not pursuing this anymore.

**Pull request closed without merging**
