### PR TITLE
VueUI Conversions and Style Tweaks

### PR DESCRIPTION
**Pull request by MarinaGryphon**
* Vue-ifies portable air pumps, APCs, SMES units, and the AI/admin Supermatter Crystal monitor. A lot of them have been spruced up as well!
* Adds an optional min/max button to VueUI numeric inputs.
* Fixes some missing formatting for VueUI progress bars.
* FontAwesome icons in VueUI windows are now fixed-width. Thanks for pointing out the issue, Geeves!
* VueUI group-item elements now have their labels top-aligned.
* VueUI windows now have a transparent background box to provide more visual contrast. This might cause issues with window sizes; please report them if encountered so the default sizes can be adjusted.

### CODE REVIEW

**Comment by MarinaGryphon** [comment]
!review

**Comment by MarinaGryphon** [comment]
!wip

**Comment by MarinaGryphon** [comment]
!review

**Review by skull132 — APPROVED** [review]

**Comment by Geevies** [comment]
>
>FontAwesome icons in VueUI windows are now fixed-width. Thanks for pointing out the issue, Geeves!

i did? wild

**Review by Geevies — APPROVED** [review]

**Pull request merged**
