### PR TITLE
Update reftracking

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Updated the reference tracker, it should now be faster

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by LemonInTheDark** [comment]
this is an uncredited port of my work on /tg/. please port my work but also you should reference the pr in some way, both like, for the license to make sense (crediting) and so the sources on things don't get lost to the sands of time.

**Comment by FluffyGhoster** [comment]
> this is an uncredited port of my work on /tg/. please port my work but also you should reference the pr in some way, both like, for the license to make sense (crediting) and so the sources on things don't get lost to the sands of time.

Both codebases are AGPL3 and your TG PR (80443) doesn't specify any additional requirement, ontop of that the TG repo readme states:

`All code after [commit 333c566b88108de218d882840e61928a9b759d8f on 2014/12/31 at 4:38 PM PST](https://github.com/tgstation/tgstation/commit/333c566b88108de218d882840e61928a9b759d8f) is licensed under [GNU AGPL v3](https://www.gnu.org/licenses/agpl-3.0.html).`

So I do not believe (but I'm not a lawyer) that there's any requirement for crediting in the AGPL3 otherwise, you released your code without any supplement listed in §7 (https://www.gnu.org/licenses/agpl-3.0.html); it's a good work hence why I ported it back then and obviously we're all grateful for it, but it seems you're trying to say I must have done something different when it doesn't appear I had any licensing need to, the license already makes sense as-is I believe - feel free to write your PR in a comment on the file to link it, I don't have an issue with that, only the framing that "this is an uncredited port" and "for the license to make sense (crediting)" seems to imply, to be clear.

**Comment by LemonInTheDark** [comment]
putting aside the mess of not knowing where code comes from, you needed to credit me in some form yes. AGPL code is not CC-0, the author of a block of code still holds copyright (in most places and unless they otherwise release/transfer it) to that code. that means they can relicense it, etc etc. this is not the case for you, because you didn't write this, I did, and I haven't done any of those things.

AGPL is built off copyright law, it places restrictions on how a "thing" (code) can be used "enforced" by the copyright of the author (in /tg/'s case because we do not use a CLA to transfer copyright to one organization, "the author" is anyone who has worked on the relevant code). it is not creative commons.

**Comment by FluffyGhoster** [comment]
> putting aside the mess of not knowing where code comes from, you needed to credit me in some form yes. AGPL code is not CC-0, the author of a block of code still holds copyright (in most places and unless they otherwise release/transfer it) to that code. that means they can relicense it, etc etc. this is not the case for you, because you didn't write this, I did, and I haven't done any of those things.
> 
> AGPL is built off copyright law, it places restrictions on how a "thing" (code) can be used "enforced" by the copyright of the author (in /tg/'s case because we do not use a CLA to transfer copyright to one organization, "the author" is anyone who has worked on the relevant code). it is not creative commons.

It is my understanding that by default AGPL3 does not require any crediting, you can add a clause to require it as seen in §7 if you are the material holder, however said code was already released under AGPL3 without said clause, and I think therefore it wouldn't apply here either, the material is already released, furthermore §7 indicate:

`If you add terms to a covered work in accord with this section, you must place, in the relevant source files, a statement of the additional terms that apply to those files, or a notice indicating where to find the applicable terms.`
`Additional terms, permissive or non-permissive, may be stated in the form of a separately written license, or stated as exceptions; the above requirements apply either way.`

Which is not present in the TG's file nor the original PR you're referring to, and I do not believe it's possible to alter the terms after the release, but again I'm not a lawyer - would you please source in the AGPL3 license where it requires said accreditation? Because I am not seeing anything aside from said paragraph, that you seem to have elected not to use upon the release of said material. It's true you can relicense it, but you can't un-license it from the AGPL3. This is to my understanding outlined in the AGPL3 §2 at the following line:

`All rights granted under this License are granted for the term of copyright on the Program, and are irrevocable provided the stated conditions are met.`

I would therefore intuit that while it's true you can relicense the parts you develop, that doesn't remove the AGPL3 license to which they are already under once they're released with said license, which outside §7 as per above do not seem to require any accreditation, would you please reference what part of the AGPL3 outside optional §7 clauses that you do not seem to have conveyed with the original work require crediting? I will be happy to edit the PR with a link to your original PR either ways, but I firmly reject an accusation of wrongdoing as it doesn't appear the license you licensed said work under supports the apparent claim that I have violated said license.

**Comment by Geevies** [comment]
auroradev here, i believe we should credit work regardless because it's the good and moral thing to do. SS13 only succeeds because people across multiple forks work together

**Comment by JohnWildkins** [comment]
> this is an uncredited port of my work on /tg/. please port my work but also you should reference the pr in some way, both like, for the license to make sense (crediting) and so the sources on things don't get lost to the sands of time.

First of all, apologies on behalf of the Aurora team for not catching this in the first place.

I would like to state for the record that regardless of whether or not there is a legal requirement to credit PRs in AGPL repos, it is also explicitly mentioned in our contributor guidelines:

> As a courtesy, attribution of authorship is also encouraged, even if the license of the content does not require this outright. Generally this is done in the PR by declaring the source of the material, the author(s) (if known), and adding similar attributions to the relevant changelog entry (if applicable). This may be both done in the author field or within the plain text describing the change itself.

If I may editorialize personally on top of that, crediting other people's work is just the right thing to do, too. I have gone ahead and edited the PR title and description to make the attribution clear.

**Comment by FluffyGhoster** [comment]
I have specified no less than twice, in both comments, that I'd be more than glad to have the two PRs linked and that I was specifically addressing the implication of it being a license violation not to. Trying to pass "As a courtesy" and "encouraged" as if a requirement is just the cherry on top of trying to frame my words as if I was addressing something else, which I find particularly interesting to be combined with the moral posturing, especially so when you realize that the PR specifically states to be updating something that is already credited to the original codebase in the previous PR, which already implies it's an update coming from said codebase. I do not port PRs in particular, just look at the file diffs when doing updates (and/or just copy the files), which is what a sane person should do to avoid porting a specific and possibly bugged version instead of the latest iteration of the code. I have ported no PR in particular, just the updated version of the file at the time that was available in the same source where the code was initially ported from, which as stated in the initial port, it's TG. I would suggest to update the contribution guidelines with "must" or "have to" if that's wished to be an explicit requirement, in order to avoid confusion in the future, but that seems rather silly given you'd have to trace back each PR that lead to the current version of the file(s) you're porting; if you think otherwise, I can only wish you luck for tracking back all the PRs that made the code that ends up in a PR like the VueUI -> TGUI migration that was done back in 2023, which also doesn't seem to link to any PR (or even indicate any particular codebase) as a source.

Best.

**Pull request merged**
