### PR TITLE
Total Command Remap + Dual Consulars and Reps

### PR DESCRIPTION
**Pull request by Eyeveri**
Remaps every single section of the Command "Department" without touching the Helm area too much, or the bridge break room. 
- Places the Conference Room where current Captains office is.
- Places the Captains office where current Conference room is.
- Connects XO's office to the bridge.
- Creates two Corporate Representative Offices and Slots. Only negative is that there was no way to have both be able to see the stars.
- Creates two Consular offices that are publicly viewable for the purpose of flags. 
- Creates a better organized and aesthetically pleasing supply closet for the bridge, separates the guns, armor, and adds stun batons to bridge defense equipment since the Atrium is semi-public. Adds 3 .45 pistols to the closets and 6 .45 magazines. 
- Creates a semi-public area for the bridge. Dubbed the "Command Atrium", this space is public on Green alert. 
- Creates a new meeting room specifically for CCIA purposes, out of request from the entire CCIA team. This area has its own blast doors, is radiation proof, and has two bolting doors to prevent unintentional antagonist involvement in interviews. 
- Moves Telecomms to be by D3 engineering. I am happy to make it "more connected" to Engineering if requested. 

The project thread is here - [https://forums.aurorastation.org/topic/19508-feedback-for-command-remap-not-bridge/#comment-170751](url) 

EntireRemap

Captains office.
Captains Office

Command Atrium
Command Atrium

Conference Room
Conference Room

Consular Office Alpha
StrongDMM-2023-12-08 14 35 06

Consular Office Bravo
StrongDMM-2023-12-08 14 34 01

HRA/CCIA Office
HRA Area

Representative Office Alpha
Representative A

Representative Office Bravo
Representative B

Supply Room/Connection from Captains office to Bridge
Supply Closet

XO's Office
XOs Office

Telecommunications 
Telecomms

### CODE REVIEW

**Comment by Eyeveri** [comment]
!wip

**Comment by Eyeveri** [comment]
!review

**Review by FluffyGhoster — APPROVED** [review]
Code LGTM, I think it's good enough to be testmerged map wise

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Arrow768 — CHANGES_REQUESTED** [review]
There are some issues with the areas at tcoms:
image

The surface civilian substation is only connected to the engineering break room and the "engineering ladder shaft" maint section.
image

The "engineering ladder shaft" maint seciton  seems rather large and rather unintuitively layed out (i.e. why is it not covering the two tiles infront of the left airlock?)
image

The outer door (3) of the HRA lobby is also triggered by the bolt button.
Imho only the Inner doors (1) and (2) should be triggered
image

**Comment by Arrow768** [comment]
The routing of the main grid is also not too great (going through the engineering break room and coming back out through the shield room).

Ideally the maint corridorhould be widened to 2 tiles and the green/red wire run next to each other.
For that you have to shave a few tiles of the washroom or the engineering breakroom
image

**Comment by Eyeveri** [comment]
> The routing of the main grid is also not too great (going through the engineering break room and coming back out through the shield room).
> 
> Ideally the maint corridorhould be widened to 2 tiles and the green/red wire run next to each other. For that you have to shave a few tiles of the washroom or the engineering breakroom image

I did not design the breakroom wiring. I only connect this to the mainline in the shield room. 

I have a remap planned for the entirety of D3 maintenance to make it more wire friendly. I'm working on a bandaid right now.

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
