### PR TITLE
Security areas mapping improvements

### PR DESCRIPTION
**Pull request by Amunak**
* Split upper security (investigations & training) into multiple per-room areas as it should be. Added light switches and APCs for those areas.
* The room with stairs to Training is now a part of the Training area, not Brig.
* Evidence Storage is now its own area as well.
* From security/brig there were two rooms split: the 'control room' and 'processing'. Also added APCs.
* Added back the option to toggle lights to most Security areas (basically everything but places where prisoners are held).
* Added/modified area icons for most of the areas mentioned above for easier mapping.
* Removed the unused Security Hallway area.

#### Main level
aurora-sec4
#### Upper level
aurora-sec5

### CODE REVIEW

**Comment by Amunak** [comment]
!review

**Comment by Amunak** [comment]
Actually looking at the screenshots now maybe Interrogation should also be split and the two middle security offices as well.

**Comment by fernerr** [comment]
Security running out of power quickly isn't the worst of things, be it from sabotage or otherwise. Though that is a bit of an unrelated issue perhaps. I feel a lot of small rooms can take hours to run out of power when it's cut.

**Comment by Amunak** [comment]
That's actually a really good point I haven't thought of.

Having proper areas has nice advantages like being able to jump there, having better alerts, the lighting, etc. But I'll happily add (and map in) APCs with a very small battery (perhaps `/obj/item/cell/crap`?) for APCs that just have a single room with few stuff in it or a corridor with a single light or whatever.

**Comment by Amunak** [comment]
So I just added apc/low with a regular power cell (1000 charge vs. the usual 5000) and mapped it into the security areas (offices, all the upper level and the "control room" and processing).

Eventually this should probably be in all smaller, less important rooms with not much equipment. It makes it so that the average office would run out of power in about 20-30 minutes (not caring about the power saving mode). This would also make it so that power outages potentially have consequences.

**Review by fernerr — APPROVED** [review]
Wonderful stuff

**Review by Geevies — APPROVED** [review]

**Pull request merged**
