### PR TITLE
Do not Nerf pylons, sadly, and other things

### PR DESCRIPTION
**Pull request by Alberyk**
-nerfed overall accuracy, and removed burst, of the scout rifle
-removed a fuckton of white space from nanacode
-should fix ipcs being stung by changelings at long last

### CODE REVIEW

**Comment by NanakoAC** [comment]
Pylons have barely been out for a couple days, they have a plethora of weaknesses, and i see no justification for nerfing them.

But that aside, any balance adjustments should be done gradually. You have literally reduced their DPS by 80%. Thats not happening.

I strongly advise you remove pylon changes and let me handle balancing them.
If you absolutely feel the need to nerf them you're going to have to justify that

**Comment by LordFowl** [comment]
Let's not play the false tag game. You have a review button for a reason.

**Comment by SonicGotNuked** [comment]
I think this insta nerf to shit is a over reaction, pylons take a LONG time to kill when they are not charged. Both rounds I did this, people tended to just rush in expecting not to get shot down. Security had no co-ordination with this and I seen most of them sit around and fire lasers at the pylons.

**Comment by Alberyk** [comment]
It is not common knowledge that pylons are immune to laser, besides, even not an officer wearing full ablative and an energy shield could stand some seconds of being fired upon. And security has little to no ways of fighting the pylons since they will snipe anyone from afar at this point.

**Comment by OneOneThreeEight** [comment]
"You have literally reduced their DPS by 80%. Thats not happening."

This is not a competitive Tower Defense game, this is a heavy RP SS13 server. Adjust mechanics to benefit roleplay, not re-shape the entire balance of a game mode to further make facing off against the cult an impossibility.

**Comment by SonicGotNuked** [comment]
The only thing security did was rush the defenses head on, they have not done anything to try and prevent that. Security constantly rushes the cult and ends up winning 70% of the time due to them having ranged weaponry. There is ways to face the cult and it does not include rushing them. Give it some time and allow it to evolve to a greater stand point, the pylons should not be turned into a minor inconvenience to security (also no one tried venting engineering)
I will also point out that if your lasers are making them blue and hit harder, I think you should tell everyone not to use lasers.

**Comment by NanakoAC** [comment]
I am going to handle rebalancing pylons, gradually and carefully. Theres no farther need for the proposed changes to them in this PR

**Comment by skull132** [comment]
For the time being, remove the alterations to pylons. We'll see how Nanako's PR handles it.

Though, you have no idea how badly I want to merge the PR right now just because of this:
`-removed a fuckton of white space from nanacode`

**Pull request merged**
