### PR TITLE
Generic xenofauna names

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
Just a silly little PR that makes the generic xenofauna have generic names instead of the nonsense words they have currently.

### CODE REVIEW

**Comment by JohnWildkins** [comment]
but the sovl

**Comment by TheDanseMacabre** [comment]
!review

**Comment by WickedCybs** [comment]
You hate soul.

**Review by Alberyk — APPROVED** [review]

**Comment by githubuser4141** [comment]
This is just sad, people say "no sovl" in a jokey sense, but this is pretty disapointing because it removes mystique and RP value from simply *looking* at a creature. The original names evoke a sense of wonder-- Is it a local classification, from the first colony to come across these creatures? Is it a global classification from a non-Common speaking faction and perhaps the translation didn't come across so well?

The new names come across as generic video-gamey names. "Rammer", oh, I wonder why it's called that. Probably because of it's tusk and tendency to charge at things? "Snow rodent", get it? It resembles a rodent and lives in the snow? The server CEV Eris did something similiar to this-- removed the xenofauna event completely, which killed a lot of "RP for the sake of RP"-- I remember quite a few times where I'd comment on the funny-looking creatures coming out of a vent and offer to sell them or keep them as pets. The devs removed it and replaced it with either: harmless mice, or 100% hostile spiders/drones/mobs because it "didn't fit our setting". Sometimes good RP can happen from harmless, weird events as long as they're not 'WaCkTaStIc' or break the setting.

**Comment by TheDanseMacabre** [comment]
do you play aurora

**Review by NonQueueingMatt — APPROVED** [review]

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
...Should probably keep the old names in some way, maybe in the extended desc or whatever.

Perhaps as a species specific coinage or whatever.

Either that or change the path names as well. 
Because it's going to be moderately annoying to spawn them in future or debug when someone reports a bug with a "snow rodent" and then it's called diyaab in the files and it's a pain in the ass.

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
Change the types to match the new names.

**Pull request closed without merging**
