### PR TITLE
Update, JUL2017

### PR DESCRIPTION
**Pull request by skull132**
Memes are becoming dreams.

### CODE REVIEW

**Comment by skull132** [comment]
THE DREAM IS FUCKING DEAD.

EVERYONE GO HOME.

**Comment by Lohikar** [comment]
At last I have been freed from ZAS hell.

**Comment by Lohikar** [comment]
newnewmap when

**Comment by skull132** [comment]
my browser hangs for a few seconds while loading this, even without the diffs showing.

**Pull request merged**
