### PR TITLE
fights lag by killing the sun

### PR DESCRIPTION
**Pull request by JohnWildkins**
fortnite battle pass
i just lagged out my [redacted]

### CODE REVIEW

**Comment by JohnWildkins** [comment]
!review

**Comment by JohnWildkins** [comment]
!review

**Comment by BLUNTFORCE420** [comment]
WOO LETS GO JOHN

**Comment by MortalRed** [comment]
Assunzione origin story.

**Review by NonQueueingMatt — APPROVED** [review]

**Review by FluffyGhoster — APPROVED** [review]

**Pull request merged**
