### PR TITLE
Investigators Can Use the Holobadge

### PR DESCRIPTION
**Pull request by SleepyGemmy**
title. likely an oversight and marked as a bugfix.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Review by mikomyazaki — APPROVED** [review]

**Comment by SleepyGemmy** [comment]
!review

**Comment by SleepyGemmy** [comment]
!bugfix

**Comment by SleepyGemmy** [comment]
bot is dead, ill run the commands later.

**Comment by SleepyGemmy** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]

**Pull request merged**
