### PR TITLE
Password Protected Files

### PR DESCRIPTION
**Pull request by dapocalypse**
This PR adds password protected files. When creating a file an additional prompt will come up. This will ask if you would like to set a password. If left blank a password will not be set and the file will function normally. If a password is set, when viewing, cloning, renaming, or deleting a file, the password prompt will again come up asking for the previously set password. When cloned, the cloned file retains the password.

Also because i dont know github, everything i merged into my master is also here

### CODE REVIEW

**Comment by Arrow768** [comment]
Should target development

**Comment by Karolis2011** [comment]
Please retarget development, such change is inappropriate for master.

**Comment by dapocalypse** [comment]
Hmm? Why is it adding everything i merged into me?

**Comment by dapocalypse** [comment]
Closed so i can figure my shit out

**Pull request closed without merging**
