### PR TITLE
Maybe we should use #defines for reagent IDs?

### PR DESCRIPTION
**Pull request by skull132**
So. Here's my logic. Typos in reagent IDs suck. Yes they're safely runtimed but it's a butt if one typo gets in and is not detected in live code unless via some obscure runtime that happens once a month. In general, we use #define's for shit like this.

So here I am, using defines. Python was utilized for the initial sweep.

Feedback on this before proceeding? Obviously there's more to replace.

### CODE REVIEW

**Comment by BurgerLUA** [comment]
I'm inclined to disagree with this concept. While it does prevent errors and mistakes, I think contributors should learn to just double-check their code and actually test it.

**Comment by skull132** [comment]
erm. Your argument seems to boil down to, "Well, we have this way of negating errors, but we should just try to make sure that people are more diligent instead." IMO that's a flawed mentality, specially when the fix is this unobtrusive to the process of actually making changes.

**Comment by LordFowl** [comment]
This seems to be the standard use of #defines. I see no reason not to update the system. Especially since recent PRs *cough*burger*cough* have had issues with misspelled reagent IDs.

**Comment by BurgerLUA** [comment]
Which ones? I think there was only 1 PR from a previous devmerge that spelled a reagent wrong.

**Pull request closed without merging**
