### PR TITLE
Crew Armory Tweaks

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
Increased the number of vests to six, changed them to the generic type, changed the helmet sprite, added armbands, and fixed the FAKs being empty.

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Comment by NonQueueingMatt** [comment]
Why are we replacing the helmets with hardhats tho?

**Comment by TheDanseMacabre** [comment]
> Why are we replacing the helmets with hardhats tho?

It's mostly because the generic vest doesn't pair well with actual helmets. I've asked Kyres for the generic helmet sprite that he made but was never implemented but he's not sure if he still has it. So you can consider the hardhats a placeholder until I can whip up something else.

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
why are you sanitizing every variable on the map?
if this was unintentional, it can be turned off in File -> Preferences -> Sanitize Variables (unchecked), in strongdmm.

**Comment by KingOfThePing** [comment]
> > Why are we replacing the helmets with hardhats tho?
> 
> It's mostly because the generic vest doesn't pair well with actual helmets. I've asked Kyres for the generic helmet sprite that he made but was never implemented but he's not sure if he still has it. So you can consider the hardhats a placeholder until I can whip up something else.

If yoou are missing sprites or they are just not finished yet, then this should either be a draft or WIP, and not be merged until it's done. Replacing helmets with hardhats "as a placeholder" is probably the weirdest reason ever. Finish it when it's done, not with placeholders.

**Review by Arrow768 — DISMISSED** [review]
I concur with @KingOfThePing.

Either keep the current helmet as is (even if they are mismatched; its the crew armory, who cares) or wait until the actual sprites are implemented.
DNM until one of these options is implemented

**Comment by TheDanseMacabre** [comment]
image
Addressed. The generic helmet item now has a palette to match the generic vest.

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
