### PR TITLE
Small malfunction tweaks

### PR DESCRIPTION
**Pull request by printer16**
This basically makes it harder for the AI to go NUKEM and easier to fake things like announcements and code changes. I increased the system override from 2750 to 5000 in terms of research points, and decreased machine override to 5000 as well as reducing the forcefield research costs. The turret hardware has been buffed slightly (More turret health) to make it (possibly) worthwhile. The Elite and Advanced encryption hacks have had their fail chance slightly reduced. I plan on possibly adding some new hardware for malfunction in the future such as EMP resistant electronics or possibly an interception research tree that allows the AI to intercept messages to centcom. This is to get a general feel of what the balance for things should be.

### CODE REVIEW

**Comment by skull132** [comment]
This may conflict up the ass with #1285 . We'll see.

**Comment by printer16** [comment]
Tried letting people who read it know that is now more viable to go for different research options and try new gimmicks with the hacks instead of nuke, I can broaden it up though if you want.

**Comment by CakeIsOssim** [comment]
EMP resistance is basically already a hardware - the alternate power unit, or whatever it os. Prevents death due to loss of power, which is more likely to kill the AI than the damage the EMP inflicts (which is already considerably low). Heavy EMP will do 10% integritt, and light will do 5%. The rest of this looks alright, though.

**Comment by printer16** [comment]
EMP resistance electronics is not within this PR.

**Pull request merged**
