### PR TITLE
Dominian Dionae may now access Dominian clothes

### PR DESCRIPTION
**Pull request by listerla**
The selections now have the commoner dresses (which IIRC they could access before) and such in the same selection as the noble items.

### CODE REVIEW

**Comment by listerla** [comment]
!review

**Comment by listerla** [comment]
!bugfix

**Review by SleepyGemmy — APPROVED** [review]

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
unintended file added: `code/modules/client - Shortcut.lnk`.

**Review by SleepyGemmy — APPROVED** [review]

**Comment by listerla** [comment]
Probably remove bugfix tag as well if it's lore impact; I was under the impression this was unintentional. Sorry!

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
