### PR TITLE
Skrell Stuff

### PR DESCRIPTION
**Pull request by Geevies**
* Added some Warbling event skrell stuff to the game.

I made some tweaks and changes here and there, mostly bugfixes. I have absolutely no idea who added what, it happened too long ago, so if you want changelog credits, post here or DM me.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Review by Doxxmedearly — APPROVED** [review]

**Comment by TheDanseMacabre** [comment]
Wasn't there a non-hardsuit set of Jargon armor? It might be worth adding it too, because both of these suits seem too strong for normal use.

**Comment by Caelphon** [comment]
> Wasn't there a non-hardsuit set of Jargon armor? It might be worth adding it too, because both of these suits seem too strong for normal use.

It isn't being used normally (as it requires to be spawned in I believe) and is meant to be for the Skrell Arc.

**Review by skull132 — APPROVED** [review]

**Comment by skull132** [comment]
Bypassing merge delay because event soon:tm:.

**Pull request merged**
