### PR TITLE
Gun overhaul

### PR DESCRIPTION
**Pull request by Re2Taz**
Rework on all current guns within Aurora.

### CODE REVIEW

**Review by fernerr — COMMENTED** [review]
I'd rather see this as a feature that can be optionally added for any airlock, rather than it being a snowflakey special one. Like with keypad maglocks.

**Comment by Re2Taz** [comment]
It's the foundation for keypad airlocks. People can add that. It's just very neat having the option as a mapper to put in a keypad door, for a ruin or for civilian housing etc.

**Comment by TheDanseMacabre** [comment]
While I do like what you've done with some sprites, I also believe that some changes are a net detriment. This PR is absolutely going to need a feedback thread on the forums, please.

**Comment by Alberyk** [comment]
Why did you totally change the direction of the pr instead of making a new one?

**Comment by NonQueueingMatt** [comment]
Inactive author.

**Pull request closed without merging**
