### PR TITLE
Poison Balance Tweaks

### PR DESCRIPTION
**Pull request by NanakoAC**
A small tweak patch to fix some odd balancing issues with certain chems. Generally homogenising the poison chems to have less instakill options and see a little more use from the less common ones

Majorly nerfed polytrinic acid, because it was lethal at 5u dose
Majorly nerfed mercury, it was a 30 second kill and its available in the dispenser.  

Minorly nerfed a couple of other things, mostly standardisation - factoring in removed where it wasn't before. doing flat effects every metabolism tick is generally bad. This was the issue with mercury.

Buffed the base metabolic rate of poisons. its still generally extremely slow

Buffed lexorin by removing the (irrelevant) brute damage and adding some extra oxyloss instead (doesn't heal due to the losebreath effect). This should make the changeling's death sting not entirely worthless.

### CODE REVIEW

**Comment by printer16** [comment]
Just a suggestion. Could you possibly reduce the stupid strong effects of Potassium Chlorophoride? "Takes 200 seconds to metabolize a single unit, making this a very effective long-lasting paralytic." all the while dealing 10 toxin per unit and 2 suffocation. Think about this-- 15 units is enough to keep someone out for 50 minutes. That is stupidly strong and it's pretty easy to make.

**Comment by Lohikar** [comment]
Feature, target development please.

**Comment by NanakoAC** [comment]
nope, bugfix. This PR is in response to an issue that happened last night, where someone was fed a tiny dose of mercury (by accident) and died in under a minute, due to the oversight of Removed not being factored into its brain damage

**Comment by NanakoAC** [comment]
@printer16 i'm not sure about chlorophoride, its kind of in-limbo atm. In the future i'dlike to make it useful for its actual intended purpose-  heart transplants. But since those aren't a thing right now it doesn't really fit. i'm not sure what to do with it in the interim

**Comment by LordFowl** [comment]
A single bugfix surrounded by several feature/rebalance is more festure/rebalance than bugfix, isn't it?

**Comment by Arrow768** [comment]
- You nerfed lexorin to a level where you need more than 50 units to even get into crit
- You changed lexorin to cause oxy damage instead of organ damage
- You reduced the chance that impedrezene causes brain damage by 66%
- You reduced the damage of Polytrinic acid to 60%
- You reduced the damage of acid to 40%

These changes are quite drastic and definitely need to be tested before merging them into master.
Retarget to master please.

**Comment by MarinaGryphon** [comment]
I don't believe lexorin ever caused organ damage?

**Comment by Lohikar** [comment]
No, it does.
```
/datum/reagent/lexorin/affect_blood(var/mob/living/carbon/M, var/alien, var/removed)
	if(alien == IS_DIONA)
		return
	M.take_organ_damage(3 * removed, 0)
	if(M.losebreath < 15)
		M.losebreath++
```

**Comment by NanakoAC** [comment]
@Arrow768 
I did not nerf lexorin, i buffed it.
Just to make sure we're on the same page, take_organ_damage damages EXTERNAL organs, ie limbs. The amount of brute damage lexorin deals is fairly insignificant and gets out-healed naturally, so it doesn't really do any damage at all for practical purposes.

By changing that to oxyloss instead, it will kill much faster, because lexorin also increases the losebreath counter (represents an inability to breathe) which prevents oxyloss from wearing off. This makes it kill significantly faster than it did before

The reduction of brain damage on impedrezene is because it is not intended to cause damage, but to slow the target down. perhaps the brain damage should be removed altogether

Acids were atrociously powerful when injected, feel free to try that out in live code. 

Anyways, these aren't drastic changes in any meaningful sense. The scale of the adjustments is large, but **the adjustments are made to niche content** - poisons are rarely used.  The ones which i've directly altered even less so, lexorin is the only one that sees significant use in combat due to being part of a changeling sting. These tweaks are intended to bring things into a little more believable and balanced state.

Incidentally i didn't touch cyanide. That's your instant kill poison, and it does require a lot of effort to make, you have to cultivate it with mutated plants

**Comment by skull132** [comment]
Did testing.

Just about the only "Oh, wow. This is fucking dumb," on the list was mercury. Which kills you at 60 brainloss, in ~90 seconds, after a 15 unit injection.

Phosphorous I wasn't even able to get to do shit. Perhaps it doesn't work injection, though the affect blood proc would imply otherwise.

I agree with buffing Lex *slightly*, though I enjoyed the fact that it can be used as a sedative due to it slow and very controllable lethality.

Impredrazine is pretty slow as is, taking over 90 seconds (perhaps closer to 2.5 minutes) to brainkill someone from a simple 20 unit injection. I think reducing its effectiveness by 2/3rds is too much, and makes it completely ineffective and useless. A modifier of 2 is more appropriate. Or perhaps not touching it at all, due to the fact that it cannot kill from a 15 unit injection.

Polyacid is pretty amazing. I think it should stay amazing. Or maybe like. A 8 amazing. Definitely not a 6 meh.


As for whether or not it's fit to go into master. Eh, rather not. Generally, rebalances move into dev first. As with the armoury and other PRs. The only real thing that's worth shoving straight into master would be the mercury fix, but I'm not certain it's used enough. At least, I've not heard admins and mods mention that it's an issue.

**Comment by NanakoAC** [comment]
RE: Phosphorous: You read the diff wrong, i didnt touch that. I blame github for being confusing, the nerf there was to acid

RE: Impedrezene. Nobody really uses it. Especially since mercury exists and is easier to get, having another drug that does brain damage is redundant. i was thinking of entirely removing that aspect of it - its meant to be a way of impairing people and slowing them down, not killing them.

RE: Polyacid.  Its really not hard to make and theres not much defense against someone with a syringegun full of it. Even a normal syringe can be harm-intent stabbed into someone. I feel that the damage it allowed was just far too much for medical to have easy access to, and pretty unbelievable considering the kill speed of other things. Not to mention it kind of sidelines poisons if you can just inject someone with acid and kill them rapidly

Small quantities of acid injected shouldnt really do that much damage, they'd probably burn a hole through the injection site and drip back out of the wound. In the real world acid is the weapon of choice for nonlethal disfigurement, not for assassination. I dont believe acids should be an effective killer in any medium except massive contact exposure. EG: Chem sprayer

**Comment by skull132** [comment]
> RE: Impedrezene. Nobody really uses it. Especially since mercury exists and is easier to get, having another drug that does brain damage is redundant. i was thinking of entirely removing that aspect of it - its meant to be a way of impairing people and slowing them down, not killing them.

Argument doesn't make sense. At all. At the rate to which you slowed it, it does absoloutely no noteworthy damage. Which is sad, as "safe" ways to neutralize people with drugs shouldn't exist. If you want to focus it more on being a drug which handicaps, slow down the metabo rate a little and increase the presence of debilitating effects.

It should have a lasting effect, and the present one, IMO, is pretty good. As said, could also be nerfed to 2/3rds, definitely not any lower, though.

**Comment by NanakoAC** [comment]
agreed. the changes to impedrezene were kind of half-assed. ill just revert that part for now. maybe revisit in future when we have more impeding mechanics to work with

**Comment by skull132** [comment]
@NanakoAC this is awaiting the changes you mentioned in the last comment before being pulled into dev or master. Probably dev, as there's nothing critical/amazing here.

**Comment by NanakoAC** [comment]
done, sorry for delay x

**Pull request merged**
