### PR TITLE
Adds Greatcoats

### PR DESCRIPTION
**Pull request by Ben10083**
Adds Black and Brown Greatcoats to loadout, thanks to greytide_(discord) for sprites!

Black:
image
image

Brown:
image
image

- [x] Description
- [x] Open Sprites

### CODE REVIEW

**Comment by Ben10083** [comment]
!wip

**Review by FluffyGhoster — APPROVED** [review]
Seems fine enough code wise

**Comment by 1glitchycent** [comment]
zavodbros.... we won???!!!

**Comment by NonQueueingMatt** [comment]
applying maint discussion because I'm leaning towards not allowing greatcoats for non-Dominians for setting consistency

**Comment by NonQueueingMatt** [comment]
add the new sprites you showed in code dungeon without the lining and this is fine to merge

**Comment by Ben10083** [comment]
@NonQueueingMatt Added. PR changed to reflect that these are now Black and Brown greatcoats, added new loadout option for them

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
