### PR TITLE
You Tell 'Em, Boss: The Diplomatic Aide

### PR DESCRIPTION
**Pull request by RustingWithYou**
Adds a new job, the Diplomatic Aide. This role acts as an assistant/bodyguard/general-purpose goon for the consular officer.
The job is disabled by default, but Consular officers can open a single slot for a Diplomatic Aide matching their citizenship.

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Comment by dessysalta** [comment]
Out of curiosity, would this invalidate existing assistants/aides if they're outside of the "diplomatic aide" role, such that playing an ordinary assistant to aide a consul would be against policy? Mostly in the context of multiple viax/akaix servicing a Ta, etc.

**Comment by DreamySkrell** [comment]
I don't think adding a whole new job with new snowflake code, is like, a good addition. Why couldn't they just be (independent) assistants?

**Comment by RustingWithYou** [comment]
> Out of curiosity, would this invalidate existing assistants/aides if they're outside of the "diplomatic aide" role, such that playing an ordinary assistant to aide a consul would be against policy? Mostly in the context of multiple viax/akaix servicing a Ta, etc.

This would be up to admins, but I don't see why it would.

**Comment by RustingWithYou** [comment]
> I don't think adding a whole new job with new snowflake code, is like, a good addition. Why couldn't they just be (independent) assistants?

I thought about this, but liked the idea of giving them access to the consular office and some lighter versions of the consular loadouts. In addition, I think it makes it easier for the consular player in question only getting one when they explicitly want it.

**Comment by GMR25** [comment]
> > I don't think adding a whole new job with new snowflake code, is like, a good addition. Why couldn't they just be (independent) assistants?
> 
> I thought about this, but liked the idea of giving them access to the consular office and some lighter versions of the consular loadouts. In addition, I think it makes it easier for the consular player in question only getting one when they explicitly want it.

I’m not sure how only getting when one desired is a factor here. An assistant doesn’t have any say in their position, they can’t force themselves on a Consular even if they wanted to. Assistants also wouldn’t be citizenship locked, so you’d be able to have a Bieselite or whoever assisting you if desired with far less character limitations.

**Review by Arrow768 — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
