### PR TITLE
Removes several playable and a few unplayable species

### PR DESCRIPTION
**Pull request by LordFowl**
WIP for now as I decide how best to remove IPC subspecies, which will be packaged in this PR as well.

### CODE REVIEW

**Comment by ComradeCorbyn** [comment]
boss mode

**Comment by skull132** [comment]
Should wait until a final decision on the spacers is made, before removing them as an unused species.

**Comment by LordFowl** [comment]
Even if I remove them I am fairly certain that none of Alb's code uses their base, so this should pose no problem. In fact, it'd be better if this was merged first so that Alb could update to match the new organization standard.

**Comment by LordFowl** [comment]
Also this fails unit tests because I removed Resomi.

**Comment by MarinaGryphon** [comment]
call it off guys we have an ipc maintainer now

**Pull request closed without merging**
