### PR TITLE
WIP Holder PR for Meme Remake

### PR DESCRIPTION
**Pull request by Kaedwuff**
This is not finished.  Please do not review it at this time, I'm only putting this here so I have something to commit to.

### CODE REVIEW

**Comment by VTCobaltblood** [comment]
you can open draft prs

**Comment by Kaedwuff** [comment]
> you can open draft prs

How does that work? I did not know this.

**Comment by VTCobaltblood** [comment]
Look above

**Comment by Kaedwuff** [comment]
Okay, thank you. I will be using that in the future if I have a WIP! :O

**Comment by VTCobaltblood** [comment]
You can close and re-open the PR, it won't delete the branch and you can make it a draft

**Pull request closed without merging**
