### PR TITLE
Hopefully fixes the ops lift getting stuck on third deck.

### PR DESCRIPTION
**Pull request by DreamySkrell**
fucking lifts

how do they work???

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!bugfix

**Comment by DreamySkrell** [comment]
!review

**Comment by SleepyGemmy** [comment]
is this playtested?

**Comment by DreamySkrell** [comment]
> is this playtested?

yeah

**Comment by DreamySkrell** [comment]
uhhh I mean, I tested this like 10 times, and it worked every time, except once, but I genuinely have no idea if it was cause I was changing the values between recompiles and it didn't register or what

**Review by SleepyGemmy — APPROVED** [review]

**Review by alsoandanswer — APPROVED** [review]

**Review by FluffyGhoster — APPROVED** [review]

**Pull request merged**
