### PR TITLE
Brotha, I Hurt People - adds Vaurca Attendants

### PR DESCRIPTION
**Pull request by feartheblackout**
I've only been at this since the start of the month, and obviously there will have to be adjustments made, but here we go:

With this PR, Vaurca Attendants, or type BB warriors, will be playable on the ship. They are faster than Myrmidons, but also more prone to injury. Because the sprites are taller and wider than baseline Vaurcae, modified uniform, shoe, and tunnel cloak sprites are also provided, as well as unique offsets. Examples seen here:
image
image
image

TO-DO (off the top of my head currently):
- [x] Get reviewed by the Vaurca lore team
- [x] Get opinions from actual spriters on how I did lol
- [x] Get better damage mods
- [ ] Figure out a better implementation for the accessory offsets and whatever else needs improvement code-wise
- [ ] Figure out how I'm going to add Attendant variants of the tunnel cloaks while still having them work for Bulwarks

Enjoy, Vaurca fans!

### CODE REVIEW

**Comment by feartheblackout** [comment]
!review

**Comment by alsoandanswer** [comment]
Alright, spriter input : 
Please use **icon_supported_species_tags** and set **contained_sprites** = TRUE and append them to existing clothing. Purpose made icon files are depreciated. (E.g., icons/mob/species/attendant/back.dmi , icons/mob/species/attendant/shoes.dmi). Add them in game similarly to how tajara shoes are added in currently.

Also, DO NOT make new object defines for new clothing wherein the only difference is being species restricted! It is better for them to just wear existing clothing - just have **icon_supported_species_tags** modify the sprite for you.

Other than that, I like the tunnel cloak sprites and whatnot. You've followed the style well, and that's really all I can ask for.

**Comment by KingOfThePing** [comment]
This is cursed as fuck 

👍

**Comment by feartheblackout** [comment]
> Alright, spriter input : Please use **icon_supported_species_tags** and set **contained_sprites** = TRUE and append them to existing clothing. Purpose made icon files are depreciated. (E.g., icons/mob/species/attendant/back.dmi , icons/mob/species/attendant/shoes.dmi). Add them in game similarly to how tajara shoes are added in currently.
> 
> Also, DO NOT make new object defines for new clothing wherein the only difference is being species restricted! It is better for them to just wear existing clothing - just have **icon_supported_species_tags** modify the sprite for you.
> 
> Other than that, I like the tunnel cloak sprites and whatnot. You've followed the style well, and that's really all I can ask for.

Got it! Should this be done with all the uniforms as well? I set icon_auto_adapt to TRUE on /obj/item/clothing/under and modified everything accordingly, but this only seems to make it work with the jumpsuits, while just about every other uniform uses the default sprites. Setting contained_sprite to TRUE also seems to break those sprites completely.

**Comment by feartheblackout** [comment]
image

**Comment by alsoandanswer** [comment]
> Got it! Should this be done with all the uniforms as well? I set icon_auto_adapt to TRUE on /obj/item/clothing/under and modified everything accordingly, but this only seems to make it work with the jumpsuits, while just about every other uniform uses the default sprites. Setting contained_sprite to TRUE also seems to break those sprites completely.

Well, I can't really help you for every use case, but make sure you check these things accordingly :
Make sure icon_species_supported_tags = list("vaa") (inclusive of any other species supported tags) and icon_auto_adapt = TRUE for sprites that have a unique sprite for Vaurca Attendants. If you have not made a unique sprite, do not set these to TRUE or anything, leave them be.

Make sure all of the sprites are in the *same .dmi*

Make sure all of the sprites have the correct suffixes. For example, uniforms use "_un" suffix, shoes use "_sh" suffix, etc.

That's all the advice I can give from your message. However, PLEASE don't hesitate to DM me anyway! There's only so much information I can glean from your message, and I can help you better on Discord!

**Comment by feartheblackout** [comment]
Going to probably continue this during the weekend. I've been busy with moving to a new place, sorry!

**Comment by feartheblackout** [comment]
Decided to just simplify the whole process of uniform-making by using pixel offset and shaving some pixels off the thighs instead. Hopefully that's acceptable. Here's it in action: 
image

**Review by DreamySkrell — APPROVED** [review]
looks fine I think

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
pending a discussion with vaurca lore

**Comment by NonQueueingMatt** [comment]
After discussing this with vaurca lore it'll be closed as it's not really wanted. You can ask desven for more details on the lore end, but from our side, introducing another (niche) subspecies with specifically-sprited clothing is a maintainer nightmare.

**Pull request closed without merging**
