### PR TITLE
adds new airlock and firedoor sounds

### PR DESCRIPTION
**Pull request by listerla**
Another attempt at https://github.com/Aurorastation/Aurora.3/pull/9912 with permission from original author.

Should be complying with everything said when that was closed, unless it is preferred the glass airlocks or maint airlocks use the default sound, which is easily done.

### CODE REVIEW

**Comment by listerla** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
Again, glass airlocks should not have the same sound as normal airlocks. They should sound much lighter, like they do right now. Otherwise, looks good. Address this and I will testmerge it.

**Comment by listerla** [comment]
Glass airlocks do not have the same sound. They are set to the 'hall' sound, while default airlocks are set to the 'covert' sound.

**Comment by NonQueueingMatt** [comment]
> Glass airlocks do not have the same sound. They are set to the 'hall' sound, while default airlocks are set to the 'covert' sound.

Listen to it in game. It's out of place for a glass airlock.

**Comment by listerla** [comment]
Sound replaced with an alternate sound from the original.

**Comment by NonQueueingMatt** [comment]
These sounds are alright, but I should note that with "glass airlocks" I meant the white hallway ones. The sounds before were fine for the rest, so if you want to change those back, go for it.

**Comment by Dekserrrrrr** [comment]
The maintenance airlocks sound WAY too loud, honestly. Almost like mini blast doors.

**Pull request closed without merging**
