### PR TITLE
Fixes Kataphract Shuttle Docking Issues

### PR DESCRIPTION
**Pull request by EJDenton**
Corrected Dock Target, verified vars, and removed extra docking controller to resolve the Kataphract shuttle not docking properly.

Fixes https://github.com/Aurorastation/Aurora.3/issues/19059

### CODE REVIEW

**Comment by EJDenton** [comment]
!bugfix

**Comment by EJDenton** [comment]
!review

**Comment by DreamySkrell** [comment]
image
this is replacing airlock markers defined in code with markers defined in the map
the fixes (changing IDs or whatever) should be done on markers defined in code instead

**Comment by EJDenton** [comment]
@DreamySkrell I made the requested changes but I didn't see a way to re-request the review of changes that I've seen in the past. Hopefully this message is enough.

**Review by DreamySkrell — APPROVED** [review]

**Pull request merged**
