### PR TITLE
Portable Turret Fixes

### PR DESCRIPTION
**Pull request by Ben10083**
Portable Turret can now access it's panel to control it's settings, as intended

### CODE REVIEW

**Comment by Ben10083** [comment]
!wip

**Comment by Ben10083** [comment]
bugfix

**Comment by Ben10083** [comment]
!bugfix

**Comment by Ben10083** [comment]
!review

**Review by DreamySkrell — APPROVED** [review]

**Review by FluffyGhoster — APPROVED** [review]

**Pull request merged**
