### PR TITLE
Replaces Gadpathur Patrol Corvette Longbow with a Grauwolf + minor fixes

### PR DESCRIPTION
**Pull request by lavillastrangiato**
* Title.
* A corvette-class patrol vessel should not have a 406mm cannon, both in terms of game balance (no other corvette-class ship in the game has a Longbow) and internal logic.
* Also fixes a couple bugs with the airlock and some incorrect types of connectors.

### CODE REVIEW

**Comment by lavillastrangiato** [comment]
!review

**Comment by FluffyGhoster** [comment]
I think it is fine for this ship to have a longbow, it's a faction literally focused on preparing for a (defensive) war, it makes sense they would install the biggest gun they could fit

**Comment by lavillastrangiato** [comment]
> I think it is fine for this ship to have a longbow, it's a faction literally focused on preparing for a (defensive) war, it makes sense they would install the biggest gun they could fit

No. This is a 406mm cannon.

tumblr_nkm3nwbsXj1rwjpnyo1_1280

A corvette can weld this to their hull with minimal problems (well, apart from the fact it'd take up most of the deck). But they're going to have a pretty hard time _moving_ after they weld it on, even in space. There's also the fact that this is a patrol corvette, not a cruiser-class vessel. Patrol vessels are usually small to medium in size; battleships, like Iowa-classes, are the types of ships that carry that calibre of weapon.

The other reason that a patrol corvette shouldn't have a 406mm cannon is balance reasons. Ships like the Freebooter and the SFA corvette are fairly thinly-armoured and don't have Longbows because, well, they're corvettes. It's not fun and engaging for the Freebooter to be simply bunker-bustered if they desire to do piracy.

If your solution to this problem is "arm up the Freebooter more", you'd be missing the point. Power creep is something that should be avoided.

**Comment by DreamySkrell** [comment]
I think it's fine and I agree with Fluffy

**Comment by Eyeveri** [comment]
I agree with Fluffy and Dreamy. I think that them having a Longbow is fine. I suggest a feedback post to gauge the community's view on it.

**Comment by Eyeveri** [comment]
Added the maintainer discussion and DNM labels, because as of right now there are three developers saying to keep the Longbow. It'll be up to the maintainers.

**Comment by NonQueueingMatt** [comment]
We've decided not to implement this in favour of keeping variety. However, we will write a guide detailing when/what guns to use, why, and how to balance them for offships.

**Pull request closed without merging**
