### PR TITLE
Makes 5-Cheung hideout fancier.

### PR DESCRIPTION
**Pull request by TheStryker**
Changes up the 5-Cheung hideout to be more professional, in line with the local branch being a neighborhood organization in an upper-middle class area.
- 5-Cheung hideout was turned into a consulting firm with a 3rd floor.
- Corndog restaurant was turned into a vending machine restaurant with a back-alley surgical ward in the basement.
- Mopped up the floors in various locations.

image

image

Adds assets to support these changes.
All spritework done by Lancer.

### CODE REVIEW

**Comment by TheStryker** [comment]
!review

**Comment by Greenjoe12345** [comment]
image
maybe use the sliding glass doors seen elsewhere on PV here rather then windoors?

**Comment by DreamySkrell** [comment]
image
I do not see the bike keys anywhere

**Comment by DreamySkrell** [comment]
image
the wall types should be consistent in the basement, either all steel or all wood (should be all steel though cause the mid and top floors are steel)

**Comment by DreamySkrell** [comment]
the spawn points also somehow got mixed up, both on master, and on this PR

image
the cheung goons should all spawn here ^

but somehow on this PR there are 4 spawns on the mid floor of the hideout, and 1 spawn (?) in the ramen place

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
as above

**Comment by TheStryker** [comment]
> image maybe use the sliding glass doors seen elsewhere on PV here rather then windoors?

I used the windoors because they were also used on the front of the police station and the convenience. I can change it to use the sliding doors from the spaceport but those have no side sprites, so it'll also look odd since only one set of doors will be sliding.

**Review by DreamySkrell — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Review by FluffyGhoster — APPROVED** [review]

**Pull request merged**
