### PR TITLE
Atom gliding for clients

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Added atom gliding for clients (not AI-controlled mobs or other things, for now).

This will require a testmerge and some observation on live to see how everything behaves, consider it an experiment for now.

https://youtu.be/r4PG8_gufxY

https://youtu.be/695OKWL9iGk

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!review

(this isn't the final form, there's some cleanup that can possibly be done, I just wish to see how it behaves in live to see if there's issues that would require an unworthy amount of work to solve)

**Comment by SleepyGemmy** [comment]
i'm glad this is being readded! since the tickrate increase i've always felt movement has been jerky.

**Comment by SleepyGemmy** [comment]
is the smoothness for the movement configurable by the client, as the FPS value used to be able to be used for?

**Comment by FluffyGhoster** [comment]
> is the smoothness for the gliding configurable by the client, in the same way the FPS value used to be able to be used for?

No, the subsystem sets the glide size

**Pull request closed without merging**
