### PR TITLE
Removes the Custodial Module

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR removes the custodial module. custodians already have little enough to do as-is, especially if both slots are filled, and the module basically invalidates their entire role.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Comment by NiftyBaby** [comment]
...could the discussion on this kind of thing not be finalized first?

**Comment by desvenlafaxine** [comment]
If we're voting to remove modules, I'd like to see responder module go next.

**Review by Sindorman — APPROVED** [review]

**Review by Sindorman — CHANGES_REQUESTED** [review]
The PR is partially valid code wise, however it already conflicts with the cyborg rework suggested in my thread. One of the changes was add locking of some modules to be disabled by default and be enabled via robotics console by command such as RD/Captain. Therefore, once that is implemented this PR will need to be reverted. Because of that I suggest you simply remove the choice to choose the module for now, but keep the other code such as what module has, and other mechanics in there

Meant to request change, not approve

**Comment by SleepyGemmy** [comment]
> The PR is partially valid code wise, however [...]

sounds good.

**Comment by NonQueueingMatt** [comment]
Unwanted.

**Comment by SleepyGemmy** [comment]
pursuing Sindorman's solution instead.

**Pull request closed without merging**
