### PR TITLE
Command level improvements/remapping

### PR DESCRIPTION
**Pull request by Hunttark**
Second attempt at Command remapping. Prior PR had a merge conflict with my Infirmary PR, a conflict which did not seem to disappear no matter the changes applied to the problem area.

- Entire layout change of the Bridge, update of bridge crew lockerroom, update to Captain's space, breakroom updates.
It- Entirely the same setup as the prior PR, nothing has changed besides resolving the damn mysterious conflicts.

67196dd4f71ed577a634f99186afac70

### CODE REVIEW

**Comment by Hunttark** [comment]
!review

**Comment by Hunttark** [comment]
!wip

**Review by mikomyazaki — APPROVED** [review]

**Comment by Arrow768** [comment]
I am not sure what purpose the room marked in red serves (and why its part of the "bunker" area.
The Airlock marked with (1) seems quite off and should be replaced with a rwall.

If that is replaced by a rwall, the piping needs to be changed so it is not going under a rwall (instead tie the captains office into the bridge)
image

**Comment by Hunttark** [comment]
> I am not sure what purpose the room marked in red serves (and why its part of the "bunker" area. The Airlock marked with (1) seems quite off and should be replaced with a rwall.
> 
> If that is replaced by a rwall, the piping needs to be changed so it is not going under a rwall (instead tie the captains office into the bridge) image

The room is red and is simply dragged/the exact same as the current SCCV Horizon map. It is a part of the bunker area as the said room is where the bunker APC used to be located for some unknown reason. It seems I forgot to resolve the area of such. I can change such if you want and reroute the power, disposals, and atmos lines through the bridge instead? There were comments that having multiple entrances/exits, is never a 'bad thing' especially since it may benefit an tags, but ill do whatever is found necessary, I don't understand the point of the room myself.

**Comment by Hunttark** [comment]
!review

**Comment by Hunttark** [comment]
Removed WIP and switched to review since the asteroid anomaly was found to be the cause of a check failure, not the map itself***

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
