### PR TITLE
Bullet Trails

### PR DESCRIPTION
**Pull request by Geevies**
* Added bullet trails to non-energy projectiles.

https://user-images.githubusercontent.com/22774890/104509954-1d2f8700-55f3-11eb-8b01-2f9b18b40c76.mp4

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by NonQueueingMatt** [comment]
This makes bullets look more like rockets honestly.

**Comment by OneOneThreeEight** [comment]
Might I suggest trying to give them motion blur instead?

**Comment by skull132** [comment]
With Matt on this one. Different icon needed.

**Pull request closed without merging**
