### PR TITLE
Unapologetic Opossum Buffs

### PR DESCRIPTION
**Pull request by Geevies**
* Ported Opossums.

image

Ported: https://github.com/Baystation12/Baystation12/pull/26620, https://github.com/Baystation12/Baystation12/pull/26634, https://github.com/Baystation12/Baystation12/pull/26780

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Review by fernerr — COMMENTED** [review]
While it's a cute idea, I'm not sure I support adding more pets to the station, especially one that's not especially related to us or our lore. And after all cargo tends to get the occasional pet anyhow, depending on what spawns in their warehouse, which are far more exotic/lore related usually.

**Comment by TheDanseMacabre** [comment]
Station pets are already pretty stupid and the proliferation of non-domesticated animals on the station as "pets" is stupid.

**Review by Chada-1 — APPROVED** [review]
Not much to say, but like. We could totally rebrand them to another department or even make them a random maintenance/warehouse spawn if it comes down to it, they're super cute.

**Comment by Chada-1** [comment]
> Station pets are already pretty stupid and the proliferation of non-domesticated animals on the station as "pets" is just ridiculous.

The primary thing stopping Opossums from being domestic isn't their temperament, it's their dietary requirements. If they didn't require a very specific calcium intake to prevent crippling bone disease, they'd actually be fantastic pets (And when properly cared for, they are)

I know this because I love them and I've looked into wildlife rehabilitation for them.

**Comment by skull132** [comment]
Against adding human critters instead of adding UNIQUE LORE critters like schlorrgos.

**Pull request closed without merging**
