### PR TITLE
Tramp freighter ship, hivebot mini-away site.

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
What it says up there.

### CODE REVIEW

**Review by mikomyazaki — COMMENTED** [review]
What do you imagine a round will currently look like for the Freebooter Crew?

**Comment by TheDanseMacabre** [comment]
> What do you imagine a round will currently look like for the Freebooter Crew?
It's very freeform, seeing as they're an independent group with a very large amount of varied equipment. They could do anything from trading with the Horizon, to mining, to exploring away sites, whatever - in a way I'd consider it a "beginner" away site role, seeing as you have no predetermined alignment and the options to do whatever you'd like. While I think faction-aligned third party ships are the best and what we should generally focus on, I also think we need independent ones here and there.

**Comment by mikomyazaki** [comment]
> > What do you imagine a round will currently look like for the Freebooter Crew?
> 
> It's very freeform, seeing as they're an independent group with a very large amount of varied equipment. They could do anything from trading with the Horizon, to mining, to exploring away sites, whatever - in a way I'd consider it a "beginner" away site role, seeing as you have no predetermined alignment and the options to do whatever you'd like. While I think faction-aligned third party ships are the best and what we should generally focus on, I also think we need independent ones here and there.

I think the site description, especially calling them freebooters & happy with illegal activity is going to learn them toward piracy (you even called the PR branch 'alittlethieving'), so currently I think this ship will just go the same way as the EE ship did. I asked in dev chat and the maintainers said that soft-antagonist/antagonist-leaning ships are going to require the dynamic gamemode PR to be finished (#13664) before they can be included. 

I have some feedback on the actual map as well, but I think the most important thing is the map's place in a round.

**Comment by TheDanseMacabre** [comment]
> I think the site description, especially calling them freebooters & happy with illegal activity is going to learn them toward piracy (you even called the PR branch 'alittlethieving'), so currently I think this ship will just go the same way as the EE ship did. I asked in dev chat and the maintainers said that soft-antagonist/antagonist-leaning ships are going to require the dynamic gamemode PR to be finished (#13664) before they can be included.
I'd be happy to change them into a generic freight crew, in that case. I can see where you're coming from.

**Review by Arrow768 — DISMISSED** [review]
Wrong map format (again)

**Review by JohnWildkins — CHANGES_REQUESTED** [review]
image

wall lockers were consolidated so you need to re-path these

**Review by JohnWildkins — CHANGES_REQUESTED** [review]
Hivebot Hub has nothing glaring to it.

Tramp Freighter has a few problems:
- Mining Vendor currently is going to send anything ordered that requires shuttle delivery (drill head, etc.) on the cargo shuttle. You either need to change how the vendor works if it's placed off-map, or replace it.
- Freighter starts with WAY too much stuff. It's highly variable because most of it is their full cargo bay which rivals the Horizon's in size. That combined with good starting mining equipment and weapons seems a little suspect.
- Despite having a lot of good mining equipment, they don't have really anything to do with it (except sell it to the Horizon, I guess?) There's no refinery equipment on the ship, or really anywhere to store it other than just in boxes in the hangar.

I think the best thing for the ship would be to cut back pretty significantly on the full random crates they spawn (maybe swap some out for random loose items, but something like 50-75% of the spots should probably be blank), and somehow shove a small refinery into the ship. That lets the ship's crew engage with the mining progression if the Horizon isn't doing anything interesting.

**Comment by TheDanseMacabre** [comment]
Mining vendor removed, roughly half of all lootcrates removed and refinery added.

**Review by Alberyk — APPROVED** [review]

**Review by JohnWildkins — APPROVED** [review]

**Pull request merged**
