### PR TITLE
Limits what can go in wallets.

### PR DESCRIPTION
**Pull request by 1Sparky1**
<s>Title. Autoinjectors can, so it was kinda odd their gaseous cousins couldn't too.</s>

New title. Basically, what Matt said in the comments, actually looking at the stuff you could put in wallets was nonsense. Trimmed down most of the unreasonable items (Willing to change this with feedback).

### CODE REVIEW

**Comment by 1Sparky1** [comment]
!review

**Comment by NonQueueingMatt** [comment]
I cannot believe I am fucking saying this, but the wallet powercreep is getting kind of insane. This ID slot item can hold so much shit it's dumb.

**Comment by 1Sparky1** [comment]
I do agree that wallets seem a little strong, but I think they should either hold both autos or neither, as it seems a little pick and choose for the sake of balance otherwise.

**Comment by NonQueueingMatt** [comment]
> I do agree that wallets seem a little strong, but I think they should either hold both autos or neither, as it seems a little pick and choose for the sake of balance otherwise.

Autoinhalers will not be allowed in wallets. If you want to remove unreasonable items from being stored in wallets, go for it.

**Review by Casper3667 — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
