### PR TITLE
Dominian Corvette symmetry and Fixes for tajaran Smuggler and SSMD

### PR DESCRIPTION
**Pull request by tzui5020**
- Makes the Dominion corvettes shuttle symmetric
- Upgrades the SSMDs APC so the Starboard thrusters can properly work
- Attaches the Thrusters to pipes on the Tajaran Smuggler ship (Get arrested by sol and get your ship fixed, fair trade?)

### CODE REVIEW

**Comment by tzui5020** [comment]
!review

**Comment by tzui5020** [comment]
Let me fix that

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by Arrow768** [comment]
Please ping a maintainer when you solved the conflicts

**Comment by tzui5020** [comment]
there's still something wrong with it and I don't think I can resolve this in a Timely fashion so I'll try again at a later date

**Pull request closed without merging**
