### PR TITLE
Christmas in July

### PR DESCRIPTION
**Pull request by furrycactus**
Adds the gaudy and over the top Christmas decor to the Aurora and Odin once again. Summer themed, this time, as I promised exactly a year ago.

Some additional edits, ported an improved base santa hat from TG, with the one with a beard included as a subtype.
Gifts containing mobs now have their sprites changed, thanks to Happy_Fox

### CODE REVIEW

**Comment by furrycactus** [comment]
Forgot a few things, give me a bit.

**Comment by furrycactus** [comment]
!review

**Review by fernerr — COMMENTED** [review]
Examined the file, the big diff is due to the dictionary letter for chasm_mask changing. Unsure as to why, but there's nothing wrong with the file itself, as it's merged as expected. No biggie.

**Review by skull132 — APPROVED** [review]

**Comment by fernerr** [comment]
I'll take another look on this tomorrow, and solve any conflicts.

**Comment by MarinaGryphon** [comment]
> Examined the file, the big diff is due to the dictionary letter for chasm_mask changing. Unsure as to why, but there's nothing wrong with the file itself, as it's merged as expected. No biggie.

If you made the changes via StrongDMM and have the mapmerge commit hook set up, you'll need to commit with the `--no-verify` option to avoid it messing stuff up.

**Pull request merged**
