### PR TITLE
Adds a bloom layer to lighting.

### PR DESCRIPTION
**Pull request by chaoko99**
https://streamable.com/yymbp

### CODE REVIEW

**Comment by skull132** [comment]
If I may say.

_Too much bloom._ The end product is a washed out view.

**Comment by chaoko99** [comment]
It's a mapping issue. The llights are far too bright / too frequent.

**Comment by skull132** [comment]
Make sure that it's an actually solvable mapping issue and provide a preview of a properly mapped area for reference, then.

It might well be the case that the current light levels are set so that we cannot move the lights further apart without editing them.

**Comment by chaoko99** [comment]
I was thinking of adding ceiling lights.

**Comment by chaoko99** [comment]
Light strips it is.

**Comment by TheGreatJorge** [comment]
I mean. Not that it can't look good at times. But on second thought, I'd say that there are not too many lights mapped in. There are many, but not too many.

I though about light strips for some time, and I am not sure if they will cut it. They would result in many more, but weaker light sources, while changing the appearance of areas quite a lot.
They could probably look good, but I don't think floor light strips should be added solely to fix the adder issue.

I'll probably need clear explanation on why changing lights parameters or why blacklisting the adder for some light sources will not work as a solution again. Because I still don't get it.

I really find the lights object system to be quite balanced right now. Not too many lights to tend to, not too few... you get my points.

**Comment by chaoko99** [comment]
>I'll probably need clear explanation on why changing lights parameters or
why blacklisting the adder for some light sources will not work as a
solution again. Because I still don't get

Because I have no idea how to approach the issue.

>I though about light strips for some time, and I am not sure if they will
cut it. They would result in many more, but weaker light sources, while
changing the appearance of areas quite a lot.
They could probably look good, but I don't think floor light strips should
be added solely to fix the adder issue.

I mostly wanted them for the sake of style. SS13 isn't very
science-fictionish in aesthetic.. It's grungy and industrial, and that
bothers me. Floor lights are pretty and whatnot. Dumb personal things.

**Comment by chaoko99** [comment]
The primary cause of this issue is due to the fact that our lights have
exactly no baring on how light *actually* functions by stretching
luminosity over a distance, rather than luminosity determining distance.

**Comment by TheGreatJorge** [comment]
I see, oh well. I was just basing it on the fact how in reality, there can be many lights around a building without the interior looking like a sunbath. So I thought I'd prefer this option, making lights not brighten areas, while keeping as many of them as there are now.

I've really got no clue about any of this as far as code goes, but I bet Lohikar could look into this with you, if he has time, if you don't know how to approach that? If you want to try the approach, that said.

Making some aethetic new light types and adding bloom both sound great, but I think these would go better of apart from each other, rather than using one to control the other.

**Comment by chaoko99** [comment]
I don't know how I'm going to finish this.

**Comment by chaoko99** [comment]
Gonna close this for a while. I dunno what I'm gonna do to make this work. Generally speaking; overlay images can't be modified after application if they're using images.

**Pull request closed without merging**
