### PR TITLE
Combines the ss13_admin and ss13_player table.

### PR DESCRIPTION
**Pull request by Arrow768**
Combines the ss13_admin and ss13_player table into one.

I kinda want to rewrite the entire backend logic since its somewhat dated.

### CODE REVIEW

**Comment by Lohikar** [comment]
This'll be fun for compatibility.

**Comment by Arrow768** [comment]
Why is that ?

**Comment by Lohikar** [comment]
Switching between a version of the server without this PR and one with it will involve either duplicating the admin info or changing to the flatfile backend.

**Comment by Arrow768** [comment]
I do not see that as an issue, as we are currently not running a test server.

Even if we would this could be mitigated by just merging it into dev shortly before the merge into master.

**Comment by skull132** [comment]
Also, I was thinking.

At one point we're gonna have a situation where we'll need to give someone perms, but he doesn't need to show up on the admin list. Atm the way to do that is to set `flags` to whatever perms he has, but keep his `rank` as `NULL`. This loses some information, if whatever aux system would also want a rank name.

Should we perhaps add a third column, boolean, `ingame_rank`?

**Comment by Arrow768** [comment]
I can just modify the query to cover that aswell

**Pull request merged**
