### PR TITLE
Skrell Chest Sprite Fix

### PR DESCRIPTION
**Pull request by RyverStyx**
Fixes the flat look of the Skrell chest sprite (see below) 
image

### CODE REVIEW

**Comment by RyverStyx** [comment]
!review

**Comment by RyverStyx** [comment]
!bugfix

**Review by Arrow768 — APPROVED** [review]

**Review by Geevies — APPROVED** [review]
looks dope

**Comment by listerla** [comment]
This seems less like a bugfix and more like a sprite adjustment to be honest. I don't see any bug with the old sprite, other than it having looked bad.

**Comment by Arrow768** [comment]
> This seems less like a bugfix and more like a sprite adjustment to be honest. I don't see any bug with the old sprite, other than it having looked bad.

That is a good point

**Pull request merged**
