### PR TITLE
Cultist stun rune fix

### PR DESCRIPTION
**Pull request by synystersparx**
This makes it so cultists aren't stunned by their own stun runes. It also adds mute to the stun rune (which the talisman has) and slightly extends the stun to 3.

I don't agree with the talisman nerf - I think Cultists should mostly rely on Nar-sie, not have to go scrounging to create a more acceptable form of stun. But this gives a slight chance for a cultist to do something with the rune (which is much harder to surprise someone with than a talisman) while also not being completely useless by not stunning the user or fellow cultists.

### CODE REVIEW

**Comment by synystersparx** [comment]
!review

**Comment by synystersparx** [comment]
!bugfix

**Comment by Arrow768** [comment]
@synystersparx the bugfix label should only be used for PRs that only contain bugfixes.
As this PR contains more than just a bugfix for the issue you mentioned, the bugfix label has been removed.

**Comment by synystersparx** [comment]
Oh,  apologies, didn't realize!

**Pull request merged**
