### PR TITLE
Adds duffel bags to various departmental job lockers

### PR DESCRIPTION
**Pull request by Jaraci**
See title. I always want a duffel when I play engineer in particular, but it's really irritating to actually track one down if you don't specifically spawn with one. If you do that, though, you can't take one of the otherwise unique leather satchels or rucksacks or anything. This fixes that.

I had to bump up the base `storage_capacity` of lockers a bit to ensure everything could fit inside them. Hopefully that isn't an issue!

### CODE REVIEW

**Comment by Jaraci** [comment]
!review

**Review by SleepyGemmy — APPROVED** [review]
i like the changelog file name.

**Review by JohnWildkins — APPROVED** [review]
> I had to bump up the base `storage_capacity` of lockers a bit to ensure everything could fit inside them. Hopefully that isn't an issue!

balance tag added 
request changes
will discuss with maintainers dnm

**Review by NonQueueingMatt — APPROVED** [review]
Bumping up locker capacity isn't really a problem.

**Pull request merged**
