### PR TITLE
Lights: The Aurora

### PR DESCRIPTION
**Pull request by nerocavalier**
* Adds lightings to several previous dark areas.
* Adds light switches to Chapel entrance, Bridge Entrance, and by upper stairs in Psychologist's area.
* [All changes](https://imgur.com/a/2ApcQMP)

### CODE REVIEW

**Comment by nerocavalier** [comment]
!review

**Review by Arrow768 — APPROVED** [review]

**Comment by nerocavalier** [comment]
just check code dungeon for images, i'll add them to main post tomorrow

**Comment by NonQueueingMatt** [comment]
Travis is failing because you're using `step_x` and `step_y` for the items you've mapped in. Use `pixel_x` and `pixel_y` instead.

**Comment by nerocavalier** [comment]
Ok, fixed.

**Review by desvenlafaxine — APPROVED** [review]

**Pull request merged**
