### PR TITLE
Fixes the uplink listing for a free first aid kit having the same path as the option to buy one normally

### PR DESCRIPTION
**Pull request by Tag114**
Fixes the option in the uplink to claim a single medkit for free and the one to buy one normally both having the same path, preventing the option to buy a medkit normally from appearing.

### CODE REVIEW

**Comment by Tag114** [comment]
!review

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
No, there's a difference. The other one can only be bought once, the other can be bought multiple times. They should have different paths, though.

**Comment by Tag114** [comment]
I had noticed they were different but for some reason I thought only the free one was supposed to be there.

**Comment by Tag114** [comment]
!wip

**Comment by Tag114** [comment]
!bugfix

**Comment by Tag114** [comment]
!review

**Comment by Tag114** [comment]
!wip

**Comment by Tag114** [comment]
!review

**Review by DreamySkrell — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
