### PR TITLE
Bulwark expression masks

### PR DESCRIPTION
**Pull request by Stev-the-third**
Adds expression masks to bulwarks. Confirmed by lore.
 
Bulwark Mask Export

### CODE REVIEW

**Comment by Stev-the-third** [comment]
!review

**Comment by Stev-the-third** [comment]
!wip

**Comment by Stev-the-third** [comment]
!review

**Review by FluffyGhoster — APPROVED** [review]
This is nightmare fuel and I'm all for it

**Review by hazelrat — APPROVED** [review]

**Pull request merged**
