### PR TITLE
Disables ERT on Revolution

### PR DESCRIPTION
**Pull request by ParadoxSpace**
probably a lazy PR but it's pretty hot out today.
i don't really think it's at all fair that ERT is a thing on revolution. it's basically a guaranteed safety net for loyalists unless they're stubborn, or the revs somehow blitz the (well-fortified) bridge first. neither of which are particularly common. if ERT should exist on rev, the ability for revs to call in syndicate backup should as well. until then, ERT isn't necessary. it's just a loyalist 'ok good fun but i win' button. no.

### CODE REVIEW

**Comment by ComradeCorbyn** [comment]
maybe just allow civil protection or something. idk, but ERT is designed to fight raiders and mercs. not some little boy with a fireaxe and no armor

**Comment by veraknocks** [comment]
i dont play the game but i can see valid reasoning only from the perspective that the revolution is part of a greater simultaneous movement throughout nanotrasen assets which can justify taxed resources and no ERT. toy with the idea a little more if you can though

**Comment by AmoryBlaine** [comment]
Replace ERT signal responses with CP responses. You get guys in some riot gear with a focus on non-lethal weaponry, and crowd control, instead of hardsuit clad tacticool operatives.

**Comment by MarinaGryphon** [comment]
Civil protection has extremely strong armor. No.

**Comment by ComradeCorbyn** [comment]
then nerf civil protection armor

**Comment by Arrow768** [comment]
Well, its a lazy solution.
Imho it would be better to have a ic way to disable ERT
(i.e. by dismantling a machine, ...)

But until something like that is added, this will have to do.

**Pull request merged**
