### PR TITLE
Morphine/Tramarine Tweaks

### PR DESCRIPTION
**Pull request by Acetrea**
Reduces the overdose threshold of Morphine to 10 and Tramarine to 15.
Adds seizures to both medicines as a result of overdosing.

### CODE REVIEW

**Comment by Acetrea** [comment]
!review

**Comment by FluffyGhoster** [comment]
I'm struggling to see a reason for the OD amount reductions, what is the rationale behind it?

**Comment by Acetrea** [comment]
> I'm struggling to see a reason for the OD amount reductions, what is the rationale behind it?

The way I see it, Mortaphenyl OD is 15u and its painkiller effect is 50.
Morphine's OD is 20u and painkiller effect is over double at 120. 
Tramarine's (meant to be a more stable lab-made Morphine) OD is 20u and painkiller effect is 90.

Based on these numbers, I don't see the reasoning as to why Morphine/Tramarine with a higher painkiller effect than Mortaphenyl would have a higher OD threshold. I want to add real consequences to using these drugs over the ones that are safer, which is why I also added the seizures to the OD.

Mortaphenyl is meant to be used over Morphine and Tramarine for safe Medical roleplay. A good, educated doctor would not give a more addicting drug if there were a better alternative. But as it is, there is no code that creates a lasting addiction effect*, therefore with Morphine/Tramarine's 20u OD threshold and amount of painkiller effect, there are some people in Medical who use Morphine over Mortaphenyl, even when Mortaphenyl is available in the fridge.

*There are only a couple lines of code for "addiction" that give the player one message in the chat that says "You feel terrible".

**Comment by Acetrea** [comment]
> > > I'm struggling to see a reason for the OD amount reductions, what is the rationale behind it?
> > 
> > 
> > The way I see it, Mortaphenyl OD is 15u and its painkiller effect is 50. Morphine's OD is 20u and painkiller effect is over double at 120. Tramarine's (meant to be a more stable lab-made Morphine) OD is 20u and painkiller effect is 90.
> > Based on these numbers, I don't see the reasoning as to why Morphine/Tramarine with a higher painkiller effect than Mortaphenyl would have a higher OD threshold. I want to add real consequences to using these drugs over the ones that are safer, which is why I also added the seizures to the OD.
> > Mortaphenyl is meant to be used over Morphine and Tramarine for safe Medical roleplay. A good, educated doctor would not give a more addicting drug if there were a better alternative. But as it is, there is no code that creates a lasting addiction effect*, therefore with Morphine/Tramarine's 20u OD threshold and amount of painkiller effect, there are some people in Medical who use Morphine over Mortaphenyl, even when Mortaphenyl is available in the fridge.
> > *There are only a couple lines of code for "addiction" that give the player one message in the chat that says "You feel terrible".
> 
> The problem here, is that there's no situation ATM in which morta+perconol wouldn't be sufficient for any use case, so making tramarine/morphine worse when they already are underused just worsen their position as an option that already has a teinous position
> 
> It's not a bad idea per se, but it should have uses in which you can't just use morta+perc for all the needs, then it would make sense to sell it as more "risky" to use Just making it worse, when it's already underused, just leads to it becoming even less used than already is

I've seen the need for more heavy painkiller use in certain cases where someone is heavily injured, both with brute and burn, but they manage to survive and need to be kept essentially sedated until they can be healed a bit more. In these cases, Oxycomorphine was used which also has an OD limit of 10u, but can't be used with Mortaphenyl. This I believe is when Morphine would be used because Mortaphenyl and Morphine do not cause a drug interaction. The painkiller effect of Morphine is closer to Oxycomorphine than it is to Mortaphenyl which makes me think it should be more similar to oxy than it should Mortaphenyl.

Nonetheless, we've had many changes to medical gameplay for the purposes of realism and I just don't see how it's realistic for Morphine to have a higher OD threshold than Mortaphenyl when it does more than double the painkiller effect.

**Comment by FluffyGhoster** [comment]
> Nonetheless, we've had many changes to medical gameplay for the purposes of realism and I just don't see how it's realistic for Morphine to have a higher OD threshold than Mortaphenyl when it does more than double the painkiller effect.

Realism is rarely a main consideration, you can tank an entire rifle magazine and live to tell just to make an example, while a single hit on the head even from a much less powerful cartridge (eg a pistol) is fairly often fatal in reality

But, apart from that, let's see how it goes

**Review by Arrow768 — APPROVED** [review]

**Review by FluffyGhoster — APPROVED** [review]

**Pull request merged**
