### PR TITLE
NanoUI-Edge

### PR DESCRIPTION
**Pull request by Lohikar**
changes:
- NanoUI will now attempt to use MS Edge if available.

This PR modifies the HTML headers used in NanoUI so that IE will attempt to instead render using Edge if it is available. This appears to have a positive performance impact, as well as it should allow use of HTML5 and CSS3 features in templates.

All NanoUIs I tested were functional, although the modular computer camera monitor had layout issues.

Known broken:
- [ ] PDA - Supply Manifest
- [ ] PDA - News (minor)
- [ ] PDA - Menu (minor)
- [ ] Camera Monitor
- [ ] Modular Computers - Program Download
- [ ] Modular Computers - Sudoku
- [ ] Modular Computers - Lighting Control
- [ ] Omni Filters
- [ ] Omni Mixers
- [ ] Pathogenic Incubator
- [ ] Pathogenic Isolator
- [ ] Radiocarbon Spectrometer
- [ ] Air Alarms (minor)
- [ ] Chemical Dispensers (minor)

### CODE REVIEW

**Comment by skull132** [comment]
Not everyone has edge yet. We gathered stats for this, you should force compat for version 11. You should also remove the shims at that point, to speed up download.

**Comment by Lohikar** [comment]
This doesn't enforce the usage of Edge, it'll just use Edge if it's available, and bar that, the latest IE version available.

XP clients will still use IE8, so removing the shim would break compatibility with them (I don't know how many players actually still use XP).

**Comment by skull132** [comment]
> (I don't know how many players actually still use XP).

We know, though! Not enough to matter.

**Comment by optimumtact** [comment]
>Not enough to matter

wish we had that to

**Comment by Lohikar** [comment]
Checked a few UIs, most seem fine aside from minor layout issues in:
- PDAs
- Air alarms
- Request Consoles
- Chemical Dispensers

**Pull request closed without merging**
