### PR TITLE
Minor mapping improvements

### PR DESCRIPTION
**Pull request by Amunak**
- Camera in Consular Office has been removed for the Consular's privacy. AI can still see in as long as the window tint is off.
 - Added missing bolt buttons for toilettes: engineering, command, patient.
 - Replaced regular bed in ICU with a roller bed.
 - Added a bucket to medical custodial storage.

### CODE REVIEW

**Comment by Amunak** [comment]
!review

**Review by fernerr — APPROVED** [review]

**Review by Geevies — APPROVED** [review]

**Comment by Amunak** [comment]
@fernerr @Geevies I was notified that the rep's office camera should also begone, so I reworked it a little bit:
* The Diplomatic reception now has 2 cameras so that the AI can see inside both offices when the window tint is off. This is ... odd, but IMO better than the alternative of the AI not seeing fully inside.
* The hallway camera is crucial. for this as well as it allows the AI to see the top row of the Consular office.
* I have moved the window tint control in Consular Office to a position where the AI can see it if they open the doors, making it possible to toggle it even when tinted.

### Screenshot time!
#### Windows untinted
dreamseeker_2020-10-25_13-52-14
#### Windows tinted, doors open
dreamseeker_2020-10-25_13-51-26
#### All closed
dreamseeker_2020-10-25_13-41-07

**Comment by Amunak** [comment]
Also there's a bug where the AI view doesn't update when the tint changes, I'll try to fix that (in a separate PR).

**Review by fernerr — APPROVED** [review]

**Comment by SueTheCake** [comment]
I don't see the justification for the removal of these cameras. They've been removed before, and then re-added, so this is just rehashing something that we already went through for no reason, and I suspect this has been spurred by recent events. 

Other corporate liaisons in their office would be prime targets for NT spying - they already spy on each other in more egregious ways, anyway, and while a case can be made for the consular office, one for the liaison office is not. Other sensitive areas on station have security cameras. 

They don't record speech, they don't record emotes, there is nothing preventing 'shady roleplay' from happening in any capacity in these offices, and they both lead into a maintenance tunnel with a secret bar if you want to do something more overt.

**Comment by connorjg1** [comment]
> I don't see the justification for the removal of these cameras. They've been removed before, and then re-added, so this is just rehashing something that we already went through for no reason, and I suspect this has been spurred by recent events.

This is technically incorrect. Consular/Representatives and IAA are different jobs. These offices have only been around a month at most so this isn't "They've been removed before". This was also suggested before any recent events in regards to cameras in the office as amusing as those events were.

> Other corporate liaisons in their office would be prime targets for NT spying - they already spy on each other in more egregious ways, anyway, and while a case can be made for the consular office, one for the liaison office is not. Other sensitive areas on station have security cameras.

The argument that other sensitive areas shouldn't (Especially the entrance to the SAT) is one that is perfectly reasonable. Less cameras in general is better


> They don't record speech, they don't record emotes, there is nothing preventing 'shady roleplay' from happening in any capacity in these offices, and they both lead into a maintenance tunnel with a secret bar if you want to do something more overt

A maintenance area that anyone with maintenance access can enter. 

At the end of the day it's whatever. The difference between these offices having a camera and not having one is absolutely tiny.

**Comment by SueTheCake** [comment]
It is most absolutely not tiny, it is a slippery slope of nonsense because the bar backroom and kitchen cold room cameras were removed with even shakier justification. These I can swallow because the only reason you'd be doing anything in these rooms is murdering someone to death, but this is not the case here.

Liaison and consular are no different in special privileges than IAA were, and they have the same command whitelist as every other command member. They do not deserve special treatment, they have methods of underhandedness available to them, and changes like this reward players for not thinking outside of the box, not having a plan, and just hands them privacy on a silver platter when they don't really need it and have methods available to them to achieve it.

Rewarding lazy players should not be what we do here. This is the last take I'll add on this.

**Comment by fernerr** [comment]
Lessened camera coverage in private settings is something that's aimed for already.
The spying aspect would make sense with cameras that were actually hidden, something more discrete than a rotating globe camera. 
Ping me if you want a feedback thread or want to post something further, this isn't the place for long back and forths.

**Pull request merged**
