### PR TITLE
Adds Europan Smoking Pipe

### PR DESCRIPTION
**Pull request by Snakebittenn**
Sprites by the talented Stryker!

### CODE REVIEW

**Comment by Snakebittenn** [comment]
!review

**Comment by alsoandanswer** [comment]
put it in the pipe selection thanks

**Comment by Snakebittenn** [comment]
No, it shouldn't be renamable

**Comment by Snakebittenn** [comment]
You now can't rename the coat.

**Review by Aboshedab — APPROVED** [review]

**Review by fernerr — APPROVED** [review]

**Comment by Snakebittenn** [comment]
Nevermind that on the coat

**Pull request merged**
