### PR TITLE
IAA_Pen

### PR DESCRIPTION
**Pull request by ben10083**
Removed the many pens in IAA office and added a single multicolored on for each desk.

https://imgur.com/uZlD2jZ

### CODE REVIEW

**Comment by ben10083** [comment]
!review

**Comment by ComradeCorbyn** [comment]
ben you mad lad

if i were to create a sprite for IAA-specific folders, would you be able to add them into the PR?

**Comment by VTCobaltblood** [comment]
Removes so much of the charm.

**Comment by ben10083** [comment]
@ComradeCorbyn I do not feel that IAAs need specific folders tbh
@VTCobaltblood what charm?

**Comment by dragoslava** [comment]
Please use map merge

**Comment by ben10083** [comment]
I will redo this, lets hope it works next time smh

**Pull request closed without merging**
