### PR TITLE
Reverts gas masks being placed inside survival boxes

### PR DESCRIPTION
**Pull request by skull132**
My mistake so here's a clean-up PR.

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
for what purpose

**Comment by skull132** [comment]
The change was unintended (wasn't in the description and I didn't read it out from the code) and is a balance concern. It neuters some random events, weapons, tools.

**Comment by ParadoxSpace** [comment]
that's fair then

**Comment by OneOneThreeEight** [comment]
Darn. I really liked the gas mask sprites tbh. Understandable that they'll be gone, though, I really liked them.

Slightly curious; why wasn't the OG gas mask replaced with the new sprite in the first place? Seems kinda weird to have an alternative gas mask that does nothing different.

**Pull request merged**
