### PR TITLE
Increases overmap hazard density

### PR DESCRIPTION
**Pull request by Alberyk**
Overmap was looking a bit too empty.

### CODE REVIEW

**Review by mikomyazaki — APPROVED** [review]

**Comment by TheDanseMacabre** [comment]
20 still seems a touch low. Seeing as the original overmap on Bay has 34, 30 seems more appropriate, imo. Even 25, I guess.

**Comment by WickedCybs** [comment]
Would agree with above, it'll be more populated but not much more.

**Comment by MortalRed** [comment]
While I don't doubt the ability of the pilots to navigate these obstacles, it has to be noted that in most cases, navigating around an obstacle takes time, time that the expedition crew or miners would much rather spend doing the thing they signed up for. Having too many hazards would have a noticeable impact on a round's pace.

**Comment by JohnWildkins** [comment]
> While I don't doubt the ability of the pilots to navigate these obstacles, it has to be noted that in most cases, navigating around an obstacle takes time, time that the expedition crew or miners would much rather spend doing the thing they signed up for. Having too many hazards would have a noticeable impact on a round's pace.

The point (I think) is to make it so that navigation around them is more difficult in general, which will end up with more choices of "do we navigate through this hazard or this one". There's also other ways to cut down on the downtime in mining in particular that have been or will be done (transit time, airlock cycling, etc.)

**Review by JohnWildkins — APPROVED** [review]

**Pull request merged**
