### PR TITLE
Kataphract Remap

### LINKED ISSUE #14852: Ghostrole Bug - unathi Kataphract ship has no Cryo pods
This means that if someone has to leave they have to do it on another ship which is bad for immersion and i also not always available

### LINKED ISSUE #16424: [Bug]: 3 bugs reported in one - Kataphract Knight Specialist does not have access to Specialist Void Armor, or access to the armory button "shutter control," and when on the Kataphract shuttle, the option to "cycle to exterior" just opens all the doors.
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Third party ship

### Describe the issue

The Knight Specialist does not have access to Specialist Void Armor, or access to the armory button "shutter control."

When in the shuttle, the option "Cycle to exterior" was selected, with no override enabled, just normal vanilla settings, all doors opened, spacing me. Fortunately I was prepared for space, being in an airlock.

### How to reproduce

Play as Kataphract Knight Specialist, try to open Specialist voidsuit sliding glass door, or press armor shutter access button.

As Kataphract Knight, cycle airlock on shuttle to exterior during normal play.

### Round ID

cn6-cAOT

### Staff ckey

YouJustGotOwened

### PR DESCRIPTION
**Pull request by lavillastrangiato**
Completely remaps the Kataphract ship.

Known bugs that were present before I got here:

* ACCESS_KATAPHRACT_KNIGHT/ID variable 114 is not working. For now it has been removed from the map.
kataphract

* Fixes #14852
* Fixes #16424

### CODE REVIEW

**Comment by lavillastrangiato** [comment]
!review

**Review by Eyeveri — APPROVED** [review]
Great job. I don't see anything that throws up any concerns.  Maybe consider cutting every bruiser shell from 3 to 2 per (12 to 8), because right now I think this makes them more armed (ammunition wise) than the Horizon. Not required by me though.

**Comment by Eyeveri** [comment]
image
I was wrong actually, these buttons are upside down. Should be set to dir = 1 instead of dir = 6

**Review by Eyeveri — CHANGES_REQUESTED** [review]
Regarding the buttons above

**Review by Eyeveri — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
