### PR TITLE
Forensic Technician Bay Re-Model

### PR DESCRIPTION
**Pull request by dragoslava**
Re-Models the FT Bay, aswell as adding another slot for a CSI/ FT Duo

https://i.imgur.com/cGioIOt.jpg

### CODE REVIEW

**Comment by Arrow768** [comment]
Screenshot of the mapping changes plese

**Comment by LordFowl** [comment]
Why do we need 2 FTs?

**Comment by dragoslava** [comment]
!review

**Comment by Arrow768** [comment]
This needs a feedback topic (hence the feedback required tag)

Please explain why you believe it is required to have to ft job slots in the feedback topic.

**Pull request closed without merging**
