### PR TITLE
You see me rollin' 2 - Deja Vu Edition - More Roller Bed Tweaks

### PR DESCRIPTION
**Pull request by 1Sparky1**
- Adds brakes, with on-sprite indicators, to both regular and hover roller beds.
- Resprites roller beds to accommodate above indicators, and to be more colourful (NT blue and white)
- Makes clicking on effects (i.e. flour from scrubbers) or lattices (i.e. gratings in maintainance) with roller beds deploy them to their turf

final_beds

Making roller bed QoL changes? This seems familiar.

Edit: Forgot image

### CODE REVIEW

**Review by SleepyGemmy — APPROVED** [review]
consider using overlays for the brake light.

**Comment by 1Sparky1** [comment]
> consider using overlays for the brake light.

There is a slight change around the wheels on the brake sprite, and the hover bed would be difficult to make work with overlays, so I figured this would be best.

**Review by FluffyGhoster — APPROVED** [review]
There is a behavior that, if the mob is gibbed while on the bed, the bed does not collapse, but I do not believe it's due to this PR, so...

**Comment by SleepyGemmy** [comment]
> There is a behavior that, if the mob is gibbed while on the bed, the bed does not collapse, but I do not believe it's due to this PR, so...

make a bug report.

**Pull request merged**
