### PR TITLE
Jumping Over Mines

### PR DESCRIPTION
**Pull request by Geevies**
* You can now jump over landmines and other floor traps.

https://github.com/Aurorastation/Aurora.3/assets/22774890/1887ea1d-0853-4b07-98a5-0ad42f5a4b21

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by FluffyGhoster** [comment]
I don't know how I feel about this, given they're supposed to provide area denial, if you can just jump over them reliably it kind of weakens their use case quite a lot, perhaps add a chance of failure where they trigger?

**Review by Alberyk — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
> I don't know how I feel about this, given they're supposed to provide area denial, if you can just jump over them reliably it kind of weakens their use case quite a lot, perhaps add a chance of failure where they trigger?

to be fair, jumping over them needs you to actually see the mine before walking over it - in a game where you can destroy everything and there's always a second way in "area denial" is really weak and almost irrelevant if it's not a wide thing like void or fire

mines imo are only useful for blowing people up if they don't see them and walk into them

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by FluffyGhoster** [comment]
> > I don't know how I feel about this, given they're supposed to provide area denial, if you can just jump over them reliably it kind of weakens their use case quite a lot, perhaps add a chance of failure where they trigger?
> 
> to be fair, jumping over them needs you to actually see the mine before walking over it - in a game where you can destroy everything and there's always a second way in "area denial" is really weak and almost irrelevant if it's not a wide thing like void or fire
> 
> mines imo are only useful for blowing people up if they don't see them and walk into them

Fair point

**Review by FluffyGhoster — APPROVED** [review]

**Pull request merged**
