### PR TITLE
Adding 'Velvet Rose' to Jukebox

### PR DESCRIPTION
**Pull request by Nerrathiel**
Adding a song to the in game jukebox. Worked fine when tested in game.

### CODE REVIEW

**Comment by Nerrathiel** [comment]
!review

**Comment by Arrow768** [comment]
Under what license is the song you added?

**Comment by Nerrathiel** [comment]
> Under what license is the song you added?

None. It's not published. I made it.

**Comment by alsoandanswer** [comment]
Cool and good, but have you made a post in the forums? So, you know, people like it?

**Comment by Nerrathiel** [comment]
> Cool and good, but have you made a post in the forums? So, you know, people like it?

Oh, didn't know I should. I asked on discord what's needed to add a song and the only thing I was told was copyright. Made a forum post to gather feedback here: https://forums.aurorastation.org/topic/13430-new-song-for-jukebox-velvet-rose-by-naelynn/

**Comment by NonQueueingMatt** [comment]
Is the song meant to be 1 second long?

**Comment by Nerrathiel** [comment]
> Is the song meant to be 1 second long?

As far as I can tell, it's not. The download from this pr works fine and downloads the full version. Not sure what caused it :(

**Pull request merged**
