### PR TITLE
Removes kois from the garden's vendedor

### PR DESCRIPTION
**Pull request by Alberyk**
What the title says, because holy fuck this is not a good idea.

### CODE REVIEW

**Comment by sdtwbaj** [comment]
imma hit that -1

kinda necessary for vaurca to survive, especially on rounds without a gardener.

**Comment by BurgerLUA** [comment]
It's a plant that needs to be managed by trained professionals like Diamond with Flaw who let spores get all over the food in the kitchen, professionally.

**Comment by Alberyk** [comment]
No thanks, the garden is not safe for k'ois.

**Comment by BurgerLUA** [comment]
Could possibly, for balance reasons, make it a contraband item that can be retrieved via emag or wire cutting.

**Comment by skull132** [comment]
Can you make something emag only in the vendor? If we make it hackable literally everyone will hack it regardless.

**Comment by Arrow768** [comment]
Not at the moment. Emagging only effects the access restrictions atm.

**Comment by LordFowl** [comment]
K’ois is still available to botany and xeno botany. This only removes it from public access

**Pull request merged**
