### PR TITLE
[WIP] Unapologetic Mole Buffs

### PR DESCRIPTION
**Pull request by LordFowl**
Implements Talpi, as described here; https://forums.aurorastation.org/viewtopic.php?f=18&t=10452

More comprehensive description pending.

- [x] Core species code
- [ ] Implement mole-man vision code
- [ ] Sprites
- [ ] Climbing mechanics
- [ ] Civilization mechanics (Crafting, construction, hunting, etc)
- [ ] Spawning mechanics (Giving ghosts the ability to spawn as them)
- [ ] Village spawning mechanics (Working with DMMS and mapping in constructables)
- [ ] Balance
- [ ] Testing
- [ ] Lore approval/negotiations

### CODE REVIEW

**Comment by GGSnipa** [comment]
But will I be able to customize my Talpi? Talpi mains need this.

no but on a serious note, how do you intend to do the crafting and village spawns?

**Comment by LordFowl** [comment]
I'm hoping to use code to accomplish the crafting and village spawns, but failing that I might just use interpretive dance and hope the server can just bear with me for a moment.

**Comment by Arrow768** [comment]
Hasnt been worked on in quite a while

**Comment by NiftyBaby** [comment]
NoooooooOooOO!

**Pull request closed without merging**
