### PR TITLE
Adds mechanical traits from origins.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
Redux of #14699

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Review by alsoandanswer — COMMENTED** [review]
You know, the origin trait descriptions should probably be defines themselves as well.
Maybe even paired with the respective trait.

**Comment by NonQueueingMatt** [comment]
> You know, the origin trait descriptions should probably be defines themselves as well. Maybe even paired with the respective trait.

No, because we might want them to be custom or not paired up with a trait (see the Gadpathurian origin).

**Review by Alberyk — APPROVED** [review]

**Review by alsoandanswer — APPROVED** [review]
Fair point.

**Pull request merged**
