### PR TITLE
Potentially fix the crippling lag issue

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
Why is everything on Fire

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Review by Geevies — APPROVED** [review]
dread

**Comment by NonQueueingMatt** [comment]
caused by byond 1755+, unnecessary

**Comment by NonQueueingMatt** [comment]
spoke too soon

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
