### PR TITLE
Mono Eye

### PR DESCRIPTION
**Pull request by Geevies**
* You can now choose to have a missing eye.

image
image

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by alsoandanswer** [comment]
i dont really think adding an entire selection for eyes is very good, doesn't one of muaha's PRs do this already with customizable stuff?

**Comment by Geevies** [comment]
> 
> 
> i dont really think adding an entire selection for eyes is very good, doesn't one of muaha's PRs do this already with customizable stuff?

How?

**Comment by alsoandanswer** [comment]
https://github.com/Aurorastation/Aurora.3/pull/7021

**Comment by Geevies** [comment]
> 
> 
> #7021

That just adds a bodymarking that goes over the eye, though? It doesn't work for Skrell or Vaurca?

**Comment by alsoandanswer** [comment]
can't it just be a bodymarking then?

**Review by Alberyk — APPROVED** [review]

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
That's a good point. Why _isn't_ this just a recolorable body marking?

**Comment by Geevies** [comment]
> 
> 
> That's a good point. Why _isn't_ this just a recolorable body marking?

becaues this is reductive. if the eye is gone, we can make new bodymarkings that go in its place, like an eyehole that is smaller than the original eye sprite, or a scar across it. if it's a recolourable body marking, it'd be extra tedium to find the correct body colour, and it'd be relying on layering staying the same in the future

**Pull request closed without merging**
