### PR TITLE
Shuttle update: Part Three: The Merchants Invest

### PR DESCRIPTION
**Pull request by fernerr**
This is part 3 of the work of the big shuttle update started by Poze (#5771, description not up to date.) with more to come as that pr is split up into more manageable chunks. (Previous part: #7457)

**In this episode the merchant base and ship gets a new coat of paint via some new private investments.**

merchant 7

**Features:**
 - One often requested feature has been is the ability to easily lock your ship if you decide to trade and interact with some of the crew onboard, so now there's a button at the very entrance to lock a blast door to prevent greytide intrusion as easily.
 - The cockpit now has the ability to deploy shutters to both protect you from potential carp intrusion and to keep your clientele anonymous whilst you discuss your nefarious backroom dealings.
 - The main cabin in the shuttle now has a net turret to wrangle any uncooperative customers and free coffee is available at the entrance to lure in prospective customers.
 - A nitrogen canister along with some vox voidsuits have been added so vox merchants don't have to worry about suffocating on every visit.
 - Some additional materials, item spawns and cash has been provided (6k vs 4k) to open up more opportunities to vary things up for the merchant.
 - Tweaked the copy turf code, so floors shouldn't reset if you've changed them from tiling to wood for example.
 - Merchant assistants can now be from a wider range of species and they spawn with a randomized outfit instead of always a grey jumpsuit.

### CODE REVIEW

**Comment by Aboshedab** [comment]
I'm a moron.

**Comment by Geevies** [comment]
Even Gods can bleed.

**Comment by runecap** [comment]
Will wood be a new material that spawns in the merchant base? It's good for customizing the shuttle.

**Comment by fernerr** [comment]
> Will wood be a new material that spawns in the merchant base? It's good for customizing the shuttle.

Yes.

**Comment by fernerr** [comment]
!review

**Comment by fernerr** [comment]
Please make sure #7577 is merged before this one

**Pull request merged**
