### PR TITLE
Tactical Coifs Fit Unathi and Tajara

### PR DESCRIPTION
**Pull request by CyberSpyXD**
Sec got tac coifs this year but Tajara and Unathi weren't able to larp it up with them as they lacked unique sprite sets, which made the side sprites of the coif not fit them.

Now they mostly do fit.

wearing it in a worn slot
image

wearing it as an accessory (lets hair go over it)
image

### CODE REVIEW

**Comment by CyberSpyXD** [comment]
!review

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
sprite sheets are depreceated, use icon_supported_species_tags

**Comment by CyberSpyXD** [comment]
> sprite sheets are depreceated, use icon_supported_species_tags

It's beyond my ability to make it so the icon auto adaptation also affects the sprites when they're worn as an accessory. That's an important function for the coifs, so it can't be removed as a feature.

**Comment by CyberSpyXD** [comment]
The PR can stay frozen for now, someone else might be able to do the accessory thing soon enough.

**Comment by alsoandanswer** [comment]
superceded by https://github.com/Aurorastation/Aurora.3/pull/17625

**Pull request closed without merging**
