### PR TITLE
Fastboot

### PR DESCRIPTION
**Pull request by Lohikar**
Adds a config option that disables some time consuming bootup steps that aren't generally required for debugging.

### CODE REVIEW

**Comment by skull132** [comment]
Not certain if this is a good idea. Should just rename it to toggle sunlight.

Duplicate control over features in config is bad, leads to mistakes.

**Comment by Lohikar** [comment]
This doesn't just toggle sunlight, it's also turning off icon_smoothing prebake.

**Comment by skull132** [comment]
Mkay, as long as it doesn't apply double conditions to things you can already turn off via config (like asteroid generation).

**Comment by skull132** [comment]
Also, is there a way you can somehow integrate this into Travis? To speed up testing. Perhaps modify the setup scripts which copy config to also replace `# FASTBOOT` with `FASTBOOT`.

**Comment by Lohikar** [comment]
Will look into it tomorrow.

**Pull request merged**
