### PR TITLE
Makes records bigger.

### PR DESCRIPTION
**Pull request by MarinaGryphon**
* Records are now eight times bigger.

### CODE REVIEW

**Comment by skull132** [comment]
Not a fan.

Imo we should be looking to make the records more structured and compartmentalized. Giving the player more control over them. Instead of just giving them a largely text field to play with. There's only so much unformatted text someone wants to read.

**Comment by Arrow768** [comment]
Needs to be verified as functional beforehand.
We had some issues with records being too long to be handled by the sql driver / implementation of it in byond.

**Comment by GMR25** [comment]
> Not a fan.
> 
> Imo we should be looking to make the records more structured and compartmentalized. Giving the player more control over them. Instead of just giving them a largely text field to play with. There's only so much unformatted text someone wants to read.

One might argue there's more control in the text field and allowing the player themselves to format it, and add what they desire. But I suppose that's a discussion for a forum thread if anything. Tho I don't think record field needs to be bigger, as it may just encourage 'walls of text' or 'novels'.

**Comment by Mwahahahaha** [comment]
I think this is a fantastic change for quite a lot of reasons.
I just don't know if I'm allowed to discuss all those here or...

**Comment by MarinaGryphon** [comment]
> Not a fan.
> 
> Imo we should be looking to make the records more structured and compartmentalized. Giving the player more control over them. Instead of just giving them a largely text field to play with. There's only so much unformatted text someone wants to read.

We could add formatting to it in a later PR. Like pencode.

**Comment by Mwahahahaha** [comment]
Likewise, I personally feel it can actually be pretty readable even without BBCode to shape it up even more. Even more so with this new NanoUI look for records than the previous one.

**Comment by Geevies** [comment]
@MarinaGryphon Still interested in this, or can it be closed?

**Comment by skull132** [comment]
More formatting (better templates ingame) is preferred over simply MAKE BIGGER. And also needs testing. So closed and denied.

**Pull request closed without merging**
