### PR TITLE
Fixes eye color in setup.

### LINKED ISSUE #3336: Eye Color
Eye color (human, character creator) will only let you set variations of green or pinkish-purple, any other color will revert to those two or black.

### PR DESCRIPTION
**Pull request by MarinaGryphon**
Damn you, Lohikar, and your newfangled copy-paste. Replaces an erroneous `GetRedPart(new_eyes)` with the correct `GetBluePart(new_eyes)`.

Fixes #3336.

### CODE REVIEW

**Comment by Lohikar** [comment]
This wasn't even copy+paste, just a brain fart.

**Comment by Lohikar** [comment]
Fixes #3336.

**Comment by Lohikar** [comment]
Bad changelog.

**Comment by MarinaGryphon** [comment]
Haha, whaaat? Nooooo... no such thing.

**Pull request merged**
