### PR TITLE
Modular Wristbound Sprite Revert

### PR DESCRIPTION
**Pull request by Geevies**
* Wristbound sprites have been reverted, and their on-mob sprites have been removed.

https://forums.aurorastation.org/topic/14816-adjust-the-wristbound-computer-sprites

image

Feedback thread:
https://forums.aurorastation.org/topic/14816-adjust-the-wristbound-computer-sprites

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Review by Snakebittenn — APPROVED** [review]

**Comment by alsoandanswer** [comment]
just remove the onmobs would do

**Comment by Geevies** [comment]
The feedback is about the loss of colour as well, so no.

**Review by furrycactus — APPROVED** [review]

**Comment by furrycactus** [comment]
Approving because it looks functionally sound, but DNMing for for feedback and shit for the next couple days and stuff.

**Pull request merged**
