### PR TITLE
Adds Service Airlocks

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR adds two service airlocks, one regular and one with glass. they are green with a lime stripe.
the default airlock sprite is now plain metal instead.

the plan is to start mapping the new service airlocks to where they are applicable, when this PR is merged.

note: icon diff previews look a bit janky, but it looks fine ingame.

images:
image
_fig. 1: new default - service airlock - glass service airlock_

image
_fig. 2: ingame._

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Comment by mikomyazaki** [comment]
As I've already said elsewhere (just repeating for the PR notes) - I don't think this is distinctive enough relative to the maintenance doors. I think Service will need a more noticeable colour assigned to it if it wants specific doors, which I'd like to see.

**Comment by SleepyGemmy** [comment]
!wip

**Comment by SleepyGemmy** [comment]
!unwip

**Comment by SleepyGemmy** [comment]
!wip

**Comment by SleepyGemmy** [comment]
!review

**Review by JohnWildkins — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
