### PR TITLE
Replacing old vent sprites with new ones

### PR DESCRIPTION
**Pull request by nonnoanselmo**
This PR replaces the old vents and scrubber sprites with new ones used also on /tg/.

These sprites are fully animated and would blend better with the overall environment of the new tiles.

### CODE REVIEW

**Comment by nonnoanselmo** [comment]
!review

**Comment by nonnoanselmo** [comment]
ventsrnice

**Comment by Geevies** [comment]
The old sprites? The ones that got implemented a month or so ago?

**Comment by Alberyk** [comment]
Fairly sure that people are already working on tweaking the ones we have. I am against porting more tg sprites.

**Comment by Geevies** [comment]
closed by author request

**Pull request closed without merging**
