### PR TITLE
Tiny newspaper and bridge crew cap spelling fixes.

### PR DESCRIPTION
**Pull request by KingOfThePing**
The newspaper had some artifact in it's title and the description of the bridge crew cap sounded weird af. Fixed both.

### CODE REVIEW

**Comment by KingOfThePing** [comment]
!bugfix

**Comment by KingOfThePing** [comment]
!review

**Review by mikomyazaki — APPROVED** [review]

**Comment by KingOfThePing** [comment]
!bugfix

**Comment by KingOfThePing** [comment]
why me no able to add labels, grug angry

**Review by alsoandanswer — APPROVED** [review]

**Pull request merged**
