### PR TITLE
Adds gun safety system

### PR DESCRIPTION
**Pull request by mikomyazaki**
Sounds + Icons taken from bay:
[Sound](https://github.com/Baystation12/Baystation12/commit/2556d3f227f65163261599ccb1227c08fba3b21f) added by Higgins
[Icons](https://github.com/Baystation12/Baystation12/pull/21749) by comma (chinsky)

Adds a safety system for all guns except mech guns because they have their own UI stuff. Will show a little marker on your gun when held.
Toggle safety by ctrl+clicking the gun, or using harm intent + shooting will auto-disable the safety.

Also tidies up code a bit.

### CODE REVIEW

**Comment by mikomyazaki** [comment]
!review

**Comment by OneOneThreeEight** [comment]
We already have an opt-in safety system, no?

**Comment by NonQueueingMatt** [comment]
There's already a preference for an intent check ye. It might be worth removing that as well, @mikomyazaki.

**Comment by mikomyazaki** [comment]
Removed the old safety system. Thanks.

**Pull request merged**
