### PR TITLE
Simple Elevator Door Balance Changes

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Overview
An AI can easily shutdown antags or crewmembers by bolting open a singular elevator door. This is a dumb oversight that should be tweaked. This PR makes it so that in order to interface with an elevator door, the AI must hack into it. This takes quite a bit of time so this should give antags some amount of time as opposed to no time at all. This PR also makes it so that doors can crush all mobs with it's safeties disabled, and that disabling the ID scan on an elevator door has it open normally like an airlock.

Feedback Thread: https://forums.aurorastation.org/viewtopic.php?p=107870#p107870

### CODE REVIEW

**Comment by BurgerLUA** [comment]
!review

**Comment by dragoslava** [comment]
Honestly this needs a feedback itself as the general opinion on thisd in the past has been mixed

**Comment by BurgerLUA** [comment]
A thread will be up tomorrow, of course. I'm finishing another PR as well that will share the same feedback thread.

**Comment by Matthew951** [comment]
Or we could replace one of the elevators with stairs

**Comment by LordFowl** [comment]
No.

**Comment by skull132** [comment]
Closed.

Bad fix for a potentially non-existent issue. It'd be better to maybe add a ladder or few to the sublevel. Or to just accept this as a possible ingame encounter which requires the players to think.

**Pull request closed without merging**
