### PR TITLE
Infirmary quality of life changes & additions

### PR DESCRIPTION
**Pull request by Hunttark**
- The third attempt, merge conflict encouraged me to restart and this time include all my V2 changes!
- Infirmary equipment additions include but are not limited to vitals scanner 1x, secure chemistry fridge, secure pill cabinet, 6x oxygen tanks for IVs, monkey cube box, suit-cycler in EMT.
- Psych-office layout changes, the addition of a patio, and some quality of life improvements to make the area more compelling for RP.

- Swapped the recovery ward and exam room, hopefully, exam room will get some further use and potential antaggery
- I probably forgot something, but nothing major that can not be seen in diff check.

### CODE REVIEW

**Comment by Hunttark** [comment]
!review

**Comment by Hunttark** [comment]
Also, do not worry. If I have to do a V4 of Infirmary changes because of another merge conflict after four days, I will only burn half a building down

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
The cat should probably be put in a seperate PR.

**Comment by Hunttark** [comment]
> The cat should probably be put in a seperate PR.

Okay, if I did this right, I reverted the changes. If I did this wrong, I somehow screwed stuff up. I think I did it right, I hope.

**Review by alsoandanswer — APPROVED** [review]

**Comment by mikomyazaki** [comment]
The item additions are good.

> Swapped the recovery ward and exam room, hopefully, exam room will get some further use and potential antaggery

I doubt that it will get any additional use (except by taking that use away from the recovery room). But we can hope... I think I prefer it being on the lower floor.

The only change I want to request is that you change the psych office disposals into a small disposals unit like every other room in medbay uses, it really stands out in the small room.

**Review by mikomyazaki — CHANGES_REQUESTED** [review]
The item additions are good.

> Swapped the recovery ward and exam room, hopefully, exam room will get some further use and potential antaggery

I doubt that it will get any additional use (except by taking that use away from the recovery room). But we can hope... I think I prefer it being on the lower floor.

The only change I want to request is that you change the psych office disposals into a small disposals unit like every other room in medbay uses, it really stands out in the small room.

**Review by mikomyazaki — APPROVED** [review]

**Pull request merged**
