### PR TITLE
Langserver static analyzer found that much warnings

### PR DESCRIPTION
**Pull request by Megmeehey**
* I just opened Aurora project, and let analyzer do his job. Mostly, it finds misused `as ...` clauses, mispaced dots, unused defs or undefining unexisting defs, empty for() etc.
* Also, `STUTTER` disability define and `STUTTER` damage define were intersecting. So, I renamed defines for disabilities.

No changelog needed, this one is merely refactoring stuff

### CODE REVIEW

**Comment by Megmeehey** [comment]
The only thing, I did not figured out how to fix is the 
изображение
This define (well `THIS_PROC_TYPE_WEIRD` actually) uses like ...... in definition, and I have no clue how that works.

**Comment by Megmeehey** [comment]
!review

**Comment by skull132** [comment]
`PROC_LOG_` macros are fun and can be nixed. They were a curiosity ported from TG.

**Comment by Megmeehey** [comment]
Removed proclog macros. There were only 5 places, where those were used, and I replaced that with simple `log_debug(...)`

**Comment by Geevies** [comment]
What the heck is going on here. @Megmeehey Thoughts?

**Comment by Megmeehey** [comment]
> What the heck is going on here

Static analyzer fixes and nothing more. You can do that yourself with spacemaniac tools.
 
> Mostly, it finds misused as ... clauses, mispaced dots, unused defs or undefining unexisting defs, empty for() etc.
Also, STUTTER disability define and STUTTER damage define were intersecting. So, I renamed defines for disabilities.

I have no intention of updating this, so this PR can be omitted.

**Comment by skull132** [comment]
I have my own, less conflicted version about to run live. So closing this one.

**Pull request closed without merging**
