### PR TITLE
Merc Shuttle Has Windows at the Cockpit Again + Inflatables

### PR DESCRIPTION
**Pull request by WickedCybs**
The change to the Horizon had the Merc ship changed a bit, and one of those changes was essentially making it so the entirety of the ship is only surrounded by un-interactable walls that can only be blown open. The only entrance would be the dock. The windows were an important part of the balance and aesthetics, giving people options. So I've added those back.

image

The reinforced windows have had their health buffed compared to the usual.

### CODE REVIEW

**Comment by WickedCybs** [comment]
!review

**Comment by WickedCybs** [comment]
I fucked up and made other windows stronger

**Comment by WickedCybs** [comment]
!wip

**Comment by WickedCybs** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Review by JohnWildkins — APPROVED** [review]

**Pull request merged**
