### PR TITLE
April Update - Dueling

### PR DESCRIPTION
**Pull request by Kaedwuff**
Adds a new Dueling tab to the loadout.  People may now select a single gun to bring to work for dueling purposes.

### CODE REVIEW

**Comment by Pacmandevil** [comment]
saying it's an april fools joke kind of defeats the point of it being an april fools joke dude

**Comment by Kaedwuff** [comment]
Only for the people visiting the github.

I"m pretty sure there is 0% chance anyone would actually let me add real guns to the game for no reason, so explanation was required. The rest of the players who do not visit the github will get the full experience of the joke.

**Comment by Kaedwuff** [comment]
On the suggestion of Arrow, this PR has some content added. 

!review

**Comment by skull132** [comment]
Well, April Fool's is over. So PR closure time.

**Pull request closed without merging**
