### PR TITLE
[WIP] Attempt fix bridge remapping

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Trying to save lordpwner's work.

Do not merge.

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!do not merge

**Comment by FluffyGhoster** [comment]
@AuroraBirdie clone my branch, copy the file in some folder and open the map with strongdmm and select the area that you have remapped, CTRL+C it, clone master into your repo with another branch name, open the same map in the same instance of strongdmm, CTRL+V it, if it's not aligned CTRL+Z and redo until it's aligned correctly, and you should be able to PR it with minimal effort

**Comment by Eyeveri** [comment]
Glad you were able to fix this. I wasn't even able to load the map in.

**Comment by AuroraBirdie** [comment]
Reopenned my PR, haven't got a merge conflict yet. Appreciated. Also it didn't add the do not merge

**Comment by FluffyGhoster** [comment]
np

**Pull request closed without merging**
