### PR TITLE
Solution for Issue - 15912

### PR DESCRIPTION
**Pull request by Eyeveri**
Solution for issue 15912. Removes two potted plants. I'll probably submit a PR that'll allow people to walk past plants again. Maybe. 

Screenshots of change - 
deathtoplants
deathtoplants2

### CODE REVIEW

**Comment by Eyeveri** [comment]
!bugfix

**Comment by Eyeveri** [comment]
!review

**Comment by Greenjoe12345** [comment]
you'll want to put fixes #15912  on the desc so it'll auto-close that when merged
though a better solution would be to see about why it's made them solid, rather then removing them entirely, imo

**Comment by KingOfThePing** [comment]
This is not a bugfix for the submitted issue. The issue is that these two potted plants (or plants in general) have collision, when they should not. You are not fixing that.

**Comment by SleepyGemmy** [comment]
superseded by PR 15914.

**Pull request closed without merging**
