### PR TITLE
Revert and replace #4127 -- Funk jood, round deux

### PR DESCRIPTION
**Pull request by skull132**
* Reverts the new chemicals and their effects as implemented in #4127 due to their unnecessary severity.
* Replaces the reverted mechanics with new mechanics which seek to accomplish a similar thing. Mobs now have an `nutrition_attrition_rate` factor, which is a multiplier describing how fast they grow hungry. By default, the multiplier is `1`. Only eating healthy/chef food will see to it that said multiplier remains at `1`.

  Eating bad food, specifically food with `nutriment/synthetic` in it, will result in the multiplier gradually increasing. This will make the character grow hungry faster, if their only source of sustenance is junk food. The maximum value of the multiplier is up for debate, but it should be no higher than `2`. Even that may be stretching it.

  The intent is that, in the worst case scenario, all this'll do is make you go and get food from the vending machines more often. And slightly impact your ability in high stress situations. Nothing severe, like heart damage.

* Also cleans the everliving fuck out of the junk foods file.

TODO:
 - [x] Run some maths and figure out the proper rates for increasing the attrition rate and its maximum value.
 - [ ] Run some searches for remaining notes of junk food compounds.

### CODE REVIEW

**Comment by BurgerLUA** [comment]
Honestly seems inappropriate as I was planning on implementing this, however I was waiting for the mental medication overhaul to finally merge into development which has yet to merge.

**Comment by BurgerLUA** [comment]
You're likely still going to get bitched at by other players as well. It's clear from the various feedback thread that they don't want any nerfs to junkfood, but buffs instead. You're effectively replacing the devil with just another demon.

**Comment by skull132** [comment]
Re: inappropriateness. You're free to PR your own alternative, and then we'll see which one is more suitable. I just had this specific idea planned out and wanted to execute. So I did. Doesn't mean this has to be the final form.

And I'm hesitant to use buffs. Buffing is more likely to result in power creep than nerfing certain things. (In general, negative feedback is better.) But I guess we'll see.

**Comment by BurgerLUA** [comment]
My idea could be implemented alongside yours. Yours add nerfs to junkfood while mine adds buffs to mine. We'll see what happens.

**Comment by BurgerLUA** [comment]
This is probably highly inappropriate given how im the demon of this sort of thing, but the default hunger rate should be slightly slower.

I'm predicting that a lot of people will get hungry really fast and they're going to unironically blame me.

**Comment by skull132** [comment]
ye I've yet to tweeeeaaak that number. I need a quick reference on how much shit is eaten to regularly fill the foodbar.

So like. Tomorrow:tm: this will be ready, I promise.

**Comment by skull132** [comment]
HOKAY, QUICK MAFFS.

The idea is that shoving down 400 units (BASE_MAX_NUTRITION) amounts of shit will make you go hungry twice as fast. This comes from the observation that people usually only eat half to two-thirds of their actual max nutrition, so they'll rarely get the actual doubled hunger rate off of 1 feeding.

The way I reached the nutriment_factor value of 0.002, `(REM * 4)/BASE_MAX_NUTRITION`, is this: every time in digest we get roughly `removed = REM * 4`. And that's as far as I'm able to explain _why_ I got that equation atm but I suspect it works. 🤔 An integral was used at one point as well, so surely it's correct. 

ANYWAYS THIS SHOULD BE FINE AND IS EASILY TWEAKEABLE PR IS READY FOR MERGE.

**Pull request merged**
