### PR TITLE
Adds flagpatches to the loadout.

### PR DESCRIPTION
**Pull request by TheStryker**
Adds a selection of flagpatches that can attach to jumpsuits and vests.
image
image
image
image

Special thanks to the human lore team for helping with some of the descriptions.

Since the loadout accessories tab is getting a bit bloated, I could try to work on an "accessories - vests" or somesuch tab, but to be honest I have no idea how to do that.

### CODE REVIEW

**Review by KingOfThePing — APPROVED** [review]

**Comment by ChevyChevron** [comment]
The colors on some of the patches' on mob sprites seem to be a bit off. Visegrad is the one I noticed, having red on the bottom and green on the left when they should be reversed.

**Comment by TheTrollDoctor** [comment]
Love this addition! I think you might wanna tweak the Fisanduh onmob sprite, maybe removing the top left yellow pixel representing the star, since as-is it looks almost identical to the Hegemony onmob. Would also suggest making the NKA blue a bit brighter/more prominent, as it's a bit hard to make out and the flag is p hard to identify from just the white.

**Review by Alberyk — APPROVED** [review]

**Review by SleepyGemmy — APPROVED** [review]
extremely good PR.

**Comment by TheStryker** [comment]
image
Fixed the Visegrad and colorable flag patches.

**Comment by ChevyChevron** [comment]
Corrected Visegrad patch still seems incorrect. I've attached what it should probably look like, going off the orientation of colors on the flag. I promise I'm not trying to be nit-picky here.
image

**Comment by TheStryker** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
