### PR TITLE
Removes the roof level

### PR DESCRIPTION
**Pull request by Alberyk**
What it says in the title. We have way too many z-levels and looks like it is getting on the way of memory/performance.

### CODE REVIEW

**Comment by Cnaym** [comment]
Would it be like Z level 8 and 2 then?
This is a massive balance change for movement outside, antag access to the bridge and telecomms and so on. It would also cost us a set of solars that are active from round start to keep lowpop floating, making solars useless. (~300kw out of ~700kw less).
The construction level would be a more efficent cut IMHO, since it is only used by psychologists(who can have their office almost anywhere), virology(which is rarely used and likely to be removed) or mining(which has other z levels to pick).

Would this change affect carp migrations size or absolutely kill Tue surface level?

**Comment by Alberyk** [comment]
There are solars on telecomms too. Carp migration should remain the same, they never moved to other levels at all anyway. Also, removing the construction level is far more work and would remove more stuff than just cutting the roof level.

**Comment by Alberyk** [comment]
The carp migration in other levels will likely remain unchanged. Solars were never really enough to power the station, even under low pop or something. I don't think that anything is really going to be affected because the roof level barely had anything of value. And all the ladders and stuff were removed.

**Comment by Cnaym** [comment]
The station can be fully powered by solars. The lowpop no engi idea was to give the station some sort of power, over no power at all. Roof solars provide ~300kw while the telecomms solars are roughly 200kw each. All solars active results in a stable 700kw, which is enough for the station + shields if setup correctly. Little side issue being the telecomms solar not being stable due to the roation and shadow calculations  (300x 200kw results in roughly 400kw, due to the sun never reaching all of them, while the roof always has full coverage).
Not to ride on the ladder joke, but removing ladders =/= fixing the holes.

**Comment by skull132** [comment]
> The station can be fully powered by solars. The lowpop no engi idea was to give the station some sort of power, over no power at all. Roof solars provide ~300kw while the telecomms solars are roughly 200kw each. All solars active results in a stable 700kw, which is enough for the station + shields if setup correctly. Little side issue being the telecomms solar not being stable due to the roation and shadow calculations (300x 200kw results in roughly 400kw, due to the sun never reaching all of them, while the roof always has full coverage).
> Not to ride on the ladder joke, but removing ladders =/= fixing the holes.

On the flip side, the interstitial level is important as an expansion and mining level. And in theory could easily be opened up more with later map edits between it and the roof level.

**Comment by Brayyce** [comment]
Has the Z-level always caused a problem like this? 

While I'll miss the niche content that's there. If a level had to be sacrificed this, or the blank level would be it. 

@Alberyk When I checked the Ladder near the pool up to the old Running track was still intact, and most of the pipes, and wires heading upward still existed.

**Comment by Alberyk** [comment]
@Brayyce Whatever was changed, likely all the light and icon fuckery, has increased our memory usage. The roof level is not really used for anything important and uses a lot of open spaces.

All ladders should be removed, the pipes and stuff should probably not get on the way of anything.

**Comment by Shelkad** [comment]
@Alberyk Won't removing unused sector in some part of the sub-levels would be more efficient in term of objects removed than the roof level? Thinking for example about medical where nobody ever use the long stay ward and quarantine will also be pretty useless now that virology is cut off.

**Comment by Alberyk** [comment]
@Shelkad Removing parts of the sublevel won't have the same effect as removing an entire z-level.

**Comment by skull132** [comment]
> Has the Z-level always caused a problem like this?
> 
> While I'll miss the niche content that's there. If a level had to be sacrificed this, or the blank level would be it.

The issue isn't any Z-level in specific, or Z-levels in general. It's just that our memory usage at runtime has increased to a point where we're regularly running over BYOND's 1.8 gigabyte limit, and thus crashing. Removing a Z-level is the easiest way to stem it until we can implement some tooling to figure out what the fuck is going on. And if we _do_ figure out what the fuck is going on, it might be that the memory usage cannot be stemmed without removing more important features than a non-critical Z-level.

> Won't removing unused sector in some part of the sub-levels would be more efficient in term of objects removed than the roof level? Thinking for example about medical where nobody ever use the long stay ward and quarantine will also be pretty useless now that virology is cut off.

Eh. Debatable. Likely though, removing 255^2 tiles of space will have a more noticeable effect on memory than removing a few objects here and there.

**Pull request merged**
