### PR TITLE
i sepnt  thirty minutes trying to work out how to make ap ull request for TOWEL VIOLENCE      

### PR DESCRIPTION
**Pull request by Ornias**
_**adds GRATUITOUS TOWEL VIOLENCE**_

### CODE REVIEW

**Comment by Ornias** [comment]
how do  i edit these after i've oepend them i've just ahd a # **_REALLY GOOD IDEA_**

**Comment by Alberyk** [comment]
what.

**Comment by Fire-and-Glory** [comment]
is this real

**Comment by Lohikar** [comment]
Couple issues:
- This exact code is already in the codebase.
- You didn't include the new file in the compile.

Closing this, feel free to ask for it to be reopened if you add something.

**Comment by Ornias** [comment]
pelase reopen: i changed the towel file : )

**Comment by Lohikar** [comment]
Ah, I see what you did. You still need to move the file to the correct location or just edit the existing one.

**Comment by Ornias** [comment]
ok i'll do it

**Comment by Ornias** [comment]
i don't know how

**Comment by Fire-and-Glory** [comment]
>force 1000

**Pull request closed without merging**
