### PR TITLE
Prescription Overhaul

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Overview
As a chemist I find it increasingly annoying to deal with snowflake medication requests. Record formatting is a joke, and the fact that I have to scan through a wall of text of someone's poorly written medical record to get their prescription is incredibly unrealistic. In reality, all you get is a prescription note from a doctor that's neatly printed, visible, and formatted. Dealing with all this nonsense genuinely makes me not want to play chemist despite being one of the only chemists that actually plays.

This does the following things:
- Makes medication a loadout option that allows the user to spawn in with the medication. It makes absolutely 0 sense from a gameplay, roleplay, and realistic standpoint that the chemist has to provide medication themselves upon request.
- Spawns the user with a piece of paper stating that they're allowed to be carrying that medication on station. A copy of this paper is sent to the chemist so if they're unoccupied, they can produce spare medication if needed instead of having to scan records.
- Limits the medication that someone can be prescribed to. No more 10 stage medication recipes. No more asking for dylovene or tramadol. No more prescribing super strength antipsychotic medication that they give to calm down patients at mental wards.
- Setups a universal system of doses. No longer will I have to deal with annoying or nonsensical dosage types. It's all universal now and it all makes sense.

## WIP
Things will need to be tweaked and a new policy would need to be put into effect regarding medication. Feedback would be needed on a change such as this.

### CODE REVIEW

**Comment by BotBOREALIS** [comment]
Icons with diff:
<details><summary>icons/obj/library.dmi</summary>

Key | Old | New | Status
--- | --- | --- | ---
minifax||minifax|Created
minifax_receive||minifax_receive|Created
minifax_receive[1]||![minifax_receive[1]](http://images.aurorastation.org/images/48d4678e56c072623bdd9c74480ed6d7.png)|Created
minifax_off||minifax_off|Created
</details>

**Comment by BurgerLUA** [comment]
!wip

**Comment by skull132** [comment]
> Makes medication a loadout option that allows the user to spawn in with the medication. It makes absolutely 0 sense from a gameplay, roleplay, and realistic standpoint that the chemist has to provide medication themselves upon request.

A part of me wants to point out the cognitive dissonance in attempting to pursue multiple PRs which force someone to rely on the presence of ingame characters, and then doing this. :thinking: Just a passing thought.

Shit posting aside.

> Spawns the user with a piece of paper stating that they're allowed to be carrying that medication on station. A copy of this paper is sent to the chemist so if they're unoccupied, they can produce spare medication if needed instead of having to scan records.

Make it still leave a mark in the records as well. So the chemist is aware of shit and can spot forgeries more easily.

**Comment by BurgerLUA** [comment]
@skull132 
There is a difference between asking for food and asking for a 10 stage chemical recipe.
There is a difference between the chef striking up a conversation while the food is cooking and a chemist making awkward small talk about the fact that they have a mental illness.
There is a difference between spending time making snowflake prescription medication that only one person can use and making food that everyone can eat.
There is a difference between the chemist having everything to do and having no time for depression RP and the chef having really nothing to do and needed much needed RP.
There is a difference between not being able to take your medication because there is no chemist, and still being able to suit your needs because there are snack vendors across the station.

**Pull request closed without merging**
