### PR TITLE
Adds the NT Mk43 Semi-Automatic Rifle

### PR DESCRIPTION
**Pull request by Geevies**
As suggested by this thread: https://forums.aurorastation.org/topic/10991-the-nt-mk43-semi-automatic-rifle/

It also adds rubber 7.62 rounds, each doing 15 brute and 65 agony damage.

### CODE REVIEW

**Comment by Geevies** [comment]
Currently it doesn't spawn anywhere, and a better description is pending. I think I'm going to wait on all the pending mapping changes to complete before I mess around with that.

**Comment by skull132** [comment]
WIP for a month and massive icon conflicts. Closed.

Feel free to reopen once updated.

**Comment by Geevies** [comment]
oh god

**Comment by NonQueueingMatt** [comment]
You can't escape the icon conflicts geeves

**Comment by Geevies** [comment]
watch me whip

**Pull request closed without merging**
