### PR TITLE
Adjusts sanasomnum injector cost

### PR DESCRIPTION
**Pull request by kyres1**
This PR adjusts the sanasomnum prices from 2 to 9 telecrystals, meaning mercs/ninjas can only purchase one. Weaker antagonists such as traitor and burglar are still able to purchase two, but only if they almost explicitly save for it (since it leaves them with a total of 2 telecrystals.) Extraordinary circumstances like looting your buddy's corpse would still give you one extra shot at using it, so you're not completely without hope even then, but at least you have to do something to obtain it.

The thread for this is here; 
https://forums.aurorastation.org/topic/17684-limit-sana-injectors/

### CODE REVIEW

**Comment by kyres1** [comment]
!review

**Comment by NonQueueingMatt** [comment]
I dont think the cost should be raised, rather the injectors should just be limited to 1 per uplink

**Comment by SleepyGemmy** [comment]
what matt said. items should not be cost controlled if possible.
ideally, wait for #14999 to get merged.

**Comment by kyres1** [comment]
I did not realize dreamy's PR was up. Will remake this later with that used

**Pull request closed without merging**
