### PR TITLE
Unathi Trawler

### PR DESCRIPTION
**Pull request by EJDenton**
Adds a new civilian unathi ship, intended to fly into shoals to harvest carp.

image

### CODE REVIEW

**Comment by EJDenton** [comment]
!wip

**Comment by EJDenton** [comment]
!review

**Comment by DreamySkrell** [comment]
image
areas file name should be consistent with other files here

**Comment by DreamySkrell** [comment]
image
replace this air tank with air canister on a connector, cause there is no way to refill air of this tank rn

**Comment by DreamySkrell** [comment]
image
do not change layer of pipes/pumps/etc

image
generally just don't change the layer variable of anything

**Comment by DreamySkrell** [comment]
image

don't have to change the large tank/chamber now, but in the future use `/obj/effect/map_effect/marker/large_tank`, see civ yacht or scc scout for example

**Comment by DreamySkrell** [comment]
image
use `/obj/effect/map_effect/window_spawner/full/shuttle/mercenary` for all the windows so they get window frames matching the walls

**Comment by DreamySkrell** [comment]
update your branch from master as it is outdated by over two weeks

**Review by DreamySkrell — APPROVED** [review]

**Review by DreamySkrell — APPROVED** [review]

**Review by alsoandanswer — APPROVED** [review]

**Pull request merged**
