### PR TITLE
re-adds radio sounds, properly this time

### PR DESCRIPTION
**Pull request by alsoandanswer**
they should have proper pauses and checks and shit, and should actually be properly balanced because I ported these from Bay

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by skull132** [comment]
Results from the test merge are. They appear too loud to be persistently enabled. Maybe knock them down a lot, like 50%, so they just become background noise?

**Comment by furrycactus** [comment]
Adding an option for them to be toggleable in the Preferences tab was some feedback I heard a lot, too.

**Comment by NonQueueingMatt** [comment]
The sound itself is still too loud. Make it quieter with Audacity or something.

**Comment by alsoandanswer** [comment]
!review

**Pull request merged**
