### PR TITLE
Removes the AI from traitor job eligibility

### PR DESCRIPTION
**Pull request by Jaraci**
See title. I'm sick of 1:45 'vent and bolt everything' gimmicks; the AI rolling traitor is basically just a check as to whether you have an engineer in round who knows how to kill it or not, otherwise you run the risk of it taking the entire round hostage. If you don't have an engineer like that the round is inordinately taken over by the thing if it wants to: it's like malf without the ability to go code delta and a million times more frequent than malf ever was. The only saving grace is that it takes a competent engineer about five minutes to kill it if they want to on the Horizon map; the downside is that if you don't have that engineer you're back to playing malf again.

I know this will get DNMed and subject to maintainer discussion; good. I just want the discussion to be on the table at all -- I don't care if it gets shot down, or if some other limitation is a more acceptable compromise than flat out removing it, but considering you can basically get your traitor roll on every single autotraitor/mixed traitor gamemode you want to get it on, I'm saying that it shows up far too frequently to be really engaging.

I have held out hope for months now that the AI whitelisting process might have helped rein things in in terms of gimmicks that don't necessarily involve bolting, electrifying, and venting stuff en masse but in my opinion it hasn't. I debated putting cyborgs up for removal as well but wound up not bothering, since I think that would give this PR a 100% chance of failure rather than a solid 90% or so.

### CODE REVIEW

**Comment by Jaraci** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]
Personally, I argued against traitor AI when we were talking whether to whitelist or remove it and I still think it should be removed for the same reason malf was removed. It's not really engaging and traitor AIs can't particularly do any good gimmick.

**Comment by KingOfThePing** [comment]
God bless

**Review by KingOfThePing — APPROVED** [review]

**Review by ScheveningenZonn — APPROVED** [review]
get this shit outta my game

**Comment by senorsapo** [comment]
Great PR. AIs have far too much power and grief potential to be antagonists, and more often than not I have had trash AI rounds.

**Review by SleepyGemmy — APPROVED** [review]

**Comment by Arrow768** [comment]
As predicted above.
Will be discussed by the maintainers.

**Comment by DreamySkrell** [comment]
We have so few AI players and chars, that this might as well be directly targeting them by name.

I'd rather have AI removed completely, if the whitelist is clearly not working, and bad AIs do not get ahelped and removed.

**Comment by Jaraci** [comment]
> We have so few AI players and chars, that this might as well be directly targeting them by name.

I don't care. If they don't want to be "indirectly" targeted by name then they can feel free to turn the traitor pref off and play the regular AI role instead.

**Comment by EJDenton** [comment]
Can non-contributors post here? If so, as someone who regularly does play traitor AI, I would rather it not be removed. I generally only bolt or syphon areas that hinder people setting up emitters to meme me the moment I don't follow orders. If people actually tried to fix me I would be perfectly willing to work with them but I've been emittered by engineering simply for making snarky comments.

**Review by EJDenton — CHANGES_REQUESTED** [review]
Can non-contributors post here? If so, as someone who regularly does play traitor AI, I would rather it not be removed. I generally only bolt or siphon areas that hinder people setting up emitters to meme me the moment I don't follow orders. If people actually tried to fix me I would be perfectly willing to work with them but I've been emittered by engineering simply for making snarky comments.

**Comment by sheeplets** [comment]
This should have been shitcanned ages ago. Good riddance.

**Comment by Dekserrrrrr** [comment]
Adding from EJDenton, as an AI player who does play Traitor on occasion, I feel like this is exactly why whitelists were put in place, so we can root out the bad players and let the good AI players run the actually fun gimmicks. Why not just remove whitelists of bad AI players and let the good players explore good gimmicks?

**Comment by Butterrobber202** [comment]
main reason AI traitor sucks and can only do "haha vent bolt" is because that's literally their only toolset. Traitor AIs do not receive any abilities or uplink to give them gimmick flexibility. antagonist AIs should stay in the game, but the present "shitty outdated malf" or "gimped traitor" can both safely be shitcanned.

**Comment by EJDenton** [comment]
> main reason AI traitor sucks and can only do "haha vent bolt" is because that's literally their only toolset. Traitor AIs do not receive any abilities or uplink to give them gimmick flexibility. antagonist AIs should stay in the game, but the present "shitty outdated malf" or "gimped traitor" can both safely be shitcanned.

I would love to have additional tools to expand the type of gimmicks we can run. I think one of the main issues with antag AI currently is the antipathy for sentient AI that seems to be baked into the lore. Making any moves that are not subservient to the crew often causes immediate blow-back so I feel like additions would need to be subdued in scope and things that allow you to build atmosphere and tension without drawing direct attention to yourself.

I would still opt to not dissolve the traitor AI role until something was in-place to replace it because without interest on the development side it could sit in limbo forever. I agree with Dekser that utilizing whitelists and removing problem players from the role should be to way to move forward.

**Review by Arrow768 — DISMISSED** [review]
Discussed by the maintainers.
We believe that the AI is best used as a auxiliary tool by the traitors.
In order to achieve that goal the following needs to be changed:
* Reduce the cost of the law-board in the uplink to 1 or 2 TCs
* Add a info that a AI upload board can be found in tech storage to the description of the law-board in the antag uplink.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
