### PR TITLE
Adds more holidays to the holiday system

### PR DESCRIPTION
**Pull request by listerla**
Most taken from the Wiki. The Martian and Konyanger ones are made out of significant dates I could find in the lore; the secession of the Red Coalition and of Konyang respectively.

image

### CODE REVIEW

**Comment by KingOfThePing** [comment]
Why did you remove the Summer Solstice? There can still be IRL holidays in this list (and there are plenty), especially if it is not occupied by a lore holiday.

**Comment by listerla** [comment]
Because it was only set for 2018, 2019, and 2020, and I didn't feel like updating it for the next few years as well.

**Comment by listerla** [comment]
!review

**Comment by listerla** [comment]
<go to close a quote
<press the button twice

**Comment by Sindorman** [comment]
I really hate the `holidays.dm` switch code, it is so unreadable and bad. I might refactor it if I think of a better solution

**Review by Sindorman — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
