### PR TITLE
Duffelbag Resprite/Tweak

### PR DESCRIPTION
**Pull request by ParadoxSpace**
The old ones were blatantly not duffelbags, nor did they line up with the icon sprites. They are now more visually distinct, hold more than a regular bag, but have a slowdown of 1.

### CODE REVIEW

**Comment by VTCobaltblood** [comment]
ayy finally people carrying their bags in their hands instead of sitting down with a huge bag on their back

**Comment by ParadoxSpace** [comment]
!review

**Comment by alsoandanswer** [comment]
SeemsGood
seemsgood

**Comment by Arrow768** [comment]
Please post a picture of a person with the new duffelbag so we can get a better expression how it looks.
(From all sides please)

**Comment by ParadoxSpace** [comment]
https://i.imgur.com/T3o1CUZ.png

**Pull request merged**
