### PR TITLE
Research Crematorium

### PR DESCRIPTION
**Pull request by furrycactus**
Added two crematoriums to the research sublevel so that people can dispose of dead monkeys without people yelling "OMG ANIMAL CRUELTY" over radio when they go into the compactor. Also can be used to dispose of hazardous research materials or stuff like that.

### CODE REVIEW

**Comment by furrycactus** [comment]
!review

**Comment by VTCobaltblood** [comment]
just yeet them out the mass driver w/ a bomb

**Comment by furrycactus** [comment]
That's not much of a solution when you're lacking someone who can work Toxins. Plus it leaves a huge mess.

**Comment by furrycactus** [comment]
Changed it to look like this.
https://i.imgur.com/qYozE3B.png

**Pull request merged**
