### PR TITLE
More keybindings

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Added keymap R, to enable throw mode, lifting the R key disables throw mode, clicking the HUD icon works as before (toggle).
Added keymap SPACE, to enable run mode, lifting the SPACE key disables run mode, clicking the HUD icon works as before (toggle).
Added SHIFT+R as a keymap to resist.
Added CTRL+PGUP/CTRL+PGDOWN as a keymap to Move-upwards and Move-down, respectively.

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!review

**Comment by TheDanseMacabre** [comment]
Not a fan of needlessly replacing . and , with a two-key combo. It's less convenient and according to discord the motivation is to make it easier for /tg/ players, because that's how they do it over there? Which is a bizarre reasoning, if you ask me (seeing as the community overlap is minimal), and shouldn't be pursued.

I'm also not a fan of spacebar being used for running but that might reflect my own personal preferences more than anything else, as I use spacebar for a macro.

**Comment by FluffyGhoster** [comment]
Added a preference option to revert the R to classic toggle, under the General tab and readded the old keymaps for move-up and move-down.

**Comment by granodd** [comment]
Going to agree with Danse in that these seem like changes to hotkeys that no one really asked for. Unsure of how valid the claim is that they're made to accommodate TG players, but if it is, TG is the last place I'd suggest for making hotkey changes on Aurora given the vast difference in their keys, code, and mechanics.

All this really seems to do is create conflict for players with existing macros, when everything in this PR could feasibly be done with macros too bar the throw hold-down.

If any changes are to really be put through, they all should have a toggle of whether to use them at all rather than imposing them and conflicting with the way people already play.

**Comment by FluffyGhoster** [comment]
- The CTRL+PGUP/CTRL+PGDOWN was added following TG's style, not the other keybinds, which is a misquote
- I said that it was done to help _new players_ that likely _comes from_ a tg-based build before finding us, given the pervasiveness of it, and because the few times I asked how to move up or down when I started playing in Aurora I was told to use the commands, so it seemed like the "," and "." were fairly unknown keybinds (I have found them only because I looked at this macro list), there are other reasons too, such as having an up and down key making more sense than a comma and a period to go up and down, but I didn't get around to present this point, either way saying that it is the only reason is a misrepresentation
- It is not possible to reliably replicate neither the hold down throw nor the hold down run with macros with the current code, as they are toggled on and off with the same command, and your client-side macro has no way to know if it's on or off already

**Review by Arrow768 — CHANGES_REQUESTED** [review]
I really dislike the idea of having preference toggles for keybinds.

The Keybinds should be universal for every player.
Adding some half-assed key-customization system is not the solution to the problem.
If there really is a need to customize the keys, then a full key map system should be added.

**Comment by GMR25** [comment]
If there's no preference toggle then this is solely a downgrade for anyone preferring 1-press throw toggle, especially for catching. I don't want to have to press the UI icon instead of pressing page-up once.

I'm hoping it's only this new hotkey that's hold-to-use, and the original hotkey (page-up) would be press-to-toggle as it always has been.

**Comment by FluffyGhoster** [comment]
Other keybinds are not touched, so page up should still toggle it if it did before.

As a side note, I just discovered that, at least on my PC, the period button does not even work, you have to use the numpad period if you want to go down, so if that is indeed something that happens to everyone, I would question the utility of keeping comma and (numpad) period(?). Note that I tested it on the live server, not on this branch.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
