### PR TITLE
Fix terminator IPC's

### PR DESCRIPTION
**Pull request by connorjg1**
Terminator IPC's have had a broken cell for a few months stopping them from being usable. The internal cell now works again.

### CODE REVIEW

**Comment by connorjg1** [comment]
!review

**Comment by connorjg1** [comment]
!bugfix

**Comment by connorjg1** [comment]
I have no idea why this is failing, will need to ask and see.

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
wouldn't it be better to fix the terminator microbattery? there's a very noticable difference that the terminator has emp resistance.

**Comment by connorjg1** [comment]
> wouldn't it be better to fix the terminator microbattery? there's a very noticable difference that the terminator has emp resistance.

This was the original plan. I couldn't figure it out. For all intents and purposes it looks like it should be working. The only solution I found that worked caused runtimes which was to force initialize the terminator microbattery.

I did testing though with both using said solution and the EMP resistance seemed to make absolutely no difference. Both the terminator microbattery and the standard microbattery took the same amount of EMP's to empty the cell.

**Comment by connorjg1** [comment]
> wouldn't it be better to fix the terminator microbattery? there's a very noticable difference that the terminator has emp resistance.

Addressed

**Review by Arrow768 — APPROVED** [review]

**Review by alsoandanswer — APPROVED** [review]

**Pull request merged**
