### PR TITLE
Adds bluespace borg

### PR DESCRIPTION
**Pull request by Karolis2011**
In summary: It's medical, engineering and combat borg modules merged and enchanted with absurdity.

### CODE REVIEW

**Comment by Karolis2011** [comment]
!review

**Comment by ben10083** [comment]
No rcd? If you are providing a op borg, rcd is a mist have addition

**Comment by Pratepresidenten** [comment]
Atlast a worthy edition to bend time and space

**Comment by Ratvar** [comment]
Can it phase through stuff phazon style?

**Pull request merged**
