### PR TITLE
Adds Vaurca Attendant as a Warrior bioform, based on having a gaster or no gaster

### PR DESCRIPTION
**Pull request by feartheblackout**
image
image
Basically, taking the gaster on or off of the Warrior will tell you that your bioform has changed, and update the blurb, name, and species mods of your mob accordingly. That means no sprite changes this time, besides the gaster itself. Hopefully, an acceptable alternative to the Attendant subspecies that was previously offered in #17550.

### CODE REVIEW

**Comment by feartheblackout** [comment]
!review

**Review by DreamySkrell — APPROVED** [review]
based if true

**Comment by Greenjoe12345** [comment]
I think it was said attendants as an actual new species could be allowed of they used normal clothing sprites, just using some code to move em up slightly

**Comment by FluffyGhoster** [comment]
@desvenlafaxine

**Comment by desvenlafaxine** [comment]
I don't oppose it, but I'd like to understand the benefits better. While I appreciate the inclusion of more bioforms, I feel like they should serve more of a purpose, similar to how they're ultimately utilitarian to Vaurcae as well.

**Comment by DreamySkrell** [comment]
I think it's fine as just a bit of characterization and differentiation between different vaurca characters. In the same way that skrell have a tail or no-tail option.

**Comment by feartheblackout** [comment]
!wip while i fix everything and get it in decent working order. see description for more details

**Comment by feartheblackout** [comment]
haha oops lets try that again

**Pull request closed without merging**
