### PR TITLE
Allows Bridge Crew to take Ve'katak Phalanx augments

### PR DESCRIPTION
**Pull request by feartheblackout**
bridge crew can (presumably) be double-contracted with the ve'katak phalanx. all command roles remain untouched. this PR previously included corporate reporters as well but is being split into two PRs due to maintainer discussion

### CODE REVIEW

**Comment by feartheblackout** [comment]
!review

**Comment by Arrow768** [comment]
Maintainer Discussion due to the inclusion of Bridge Crew

**Comment by feartheblackout** [comment]
going to split this up into two PRs, retaining the bridge crew changes on this one to make the corporate reporter changes easier to pass .

**Comment by NonQueueingMatt** [comment]
approved

**Review by NonQueueingMatt — APPROVED** [review]

**Review by DreamySkrell — APPROVED** [review]

**Pull request merged**
