### PR TITLE
Adds Missing Science Holopads

### PR DESCRIPTION
**Pull request by Ben10083**
Adds missing holopads to Research Director Officer, Xenobiology, and Xenobotany.

### CODE REVIEW

**Comment by Ben10083** [comment]
!review

**Comment by FluffyGhoster** [comment]
Undocumented changes of scrubbers/vents + why are they under tables?

**Comment by Ben10083** [comment]
> Undocumented changes of scrubbers/vents + why are they under tables?

1) thought they were recommended to be more 'hidden' like under tables when possible
2) Change occurred while trying out various locations for holopads in that office, I can change it back if you wish

**Comment by Ben10083** [comment]
The Deep State has informed me to not hide these things under tables, it has been changed. Glory to the Regime o7

**Review by DreamySkrell — APPROVED** [review]

**Review by Geevies — APPROVED** [review]

**Review by Geevies — APPROVED** [review]

**Pull request merged**
