### PR TITLE
Hydroponics Animal Husbandry

### PR DESCRIPTION
**Pull request by furrycactus**
Less interesting than the title suggests, this converts the hydroponics backroom to a grassy area with dirt plots, a chicken crate, a goat crate, and the bare basics for assembling a beehive for honey.

image

### CODE REVIEW

**Comment by furrycactus** [comment]
!review

**Comment by sheeplets** [comment]
The beekeeping supplies and animal crates are a very welcome addition that we've been asking for for years. I don't particularly agree with removing the basins, however. Some people like having them to rearrange elsewhere.

**Comment by Yakunan** [comment]
> The beekeeping supplies and animal crates are a very welcome addition that we've been asking for for years. I don't particularly agree with removing the basins, however. Some people like having them to rearrange elsewhere.

The basisn's i always use to rearrange/add are the 6 basins found in maintenance. Else you can always order more from cargo. I dont think this will be an issue.

**Comment by furrycactus** [comment]
As already said, there's spare trays in maintenance if you want more to rearrange. Things can be planted in the dirt plots too, and there's actually more dirt plots than there were plant trays previously, so this is sorta a buff. Some people might want to say "but I can't tell how the plants are doing at a glance", but it's as simple as walking up and clicking Examine to see how a plant in a soil plot is going. Bees have a beneficial effect on nearby plants as well, so this is quite absolutely a net buff.

**Comment by Doxxmedearly** [comment]
I know beekeeping supplies use welding fuel (for some reason) but would this tank not be better placed in maintenance? If they want to keep bees they can grab it and move it in. Having a fuel tank sitting in hydro just feels odd for that niche use.

**Review by Casper3667 — APPROVED** [review]

**Comment by Casper3667** [comment]
It looks good outside the slight weirdness with the fuel tank, but it isn't completely out of the world.

**Review by Geevies — APPROVED** [review]

**Pull request merged**
