### PR TITLE
Various removals.

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
The cueball is self-explanatory, a highly ugly flashing nuisance ripped from homestuck.
The two lawyer suits removed by this PR are neon colors that are dissonant with the rest of our palette, on top of being Ace Attorney references. The other two Ace Attorney reference suits are being kept, because they at least are not eyesores.
Removes the Deckard pistol, which, as the code tells you, is the Blade Runner gun. It's also very poorly-sprited.
Removes a large number of posters, which are mostly completely dissonant with the server's roleplay standards and make many references to SS13 memes, or are outright references to popular media. Some things I wasn't sure about, so if you happen to know some are references, please inform me. One poster appeared to be a player's character art bizarrely added to the game itself.

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Comment by TheDanseMacabre** [comment]
!wip

**Comment by Zelmana** [comment]
Why are we removing deckards gun but no complaints when a cyberpunk gun was just added to code?

If you're going to hate remove all references let's at least be consistent.

Yet another "removed because I don't like" PR that can be changed with a "readded because I do like" PR

**Comment by KingOfThePing** [comment]
He absolutely complained about the Cyberpunk gun PR. The difference here is that I at least made it fit into the auroraverse. The Deckard gun is just the Deckard gun. Does that warrant it's removal? Probably not, but that's the difference.

**Comment by TheDanseMacabre** [comment]
>He absolutely complained about the Cyberpunk gun PR. The difference here is that I at least made it fit into the auroraverse. The Deckard gun is just the Deckard gun. Does that warrant it's removal? Probably not, but that's the difference.
Besides that, the Cyberpunk gun at least looks decent. The Deckard gun is hideous and functionally pointless. It occupies no niche that isn't filled by another gun, technically speaking.

**Comment by TheDanseMacabre** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
!wip

**Comment by TheDanseMacabre** [comment]
!review

**Review by KingOfThePing — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
