### PR TITLE
Mapped Out AI

### PR DESCRIPTION
**Pull request by Geevies**
* Added an additional stationbound slot for a total for 3.
* Entirely mapped out the AI.

Used StrongDMM, hopefully it works.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by Chada-1** [comment]
You should disable the AI gamemodes (Including the mixture modes) if this goes in too.

**Comment by LanceLynxx** [comment]
Heavily against this, I see no reason to remove the AI.
If anything, at most, it should MAYBE become a whitelist role tied with the command whitelist.

Punish players who use it badly instead of removing the role.

**Comment by NonQueueingMatt** [comment]
> 
> 
> Heavily against this, I see no reason to remove the AI.
> If anything, at most, it should MAYBE become a whitelist role tied with the command whitelist.
> 
> Punish players who use it badly instead of removing the role.

Who are you, again?

Closing as unwanted due to the poll.

**Comment by LanceLynxx** [comment]
> Who are you, again?

A player.

That extremely rude and unrelated to the topic.

**Comment by optimumtact** [comment]
I think we should merge this

**Comment by Iamgoofball** [comment]
Yeah, I think we can move forward with this.

**Pull request closed without merging**
