### PR TITLE
Ghosts no longer complain, moan, whine, lament, or blubber

### PR DESCRIPTION
**Pull request by DreamySkrell**
Ghosts now simply just "say".

Why? I hate it how people try to have normal conversations in ghostchat, and they come out as "X moans", "Y whines", "Z laments".

Also being salty in ghostchat is not really allowed anyways.

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!review

**Comment by NonQueueingMatt** [comment]
Not really a fan. This is kind of just a funny meme.

**Review by Arrow768 — APPROVED** [review]
Technically fine.
Will be discussed if wanted.

**Comment by EmperorJayJay** [comment]
Maintainers get to discuss this but tbh I feel it'd cull some of the implied toxicity of dchat and it feels kinda annoying if people try to have a legitimate discussion about w/e.

**Review by kreeperHLC — APPROVED** [review]
Toxicity is fun, but whatever.

**Review by Alberyk — APPROVED** [review]

**Review by SleepyGemmy — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
We don't really think this PR would be of any consequence, so it's being denied. Toxicity happens regardless of the verb - just adminhelp and move on.

**Pull request closed without merging**
