### PR TITLE
Dionae general lore pass

### PR DESCRIPTION
**Pull request by listerla**
- imageadd: "Added two new Dionae accents, for the Pests of Titan Prime and the Primitive Sirens of Mictlan."
  - tweak: "Added the Iron Eternal and Ichor Eternal as religion options for Dionae."
  - tweak: "Updated Xrim origin to modern standards, with the Enlightened and Scorned."
  - tweak: "Restricted some Dionae accents and religions for certain origins."

All based on the current incarnation of Dionae lore, this is an attempt to get the origins generally up-to-date with changes.

### CODE REVIEW

**Comment by listerla** [comment]
!review

**Review by FluffyGhoster — APPROVED** [review]
As far as code, it looks good to me, but I believe this will need to be signed off by the Dionae lore guys (?)

**Comment by listerla** [comment]
> As far as code, it looks good to me, but I believe this will need to be signed off by the Dionae lore guys (?)

Already talked to Caelphon about it; I'll ask him to give it another look-over.

**Comment by listerla** [comment]
image
Cael-approved

**Pull request merged**
