### PR TITLE
Improvised Crossbow Nerfs

### PR DESCRIPTION
**Pull request by KingOfThePing**
This nerfs the improvised (powered) crossbow. 

- reduces (superheated) rod throwforce to 10 from 15
- reduces maximum tension to 3 from 5
- reduces speed increase per tension to 3 from 5

This means the weapon still does a considerable amount of damage + the bolt sticking into the victim, but prevents it from pinning people to walls.

Pinning people to walls is basically a game ender and while it's cool its very overpowered for an easily buildable, improvised weapon. People can run up to enemies, point blank (unmissable) pin people to walls and do considerable internal damage initially and potentially arterial bleeding when the rod is yanked out. Too strong, thus the nerf.

### CODE REVIEW

**Comment by KingOfThePing** [comment]
!review

**Comment by TheDocOct** [comment]
As an engineering main-

yeah, alright, fine

**Review by TheDocOct — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Comment by WickedCybs** [comment]
It disrespected the pipegun gang.

**Comment by KingOfThePing** [comment]
> It disrespected the pipegun gang.

the pipegun is next

**Comment by Butterrobber202** [comment]
> > It disrespected the pipegun gang.
> 
> the pipegun is next

no no no no no

**Comment by KingOfThePing** [comment]
Recent changes:

- buffs the raw damage of the bolt to 20 from 10

The crossbow now does 35 damage to unarmored civilians ("enemies") but does not pin people to the walls anymore.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
