### PR TITLE
Buttpacks: Storage Solution for the Socially Insecure

### PR DESCRIPTION
**Pull request by Aticius**
You can now wear fannypacks on your butt. This is very important.

This is probably spritebloat, but a refactor of these things is beyond me.

### CODE REVIEW

**Comment by Aticius** [comment]
!review

**Review by Chada-1 — APPROVED** [review]

**Comment by alsoandanswer** [comment]
I'd suggest you move fannypacks to a new dmi.

Path should be icons/mob/belt/fannypack.dmi

Shove all the fannypack sprites in there.

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
above

**Review by NonQueueingMatt — DISMISSED** [review]
Remove the sprites you added to belt.dmi.

**Comment by Aticius** [comment]
> Remove the sprites you added to belt.dmi.

They should already be gone?

**Review by alsoandanswer — APPROVED** [review]

**Pull request merged**
