### PR TITLE
Fixes Point Verdant Code and Mapping Issues

### PR DESCRIPTION
**Pull request by kyres1**
I have sinned

  - bugfix: "Fixes Point Verdant's stairs literally obliterating the server by making their directions work in accordance to their bounding boxes."
  - bugfix: "Fixes duplicate stairs on Point Verdant."
  - bugfix: "Fixes some inconsistent railings on Point Verdant, forcing players to walk through them to climb stairs."
  - bugfix: "Adds a light switch to the Point Verdant street vendor building."
  - bugfix: "Adjusts the location of deep water on Konyang to avoid structures, so the overlays don't conflict."\

### CODE REVIEW

**Comment by kyres1** [comment]
!bugfix

**Comment by kyres1** [comment]
!review

**Review by SleepyGemmy — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
There should not be bikes on PV without any keys or locking mechanics, otherwise anyone can just walk up to any bike and drive off. Like the crew should not steal the bikes of the locals to move around the map.

I have an idea on how to implement bike keys and bike renting, and I would like to do it tomorrow or monday, I will ping you on discord.

**Comment by FluffyGhoster** [comment]
>Like the crew should not steal the bikes of the locals to move around the map.
IC issue, honestly, that's what the Konyang police is there for

**Comment by DreamySkrell** [comment]
> > Like the crew should not steal the bikes of the locals to move around the map.
> 
> IC issue, honestly, that's what the Konyang police is there for

I disagree. Stealing stuff should be possible, but it shouldn't be so easy you can do it unintentionally - like currently there is no way to even tell which bike belongs to who.

**Comment by kyres1** [comment]
> There should not be bikes on PV without any keys or locking mechanics, otherwise anyone can just walk up to any bike and drive off. Like the crew should not steal the bikes of the locals to move around the map.
> 
> I have an idea on how to implement bike keys and bike renting, and I would like to do it tomorrow or monday, I will ping you on discord.

The bikes and mop were removed from the PR, leaving only the bugfixes there.

**Review by DreamySkrell — APPROVED** [review]

**Review by FluffyGhoster — APPROVED** [review]

**Pull request merged**
