### PR TITLE
Various Map tweaks

### PR DESCRIPTION
**Pull request by furrycactus**
- Added light switches in just about every place I could think that it's reasonable to have them.
- Added two radiation suit closets to the research department, one in Spectrometry and one in the Telescience Lab.
- Shuffled around the solar arrays so that they're faster to set up and require less cable, also added more cable to the roof array because that one needs a lot.
- Changed the weird air bypass that telecomms had to one that's actually more functional.

### CODE REVIEW

**Comment by furrycactus** [comment]
!review

**Comment by VTCobaltblood** [comment]
Can we get a list of places that light switches were added to?

**Comment by furrycactus** [comment]
It'd be quicker to list where they aren't. I tacked them almost in every place that wasn't a kind of main hallway. Main department halls and the central halls on the station don't have them, but almost everywhere else does now.

**Comment by Sindorman** [comment]
Why there are so many changes for just adding light switches? Usually that would be 500 changes for eacch map, not 2000

**Comment by furrycactus** [comment]
I did other things too. Changing the layout of half the solars, changing their wires, changing around pipes in telecomms, moved around windows and grilles on the holodeck so that the windows are more symmetrical (which I also forgot to mention).

**Comment by Sindorman** [comment]
While that is kinda listed in the description, this is not obvious from the name

**Comment by furrycactus** [comment]
I'll get up to fixing this soon, I haven't had a whole lot of time to fix it yet.

**Comment by fernerr** [comment]
Yeah no worries, feel free to message me whenever if you need something.

**Comment by furrycactus** [comment]
Started this over again because it had been a while and I'm bad at dealing with conflicts. New one is #6856.

**Pull request closed without merging**
