### PR TITLE
Janitor, hydroponics and medical inhands

### PR DESCRIPTION
**Pull request by alsoandanswer**
Regex'd surgery tools to be obj/item/surgery, excuse the huge file changes

Adds missing surgerytray sprites for the alternate science scalpels

And basically, janitor, hydroponics and medical inhands, the usual stuff. Moves them to a new folder.

NEW : tank inhands have been moved to a new folder. Also added inhands for emergency tanks, cuz.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by alsoandanswer** [comment]
!review

**Comment by Geevies** [comment]
Why are these not contained sprites?

**Comment by alsoandanswer** [comment]
> 
> 
> Why are these not contained sprites?

Some of these inhands are used more than once for different things

**Comment by alsoandanswer** [comment]
!review

**Comment by alsoandanswer** [comment]
!review

**Pull request merged**
