### PR TITLE
New Dungeon /// Grove Oasis

### PR DESCRIPTION
**Pull request by Caelphon**
Right. Here goes.

This is my first mapping PR, so it is bound to go wrong. I'd like to get more involved in the server's various avenues (outside of just lore) and mapping is a pretty big one, so I wanna build up my skill and actually be able to make my own maps to alleviate the stress of our mappers. 

This will be WIP until I'm certain I haven't destroyed something.

### CODE REVIEW

**Comment by Caelphon** [comment]
!wip

**Comment by Caelphon** [comment]
I think I fucked something up here.

**Comment by Caelphon** [comment]
I believe the [Revert "Update aurorastation.dme"]" is my just misnaming my commit, so I apologize for that.

**Comment by Caelphon** [comment]
The area was changed to template_noop as per Cybs recommendation; as opposed to grove.

**Comment by Caelphon** [comment]
!wip

**Comment by Caelphon** [comment]
!remove wip

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
You need to actually add the new ruin to the grove exoplanet by adding it to the `possible_random_ruins` list.

**Comment by Caelphon** [comment]
I accidentally deleted my repo, so let me start this again properly.

**Pull request closed without merging**
