### PR TITLE
Ports arcade sprites from Polaris

### PR DESCRIPTION
**Pull request by desvenlafaxine**
Updates arcade machines, adds a unique sprite for each one and adds rotating sprites.

Ported from [Polaris](https://github.com/PolarisSS13/Polaris/pull/7938)

Iefrr7b0Nr
image

### CODE REVIEW

**Comment by desvenlafaxine** [comment]
!review

**Review by Casper3667 — APPROVED** [review]
Nitpick I suppose, but if the old sprite isn't being used then there isn't much reason to keep it around and use space. Other than that it looks fine.

**Review by Casper3667 — CHANGES_REQUESTED** [review]
I took a moment to test it, and it appears that while the sprites are changed, the arcades still default to switching over to a default broken sprite rather than just breaking the screen if they break.

Images from testing, the two on the left were shot until they broke:
image

**Comment by Geevies** [comment]
i don't think these sprites fit aurora's artstyle, unfortunately

**Comment by desvenlafaxine** [comment]
Grey helped me fix the bug. They should be good now.

**Review by Casper3667 — APPROVED** [review]
Alright, I fixed up the sprite problem as it ended up being a little more annoying than anticipated. Now it works fine mechanically but I give Geeves has a point in the sprites feeling different.
image
image

**Comment by desvenlafaxine** [comment]
!review

**Comment by NonQueueingMatt** [comment]
Same thing as in your vending machine PR. These sprites don't really fit our style. You can find other ones if you want to keep the PR up.

**Comment by desvenlafaxine** [comment]
> 
> 
> Same thing as in your vending machine PR. These sprites don't really fit our style. You can find other ones if you want to keep the PR up.

Same argument as my other PR. I'm going to update this to remove the side sprites, though.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
