### PR TITLE
A round of sprite improvments/additions.

### PR DESCRIPTION
**Pull request by fernerr**
This pr aims to implement a bunch of the work done by Amoryblaine (found in this thread https://forums.aurorastation.org/topic/11698-amorys-sprites/)

 - Adds new sprites for the tactical gear available in cargo.
 - Adds new, green, sprite for the military belt, the old red one is added as a specific syndicate variant.
 - Improves the sprite of the ushanka, adds the old one as a variant by request.
 - Adds rolled down sleeves states for two sol uniforms, adds sol tactical helmet and heavy armor vest.
 - Adds a TCFL jacket to the loadout.
- Changes the flipped sprites of most caps to be leaning rather than straight.
 - Makes the visors of biosuits transparent.
 - Recolours the security biosuit from orange to pale blue.
 - Recolors the hip holster to be black.
 - Makes the tactical gas masks eyes transparent.
 - Tweaks the red and blue bandanas to be less bright.
 - Adds some missing balaclava sprites, Improves the look of rolled up balaclavas.
 - Makes the security berets more fitting with the standard blue one.

Map edits: Replaces the armoury biosuit locker with a security one, replaces the gas masks in the armoury with the more modern ones.

### CODE REVIEW

**Comment by fernerr** [comment]
!wip

**Comment by skull132** [comment]
Gonna get the spriters to provide feedback on this and their conformance to style and aesthetic.

**Comment by fernerr** [comment]
Not sure why it says that I requested a review, I didn't touch anything intentionally.

**Comment by fernerr** [comment]
!review

**Pull request merged**
