### PR TITLE
Add the roller bed rack to the medical module

### PR DESCRIPTION
**Pull request by TheGoret**
Everyone who played medical borgo know how much its hard to pull someone around. Be it around the station, or from the advanced scanner to surgery. This PR gives the same roller bed rack as the rescue module have.

### CODE REVIEW

**Comment by TheGoret** [comment]
!review

**Comment by Arrow768** [comment]
The medical borg is supposed to be a support module inside of medical and work with medical staff to treat people.
We already have the rescue borg for "frontline" work.

**Comment by TheGoret** [comment]
Arrow, I don't know if you play around medical alot, but let me explain my thoughts on this:
-Medical modules have stopped being support module for a while now. They even have the tools to be autonomous from a medical doctor, in case there is none. Its useful for low pop, but also when medical is overwhelmed. Being able to move someone injured is absolutely necessary.
-As they got surgery tools, they need to be able to drag people INSIDE the medbay, I have seen too much people being dragged in chairs by borgos and it makes me laugh and cry at the same time. 

Based on these two arguments, it is completly different from the rescue bot. And speaking of which, I haven't seen it being used in a while and I consider making a feedback thread for its removal and being merged with the medical borg (like the construction with engineering) but this is for another day.

**Comment by Pratepresidenten** [comment]
This is a good idea, so I dont have to pull my rollerbed all around like some neanderthal.
But yes, who uses rescue borgs anymore. Useless >:c

**Pull request merged**
