### PR TITLE
High Vis Jacket, Departmental (Med/Sec/Eng) storage

### PR DESCRIPTION
**Pull request by LynxSolstice**
Lets the high vis jackets hold medical items in their storage, to enable more drip options for paramedics (and other medical players I guess too)

### CODE REVIEW

**Comment by LynxSolstice** [comment]
!review

**Review by FluffyGhoster — APPROVED** [review]

**Comment by LynxSolstice** [comment]
> Really not a fan of this, cause highvis jackets are not exclusive to medical, anyone can take them.
> 
> It feels arbitrary to allow them to take specifically medical items. Especially since it allows `obj/item/clothing/head/hardhat/first_responder`... but not a normal hardhat? What is the difference between a FR hardhat and a non-FR hardhat?
> 
> Why not also allow engineering items? And security? Or ops? All of these jobs can take highvis jackets too, and arguably engineering could be even more justified in doing so. I don't want to see more PRs adding job items to random non-job clothing.
> 
> If we're adding job items to jackets like this, at that point would be better to just un-restrict all jackets and the like altogether, so any jacket could store anything.

This PR atm is atomized to only affect the jacket's usage as a medical clothing item, for primarily paramedics, the allowed list was copied from the paramedic jacket, and any further departmental allowances is out of scope for this PR. It's for the drip.

**Comment by DreamySkrell** [comment]
I am not requesting that you update this jacket with other department items, or other jackets with anything.

I am saying this is very arbitrary to add dept items to a generic non-dept jacket, and I do not want to see people adding random dept items to random jackets and other clothing items, just cause "drip". It is arbitrary and a mess to maintain, and at that point it would be better to just un-restrict all jackets to be able to take anything.

Up to maintainers to decide in the end though.

**Review by Arrow768 — CHANGES_REQUESTED** [review]
I concur with dreamy.

This is a non-department-specific jacket.
As such the items it can carry should not be restricted to a single department.

I see a few options:
* Add a department specific variant (with separate sprites)
* Add the relevant items of other departments to the high vis jacket.

You are free to propose another solution.

**Comment by LynxSolstice** [comment]
> * Add the relevant items of other departments to the high vis jacket.

I'm more a coder than a spriter, so I can do this. Do you want weapons included for Security or just the standard items from the security belt?

**Comment by Arrow768** [comment]
> > * Add the relevant items of other departments to the high vis jacket.
> 
> I'm more a coder than a spriter, so I can do this. `Do you want weapons included for Security or just the standard items from the security belt?`
> 
> I've decided on allowing the guns, since the cadet hazard vest also allows them.

Sorry for the back and forth.

I have looked at the results and discussed that with the other developers.
I dont think that the non-department-specific-variant is a good solution.
-> That huge list of items is not exactly maintainable and it would set a precedent for more generic items that can carry department stuff. (Which is not wanted).

If you would like this to be merged, we need department specific variants of the jacket with the relevant sprites.
(The sprite can be quite similar, but it should use the department colors)

**Comment by LynxSolstice** [comment]
> > > * Add the relevant items of other departments to the high vis jacket.
> > 
> > 
> > I'm more a coder than a spriter, so I can do this. `Do you want weapons included for Security or just the standard items from the security belt?`
> > I've decided on allowing the guns, since the cadet hazard vest also allows them.
> 
> Sorry for the back and forth.
> 
> I have looked at the results and discussed that with the other developers. I dont think that the non-department-specific-variant is a good solution. -> That huge list of items is not exactly maintainable and it would set a precedent for more generic items that can carry department stuff. (Which is not wanted).
> 
> If you would like this to be merged, we need department specific variants of the jacket with the relevant sprites. (The sprite can be quite similar, but it should use the department colors)

I'm unfortunately unable to fulfill the requirements here, I could shave off some items, however, or work with another code restriction, perhaps I could allow all of a subtype, like object/item/reagent_containers and object/item/device?

**Comment by LynxSolstice** [comment]
Cannot fulfill the requirements for merge.

**Pull request closed without merging**
