### PR TITLE
Bishop Language Slot Addition

### PR DESCRIPTION
**Pull request by Snakebittenn**
They get one (1) extra language slot.

### CODE REVIEW

**Comment by Snakebittenn** [comment]
!review

**Review by Geevies — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]
This is possibly the PR I've had the worst time approving. At no point do I ever think that this is worth it, nor will any players be happy about this as the bishop playerbase is nonexistant, but I don't find either of those concerns worth denying a PR over.

**Comment by Arrow768** [comment]
Will be discussed between the maintainers

**Comment by Arrow768** [comment]
In it goes, however additional language slots for other IPCs will not be permitted.

**Pull request merged**
