### PR TITLE
Blouse Availability Fix

### PR DESCRIPTION
**Pull request by Snakebittenn**
- bugfix: "Blouses are available again."
  - bugfix: "Starshades are too."

### CODE REVIEW

**Comment by Snakebittenn** [comment]
!bugfix

**Comment by Snakebittenn** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]

**Review by fernerr — APPROVED** [review]

**Comment by Snakebittenn** [comment]
!wip

**Comment by Snakebittenn** [comment]
!wip

**Comment by Snakebittenn** [comment]
!review

**Comment by Snakebittenn** [comment]
!review

**Comment by fernerr** [comment]
Fixes #9925

**Pull request merged**
