### PR TITLE
Mantle Fix 2.0 and Refactoring Skrell Sprites

### PR DESCRIPTION
**Pull request by RyverStyx**
Fixes the mantle again. Last time I promise.

### CODE REVIEW

**Comment by RyverStyx** [comment]
!bugfix

**Comment by RyverStyx** [comment]
!review

**Review by Alberyk — APPROVED** [review]

**Comment by RyverStyx** [comment]
Added some changes from @Llywelwyn in regards to how Skrell sprites are stored. Nothing has been added or deleted.

**Comment by Llywelwyn** [comment]
> Added some changes from @Llywelwyn in regards to how Skrell sprites are stored. Nothing has been added or deleted.

Merged branches since they're both just Skrell sprite edits, to avoid having merge conflicts/having to wait until this PR is accepted before the other changes can be made.

All skrell_items.dmi items are now moved to respective contained dmis in icons/obj/contained_items/skrell/ - discussed this in #code_dungeon in the discord to make sure it was acceptable beforehand.

**Pull request merged**
