### PR TITLE
Adds *Chitter

### PR DESCRIPTION
**Pull request by otatoh**
Adds a *chitter emote for vaurca. Sound effects obtained from ZapSplat.com under their standard license.

https://vocaroo.com/i/s0ABySqTfVmK
https://vocaroo.com/i/s002PqFAcjs5
https://vocaroo.com/i/s1XRnfZiywXy

### CODE REVIEW

**Comment by skull132** [comment]
!review

**Comment by skull132** [comment]
> Attribution / Credit Required
> Sound effects licensed via this standard license require attribution in the form of a credit / link back to our website. Please do NOT credit us from any social media platform. Credits must be added to the project itself, for example in your YouTube video description, app or game credits page or your projects related website or blog etc.

License requirement not fulfilled.

**Comment by skull132** [comment]
> 
> 
> My bad, where would be the proper place to put that?

It'd be easiest to create a subfolder called like, `zapsplat`, move the sounds there, and put the require information there in a `.txt` or `.md` file. That way, it's prettttyy clear as to what's what.

**Comment by otatoh** [comment]
Added.

**Pull request merged**
