### PR TITLE
New backbag sprites and a lot more!

### PR DESCRIPTION
**Pull request by alsoandanswer**
- rscadd: "Compresses bag types and adds seperate color selection option in the loadout. Color selection only works for leather satchels, pocketbooks and rucksacks. Select 'None' for default color."
  - rscadd: "Adds Faction-specific Backpacks! Matches your corporation."
  - rscadd: "Adds new Job-specific bags, namely for all the Heads of Staff, the Psychiatrist, and EMTs."
  - imageadd: "Adds resprited backpacks and satchels from /tg/, the rest sprited by yours truly."

dreamseeker_2gHgViqK8u
dreammaker_XgJKKND29y
forgot zeng-hu because i am sleep deprived
dreamseeker_Q2SJn34gD9

Note : Swapped around the leather satchel and the grey satchel in code for tidiness reasons.

Inhands will be done at a later date because I am very tired.

Maybe put this up for a test merge so people know the option exists. And report any issues they have.

Hope you enjoy. Thanks.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by TheStryker** [comment]
The shading on these ones are nice, but it would be interesting to see what the Idris and NanoTrasen backpacks would look like with the logo since it seems like there's just a missing space (especially since the latch is missing on the NT satchel/isn't that clear).

**Comment by TheDanseMacabre** [comment]
These new sprites aren't bad, but there is one major issue - the straps are ludicrously think and obscure a huge portion of the character's outfit.
chrome_dO87bLoXob
Sa712AQYDp
Compare your new leather satchel to the old one - your design would have a diagonal third of the character's outfit obscured by the strap, and there isn't a single backpack item you're adding that is slimmer than this. In fact, the strap looks so thick that it resembles what the back-worn assault rifle sprites look like. These absolutely need to be slimmed down, because a character's sprite is the only visual expression of that character, and these new backpacks highly distract the sprite as a whole.

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
I think these changes for bags are a bit too drastic. The shading is going to look out of place with literally every clothing item - it's just not gonna work.

Additionally, three wide bag straps are a complete no. That's not happening.

**Comment by niennab** [comment]
Was PMCG missed? 
Might also be worth having variants in black for Zavodskoi as well. Or that the bags are all together black. As is, Orion and Zavodskoi are the same beyond a splash of red.

**Comment by KingOfThePing** [comment]
I think they look pretty good, I do agree on the straps being too wide. Otherwise, I like them personally and dont think they clash with the style(too much).

**Comment by atteria** [comment]
The Idris bags are very low contrast and monochromatic. Adding a real accent color and some hue-shifted lighting like the original TG bags would help.
The Nanotrasen bags are low-contrast to a lesser extent as well, and could use darker shadow areas.

**Comment by alsoandanswer** [comment]
dreamseeker_auJZ1XjSy9
dreamseeker_YNiwEwpnTn

**Review by Alberyk — APPROVED** [review]

**Review by NonQueueingMatt — DISMISSED** [review]
I still do not want the three wide satchel straps, they're basically so wide they're unusable on any sort of sprite. At that point the straps may as well be deleted entirely, and on some uniforms they kind of compliment the look.

The hiding feature is a welcome addition, but it's something that everyone is gonna have to do every round, which is ball bustingly frustrating. Either get rid of the straps entirely at this point or turn them back into one pixel wide straps.

**Comment by TheDanseMacabre** [comment]
I think "add the ability to remove the straps entirely" is a very bizarre solution to "three pixel wide straps simply do not work". Why not just make the straps, well, not that thick? I don't follow the logic.

**Comment by alsoandanswer** [comment]
> I think "add the ability to remove the straps entirely" is a very bizarre solution to "three pixel wide straps simply do not work" problem. Why not just make the straps, well, not that thick? I don't follow the logic - especially because the straps are an important visual indicator of whether or not you're even wearing a bag at times, and they often contribute to aesthetics. There's nothing wrong with straps existing - the problem is with them being way too thick. This PR essentially presents you with two flawed choices: Go without the strap altogether, or have the aesthetic annihilating three-pixel straps.

Because one tile straps look _absolutely terrible._ A thin, one pixel line gives little-to-no space to work with and has the worst of both worlds - it clutters the sprite like a three-wide without giving the additional space to work with, and on the otherhand, it's hard to see anyway, so might as well remove it. 

Here are some examples by our contemporaries with well-established artstyles.
Eris and Colonial Marines has had them removed. /tg/ has them 3-wide.
It has been tried and tested, by teams of talented, some commisioned, spriters. They simply do not work.

**Comment by TheDanseMacabre** [comment]
> > I think "add the ability to remove the straps entirely" is a very bizarre solution to "three pixel wide straps simply do not work" problem. Why not just make the straps, well, not that thick? I don't follow the logic - especially because the straps are an important visual indicator of whether or not you're even wearing a bag at times, and they often contribute to aesthetics. There's nothing wrong with straps existing - the problem is with them being way too thick. This PR essentially presents you with two flawed choices: Go without the strap altogether, or have the aesthetic annihilating three-pixel straps.
> 
> Because one tile straps look _absolutely terrible._ A thin, one pixel line gives little-to-no space to work with and has the worst of both worlds - it clutters the sprite like a three-wide without giving the additional space to work with, and on the otherhand, it's hard to see anyway, so might as well remove it.
> 
> Here are some examples by our contemporaries with well-established artstyles. Eris and Colonial Marines has had them removed. /tg/ has them 3-wide. It has been tried and tested, by teams of talented, some commisioned, spriters. They simply do not work.
> 
> Addendum : Funnily enough, we already have things with 3-wide straps. See the fireaxe back and bluespace backpack sprite.

Even if you are correct about one pixel straps (you aren't, to be frank), you're creating a false dichotomy by suggesting there are two options and two options alone - three-pixel straps or one-pixel straps. In reality, two-pixel straps work just fine - we already use them and, well, they look good.
image
Here's the fact of the matter: I have not encountered even a single player that has liked your three-pixel straps. So no, they really don't work. 
Three-pixel straps work for fireaxes and assault rifles. Not backpacks that people wear 24/7 at all times. Odds are if you're wearing one of these things, your sprite will already be obscured.

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
I can't approve of the three-pixel strap sprite at all. It needs to go.

**Comment by alsoandanswer** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
