### PR TITLE
Fusion Reactor for Away Ships

### PR DESCRIPTION
**Pull request by WickedCybs**
This is a port of the nuclear reactor seen on some of the bay ships with a few tweaks done to the reactor itself. There is also a small rebalance of how much power the other generators output since the values are really high across the board even if you don't crank up the output.

When placed you will also want to map a coolant tank nearby and a bucket or something to transfer reagents between the two.  It doesn't expend much coolant so it will last most of or the entire round.

### CODE REVIEW

**Comment by WickedCybs** [comment]
Figuring out how to get the coolant to work at the moment.

**Comment by WickedCybs** [comment]
!wip

**Comment by Lucaken** [comment]
To be precise, most ships would use fusion reactors. Same thing mechanics-wise, just a matter of the name. Nuclear reactors are a very different thing and mostly abandoned by now.

**Comment by GMR25** [comment]
> To be precise, most ships would use fusion reactors. Same thing mechanics-wise, just a matter of the name. Nuclear reactors are a very different thing and mostly abandoned by now.

Isn't fusion technically nuclear fusion? The name would be correct in the contemporary period of Aurora, as people likely wouldn't associate 'nuclear reactor' with nuclear fission anymore - just nuclear fusion.

**Comment by Lucaken** [comment]
> The name would be correct in the contemporary period of Aurora, as people likely wouldn't associate 'nuclear reactor' with nuclear fission anymore - just nuclear fusion.

They might, but even then they would call them fusion reactors, because oldschool nuclear reactors (what we have today) can also still exist in Frontier systems and such. Ignoring that, it's also just making it clear for actual players.

**Comment by WickedCybs** [comment]
!review

**Review by Alberyk — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
