### PR TITLE
Assorted Bug Fixes

### LINKED ISSUE #17324: [Bug]: Broken Xeno Footwear from #16265 test merge
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Under the tajara xenowear, both versions of the jackboots do not work as well as the adhomian boots. Using them gives a bugged item that cannot be worn by tajara. Other boots such as the workboots work fine, for whatever reason.

https://i.gyazo.com/b1ec451db5b45bcd0e1c5d8a4936574d.png

### How to reproduce

1. Select footwear under Xenowear - Tajara.
2. Does not appear on preview.
3. Gives default footwear and places broken footwear in bag on spawn.

### Round ID

_No response_

### Staff ckey

_No response_

### LINKED ISSUE #17367: [Bug]: Bodymarking Tattoo (Koi, R. Arm) is broken
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

Selecting the tattoo body marking in the title does not show it in the character preview. Others seem to work.

### How to reproduce

1. go in character creation
2. select said tattoo
3. dont see it

### Round ID

cpQ-dBiE

### Staff ckey

_No response_

### LINKED ISSUE #17388: [Bug]: Bottle type selector on Chemmaster showing Chemical heaters
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When you attempt to change the bottle shape in the Chemmaster, you can't see any bottles. Just chemical heaters.

image

### How to reproduce

1. Go to bottle chemical and change the bottle
2. Click Bottle Type.

### Round ID

cpT-dLCY

### Staff ckey

_No response_

### LINKED ISSUE #17391: [Bug]: Some merchant "buy items" have no sprites
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Away Site

### Describe the issue

image
These items have no hand'held sprite. They can be purchased from the merchants trade machine. 

### How to reproduce

1)Buy object from a trader (as a merchant)
2)See that item has no sprite

### Round ID

_No response_

### Staff ckey

Melariara

### LINKED ISSUE #17394: [Bug]: Some footwear is invisible
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

image
Some footwear is invisible, both the onmob and the item icon. This doesn't only apply to tajara shoes, but some other boots, like the ones the TCFL use, are also invisible

### How to reproduce

Select tajara flats in the loadout, and try some other types of shoes too?

### Round ID

multiple

### Staff ckey

_No response_

### LINKED ISSUE #17396: [Bug]: Can no longer pull cigarettes out of a package with your mouth
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When you try to pull a cigarette out of a cigarette package with your mouth, it says "*NAME* is in no condition to handle items!"

### How to reproduce

1. Get Gato Royales Cigarette packet
2. Target mouth
3. Click self with cigarette package
4. Get told you are a cripple
5. Cry

### Round ID

_No response_

### Staff ckey

_No response_

### PR DESCRIPTION
**Pull request by alsoandanswer**
Fixes #17396
Fixes #17394
Fixes #17391
Fixes #17388
Fixes #17367
Fixes #17324

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!bugfix

**Comment by alsoandanswer** [comment]
!review

**Review by Alberyk — APPROVED** [review]

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
please don't remove the custodial holster. i've already restored it once in #15351. it differs from the regular holster, even if minorly.

**Review by FluffyGhoster — APPROVED** [review]

**Comment by alsoandanswer** [comment]
> please don't remove the custodial holster's sprite. i've already restored it once in #15351. it differs from the regular holster, even if minorly.

I am not accomodating senseless sprite bloat for a one pixel height difference that is only known and used by one person.

**Review by SleepyGemmy — APPROVED** [review]
whatever.

**Pull request merged**
