### PR TITLE
Charger Tweaks

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR tweaks and cleans up the chargers' code.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Review by Alberyk — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Arrow768 — COMMENTED** [review]
I am concerned about these changes.
For example with the cell charger you add 100kW to the cell for every 2kW consumed.
This pretty much bypasses the established power mechanics and allows some rather gamey behaviour.

For Example:
Have a room off the grid powered by a apc with a single power cell.
Add a recharger to the room.
Charge power cell in that room.
APC Charge gets reduces by 2 kW, Power Cell Charge incrased by 100kW
Profit from infinite energy.

In addition I dont see the extra defines for KILOWATT/... as we already have KILOWATTS.
Especially when you are not even using them consistently.

**Comment by SleepyGemmy** [comment]
reducing the charging rate will make charging very slow, i assume. however, if this is wanted then that is what i'll do.

**Comment by SleepyGemmy** [comment]
addressed.

**Comment by SleepyGemmy** [comment]
old power values restored.

**Comment by SleepyGemmy** [comment]
old power values restored.

**Comment by SleepyGemmy** [comment]
!review

**Comment by Arrow768** [comment]
DNM until I can review that again

**Pull request closed without merging**
