### PR TITLE
Fixing some funny glove boxes + glove snipping

### PR DESCRIPTION
**Pull request by KingOfThePing**
Ping is here to help out a friend in need, who accidentally did an oopsie.

- Puts the glove boxes from the OR walls where they belong
- Fixes glove fingertip snipping
- Fixes the xeno nitrile glove amounts in the boxes

Hopefully it all works now.

### CODE REVIEW

**Comment by KingOfThePing** [comment]
!review

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
the glove box needs its storage capacity changed from 8 to 14 to fit all the gloves.

**Comment by KingOfThePing** [comment]
> the glove box needs its storage capacity changed from 8 to 14 to fit all the gloves.

what in the goddamn

**Review by SleepyGemmy — APPROVED** [review]
requested changes addressed.

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
