### PR TITLE
Ballistic Removal

### PR DESCRIPTION
**Pull request by LadyFowls**
- [ x] Removes the ion rifle, shotgun and the lethal .45 ammo from the armory.

- [ ] Begin work on energy replacements

- [ ] Energy cell batterys

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
bro we need replacements first

**Comment by LadyFowls** [comment]
!review

**Comment by Pratepresidenten** [comment]
The ion is a ballistic weapon? Nani

**Comment by Arrow768** [comment]
This isn't going to work out.
The ion rifle is needed at this time, as it's the only effective counter to some threats.

**Comment by NonQueueingMatt** [comment]
Hard no. I don't support the removal of the ion rifle until a replacement is put in first and that has to be a separate PR.

The removal of ballistics needs to be split off. I personally like that idea, but it needs more work.

**Comment by XanderDox** [comment]
Why remove ballistics? The lethal .45 are only ever issued if there's a genuine emergency warranting them. We should not nerf security to the point of idiodicy. We should not make Security face heavily armed Mercs with rubber bullets and carbines alone either.

**Comment by LadyFowls** [comment]
> Hard no. I don't support the removal of the ion rifle until a replacement is put in first and that has to be a separate PR.
> 
> The removal of ballistics needs to be split off. I personally like that idea, but it needs more work.

This makes some valid points, I think I can work on something off to the side for this in that case.

**Pull request closed without merging**
