### PR TITLE
Pharmacy/Psych remap

### PR DESCRIPTION
**Pull request by Eyeveri**
This remaps the Pharmacy to make it considerably less cramped. It also moves the psych office from deck 2 to deck 3.  Adds a 'medical breakroom' with the left over space. It's honestly just a coffee/snack closet with a small balcony, vending machines and a box of candy.

### CODE REVIEW

**Comment by Eyeveri** [comment]
!review

**Comment by Melariara** [comment]
Why is there so much dead space in the pharmacy now? It looks way more cramped to actually produce the chemicals now.

Also, the uvent in the psych lab doesn't seem to be attached to a piping system leading in.

**Comment by Eyeveri** [comment]
> Why is there so much dead space in the pharmacy now? It looks way more cramped to actually produce the chemicals now.
> 
> Also, the uvent in the psych lab doesn't seem to be attached to a piping system leading in.

Here's the messages I sent to Mel in discord - I couldn't reply here, until now. 

There's a lot more table space now, and everything you need is basically in the 3x3. The only thing making it more cramped is the cutoff from the lab by the windooors. I hate the lack of table space that we currently have, and just the layout in general. 

Regarding the rest of the dead space, I think I'm going to condense it by one tile to the right. Maybe. Or, add tables along the windows to act as desks/prescription filling. 

Regarding the office, I have air tubes and scrubber tubes hooked up. Ping and I went over it and it should work.

and - 

Honestly, playing recent Pharm rounds, I have absolutely hated how small it is. I have felt really constricted, and overall limited by the space. Trying to make grenades is a nightmare, disposing of the bottles is a pain because almost everytime I toss something, it breaks- which isn't necessarily horrible, but when you're trying to get all of the medbay chems made in a timely manner, it gets irritating. 

Not only that, but for players who have a hard time keeping their minds on one task a time (like me), have always complained about the pharmacy being too small/not  enough table space to help make chemicals, do paperwork and also use the laptop. Even on the Aurora map. 

I don't see any downsides in the slight expansion. Medical gets a small breakroom, the Psychiatrist gets a nice view of the rafters/the third deck medical will get used more, and they're secluded even further for antag shenanigans, with one way in and one way out.

**Review by SleepyGemmy — COMMENTED** [review]
**some general feedback:**
personally, i don't like the move of the psychiatrist's office to the above z-level. this was the case on the Aurora and made the psychiatrist's office feel absent and rarely used. i hope some kind of compromise can be made where the chem room is extended while keeping the psychiatrist's office on deck 2.

as an addendum to the above, i don't like the break room section that fills the left over space from the psychiatrist's office. i feel like a better utilization of this space would be to extend the public hallway upwards and making a general, public access break area instead. (i.e. a table/some tables and vending machines.)

image
i feel like this windoor airlock is going to cause congestion and become pretty annoying rather fast, regarding ease of movement. the borosilicate window panes also feel out of place.

i also echo what Melaria said. there seems to be a lot of dead space in the room now.

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
**map feedback:**
the sofa in the break room is mapped in wrongly. it appears to be the "middle" section for both, instead of the "left" and "right" subtypes, respectively. some windows to the north part of the new pharmacy section would be nice as well.

otherwise, the map is fine as far as i can see.

**Comment by Eyeveri** [comment]
> 

I went over it again and again, and could not find a compromise that kept the Psych office the same size/not congested, and on deck two. 

Regarding the shower/doors. I can make it a single door, but the whole purpose is to ensure phoron fires don't leak out/there is an enclosed shower space still. Think of a decontamination chamber. And I used borosilicate because that's what the entire pharmacy uses, in the event of phoron spills/fires. 

There's more deadspace in the lobby, GTR, and even exam room 1, than there is in the Pharmacy. The pharmacy now only has a 3x3 area, by the door, counter, and disposals that is "deadspace" and it's just a bit open. A little open space never hurt anyone. 

Regarding the sofa, I didn't notice it. SDMM is a bit weird, I'll fix that real fast.

**Comment by Eyeveri** [comment]
So I updated the sofa, and fixed some minor stuff. I can't really add in windows without it making the medical bay backhall looking weird. So.

**Review by SleepyGemmy — APPROVED** [review]
the mapping itself is fine.

**Comment by Eyeveri** [comment]
Working on figuring out what the merge conflict is

**Review by KingOfThePing — APPROVED** [review]

**Review by alsoandanswer — APPROVED** [review]

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
Not a fan of the removal of the public stairwell leading to the little hangout area near where the psych office was, nor of the open space on the top level of medical either.

**Comment by Eyeveri** [comment]
> Not a fan of the removal of the public stairwell leading to the little hangout area near where the psych office was, nor of the removal of the open space on the top level of medical.

As discussed in discord, the opening is still there, just half in size.
https://gyazo.com/5a5543e367c6a9774d99b582655047a5

and I'll add a staircase to the little break room balcony when I'm home from work.
https://gyazo.com/5a5543e367c6a9774d99b582655047a5

**Comment by Eyeveri** [comment]
Gotta fix this merge conflict and add in matt's requested changes. Give me a bit.

**Comment by NonQueueingMatt** [comment]
Inactive.

**Pull request closed without merging**
