### PR TITLE
Removes secret chems and mystical hoodoo, misc. map changes, fixes a typo

### PR DESCRIPTION
**Pull request by MarinaGryphon**
* Fixes a misspelling of 'withdrawal'.
* Removes all secret chems.
* Removes chemicals deemed too magical. This will probably be relatively contentious.
* Gives Chemistry some more space.

### CODE REVIEW

**Comment by Arrow768** [comment]
This policy suggestion has been dismissed here:
https://forums.aurorastation.org/viewtopic.php?f=126&t=10813

**Comment by MarinaGryphon** [comment]
Wrong thread, check the suggestions forum for the new one.

**Comment by Alberyk** [comment]
Sorry but you are leaving behind a lot of magic; remove wizards, cult, vampires and phoron too.

**Comment by Arrow768** [comment]
Please provide a link to it.
The topic I linked above is the only relevant topic that I found.

The only other topic that I found mentioning secret chems is [this one](https://forums.aurorastation.org/viewtopic.php?f=18&t=11137)
But the OP **is not suggesting** the removal of secret chems here.

**Comment by MarinaGryphon** [comment]
The ones currently in-game are mystical hoodoo, OP's words, and I quite agree.

**Comment by Arrow768** [comment]
Yes the ones in game are mystical hoodoo, and he suggested them to be changed to something phoron-related not removed. (Which I actually agree with)

The topic you linked is discussing changes to them, not their removal.
Therefore this PR does not represent the discussion in the topic.
If you want to remove them, make a new policy suggestion in the correct subforum that requests their removal.

**Comment by MarinaGryphon** [comment]
The removal is just a stopgap solution until they can be reworked, but as it stands these things completely break immersion and should be removed.
Keeping them until they are fixed or reworked would be a terrible idea, and only damage immersion further.

**Comment by NonQueueingMatt** [comment]
This PR being a thing is saddening. There is a limit to how far you can take immersion, yes we are HRP, but the fact that a *secret chemical which is almost never made* with a magical name is too preposterous for our server is simply stupid.

Secret chems slowly being ruined by the players _themselves_ isn't what I expected.

**Comment by skull132** [comment]
This solves nothing and you're giving stupidity more attention than it deserves. No.

**Pull request closed without merging**
