### PR TITLE
Can't speak in radios while cuffed + no more radio icons in messages

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
Title

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Comment by alsoandanswer** [comment]
I don't think you should remove radio icons, they give chat a little more extra flair, and it isn't really impactful gameplay wise

**Comment by NonQueueingMatt** [comment]
Radio icons also incidentally tell you what radio the user is using. I don't like that being a thing, it's pretty soft meta.

**Comment by alsoandanswer** [comment]
Soft meta, but it isn't earth shattering immersion breaking

**Comment by NonQueueingMatt** [comment]
I never said it was.

**Comment by synystersparx** [comment]
I don't even think the icons are soft meta. I can tell when someone is speaking on an intercom VS a headset IRL.

**Comment by Sindorman** [comment]
> Soft meta, but it isn't earth shattering immersion breaking

It has made lots of situations bad. Lots of people would want icons out because it broke rounds since people meta off the radio icon if someone is same identity.

**Comment by Pratepresidenten** [comment]
Leave the icon in for the AI maybe? Not the borgs, just the AI.

**Pull request merged**
