### PR TITLE
[MAP] Several major remaps, and additions.

### PR DESCRIPTION
**Pull request by Juani2400**
Mapwise, these are the changes:
- Remap: Atmopsherics.
- Remap: Captain's Office.
- Remap: Head of Staff Conference Room.
- Remap: Chief Medical Officer's Office.
- Remap: Medical Briefing Room.
- Remap: Security Processing and Holding Cell.
- Modification: Robotics Laboratory.
- Addition: Desk Ringers in several locations.
- Fix: #3391, #3374, #3345, #3341, #3308, #3306, #3277, #3244, #3173, #3094.
- Several other minor changes.

Codewise, the following has been modified:
- A new subtype of folder has been sprited for the Security folders.
- More colours of flooring decals were added.
- New colours for pipes were added (Lohikar).

Images:
image

image

image

image

### CODE REVIEW

**Comment by Juani2400** [comment]
The merging needs to wait for the ringers to be merged. Also, a new map file will be reuploaded soon due to conflicts.

**Comment by Juani2400** [comment]
maps/aurora/aurora-3_sublevel.dmm had to be uploaded without merging, as it caused conflicts in the mapfile.

**Comment by Juani2400** [comment]
Should be all set, despite the large number of diffs because the sublevel could not be merged.

**Comment by Lohikar** [comment]
You must convert the DMM here to TGM before this is mergable.

**Pull request closed without merging**
