### PR TITLE
New Short Ponytail Sprite

### PR DESCRIPTION
**Pull request by TheBurninSherman**
I was disappointed with the available hairstyles in the short ponytail category so I asked a friend to make a sprite that I was satisfied with.

The changes made were the addition of the file hair_ponytail_short5.dmi to hair.dmi so as add a new a pickable hairstyle in-game for human characters.

### Asset Licenses
The following assets that **have not** been created by myself are included in this PR: hair_ponytail_short5 imported to hair.dmi
| \Aurora.3-master\Aurora.3\icons\mob\human_face\hair.dmi | Kyres1 | CC0 |

### CODE REVIEW

**Comment by TheBurninSherman** [comment]
!review request

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
you didn't actually add the ponytail as a selectable option in the loadout.

**Comment by TheBurninSherman** [comment]
I will review and see to add it properly. First time doing this, so I would think there's a little bit of trial and error.

**Review by SleepyGemmy — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Comment by alsoandanswer** [comment]
I'm just asking, is 'Auroralocal' your master branch?  If so, you need to make a branch or else you'll mess up your git.

**Comment by TheBurninSherman** [comment]
Aurora Local is not my master branch but rather the "local" version of the server's code I modified for the PR.

**Review by alsoandanswer — APPROVED** [review]

**Pull request merged**
