### PR TITLE
Power cells now drain to zero

### LINKED ISSUE #6559: Cyborg power warning is broken
When a cyborg runs out of power, when you try to use "Power Warning" it still says "You can only use this emote when you're out of charge." like if you still had power

### LINKED ISSUE #10269: Cybord power warning
Out of power.
 when pressing the button it says i cannot use it unless im out of power.
bilde

### PR DESCRIPTION
**Pull request by mikomyazaki**
Fixes #10269
Fixes #6559

Power cells with an extremely small amount of power left were not satisfying `charge == 0` checks, but was too small to satisfy any power demands -- And thus never actually becomes zero.

There are many checks that just do `!cell?.charge` that expect a 'no charge left' state to be exactly zero.

### CODE REVIEW

**Comment by mikomyazaki** [comment]
!bugfix

**Comment by mikomyazaki** [comment]
!review

**Comment by Amunak** [comment]
Are you sure this won't cause problems when `amount` is some big number, when a smaller check would succeed?

Additionally, some devices (like APCs) use `cell.use()` directly, therefore not triggering this fix. APCs have their own checks and whatnot so perhaps it's not an issue there, but maybe adding something extra to `use` like setting charge to 0 when it's smaller than 1 would catch some extra edge cases as well?

**Comment by mikomyazaki** [comment]
> Are you sure this won't cause problems when `amount` is some big number, when a smaller check would succeed?

I've looked at every usage of `checked_use()` and I don't think it will cause any differences. **One** exception is that it will cause the 'used_power_this_tick' on the tick before the robot runs out of power to be zero instead of whatever was left in the cell, which is used for the stat display panel - I don't think this will make a difference to anyone since they already ran out of power.

> Additionally, some devices (like APCs) use `cell.use()` directly, therefore not triggering this fix. APCs have their own checks and whatnot so perhaps it's not an issue there, but maybe adding something extra to `use` like setting charge to 0 when it's smaller than 1 would catch some extra edge cases as well?

`use()` already does what I'm trying to make `checked_use()` do.

With my change included, the difference between `checked_use()` and `use()` is that `use()` will return a value if there was ANY power left, whereas `checked_use()` will return FALSE if the amount of power left was less than `amount`, or TRUE if there was (charge >= amount) power left. They will both return 0 or FALSE if there is 0 charge.

They will now both fully drain the cells.

**Comment by mikomyazaki** [comment]
Realised that use() does a bunch of things, and may be overridden for a particular cell. So I've changed things slightly.

Overall behavior is the same.

**Review by Amunak — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
