### PR TITLE
Moving emitters

### LINKED ISSUE #4778: Uneven count of spare emitters
Checklist before you submit an issue! Feel free to partially or fully delete this in your eventual report.
[x] Do a quick key word search of the git for duplicate reports. If you find any, simply post a reply onto that issue instead!
[x] Please be specific in your description of the issue. Explain the desired result (what should be happening) and the actual result (what is happening). Simply stating that [something happens] is not very helpful at describing what's wrong.
[x] Have you tried reproducing the issue? If yes, steps to reproduce it would help immensely!
[x] All additional details help. Such as round ID, an admin you talked to if the issue required immediate fixing, etcetera, etcetera.

**Current state of being**
Currently there are three spare emitters, one emitter in the SuperMater engine and four emitters with the tesla kit.

**Requested state of being**
Four spare emitters, one in the SuperMater engine and Four Emitters with the tesla kit

**Reasoning behind it**
OCD wise I hate three, It feels awkward to have an uneven amount of spares. Besides putting up a forcefield around a tesla or singularity requires four of them. All considering, it may be nice to have four spare emitters in case people try to play with the Tesla or Singularity.

**Balance issues and round disturbance**
The only reason for there being three is to force interaction with other departments such as, in this case, cargo. In my humble opinion it seems unwarranted to put people making VERY time consuming custom redesigns through the process of waiting on cargo (without the (un)willingness of cargo taken into account) or force them to gut a vital Super Mater part.  Thus in the current setup, cargo is rarely asked for a fourth spare emitter because it's not worth the time and energy.

Having four, gives more options to engineering gameplay during low-pop hours while not significantly impacting the round for other departments besides (possibly) engineering.

**Need of change**
Considering the bugs regarding the power/apc issues around the Tesla are being solved, it is to be expected that it will be used more and experimented (yeay) on more in the near future. This request gives people wanting that gameplay more options. 
Said gameplay (experimental Tesla designs) is tested yesterday and the day before and does add to an increase in certain RP (and looc) player interactions even on low-pop hours.

### PR DESCRIPTION
**Pull request by Sindorman**
A player asked to move around emitters from storage and add more spare to Tesla. This fixes #4778 . So the list of changes:

- Deleted two spare emitters from SM storage room, leaving it with 1 spare.

- Added 3 spare emitters to Tesla storage. 

- Moved Tesla machinery around in Tesla storage, making room to walk around.

### CODE REVIEW

**Comment by Arrow768** [comment]
The reason for the limited number of emitters is that emitters are the main way to combat a malf AI.
It´s already hard enough to get rid of the emitters as malf.

**Comment by Ornias1993** [comment]
@Arrow768 One more emitter does not change that, besides most of them are futher from the AI core this way, in a less frequently used location. Which means all you need is one borg to get rid of 4 of the spare emitters.

**Comment by Sindorman** [comment]
@Arrow768 But I moved these emitters from Main to sublevel and added added 2 more, they are all on sublevel which is harder to pull around? Though I think if you have less spare emitters then required that will make you interact with cargo more.

**Comment by Ornias1993** [comment]
@Sindorman I have debated myself about the "Cargo thing" too, I think two extra emitters is too much, as soon as je need a spare for the supermater you need cargo's assistance anyway.

I think placing four spare emitters in total spread over the two storages, is the most "middle ground" option. Five is a bit off and also gives more risk for the AI during malf.

**Comment by Sindorman** [comment]
Okay, I have removed one spare in Tesla storage. Making it now have 1 in SM storage and 3 in Tesla storage.

**Comment by Ornias1993** [comment]
Yeah, I think this is agreeable by most people and actually makes MALF a little more... well... "Dynamic" :)

**Pull request merged**
