### PR TITLE
Bluespace drive

### PR DESCRIPTION
**Pull request by FluffyGhoster**
immagine

Added the bluespace drive.
Fixed overmap projectiles not transferring correctly.
Code improvements. A lot of.

### CODE REVIEW

**Comment by courierbravo** [comment]
Internal walls are using cardinal ship walls. Internal walls, outside of rare use cases like burn chambers, should be using /turf/simulated/wall and /turf/simulated/wall/r_wall, the standard steel and reinforced walls.
Likewise with windows, they should be using the normal window frame spawners, not the hull spawners.
There's a lightswitch directly on the window. It should be on a solid wall, not the windowframe/glass.
image

**Comment by courierbravo** [comment]
The ceiling above has no plating covering it, leaving it exposed.
The area above will need to be edited partially to accommodate for the new floor.
image

**Comment by courierbravo** [comment]
The room is cramped and lacking adequate detailing. 
Please replace the floor under the equipment with bare plate or some similar change (see: supermatter and INDRA)
Please also expand the area, so that engineers can safely work in the room and make modifications. 
image

**Comment by courierbravo** [comment]
While technically passable, this room needs at least one more set of vents/scrubbers. Additionally, the pipes shouldn't be crossing over each other. See guidelines_atmos_pipes.dmi for examples of proper piping.
image

**Comment by courierbravo** [comment]
Please rewire it from feeding off of the engineering sublevel grid to directly off the main grid. 
Additionally, since its on its own SMES network, the room should have its own powernet sensor and breakers.
image

**Comment by courierbravo** [comment]
The drive being a box jutting out the side of the ship doesn't look good. I strongly recommend consulting the mapping team on how we can remap a portion of the maints area there and even that whole side of deck 1 engineering to properly incorporate this.
image

**Review by courierbravo — DISMISSED** [review]
From a mapping perspective, this needs a good bit of work still. Issues detailed.

**Comment by FluffyGhoster** [comment]
> Internal walls are using cardinal ship walls. Internal walls, outside of rare use cases like burn chambers, should be using /turf/simulated/wall and /turf/simulated/wall/r_wall, the standard steel and reinforced walls. Likewise with windows, they should be using the normal window frame spawners, not the hull spawners. There's a lightswitch directly on the window. It should be on a solid wall, not the windowframe/glass.

Fixed

> The ceiling above has no plating covering it, leaving it exposed.
> The area above will need to be edited partially to accommodate for the new floor.

Fixed

> The room is cramped and lacking adequate detailing.
> Please replace the floor under the equipment with bare plate or some similar change (see: supermatter and INDRA)
> Please also expand the area, so that engineers can safely work in the room and make modifications.

Disagree

> While technically passable, this room needs at least one more set of vents/scrubbers. Additionally, the pipes shouldn't be crossing over each other. See guidelines_atmos_pipes.dmi for examples of proper piping.

Implemented

> Please rewire it from feeding off of the engineering sublevel grid to directly off the main grid.
> Additionally, since its on its own SMES network, the room should have its own powernet sensor and breakers.

They aren't connected in cascade, they both feed from the same wire

> The drive being a box jutting out the side of the ship doesn't look good. I strongly recommend consulting the mapping team on how we can remap a portion of the maints area there and even that whole side of deck 1 engineering to properly incorporate this.

Not meaningfully different than the other "boxes" that jut out of the side of the ship, eg. the science firing range

**Comment by courierbravo** [comment]
The amount of atmos int the room isnt acceptable. Especially for a room handling gases like phoron.
The SMES's still need to be being fed from the main power line (red cable)
The firing range has detailing around it, along with fitting neatly under the ship. Where as the bluespace drive is jutting out from the side of the ship, visible from z layers above it.
Going to communicate further over discord as required.

**Comment by FluffyGhoster** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Geevies — APPROVED** [review]
i glanced at this and it scared me so fingers crossed the testmerge got all the big bugs out

**Pull request merged**
