### PR TITLE
Package Wrap Amount Tweak

### PR DESCRIPTION
**Pull request by VisVirific**
* Increases the Package Wrapper amount from 25 to 30

### CODE REVIEW

**Comment by VisVirific** [comment]
!review

**Review by JohnWildkins — APPROVED** [review]
powercreep

**Comment by VisVirific** [comment]
The mathematical meta is unbeatable

**Review by Doxxmedearly — APPROVED** [review]
Great, now antags will be wrapping crewmembers up left and right, this is ridiculous

**Review by NonQueueingMatt — APPROVED** [review]
powercreep

**Pull request merged**
