### PR TITLE
Refactored security levels

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Refactored how security levels work, they are now datums with a subsystem to manage them.
Added and reflavored the security levels to better track the security status of the ship.
Some alert levels now have different colors for the lights, and set the screens.

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!review

**Comment by nauticall** [comment]
I think the alert levels being numbered 5-1 (in descending order) is confusing and inappropriate for the alert levels. I get the inspiration from DEFCON, but that is more for a preparedness level and a military/national context whereas this is a direct alert level on a civilian ship. I'd much prefer either using colors or Greek letters (code alpha, beta, gamma, delta, epsilon, etc) or something like it; it would be more intuitive for people overall and cause less fuss over "Which one is more severe again?" being said over radio. Alert level names should be concise.

**Comment by FluffyGhoster** [comment]
> I think the alert levels being numbered 5-1 (in descending order) is confusing and inappropriate for the alert levels. I get the inspiration from DEFCON, but that is more for a preparedness level and a military/national context whereas this is a direct alert level on a civilian ship. I'd much prefer either using colors or Greek letters (code alpha, beta, gamma, delta, epsilon, etc) or something like it; it would be more intuitive for people overall and cause less fuss over "Which one is more severe again?" being said over radio. Alert level names should be concise.

I don't agree, this is very loosely inspired with REDCON (https://en.wikipedia.org/wiki/REDCON) and everyone more or less know (through movies, games etc.) how this system works, it's also very easy to assume everyone who can play on an HRP server can count to 5, and there's announcements that tell you the status; on the other hand, people knowing the greek alphabet in order seems less likely (and we can't introduce intermediates, unlike with numbers that have decimals)

Lights change in intensity based on the level (condition 3 2 and 1 go from blue, to light red, to full red), you see from roundstart that you start at condition 5 (so it's easy to figure out that 4 is more of a threat than 5 but less than 3)

Also, it's cool

**Comment by FlamingLily** [comment]
I very much disagree with the mechanical/flavour changes proposed. As Nauticall has said, it's likely to be very confusing and frankly, doesn't fit the alerts as we have them currently. It's difficult to put a single scale of severity on Blue and Yellow, as they're kind of unrelated to each other; DEFCON and REDCON are military readiness counters and therefore start at 5 because that's when the military has to be "least ready." The Horizon isn't a military ship, and instead would use something like [Marsec](https://www.edumaritime.net/isps-code/ship-security), the actual IRL maritime security codes system, which starts at 1 and ends at 3 (for "active emergency").

However, I still think the colour codes should be retained, as they're the clearest options we have, as "Green = Good, Red = Bad, Yellow and Blue in between" are extremely simple to understand (And Delta being the exception for not being a colour helps with this).

I also have things to say that I feel only having security alerts is a missed opportunity (I think a ship like this should at least have an engineering emergency for ship damage, or whatever), but that's perhaps for a different forum.

**Comment by FluffyGhoster** [comment]
>doesn't fit the alerts as we have them currently

It's not supposed to, that's why the changelog says reflavored

>The Horizon isn't a military ship, and instead would use something like [Marsec](https://www.edumaritime.net/isps-code/ship-security), the actual IRL maritime security codes system, which starts at 1 and ends at 3 (for "active emergency").

Real civilian ships do not mount ship weapons, also I said "loosely inspired" for a reason, it's not the same, it just works from bottom up

>I also have things to say that I feel only having security alerts is a missed opportunity (I think a ship like this should at least have an engineering emergency for ship damage, or whatever), but that's perhaps for a different forum.

It's in my plans to add more options for the 1MC, but it'll be a separate system from the ship alert level, which is only supposed to represent the ship security status, this will come at a later date, considering this change was one of the first thing i wanted to make two years ago but was pulled away from to other things until now

**Comment by Bear-the-bare** [comment]
I'm afraid I do not feel this fits the corporate team, nor was this brought to myself as much of this effects corporate regulations and will ask a lot of with the CCIA team for reworks and requires our input.

I'm not against a potential rework of the alert status and regulations regarding it, but until I've given input this change should not go through.

Feel free to message me directly on discord, @bear0117

**Review by Arrow768 — CHANGES_REQUESTED** [review]
The old names/descriptions of the security levels need to be kept.
If you want to change that, it should be part of a separate PR

**Comment by NonQueueingMatt** [comment]
Pretty much what Arrow said.

**Comment by FluffyGhoster** [comment]
I have no interest in changing it again to then undo it all over, I'd have to repath the levels and whatnot, which are the main point why I started this, and I see no reason why it'd be needed: There's no technical difference that requires to split the two things

If it takes a while for the verbiage change to be discussed, that's perfectly fine, I'm in no rush

**Comment by NonQueueingMatt** [comment]
I don't really see us accepting these new security levels unfortunately? They're kind of going against the recent anti-militarization changes imo

**Comment by FluffyGhoster** [comment]
If that turns out to be the case, feel free to close this PR (though the thought that the flavor of some level would be "going against the recent anti-militarization changes" is at best a stretch, in my opinion)

**Comment by NonQueueingMatt** [comment]
We are generally open to redoing the alert levels, but they need to be redone to be straight up better and in line with existing requirements (not contributing to a military look, for one, and secondly talking with CCIA to figure out what can be made better about the existing ones).

We additionally don't want to mix technical and policy changes in the same PR. Meaning, if any change were to happen, first of all the PR refactoring levels needs to be made WITHOUT any changes to existing alert levels. Only then we can talk about changing them.

**Pull request closed without merging**
