### PR TITLE
Bridge Shutter Fix

### PR DESCRIPTION
**Pull request by Ben10083**
Removed the improperly placed shutter.

Also added more of those shutters so they cover captain's office and break room, as if the windows at bridge need locked down, those will as well.

### CODE REVIEW

**Comment by Ben10083** [comment]
!review

**Comment by Ben10083** [comment]
!bugfix

**Review by Arrow768 — COMMENTED** [review]
Would you mind posting a picture where you highlight the new shutter locations.
The mapdiffbot is not useful when reviewing that.

**Comment by Ben10083** [comment]
> Would you mind posting a picture where you highlight the new shutter locations. The mapdiffbot is not useful when reviewing that.

https://imgur.com/a/HzInifa

Ignore the corners on the exteriors, I added shutters to them as well now.

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
