### PR TITLE
Removes medical alt titles

### PR DESCRIPTION
**Pull request by skull132**
Alternate titles for jobs are meant to be flavourful. They are not meant to be used as gameplay mechanics which incur with them restrictions, unless the mechanics to enforce these restrictions exist. In this case, they do not. It is a blight upon the design of this game that we require that players new and old must consult an out-of-game chart to figure out WHAT EXACTLY their character can do, while players of other departments are given this freedom to decide for themselves (within the parameters of the master job).

Thread: https://forums.aurorastation.org/topic/14668-fuse-medical-roles-and-detach-medical-from-the-real-job-of-medical-doctor

Names still subject to change if anyone has any better ideas.

### CODE REVIEW

**Comment by skull132** [comment]
Don't merge until we've got a final set of names (eg. if anyone has any better). Though if the PR lasts until the coming weekend, punch it.

**Comment by skull132** [comment]
Do I? Darn. This is what I get for being lazy.

**Comment by Snakebittenn** [comment]
I'd suggest Triage Technician instead of Rescue Technician

**Comment by skull132** [comment]
Considering the primary responsibilities of the rescue technician, triage technician makes no sense.

Also, get the fuck back into the thread with your suggestions for alternate names.

**Comment by skull132** [comment]
Superceded.

**Pull request closed without merging**
