### PR TITLE
Adds holopad to holodeck

### PR DESCRIPTION
**Pull request by Geevies**
Title.

It's offcentre, because the holodeck doesn't have an even number of vertical tiles. Woe is life.
image

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by AceAlvie** [comment]
Test Type: **Solo Player** as **Host** on Private Server

Testing this request, at a first glance the Holo pad appears and remains whenever the Holo Deck is changed to any other setting, but on some Decks have the pad hidden underneath a a prop.


**Suggestion**: IF possible, for each setting of the Holo Deck, the holopad be placed in more available, easy to access places, perhaps corners.
Bellow you can see the screenshots taken during the review.

Screenshot_10
Screenshot_13
Screenshot_14
Screenshot_4
Screenshot_5
Screenshot_6

**Comment by StationCrab** [comment]
Why not place it in the hallway near the emergency meet up point. The AI can drift inside the holodeck to interact with folks, this would also give the crew an ability to contact the AI through the holopad in emergencies, two birds with one stone.

**Comment by NonQueueingMatt** [comment]
The holopad placement is really bad, especially in the boxing deck. It should not be in the holodeck itself.

**Comment by Geevies** [comment]
Implementing a way for the AI to materialize in the holodeck without a holopad seems to be the best option.

**Pull request closed without merging**
