### PR TITLE
No more paint in backpressure surges.

### PR DESCRIPTION
**Pull request by alsoandanswer**
Title.

It's coarse, rough, irritating, and totally fun to be puke green for half the round.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by Butterrobber202** [comment]
It is possible to shower and remove the paint, as far as I am aware.

**Comment by Melariara** [comment]
You can also use cleaner to get rid of paint, or a mop.

**Comment by alsoandanswer** [comment]
Addendum : Pain in the ass to clean from walls. Engineers and Janitors OCD triggered. Especially wonky with special turfs like shuttles and stuff.

**Comment by Melariara** [comment]
> Especially wonky with special turfs like shuttles and stuff.

IIRC, at this point in time, paint can't get into shuttles due to shuttles not having scrubbers at all. Unsure if this will change in NBT.

**Review by Geevies — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
