### PR TITLE
Removes icon unit test

### PR DESCRIPTION
**Pull request by mikomyazaki**
"Random" unit test failures appear to be a long-existing BYOND issue (~4 years at least). If I figure out how to solve this I'll resubmit... (unlikely)

We can keep in the various icon fixes from the PR that added this test.

See:
[`in` randomly not working for a list of text strings (stored from icon_states())](http://www.byond.com/forum/post/2502930)
[`item in list` does not always work](http://www.byond.com/forum/post/2129715)

### CODE REVIEW

**Comment by mikomyazaki** [comment]
!bugfix

**Comment by mikomyazaki** [comment]
!review

**Comment by alsoandanswer** [comment]
Maybe have like, the icon test thing only test icon files modified by the PR?

If not, then big F for icon unit tests.

**Comment by mikomyazaki** [comment]
> Maybe have like, the icon test thing only test icon files modified by the PR?

Not sure it's worth it. That would be pretty complicated to do I think?

**Pull request merged**
