### PR TITLE
Makes away ships no longer shuttle subtypes

### LINKED ISSUE #13919: The Cargo freighter ghostspawn ship has a disappearing airlock
This happened twice now, the Airlock leating from the kitchen to the mining suits just disappears as soon as you leave the "Faint Ship activity" map

### LINKED ISSUE #14090: Ghostspawn Freighter OTHER airlock bug
grafik
This Airlock no longer functions properly once you leave the "Faint ship activity" map
the doors no longer cycle properly
In this image there is a vacuum inside, but the outer doors just didn't open, none of the doors locked either.

### LINKED ISSUE #14275: Ghostspawn issue - TCFL ship
grafik
There do not appear to be any navpoints for shuttles to spawn in on for the TCFL ship map

### PR DESCRIPTION
**Pull request by Doxxmedearly**
Test merge candidate. This was stupidly involved. I've tested it thoroughly but lord knows there's something I've missed.

Away ships being shuttles required janky interactions (Such as launching your ship, which should be in space, into space, again?), unnecessary sectors ("faint ship activity") and a lot of broken shit when you did launch (Disappearing and broken airlocks and machines). This should allow more mapping freedom on away ships, and honestly it just makes sense that they aren't shuttles, because they are not intended to land anywhere; they have their OWN shuttles for that.

Changes involved:
-Moved these from `visitable/landable` to just `visitable`. Duh.
-Changed the ship areas to be NOT shuttle areas (Causes horrible init issues). There is now a tidy area/ship for these.
-Made the site not initialize itself as a shuttle. Duh.
-Removed faint ship sectors (Which was a hacky workaround for them being shuttles.)
-Made mothershuttle = null (This is supposed to be used only for shuttles within shuttles. Keeping this on non-shuttles causes docking issues. It is NOT needed to return to the home ship.)
-Needed to map out some unneeded landmarks etc.
-Replaced the now-unnecessary shuttle control consoles with engine consoles (Some helms lacked these) or tables or other ways to fill the empty space.

Fixes #14090
Fixes #13919
Fixes #14275
(Possibly fixes the freighter smelter not working, will have to verify with another test)

It should be pointed out that this does not remove the ability to make landable ships that contain shuttles, if that is ever needed. But our current ships are not meant to land or dock; only their away shuttles are.

### CODE REVIEW

**Comment by Doxxmedearly** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]
Works fine after testing, it seems.

**Comment by Doxxmedearly** [comment]
Most of what I want to test is to ensure that away shuttles can dock in the hangar (Or, in the case of the TCFL shuttle, the extra docking arm). They did work on my local testing, just had to be sure.

**Comment by Doxxmedearly** [comment]
Need to address the linked issue before merge. There ARE generic navpoints that just don't work for some reason on the away ships

**Comment by Doxxmedearly** [comment]
Resolved

**Review by alsoandanswer — APPROVED** [review]

**Review by JohnWildkins — APPROVED** [review]
me when

**Pull request merged**
