### PR TITLE
Small Medical Remap + Cosmetic Changes

### PR DESCRIPTION
**Pull request by MarinaGryphon**
Because I like to give up on my dreams.

* **Various remaps of parts of Medical**:
* Pharmacy and Main Storage https://i.imgur.com/Tp01gEm.png
* Cryo + removal of Surgery mediexpress https://i.imgur.com/LfpuwNe.png
* Breakroom https://i.imgur.com/qMQutkk.png
* Secondary Storage https://i.imgur.com/70XYKWe.png
* Overview incl. lobby + EMT bay https://i.imgur.com/r4xsAIc.png
* Repaths **wall nanomed vendors.**
* Adds **patient slippers.** Repaths slippers to remove duplicate code.
* Makes patient gowns and slippers accessible via the patient wardrobes in Cloning and Virology Quarantine.
* Makes certain shoes (foam flip flops, cloth footwraps, and slippers) **not block stepping on shards.**
* Changes latex glove boxes to **nitrile glove boxes,** which have **5 nitrile gloves and 2 latex gloves.** Latex allergies are no joke, people.
* Adds a spare can of espresso grounds to Medical's breakroom. This is clear coffee powercreep.
* Renames `A can of Coffee Beans` to `can of espresso grounds`. No path changed.
* Uses **wingrille spawners** (which can now be configured to **add shutters automatically!**) instead of manually mapping in most non-electrochromic Medical windows. I was lazy with this, PR to completely do this Soon:tm:.
* Fixes one last instance of spaceacillin.
* Fixes cryo always ejecting to the south regardless of the mapped-in direction. Changes nothing gameplay-wise for now.
* Oh god Oh fuck another monolithic PR, apologises to Skull
* Adds a **roller-bed holder**, which is an **alternative to the paramedic RIG for lesser-trained personnel**. Holds several tiny to small items as well as one rollerbed, goes in the back slot, clicking with it on a rollerbed picks it up.
* **Removes the MediExpress delivery system** until it can be properly remapped without going under walls, like some kind of madman. The only part remaining is the interstitial Virology -> Virology Quarantine delivery system, which is mapped somewhat sensibly and serves an important purpose.
* God I think that's everything
* Oh, adds a manual to the EMT bay. Right.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
Fix merge error please

**Comment by MarinaGryphon** [comment]
!review

**Comment by Geevies** [comment]
Do fix the travis issues, btw.

**Comment by MarinaGryphon** [comment]
> * Please return the medical lobby to its original design, it's now an ugly mess, the behind the desk space is too big compared to the room size,
Subjective. Medical players seemed to like it.
>there's two filing cabinet objects
One starts with hard copies of records in them. It's intended.
>There's a plant placed over the memorial plaque.
Heh. This was intended.
>The lobby is now also another chokepoint -  medical's biggest problem already. The emt bay doesn't need to be bigger. An airlock between the emt bay and the lobby is a good idea though.
Subjective. Again, Medical players seemed to like it.
The rest of these are either easy to fix or were merge issues.

**Comment by MarinaGryphon** [comment]
>Remake the cryogenics room, I don't see the idea of its removal and now the cryo coolers draw power from general treatment. There's also a floating light fixture by it.

The APC now has a larger cell. People also approved the idea and hated the original.
These arguments really just seem out-of-touch with the playerbase, but I can make a feedback thread if you'd like.

**Comment by fernerr** [comment]
The lobby being cramped wasn't just pointed out by me but also Furrycactus.
Having one of the most traveled stretches in the station becomes cramped down and partly blocked by chairs and the water cooler I believe is a misstep, But if you don't think so, do make that feedback thread.
The other non-technical issues I can let slide, but not the lobby design.

**Comment by Geevies** [comment]
@MarinaGryphon Fixing this, or close?

**Pull request closed without merging**
