### PR TITLE
Dominian greatcoats and coats additions.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
- Resprited dominian greatcoats, consular greatcoats and consular uniforms.
- Added shorter versions of the dominian greatcoat to the loadout.

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Comment by alsoandanswer** [comment]
Should probably keep the black pants variants as an alternate outfit.

**Comment by NonQueueingMatt** [comment]
> Should probably keep the black pants variants as an alternate outfit.

They're completely different shading and make, I don't think they'd fit.

**Review by alsoandanswer — APPROVED** [review]
I don't particularly have any opinion, I think it looks good.

I just have an overwhelming premonition someone's going to complain that their character suddenly has white pants.

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
