### PR TITLE
Shuttle console shows scan of area around navpoint

### PR DESCRIPTION
**Pull request by DreamySkrell**
image
image

  - rscadd: "Shuttle console program shows a scan of the area when selecting a navpoint."

This could also be used in the targeting and sensors consoles.
~~I would like to see the performance impact before further work.
Currently it is refreshing every map every 30 seconds, but it is set to `SS_BACKGROUND` so it should not do this if more important things have to run. Idk.~~
removed regeneration of minimaps for now - could be brought back (and optimized) in further PRs

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!review

**Comment by DreamySkrell** [comment]
it could be test merged I guess

**Review by Alberyk — APPROVED** [review]

**Comment by DreamySkrell** [comment]
do not merge until this is more optimized

**Comment by DreamySkrell** [comment]
removed regeneration of minimaps for now - could be brought back (and optimized) in further PRs

**Pull request merged**
