### PR TITLE
Hail Lii'dra

### LINKED ISSUE #17921: [Bug]: Black Koi Zombies Need Liidra Speak and Night Vision
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When someone is turned into a zombie because of stage four black k'ois, they don't have Lii'dra speak and they don't have night vision.

### How to reproduce

1. Infect with black K'ois
2. Wait until stage 4
3. Suffer as your thrall is both blind and mute

### Round ID

crb-duGP

### Staff ckey

Fluffyghost

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Liidra zombies now speak Liidraic by default.
Fixed a runtime that prevented the Liidra zombies from speaking in the hivenet
Liidra zombies now see in the dark, like their Vaurca counterparts.
Refactored set_default_language into a proc, updated the verbs that interact with it.
Minor refactor of the set default language verb.
DMDoc'd add_language and minor refactor of it.
Removed see_in_dark related things, set it as per TG, we rely on the lighting plane only now.

Fixes #17921

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!review

**Comment by Butterrobber202** [comment]
extra work but, would it be possible to cram Lii'draic Hivenet and some sort of "Black K'ois Infected/Fellow Lii'dra" UI into a single "is lii'dra" flag so Lii'dra can ID whose on their side with ease? 

I say this because I absolutely WASTED one of my own zombies in a round a few days ago, because they had Security armor on.

**Comment by FluffyGhoster** [comment]
> extra work but, would it be possible to cram Lii'draic Hivenet and some sort of "Black K'ois Infected/Fellow Lii'dra" UI into a single "is lii'dra" flag so Lii'dra can ID whose on their side with ease?
> 
> I say this because I absolutely WASTED one of my own zombies in a round a few days ago, because they had Security armor on.

I think you're referring to the HUD? If so, you don't see the others marked because they are liidra, you see them because they are antagonists

**Comment by Butterrobber202** [comment]
> > extra work but, would it be possible to cram Lii'draic Hivenet and some sort of "Black K'ois Infected/Fellow Lii'dra" UI into a single "is lii'dra" flag so Lii'dra can ID whose on their side with ease?
> > I say this because I absolutely WASTED one of my own zombies in a round a few days ago, because they had Security armor on.
> 
> I think you're referring to the HUD? If so, you don't see the others marked because they are liidra, you see them because they are antagonists

no no, I meant like creating a specific Lii'dra indicator so a Lii'dra Antagonist can ID their zombies and other Lii'dra.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
