### PR TITLE
Allows the toy guns that spawn in the warehouse to also spawn as real guns

### PR DESCRIPTION
**Pull request by 4000daniel1**
I always thought the bang guns that spawn in warehouse had a very small chance to be real guns, APPARENTLY THEY DON'T. Most of the time these will probably just get sent off to security but since the strongest one that can spawn is the revolver it shouldn't make too much of a difference.

My hope is that it'll enable ops to occasionally get opportunities to do classic funny ops things like negligent bottle shooting contests and what not. (It's been too long since the last one)

### CODE REVIEW

**Comment by 4000daniel1** [comment]
!review

**Comment by KingOfThePing** [comment]
Please no

**Review by DreamySkrell — APPROVED** [review]
I think it's fine as long as real guns are rare

**Review by FluffyGhoster — APPROVED** [review]

**Comment by 4000daniel1** [comment]
The probability could be lowered further, but with it being in the rare category with a spawn weight of 1 I believe it's already quite rare as it is. And when it does spawn, it's most likely going to be the single shot zip gun.

**Review by Geevies — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
