### PR TITLE
Adjusts phoron scarcity bounties

### PR DESCRIPTION
**Pull request by Doxxmedearly**
Updated 4/23:
Reworded bounties to reflect current lore.
Removed the canister bounty since it was replaced at some point by the solar array bounty. Also it's... kinda weird for the exploration vessel that needs phoron to ship its fuel supply out. 

Old:
I'm sure this will need approval from lore and maintainers. 

Basically, when I made these bounties, they were only meant for the Aurora during the scarcity arc leading up to the NBT, to put pressure on them and really drive the shortage home. 

Now that we're on the SCCV Horizon, these bounties should be removed, as the vessel does not fulfill the same role as the Aurora. 

They can also be edited as lore/maintainers see fit, will make those changes if requested. But it was not meant to carry over to NBT.

### CODE REVIEW

**Comment by Doxxmedearly** [comment]
!review

**Comment by Ben10083** [comment]
I mean we are still in a Phoron scarcity crisis right? Perhaps instead of removal instead you can simply tone down the language to simply be a lucrative bounty (SCC and others will pay out the ass for some Phoron)

**Comment by Doxxmedearly** [comment]
I am waiting for maintainer and lore feedback, and will adjust it as they direct.

Personally, my thought is that since that the Horizon is primarily an exploration vessel, expecting them to constantly feed small amounts of phoron back to the SCC is not fitting. Aurora was primarily a mining and research station, so it made sense to give them high expectations for phoron shipments.

That said, there's plenty of argument that simply dropping the high_priority tag and amount expected to ship is also reasonable! It's ultimately up to the head honchos. This PR is more to bring attention to it than anything.

**Review by JohnWildkins — APPROVED** [review]

**Review by mikomyazaki — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
Caelphon's judgement is as follows:
`keep it but definitely alter the language so it’s seen as an important part of the operations across the CRZ`

**Comment by Doxxmedearly** [comment]
@NonQueueingMatt Updated

**Pull request merged**
