### PR TITLE
Adds language colours for Tradeband and Freespeak.

### PR DESCRIPTION
**Pull request by Jaraci**
See title. Done with the approval etc of @NotSchwann , the human lore man.

image
image

### CODE REVIEW

**Comment by Jaraci** [comment]
!review

**Comment by Spacemanspark** [comment]
You're a saint

**Review by WickedCybs — APPROVED** [review]

**Comment by Butterrobber202** [comment]
Tradeband color is the same as Siik'Tajr

**Comment by Jaraci** [comment]
> Freespeak color is the same as Siik'Tajr

I'm not really worried about this. We already have languages that share colours, like one of the Sinta ones and Rootsong. I don't foresee any real likelihood that this is going to pose a problem.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
