### PR TITLE
BAPI - better error handling

### PR DESCRIPTION
**Pull request by DreamySkrell**
image

now shows what map is failing

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!review

**Review by Arrow768 — APPROVED** [review]

**Comment by DreamySkrell** [comment]
do not merge, this will be integrated into the other bapi PR

**Comment by DreamySkrell** [comment]
integrated into https://github.com/Aurorastation/Aurora.3/pull/19311

**Comment by DreamySkrell** [comment]
integrated into https://github.com/Aurorastation/Aurora.3/pull/19311

**Pull request closed without merging**
