### PR TITLE
Firelock Windows

### PR DESCRIPTION
**Pull request by Geevies**
* Firelocks now have windows that allow you to see through them. Shooting through them is difficult, as the window is quite small.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by fernerr** [comment]
I don't support this. When the firedoors close, the lights turn red, vision gets limited. I find it provides atmosphere and makes you have to use your noggin before opening places.
I could support a version that has windows, but making it the defacto thing I would be against.

**Comment by alsoandanswer** [comment]
Why? Didn't you literally remove elevator windows for the exact same reason?

**Comment by Arrow768** [comment]
I am not sure about that.
Closing activating a firealarm in a area can be very useful if you want to confuse any pursuers regarding the path you took to escape them.

**Pull request closed without merging**
