### PR TITLE
Adds a stairwell

### PR DESCRIPTION
**Pull request by fernerr**
Adds a stairwell at the aft end of the surface hallway, connecting the surface to the main level.

stairs
stairs2
cargo1

 - Useful in emergencies or if you're just strolling around.
 - Makes it easier for newbs to find their way down.
 - Brings the merchant closer to the rest of the station.
 - The fire inspectors are long overdue for an inspection.

Other additions, some by stuff suggested on the forums:
 - Made security's and the captain's toilets lockable.
 - Added a scanner bed to csi autopsy room.
 - Added a second cyborg analyzer to robotics.
 - Made the accessway to telecommunications more obvious and redrew its path while also altering some maintenance tunnels in proximity as well as some asteroid paths.

### CODE REVIEW

**Comment by XanderDox** [comment]
My opinion does not matter much, but I don't think this is a good idea. The original idea for this map way back when was there'd be sabotage-able lifts controlled the primary flow of people between levels, so antags could target these locations if they needed to interfere with movement between the levels outside of maintenance access ladders.

By conjoining the Main and Surface levels with a staircase, it adds a new location that needs to be considered when trying to separate the levels or interfere with crew movement, and goes against the intention this map was originally made with.

Obviously, advancement is a good thing and the map doesn't need to stay true to the OG idea, but I don't see the point in the staircase when we already have three lifts that go to the Surface (not including the Command lift)

**Comment by KingOfThePing** [comment]
Including the command lift as a way to get to the surface is like saying there are ladders outside on the asteroid that connect the levels. Virtually useless to the majority of the crew. Stairways are a good idea, it makes little sense to rely on lifts only from an IC perspective. There are also plenty of other means to travel between levels anyway (inside the station, too) so this here hardly changes anything except making the place feel more like a real station. I support this change, it is long overdue.

**Comment by fernerr** [comment]
Sabotaging access between the levels only matters to hinder round end transfers or to camp new arrivals to the station. 
The surface level is already a ghost town for much of most rounds, where a corpse can lay cold on the ground up there for half the round without getting noticed.
This staircase is another means to promote public traffic up there during standard operation. Plus, its location has been chosen to be far enough away that the elevators are still useful.
That's all I'll say here on the matter.

**Comment by fernerr** [comment]
Please make sure #7631 is merged before this one.

**Pull request merged**
