### PR TITLE
Idris cafe

### PR DESCRIPTION
**Pull request by DreamySkrell**
image
image

- maptweak: "Remaps the third deck cafe to be Idris themed."
- rscadd: "Adds syrups and takeaway cups."

### Asset Licenses
The following assets that **have not** been created by myself are included in this PR:

| Path | Original Author | License |
| --- | --- | --- |
| icons/obj/coffeemenu.dmi | disappointedButNotSuprised | CC BY-SA 3.0 |
| icons/obj/syrup.dmi | disappointedButNotSuprised | CC BY-SA 3.0 |
| icons/obj/drinks.dmi | Crumpaloo | CC BY-SA 3.0 |

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!review

**Review by Generalcamo — CHANGES_REQUESTED** [review]
Please make sure you credit the original authors in the changelog and in the PR description (use the template provided in the default description), per the terms of the CC-BY-SA license /tg/ is licensed under.

Most sprites come from disappointedButNotSuprised in this PR: https://github.com/tgstation/tgstation/pull/70725

Takeaway cup sprite by Crumpaloo, with modifications: https://github.com/tgstation/tgstation/pull/66538

Maintainers: DNM until this is done, so we are legally ok

**Comment by DreamySkrell** [comment]
> I think my only concern here is that a lot of this stuff should also be added to the main bar, but we need to redesign that anyway.

I have added takeaway cups and empty syrup bottles to dinnerware vendors, but yeah, I'd like the impact of this PR to be minimal. Remapping only the third deck cafe - mid deck kitchen and bar can be remapped in a different PR.

**Comment by DreamySkrell** [comment]
> Please make sure you credit the original authors in the changelog and in the PR description (use the template provided in the default description), per the terms of the CC-BY-SA license /tg/'s sprites are licensed under.
> 
> Most sprites come from disappointedButNotSuprised in this PR: [tgstation/tgstation#70725](https://github.com/tgstation/tgstation/pull/70725)
> 
> Takeaway cup sprite by Crumpaloo, with modifications: [tgstation/tgstation#66538](https://github.com/tgstation/tgstation/pull/66538)
> 
> Maintainers: DNM until this is done, so we are legally OK.

addressed

**Review by FluffyGhoster — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]

**Review by SleepyGemmy — APPROVED** [review]

**Comment by DreamySkrell** [comment]
merge conflict resolved

**Pull request merged**
