### PR TITLE
himeo industrial rig variant

### PR DESCRIPTION
**Pull request by crunchypretzels**
Retrying an old project, now that I have a little time on my hands.

This allows the Himeo modkit to modify the industrial RIG(mining rig) assembly shell, made in Robotics or by disassembling an industrial rig, turning it into a Himeo variant. Sprites are by myself.

Currently, the modded hardsuit can only be worn by humans, IPCS, and Tajara, with Tajara sprites by myself. I'm more than willing to take suggestions for future revisions to the suit.

No mechanical changes; everything is cosmetic.

This PR also allows for items on the suit slot to block hair sprites, with some work.

image

image

image

### CODE REVIEW

**Comment by crunchypretzels** [comment]
!wip

**Comment by crunchypretzels** [comment]
Today's progress:

Still haven't fixed the description, but it seems to be a wider issue. 

The kit is now applied to an industrial rig assembly(get Robotics involved) or by disassembling one you buy from the mining vendor.  More sprites by me for the assembly process!

I'm happy with how the colors look. I'll give them another pass sometime when we're closer to actually pulling, but they'll probably be final barring a massive improvement in spriting skills in the next three days.

We're trying to figure out how to block hair on a suit item, but I'm beginning to believe the ability to hide hair is as cursed as RIG code.
image

**Comment by crunchypretzels** [comment]
Now with a Council variant! All bugs are fixed. We ship after raid.

**Comment by crunchypretzels** [comment]
!wip

**Comment by crunchypretzels** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
