### PR TITLE
Pneumalin for Shuttles

### PR DESCRIPTION
**Pull request by KingOfThePing**
Adds 2 Peridaxon inhalers to, as requested by this thread:

https://forums.aurorastation.org/topic/17376-load-peridaxon-auto-inhalers-onto-our-ships/#comment-158093

- the Medbay stabilization wall locker
- to the Intrepid's medical room med locker
- to the mining shuttle's emergency wall locker

This totals to 10 units Peridaxon each. Good for up to two patients, so they dont die. A reasonable amount, without being too overpowered I hope.

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
Pneumalin would maybe be preferable since it only heals lungs.

**Comment by KingOfThePing** [comment]
This is true. It is a question of balance (and I dont know how the balance of away missions is right now, so I trust your judgement):

10 units of a chemical that "moderately" heals the lungs
or
10 units of a chemical that heals all organs (except the brain) "minor[ly]".

If you say that Pneumalin is better suited, for balance reasons, then I will swap them out.

**Comment by KingOfThePing** [comment]
!review

**Comment by KingOfThePing** [comment]
Peridaxon heals 1 unit of damage per tick, split up between all damaged organs. Peridaxon is pretty shit lmao

**Review by Alberyk — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
