### PR TITLE
Fixes Ouerea Vaurca spawns

### PR DESCRIPTION
**Pull request by RustingWithYou**
Ouerea Vaurca ghostroles now actually spawn with masks so they don't die immediately.

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Comment by RustingWithYou** [comment]
!bugfix

**Comment by FluffyGhoster** [comment]
I think you also need to turn on internals as a vaurca when you put on the filter (?)

**Comment by RustingWithYou** [comment]
> I think you also need to turn on internals as a vaurca when you put on the filter (?)

`H.internal = preserve`
`H.internals.icon_state = "internal1"`
`H.update_body()`

this code activates internals

**Pull request merged**
