### PR TITLE
Ian and Corgi Resprite

### PR DESCRIPTION
**Pull request by niennab**
I've made Ian to be smaller, more corgi-like and features an SCC bow collar. All corgi's are slightly less garrish orange. Changes have been applied to Lisa and puppy variant as well.

Although unused code, the Ian clothing sprites were also moved to suit the new sprite.

corgiresprite
corgiresprite2

### CODE REVIEW

**Comment by niennab** [comment]
!wip

**Comment by niennab** [comment]
!remove wip

**Comment by niennab** [comment]
!removewip

**Comment by niennab** [comment]
!wipremove

**Comment by niennab** [comment]
New dead sprites.
corgidead
All together in game:
family

**Comment by niennab** [comment]
!review

**Review by Alberyk — APPROVED** [review]

**Review by kreeperHLC — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
