### PR TITLE
Adds alternate bridge crew uniforms.

### PR DESCRIPTION
**Pull request by TheStryker**
Adds three new bridge crew uniforms. Flavor texts on the cap and San Colette uniforms done by Schwann. If people want, I can also split up the San Colette uniforms to be a jacket and uniform.
image

### CODE REVIEW

**Comment by TheStryker** [comment]
!review

**Comment by SleepyGemmy** [comment]
making the jacket seperate would be cool, yeah.

**Review by niennab — APPROVED** [review]
I wouldn't mind seeing the jacket seperate too. Good stuff though.

**Comment by Greenjoe12345** [comment]
Could there be a version where the skirt is white and gold like the pants on the left?

**Review by NonQueueingMatt — APPROVED** [review]

**Review by KingOfThePing — APPROVED** [review]

**Comment by DreamySkrell** [comment]
Could these be named "bridge uniforms", and not "bridge crew uniforms"?
So the XO and maybe also Captain can wear them.

**Comment by DreamySkrell** [comment]
Also kinda weird how these have the "aiguillettes" or whatever. These are fancier than XO and Captain uniforms, which don't have those.

**Comment by NonQueueingMatt** [comment]
> Could these be named "bridge uniforms", and not "bridge crew uniforms"? So the XO and maybe also Captain can wear them.

You can use the custom item renaming feature for this

**Comment by TheStryker** [comment]
Broke up the uniform into a uniform and jacket, as well as added a white variant of the skirt uniform, per requests.

**Review by Haydizzle — APPROVED** [review]
Might be weird to give the same outfit to each slot instead of denoting differences with markings of prestige for captain/XO/bridge crew/etc. This looks good sprite wise. Didn't see anything out of the ordinary in the code.

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
