### PR TITLE
Health Analyzer Bandage 'n Salve

### PR DESCRIPTION
**Pull request by Geevies**
* Health analyzers now report whether the limbs have been bandaged or salved as well.

image

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by alsoandanswer** [comment]
Doesn't seem to particularly obvious. I'd prefer a small icon2html with bandage and salve icons, should be a little more self-explanatory than an unexplained [B, S]

**Review by Chada-1 — APPROVED** [review]

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
These seem really easy to not notice. Make it a little more obvious by maybe making the limb span be `good` if the organ is bandaged/salved?

**Comment by Geevies** [comment]
> 
> 
> These seem really easy to not notice. Make it a little more obvious by maybe making the limb span be `good` if the organ is bandaged/salved?

that'd imply that the limb itself is good

**Comment by Geevies** [comment]
gonna remove the changes requested so people look at the PR

**Comment by JohnWildkins** [comment]
not really a fan of the B/S either, they're not obvious as to what exactly they mean and it doesn't really help the already cluttered mess that is the health analyzer text box

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
