### PR TITLE
Adds the Izharshan Unathi Pirate ship

### PR DESCRIPTION
**Pull request by anconfuzedrock**
Adds a small Izharshan pirate ship- about as large as the Intrepid, but more densely packed, I made it a shuttle directly so that it can easily dock/board (and most importantly, so there's no confusion or awkwardness when someone wakes up late on an empty ship.) The captain is whitelisted, the 3 crewmen are not. The ship only spawns in badlands areas. This also adds the Izharshan banner and unathi pirate voidsuits.

Of note is the bruiser cannon, a single-shot unathi ship weapon first implemented for the pirates. ~The pirates get 1 explosive shell for it, which is decent (though FAR inferior to the longbow, only a bit meatier than a single flak shrapnel), but the rest of~ their ammo is makeshift canister/beehive shot, which shoots spreads that deal less damage than even the francisca and fly slower on the overmap. Canister has a few more shots, but is less accurate and has significantly less dmg/pierce. Beehive has slightly _more_ pierce than ap but deals wayy less damage- good for scaring ships to extort them, but bad at causing hull damage. Because the beehive can't really help it tear through the hull, and it's weak overall, this gun gets six beehive as specialty ammo, and 12 canister for more regular fighting.

some of the horizon docks are totally unused without even landing marks, this adds a landing mark to one of the docks for this and any ship, and also moves it a bit to the left so any ship wider than the airlock doesn't smush into the lounge.

Sprites for the flag and voidsuits by CNEGecko (alongside most of the fluff and descriptions), sprites for the gun by Kyres.

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
!review

**Review by Alberyk — APPROVED** [review]

**Comment by anconfuzedrock** [comment]
not happy I made that change right after a review, but it felt prudent since it seems we're adding more ammo to all other ships, and I hadn't really accounted for that. soo, giving it more of the canister ammo, because that's for digging through ship armor, and I'm taking out the HE shell because one big boomy on a ship probably isn't too balanced, and I should probably balance the HE shell around a ship that's expected to actually use them.

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by anconfuzedrock** [comment]
ok this is literally just adding paper and a pen I think that's ok

**Comment by anconfuzedrock** [comment]
ok, whoops, had its spawn location commented out during testing, forgot to restrict it to badlands; fixed now.

**Pull request merged**
