### PR TITLE
Makes some aliens able to select the integrated medical scanner again

### PR DESCRIPTION
**Pull request by lavillastrangiato**
* Title. The listed job was "Chemist" instead of "Pharmacist".

### CODE REVIEW

**Comment by lavillastrangiato** [comment]
!review

**Comment by FluffyGhoster** [comment]
Can you do that for the lizards and cats too?
image

**Comment by lavillastrangiato** [comment]
> Can you do that for the lizards and cats too?

what da

yeah let me cook for a second

**Comment by FluffyGhoster** [comment]
!bugfix

**Review by FluffyGhoster — APPROVED** [review]

**Review by SleepyGemmy — APPROVED** [review]

**Pull request merged**
