### PR TITLE
Animal and small creature tweaks

### PR DESCRIPTION
**Pull request by NanakoAC**
Overhauls animal AI a bit, adds autofeeding to animals that can eat, coded to have a minimal performance impact. They'll now seek food in the nearby area and automatically eat it, or beg for it if held by someone.Similar to what i did with ian, the scanning frequency gradually slows down to save performance, and jumps back to full if food is detected

Fixes mousetraps being useless, and whole ton of bugs

Changes drone laws afer discussion with administrative team, to better align with their expectations of drone behaviour

Requires some testing with containedsprites before its ready to go, so DNM until that is in

changes: 
  - rscadd: "Added automatic feeding to most animals which can eat. They will eat food nearby, and beg for food held by others. Animals may take a while to notice food near them."
  - tweak: "Tweaked a few animal sizes, metabolisms and meat amounts. Animals are a little less needy for food. Except dogs."
  - tweak: "Disciplining a dog with a rolled up newspaper will make it stop stealing food for a little while."
  - bugfix: "Fixed Mousetraps not triggering when placed on vents."
  - tweak: "Buffed mousetraps."
  - bugfix: "Dead mice don't squeak."
  - tweak: "Adjusted feedback messages for animals climbing onto people, and animals being fed by people."
  - tweak: "Cats can now walk on/under tables."
  - bugfix: "Improved animal AI, and fixed issues of runtime moving around while dead."
  - bugfix: "Made Runtime more responsive when thrown at mice."
  - imageadd: "Mice can now be worn on your shoulder (ear slot). Special thanks to superballs for making sprites"
  - bugfix: "Vent names when ventcrawling will no longer constantly shuffle around."
  - rscdel: "Maintenance drone lawset has been altered based on administrative feedback."
  - rscadd: "Drink dispensers and fax machines on tables, can now be walked under by small animals."

### CODE REVIEW

**Comment by NanakoAC** [comment]
Needs containedsprites PR to be merged in order to function properly, DNM until then

**Comment by Bedshaped** [comment]
I had an idea.

Adding cheese to mousetraps, causes any mice in view(2) to uncontrollably walk into the trap

**Comment by NanakoAC** [comment]
thats already in, hungry animals will move onto any food in sight

**Comment by Bedshaped** [comment]
Even player controlled ones?

**Comment by NanakoAC** [comment]
no, not player mice, only NPCs. It'd be a bit powerful if it could suck in players like that, i think.

This PR does buff mousetraps in several other ways, making them far more effective as traps placed on vents, which makes them a very useful anti-playermouse-weapon

**Pull request closed without merging**
