### PR TITLE
Modular Computer Buffs

### PR DESCRIPTION
**Pull request by ParadoxSpace**
- Basic hard drives are slightly less power demanding.
- Basic hard drives now fit in tablets/wristcomps.
- Everyone gets an ntsl interpreter now.

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
!review

**Comment by Geevies** [comment]
@Arrow768 IMO, P2P is fine, since you can share text documents that way. How do you feel about allowing P2P in?

**Comment by Arrow768** [comment]
If the P2P program is changed to prevent the sharing of applications, then I dont have an issue with it.

**Comment by ParadoxSpace** [comment]
Update:
Removes NTNet downloader and p2p transfer.
Adds news browser and ntsl interpreter.

**Comment by ParadoxSpace** [comment]
Removed news.

**Pull request merged**
