### PR TITLE
Tarwa Conglomerate Ship Remap

### PR DESCRIPTION
**Pull request by beepbopbeepbop**
Remaps the old Tarwa Conglomerate ship to be up to current mapping standards, and adds a new suit cycler variant for the Tarwa voidsuits.

### CODE REVIEW

**Comment by beepbopbeepbop** [comment]
!review

**Comment by DreamySkrell** [comment]
image
stray pipe

**Comment by DreamySkrell** [comment]
image
do not change frequency on airlock markers

**Comment by DreamySkrell** [comment]
image
all away site/ship maps should be 255x255

**Review by DreamySkrell — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by FluffyGhoster** [comment]
Unit tests are failing, merge master and fix the unit tests (https://github.com/Aurorastation/Aurora.3/actions/runs/9983704036/job/27591758335?pr=19627)

**Pull request merged**
