### PR TITLE
Balancing the Nar'sie summoned creature

### PR DESCRIPTION
**Pull request by OneOneThreeEight**
* tweak "Reduces speed of the Nar'sie summoned creature, buffs their maximum health to make them tanky."

Getting rushed by large blob-like insanity other-things is very silly, especially when you can't really counter their mobility. Originally, they'd put you into crit almost instantaneously and _break all of your bones_. Due to how mob code works, they can attack you and chase you, because their attacking within the millisecond as they can in range with you is effectively perfect as opposed to how human reaction time and input works.

 Instead, however, their mobility is much less overwhelming with this change, but they're very tanky, so trying to kite them is "easier" but not without its own difficulties. God help you if you get into range of their devastating melee attacks, or if you get swarmed by several of them.

Granted, a cult apocalypse is probably not meant to be survivable, but when you're two tiles away from a closet and that close to getting safety before gettin' ganked by a creature, it's a bit dumb.

### CODE REVIEW

**Comment by OneOneThreeEight** [comment]
WOWIE ZOWIE IT ACTUALLY WENT THROUGH +111

**Comment by NanakoAC** [comment]
are you sure the speed var works like that? Ususually with movedelays, a lower value is faster

also, these creatures aren't limited to cult shenanigans iirc, but i approve of these changes

**Comment by NanakoAC** [comment]
@OneOneThreeEight Can you confirm that the change to the speed value actually works how you intend it to? ie, that this negative value slows the monster down, and doesnt speed it up

**Comment by skull132** [comment]
I did some testing, and on the live server, it doesn't appear to change anything?

**Comment by OneOneThreeEight** [comment]
@NanakoAC It did in my fork. I've no idea why the speed variable doesn't work on live.

**Comment by NanakoAC** [comment]
/mob/living/simple_animal/movement_delay()
	var/tally = 0 //Incase I need to add stuff other than "speed" later
	tally = speed
	if(purge)//Purged creatures will move more slowly. The more time before their purge stops, the slower they'll move.
		if(tally <= 0)
			tally = 1
		tally *= purge
	if (!nutrition)
		tally += 4
	return tally+config.animal_delay


Higher speed value means a higher movedelay means slower movement. I'm pretty sure youve made those creature faster, not slower

**Comment by skull132** [comment]
Tbh, I'm finding it difficult to slowdown the creature through no matter the values I apply. I've stopped testing at runtime and resorting to editing and recompiling for test purposes. No dice no matter the modifications I make: the monster still matches speed with a human that's running away.

**Comment by OneOneThreeEight** [comment]
I was warned to not touch mob, might as well close this for now until somewhere in the convenient future that mob code can be looked at. The first time I tested it, it was properly slow, but loading the same patch again, it's the same as on live.

**Pull request closed without merging**
