### PR TITLE
Wiring Guidelines map

### PR DESCRIPTION
**Pull request by Eyeveri**
This map is to provide the proper wiring palette, how to setup basic power nets - with examples of what not to do as well.

I include two miniature stations, one with proper wiring, and the second with improper wiring - per our mapping guidelines. 

Additionally I added several examples of what to do, and what not to do when routing wires into buildings, as well as setting up electrified windows.

### CODE REVIEW

**Comment by DreamySkrell** [comment]
image
image

pretty sure, these wires are not going to connect, so it's not correct

**Comment by DreamySkrell** [comment]
image
these wires not connected to these APCs

**Comment by DreamySkrell** [comment]
image
stray wires under SMESes

**Comment by DreamySkrell** [comment]
image
image

some wrong prefabs
wires should only have set the `icon_state` var
should not set these vars:
- d1
- d2
- dir

**Review by DreamySkrell — APPROVED** [review]
forgot to approve :skull:

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
