### PR TITLE
Blinking lights for the Janitor's wet floor signs

### PR DESCRIPTION
**Pull request by Fire-and-Glory**
I think we can agree that the wet floor signs just aren't visible enough right now.

rscadd: "Gave the Janitor's wet floor signs lights that can be used by activating them in-hand."

Credit goes to Alberyk for coding the signs but I don't think that fits in the changelog.

### CODE REVIEW

**Comment by NanakoAC** [comment]
I think you should give these lights a timeout, maybe 55 minutes, after which they turn themselves off again.

Wet floors dry up, but janitors sometimes forget to remove the signs. having the lights autodeactivate would help give more accurate information

You should also add alt+click functionality to turn the lights on and off while the signs are deployed on the floor. Look at modules/hydroponics/trays/tray.dm for an example of how its done

**Comment by skull132** [comment]
Thoughts on the above, @Fire-and-Glory ?

**Comment by NanakoAC** [comment]
Just to clarify a little, the lights idea is a "maybe this would be nice, not really important" The alt-click is more 'utterly essential, because the signs will be a pain to use without it'

**Comment by Fire-and-Glory** [comment]
The timeout isn't something I'm _quite_ willing to do because I can't actually code and don't like pestering other people.

I'd say if the janitor left them somewhere then someone'd probably turn them off after a while, s'not like they're ID locked.

What does confuse me is how being able to turn them on and off on the floor is 'utterly essential', if you're going to put a sign on the floor, you'll need to get it in your hand first, no? And why would you turn the sign off and _not_ pick it up and take it away?

**Pull request merged**
