### PR TITLE
Tentative Europa Mech Port

### PR DESCRIPTION
**Pull request by Geevies**
Maybe ports the refactored mechs from Europa over to us. Full credits to the code goes to MistakeNot4892, the original coder. I'm just shuffling code around to make it work over here. I don't even know if it works, because I'm currently stuck on a few procs. Lmao, let's try this.

### CODE REVIEW

**Comment by Geevies** [comment]
I marked all the issues I ran into with "TODO", so you can Crtl + F to search for that if you wish to.

**Comment by Geevies** [comment]
!wip

**Comment by Geevies** [comment]
So, it compiles. The main issue I have now is the HUD, and that's mostly because it uses a "PoolOrNew" proc, and I have no idea what that does.

**Comment by Sindorman** [comment]
Uhm, I don't like it having one file per each mech part like "legs", "arm", etc. There are so many tiny files that needs to be combined. 

Another note is that their code uses `usr << message` which has to be changed

**Comment by Geevies** [comment]
> 
> 
> Uhm, I don't like it having one file per each mech part like "legs", "arm", etc. There are so many tiny files that needs to be combined.
> 
> Another note is that their code uses `usr << message` which has to be changed

Changing the user << and world << to to_chat and visiblemessage is the very last thing on my to-do list. I wanna get these working before I try and polish them.

Fair, I can condense those tiny files into one file with forwardslash separators, no biggie.

**Comment by Geevies** [comment]
Riiiight. That's all the porting work done. It compiles, woo. The UI works, you can open and close cockpits, you can eject, you can lock your cockpit. Good stuff.

Now, I just need to modify mech fabricators to print the new mech stuff, and then remove the old mech stuff. And also add all our current mech equipment to this system. Wew.

Also the mech is invisible. It used to work before, so something probably buggered up. Lmao. I'll fix that.

**Comment by Geevies** [comment]
Closing PR for personal reasons.

**Pull request closed without merging**
