### PR TITLE
Adds a mini disposals bin to medbay lobby.

### PR DESCRIPTION
**Pull request by FirinMaLazors**
Per TronHoward request.

### CODE REVIEW

**Comment by FirinMaLazors** [comment]
!review

**Review by fernerr — APPROVED** [review]

**Comment by Geevies** [comment]
Are the ones added to the elevators actually connected to disposals?

image

**Review by fernerr — CHANGES_REQUESTED** [review]
I didn't realize you had added more than the 1 bin, I don't find those spots fitting, so remove them for now.

**Comment by FirinMaLazors** [comment]
Crap, I'm so sorry!  I thought I had removed those.

**Review by fernerr — APPROVED** [review]
No worries, it happens.

**Review by Geevies — APPROVED** [review]

**Pull request merged**
