### PR TITLE
Fixes invalid clicking on chalk/crayons

### PR DESCRIPTION
**Pull request by Kaedwuff**
Per #6425 pointing out that you can click chalk, I discovered that the creator of #6393 neglected to bother coding in exceptions for all illogical children of the pen item in their rush to add in new memes.

Fortunately, I have cleaned up the mess.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
lmao this is hilarious

**Comment by alsoandanswer** [comment]
!bugfix

**Comment by skull132** [comment]
!bugfix

**Comment by TehFlaminTaco** [comment]
I assure you it was an oversight in that I forgot Crayons were technically pens.

**Pull request merged**
