### PR TITLE
Alt-title access fixes

### PR DESCRIPTION
**Pull request by Doxxmedearly**
No alt-title access was working, because `get_id_assignment()` returned their alt-title WITH their corporation's suffix, such as (Hepht) or (Idris), which fucked up getting values from the additional access list. 

By fixing this, it also fixes issues with corp reporters and tech support not having correct access.

Just made it so the suffix gets ignored on `get_id_assignment()` when the ID imprints job accesses. Doesn't affect how the job title appears on their ID or manifest or anything else.

### CODE REVIEW

**Comment by Doxxmedearly** [comment]
!review

**Review by Generalcamo — CHANGES_REQUESTED** [review]
Per #16211 and #15061, apprentices are not supposed to have alternative access. They should have basic access to their main department lobby only.

**Comment by Doxxmedearly** [comment]
> Per #16211 and #15061, apprentices are not supposed to have alternative access. They should have basic access to their main department lobby only.

Resolved and updated

**Comment by Generalcamo** [comment]
!bugfix

**Review by Generalcamo — APPROVED** [review]

**Comment by Doxxmedearly** [comment]
!bugfix

**Review by SleepyGemmy — APPROVED** [review]

**Pull request merged**
