### PR TITLE
Improved vent, scrubber and holopad sprites

### PR DESCRIPTION
**Pull request by alsoandanswer**
Title.
They should look more familiar to the old ones while having a new shine.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by Geevies** [comment]
Is this just a bayport?

**Comment by BoryaTheSlayer** [comment]
Familiar? The first two look completely different, and the holopad literally looks the same as the old one lmao.

**Comment by Doxxmedearly** [comment]
The holopad is such a downgrade, I cannot agree with that change.

**Comment by alsoandanswer** [comment]
> 
> 
> Is this just a bayport?

> 
> 
> Familiar? The first two look completely different, and the holopad literally looks the same as the old one lmao.

Yes.

> 
> 
> The holopad is such a downgrade, I cannot agree with that change.

How so?

**Comment by NonQueueingMatt** [comment]
The vents and scrubbers are so extremely different that they're not really "familiar".

I also think that these pop out far more in the flooring. Definitely not going to be approving this one. I think these are pretty much a downgrade, being straight sprite ports from other codebases which completely undermines the unique Aurora imagery that we're trying to build.

The holopad sprite is just the old one, which looks far worse on the new floors. No comment.

**Comment by alsoandanswer** [comment]
> I also think that these pop out far more in the flooring.
That's the point.

**Pull request closed without merging**
