### PR TITLE
Sentences now auto-punctuate if there's no punctuation.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
See title. Shouldn't interfere with most if not all cases, however I've no way of testing bolding as it just doesn't work locally - theoretically, should be fine.

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Comment by skull132** [comment]
Would it be slightly too much to ask that we make this a preference?

**Comment by NonQueueingMatt** [comment]
It wouldn't, but I don't see the point in it. If it has to be done, sure, would only take a few minutes.

**Comment by Karolis2011** [comment]
I wonder would regex be faster then copy text?

**Comment by TehFlaminTaco** [comment]
`copytext` should be faster than regex in this case iirc. But I'd much prefer this to be a preference I can turn off.

**Comment by KingOfThePing** [comment]
You are doing gods work, son

**Pull request merged**
