### PR TITLE
Deletes Skrell

### PR DESCRIPTION
**Pull request by LordFowl**
This PR deletes all user-facing elements of Skrell (henceforth skrellements), primarily loadout items, vending machine items, voidsuit items, and the race itself, from being available in-game. These items and race datums still exist because presumably Skrell will not totally be removed from lore, so they have some potential use as adminbus items. However their total removal is certainly a feasible possibility given the necessary impetus.

Come November 3rd (The date of the next devmerge) it will have been over 100 days (102 specifically) since the Skrell have had a loredev, much less any development in their lore. When we were determining whether or not to remove Vaurca sometime in 2016, their loredev had been absent for far less, and even then their lore was not as infrequently updated as Skrell lore is. And to boot Vaurca _barely_ hung on (Yes, there was a time when Vaurca nearly were removed from the server).

If Skrell will not be updated, and will not have a loredev, and will not participate in the server lore except as something to occasionally point to as a frame of reference, then why have them available in game? They are as relevant as Vox are at this point.

I do not have the stats on hand, but I can't imagine that this lore drought has down Skrell playerbase any good either. I would be surprised to see if there were even a handful of dedicated Skrell players at this point.

- [x] Complete removal of user-facing skrellements.
- [x] Verify removal of user-facing skrellements.
- [x] Verify changes with lore-team.

### CODE REVIEW

**Comment by Sindorman** [comment]
I personally would not remove species items, etc. I would only remove In game reference and ability to spawn as skrell for players.

**Comment by LordFowl** [comment]
The species items still exist in code, but are no longer available at round-start on station (e.g. voidsuits have  been removed from EVA, skrell accessories have been removed from the loadout, skrellsnax have been removed from vendors and lunchboxes, etc.) This is what I refer to as a level 1 removal:

Level 1, Soft removal: Species is removed, but all lore and items remain intact. See; Vox
Level 2. Hard removal: Species is removed, lore is changed drastically, items are re-fluffed. See; Resomi, Bay's removal of Tajara.
Level 3. Total purge: The species is made to have never existed. All trace of it is wiped out, and to future generations its existence will be the subject of myth, not history.. See; Kocasslani.

**Comment by Kaedwuff** [comment]
Why, though?

Are there plans to implement something new in their place?  I don't particularly care about skrell, but it's odd to me to just remove them from the game because there is no lore devs around.  People still play them.

**Comment by Kaedwuff** [comment]
Is there a thread about this, then?

**Comment by zaeperry99** [comment]
"If nobody wants to become the Skrell loredev, even when faced with their removal, then I can’t imagine any of those few Skrell players cared much anyways."
I've firsthand seen people claim that they'd absolutely do it if not for things like jobs, school, or other responsibilities. Combine with the fact that there was no form of server announcement or forum thread to this project in particular right up until it was ceremoniously made a PR and posted on discord and it should be apparent why this claim is pretty much ridiculous.
I (nor I Imagine any of the Skrell players outside of the staff) were aware that without a loredev their removal was upcoming, so this attitude of 'Nobody cares if Skrell are being removed, why even keep them' strikes me as an excuse, not a reason. If you're going to go with the actually reasonable claim of 'The fact that they have no progress in the lore whatsoever right now which makes them dead weight', maybe don't back it up with nonsensical 'Nobody cares anyway' claims.

**Comment by LordFowl** [comment]
Chill out, brother. This PR is not even a day old. It's a full month until the devmerge. This change isn't being snuck in under the cover of darkness. You have seen the coming possibility, and you have an opportunity to react. The Skrell are not being removed tomorrow, nor indeed next week. I would be equally glad to see the Skrell revived as I would be to see them deleted, I just do not think it is particularly likely.

My points stand, regardless of whether you see them as excuses or reasons.

**Comment by BurgerLUA** [comment]
honestly tajara get a lot of flak for being space nazis but honestly if you look at the skrell lore you can tell that they're closely related to what happened during the rise and fall of adolf hitler and donald trump

**Comment by Arrow768** [comment]
Closing it, since it has served its purpose.
There are now a few applicants for skrell lore dev.

**Comment by LordFowl** [comment]
Just in case we need it for the November merge

**Comment by LordFowl** [comment]
Re-opening for dramatic effect.

**Comment by Arrow768** [comment]
Closing it. A new skrell lore dev has been chosen

**Comment by LordFowl** [comment]
Actually you'll find that the new skrell lore-dev has thumbs up'd this PR, which means it's approved, so please stop trying to break through departmental barriers and stick to your lane, Arrow.

**Comment by ToasterStrudes** [comment]
Heck yeah synth pride world wide glorsh did nothing wrong

**Comment by Sindorman** [comment]
@LordFowl Have you tested the PR? If it still has some skrell presence that would be a no-no.

**Pull request closed without merging**
