### PR TITLE
A few UI tweaks to help with readability on medical scanners.

### PR DESCRIPTION
**Pull request by ASmallCuteCat**
Changes some of the UI elements of medical body scanners, so that the text is colored if injury or complications are present.

### CODE REVIEW

**Review by ASmallCuteCat — COMMENTED** [review]
!review

**Comment by ASmallCuteCat** [comment]
color added 2

**Comment by sheeplets** [comment]
Could you include a few screenshots of what the changed UIs look like?

**Comment by ASmallCuteCat** [comment]
> Could you include a few screenshots of what the changed UIs look like?

scanner2
scanner1

**Review by DreamySkrell — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
