### PR TITLE
Medical Interns can access FR stuff

### PR DESCRIPTION
**Pull request by grinkgo**
#15061 added first responder interns as a title but they still do not have FR access. This just gives them access to the FR prep room/equipment.

### CODE REVIEW

**Comment by KingOfThePing** [comment]
I was specifically instructed to not give interns any specialized access, no matter the alt-title.

**Comment by SleepyGemmy** [comment]
interns should not have more than basic medical access.

**Comment by grinkgo** [comment]
afaik this only gives interns access to 1 more room, one which is relevant to its position. FR access doesn't include maint or other areas. Literally just the prep room and its contents. Surgery interns can access the ORs, no? What's the difference here

**Comment by SleepyGemmy** [comment]
> Surgery interns can access the ORs, no?

intern surgery access was removed in 15061 although improperly (forgot to remove it in `minimal_access`).

**Comment by grinkgo** [comment]
> > Surgery interns can access the ORs, no?
> 
> 
> 
> intern surgery access was removed in 15061 although improperly (forgot to remove it in `minimal_access`).

wait so they got the titles but their access got nerfed 💀

**Comment by NonQueueingMatt** [comment]
Not happening. I don't want interns fully substituting other jobs.

**Pull request closed without merging**
