### PR TITLE
(Many) Emissive Lights Now Glow

### PR DESCRIPTION
**Pull request by MarinaGryphon**
* Many emissive lights now have a glow/bloom effect.
* Some vendors had their icons changed to better match up with this. Some have yet to be fixed. Some are just bad-looking (I'm looking at you, SecTech vendor) and there's not much I can do about it.
https://i.imgur.com/oEP5Wsb.gifv
https://i.imgur.com/3QAbv6V.gifv
https://i.imgur.com/cByD2WK.gifv
https://i.imgur.com/bEc5k5z.gifv
https://i.imgur.com/8fKuQ5V.gifv
Sampling of changes: https://i.imgur.com/QpIer4J.png

### CODE REVIEW

**Comment by alsoandanswer** [comment]
i think these effects are a little too intense

also those red dots on the intercom are supposed to be there, they're for the microphone and speaker buttons, so they're red when off. you'll need to readd them manually.

**Comment by MarinaGryphon** [comment]
> i think these effects are a little too intense
> 
> also those red dots on the intercom are supposed to be there, they're for the microphone and speaker buttons, so they're red when off. you'll need to readd them manually.

They were supposed to be there until I removed them. I think having them be off rather than a different color is better.

**Comment by alsoandanswer** [comment]
> They were supposed to be there until I removed them. I think having them be off rather than a different color is better.

it's to show whether to show difference between on/off and no power. 

it's for consistency's sake, please

**Comment by MarinaGryphon** [comment]
Glowiness reduced some. https://i.imgur.com/crNjbJx.png

**Comment by alsoandanswer** [comment]
I think you forgot to push

**Pull request merged**
