### PR TITLE
Replaces loyalty implants with mindshields

### PR DESCRIPTION
**Pull request by ParadoxSpace**
Does the same exact thing except without the forced loyalty. Descriptions by the mighty Nikov.

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
!review

**Comment by Arrow768** [comment]
This has already been suggested before multiple times (in the forum of a suggestion topic and a policy suggestion)
The policy suggestion has been rejected as not wanted, therefore closing this PR.

**Comment by MarinaGryphon** [comment]
unknown-195
Has it really? Interesting.

**Comment by skull132** [comment]
> Define implant laws,

is pretty far removed from

> Rename to mind-shield implant.

**Comment by MarinaGryphon** [comment]
"Remove implants" is also the second-highest option there. If the issue is with mindshields, then so be it.

**Pull request closed without merging**
