### PR TITLE
Condenses Medical Outerwear Into Its Own Selection + A First Responder Jacket Change

### PR DESCRIPTION
**Pull request by WickedCybs**
Basically the title. We had a lot of medical suit-wear that were in their own independent selections. Condensing them should help keep things tidy and organized.

Other than this, I changed the path of the dark green first responder jacket so it can finally hold medical items (old issue apparently that it couldn't) and gave its opened condition a touch up so the side sprites wouldn't be identical to the closed state. It can also hold a medical helmet now, like the chest rig.

image

### CODE REVIEW

**Comment by WickedCybs** [comment]
!wip

**Comment by WickedCybs** [comment]
Yeah I am going Off

**Comment by WickedCybs** [comment]
Anyway I noticed the dark green FR jacket had a path that meant it wasn't a subtype of the FR jacket, and thus couldn't put any medical gear into its suit slot. Since this is already condensing a lot of the suit wear into one selection, threw it in there and also repathed it.

**Comment by WickedCybs** [comment]
This is _probably_ a better title.

**Comment by WickedCybs** [comment]
!review

**Comment by WickedCybs** [comment]
I ended up cutting the unused EMS jacket from this PR because I felt it kind of needed more sprite work.

**Review by Casper3667 — APPROVED** [review]

**Comment by WickedCybs** [comment]
Forgot the IAC gear existed, but it fits in the scope in the PR so I am condensing that into its own category too.

**Review by Geevies — APPROVED** [review]

**Pull request merged**
