### PR TITLE
Replacing carp/shark sprites.

### PR DESCRIPTION
**Pull request by Sindorman**
This PR replaces carps and sharks sprites. by thread https://forums.aurorastation.org/topic/11503-space-carpspace-shark-aesthetic-change/

- Replaces carp/shark sprites

- Moves shark sprites into animal.dmi file. Removes spaceshark.dmi

- Old sprites of carp and shark remain. Also made a new mobs that uses old carp and shark sprites

- Moves all NPC sprite files into `icons/mob/npc` folder, for organization.

- Updates all paths.

TODO:

- [x] Get gib state sprites

### CODE REVIEW

**Comment by Alberyk** [comment]
Why is the familiar sprite being removed?

**Comment by alsoandanswer** [comment]
add the new sprites, but dont delete the old sprite

put back the sprite you dumdum we still need it for admemes and wizard business

**Comment by Sindorman** [comment]
@Alberyk What? It is using new shark sprites. I am moving the sprites into one file.

**Comment by Alberyk** [comment]
The pike familiar uses the space shark sprite, the big one, and there is no reason to change it, as it is a familiar/wizard magic creature.

**Comment by Sindorman** [comment]
I can put it back.

**Comment by skull132** [comment]
Questions real quick:
* I assume holocarp and the carp AI hologram icon are replaced with the new sprites? If yes, would it be worth replacing the AI icon back into the old carp icon, siiince it doesn't make sense to have a pretty spoopy thing as an AI icon.
* Is the plushie still the old icon? I assume yes.

**Comment by Sindorman** [comment]
@skull132. No, references to carps such as plushie and holograms haven't been changed. Only mob Sprite was replaced.

**Pull request merged**
