### PR TITLE
Added a IMS and Medhud to Medical Module

### PR DESCRIPTION
**Pull request by ben10083**
Basically Added a Incision Management System (IMS) and a Medical Hud to the Medical Module

IMS; allows for more efficient surgery, at times of near death this thing can be a lifesaver (plus is a nice QOL)

Medical Hud; If the IMS isnt allowed on this module, I definitely want this. This hud will allow medical robots to set physical status of patients and is great for record keeping (seriously, why does this module not have this?!)

### CODE REVIEW

**Comment by Sindorman** [comment]
Oh... I though Borgs/AI can set their vision to security records or medical records.

**Comment by ben10083** [comment]
They can but you still need the hud to set their status (dead, SSD, etc).

**Comment by Arrow768** [comment]
MedicalHUD: Yes, I dont see a reason why we shouldnt have that.
IMS: Only via a science upgrade. Simmilar to the floodlight module.

**Comment by ben10083** [comment]
@Arrow768 Unsure how I can do that, if you could DM me and guide me how, that would be great.

**Comment by skull132** [comment]
@ben10083 I need you to push the changes removing the IMS/making it an upgrade module to this branch.

I'm closing it until you've got it sorted. You can reopen it then and we'll put it into an update.

**Comment by ben10083** [comment]
Sorry for the delay! After thinking about it, an upgrade just for the IMS seems like a waste, so I removed the IMS so it is just the Med hud now.

**Pull request closed without merging**
