### PR TITLE
Updated the sound system

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Updated the sound system with an adapted version of TG's one.
Updated the looping sounds with TG's version.

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]

**Comment by hollyhocc** [comment]
some sounds are EXTREMELY LOUD, one being the thruster sound (at least in the freebooter ship)

**Comment by FluffyGhoster** [comment]
> some sounds are EXTREMELY LOUD, one being the thruster sound (at least in the freebooter ship)

What do I have to do to make this sound play?

**Comment by hollyhocc** [comment]
maneuver in the freebooter ship and it will play, its the sound the thrusters make

**Comment by FluffyGhoster** [comment]
> maneuver in the freebooter ship and it will play, its the sound the thrusters make

Reduced it from 100 * thrust_limit * power_modifier to 70 * thrust_limit * power_modifier

**Comment by courierbravo** [comment]
Frequently able to hear sounds from far away on the horizon as if they were next to me. This has been overwhelming and even disorienting at times to hear on higher pop.

**Comment by FluffyGhoster** [comment]
> Frequently able to hear sounds from far away on the horizon as if they were next to me. This has been overwhelming and even disorienting at times to hear on higher pop.

Need more specifics on what and how to reproduce it

**Review by DreamySkrell — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
