### PR TITLE
Micheal Wave

### PR DESCRIPTION
**Pull request by alsoandanswer**
Re-adds microwaves.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by NonQueueingMatt** [comment]
Why?

**Comment by alsoandanswer** [comment]
Break room immersion and ghetto cooking. Also, I really enjoyed just microwaving donk-pockets.

**Review by JohnWildkins — CHANGES_REQUESTED** [review]
I'm biased but these probably need to be mapped on Horizon before this goes through

**Comment by NonQueueingMatt** [comment]
Remap this for the Horizon then re-open.

**Pull request closed without merging**
