### PR TITLE
Fixes CI

### PR DESCRIPTION
**Pull request by MarinaGryphon**
Paths were changed without the map updating, this makes CI fail.

### CODE REVIEW

**Comment by MarinaGryphon** [comment]
!bugfix

**Review by Alberyk — APPROVED** [review]

**Comment by MarinaGryphon** [comment]
!wip

**Comment by Geevies** [comment]
image
image

**Comment by MarinaGryphon** [comment]
> image
> image

image

**Comment by MarinaGryphon** [comment]
!review

**Comment by MarinaGryphon** [comment]
Should be fine after this point, assuming it passes.

**Comment by MarinaGryphon** [comment]
AND IT PASSES, FOUR TIMES IN A ROW

**Comment by MarinaGryphon** [comment]
so now it's failing

**Pull request closed without merging**
