### PR TITLE
Medbay Job Reshuffling

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
**The Problem**
- Currently we suffer from a problem where you can end up with whack shit like three surgeons and two nurses. In addition, you can't really add more significant alt titles without the list being bloated.

**How do we solve it?**
- Medical Doctors are renamed to Physician. It's just a better name.
- Change the Physician slots to 4 instead of 5.
- Add two separate surgeon slots.
- Thus, we end up with 2 different slots with clearly defined responsibilities.

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Comment by Aboshedab** [comment]
May I suggest giving two nurse slots? Allows symmetry and gives nurses someone to work with.

**Comment by Doxxmedearly** [comment]
Seconding Abo's thoughts. Nurses generally handle the bulk of work in medical areas. Surgeon slots great tho +1 good rper

**Comment by NonQueueingMatt** [comment]
Nurses now have two slots.

**Comment by NonQueueingMatt** [comment]
Changed yet again. Four physician with nurse and EP as alt titles and two slots for surgeons.

**Pull request merged**
