### PR TITLE
Many balance changes to halloss and damage.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
AKA "I want to off myself".

### So what's the goal here?

- Turn laser weapons into **disablers.** No, not the non-lethal kind - they'll still be lethal but more geared towards disabling the enemy and killing them if you go overboard.
- Turn ballistic weapons into **killers**, aka the weapon that actually shits on you with a combination of organ shredding, shrapnel and bleeding.
- Remedy the pain problem by decreasing the threshold at which you go horizontal (currently 200, changed to 175, pending testing).
- Fix toxin damage being too good.

### The Changelog

  - Lowered the threshold at which you fall down in paincrit.
  - Melee weapons no longer have a chance to RNG knockdown when aiming for the chest.
  - Shrapnel no longer causes direct damage. It now adds pain to the organ the shrapnel is in.
  - Lasers now evaporate less blood, but deal more pain.
  - Arterial bleeding is now MUCH nastier.
  - Ballistics now suffer a lower damage penalty after damaging organs.
  - Toxins have been nerfed overall.
  - Buffed the liver's breaking threshold.
  - Ballistics now inflict slightly more pain.

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Comment by NonQueueingMatt** [comment]
!review

**Comment by Butterrobber202** [comment]
Will lasers still work good on simple mobs?

**Comment by NonQueueingMatt** [comment]
> 
> 
> Will lasers still work good on simple mobs?

Laser damage is unchanged.

**Pull request merged**
