### PR TITLE
Nerfs damage multipliers sourced from hulk and red nightshade usage.

### PR DESCRIPTION
**Pull request by scheveningensun**
Apparently, doubling your damage with high damage melee weapons causes unexpected results! Who would've thought!

SaltPR because 3 officers got decapitated in 10 seconds by a pathetic 30 damage Vaurca weapon (literally worse than most material weapons in-game) due to the fact a hulk effortlessly cut into the air in their general direction. Imagine if that was an amohdan sword (which does rarely appear in some loot on away sites) or a steel rapier (even more common, see: merchants). Yeah, probably shouldn't let this one go unaddressed so people don't have to imagine that.

Damage breakpoints are wack and this code is esoteric

### CODE REVIEW

**Comment by scheveningensun** [comment]
!review

**Comment by Jasorn** [comment]
I think you need to consider that the reason people got de-capped was because the vamp hulk was able to wield an overpowered sword, one that a warden decided he could rush him with and failed? I'm against nerfing everything based on one instance of a strong weapon?

**Comment by scheveningensun** [comment]
> I think you need to consider that the reason people got de-capped was because the vamp hulk was able to wield an overpowered sword, one that a warden decided he could rush him with and failed? I'm against nerfing everything based on one instance of a strong weapon?

it was 30 damage. craftable swords outdamage it

**Comment by Syncrosync** [comment]
I disagree with saltPRs for sec losing a fight. If they were dumb enough to rush the hulking beast with a melee weapon, then get killed with said weapon, thats on them. A hulk is a HULK. It is meant for close range beatdowns. 

Craftable weapons damage is based on the material they are made with, so it makes sense that they can be stronger.

**Comment by NobleRow** [comment]
Keep in mind the Greatsword was also doing cleave damage, so it could hit multiple people at the same time. It's Sec's fault in this instance to introduce the weapon to the engagement at all. They did more damage hitting eachother with the weapon than they did to the Hulk. What was the biggest issue is that the Warden showed up with the sword and not anything else he could've brought from the armory.

**Comment by Arrow768** [comment]
Closed.
Getting into CQC with a hulk is a case of play stupid games, win stupid prices.

**Pull request closed without merging**
