### PR TITLE
Removes spy vs. spy as a playable gamemode.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
I used to once believe that this would be a good gamemode.

It isn't.

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Comment by Chada-1** [comment]
Just wondering now if Revolution should be renamed to Spy vs Spy if this gamemode is being removed 👀 Afew people have likened it to spy vs spy (The source material)

**Comment by NonQueueingMatt** [comment]
> 
> 
> Just wondering now if Revolution should be renamed to Spy vs Spy if this gamemode is being removed 👀 Afew people have likened it to spy vs spy (The source material)

No, would be confusing

**Comment by Cnaym** [comment]
Being a paranoid person with a gun is only fun for so long. You can do most of it as normal crew, without beging for attention from the ISD for half an hour. I think it worked not very well with most characters personalities and more often than not gave an officer a reason to play super aggressive and lethal towards antags.

**Pull request merged**
