### PR TITLE
Adds an Intermediate Research Understudy Role - Revival

### PR DESCRIPTION
**Pull request by 1Sparky1**
A revival of #17209. 

Adds a new role, Research Understudy, intended to be the learner role for science, while retaining Lab Assistant as a purely roleplay focused job. 

Understudies have a higher age requirement of 28 due to them being expected to be able to transition to the non-learner roles, while Lab Assistants remain with the lower age of 18, as they are just a pair of safe hands to help science out. 

Also added alt-titles to help differentiate between the various fields of science.

### CODE REVIEW

**Comment by Eyeveri** [comment]
I don't think this is needed. Lab Assistant is, and always has been the learner role.

**Comment by FluffyGhoster** [comment]
I agree with Read

Make a feedback thread on this

**Comment by 1Sparky1** [comment]
Feedback thread, as requested: https://forums.aurorastation.org/topic/20291-split-lab-assistant-into-two-roles/

**Review by Geevies — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
Sorry for the long delay, but we've decided not to implement this.

1. This sets a precedent I don't particularly like for "permanent intern slots", which I don't want.
2. We really doubt this would be a role that's used often.

**Pull request closed without merging**
