### PR TITLE
Konyang: Einstein Engines Corporate Shuttle

### PR DESCRIPTION
**Pull request by RustingWithYou**
Adds an Einstein Engines corporate shuttle which can spawn in the Haneunim sector. This shuttle has three ghostroles - a pilot and two passengers. 

Map image attached as mapdiffbot is currently experiencing Issues.
image

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Review by Alberyk — APPROVED** [review]

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
image
too wide, needs to fit within the red rectangle - see maps/helpers/guidelines_shuttles.dmm

**Comment by DreamySkrell** [comment]
image
Also avoid diagonal walls like that, they look really bad and do not fit the perspective in game - add walls in the red squares

**Comment by DreamySkrell** [comment]
Also. What is the goal/purpose of this shuttle? Just to visit Point Verdant, nothing else beyond that? They don't really have the gear to do anything else like exploring away sites, and I don't think Horizon crew would really allow EE to dock and visit Horizon.

It's marked to spawn only in the Konyang sector yes, but if they're only there to visit PV, why not just add more EE ghost roles on Point Verdant? I mean I guess some overmap traffic is nice though.

**Comment by DreamySkrell** [comment]
Looking at the actual map:
- add cryopods so they can cryo and leave the round
- give them some funds in the wooden cabinets in passenger rooms, credits and valuables, so they can spend them on konyang to buy stuff (alternatively put those in the outfits so they spawn with them)
- they have the weakest portable generator that runs on graphite, but in the crate there's tritium
- maybe consider hiding/deleting the empty sector after the shuttle jumps out of it

**Comment by RustingWithYou** [comment]
> Also. What is the goal/purpose of this shuttle? Just to visit Point Verdant, nothing else beyond that? They don't really have the gear to do anything else like exploring away sites, and I don't think Horizon crew would really allow EE to dock and visit Horizon.
> 
> It's marked to spawn only in the Konyang sector yes, but if they're only there to visit PV, why not just add more EE ghost roles on Point Verdant? I mean I guess some overmap traffic is nice though.

For this I'd encourage talking to Lancer about it as it was made at his request for Konyang.

The changes for size and other recommended ones have been made

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
image
^ The shuttle landmark was moved one tile to east for some reason

image
It should be placed like it was before like here

**Review by DreamySkrell — APPROVED** [review]

**Pull request merged**
