### PR TITLE
Adds more emergency equipment to survival boxes

### PR DESCRIPTION
**Pull request by Jaraci**
Adds an oxygen candle, a roll of gauze, and an inaprovaline autoinjector to the emergency box. The box now has more carrying capacity in order to hold these extra items; to offset this, I am exhaustively limiting the items that can be put inside it so it doesn't get used as bonus free storage space.

### CODE REVIEW

**Comment by Jaraci** [comment]
!review

**Review by Arrow768 — APPROVED** [review]

**Review by fernerr — COMMENTED** [review]
I question how necessary these additions are. Locating and applying medical supplies is part of the struggle when something goes wrong. Supplies exists at numerous locations on station as well with the whole medical department on board.

**Comment by sheeplets** [comment]
Mirroring Ferner's concerns, I feel like the inaprovaline autoinjector would be a worthwhile enough addition by itself without needing to modify anything else. Oxygen candles are plentiful enough as it is and giving every crewman a roll of gauze to patch themselves up with has the potential to step on medical's toes in a big way. The autoinjector however seems massively helpful both from the lens of a regular crewman and a medical player.

From the _code_  perspective I can definitely see room for abuse by medical, specifically, given that with the way you have things written out it seems to give you the ability to stuff your survival box with any kind of stackable (gauze/ointment/ATKs/ABKs) or the pharmacy's custom autoinjectors/autoinhalers. We already do it with first aid kits, frankly, but those are finite on the map so it balances things out a bit.

**Comment by WickedCybs** [comment]
I wholeheartedly support this PR. I wouldn't really say even basic medical supplies like gauze are easily obtainable and at any first aid cabinet you only receive the bare minimum of medical supplies even still, sometimes only one roll of gauze and ointment depending on where you are.

It sort of heavily depends on which role you play too, a visitor has less chances to even get bandages unless they accessed one of the sole first aid cabinets available to them at the emergency dock (this is also looted by other departments). They aren't limitless either, one stack of gauze/ointment only has five charges. 

This all side, five units of inaprovaline really isn't much, at best it'll slow a persons decay and temporarily stabilize for maybe twenty, thirty seconds. The gauze will help for bleeding but this isn't an advanced FAK, anyone using it will still get infected and medical will still have wounds to treat assuming they have more than minor damage. I think its very fitting that the SCC would give people at least some gauze on hand due to the nature of the station.

So yeah, I've never been out of a job as a medical player just because someone managed to bandage themselves. Anyone hurt enough to need medical is still going to need it, absolutely.

**Review by TheDanseMacabre — APPROVED** [review]
Seems solid to me. I always felt that for a "survival box" the thing's been pretty lacking.

**Pull request merged**
