### PR TITLE
Adds Sol Common as an Option for Skrell

### PR DESCRIPTION
**Pull request by RyverStyx**
See title. Matthew Atlas Approved.

(UNTIL IT CAN BE ENFORCED BY CODE: The Skrell lore team will make sure that no non-Sol originated Skrell take Sol as an option)

### CODE REVIEW

**Comment by RyverStyx** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]

**Review by SleepyGemmy — DISMISSED** [review]

**Comment by ScheveningenZonn** [comment]
while this may be a lore decision I think this should have a community feedback thread for both feature and lore reasons. this is a substantial decision of precedent being made here.

**Comment by Arrow768** [comment]
The current ruling (from october 2019, and re-iterated quite a few times by then) is as follows:
```
[...]
Sol Common / Species Languages:
Each Species has a language for their own exclusive use.
For humans that language is Sol Common
Physically being unable to speak said language is currently the standard reason why other species can not use certain languages so I would keep with that theme.
For inter-species communications TCB is the standard language.
Should there be a especially close ties between two specific species then a intermediary language can be added. (For example between skrell and diona)
[...]
```
In addition skrell getting Sol Common has been discussed 3 or 4 times by now and always been rejected.
It will be discussed again, but unless there is a major overhaul (planned) in how we handle languages the specifics of "each species must have a unique language" will still be maintained.

**Comment by RyverStyx** [comment]
> The current ruling (from october 2019, and re-iterated quite a few times until now) is as follows:
> 
> ```
> [...]
> Sol Common / Species Languages:
> Each Species has a language for their own exclusive use.
> For humans that language is Sol Common
> Physically being unable to speak said language is currently the standard reason why other species can not use certain languages so I would keep with that theme.
> For inter-species communications TCB is the standard language.
> Should there be a especially close ties between two specific species then a intermediary language can be added. (For example between skrell and diona)
> [...]
> ```
> 
> In addition skrell getting Sol Common has been discussed 3 or 4 times by now and always been rejected. It will be discussed again, but unless there is a major overhaul (planned) in how we handle languages the specifics of "each species must have a unique language" will still be maintained.

Elyran Standard.

Skrell have no unique language. Vaurca and Diona speak Nral'Malic.

**Comment by Generalcamo** [comment]
I believe IPCs can already speak Sol Common. I think this may already be a moot case, as it's already not unique to humans.

**Comment by SleepyGemmy** [comment]
> I believe IPCs can already speak Sol Common. [...]

IPCs are created by humans.

**Review by Arrow768 — APPROVED** [review]
This will be merged and its usage evaluated.
-> It might get reverted down the line

**Pull request merged**
