### PR TITLE
Adds trocanolol, a beta blocker

### PR DESCRIPTION
**Pull request by nauticall**
What it says on the tin. Trocanolol (abbreviated to "trocan") is a **beta blocker** - it **slows heart rate down** to counter the effects of a fast pulse. If combined with inaprovaline, it can entirely prevent someone from going into cardiac arrest from pain shock without the need of painkillers. On its own, it creates bradycardia, dropping heart rate by about 20-30 bpm. Overdose leads to severe bradycardia.

Trocanolol also functions as a purge medicine for adrenaline - it specifically counteracts its effects and attempts to remove adrenaline from the bloodstream. While this isn't strictly accurate to IRL mechanisms of action, it mimics it well enough.

It also can be used as an RP medicine (cus we HRP in here fellas) to be given as a prescription for cardiac issues, et cetera.

To prevent it from becoming _too_ redundant or destructive, this PR also lowers the pulse-slowing property of pneumalin. Without it, administering trocanolol and pneumalin was life-threatening, so this was done to prevent that from being so easily achieved.

Ingredients are 1:1:1 **inaprovaline, lithium, hydrazine**.

### CODE REVIEW

**Comment by nauticall** [comment]
!review

**Comment by NonQueueingMatt** [comment]
Not really sure if I'm a fan of a chem that just removes the only side effect of people being irresponsible with stuns.

**Comment by OolongCow** [comment]
> Not really sure if I'm a fan of a chem that just removes the only side effect of people being irresponsible with stuns.

Don't painkillers already effectively do this due to the raised heart rate being caused by HalLoss?

**Comment by NonQueueingMatt** [comment]
> > Not really sure if I'm a fan of a chem that just removes the only side effect of people being irresponsible with stuns.
> 
> Don't painkillers already effectively do this due to the raised heart rate being caused by HalLoss?

No

**Comment by OolongCow** [comment]
> No

Weird. I was always under the impression that raised heart rate was due to the pain, not a direct adding of a condition. I see your point, then.

**Pull request closed without merging**
