### PR TITLE
Tajaran Cloaks as Poncho-like Accessories

### PR DESCRIPTION
**Pull request by WickedCybs**
This makes two of the Tajaran cloak variants (commoner and royal) not just wearable in the suit slot, but also attachable to other clothing items just like the dominian capes/cloaks and poncho items available in the loadout. The gruff cloak didn't get the same treatment as it is more all-encompassing, reaching down to the feet and has a special hood which couldn't be used were it a poncho-like accessory.

Additionally, the commoner cloak's name was changed to "common cloak" and the "royal cloak" was changed to "fancy cloak" (that is how they were referred to in the code anyway) to be consistent and not imply it was only locked to the NKA or something. 

The fancy cloak had its collar raised slightly to be consistent with the common cloak.

Example on voidsuits
image

Example worn on the suit slot as usual
image

Example of the difference between the old royal cloak and the fancy cloak now with the raising of the collar.
image

The cloaks lose their storage as a consequence of course, but that's more than fine I'd think considering they don't exactly look like something you could put anything into and other cloak-esque objects don't store things either.

### CODE REVIEW

**Comment by WickedCybs** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]
I feel like the extra coat selection is a little redundant.

**Comment by WickedCybs** [comment]
Has been an interesting learning experience so will see what can be done about that aspect.

**Review by Alberyk — APPROVED** [review]

**Comment by WickedCybs** [comment]
Will be keeping the new cloak selection as they are no longer suit-type items.

**Pull request merged**
