### PR TITLE
Added new Unathi clothing

### PR DESCRIPTION
**Pull request by smallgreenant**
Added requested Unathi clothing options and added them to Xeno loadout.

### CODE REVIEW

**Comment by VTCobaltblood** [comment]
What is the point of this PR if it doesn't actually add clothing, only sprites?

**Comment by smallgreenant** [comment]
I don't know how this all works. I made the sprites based on the request of someone else, then did the push on the request of someone else. Any direction would be appreciated.

**Comment by skull132** [comment]
Sprites alone are generally not accepted. Neither is code that's inactive (never used anywhere).

Depending on who you are working with for these clothing items, they might have assumed that you're also going to code them.

**Comment by fernerr** [comment]
I'll be helping them with the code.

**Comment by AmoryBlaine** [comment]
Why does this remove and change the eridani and swat sprites?

**Comment by fernerr** [comment]
Just an oversight that'll be fixed.

**Comment by smallgreenant** [comment]
!review

**Comment by alsoandanswer** [comment]
> I don't really think that clothing names should be capitalized. Breaks former conventions. For example, "tzirzi robe" is not capitalized, so why is "Zo'zo Top"?

yeah, names are automatically capitalized

**Comment by smallgreenant** [comment]
I believe I have corrected the capitalization issue. Please let me know if I overlooked anything or if there are additional changes required. Thanks all for your patience and assistance with my first PR.

**Pull request closed without merging**
