### PR TITLE
Replaces the Detective Revolver with a Detective Blaster

### PR DESCRIPTION
**Pull request by Geevies**
Pretty much what it says on the tin. I've put the changes through some good balance tests, and they seem to be working pretty fine. I suppose this is a very soft nerf, since it reduces the total amount of ammo a detective can have around from 18 bullets that do 25 brute each, to 8 energy shots that do 20 burn each. This is offset by being to recharge pretty much anywhere for free, and being able to shoot through windows.

All-in-all, I believe a detective shouldn't take part in sustained combat, and having enough firepower to put a rowdy suspect they were meant to interrogate into crit is a good thing, in my opinion. When I played Detective, I accidentally killed way more people than actually just 'stopping' them.

And I mean, come on, it's a blaster! That's cool as shit. Also, sprites by Kyres, who's also cool as shit!

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by KingOfThePing** [comment]
How am I supposed to meme antags with lethals on green now?

**Comment by Sindorman** [comment]
Add recharger to the detective's office?

**Comment by Geevies** [comment]
> 
> 
> Add recharger to the detective's office?
Can do, definitely. Good idea. Gimme a sec.

**Comment by Geevies** [comment]
Added wall charger. Red body and broken door not included.

image

**Comment by Sindorman** [comment]
Thanks

**Comment by skull132** [comment]
Denied, blasters go through windows and giving that to sec is not on the agenda at the moment.

**Pull request closed without merging**
