### PR TITLE
Open & Close Shutters From Within the Engineering Hard Storage

### PR DESCRIPTION
**Pull request by WickedCybs**
Adds a cool button.

image

### CODE REVIEW

**Comment by WickedCybs** [comment]
!review

**Review by SleepyGemmy — APPROVED** [review]
mapping looks good.

**Review by KingOfThePing — APPROVED** [review]

**Comment by WickedCybs** [comment]
!bugfix

**Comment by WickedCybs** [comment]
Might be an oversight or something so I made it a bugfix

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
