### PR TITLE
Mech Equipment Stuff

### PR DESCRIPTION
**Pull request by Geevies**
* Added a mounted ballistic automatic rifle to the mecha fabricator.
* Rebalanced the material costs of most of the mech fab equipment. Overall, steel costs will be a bit cheaper, and more glass will be used.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by Eyeveri** [comment]
I'm not sure giving the station the ability to equip a mech with a 556 rifle is a great idea right now. I don't mind seeing this added in for jockeys, or other areas - but I do not think it should be able to be made ship side. I'd atleast like to see it locked behind an illegal tech wall.

**Comment by FluffyGhoster** [comment]
I agree with read on locking it behind research, it certainly shouldn't be easily obtainable

**Comment by DreamySkrell** [comment]
agreed with read and fluffy

**Review by Arrow768 — APPROVED** [review]

**Pull request closed without merging**
