### PR TITLE
Remapping parts of the research department.

### PR DESCRIPTION
**Pull request by fernerr**
After I, and several others have felt that the current R&D lab layout is too claustrophobic, I’ve remapped it to be bigger, allowing for more breathing room and table space.
(Old): ~~https://i.imgur.com/gNO8hD0.png~~

**Edit:** New version with some added windows and various things, based on the feedback from VTCobalt and Gem. https://i.imgur.com/4G0XNcb.png

 I’ve also added some desired features, such as a recharger to the misc. Lab, an emergency shower to the chemistry lab and added back some scientist closets and a suit storage unit which were removed at some point in time.
https://i.imgur.com/QIxWtKg.png

This was made possible by moving the Xenoflora lab to the sublevel for now. While remapping Xenoflora for the new location I added in some quality of life features that hydroponics had already been privy to, like water backpacks and an empty chemistry dispenser along with cartridges.
The new Xenoflora features a specific room to grow hazardous plants which is located behind a cycleable airlock.

The Xenoarch airlock had to be moved to make room for Xenoflora, so while I was at it I remapped the Xenoarch department in its entirety, making the space feel less disconnected by the hallway that dominated it before. Also added some additional steel as well as two stacks of metal rods to make archeological excursions less of a hassle.

The Test range was rotated to inflict less damage to the toxins lab in the future.
Edit: Removed recharger from test range, added two wall variants.

The new parts of the research sublevel: https://i.imgur.com/biYMwLe.png

P.s. This is my first time mapping and the first time making a PR, so please be patient.

### CODE REVIEW

**Comment by VTCobaltblood** [comment]
Looks absolutely fantastic so far, but requires a feedback thread nonetheless.

**Comment by fernerr** [comment]
Feedback thread: https://forums.aurorastation.org/topic/11400-partial-research-remapping/

**Comment by fernerr** [comment]
!wip

**Comment by LordFowl** [comment]
DNM until mapping unit tests are satisfied.

**Comment by fernerr** [comment]
!review

**Pull request merged**
