### PR TITLE
Racer Station Away Site

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
Credits to Sleepy Wolf for the map. It is a derelict racer hangout - I couldn't figure out how to get the shuttles to work, but if I do I intend to revisit this and make an inhabited version.

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!wip

**Comment by TheDanseMacabre** [comment]
!review

**Review by Arrow768 — APPROVED** [review]

**Review by Arrow768 — DISMISSED** [review]
Wrong map format

**Review by Alberyk — APPROVED** [review]

**Review by JohnWildkins — CHANGES_REQUESTED** [review]
Runtimes quite a bit before loading in. Most of the problems aren't strictly related to your mapping, but they do nevertheless happen when loading the away site:
- Burnt walls (`code/game/objects/effects/burnt_wall.dm`) fail to init properly because they're passed a string (MATERIAL_STEEL) rather than a `/material`.
- You put multiple `obj/effect/plastic_explosive` on the docked shuttle, but that runtimes since it needs a `target` to init properly. If you wanted planted C4 you need to edit their init to fall-back to the turf they're placed on, otherwise you need to change them out for `/obj/item/plastique`
- You have an augment implanter's base type placed, which runtimes (because `new_augment` isn't defined)
- You're using `/obj/effect/mazegen/module_loot/trash` for random trash off the east side, but that doesn't work outside of maze generation, and all it does is generate `obj/random/junk` anyway. Just replace them with that.

**Review by JohnWildkins — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
