### PR TITLE
Light Code and Sprite Tweaks

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR cleans up the light code and tweaks the sprites.

## summary
- cleans up lights' and light fixtures' code.
- makes active light tubes and bulbs layer above darkness, so it looks like they're emitting light.
- tweaks the lights' sprites.
- tweaks the light fixtures' sprites.
- renames the light tubes and light bulbs to LED, to make it clearer that they are LED.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Review by alsoandanswer — DISMISSED** [review]
These sprites are a downgrade, if I'm being honest.

Also, the emagged icon state is used for emagging the light replacer. Put it back.

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
Why are you removing the emag feature? Also, this change still isn't documented in the changelog.

**Comment by NonQueueingMatt** [comment]
I guess the emag stuff is pointless. I've never seen people use it.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request closed without merging**
