### PR TITLE
Maint. drone welding tool capacity increase

### PR DESCRIPTION
**Pull request by HetNeSS**
/obj/item/weapon/weldingtool changed to /obj/item/weapon/weldingtool/largetank. Power capacity mostly isn't an issue for a maint drone, but they are constantly forced to look for a welding tank or charging point when performing any type of construction. Especially if it includes welding glass shards to glass sheets

### CODE REVIEW

**Comment by Lohikar** [comment]
I don't really think that maintenance drones need _buffs_. They're not really supposed to be constructing things, just performing basic maintenance/repairs.

**Comment by printer16** [comment]
Good from a code standpoint.

**Comment by skull132** [comment]
What Lohikar and Pacman said. Synthetic powercreep is getting too real :l

**Comment by HetNeSS** [comment]
https://en.wikipedia.org/wiki/Luddite

**Comment by Lohikar** [comment]
The reasoning is balance - maintenance drones are a simple ghost role that is not supposed to be the end-all for repair work. Closing.

**Comment by HetNeSS** [comment]
It does nothing critical, just doubles the welding value of maint drones from 20 to 40, not even borgs, drones. To add some more sustainability. To let them do some things that they have to do at their own, as far as they cannot interact with any biological beings or synthetic systems. I don't understand why there is so much hype about such little thing

**Comment by HetNeSS** [comment]
So that point that they're ghost role do means that they don't have any right to be a part of a round?

**Comment by Lohikar** [comment]
Maintenance drones are _already_ a bit over powered, there is no reason to buff them even further, no matter how minor the buff is.

**Pull request closed without merging**
