### PR TITLE
Ai trader box removal V2

### PR DESCRIPTION
**Pull request by Nerrathiel**
Second attempt at removing boxes from merchants - due to wrong checksum for travis had to revert everything and try again. Hope I didn't fuck up again. All the feedback from previous PR should be accounted for.

### CODE REVIEW

**Comment by Nerrathiel** [comment]
Ok. Travis works fine this time.

**Comment by Nerrathiel** [comment]
!review

**Comment by Bygonehero** [comment]
Why remove wizard merchant?

**Comment by skull132** [comment]
What's the reasoning for this, real quick?

**Comment by Nerrathiel** [comment]
Boxes in game are currently an issue - they sell for 42-ish credits from traders, because the sell price doesn't include items inside of them - as such buying a box for 42 creds may end up with you buying things 20 000 creds if you're super lucky They straight up break the economy.

Furthermore, this PR doesn't remove the wizard, that's the previous PR I made, I'm just merging from the same branch I did the previous changes on, and I genuinely have no idea how to delete old commit logs. If you check current aurora page's unique traders, [ found here: https://github.com/Aurorastation/Aurora.3/blob/master/code/datums/trading/unique.dm ] you will fiind that the wiz trader has arleady been deleted. 

The pr in question is: https://github.com/Aurorastation/Aurora.3/pull/6791

**Pull request merged**
