### PR TITLE
Two New Away Sites + Extra Tiles and Other Stuff 

### PR DESCRIPTION
**Pull request by WickedCybs**
Ports the casino ship and space yacht from Baystation and gives them some tweaks specific to Aurora. To facilitate those maps and similar ones, it also comes with a port of additional carpets from bay, different coloured wood flooring (those can only be mapped in atm) and the addition of fuel ports loaded with hydrogen tanks and hydrogen tanks with extra capacity meant for shuttles.

These are also going to have multiple areas mapped in and will respect power + atmos requirements, which will be a first for overmap stuff. That will probably have some challenges that will delay the pr a bit, since I've been running into issues with APCs working without a nudge from a player, as an example.

### CODE REVIEW

**Comment by WickedCybs** [comment]
I've not been able to get the actual site to spawn for further testing, so I will probably need help with that.

**Comment by WickedCybs** [comment]
!wip

**Comment by WickedCybs** [comment]
image

image

I heard icon diffs don't work, so here is some examples of the new tiles.

**Comment by WickedCybs** [comment]
APCs start on, but don't seem to be powering their area until I spawn in as a bluespace technician and interact with them.

2022AugustFriday12060921

**Comment by WickedCybs** [comment]
I would also like to figure out how to make it so the profile of a ship isn't pitch black where it meets space.

image

**Comment by WickedCybs** [comment]
Aside from the major issue of the APCs behaving oddly, the PR is almost ready to go so I'm basically just hoping for a solution on that.

**Comment by WickedCybs** [comment]
Can merge soon after https://github.com/Aurorastation/Aurora.3/pull/14693 is in.

**Comment by WickedCybs** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
