### PR TITLE
Ports the fusion reactor from Baystation12, replacing the Tesla.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
It has been renamed to the INDRA.

To-do:

- [x] TGUIfy the UIs
- [x] Mapping
- [x] Flavour adjustments (names, description, sprite)
- [x] Code adjustments (add a little bit of Aurora-unique flavour)
- [ ] Wiki guide

### CODE REVIEW

**Comment by MortalRed** [comment]
Gonna be perfectly honest, as another "put gas in and shoot laser" engine it would've been a much more compelling replacement for the supermatter.

**Comment by NonQueueingMatt** [comment]
> Gonna be perfectly honest, as another "put gas in and shoot laser" engine it would've been a much more compelling replacement for the supermatter.

The tesla is a barely functioning laggy mess that regularly lags the server to shit, its replacement is non-negotiable. That aside, the fusion reactor isn't exactly "put gas in and shoot laser", since actual fusion reactions with solids are required + there's a lot more conceptual space for integrating it with the SM

**Comment by MortalRed** [comment]
Alright, if we're keeping the SM then we'll definitely have to reign in the power even the basic setup generates, because as it stands, it generates way too much power to be interesting.

**Comment by NonQueueingMatt** [comment]
!review

**Review by DreamySkrell — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
