### PR TITLE
Cult Stun/Incapacitation Adjustments

### PR DESCRIPTION
**Pull request by Geevies**
* Adjusted stun/incapacitation runes to be blockable by flash-resistant eyewear. Talismans are blocked by sunglasses, while larger runes are only blocked by welding goggles or voidsuits.
* Stun/Incapacitation runes now flash borgs as well, and the stuns last for longer, especially for the non-talisman variant.

\-

I'm not 100% sure about this one, but I felt that deploying an uncounterable stun that can be repeated as soon as the target stands up was a bit much, but I still understand that the cult needs some sort of way to stun and forcefully recruit people.

So, with this change, crew that are prepared and combat ready (sunglasses / goggles / voidsuits) can combat the cult without being stunned immediately, while people going about their business on the station can still be nabbed and recruited.

The runes being more effective than the talismans also encourages a slightly more defensive playstyle, with the cult building up a base of operations.

\-

The first iteration I tried gave the receiver temporary immunity to the talisman's stun for a few seconds, while also increasing the stun length, but communicating the immunity wasn't very clear and felt bad on both sides, so I went with this one instead.

### CODE REVIEW

**Comment by Geevies** [comment]
not a salt PR because i made this days after i got killed by it you cannot post this to the discord and laugh at me

**Comment by Geevies** [comment]
!review

**Comment by DreamySkrell** [comment]
> Adjusted stun/incapacitation runes to be blockable by flash-resistant eyewear. Talismans are blocked by sunglasses, while larger runes are only blocked by welding goggles or voidsuits.

I disagree with this kind of nerf, it just does not make sense like, logically. Sunglasses should not block magic.

**Comment by NonQueueingMatt** [comment]
Don't agree in principle with nerfing one of the few strong cult tools.

**Review by FluffyGhoster — APPROVED** [review]
Code is fine, I don't agree with the nerf too

**Comment by NonQueueingMatt** [comment]
We've decided that this makes playing cult unnecessarily difficult and annoying, so it is not wanted.

**Pull request closed without merging**
