### PR TITLE
Adds another Qipao

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
My friends love CHINA so much they wanted me to do another. Holy cow.

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Review by WickedCybs — APPROVED** [review]
+1 social credit

**Comment by listerla** [comment]
Isn't this pretty much identical to the cheongsams already found in dress selection? Shouldn't these be rolled together instead of having them in different places?

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
These qipaos should be under the dress selection.

**Comment by TheDanseMacabre** [comment]
The qipaos are color-selectable, and therefore cannot be included in the dress selection.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
