### PR TITLE
Operations stairs-lift swap

### PR DESCRIPTION
**Pull request by DreamySkrell**
image
image
image
image

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!review

**Comment by FluffyGhoster** [comment]
But why?

**Comment by DreamySkrell** [comment]
> But why?

Currently the top deck ops office is like, literally never used, and I imagine it is because it is connected only by the lift to the main ops areas. And people always just use the stairs, cause they are so much closer and more convenient to the entrance to ops, so a lot of people probably don't even know that the top deck ops office exists.

Swapping the stairs and the lift does not really inconvenience anyone. To the contrary, it makes it slightly faster for miners to get between ops office and mining bay. And if were to want to go with restricting miners from having free access to the warehouse, this remap would enable and allow it.

**Review by FluffyGhoster — APPROVED** [review]
Sounds good to me

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
