### PR TITLE
paroxetine actually follows the recipe in the wiki now

### LINKED ISSUE #9289: Two paroxetine recipes
There are currently 2 recipes for making paroxetine, with the mindbreaker/copper/ammonia version overwriting the version listed on the wiki (mindbreaker/norepinenphrine/acetone).  I'm not too sure if this constitutes an issue, though I brought it up as it may inconvenience folk who rely on the wiki for chemical recipes as the wiki recipe for paroxetine has been overwritten by this one.

First recipe

Second recipe

### PR DESCRIPTION
**Pull request by alsoandanswer**
title

fixes #9289

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!bugfix

**Comment by alsoandanswer** [comment]
!review

**Comment by alsoandanswer** [comment]
> 
> 
> Was there a duplicate?

Yes

**Comment by Geevies** [comment]
some chemist mains requested that this one remains and that the one with acetone was removed, since a LOT of chem recipes use acetone

**Pull request merged**
