### PR TITLE
Get your hands deep into that assistant. Stop that bleeding!

### PR DESCRIPTION
**Pull request by SonicGotNuked**
I'm hoping to make surgery a viable option and not make an entire role secondary because of space magic meds. While there are still some sins, these are the worst of the sinners.

- [x] Bicardine no longer heals internal bleeding. I'm not giving it a brute based overdose due to the previous issues that occurred when it did give overdose brute.
 
- [x] Peridaxon weakens pain messages while your organs painfully heal themselves.

- [ ] Alkysine will cause confusion and hallucinations. Overdose with a chance of giving some memory loss? (debatable)

There is also a few things I can do.

1. Peridaxon locked behind phoron salts.
2. New reagent for lung damage.
3. Temperature for medications? If you don't have it at a certain temp, it would not work or perhaps cause issues?

These are things that could be added to a later PR.

### CODE REVIEW

**Comment by SonicGotNuked** [comment]
!wip

**Comment by resilynn** [comment]
Bicaridine should still cure IB.  The rest is great, but all you'd be doing here is encouraging people to keep eating meat pies so they don't die to death.

Come up with another reason to give incentive to surgery.  Infection, por ejemplo.

**Comment by resilynn** [comment]
Additional comment- another dev pitched having a temp cure to stave off IB but not cure it.  That isn't food.

I'd be down with that.

**Comment by alsoandanswer** [comment]
Feedback thread, please.

**Comment by SonicGotNuked** [comment]
https://forums.aurorastation.org/topic/12970-bicardine-peridaxon-and-alkysine-nerfs/?tab=comments#comment-123210

**Comment by Geevies** [comment]
@SonicGotNuked May I suggest, instead just cutting the effectiveness of all chemicals in half?

**Pull request closed without merging**
