### PR TITLE
Engineering lobby expansion

### PR DESCRIPTION
**Pull request by FabianK3**
### Introduction
This PR has the goal to revamp the engineering lobby. In this PR the lobby itself and the areas adjacent to it have been modified, the adjacent areas as necessary.

### Why?
The current engineering lobby is very small. With four to five engineers, the lobby can already be considered full. It becomes especially cluttered when every table is stacked to the ceiling with different stuff and one or two crates are lying around. Generally - The lobby feels too small and is just a simple cube. Engineering lobbies should be a bit wider open as they feature the cut between clean hallways, monitoring and paperwork, and the oily heavy-duty equipment next door.

### What changed?
- The engineering lobby has been merged with the starboard hallway adjacent to it to provide more space.
_Desks, notice board, consoles and equipment area next to it, feels like engineering._
- The engineering lobby now has a notice board.
_No more wiring sheets lying around_.
- The public hallway next to the main elevator received a table with paper for engineering's guests.
_I broke a window, sorry guys!_
- The hallway between the lobby and the medical ICU has been made smaller to accommodate the new layout.
_For the lazy doctors coming from residential and security waiting to get in._
- The first aid locker next to the SM-airlock has been moved closer to the lobby to provide more visibility to it.
_No more bleeding out, remember that locker._
- Fixed wrong tile in hard-storage and wrong decal in shield gen room.
_I could not resist them._
- Very minor changes of the lobbies original contents and areas around it for usability, feel and fluff.
_Prototype, test, refine._

### Preview

**Lobby**
image

**Public facing hallway**
image

**Engineering-medical hallway**
image

**StrongDMM overview**
image

### Addendum/Edit
Updating Preview pictures and What-changed to latest commit.

### CODE REVIEW

**Review by courierbravo — CHANGES_REQUESTED** [review]
Its an existing thing from before your PR, but do you think you could move the engineering ringer button onto the desk please? Other than that, this all looks great. I'm slightly hesitant about a bigger engineering lobby given the impact the one we had a few years ago had. But I'd at least like to try your changes.

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
I have two main concerns here:

- I do not particularly like big lobbies - it's the kind of thing we tried to expunge from the Aurora for good reason. People would clump up in these big lobbies, fundamentally out of sight from the public (note how the current lobbies have no blind spots from the hallway immediately outside, whereas your lobby now has one to the left) and thus cutting them off from interaction from the outside. This is a core element of Horizon design philosophy.
- The two tile hallway to the south is really bad for mobility, especially since it's often trafficked, and especially by security for chasing antagonists.

**Comment by FluffyGhoster** [comment]
I'm not convinced making it bigger would be a positive either

**Comment by DreamySkrell** [comment]
Agree with Matt's concerns.

This makes it so the lobby is the department entrance, and non-engineers can't enter the department without going through the lobby. Other departments have entrance and lobby separate.

**Pull request closed without merging**
