### PR TITLE
WIP Meme Update.

### PR DESCRIPTION
**Pull request by Kaedwuff**
This PR is based on this thread https://forums.aurorastation.org/topic/11776-meme-20-the-cognitohazard/ in which you can find all details so far.

To do (in no particular order):
- [ ] Spawn Code and attaching to a player
- [ ] Finish mapping spawn point and assets there
- [ ] Recoding powers and progression
- [ ] Add anti-metagame event
- [ ] Patch in new sprite assets

### CODE REVIEW

**Comment by TehFlaminTaco** [comment]
Can you be a little bit more descriptive? I have no idea what this is for. (Even if it's WIP)

**Comment by SubberTheFabulous** [comment]
If I were to guess, I'd say, it's a Meme gamemode revival.

**Comment by Kaedwuff** [comment]
Description added and checklist.

**Comment by skull132** [comment]
WIP PR > June 2019. Closing.

**Pull request closed without merging**
