### PR TITLE
Drumpf destroys ligma

### PR DESCRIPTION
**Pull request by dragoslava**
The ligma meme is really stupid and needs removed, bad joke

### CODE REVIEW

**Comment by dragoslava** [comment]
the left wing media claims removing ligma is a high risk, we must stop them

(but srsly make this stop)

**Comment by BurgerLUA** [comment]
sorry you must wait a month because of PR revert rules 👍

**Comment by dragoslava** [comment]
I will destroy you >:^(

**Comment by Alberyk** [comment]
While I am fine with the proposal of this pr, I feel that #5736 does the same thing and just fixes some of the name as well.

**Comment by dragoslava** [comment]
Okie dookie.

**Pull request closed without merging**
