### PR TITLE
Fixes sol and coalition voidsuit not accepting oxygen tanks.

### LINKED ISSUE #10254: "Military Voidsuit" suit slot does not accept air tanks.
/obj/item/clothing/suit/space/void/sol is the correct string I think.

Server revision: - 2020-10-13
9d666c4d34ae217e14e7c42cc0380f159f641503
Current Map: NSS Aurora

### PR DESCRIPTION
**Pull request by flpfs**
Fixes #10254

### CODE REVIEW

**Comment by flpfs** [comment]
!review

**Comment by flpfs** [comment]
!bugfix

**Comment by mikomyazaki** [comment]
Can you also do the Valkyrie suit? `/obj/item/clothing/suit/space/void/valkyrie`

**Comment by flpfs** [comment]
Superceded

**Pull request closed without merging**
