### PR TITLE
Borg buffs and tweaks

### PR DESCRIPTION
**Pull request by Pratepresidenten**
Removes flashcheese

Also buffs emagging vs borgs

Nothing Ive tried actually makes the borg blind, so Im still looking into how to fix this.

### CODE REVIEW

**Comment by Pratepresidenten** [comment]
!wip

**Comment by Geevies** [comment]
Instead of disabling the borg, perhaps flashing does three things.
1) The flash overlay, makes it impossible for the player to see where things are.
2) Modules get "dropped", as in, modules are no longer in the hotbar, they're back in the inventory.
3) Intercept clicks, borgs cannot click on things after getting flashed. This prevents them from attacking back, or bolting doors, etc.

**Comment by Pratepresidenten** [comment]
1 and 2 was the plan, dunno how hard 3 would be, but I want theee.. Flash overlay to work first, so chugging along on that!

**Comment by GMR25** [comment]
Wouldn't blinding it require disabling the camera component?

**Comment by Pratepresidenten** [comment]
Axing for now!

**Pull request closed without merging**
