### PR TITLE
Restricts Skrell pronouns to plural

### PR DESCRIPTION
**Pull request by lavillastrangiato**
As desired by WhatsUpBrotendo, this restricts Skrell to only having they/them pronouns. Lore-wise, they can still adopt gender identities to fit in with humanity; this is a mechanical indication of their lack of sexual dimorphism.

### CODE REVIEW

**Comment by lavillastrangiato** [comment]
!review

**Review by FluffyGhoster — APPROVED** [review]

**Review by SleepyGemmy — APPROVED** [review]

**Comment by sadkermit** [comment]
Isn't the entire point of the pronoun option to denote a character's preferred pronouns, as opposed to their sexual characteristics. Pronouns and Sex options are distinct for that reason. 

> Lore-wise, they can still adopt gender identities to fit in with humanity

No one is contesting that skrell can pick their own pronouns.

> this is a mechanical indication of their lack of sexual dimorphism.

The Sex option would be used for this, of which Skrell are already limited to _Plural_, adequately representing their sexual dimorphism, aka sexes. Sexes represented by the Sex selection - that makes a lot of sense.

This decision implies one's gender identity is limited by and linked to their sexual characteristics. Sex doesn't define gender.
The '_They_' pronoun selection can already be used by skrell who do not wish to adopt a human gender identity.
Pronoun selections could just be restricted by Origin if certain skrell groups have not been assimilated enough into human culture to adopt human gender identities.

**Comment by FluffyGhoster** [comment]
>Isn't the entire point of the pronoun option to denote a character's preferred pronouns, as opposed to their sexual characteristics.

To my knowledge, it's a mechanic about how a character would generally be seen physically upon examination; that's why that info is printed by the examine command

**Comment by listerla** [comment]
As the one who commissioned this mechanic, I'd just like to note that the _original intent_ - not necessarily what devs have in mind now, but my intent when I paid for it - was for it to indicate preferred pronouns via some psionic sense rather than appearance. Hence, say, an androgynous man not taking they/them pronouns, or a masculine woman not taking he/him pronouns. However, this intent may have changed with the advent of pronoun pins. Just my two cents.

**Comment by sadkermit** [comment]
> To my knowledge, it's a mechanic about how a character would generally be seen physically upon examination; that's why that info is printed by the examine command

If a Non-Federation skrell chose to, would a skrell not appear masculine or feminine when examined if wearing masculine-tailored or feminine-tailored clothing, sound more masculine or feminine when examined if they opt to take on a more masculine or feminine intonation, behave more masculine or feminine when examined if they opted to take on mannerisms observed from humans? 

Why would none of this be reflected via their selected pronouns and thus their Examine Text? Biological characteristics are not the only characteristics that signal to other people what gender/pronouns you are/use.

**Comment by FluffyGhoster** [comment]
>If a Non-Federation skrell chose to, would a skrell not appear masculine or feminine when examined if wearing masculine-tailored or feminine-tailored clothing alongside their skrell accessories [...] 

No, this mechanic is invariant of what you're wearing or how you sound like or anything of sorts, if a mechanical guy character get out of the workshop car mechanic clothes and wear a two-pieces bikini or a dancing tutù, the text doesn't change to "she", it's invariant of anything else but the essential of the character, aka how it would seem to the average person looking at a picture of it with neutral clothes on and having never heard or seen him around (that's why it is also reported in the records, eg. security/employment ones)

In fact, it is kind of silly that you can magically project to a character what they should think when they see another character, it's something that is considered bad praxis just some lines below in the custom description text, not to mention all the compatibility problems with the various species/factions, a vaurca to my knowledge has little to no concept of even the subject, most Tajara would never think of someone as "they", and so on

**Comment by sadkermit** [comment]
> No, this mechanic is invariant of what you're wearing or how you sound like or anything of sorts

If the Examine text should not be influenced by a character's gender presentation and how they signal their identity, then why does the Examine text not draw from a character's Sex selection, which would be their physical appearance isolated from clothing choice?

>  if a mechanical guy character get out of the workshop car mechanic clothes and wear a two-pieces bikini or a dancing tutù, the text doesn't change to "she"

This doesn't signal a gender identity or someone's pronouns; this signals that they were just having a laugh. We are smart enough to separate a one-off change in attire from the rest of this person's identity. We are also smart enough to associate an androgynous individual who is wearing clothing of, sounding like and behaving as either a male or female as the gender they are choosing to present as. We are capable of holistically approaching another individual's identity.

Pronouns being based on other peoples' perspectives and uninfluenced by a character's attempts to signal a gender identity poses a few issues, especially when abstracted to humans where it becomes more sensitive. Should a transmasculine born-female character who identifies as male who 'doesn't pass'/still has noticable feminine traits select _She/Her_ pronouns to reflect the character's appearance in neutral environments and devoid of their attempts to signal a masculine identity through intonation, clothing choice and mannerisms? The only reason this character would pick _He/Him_ pronouns from the Character Setup menu is to reflect the identity they have picked from themselves; why would a skrell who has picked _He/Him_ pronouns not be able to?

> In fact, it is kind of silly that you can magically project to a character what they should think when they see another character, it's something that is considered bad praxis just some lines below in the custom description text, not to mention all the compatibility problems with the various species/factions, a vaurca to my knowledge has little to no concept of even the subject, most Tajara would never think of someone as "they", and so on

I don't necessarily disagree. Someone's welcome to work on reworking how Examine text sources the pronoun used based on a composite score or something and impacted by the observing species.

**Comment by FluffyGhoster** [comment]
>If the Examine text should not be influenced by a character's gender presentation and how they signal their identity, then why does the Examine text not draw from a character's Sex selection, which would be their physical appearance isolated from clothing choice?

That is what it did initially, when this mechanic was made in SS13 it was pulling from the sex, which also determines the sprite that is used for the mob (at least for humans), as I was saying before it was later shoehorned into being a Deus Ex Machina for other things

But ultimately, you can't determine the sex of someone just by looking at him in underwear, it can also be difficult to do if someone is naked for various medical conditions (hermaphroditism, androgen insensitivity syndrome, various genetic and development alterations that wouldn't make much sense to list here but you can neverthless check in the medical literature if you're interested) and we do not have a mechanical nudity in game, hence the closest we can reasonably get is statistically guessed gender, which is how I interpret this mechanic to represent


>This doesn't signal a gender identity or someone's pronouns; this signals that they were just having a laugh. We are smart enough to separate a one-off change in attire from the rest of this person's identity. We are also smart enough to associate an androgynous individual who is wearing clothing of, sounding like and behaving as either a male or female as the gender they are choosing to present as. We are capable of holistically approaching another individual's identity.

To someone who just sees this character for the first time, or doesn't know the character, or doesn't recognise the character, or doesn't have a concept (eg. vaurcas and per-character basis) et simila, this would indicate completely different things; it's up to the characters to decide how to interpret what they see in-game, one character could see it as someone having a laugh, another character could see it as a fluidity where it changed from one presentation to another, another could look at it and just see a human changing clothes without anything else behind it, and so on

This mechanic does not, and realistically cannot, account for any of that, the most non-deus-ex-machina-yet-still-useful thing we can use it for is to show what the character non-completely-naked body would look like to the average person, it's not a perfect mechanical use by any means, but it's the use that allows the broadest interpretation for other characters while creating the fewest logical/lore/mechanical issues

>Pronouns being based on other peoples' perspectives and uninfluenced by a character's attempts to signal a gender identity poses a few issues, especially when abstracted to humans where it becomes more sensitive. Should a transmasculine born-female character who identifies as male who 'doesn't pass'/still has noticable feminine traits select She/Her pronouns to reflect the character's appearance in neutral environments and devoid of their attempts to signal a masculine identity through intonation, clothing choice and mannerisms? The only reason this character would pick He/Him pronouns from the Character Setup menu is to reflect the identity they have picked from themselves; why would a skrell who has picked He/Him pronouns not be able to?

If it is reasonably seen as female in underwear, yes, it should pick feminine, if it's dubious it should pick neutral, if it "pass" it should pick masculine

As skrells do not have sexual dimorphism and are therefore always dubious when looked at, they should take neutral, which is what this PR is addressing


>Going back to skrell, no one is contesting that skrell who have been assimilated into human culture can adopt a human gender identity. They should be able to signal that gender identity through Pronoun choice even if their physical characteristics alone may not convey a gender identity.

This is not wanted by the lore team (hence why this PR), nor this mechanic should be used as a Deus Ex Machina to that purpose, if you can't reasonably tell a character you don't know looks like X gender, the mechanic shouldn't give that info, preferring an indeterminate "it" or even "they", you can then go into all the details of clothes, voice tone, mannerism and the likes in the description of the character, indicating that eg. this person looks to adopt X mannerisms and social norms for people of this specie/planet/culture/whatever and the likes

It wouldn't make sense for a vaurca, which does not have the concept of gender afaik, to interpret a gender expression, a gender expression would also be different between different planets so that what is associated with one gender in one place might be associated with another gender in a different place so that one character from A could see it as an expression congruent with gender X and another character from B could see it as an expression congruent with gender Y and Z and K

Unathi for example do not have the same concept of genders that humans tend to have, they just associate eg. warrior-male, healer-female, and have at least a standalone gender that is fisher IIRC; they might see for example the NKA queen, that is a general that won many battles (if I understood correctly), as a warrior and hence translate it to a male in human terms


>Someone's welcome to work on reworking how Examine text sources the pronoun used based on a composite score or something and impacted by the observing species.

Such a system would be unnecessarily complex and still would not solve the interpretation issue that is a per-character evaluation, without having much reason to exist in the first place, as the player sees the screen and can decide what the character he is playing thinks of what he sees or hears, and the extended description can be used to convey mannerisms and the likes (which can also be contraddictory or intersectional) in a far more detailed, far more nuanced manner than such a system ever could




And all of this is only considering the nuance from the perspective of gender performativity, and leaving the whole discussion between it and other philosophical views on the topic (eg. gender essentialism and social construction theories) which are also represented in-game by some species lore aside for the sake of the argument, it's an incredibly complex topic which you could probably fill a small book store only with the literature about it

Hopefully I have explained the various thoughts with this mechanic and how to use it; as I do not with to turn GitHub PRs as a philosophical debate area, and as by repo rules, this is the last post not code-related
_Also holy shit I just realized how much of a wall of text I wrote, sorry readers, I wanted to address the points thoroughly, hopefully it didn't went too off-topic_

**Comment by WhatsUpBrotendo** [comment]
Skrell lore writer here.

I'm working under the assumption that pronoun selection is how a character, regardless of mechanical (biological) sex, presents themselves. Since there's no real male/female divide in Skrell as they're all hermaphrodites, it doesn't make sense in having that distinction. There's an argument for clothes and accessories, but I don't see why that should permanently label a Skrell with gendered pronouns.

This is my reasoning for requesting the change. I'm not looking to debate the topic as it can easily derail and leave everyone involved frustrated. This PR does not impact anything regarding gender lore, and if you wish to present your character as identifying a specific way then that can easily be done through pronoun pins, roleplay, and character descriptors.

**Comment by pochetoo** [comment]
> If it is reasonably seen as female in underwear, yes, it should pick feminine, if it's dubious it should pick neutral, if it "pass" it should pick masculine

this is... really fucked. all i'm going to say.

**Comment by sadkermit** [comment]
>  you can then go into all the details of clothes, voice tone, mannerism and the likes in the description of the character, indicating that eg. this person looks to adopt X mannerisms and social norms for people of this specie/planet/culture/whatever and the likes

> if you wish to present your character as identifying a specific way then that can easily be done through pronoun pins, roleplay, and character descriptors.

But all of this would influence what another character sees when examining you. If your character's FT includes _'gendered this, gendered that, gender here, gender there'_, then why not allow the Pronoun they are identifying with?

I don't know, chiefs, I understand what you're both arguing for but I'm not a fan of it. I'm arguing in circles and none of it's about code as Fluffy mentioned, so I'm going to drop it.

**Comment by pochetoo** [comment]
> In fact, it is kind of silly that you can magically project to a character what they should think when they see another character
extending this logic, I will be submitting a PR to remove names without using a special 'introduce' verb first within the week

**Comment by DreamySkrell** [comment]
Putting [maintainer discussion] on this cause this is a divisive topic.

**Comment by DreamySkrell** [comment]
Also.

> I'm working under the assumption that pronoun selection is how a character, regardless of mechanical (biological) sex, presents themselves.

It's not. It's specifically pronouns, and not appearance.

**Comment by FluffyGhoster** [comment]
>It's not. It's specifically pronouns (or gender identity), and not appearance.

This contraddicts the previous (and as far as I am aware, only) ruling on the matter, that was done by Skull (ex-host and head dev) as per https://forums.aurorastation.org/topic/13778-make-it-so-that-when-a-character-is-examined-is-says-they-instead-of-heshe/#comment-131546 and reconfirmed in https://forums.aurorastation.org/topic/14185-a-gender-neutral-option-for-some-species/

While it is possible the decision was (or will be) changed, I have not seen any evidence it was, hence as far as I am aware the currently standing deliberation on the matter (unless you can source a different one I missed) is the above, which I will quote here verbatim with proper emphasis highlighting:

"If a species is meant to be **androgynous upon inspection**, then the code can be altered to reflect this. This is already the case with Diona, and if the Skrell lore dev wishes, can be expanded to Skrell. In species with commonly clear **sexual dimorphism**, such as humans, Unathi, etcetera, gendered pronouns _per mechanics_ would remain, as I do not see a need to expand this to all species if we can already alter it per individual species per necessity."

**Comment by Triogenix** [comment]
Howdy. So, after deliberation, it has been decided by headstaff that this PR will go forward and begin the process of being merged.

Our reasoning behind this is based in the lore that skrell don't consider, or have an equivalent to the human concept of gender when looking at their identity. They view themselves and other skrell as just, skrell. Therefore, we believe it is counterproductive to have them mechanically shown with a gendered label, as that's not how they would view themselves.

Furthermore, they(skrell) only adopt a gendered label to fit in with the rest of the alien societies who do have a concept of gender and who do consider it in their own identities and the identities of others. It means little/nothing to them personally.

I realize this may have been unclear on the wiki, so as part of this PR going forward, the wiki will be updated to better clarify and ensure there's no confusion moving forward.

Lastly, I want to address some of the things that were brought up in the discussion about this PR here on github, and how people might perceive they relate to this decision. I want to stress incredibly hard that **this decision was made by headstaff without consideration for the appearance factor that was brought up. The reasoning given here is the only thing we based this decision off of.**

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
