### PR TITLE
Tramp Freighter: Reloaded

### PR DESCRIPTION
**Pull request by RustingWithYou**
Remaps the tramp freighter to bring it up to current ship standards regarding power, atmospherics, etc.

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Comment by DreamySkrell** [comment]
image

This should be the docking port variant of the airlock markers - see horizon's top deck docks for working examples/

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
see previous comment

**Comment by RustingWithYou** [comment]
> see previous comment

addressed

**Review by DreamySkrell — APPROVED** [review]

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
image
this airlock seems to be missing buttons

**Review by DreamySkrell — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
