### PR TITLE
Kitchen Armor

### PR DESCRIPTION
**Pull request by Geevies**
* Added kitchen armor to the dinnerware vendor, retrievable by inserting coins into it.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by TheDanseMacabre** [comment]
Provided that this is a real PR, this feels way too goofy to add to the game.

**Comment by Arrow768** [comment]
This seems like a really weird addition to the kitchen vendor.
Will be discussed by the maintainers.

**Comment by Arrow768** [comment]
Closed as not wanted after a discussion with the maintainers.

**Pull request closed without merging**
