### PR TITLE
Mapping Fixes

### PR DESCRIPTION
**Pull request by ben10083**
(First one was accidentally based off development)

Removed duplicate Warden's Stamp and fixed camera name of Journalist's Office.

### CODE REVIEW

**Comment by Arrow768** [comment]
Altough the changelog should probs be changed to:
- maptweak: "Removes the duplicate stamp and fixes the name of the camera in the journalists office".

**Comment by ben10083** [comment]
I mean, shouldnt it be in past tense since it 'fixed'

**Comment by Arrow768** [comment]
Probably, but the tags are still wrong.

**Comment by Arrow768** [comment]
_Now travis kicks in. After its merged._

**Comment by ben10083** [comment]
Thanks

**Pull request merged**
