### PR TITLE
[Newmap] Map fixes, TComms Relay and Lift announcements modification.

### PR DESCRIPTION
**Pull request by Juani2400**
- Fixes several map bugs.
- Adds a TComms Relay to the Main Level. Location may not be optimal,
check.
- Modifies the configuration file of the lifts to change the
announcements lifts give when arriving to each floor for it to mention
the main areas located in that floor/department.

image

**Pending:**
- Could not fix the administration or ERT shuttles. Needs priority fixing, specially the ERT one.

### CODE REVIEW

**Comment by Juani2400** [comment]
I was told the relay covers one floor up, and one floor down. Placed it in the Main level so it covers all three levels below the Surface.

**Comment by Juani2400** [comment]
In any case, there are more changes in that level. I'd prefer if this was merged, and then I'd move it back down again, so I don't have to do the changes again. Easier.

**Comment by LordFowl** [comment]
I do not see why that is necessary.

**Comment by Juani2400** [comment]
Basically because I've not figured out how to replace a single file in a PR without reverting it.

I will upload a new PR with the changes as soon as this is merged.

**Comment by LordFowl** [comment]
No. It behooves you as a contributor to this github to have elementary understanding of how github itself works. If you need my assistance learning I'll provide it in a handful of hours - basically telling you to download what I personally use. I am sure that Lohikar could provide you much more exhaustive resources, if you'd prefer that.

**Comment by Juani2400** [comment]
Changes made. Reported disconnected pipes issues were also fixed.

**Comment by LordFowl** [comment]
Lovely. Just one last thing - since we're targeting development now and I no longer have control of the repo, we'll need to abide by submission rules - specifically providing images. Bugfixes don't require an image, but large developments will - in particular I'd like to see about the relay.

**Comment by Juani2400** [comment]
Added the image of the relay, located on the bottom-right corner of the image.

**Comment by LordFowl** [comment]
Not where I imagined it would go, but good nonetheless.

**Comment by Juani2400** [comment]
Thanks to the charity of Lohi, this should be ready to be merged.

**Pull request merged**
