### PR TITLE
Tweaks the tau ceti foreign legion spawn chance

### PR DESCRIPTION
**Pull request by Alberyk**
By request of the lore team, the tau ceti foreign legion has a higher chance to spawn.

Thread: https://forums.aurorastation.org/topic/11379-increase-the-chance-for-the-tau-ceti-legion-to-spawn/

### CODE REVIEW

**Comment by LordFowl** [comment]
I’m not totally sure if this is something the lore team should just _decide_. At this point it’s starting to look like we’re just removing ERT.

**Comment by LordFowl** [comment]
That’s nice.

**Comment by LordFowl** [comment]
Just because it is a lore addition does not justify a permanent and severe shift in gameplay without further consideration. Lore cannot decide to remove changeling because changelings are no longer canon, and I’m not so sure continually undercutting ERT is a splendid idea.

**Comment by Sindorman** [comment]
@LordFowl This is a grounding base for Upsilon update and your PR Fowl! But this discussion is not for github, but for forums. If you think we need to talk about this PR, request a feedback thread.

**Comment by skull132** [comment]
This is not necessarily permanent, Fowl.

**Comment by LordFowl** [comment]
I've seen no indication otherwise.

**Comment by Alberyk** [comment]
Closing this in preference of #6012

**Pull request closed without merging**
