### PR TITLE
Warden Gun Changes

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Overview
The Captain, the Head of Security, and the Warden are equipped with energy pistols that have the potential to kill. Perhaps I'm opinionated garbage, but I do not think the warden should have access to such a pistol. This PR changes it so that the Warden gets a custom disabler taser pistol that acts as a new and improved taser for self-defense and prisoner pacification. It uses assets that are already in the game.

# Another Additon
This was meant to be me going through every gun asset, seeing if it's implemented in the game, but there was only 1 unused noteworthy asset, and it was the colt energy pistol. However, I took the liberty of improving the sound of the gyrojet 20mm pistol because why not.

### CODE REVIEW

**Comment by Pacmandevil** [comment]
the warden can just grab a glock from the armoury, which is arguably a LOT more lethal.


I don't see the issue with them having one.

**Comment by BurgerLUA** [comment]
I just want to give a unique gun to the warden fitting of their position.

**Comment by skull132** [comment]
Is it instastun, by chance? Because instastun is trash, absoloute trash.

**Comment by Alberyk** [comment]
This is just ten extra more haloss points, I would rather have the warden keep their regular energy gun than being given just a little stronger one.

**Comment by OneOneThreeEight** [comment]
same. this is kinda dumb seeing as how wardens generally do not create problems with a 5 shot gun with a rather weak lethal setting anyway.

**Comment by Alberyk** [comment]
Also, other issue with this: the gun's theme. All energy guns in game are pretty much plastic/metal-like, with a futuristic theme, and then, for some reason, the warden has one that is just an energy colt. Even the name is in conflict with how most of the guns are named.

**Comment by skull132** [comment]
Closing, as it's effectively an unnecessary and pointless change.

The energy pistol in question isn't powerful enough to have a major impact on gameplay, and the Warden has access to lethals annyways. Plus, more stun is actually more dangerous than weak lethals. 🤔

**Pull request closed without merging**
