### PR TITLE
Fixes Ruins and lets some Spawn

### PR DESCRIPTION
**Pull request by WickedCybs**
Most of them don't at the moment due to not being pointed to properly. There's also mapping changes I had to do.

### CODE REVIEW

**Comment by WickedCybs** [comment]
!bugfix

**Comment by WickedCybs** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by WickedCybs** [comment]
DNM because this bug still seems to be happening and I don't want to cause the second runtime apocalypse.

**Comment by WickedCybs** [comment]
we didit

**Pull request merged**
