### PR TITLE
Advanced Health Analyser Fixes

### PR DESCRIPTION
**Pull request by Ben10083**
Should fix https://github.com/Aurorastation/Aurora.3/issues/18325
Fixes for Advanced Health Analyser for shell and exosuit

QoL for Exosuit analyzer full scan, making it clearer which mode you are on, and having the scan print alongside displaying it to the pilot(s)

### CODE REVIEW

**Comment by Ben10083** [comment]
!wip

**Comment by Ben10083** [comment]
!bugfix

**Comment by Ben10083** [comment]
!review

**Comment by Ben10083** [comment]
Basic
image
Full
image

**Review by alsoandanswer — APPROVED** [review]

**Pull request merged**
