### PR TITLE
Surveyors

### PR DESCRIPTION
**Pull request by Geevies**
* Replaced xenoarchaeologists with surveyors.
* Added a surveyor energy dagger to the surveyor's closets. It isn't strong enough to cut through walls.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by TheDanseMacabre** [comment]
I am of the opinion that if we are to replace any science role with surveyors, it ought to be the RnD roles, not xenoarcheology. Xenoarcheology is specialized in a good way and has value. RnD roles are objectively worse for the server.

**Comment by senorsapo** [comment]
This is renaming an entire job and is worthy of a feedback thread and maintainer discussion.

**Comment by SleepyGemmy** [comment]
closing in favour of PR 15777.

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
remove the energy dagger since xenoarchaeologists were given machetes instead.

**Comment by Arrow768** [comment]
that will be discussed during the next dev meeting.
(might take a while)

**Pull request closed without merging**
