### PR TITLE
Unapologetic Grunge Buffs

### PR DESCRIPTION
**Pull request by Snakebittenn**
Some more underwear options. Made some example outfits for fun.
image
image
image
image

### CODE REVIEW

**Comment by Snakebittenn** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]
I don't have much against this but the moment I see someone being horny with it I'm just deleting them, you and this PR.

**Review by Geevies — APPROVED** [review]

**Review by alsoandanswer — DISMISSED** [review]
Weren't these blocked in a previous PR?

**Comment by Snakebittenn** [comment]
Yes, by Matt who has decided to comment differently this time.

**Comment by alsoandanswer** [comment]
Gonna need a feedback thread here chief

**Comment by Snakebittenn** [comment]
I don't believe it's necessary, and it would only be commented in by people with one viewpoint anyways. Not a productive use of time.

**Comment by NonQueueingMatt** [comment]
I'm not going to entertain the mantra of "feedback threads for every sprite you don't like".

**Pull request merged**
