### PR TITLE
Adds Segways to security, adds a small motor pool

### PR DESCRIPTION
**Pull request by dragoslava**
changes: 
  - imageadd: "Added SegWays to security."
  - imageadd: "Added Security Motor Pool."
dreamseeker_2018-10-15_21-05-33

### CODE REVIEW

**Comment by BotBOREALIS** [comment]
Icons with diff:
<details><summary>icons/obj/segway.dmi</summary>

Key | Old | New | Status
--- | --- | --- | ---
segway||segway|Created
segway[1]||![segway[1]](http://images.aurorastation.org/images/79ac5c9e5c8154845bae8ae0be47aeed.png)|Created
segway[2]||![segway[2]](http://images.aurorastation.org/images/02289df7992aa04ada6ab7ca7f82475f.png)|Created
segway[3]||![segway[3]](http://images.aurorastation.org/images/672ba97405b113f4b5c797c748971117.png)|Created
segway[4]||![segway[4]](http://images.aurorastation.org/images/e15f006494e12f461653c6a3574065c8.png)|Created
segway[5]||![segway[5]](http://images.aurorastation.org/images/1bdd2899dec5a49d22531d609fbb3cfb.png)|Created
segway[6]||![segway[6]](http://images.aurorastation.org/images/2b6d411eae9b72524ac925400f4eed41.png)|Created
segway[7]||![segway[7]](http://images.aurorastation.org/images/67620058702c22e1ab8c69b8cf8a2230.png)|Created
segway[8]||![segway[8]](http://images.aurorastation.org/images/e6fa20f87d88ecf875d54b108d8d8645.png)|Created
segway[9]||![segway[9]](http://images.aurorastation.org/images/46a68e686ae8903b511c016cbfadf25e.png)|Created
segway[10]||![segway[10]](http://images.aurorastation.org/images/2b54377034980926fa52f965384aef54.png)|Created
segway[11]||![segway[11]](http://images.aurorastation.org/images/8ed84b44dd544a8c6df2fe7b8503700d.png)|Created
</details>
<details><summary>icons/obj/vehicles.dmi</summary>

Key | Old | New | Status
--- | --- | --- | ---
segwaykeys||segwaykeys|Created
</details>

**Comment by dragoslava** [comment]
!review

**Comment by Arrow768** [comment]
Hm, I am unsure about that "motor pool room"
Imho three segways is a bit too much.
It would be sufficient to add one to the armory or alternatively a area that can be accessed by the officers.

**Comment by Sindorman** [comment]
Segways used to be a thing long time ago, for whatever reason it was removed. I think because HOS would always use it.

**Comment by skull132** [comment]
Segways were a Goon thing first and foremost. They were horribly OP and thus locked out of public circulation since forever. They were also relatively unwieldy.

So uh, I'm 👎 here.

**Comment by Arrow768** [comment]
PR is conflicted and requested screenshots have not been added. Moving to Dez Update

**Comment by skull132** [comment]
Marked as stale, closing.

Reopen whenever you get around to updating the PR.

**Comment by BurgerLUA** [comment]
what have you done lord fowl

**Pull request closed without merging**
