### PR TITLE
Adds new Skrell accent

### PR DESCRIPTION
**Pull request by WhatsUpBrotendo**
Adds an accent for the planet Tattuqig, available to Skrell who pick the Traverse origin.

image
image
image

### CODE REVIEW

**Comment by WhatsUpBrotendo** [comment]
!review

**Comment by WhatsUpBrotendo** [comment]
Made a small update to the sprite based on feedback given.
image
image

**Review by Llywelwyn — APPROVED** [review]
possible it might look nice if the three dots are one pixel to the right, just so the outline to their left is more visible in chat (and adds symmetry)

**Comment by WhatsUpBrotendo** [comment]
> possible it might look nice if the three dots are one pixel to the right, just so the outline to their left is more visible in chat (and adds symmetry)

image
image

Moved to the right by one pixel. If this is what you were looking for I can update the .dmi.

**Review by KingOfThePing — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
