### PR TITLE
Temperature Packs now twice as effective

### LINKED ISSUE #16716: [Bug]: Temperature packs don't cool cats
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Title. While wearing blizzard packs as taj, you're apparently still too warm and irritated by temperature. 
image

### How to reproduce

_No response_

### Round ID

_No response_

### Staff ckey

_No response_

### PR DESCRIPTION
**Pull request by Ben10083**
Title

Blizzard goes from -10 to -20, and volcano from 10 to 20.

This helps with Tajarans in particular, who usually would still be too hot even with a blizzard pack

Should fix #16716

### CODE REVIEW

**Comment by Ben10083** [comment]
!review

**Comment by FluffyGhoster** [comment]
Temperature packs don't work on the cats as per #16716 

I am not sure if it's still the case, but if it is, twice of no effect still amounts to not effect

**Review by FluffyGhoster — APPROVED** [review]

**Comment by Ben10083** [comment]
!wip

**Comment by Ben10083** [comment]
Something appears to be off with temperature, going to look into it

**Comment by Ben10083** [comment]
Going to close this and re-approach

**Pull request closed without merging**
