### PR TITLE
Genetics Nerf/Reimplementation

### PR DESCRIPTION
**Pull request by dragoslava**
Corrects alot of the concerns in genetics while replacing powers and fixing powers that didnt work. Powers that did stay received nerfs or will contuine to be nerfed

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
the concern with genetics is people fucking around with it and getting powers every single game, genetics is a tumor that is best left unimplemented

**Comment by BurgerLUA** [comment]
It is with my humble opinion that a feedback thread is created on the future of genetics. I'm not asking you to scrap your work but I seriously feel that there needs to be a lengthy discussion on bringing back genetics and how we can actually make it good gameplay.

**Comment by LordFowl** [comment]
We already reached this decision long ago. No genetics.

**Comment by dragoslava** [comment]
> It is with my humble opinion that a feedback thread is created on the future of genetics. I'm not asking you to scrap your work but I seriously feel that there needs to be a lengthy discussion on bringing back genetics and how we can actually make it good gameplay.

I fully planned on doing this, it was just very very late when I made the PR

**Pull request closed without merging**
