### PR TITLE
Halloween Code Cleanup and Cruise Map Revert

### PR DESCRIPTION
**Pull request by SleepyGemmy**
title.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!bugfix

**Comment by SleepyGemmy** [comment]
!review

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
I'd suggest you avoid touching halloween code at all so code reversion can be done automatically in one click.

Else, when Ping's Halloween PR is going to be removed, maintainers cannot easily one-click revert his PR - they will have to revert this PR as well, which is unpreferable because you bundled another bugfix with it.

**Review by Alberyk — APPROVED** [review]

**Review by alsoandanswer — APPROVED** [review]
Nevermind, I guess we're keeping halloween stuff.

**Pull request merged**
