### PR TITLE
Adds an Alternative Sweater

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR adds an alternative sweater intended for letting you layer a shirt underneath and having its collar be visible.

## information
combines all sweater sprites into a contained spritesheet.
cleans up paths.
comments the code.

## sprites
image
figure 1: comparison.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Comment by alsoandanswer** [comment]
rather than sweater, alt you should name this a sweater cardigan

**Review by niennab — APPROVED** [review]

**Comment by SleepyGemmy** [comment]
> rather than sweater, alt you should name this a sweater cardigan

cardigans have buttons, the sweater does not.

**Comment by SleepyGemmy** [comment]
> rather than sweater, alt you should name this a sweater cardigan
> 
> (this is for the simple reason that there's a LOT of sweaters and it would get very confusing, its specifically why every single one has a unique name)

sweater refluffed to v-neck.

**Review by KingOfThePing — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
