### PR TITLE
The Computer-ening

### PR DESCRIPTION
**Pull request by alsoandanswer**
improves computer sprites
dreamseeker_o0gqUlWvF5

also adds a keyboard overlay for less copypasta.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Review by SleepyGemmy — APPROVED** [review]

**Review by JohnWildkins — CHANGES_REQUESTED** [review]
Invisible sprites:
`obj/machinery/computer/cryopod and subtypes`
`obj/machinery/computer/arcade and subtypes (except orion_trail)`
`obj/machinery/computer/guestpass`
`obj/machinery/computer/HolodeckControl and subtypes`
`obj/machinery/computer/ship/navigation/telescreen`
`obj/structure/computerframe`

**Comment by alsoandanswer** [comment]
> Invisible sprites: `obj/machinery/computer/cryopod and subtypes` `obj/machinery/computer/arcade and subtypes (except orion_trail)` `obj/machinery/computer/guestpass` `obj/machinery/computer/HolodeckControl and subtypes` `obj/machinery/computer/ship/navigation/telescreen` `obj/structure/computerframe`

i also removed obj/machinery/computer/ship/navigation/telescreen` because it wasnt used anywhere

**Review by JohnWildkins — APPROVED** [review]

**Comment by SleepyGemmy** [comment]
#14098 is a related issue.

**Comment by NonQueueingMatt** [comment]
DNM until issues given to the developer on Discord are addressed

**Comment by alsoandanswer** [comment]
dreamseeker_Eg6FReodQ7

**Pull request merged**
