### PR TITLE
Icelance capacity + laser change

### PR DESCRIPTION
**Pull request by nerocavalier**
* Changed laser to match laser rifle and added two shots. This should make the Icelance more useful.

### CODE REVIEW

**Comment by nerocavalier** [comment]
!review

**Review by WickedCybs — APPROVED** [review]

**Review by Geevies — APPROVED** [review]

**Comment by Arrow768** [comment]
Will be discussed by the maintainers.

**Comment by NonQueueingMatt** [comment]
The decision we took was that the capacity buff is fine, but the icelance shouldn't have the full laser projectile. Create a new projectile type that's a bit worse.

**Comment by nerocavalier** [comment]
> 
> 
> The decision we took was that the capacity buff is fine, but the icelance shouldn't have the full laser projectile. Create a new projectile type that's a bit worse.

The new beam does half the damage of laser rifle on normal sec plate carrier.

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
