### PR TITLE
Limits Lunchbox Selection to Junkfood

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Overview
Limits the lunchbox selection to junkfood. The food will fill you up like normal,, however you will be hungry later.

### CODE REVIEW

**Comment by NortonDK** [comment]
Why would one bring shitty food from home?

**Comment by JackBewt** [comment]
You already get hunger later no matter the type of food you get from the lunch box. No combination of food available for selection in the lunchbox keeps you full for a length of time that you can ignore other sources of food. This is fixing a nonexistent problem.

**Comment by Butterrobber202** [comment]
Lmao fuck off, Burger the server is not your personal play pen. If my character wants to make a ham sandwich and bring it from home you have no right to stop him.

Also, what if I want to RP having food allergies? My character would probably just make all his/her food themselves to avoid contamination.

**Comment by MarinaGryphon** [comment]
If I want a character to bring junk food from home, i.e. if they're dirt poor, I'll give them a bread tube and bottled water, no snack. My captain isn't going to be bringing junk food for lunch in a lunchbox, and she visits the chef even with the current lunchbox. This is fixing an issue that doesn't exist, and unnecessarily limiting something that works fine as is.
Lunchboxes are not vendors. You get two food items and a drink. One is junk food no matter what, except one or two options, and the other is a sandwich or salad. You know, things you pack for a lunch at work.
If you eat everything in your lunchbox, you don't get more non-junk-food without going to the chef. Lunchbox items don't last fifteen minutes of hunger, much less the entire shift.

**Comment by Butterrobber202** [comment]
I wasn’t nice enough in my last comment so I’ll just remove the targeted insults.

If I want to RP a paranoid character that make all of his own food, or a character with allergies that makes his own food to avoid contamination, why should you stop me?

Explain to me how this benefits anyone besides the Chef.

**Comment by Arrow768** [comment]
For the reasons explained via discord that PR will be closed.

**Pull request closed without merging**
