### PR TITLE
Wheeler Hairstyle

### PR DESCRIPTION
**Pull request by Wraithcraft**
Adds hair_wheeler_s to human_face.dmi, and adds a section for "wheeler"
hair in sprite_accessories.dm.
(I tested this and it works.)
The hairstyle is just a modification of "Mulder", adding some more floof, and making the hair itself a bit more grown out, hiding some of the forehead.

### CODE REVIEW

**Comment by Lohikar** [comment]
Can we have a screenshot of the new hair?

**Comment by Wraithcraft** [comment]
Screenshot! Sorry! Errrr here!
wheelerhaircut

**Comment by Wraithcraft** [comment]
And here it is compared to Mulder! 
mulderhaircut

**Comment by HetNeSS** [comment]
So a new "winking" hair?

**Comment by Wraithcraft** [comment]
Changelog added!

**Pull request merged**
