### PR TITLE
New Hai Phong flags

### PR DESCRIPTION
**Pull request by atteria**
Added a flag and banner for New Hai Phong. Finally. 

I love the new flag system.

nhp flag showcase

### CODE REVIEW

**Comment by atteria** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]
wonderful work as always

**Review by niennab — APPROVED** [review]
Absolutely stunning.

**Review by NonQueueingMatt — APPROVED** [review]
stunning flag wtf

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
