### PR TITLE
Horizon Shuttle Enhancements: Multiple Areas + Power + Layout Changes

### PR DESCRIPTION
**Pull request by WickedCybs**
This PR adds power sources to the Intrepid & Mining Pod. It also makes the Intrepid multi-area and improves the layout a bit for ease of transit and modifying. This is all to further the goal of making it so our ships and shuttles can be fully realized spaces of their own to roleplay in and such. It opens up ways to manage an additional resource (power), sabotage specific areas of a ship (turn off one set of engines maybe?) and just interact with the overmap and the people on it in additional ways. I have fond memories of players on other servers doing stuff like using their own SMES to jumpstart an abandoned ship by wiring the two together.

The APCs on the Horizon shuttles can also now be opened by those with access to those shuttles. That's a needed change as something like swapping batteries quickly becomes very important at times with a multi-area shuttle running on power. A little less so with the mining pod, but electricity draining map anomalies or unfortunate EMPs can sap their power.

There's also some other things in this PR that will make peoples lives easier for further PRs. There's a SMES configured for shuttles in particular that can be mapped into places. It might be a little too beefy but I think it's fine for now, probably needs testing. I've also ported handrails from bay. Those are nice to have in airlocks and on the exteriors of certain shuttles. It can let pilots do a quick jump without everyone getting knocked into a wall while in an airlock, and it's also just cool to have.

Intrepid here.
image

Mining Pod here.
image

The Intrepid could use a further remap as well I'd say, but that's out of the scope of this PR's goals and will be revisited once this is merged.

### CODE REVIEW

**Comment by WickedCybs** [comment]
!WIP

**Comment by WickedCybs** [comment]
At the moment there's issues with part of the Intrepid being left behind after exiting the transit z level. That piece of the shuttle stays in the transit area for whatever reason.

image
image
image

**Comment by WickedCybs** [comment]
!review

**Comment by WickedCybs** [comment]
External air vents are desired and will be added in a future PR once the capability is there. It's a necessity in order to have the airlocks properly cycle in planets with hostile atmospheres.

**Review by mikomyazaki — DISMISSED** [review]
I understand the motivation behind the APC access change -- But I'm not sure if it makes sense, we don't even let all the engineering roles access APCs, so should a Bridge Crewman be able to do it? -- And if it is decided that they should be able to, then their wiki page should probably be updated to make it clear they're trained in field-repair of shuttle systems.

An alternative would be to adjust the events so that physically opening APCs and replacing cells isn't necessary?

**Review by mikomyazaki — COMMENTED** [review]
Have you checked whether the overlapping pump + universal adapter is re-constructable? If it isn't can you let me know / open an issue.

**Comment by WickedCybs** [comment]
> I understand the motivation behind the APC access change -- But I'm not sure if it makes sense, we don't even let all the engineering roles access APCs, so should a Bridge Crewman be able to do it? -- And if it is decided that they should be able to, then their wiki page should probably be updated to make it clear they're trained in field-repair of shuttle systems.
> 
> An alternative would be to adjust the events so that physically opening APCs and replacing cells isn't necessary?
 
The only role in engineering that cannot access APCs is the atmos tech, because that's not really something they need to do. I would say the crewman on the other hand needs access to the shuttle's systems and is already trusted to look over things to a large extent already. The APC access is required for configuring the APC to either save on power if that became important for some reason, or changing for a charged battery. Even with adjusted events, I would see the APC access as always necessary and we shouldn't nerf map events to eliminate the need for it. Power management usually isn't an issue, but sometimes it can become a unique challenge depending on what happens and it provides some pretty emergent gameplay.

The mitigator might be that an engineer will likely be on expeditions too. The way I see it, they're capable of the real work and properly keeping things together while the crewman is only able to do the mission critical field-repair.

I'll look into seeing what the general sentiment is about bridge crewmen being able to do this is. I'll note I also gave the mining pod APC mining access with the expectation a miner could battery swap and such too, so that'll be another point of conversation.
> Have you checked whether the overlapping pump + universal adapter is re-constructable? If it isn't can you let me know / open an issue.

It actually does seem to be re-constructible. The order in which it's done determines which sprite is on top of the other from my testing.

**Review by NonQueueingMatt — APPROVED** [review]
Looks good.

**Review by JohnWildkins — APPROVED** [review]

**Pull request merged**
