### PR TITLE
Changeling Absorption Tweaks

### PR DESCRIPTION
**Pull request by Geevies**
* Changelings now get DNA extraction stings instead of the proboscis guaranteed kill ability. It costs 40 chems and cannot be used on the same target twice. It grants one genome point.
* Tweaked the Changeling DNA to be sorted by WEAKREFs instead of names, meaning two people with the same name won't cause problems.
* Removed the Changeling hivemind features.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Review by SleepyGemmy — APPROVED** [review]

**Comment by Alberyk** [comment]
The maintainer discussion tag was added because this pr is reading a feature (the stealthy genome farming sting) that was once considered undesirable.

**Comment by SleepyGemmy** [comment]
i'd like to note that this sting is one per person instead of multiple times per person.

**Comment by Geevies** [comment]
Will resolve conflicts after maintainer verdict

**Comment by Arrow768** [comment]
We have discussed that PR and still believe that stealthy genome farming is still a undesirable feature.
(As this motivates players to just stealthily get the genomes during the round and then go instantly for horror-form without much prior escalation)

**Pull request closed without merging**
