### PR TITLE
Gimmick hardsuit values now match mercenary hardsuit values

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
See title

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Comment by WickedCybs** [comment]
The apotheosis suit is supposed to be Einstein's HAPT equivalent I believe. If it has reason to appear in regular play though, I suppose It's fine reducing its values.

**Comment by TheDanseMacabre** [comment]
> The apotheosis suit is supposed to be Einstein's HAPT equivalent I believe. If it has reason to appear in regular play though, I suppose It's fine reducing its values.

I was under the impression it could spawn in the EE gear crate. I'll double-check this and get back to you.

**Comment by NonQueueingMatt** [comment]
> > The apotheosis suit is supposed to be Einstein's HAPT equivalent I believe. If it has reason to appear in regular play though, I suppose It's fine reducing its values.
> 
> I was under the impression it could spawn in the EE gear crate. I'll double-check this and get back to you.

It isn't in the gear crate, it's a subtype of the HAPT suit

**Pull request closed without merging**
