### PR TITLE
Allow Eridani dregs to choose Eridani citizenship

### PR DESCRIPTION
**Pull request by Generalcamo**
Per the wiki:

> Non-citizen Dregs cannot be employed on the Horizon due to the SCC refusing to employ them, however characters who are culturally Dregs or from Dreg communities who also hold Eridani Citizenship are employed by the SCC. Even if a Dreg is born a non-citizen they automatically obtain citizenship in Eridani by simply getting a job with a megacorporation. This does not mean they have been Reinstated as they have not re-embraced the Suit culture. This means that all canon player-made Eridani Dreg characters played on the Horizon who do not possess a citizenship of another country or faction are Eridanian Citizens.

With this in mind, there is no reason dregs should not be able to choose Eridanian citizenship. This is likely an oversight, which this PR (atomized from #17929) aims to fix.

### CODE REVIEW

**Comment by Generalcamo** [comment]
!review

**Comment by Generalcamo** [comment]
!bugfix

**Comment by Generalcamo** [comment]
!wip

**Comment by NonQueueingMatt** [comment]
Reopen when the issue is fixed/found

**Comment by Generalcamo** [comment]
!review

**Review by DreamySkrell — APPROVED** [review]

**Pull request merged**
