### PR TITLE
Cable Powercreep

### PR DESCRIPTION
**Pull request by Geevies**
* Made all cables easier to click by giving them an alpha 1 lining.

image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by Karolis2011** [comment]
Has this been tested with pipes? Does it cover up a normal pipe?

**Comment by Sindorman** [comment]
why is this white alpha not symmetrical? It is 1 pixel more on one side of cable

**Comment by Geevies** [comment]
@Karolis2011 yuh, since pipes are so thicc, you can easily select them, if you're actively trying to click them. the pixels don't really overlap.
image

@Sindorman that's just the RGB + Alpha view of the thing. Since the wire in the dmi is white, and 255 alpha gets displayed as white, it looks extra thick. it's only a 1 pixel lining, pinkie promise

still looks just the same in-game
image

**Comment by Geevies** [comment]
an additional aside, working with pipes aren't never really as needed as working with cables in a high stress situation. in an extreme edge case where multiple cables somehow completely goes over a pipe, the player can simply alt click and use the turf menu.

**Comment by SonicGotNuked** [comment]
God bless. Much needed.

**Pull request merged**
