### PR TITLE
CE, CMO, OM, and RD all get mini-disruptors.

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
BCs get them, they should too. They're not very powerful in the first place, heads of staff are all big targets for baddies, and it is reasonable to give them a way to defend themselves. If a head of staff doesn't want to carry a gun, they can just leave it in their locker.

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Comment by senorsapo** [comment]
makes sense now that we are in a ship. very good pr mr dansemacabre

**Comment by FlamingLily** [comment]
CE, OM and RD I can definitely agree with, they all have critical areas that their IDs grant access to

Engines,
Fuel and Shuttles.
AI

I'm not sure the CMO should have one, personally, but also I don't really care too much (plus if every other head gets one...)

**Review by KingOfThePing — APPROVED** [review]

**Review by Arrow768 — CHANGES_REQUESTED** [review]
The weapons should be added to the relevant locker code and not the map directly, as that makes future maintenance and operations more complicated.
(Instead of just placing/spawning a head of staff locker you also have to account for the other "stuff" mapped in over the locker)

**Comment by TheDanseMacabre** [comment]
Done

**Review by Arrow768 — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Review by SleepyGemmy — APPROVED** [review]

**Pull request merged**
