### PR TITLE
Returns olden pAI sprites.

### PR DESCRIPTION
**Pull request by Belsima**
image
All around me are familiar faces
Worn-out places, worn-out faces

### CODE REVIEW

**Comment by Lohikar** [comment]
Ehh. I prefer the new ones.

**Comment by Belsima** [comment]
It just feels odd slotting the big pAI card into the presumably holographic PDA.

**Comment by TheGreatJorge** [comment]
I can imagine this sprite is usable, with some changes to colour and shape, to look a bit more modern and a bit less old. If compact look is what one is going for.

**Comment by Belsima** [comment]
I didn't make it- just a port from oldaurora. I'll close it.

**Pull request closed without merging**
