### PR TITLE
Tweaks gun safety

### PR DESCRIPTION
**Pull request by Alberyk**
Makes so that guns start with their safety off.

### CODE REVIEW

**Comment by runecap** [comment]
You can already toggle safeties by ctrl+clicking the gun

**Comment by mikomyazaki** [comment]
> You can already toggle safeties by ctrl+clicking the gun

I included it in the changelog for the gun safety addition. You could maybe stick a note on the examine message if peeps are being confused about it? Or... somewhere.

**Comment by TheDanseMacabre** [comment]
i demand a feedback thread for this

**Comment by Arrow768** [comment]
Imho this is mostly a question of people getting used to the new system, so i am not sure if thar pr is needed

**Pull request closed without merging**
