### PR TITLE
[HEAVY WIP] Glide Movement

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Professional Overview
Adds byond's glide stuff. Movement now looks smoother.

## honest overview
oh god i fucking have to make wheelchairs work and test all this shit, movement code is a fucking nightmare please send help

### CODE REVIEW

**Comment by BurgerLUA** [comment]
!wip

**Comment by Lohikar** [comment]
You aware I tried this already and abandoned it due to issues, yes?

**Comment by Lohikar** [comment]
Also, the default value (0) also means glide is enabled, all you're doing is overriding the (admittedly awful) built-in glide_size calcs.

**Comment by BurgerLUA** [comment]
lohikar says it's a nightmare so no

**Pull request closed without merging**
