### PR TITLE
Pepperspray fixed

### PR DESCRIPTION
**Pull request by NanakoAC**
Pepperspray will no longer make a spraying sound when used while the
safety is on. it makes a click instead

### CODE REVIEW

**Comment by NanakoAC** [comment]
Fixes #403

**Comment by skull132** [comment]
DNM: changelog is a .txt.

Further: the proposed changes leave the scope of the issue. It gives _all_ sprays a safety var and so forth. At the moment, only the `spray/pepper` class has a safety toggle and any need for one. A simple modification of the soundfile would be more fitting.

**Comment by NanakoAC** [comment]
I'm aware of the scope, two reasons:

1. It was a simpler fix than overriding the function.

2. Spray bottles in the real world very much do have a safety.  On a great variety of window cleaner and kitchen cleaner spraybottles, you can twist the end of the cap to lock it, which prevents it from being sprayed. Given that, it seems like a logical addition. Could be useful ingame to prevent accidentally spraying stuff when you don't want to (like after you empty out the chemistry cleaner and refill it with polytrinic acid)

Right now there's no way to toggle it though, i can add that in future, or just now

**Comment by skull132** [comment]
@NanakoAC Changelog is still a .txt.

**Comment by NanakoAC** [comment]
i will fix this tomorrow, keep forgetting about it

**Pull request closed without merging**
