### PR TITLE
Hardcore Parkour: Tableclimbing Edition

### PR DESCRIPTION
**Pull request by Geevies**
This reduces the time it takes to hop onto a table by half, I think it's 3 seconds now, down from 6. I can't read code, man. I just made big number smol number.

No longer are you a leper that can't scoot onto a waist-high table in a reasonable time, yay!

### CODE REVIEW

**Comment by Geevies** [comment]
For clarity sake, I've been informed that this actually reduces the table climbing speed from 5 seconds down to 2.5 seconds. Pretty good guesstimation on my part eh, eh?

**Comment by OneOneThreeEight** [comment]
You could honestly reduce it down to half a second and that would be really good. Not exactly "epic combat strats" good but good enough.

**Comment by Geevies** [comment]
It felt REALLY good when I tested it, but, I'd like to get insight from one of the Headmins / Head Devs, I'm all for reducing it down to a second. I mean, if you want to prevent access to a place, use barriers, or flip the table and then build a barrier. Or shoot them.

**Comment by Geevies** [comment]
!review

**Comment by NonQueueingMatt** [comment]
It's just a table man. Shouldn't take 3 seconds to climb or vault for the average person. It's just inconvenience for no reason in game, really.

**Comment by Sindorman** [comment]
Actually it would take 1-3 seconds to climb/vault the table IRL.

**Comment by Geevies** [comment]
Two seconds sounds fine to me. But, as I said before, I'd like to have a Headdev give some input, then I'll gladly modify it to what's most popular. Stupid tables.

**Comment by alsoandanswer** [comment]
You know, this makes sense back in the shitter LRP days when some baldie assistant can just leap over the pharmacy desk, smash your skull in with a toolbox and start making space lube and drugs

so, 6 seconds doesn't seem so bad in the past

now they just get banned, lmao

**Pull request merged**
