### PR TITLE
Removes Log for restart vote

### PR DESCRIPTION
**Pull request by printer16**
Removes the admin message for restart votes. There's really no reason for it.

### CODE REVIEW

**Comment by printer16** [comment]
does this need a changelog since it's not changing anything?

**Comment by alsoandanswer** [comment]
Changelog is for documentation purposes. It's pretty easy to do, so,.

**Comment by printer16** [comment]
!review

**Comment by Arrow768** [comment]
Tossed that to the mins to see if this change is wanted or not

**Comment by printer16** [comment]
> Check the for-loop lines 338 - 345. You might want to remove that as well.
> 
> To the admins reading this: there's the alternative of removing the sound effect as well from this, so you're only left with a log.
> And we can log this but not message it, as another possibility.

Removed the sound as well until Arrow gets back with what the admins said.

**Pull request closed without merging**
