### PR TITLE
Automania! Adds autoinhaler and autoinjector to autolathe

### PR DESCRIPTION
**Pull request by Geevies**
* Adds autoinhaler and autoinjector to autolathe.
* Gives autoinhaler and autoinjector material values (i'm open to suggestions to tweak 'em)

This allows medical to come to cargo to print more of these and hand them out to crew. Good stuff.
If anyone has any other ideas to add more (reasonable!) stuff to autolathes, you know where to contact me.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by alsoandanswer** [comment]
Did you check the balance by crossreferencing other server recipie costs?

**Comment by Geevies** [comment]
@alsoandanswer not at all! i eyeballed it

**Comment by alsoandanswer** [comment]
You should take a look

**Comment by Geevies** [comment]
Got this from Bay.
image

I think it's too little.

**Pull request merged**
