### PR TITLE
It's Time - Lar Maria

### PR DESCRIPTION
**Pull request by CyberSpyXD**
Ports the Lar Maria research station from Bay. Rather than have a rage virus it's greimorian infested.

### CODE REVIEW

**Comment by CyberSpyX** [comment]
!wip

**Comment by Syncrosync** [comment]
All I'll say is rage virus is cooler. Too many greimorian sites as it is.

**Comment by CyberSpyX** [comment]
> All I'll say is rage virus is cooler. Too many greimorian sites as it is.

The problem would be that it's not even implemented on bay either. They removed virology just like we did. I do not agree greimorians are that overrepresented either at the moment.

**Comment by Syncrosync** [comment]
> > All I'll say is rage virus is cooler. Too many greimorian sites as it is.
> 
> The problem would be that it's not even implemented on bay either. They removed virology just like we did. I do not agree greimorians are that overrepresented either at the moment.

I mean, they are the only off-site hostile that isn't a space-fish, or a worm. I'm not saying its not a good addition, I just wish we had more than angry space bugs, and angry space fish as off-site encounters.

**Comment by CyberSpyX** [comment]
> I mean, they are the only off-site hostile that isn't a space-fish, or a worm. I'm not saying its not a good addition, I just wish we had more than angry space bugs, and angry space fish as off-site encounters.

Can always pop some suggestions on the fourm as to what may fit. More varied stuff aesthetically is always going to land with animals or machines at the moment typically I think, as anything more (like humanoid enemies) is going to affect roleplay and the continuity of such of a sight.

If not Greimorians, I'd probably have the site have hivebots though.

**Comment by NonQueueingMatt** [comment]
Stale

**Pull request closed without merging**
