### PR TITLE
Valley Hale offship additions.

### PR DESCRIPTION
**Pull request by Snowy1237**
Adds the OE, COC surveyor and Dominian science vessels to Valley Hale.

### CODE REVIEW

**Comment by Snowy1237** [comment]
!review

**Review by courierbravo — APPROVED** [review]
I swear to god I have the CoC Survey ship nearly done I'm just dying trying to make the markers work. Anyway, looks good code wise

**Comment by hazelrat** [comment]
OE seems fine, but I'm not sure why a CoC or Dominian ship would be in Valley Hale? I understand the majority of the sector is meant to be occupied by Elyra, which presumably doesn't want Dominian ships in its territory, and what's a Coalition surveyor doing outside of both the Coalition and frontier?

I'm also concerned by ghostrole bloat with this. Valley Hale is in a decent spot right now in that the pool is small enough that you can decently count on getting a ship that you want. The more ships we add to that, the less likely that is.

**Comment by Snowy1237** [comment]
I have asked human lore regarding the offships but now that you mention ghostrole bloat this PR is probably not a good idea... I will probably close this.

**Pull request closed without merging**
