### PR TITLE
Gives paramedics basic access. Removes it from janitors.

### PR DESCRIPTION
**Pull request by Arrow768**
Basic departmental access is removed from the janitors and given to the paramedics instead.

As suggested here: https://forums.aurorastation.org/topic/12357-give-paramedics-general-access/

### CODE REVIEW

**Comment by tzeneth** [comment]
Context for me, I don’t and haven’t played paramedics but discovering they don’t have general access surprises me. They should have it. I’m posting more because of the latter change to janitors.

The amount of times I’ve seen broken lights never reported, messes that were never reported, or cleanup in the medbay while everyone is busy are many. I may also be influenced by the fact I often play during dead times where there isn’t always an AI or an HoP which means I wouldn’t have easy access to certain messes that happen due to pressure backup in the air scrubbers or any other reason but I think janitors SHOULD have general access. Without general access it means that medical can be in a panic due to needing to deal with chaos and leave a mess everywhere while I can’t get in there to keep it clean, like my job is supposed to, without having one of them come over and let me in. I can also think of other examples that fit. It also means my mute janitor is much less viable (because I could do my job without needing to constantly phone in requests for access) which makes me kind of sad because it’s fun to be the silent cleaner, a person who comes in with a smile and wave while they clean up the messes by the drunk visitors, then go to medical and see that they’re busy and clean up the blood from the madness that happened and then do a tour of the station to check in with the various workers. Maybe I’m just one person who’s niche but I like that character and would be sad to have to change or stop playing them (also it’s kind of funny to see who actually takes sign and who doesn’t).

**Comment by Kaedwuff** [comment]
Janitors weren't even involved in the original suggestion, and you're getting a lot of player blowback about removing janitor access based following the contents of a different thread linked in this suggestion.

**Comment by skull132** [comment]
IMO. Either we devalue the access system in full and give both general access, or we maintain a rigid hold on it and give it to neither. ~~It'd be interesting to have sec fall under the same treatment if the latter mentality is followed.~~

I don't really see the point of removing it from Janitor while giving it to Paramedic. The same arguments apply for both: they need it to ease their job. The only difference is the stakes, I suppose.

**Comment by Arrow768** [comment]
> And what are these two access changes on a couple doors? Those aren't mentioned in your explanation.

> Basic departmental access is removed from the janitors

**Comment by Kaedwuff** [comment]
> > And what are these two access changes on a couple doors? Those aren't mentioned in your explanation.
> 
> > Basic departmental access is removed from the janitors

Are you telling me that someone just manually added janitor access to those doors instead of giving that locations access to the janitor?

**Comment by Arrow768** [comment]
Well, I changed my mind about that PR.
image

For the reasons brought up by some people on the topic (EMTs have a much greater influence on the round and already rush into areas where they shouldnt be in the first place) I am closing this PR.

**Comment by skull132** [comment]
image
For posterity's sake, this is a good argument for why Janitors should keep access and EMTs (and later, because power creep is a bitch, Sec and Engineering) shouldn't.

**Pull request closed without merging**
