### PR TITLE
Fix slot machines init

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Fix slot machines init, they were unnecessarily creating the coins to add and then immediately QDELing them, making SSAtoms angry. They were also sleeping during init, making SSAtoms doubly angry.

Please test that the slot machines keeps working, while the code suggests they should still work perfectly fine, my faith in the code I have seen in this file makes me wary.

Atomized from https://github.com/Aurorastation/Aurora.3/pull/16065

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!bugfix

**Comment by FluffyGhoster** [comment]
!performance

**Comment by FluffyGhoster** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]

**Review by SleepyGemmy — APPROVED** [review]

**Comment by SleepyGemmy** [comment]
>Please test that the slot machines keeps working

this is your responsibility.

**Comment by FluffyGhoster** [comment]
> > Please test that the slot machines keeps working
> 
> this is your responsibility.

I have tested it, it seems to work to me, coins gets accepted and whatnot, but I have never actually gamed on those slot machines, therefore what I wrote, whoever wrote or used them plenty, it would be good if he can confirm every possible combination works as expected, as far as I can tell, it does.

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
