### PR TITLE
Add mapmerge 2

### PR DESCRIPTION
**Pull request by Lohikar**
Adds TG's mapmerge2, a new TGM-compatible merger that handles things like dictionary expansion much better than the old tool, as well as supporting a git merge hook for map files.

This PR does not remove the old merger as this one is more annoying to setup.

### CODE REVIEW

**Comment by HeyBanditoz** [comment]
Honestly, you should either go all the way or not at all.

**Comment by Arrow768** [comment]
I concur. There is no point of keeping mapmerge if we have mapmerge2

**Comment by skull132** [comment]
Thirded the opinion above.

**Comment by Arrow768** [comment]
Reopening #4646 as the requested changes have not been implemented by the Author of this PR

**Comment by Lohikar** [comment]
Not going to remove old tool, mm2 does not seem to have a conflict resolver tool.

**Comment by skull132** [comment]
Merged with the old tool still intact due to no conflict resolver being present here.

**Pull request merged**
