### PR TITLE
A round of fixes, polish and suggested additions to the map.

### PR DESCRIPTION
**Pull request by fernerr**
Feedback thread: https://forums.aurorastation.org/topic/11463-adding-a-bunch-of-requested-additions-stationwide-polish-and-fixes-mixing-up-maintenance-a-bit/

- Partitions maintenance in several spots on the main level with airlocks.
- Changes up cargo, medical, security and research maintenance a bit by adding some points of interest.
- Fixes the medical maintenance exterior airlock.

(**Spoilers** if you want to explore the maintenance changes on your own.)
https://i.imgur.com/xfzgx08.png
https://i.imgur.com/CdqW9Xu.png
https://i.imgur.com/7sgra85.png

- Fixes one of the buttons in the QMs office, adds tintable windows and moved the stairs leading out of the office a bit.

https://i.imgur.com/s62Zkev.png

- Adds missing emergency shutter to the surface conference room.
- Fixes a steel wall in the kitchen that's supposed to be a wood one.
- Adds camera coverage to the telecomms lounge and reroutes the disposal outlet.

https://i.imgur.com/tAn01fd.png

- Removes the rock from on top of the telecomms solar arrays.
- Adds a chess set and deck of cards to the dining room.
- Fixes missing access requirements to the telescience windoors.
- Adds an air alarm and a chair to the CMO's office.

https://i.imgur.com/zn8pspq.png

- Adds additional airlock access controllers to Hazardous specimens.
- Adds an atmospherics control laptop to Xenoflora to remotely control  the Hazardous specimens air alarm.
- Reinforces the test range with another layer of reinforced walls.

https://i.imgur.com/kGAa9vG.png

- Adds an emergency shower to chemistry.

https://i.imgur.com/Yg8vyqD.png

- Fixes sublevel maintenance by separating it into three areas, instead of being a single disconnected area.
- Improves research request consoles by removing a couple and making their tags more specific.
- Adds a cyborg recharger to the main level bathroom.
- Adds an O2 locker outside the bar.
- Adds a desk lamp to the psych's office.
- Adds access to the exotic harvesting chamber air alarm to the Xenoarcheology atmospheric laptop.
- Fixes missing windows and wrongly coloured chair at the vacant office.
- Adds front desk shutters to RnD.
- Adds in missing emergency shutters at the library entrances.
- Adds numerous air alarms to places missing them.
- Adds actual coffee instead of water to the surface conference room coffee machine.

https://i.imgur.com/33E4K7a.png

- Adds additional vents to the surface hallway aft.

New:

-Did some changes to the Supervised Living Center by request.
-Added huge air scrubbers to toxins, made those in the brig usable.
-Added a distro to canister pump at the toxins exterior airlock.
-Fixed a few of the RDs office tinted windows which had the wrong ID.

### CODE REVIEW

**Comment by Sindorman** [comment]
Oh God, you are gonna kill me with map merge conflicts lmao.

**Comment by fernerr** [comment]
Sorry friendo, let me know if there's anything I can do to alleviate your pains.

**Comment by Sindorman** [comment]
It's okay, I just have big PR that uhm is taking long time to finish.

**Comment by fernerr** [comment]
!wip

**Comment by VTCobaltblood** [comment]
if lounge is monitored where do i erp now

**Comment by fernerr** [comment]
!review

**Comment by fernerr** [comment]
That makes sense, changed those airlocks to be of the proper access requirements as well as did a quick look-see across the station and caught a couple more.

**Comment by fernerr** [comment]
Aaaand it's done for real. But do let me know if there's any other fixes that would be good to squeeze in.

**Comment by fernerr** [comment]
Noticed a new windoor missing access requirements, will have it fixed in a minute.

**Pull request merged**
