### PR TITLE
Tidying bounties

### PR DESCRIPTION
**Pull request by Kaedwuff**
Bounties are being cleaned up per suggestion thread https://forums.aurorastation.org/topic/14245-cargo-bounties-housecleaning/

Categories of bounties I am removing
-Bounties that are extremely silly, like shards of metal for a 'booby trap to catch a clown'
-Bounties that are for common things there is no logical reason the Odin could not get for itself, like vending machine items and snacks
-Bounties for items that are irritating to collect, like rechargers and potted plants, which have to  be unscrewed and/or dragged across the station
-Bounties for items that are high risk, high security, or unique, like the captain's spare
-Bounties for items that are questionable or illegal to obtain, like human hearts
-Items that are no longer available, like the revolver
-The entire virus bounty dm, because it is unused.

The last time I did this, I also changed the bounty values to be less. This time, I am just removing dumb or unreasonable bounties.  I urge anyone reviewing this to consider the damage these bounties cause to the immersion on the server and that many of them that aren't outright memes are just frustrating to collect.  Please consider this PR from an angle outside of 'but memes funnay, why remove'.

I've also adjusted some of the descriptions of otherwise okay bounties to be less goofy.

### CODE REVIEW

**Comment by Doxxmedearly** [comment]
Unsure how I feel about removing a ton of bounties without giving them a replacement. There's already so little variety to them, this will just make the problem worse.

That said, I agree wholeheartedly with your work cleaning up the memery of them, and removing some goofy ones.

Some of the removals are questionable, though. Potted plants? Maybe annoying but it gets you around the station. Toolboxes? Statues? Pancakes? Earmuffs? Why remove these ones entirely when you could just edit the descriptions to be less memey? Seems like a heavyhanded approach when a lot of these could be pretty easily salvaged.

**Comment by Kaedwuff** [comment]
> Unsure how I feel about removing a ton of bounties without giving them a replacement. There's already so little variety to them, this will just make the problem worse.
> 
> That said, I agree wholeheartedly with your work cleaning up the memery of them, and removing some goofy ones.
> 
> Some of the removals are questionable, though. Potted plants? Maybe annoying but it gets you around the station. Toolboxes? Statues? Pancakes? Earmuffs? Why remove these ones entirely when you could just edit the descriptions to be less memey? Seems like a heavyhanded approach when a lot of these could be pretty easily salvaged.

Pancakes in particular came up as a frustrating bounty item the last time I worked on this, as they require a bunch of berries (which are almost unused otherwise) to make, so fall under 'frustrating'.  Toolboxes fall under 'common items there is no reason there should be a bounty on', and potted plants are annoying to collect and, make the station more bare after you have yoinked half a dozen of them, and is frankly a little silly, why do we need to ship decorative plants.

At the end of the day, I think the novelty of the bounty system should just  be that - a novelty. It should not be filled with things that encourage appropriating public supplies or scenery objects from the station or badgering other departments to give their supplies up for the sake of fulfilling cargo's need to do something.  I'm not a big fan of the system in general, but I recognize that it serves a purpose of giving bored players something to do when things are slow.  It doesn't _need_ to be full of hundreds of interesting and unique things to work.

Adding items is also outside of the scope of this PR.  You, or anyone else ,could easily add bounties if you feel like you want to pad out the options, but I'm pretty sure we've moved well past the dev metameme where we keep bad content in the game simply because we don't have anything to replace it.  This is bad content, so I am removing it.

**Comment by Arrow768** [comment]
After a discussion with the maintainers, we will require replacement bounties.
This is to prevent bounties becoming too repetitive.

**Comment by Kaedwuff** [comment]
> After a discussion with the maintainers, we will require replacement bounties.
> This is to prevent bounties becoming too repetitive.

I have added almost 20 new items, some of them being objects that science rarely has cause to produce for any legitimate reason, and which could definitely be used for certain antagonist purposes if are lucky enough to be a cargo antag or able to con science.

**Pull request merged**
