### PR TITLE
Disposals Layout Tweaks + Generic Changes

### PR DESCRIPTION
**Pull request by furrycactus**
- Changed the disposals lines on the sublevel so that they're linked to the tracks on the main level and empty into the crusher, instead of ejecting into space on a bunch of places around the sublevel. Virology and Xenobiology trash still eject into space, however.

- Added toeless workboots to the engineering wardrobes in Engineering, like how the security wardrobe has toeless jackboots. Also added them to the xeno wardrobe on the surface, along with some cloth footwraps too.

- Added two extra maglights, crowbars, and radios in the security equipment room so that officers and cadets don't need to fight over them.

- Cleared a little area underneath the open space turfs in the "Armoury Access Lift", renamed the airlocks to remove mention of the Armoury Access Lift because no one I asked seems to know why it exists and is called that.

- Tweaked the wire layout in the Tesla Engine room so that the APC down there doesn't always end up with a power alarm unless the engine is set up.

- Connected the Engineering Maintenance APC to the main grid instead of the Engineering subgrid, like the rest of the departmental maintenance APCs.

- Added a cell recharger in mining on the desk so that cells can be charged inside, as requested on the forums.

It's been a little while since I've mapped. I've tested these things and haven't been able to find any issues myself, but if anyone else spots any please say.

### CODE REVIEW

**Comment by fernerr** [comment]
Some nice changes, well done. 

A change to the disposal side of things that I think would work better though
https://i.imgur.com/9aVBsx9.png (Pink arrows)
Rather than creating new vulnerabilities that aren't too pretty in themselves, the disposal lines would be connected to the already existing medical disposal line.
Also; the green area, where research disposal used to be, could use a bit more chasm mask.

Feel free to pm me whenever if there's any questions or concerns.

**Comment by furrycactus** [comment]
Sure thing :ok_hand:

**Comment by furrycactus** [comment]
Oh, I also forgot to mention I replaced the windows in surface atmos with walls, so that the whole sublevel section doesn't get vented all the time when carp break the windows.

https://prnt.sc/o1m6u8

**Comment by fernerr** [comment]
Simply fix this little oversight with the leftover area at the engineering sublevel maintenance and it should be good to go. 
area

**Comment by furrycactus** [comment]
!review

**Pull request merged**
