### PR TITLE
TCAF Corvette Remap

### PR DESCRIPTION
**Pull request by hazelrat**
This is a remap of the TCAF Corvette offship, intended to be more intuitive than the current one. 

**This is up for review.**

Notes:

1. The combustion engine isn't the only source of power in the ship, there's also a portable generator that should be able to produce enough to keep the ship going.
2. This adds a few clothing and overmap sprites for use in the ghostrole, credit to Noble for them, and it also consolidates a few of the existing TCAF assets into a single faction file. It isn't comprehensive, but it's more organised than it was.
3. The armoury has been diversified a little. It's now composed of two blaster rifles, one bolt slinger, one combat laser rifle, one pump shotgun, and one burst rifle, plus the PEAC and six blaster revolvers as sidearms. The primary intention of the combat laser rifle, pump shotgun, and burst rifle is to provide a little AP which blasters universally badly lack, so the ghostrole should be decently competitive against armour. My hope is it should be roughly as strong as the Coalition Ranger ship in combat.
4. I'm not totally happy with the hangar, but I'm not satisfied with any of the docking port designs I've been able to think of, so I'm running with it for now. I do believe a docking port is generally preferable.
5. Per Trio, species restrictions are tightened a bit on the Decurion to only cover humans, Skrell, IPCs, and Vaurca Warriors. Liable to be changed. Vaurca workers have also been excluded from every combatant ghostrole, playable only as technicians. I'll be prodding at adding bulwarks too, but they're not currently included due to some fickleness with giving them appropriate uniforms.
6. The sensors are the strong variant for the shuttle and ship, with the idea that it should be particularly good at reconnaissance. I doubt anyone would use the shuttle to scout the sector, but the sensors are good to throw a bone in that direction.

### CODE REVIEW

**Comment by hazelrat** [comment]
!wip

**Comment by hazelrat** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by courierbravo** [comment]
Looks good map wise. Only thing I noticed wrong is the biogen is using the old broken var version. Just remove the variable and I'll approve :)
StrongDMM_O6FUuenx4A

**Comment by hazelrat** [comment]
> Looks good map wise. Only thing I noticed wrong is the biogen is using the old broken var version. Just remove the variable and I'll approve :) StrongDMM_O6FUuenx4A

Done!

**Review by courierbravo — APPROVED** [review]

**Review by Geevies — APPROVED** [review]

**Pull request merged**
