### PR TITLE
Gives vending machines a glow up

### PR DESCRIPTION
**Pull request by desvenlafaxine**
After much thought regarding my past attempt to update vending machine sprites, I ultimately decided to do the following:

*Remove the sideways sprites, since I cannot really see these being used.
*Acquire sprites that are an updated version of ours instead of some that look really different. The sec vending is a good example of this. The one in Polaris looks nothing like ours. The one I'm using now (from tg) is ours but updated.
*Don't make mapping changes or even touch the drying rack, because the sprite ultimately looked weird. I still don't think the smartfridge sprite is a good fit, though.

Here's a small gallery. As you can see, they just look a bit better. I don't have them animated here (except for one), but they have more frames too.
image
image
image
image
image
image

These eight machines also now have vending sprites.
image

Though the coffee one always had one, here's how it looks now:
image

08/16/2021 UPDATE: tweaked the sprites even further, added vending animations for all machines in-game and more animations over all

### CODE REVIEW

**Comment by desvenlafaxine** [comment]
!review

**Comment by desvenlafaxine** [comment]
The more I keep thinking about this, the more I see it as a necessary update. Why? To put it bluntly, the current vending machines sprites are ugly and seriously outdated. Every single change or tweak I can think for them requires me to radically change them. I don't think it's necessary to _completely_ redraw all vendors just for the sake of OC. It would be a tedious task because there's just so much you can change in a vending machine in the first place. 

I went ahead and chose those, for this version, that fit our style. Now, I cannot fathom why they wouldn't. If it's the 3/4s perspective, which plenty of things in game already have, the current vendors do so too. Here's a comparison between the current cigarrette vendor and the one I ported.
image
image

As you can see, in the current one there's an attempt to make it somewhat sideways and also show the top. It's not a plain square sprite. The one I'm porting makes the roof of the vendor more evident, but that's because it also gives a better sense of perception, since the current one just makes it look oddly flat. Besides that, it just has a better color palette and just looks better over all. There's little redeeming qualities with the current vending machine other than it's been here forever. 

In short, I think resprites are useful. They help keep the game look more up to date, and in this case they also add a bit of interaction with other vendors (the vending icons). There's nothing about the current sprites that screams 'Aurora' or 'Aurora artstyle', and the same goes for the arcades I ported, since as far as ugly sprites go, I seriously think the arcade machine is the biggest offender. I tweaked some of these to make them fit better to ours (changed colors so they fit the department, or in the case of the Zo'ra machine, I designed a new one that retains the bug head). The first attempted failed in that many of the Polaris machines looked seriously different. If you check the icon differences on this PR, all but battlemonsters (which I could recolor if asked) are just updated versions of themselves.

 Sorry for the small rant, it's just that I think we should give them a chance. It has nothing to do with that I ported them, and if I didn't try to learn how to port for this I would've probably asked or even payed for someone to do this change. I just really hate the Robust Softdrinks current sprite, that's all.

**Comment by NonQueueingMatt** [comment]
So the issue with these sprites is that they follow the 3/4 standard and we don't currently want sprites ported from other servers with that standard, unless absolutely unavoidable. Please find other sprites that match our current style if you can.

**Comment by desvenlafaxine** [comment]
> 
> 
> So the issue with these sprites is that they follow the 3/4 standard and we don't currently want sprites ported from other servers with that standard, unless absolutely unavoidable. Please find other sprites that match our current style if you can.

I don't really understand, though. Plenty of things in-game already use this perspective. As shown in my defense of these sprites, the current vending machines aim to do it too, albeit poorly. I understand the reluctance of having Bay-like 3/4 sprites. That's also the reason why I removed the side sprites for these, and I'm willing to do the same for the arcades too (which also, in their own way, are 3/4s). Here are some examples with things that have that kind of 'roof':

Forensics stuff:
image

Bookcases:
image

Photocopiers:
image

Cremators (morgue trays too):
image

The lathes:
image

The tanks:
image

The kitchen oven, which uses the exact same perspective:
image

There are more stuff. One can argue things like cabinets and tables also, but I think you get the point. I urge you to reconsider this. Test the PR, run around the station. They don't really look out of place or anything.

**Comment by desvenlafaxine** [comment]
Removed the unused vending machines and added the base sprite in case any new vendors are ever needed.

**Comment by desvenlafaxine** [comment]
imagen

Another prime example. Next to the other items on the picture, the vending machine looks like it's on the floor.

**Comment by blackwolf5505** [comment]
If the worry is about style consistency, we're already at an impasse with the mixture of 3/4th and top down sprites. There's a heavy mix as is, so consistency argument bad.

Also pretty sure most those examples Desven showed have the same source as the vendor sprites, so why vendor bad but welding tank, scanner, forensics stuff, etc, good?

**Review by NonQueueingMatt — APPROVED** [review]

**Review by Jaraci — APPROVED** [review]

**Pull request merged**
