### PR TITLE
Camera Map Fix

### PR DESCRIPTION
**Pull request by printer16**
Fixes the camera map

### CODE REVIEW

**Comment by skull132** [comment]
Is this tested? Is `config` a valid JS entity that's accessible from here?

**Comment by Lohikar** [comment]
Doesn't appear to be, no object named `config` is passed to NanoUI.

**Comment by printer16** [comment]
It works for the suit sensor console that uses config.

**Comment by skull132** [comment]
Yup, it's an actual thing being sent to every UI. Neat.

**Pull request merged**
