### PR TITLE
Adds Face Masks - A Gas Mask Variation

### PR DESCRIPTION
**Pull request by WickedCybs**
This PR adds a variant of the transparent/tactical gas masks that only covers half of the face, so like a more compact respirator basically. I think it looks rather nice for flavor and as an additional option that can be used, mainly with headgear. It can also be pulled down to the neck like a breath mask. Sometime in the future, I think I'd like to make a less black variant for engineering in particular as a half-face respirator is generally used by those dealing with particulate and such.

Some pictures

image
image
image
image
image

This PR doesn't actually map the mask in anywhere. It also does not add it to any lockers for now. 

- [x] Finish the mask up
- [x] Get versions for aliens done
- [x] Map it in/Add it somewhere

### CODE REVIEW

**Comment by WickedCybs** [comment]
!review

**Comment by Spacemanspark** [comment]
"I was born in the darkness. Molded by it"

**Comment by NonQueueingMatt** [comment]
Why not add it to the emergency survival box? I think it'd make a fine replacement.

**Comment by WickedCybs** [comment]
> Why not add it to the emergency survival box? I think it'd make a fine replacement.

Was kinda thinking about it, though it would give crew a mask capable of filtering gasses out of the gate (but they'll have no eye protection) versus the breath mask that will only do so if set with internals. 

Was thinking of adding it to various lockers, maybe swapping breath masks on voidsuit racks with the respirator. Appearance-wise the breath mask does look less bulky and such.

**Comment by WickedCybs** [comment]
Making this a draft for now until where it can be obtained is figured out. I forgot I could do that.

**Comment by WickedCybs** [comment]
Mapped in the masks and added them to a few lockers and item pools. Still open to feedback on where to put them too.

**Review by Geevies — APPROVED** [review]
nobody cared who i was

**Review by fernerr — APPROVED** [review]

**Pull request merged**
