### PR TITLE
Adds Assunzionii voidsuit modkits to loadout

### PR DESCRIPTION
**Pull request by hazelrat**
This creates two modkits for the Assunzionii 'Rook' voidsuit, one for the human variant and one for the IPC variant, available in the loadout to any character with an Assunzionii origin. It's only applicable to research voidsuits.

IPCs have access to both variants so human-shaped synthetics can still get a suit they can use.

In current code, the Rook is a military voidsuit descended from the Coalition Vulture. As this allows you to transfer it from research voidsuits, it has been shifted to be a mechanically identical subtype of the standard research suit. Anything in the description alluding to its military uses or its anomaly resistance have been removed to reflect this.

This should be a relatively clean change, the Rook isn't currently used substantially in the uplink or for any ghostroles. My thought is that, if someone ever does make an Assunzione military offship, they could resprite this suit for a new armoured variety. The implementation should otherwise resemble the implementation of the Himean modkits.

### CODE REVIEW

**Comment by hazelrat** [comment]
!review

**Review by DreamySkrell — APPROVED** [review]

**Comment by DreamySkrell** [comment]
Actually idk. Dunno.

I know we have the himean modkit already, and had it for a long time now.

But I think some thought should be given as to what voidsuits should be allowed, or if they should be allowed at all.

Cause if Assuzioni modkit is fine (not being really close to SCC I think? but also why is himeo modkit allowed, since they hate heph...), then like why people couldn't start adding about like any random nation's modkits to the loadout. And at that point why is SCC supplying us with voidsuits but the crew brings their own gear anyways.

**Comment by hazelrat** [comment]
> Actually idk. Dunno.
> 
> I know we have the himean modkit already, and had it for a long time now.
> 
> But I think some thought should be given as to what voidsuit modkits should be allowed in the loadout, or if they should be allowed at all.
> 
> Cause if Assuzioni modkit is fine (not being really close to SCC I think? but also why is himeo modkit allowed, since they hate heph...), then like why people couldn't start adding about like any random nation's modkits to the loadout. Why not kosmostrelki sec voidsuit modkit? Why not fed skrell modkit? Why not modkit?
> 
> And at that point why is SCC supplying us with voidsuits but the crew brings their own gear anyways?

I think I'm more sympathetic to the modkits so long as they stay out of security, I can personally (and subjectively!) see them being used for every department but security, where I'd think uniformity of equipment would be important. Assunzione does have strong ties to ZH, by my understanding, so I think it'd make a little more sense for them to be given permission from the SCC to utilise the design on their vessels than it does for Himeo.

I think it also helps a little that the description for this suit implies it was designed essentially or partially by ZH, in collaboration with Assunzione's government. It could just be viewed as using an alternate SCC-originating voidsuit that happens to be associated with a particular region, more than using technology that's completely foreign to the corporations.

**Comment by DreamySkrell** [comment]
>Assunzione does have strong ties to ZH, by my understanding, so I think it'd make a little more sense for them to be given permission from the SCC to utilise the design on their vessels than it does for Himeo.

In lore basically every faction or nation has strong ties to some corporation so you could use this argument to bring about any faction's voidsuits to the loadout. ZH itself has strong ties with nralakk, sol, assuzione, galatea, and I think more.

**Comment by hazelrat** [comment]
> > Assunzione does have strong ties to ZH, by my understanding, so I think it'd make a little more sense for them to be given permission from the SCC to utilise the design on their vessels than it does for Himeo.
> 
> In lore basically every faction or nation has strong ties to some corporation so you could use this argument to bring about any faction's voidsuits to the loadout. ZH itself has strong ties with nralakk, sol, assuzione, galatea, and I think more.
> 
> As for uniformity, I think it's good even outside of security. Especially for expeditions, where these suits would be used the most on. It'd be weird if Horizon goes to lemurian sea and there's horizon crew in assuzione suits mixing up with actual assuzione people (in the case of assuzione suits).

On the lore note, this is true, I just don't think it's a huge issue tonally if we did have people wearing diverse voidsuits about. Personally, I can see the SCC being permissive over it. I will say I'm more open for this for research than other departments, since I think scientists on tenure to the Horizon would get a lot more leeway with the equipment they use for their field studies than the average shmuck miner, paramedic, or engineer would.

On the other note, this is partially just a limitation of the assets we have, but we do already have an abundance of ghostroles that utilise the same voidsuits as the Horizon without producing much confusion ingame. Assunzionii working on the Horizon _are_ still actual Assunzionii people, they just happen to be working on a megacorporate ship.

**Review by NonQueueingMatt — APPROVED** [review]
don't particularly mind these kinds of modkits; they make the world feel more alive imo and it's never been a big problem to recognise them. you see them once and you know thats an engineering person in case of the himeo modkit, same goes for the assunzionii one, etc

i'd only have an issue with a more generic one or a mil larp sec one

**Comment by DreamySkrell** [comment]
> don't particularly mind these kinds of modkits; they make the world feel more alive imo and it's never been a big problem to recognise them. you see them once and you know thats an engineering person in case of the himeo modkit, same goes for the assunzionii one, etc
> 
> i'd only have an issue with a more generic one or a mil larp sec one

It's not a problem now cause we only have one (himeo, and may have two with the assuzioni modkit).
It may become a problem if people start adding modkits for other nations. And at that point everyone would be wearing random voidsuits in all colors of the rainbow, throwing our corporate aesthetics and color schemes out of the window.

**Pull request merged**
