### PR TITLE
Bump rustg to v1.2.0+a2

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Updated the default rust_g dll to 1.2.0+a2 from our other repository release.
Its two DLL binaries are from our rustg repo https://github.com/Aurorastation/rust-g/releases/tag/v1.2.0%2Ba2, they can be MD5/SHA1'd to confirm it.

 Added a debug verb for our custom udp send module used in rustg.

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!dependencies

**Comment by FluffyGhoster** [comment]
!performance

**Comment by FluffyGhoster** [comment]
!review

**Review by Arrow768 — APPROVED** [review]

**Comment by Arrow768** [comment]
You should delete the udp_debugger item

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
