### PR TITLE
Adds Solarian Army service uniforms, modifies Navy uniforms, and other such things.

### PR DESCRIPTION
**Pull request by Sinbest**
This is my first PR here, so sorry if I've done it wrong.

Summary of Changes:

- Adds Solarian Army service uniforms (shown below).
- Modifies Solarian Navy dress uniforms to "match" Army service uniforms (also shown below).
- Solarian Marines and the Solarian Army both get green and grey utility/combat uniforms.
- Adds grey Marine cover.
- Adds grey and green Army field caps.
- Adds garrison cap and campaign cap as part of Army service uniform (also shown below).
- Makes the visors of Sol dress caps round and not square like they're made of 40% cardboard or something.
- Makes the gold on officer's swords look like gold and not butter.

army uniforms

image
image

navy uniforms

Future Plans (in future PRs):
- New Marine Corp service and/or dress uniforms (unsure of colour).
- Bay-style rank insignia.
- Separate Navy uniforms into a majority black with a white hat service uniform, and an all white dress uniform.
- Separate jackets from Sol dress/service uniforms, replace the grey sweatshirts from Baystation with actual dress shirts, and replace ICCG red with Sol ~UN~ blue.
- ~UN blue Army dress uniforms (the antichrist drip)~

### CODE REVIEW

**Comment by Sinbest** [comment]
!review

**Comment by TheDanseMacabre** [comment]
Good work with the army uniforms, but a few comments:
chrome_RzdZXuoE8Y
I don't think this is a necessary change, and dress uniforms/service uniforms pretty much have no utility on Aurora. For all intents and purposes, we should just stick to having one sort of uniform that fits all situations, even if that's not in line with IRL military tradition. More or less, this is what we currently do: Enlisted people have their coveralls, and the officers have one of three similar officer uniforms.
image
As said on discord, complicating the uniforms like this will pose problems with player usage. They should be kept as simple as possible, so they end up being used properly regardless as often as possible. As for the red on the uniforms: this is intentional and not just a holdover from Bay. I felt that trying to go the UN angle with blue highlights on their uniforms was kinda overdone and I think red works well with the other colors of the uniform.
image
Rank insignia is another overcomplication that will absolutely cause problems with player usage, and there's minimal need for it. It's just bloat/excess for the sake of it, and this is a situation where absolute simplicity is best.

**Comment by Sinbest** [comment]
> I don't think this is a necessary change, and dress uniforms/service uniforms pretty much have no utility on Aurora.

Technically we already have both.

image

But yes, I understand what you're saying.

> Rank insignia is another overcomplication that will absolutely cause problems with player usage, and there's minimal need for it.

Rank insignia is meant to be a clarification and identification thing, so even if was "another overcomplication", (which I don't agree with, if it starts on your uniform, which it always does, you won't even have to think about it 90% of the time) it's an overcomplication I wouldn't mind.

**Comment by TheDanseMacabre** [comment]
> Technically we already have both. It doesn't really matter that much to me, either way.
That's just leftovers from the 2017 invasion arc, they aren't really used anywhere.

> Rank insignia is meant to be a clarification and identification thing, so even if was "another overcomplication", (which I don't agree with, if it starts on your uniform, which it always does, you won't even have to think about it 90% of the time) it's an overcomplication I wouldn't mind.
It's an overcomplication for the mappers/coders who have to do the outfits for the ghostroles themselves (I don't mind it much, but others may not feel the same way), and if a mercenary gets a gear crate, they don't have the luxury of having their uniforms start pre-ranked.

**Comment by atteria** [comment]
As for the sprites themselves, these have large, low-contrast palettes with little visible shading. The previous sprites had this issue but these new sprites range from comparable to worse in that respect.

**Comment by Sinbest** [comment]
> As for the sprites themselves, these have large, low-contrast palettes with little visible shading. The previous sprites had this issue but these new sprites range from comparable to worse in that respect.

I'm not a spriter unfortunately, so if you're referring to the uniforms in general and not the gold/silver highlights, I can't do much about that.

**Comment by TheDanseMacabre** [comment]
Oh, side note I forgot: I'm personally not too hot on the gold accents on the junior officer uniform - I just think the colors absolutely clash in a bad way. I'd also argue the use case for the MCPO's uniform is essentially nil. Keeping silver would be better. If it is an absolute necessity that they have gold for some reason, perhaps try a mixture of silver and gold or crimson and gold?

**Comment by Sinbest** [comment]
> Oh, side note I forgot: I'm personally not too hot on the gold accents on the junior officer uniform - I just think the colors absolutely clash in a bad way.

I made the junior officer's uniform have gold accents because that's how it's done on the Army uniforms and I want them to be consistent to avoid confusion. It also doesn't clash _that_ bad.

**Review by Alberyk — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
