### PR TITLE
Zeng-hu frames can be played in security

### PR DESCRIPTION
**Pull request by hazelrat**
Per request of synthetic lore, this allows Zeng-Hu frames to be played in every role in security.

I'll toss this over to Noble in the lore discord for a look-over.

### CODE REVIEW

**Comment by NobleRow** [comment]
I am lore guy and I approve this message.

**Comment by hazelrat** [comment]
!review

**Comment by FluffyGhoster** [comment]
MD to consider if this is wanted IRT what happened with the heavy IPC frames removal from sec
I hope it makes it in, personally

**Review by FluffyGhoster — APPROVED** [review]
Also, code LGTM

**Comment by NobleRow** [comment]
> IRT what happened with the heavy IPC frames removal from sec

The main difference here between the Mobility Chassis and the Industrials is that the mechanical issues for the Mobility Chassis have been solved by giving them a speed limiter. Their speed is now much more reasonable than what it was prior.

The heavy units however probably won't have this mechanics patch until after the IPC Medical Rework, which is coming along nicely.

**Review by Geevies — APPROVED** [review]

**Pull request merged**
