### PR TITLE
Horizon Propulsion Overhaul

### PR DESCRIPTION
**Pull request by nauticall**
# About

_Sponsored by Atmosia™._

Overhauls the Horizon's propulsion systems to use engineering's new meta method of using two separate mixes, one to burn and the other for propellant. The lower line (yellow, "Burn Mix") is pumped into the combustion chamber, while the top line (black/purple, "Propellant Line") is used as the actual propellant to be expelled out the thrusters; this is pumped into the heat exchangers lining the combustion chamber.

The burn mix can then be ignited using the igniter switch (located next to the left-side computers), which superheats the propellant line using the heat exchangers. With an ideal setup this can superheat the gas all the way to 10,000K (~13,000C).

Now, this puts immense strain on the walls. Left uncheck a hot propellant mix will eventually melt the walls away and turn the propulsion room into a burning mess. As a result, atmos techs who work with this setup should probably look into venting the chamber (using the exterior blast doors) about 2 minutes after ignition. 

image

# Important Devices
**A. Burn Mixer**: An omni mixer to combine gases for combustion. Remember to max out these respective lines from the tank computers.
**B. Igniter Switch**: Triggers the igniter inside the combustion chamber to light the mixture on fire.
**C. Equalization Valve (ADVANCED)**: To be used in conjunction with the phoron line equalization valve in space. Equalizes the temperature and pressure of the phoron line with that of the propellant mix. Can be used to superheat the phoron line, allowing you to fill the other thruster bank's propellant line with it.
**D. Burn Mix to Scrubbers**: Empties the burn mix line into the scrubber network, for reuse. Can be safely used as the burn mix line itself never gets superheated (unless modified).

image

Also adds emergency evacuation valves in the corners of each thruster bank. When turned these will empty the propellant line in under 2 minutes, making it useful in case you've either A. botched a thruster setup, B. want to try something different or C. are an antagonist.

image

# How to Use
1. Determine which kind of propellant mix you'd like to use. This will usually be H2/O2 or H2/N2O, but other mixtures (like phoron for the fuel, or a combination of H2/phoron, whatever you fancy) can be used as well.
2. Max out, or at least increase the pressure, of the distribution lines for the gases you want to use.
3. Configure the gas mixer. Be sure to turn it off so you can change it.
4. Open the gas pumps into the mixer.
5. Open the pump connecting the phoron line to the propellant line.
6. Open the valve connecting the propellant line to the heat exchangers.
7. Go to the propulsion control console (lower right, mirrored on starboard side), set the pressure for the injector and open it. Wait for it to build up.
8. Go to the igniter switch (B) and hit it. This will ignite the fuel mixture and superheat the phoron line.
9. Wait about 2-3 minutes for the propellant to be heated. You're usually good to go once you hit 10,000K.
10. Close the injector line with the control console.
11. Open the exterior blast doors to vent the burn mix into space. If you keep the burn mix in the chamber, it will melt the walls.
12. Profit!

# Modification

This configuration is efficient, but not _perfect._ Experimenting atmos techs can still find many ways to tweak or add onto the mix to make propulsion either more efficient or more powerful. So go grab that pipe dispenser and work your magic.

### CODE REVIEW

**Comment by nauticall** [comment]
!review

**Comment by furrycactus** [comment]
This is a pretty based change, thank you SO much for doing this. Especially the h/e pipes. I'm so tired of doing those every round

The only things I'm worried about is that a few of these things aren't absolutely vital to function and take away a couple of extra things to do for "I'm bored and want to do a little bit of busywork", primarily the regulator that sends the unused fuel mix to recycling, and the connector and pre-wrenched canister for extra propellant line volume, or to give the Canary some terrifying 10Gm/h fuel. 

The propellant dump is also a nice addition, but set up the way it is I'm worried it's almost _too_ easy to rapidly dump all of the Horizon's thrusters, particularly because if someone walks in and turns it, it'll drain the line and potentially the entire Phoron tank if people don't catch it in time. I'm sure that can be negated if techs remember to toggle off the Phoron injection on the console if they've run a hot thrust setup, but that's not so viable for a cold setup. CO2 can be used as propellant in a pinch if there's a disaster so it's not the absolute end of the world, but it does add a kind of frightening way to rapidly dump all of the Horizon's Phoron gas. Maybe add a small wall console in the room near the valve to control the gas injector out in space, and have the injector start as inactive like the one in the combustion chamber? Then the flow rate for it can be adjusted, and Injection as a whole can be toggled, adding at least something of a backup if it's turned by someone who doesn't totally understand what they're doing.

The digital valve I'm mildly worried about, only because those can't be moved or removed with wrenches or anything since they throw an alert to staff when they're toggled, but I also understand bound synthetics can't operate regular manual valves. It's probably fine.

Sorry if this was a bit of a ramble. This change otherwise is really cool and I love it very much.

**Comment by sadkermit** [comment]
i've got mixed feelings. I discussed this with Furrycactus (alongside some other atmos nerds) who mentioned most of what I'd have said, so I can keep this short. also to make sure I wasn't just being _'waah i hate change!!!'_ lol

The lines being separated and H/Es being prelaid is a good change and highlights the 'meta strategy' currently in-use. Not my problem here.

My problem with this is it adds a lot more than what is strictly necessary to achieve that - there is a lot of fluff stuff that _'i am bored and want something to do'_: the regulator leading to scrubbing, the propellant purge line, canister filling/heating. this goes beyond changing the layout of propulsion to doing 70% of an atmos tech's job for them - I know the author plays a lot of medical, so the analogy I'll use is that this is akin to the pharmacy fridge starting with not only organ regeneratives and painkillers, but also more niche things like inacusiate and cataleptinol.

as cactus mentioned, i'm not sure if digital valves are fixed inplace, but if they can't be unwrenched and moved, that's a pretty big problem as it prevents custom propulsion setups.

one additional suggestion I'd make is moving that console in the bottom-right. pretty much everything right of the mixer is/can be used for custom setups/additions to propulsion and should be space that isn't encroached upon imo. there's still room to the left of the mixer that console can be moved to, or it could be put into one of the backrooms.

**Comment by furrycactus** [comment]
> one additional suggestion I'd make is moving that console in the bottom-right. pretty much everything right of the mixer is/can be used for custom setups/additions to propulsion, the console gets in the way of that. can it be moved to where that table is instead?

If space is a concern, those small wall-mounted consoles like the Oxygen/Nitrogen/N2O/Air mix tanks have can be used instead as well. (not to backseat-map as it were, just offering a suggestion you're MORE than welcome to ignore)

**Comment by hazelrat** [comment]
I'm very much in favour of this, it was always weird that propulsion was mapped for a configuration that essentially everyone is discouraged from using. 

With that in mind, this should be balanced with how many atmos players like to customise their propulsion setups for their own flavour. Because of that, I think pre-mapped features should be either essential, or they should be performing a function that is very irritating to replicate with in-game configuration. On that note, pretty much a full ditto to what furrycactus says about the canister and the regulator to scrubbers.

**Comment by nauticall** [comment]
image

updated

**Comment by sadkermit** [comment]
im happy with the changes so far. i trialled the setup and had a few aesthetic suggestions/nitpicks to point out, not really necessary though.

1) purely an aesthetics thing but pointing it out incase you also don't like the bendy yellow line lol, but could the yellow line remain straight going into the bottom-left corner of the burn chamber, with the 2nd H/E input/output into the chamber going under the door? wholly a preference thing.
Capture
it's not critical for all 9 tiles of the burn chamber to be covered by a H/E pipe if that was a concern.

2) the H/E junction pipes are overlayed on TOP of the wall. this looks extremely cursed, bearing in mind they will glow a bright white-blue when propulsion is hit. im not sure if there is a way around this though which is very lame.
Capture
Capture

3) this kinda looks weird. markings on the floor to denote a hazard (the igniter switch) on the wall. again, a personal preference thing i noticed when trialling the setup.
Capture

could the button just be renamed to _Ignition Switch (DANGER!)_?
Capture

**Comment by furrycactus** [comment]
Loving this very much. You rock, for real.

**Comment by nauticall** [comment]
image

image

Changed the heat exchangers around and made the burn line straight again. Much better looking _and_ still toasts the phoron nicely.

**Comment by FabianK3** [comment]
I'm very happy with those changes! It really helps to reduce repetitive work every round and looks much cleaner! ⚙🛠
So far every refactoring from the first version is also a very good improvement.

The only thing i like to poke at is: Maybe we could move the vent+scrubber to somewhere else?
I can imagine they could get in the way for possible modifications/experiments and just removing them in-round wouldn't be so nice...

Thanks for the work!

**Review by alsoandanswer — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
