### PR TITLE
Fixes Federation Skrell consular officers not spawning with their cool psi-pistol

### PR DESCRIPTION
**Pull request by Jaraci**
See title.

### CODE REVIEW

**Comment by Jaraci** [comment]
!bugfix

**Comment by Jaraci** [comment]
!review

**Comment by RustingWithYou** [comment]
This will make non-Skrell consulars spawn with the psi pistol too, which they are incapable of using. I have addressed this issue in #17708 in a way that doesn't do that.

**Comment by Jaraci** [comment]
Someone else did it better and I lost the github duel

it's over

**Pull request closed without merging**
