### PR TITLE
More Contractor Stuff

### PR DESCRIPTION
**Pull request by ParadoxSpace**
this entire thing is a wip. even this description! 🎊

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
!wip

**Comment by skull132** [comment]
Wouldn't it be wiser to PR this into my working branch on #6493 ? Otherwise I'm just going to have to remove the redundant code anyways.

**Comment by ParadoxSpace** [comment]
Not sure what's redundant here.

**Comment by skull132** [comment]
Merge master.

**Remove** the items from the loadout options.
**Add** the items to the various `/datum/outfit` classes you find in the code/game/jobs/faction folder per faction.

**Comment by skull132** [comment]
Also. Remove the contractor_security things. It's an oversight on my count.

**Pull request closed without merging**
