### PR TITLE
Removes fullblock random chance. Nerfs bicaridine and kelotane. Removes keloderm.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
It will be said of those that died before today,
All those souls killed by mercenaries,

That they were playing in easy mode

### CODE REVIEW

**Comment by Alberyk** [comment]
What the fullblock random chance has to do with chemical changes? This feels a bit unatomic.

**Comment by NonQueueingMatt** [comment]
6 AR shots to officer vest aimed at chest = 124 brute
Recovery time with bicaridine: Circa 2 minutes

**Comment by NonQueueingMatt** [comment]
> 
> 
> What the fullblock random chance has to do with chemical changes? This feels a bit unatomic.

https://forums.aurorastation.org/topic/12882-make-dying-a-thing-again/page/2/

What I wrote on this thread explains it. Essentially, this deals with the issue of people dying too slowly and chemicals being too good at saving people.

**Comment by OneOneThreeEight** [comment]
It's a little unatomic but it's actually tuned just fine. You won't take continuous damage if you have first aid applied anyway.

@NonQueueingMatt Maybe look into the metabolism rates for the aforementioned healing chemicals? The healing ones should be slowed down to a crawl t-b-h.

**Comment by OneOneThreeEight** [comment]
It's a little unatomic but it's actually tuned just fine. You won't take continuous damage if you have first aid applied anyway.

@NonQueueingMatt Maybe look into the metabolism rates for the aforementioned healing chemicals? The healing ones should be slowed down to a crawl t-b-h.

**Comment by NonQueueingMatt** [comment]
!review

**Pull request closed without merging**
