### PR TITLE
Adds the docking port management program to laptops

### PR DESCRIPTION
**Pull request by Snowy1237**
See title.

### CODE REVIEW

**Comment by Snowy1237** [comment]
!review

**Comment by Greenjoe12345** [comment]
Last I saw there is a bug with the program downloaded on other consoles
https://github.com/Aurorastation/Aurora.3/issues/16879

**Review by Arrow768 — APPROVED** [review]

**Comment by FluffyGhoster** [comment]
Update and merge master

**Comment by NonQueueingMatt** [comment]
Why is this being put on a laptop? I don't think it's a bad thing that some programs remain console-only. Especially for things that should be done by BCs, so Captains or XOs can't just walk around with a laptop and do everything by themselves. I already hate how the C&C program is on laptops.

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
see above

**Comment by Snowy1237** [comment]
> Why is this being put on a laptop? 

Because I personally found it annoying that it was only present on consoles, really.

> I don't think it's a bad thing that some programs remain console-only. Especially for things that should be done by BCs, so Captains or XOs can't just walk around with a laptop and do everything by themselves.

I did not consider this angle while making this PR, I apologize. I have absolutely no issue with this PR being closed if it is unwanted.

**Comment by NonQueueingMatt** [comment]
Closing this then.

**Pull request closed without merging**
