### PR TITLE
Adds two new scientist titles

### PR DESCRIPTION
**Pull request by Yonnimer**
Adds the titles "Explorative Chemist" and "Circuit Designer" for scientists.

### CODE REVIEW

**Comment by Yonnimer** [comment]
!review

**Comment by ParadoxSpace** [comment]
What are they exploring?

**Comment by Yonnimer** [comment]
Chemical combinations/testing them. If the title's name is unpopular I can make a new one to replace it.

**Comment by mikomyazaki** [comment]
Maybe put the new job names in the changelog?

**Comment by MarinaGryphon** [comment]
I'd suggest maybe "Exploratory Chemist" instead, as "explorative" isn't really a word.

**Comment by Yonnimer** [comment]
@MarinaGryphon I originally meant to use that, but I couldn't think of the word, thanks
@mikomyazaki Updated the changelog.

**Comment by LanceLynxx** [comment]
I really don't see the point for neither of these.

Research & Development covers both these aspects. There's already the Researcher title, why not just use that instead?

And a Circuit Designer even more pointless, because it would fall under the job description of a roboticist.

**Comment by Yonnimer** [comment]
There are plenty of scientists who focus on circuits, not just roboticists.

The point of adding the titles is to differentiate the difference between someone who focuses more on research and development and someone who focuses on chemistry, similar to phoron researcher or xenoarch.

**Comment by Yonnimer** [comment]
If the pr is conversational enough or it’s requested I can make a feedback thread

**Comment by LanceLynxx** [comment]
I am aware as I am one of the players that specializes in circuits. 

If we're going this route then we'll also need titles for every single "specialty"... 

Materials Researcher for lathe/analyzer work, Modular Specialist for modular guns and kinetic accelerators, Telephysicist for t-sci, etcetera...

**Comment by skull132** [comment]
"Circuit Designer" is a really bad name. I can't think of a gooder one though, without just going, "Electronics Engineer" or something.

**Pull request closed without merging**
