### PR TITLE
new rollerbed and vitals monitor sprites

### PR DESCRIPTION
**Pull request by alsoandanswer**
rollerbed sprite ported from bay. vitals monitor item from /tg/, modified by yours truly

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by FayeLovesU** [comment]
I do not like that the new rollerbed sprites are smaller, and thus harder to click. The current rollerbeds were specifically introduced b/c they were much easier to click and grab. These seem like a downgrade in terms of ease of use. They should be brighter and bigger.

**Comment by alsoandanswer** [comment]
> I do not like that the new rollerbed sprites are smaller, and thus harder to click. The current rollerbeds were specifically introduced b/c they were much easier to click and grab. These seem like a downgrade in terms of ease of use. They should be brighter and bigger.

There's an invisible hitbox, so it's still easy to click and drag.

**Comment by FayeLovesU** [comment]
> > I do not like that the new rollerbed sprites are smaller, and thus harder to click. The current rollerbeds were specifically introduced b/c they were much easier to click and grab. These seem like a downgrade in terms of ease of use. They should be brighter and bigger.
> 
> There's an invisible hitbox, so it's still easy to click and drag.

oh rad then

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
Does the rollerbed not have a bag strap anymore?

**Comment by alsoandanswer** [comment]
> Does the rollerbed not have a bag strap anymore?

Yes.

**Review by SleepyGemmy — COMMENTED** [review]
**general feedback:**
i don't like the new roller bed sprites. they don't look very medical-y. their main colour seems to be black and the auxiliary colour seems to be blue, which has nothing to do with medical.
as mentioned by Matt, the bag strap missing seems like an oversight.

**Review by KingOfThePing — APPROVED** [review]
I like the new sprites. Especially the hover variant. The strap missing is a quick fix. Other than that, very cool.

**Pull request merged**
