### PR TITLE
Removes kitty ears from the game.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
Title. This shit serves no purpose other than cringe and should've been removed long ago.

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Comment by XanderDox** [comment]
I wish to note that both the Admins and Devs have been complicit in cat-girl cringe, specifically allowing a staff member to have a set of custom cyborg sprites that are all a Cat Girl, including a Catgirl Surgeon and Bartender.

The Catgirl custom borg sprites should be removed too if you are removing cat ears from all players,

**Comment by NonQueueingMatt** [comment]
> 
> 
> I wish to note that both the Admins and Devs have been complicit in cat-girl cringe, specifically allowing a staff member to have a set of custom cyborg sprites that are all a Cat Girl, including a Catgirl Surgeon and Bartender.
> 
> The Catgirl custom borg sprites should be removed too if you are removing cat ears from all players,

This is not something I can do. Go bother alb about this.

**Comment by Chada-1** [comment]
It's also worth noting that the borg sprite in question is a hologram, so doesn't really play by the same rules when it comes to actual clothes/etc.

The ears being removed aren't holograms. So not really the same thing.

**Comment by Kaedwuff** [comment]
> It's also worth noting that the borg sprite in question is a hologram, so doesn't really play by the same rules when it comes to actual clothes/etc.

Veronica also doesn't really fit into the normal aesthetic for a borgs, either.  She is basically a little roomba with a holo projector on to, but interacts with the world around her as if the hologram was a solid object.  If she performs surgery, how is she reaching the top of the operating table?  Why is she able to block pathing for people who could realistically just walk over her? 

Not to mention the play in question often spelled the borg's name in all lower case with a . between each letter, which was really distracting (for me, anyway) to look at.

It was a bad gimmick for a custom sprite in the first place, and requires way too much suspension of disbelief.

**Pull request merged**
