### PR TITLE
Make ladder by the crusher accessible to anyone

### PR DESCRIPTION
**Pull request by soryy708**
Following [this](https://forums.aurorastation.org/viewtopic.php?f=18&t=11291) suggestion:

Main level cryo airlock access restrictions lifted.
Added airlock by the crusher to wall off section of maintenance, with proper access.
Surface level airlock access restrictions lifted.

* [Main level screenshot](https://i.imgur.com/d7stILB.png)
* [Surface level airlock in question](https://i.imgur.com/pKeo0GJ.png)

### CODE REVIEW

**Comment by Moonyman** [comment]
i'm not too good with reading mapping put in raw code, but why does changing access in two doors require 153 deleted lines many of which seem to be related to stuff in security areas?

**Comment by soryy708** [comment]
@Moonyman Shouldn't have anything to do with it. I blame mapmerge.

**Comment by Sindorman** [comment]
In general you do not need even mapmerge to do door changes. Open map file with any text editor - find your door in code line and change one line of code.

**Comment by soryy708** [comment]
I added a door in main maint

**Comment by skull132** [comment]
Will solve conflicts at the end of the week, as I merge master back into dev. Should be good for merge at that time as well.

**Comment by Arrow768** [comment]
The doors on the main level look cluttered.
Can you move the additional door over near the right end of the crusher ?

**Comment by skull132** [comment]
Stale and now conflicted. Please reopen once you've fixed the issues outlined.

**Pull request closed without merging**
