### PR TITLE
Qipao addition

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
Adds a Qipao for my sinophile friends

Sprite by Мяу!#0979

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!wip

**Comment by Doxxmedearly** [comment]
Needs a changelog

**Comment by TheDanseMacabre** [comment]
sorry misclick

**Comment by TheDanseMacabre** [comment]
!review

**Review by Doxxmedearly — CHANGES_REQUESTED** [review]
The qipao needs `body_parts_covered` flags, as the default is that it covers upper and lower torso, arms, and legs. Looks like this doesn't cover the arms or legs. You can either add these flags manually by adding the body_parts_covered = UPPER_TORSO|LOWER_TORSO flags. Or move this under the `/obj/item/clothing/under/dress` path since it has those flags already and this sort of fits under that category.

**Comment by Doxxmedearly** [comment]
You will probably also need to merge master into your PR to appease the CI bot.

**Review by Doxxmedearly — APPROVED** [review]

**Review by OneOneThreeEight — APPROVED** [review]

**Pull request merged**
