### PR TITLE
Re-Purposes security borgs

### PR DESCRIPTION
**Pull request by LadyFowls**
- rscadd: "Adds the ability for security borgs to do forensics, aswell as deploy energy barricades."
  - tweak: "Adds MouseDrop to gripper."
  - rscdel: "Removes security borg offensive weapons."

### CODE REVIEW

**Comment by LadyFowls** [comment]
!review

**Comment by ParadoxSpace** [comment]
This is pretty much even more pointless than the old secborg. The forensics tech has literally nothing to do on an average round to begin with, it's just shieldbot and 'borg let us in this department'

**Comment by LadyFowls** [comment]
also, This has

> This is pretty much even more pointless than the old secborg. The forensics tech has literally nothing to do on an average round to begin with, it's just shieldbot and 'borg let us in this department'

please provide feedback on how to improve this

**Comment by ParadoxSpace** [comment]
You don't, you go with my PR.
Or, /tg/ peacekeepers.

**Pull request closed without merging**
