### PR TITLE
Made Straightjackets Escapable

### PR DESCRIPTION
**Pull request by Kaedwuff**
Making straightjackets capable of being resisted out of. There is a 6 minute delay to escape, but it's possible, now.

I also modified the straightjacket sprite to actually be a straightJACKET, not a weird... full body suit thing.  That has never overly made sense to me.  You can still walk and run with it on, which you wouldn't be able to do if it was restraining your legs too.

### CODE REVIEW

**Comment by Pacmandevil** [comment]
Can you post pics of sprite changes?

**Comment by Kaedwuff** [comment]
6c94a55fa2f9ab0aaf54618e571413df
87cd749c75a4441114feb6a616b424f2

Revised sprites to look less like you're wearing undies, and also to add some dangling straps. (and edited the in-world sprite too)

**Comment by OneOneThreeEight** [comment]
Really not liking the contrast in the side sprites.

**Comment by OneOneThreeEight** [comment]
*Yikes.* One day that'll need resprited.

Tentatively supporting. It'll be a bit frustrating to deal with self-harming greytide but I suppose the solution will be to let them kill themselves at this point.

**Comment by Arrow768** [comment]
Approved by mins

**Comment by skull132** [comment]
I'm thinking.

Because 6 minutes is an ass long time, it's very possible to just press the resist button when no one's looking and then suddenly pop out of your jacket. Which is a bit lame.

Why not add, either:
* A random chance of you broadcasting a visible message along the lines of, "X is shifting in his straightjacket!".
* A notice that they're doing funky shit when examined.

**Comment by Kaedwuff** [comment]
I'm in inclined to go with an occasional chance for a message to be emoted at everyone. If there's going to be a chance it would have to be at specific points, like after 2 or 3 minutes, depending on how many chances you want them to be spotted at.

**Comment by Arrow768** [comment]
A lower chance though a prolonged period would imho be better than a chance for only two or three messages.

i.e. 5% to 10% every 15 seconds or so.
But that can always be tweaked later on.

**Comment by Kaedwuff** [comment]
I don't know... Handcuffs don't have these kind of alerts, and they have a 2 minute wait. I don't want to create a situation where people can potentially just be spamming 'I'm escaping' emotes constantly. 15 seconds is way too often, I can't see less than 30 seconds per check working, maybe with a 15% chance each time.

**Comment by Arrow768** [comment]
Well, I believe you get the point.
If someone is checked on regularly, then the escape attempt needs to be noticeable.
The exact times / chances can always be tweaked

**Pull request merged**
