### PR TITLE
Unrepentant Custodial Buff

### PR DESCRIPTION
**Pull request by feartheblackout**
See commit/changelog. If you use the dispensers to fill mop buckets or the water backpacks there isn't really enough cleaner to go around for two Janitors.

### CODE REVIEW

**Comment by feartheblackout** [comment]
!review

**Comment by alsoandanswer** [comment]
I don't think you're supposed to be using space cleaner for mop buckets, just plain water, which is practically infinite from sinks.

**Comment by feartheblackout** [comment]
> I don't think you're supposed to be using space cleaner for mop buckets, just plain water, which is practically infinite from sinks.

It's just a way of cleaning without wetting the floors, which should be fine by anyone who doesn't like the funny clown slipping mechanics.

**Comment by alsoandanswer** [comment]
I mean, if you want to pull off a gimmick like that, then just ask the chemist for more space cleaner. Wet floors are a pretty normal part of janitor gameplay.

**Pull request closed without merging**
