### PR TITLE
Adds NobleRow's New Bishop Headsprites

### PR DESCRIPTION
**Pull request by HanSolo1519**
Adds new headtypes made by NobleRow. Copies most of MattAtlas' code from #18800

image
 Selen, Sienna and Siseyo heads (and markings)

### CODE REVIEW

**Comment by HanSolo1519** [comment]
I've been informed that these were actually for bishop frame IPCs, whoops!

**Comment by HanSolo1519** [comment]
For some reason, dreamdaemon gave up on me and I keep having various issues on my end
image
the code _should_™️ work, I just can't test it at the moment.

If someone else wants to test it go ahead, it's the selen, sienna and siseyo heads (and markings) on the bishop frame

**Comment by HanSolo1519** [comment]
!review

**Review by FluffyGhoster — APPROVED** [review]
lgtm

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
