### PR TITLE
Gives Atmos Techies access to Electrical Closets + One Insul gloves per locker as well

### PR DESCRIPTION
**Pull request by Melariara**
- Grants atmospheric technicians access to the electrical lockers in engineering.
- Grants one extra pair of standard insulated gloves due to now ten people wanting them.

### CODE REVIEW

**Comment by Melariara** [comment]
!review

**Comment by Arrow768** [comment]
Not in favor of this PR.
The Access to atmos / electrical equipment is the main differentiating factor between atmos techs and engineers.
If this is removed, then there is not really a point to have two separate roles for atmos tech / engineer.

**Comment by NonQueueingMatt** [comment]
Not a fan either. What should be done instead is making atmos tech an alt title, if anything.

**Comment by NonQueueingMatt** [comment]
Closing for the above reason.

**Pull request closed without merging**
