### PR TITLE
Replaces the old station windows with new ones.

### PR DESCRIPTION
**Pull request by nerocavalier**
* libera te tutemet ex inferis

### CODE REVIEW

**Comment by nerocavalier** [comment]
!wip

**Comment by NonQueueingMatt** [comment]
One thing I don't like is that the windows don't connect to the walls. They should **really** do that, because otherwise it looks extremely awkward.

**Comment by desvenlafaxine** [comment]
> One thing I don't like is that the windows don't connect to the walls. They should **really** do that, because otherwise it looks extremely awkward.

How could it be done? If the windows were a subtype of wall, it would probably be possible, but as far as I know this can't happen the way they were coded.

**Comment by desvenlafaxine** [comment]
Actually thinking about it, maybe the window frame could be made a wall that can have glass added. No idea how hard this would be, though. @NonQueueingMatt

**Comment by NonQueueingMatt** [comment]
> 
> 
> Actually thinking about it, maybe the window frame could be made a wall that can have glass added. No idea how hard this would be, though. @NonQueueingMatt



> 
> 
> > One thing I don't like is that the windows don't connect to the walls. They should **really** do that, because otherwise it looks extremely awkward.
> 
> How could it be done? If the windows were a subtype of wall, it would probably be possible, but as far as I know this can't happen the way they were coded.

It doesn't need to be a subtype of wall. You can simply have the window frame check for possible connections once it initializes, then have a sprite for every connection. Baystation has an example of this: `structures.dm` from line 138.

**Comment by Arrow768** [comment]
Please put some pictures of that into the PR

**Comment by desvenlafaxine** [comment]
> 
> 
> > Actually thinking about it, maybe the window frame could be made a wall that can have glass added. No idea how hard this would be, though. @NonQueueingMatt
> 
> > > One thing I don't like is that the windows don't connect to the walls. They should **really** do that, because otherwise it looks extremely awkward.
> > 
> > 
> > How could it be done? If the windows were a subtype of wall, it would probably be possible, but as far as I know this can't happen the way they were coded.
> 
> It doesn't need to be a subtype of wall. You can simply have the window frame check for possible connections once it initializes, then have a sprite for every connection. Baystation has an example of this: `structures.dm` from line 138.

Okay, finally checked bay window sprites. I can't tell what's even going on because they're all monochrome, so I'm unsure which are the connections actually required. Do I just basically remove the stripped line so they look like they're continous? I'm confused.

**Pull request closed without merging**
