### PR TITLE
Further reduces the strength of Zora Soda.

### PR DESCRIPTION
**Pull request by Arrow768**
Further reduces the strength of zora soda, as its regularly abused and causes gamebreaking issues.

The PR has been created after complaints from the admins and players about the balance of the Zo'Ra Soda.
https://forums.aurorastation.org/viewtopic.php?f=21&p=105230

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
here's a less hamhanded solution
nerf it for unathi and tajara, and I personally decree this, put HOZM behind a coin.

**Comment by OneOneThreeEight** [comment]
@ParadoxSpace Nope, even humans abuse it much of the same. The difference in speed between the species due to the caffeine is barely noticeable.

**Comment by skull132** [comment]
Making the caffeine variable depend on the species should be doable via modifying the ingestion effect and making it _not_ call parent before certain modifications.

**Comment by Arrow768** [comment]
Indeed, but modifications to the drinks code are out of the scope of that pr.

**Pull request merged**
