### PR TITLE
Vault tweak/Fix

### PR DESCRIPTION
**Pull request by Eyeveri**
After witnessing a merc round, I realized two things. 
1. More turrets were needed. 
2. Motion Sensors weren't setup right. My bad. 
3. The loot needed a bit more "common" items. 
4. Double reinforced walls were a good idea. 

I also reconnect operations to maintenance with this. 
Screenshot (125)

### CODE REVIEW

**Comment by Eyeveri** [comment]
!bugfix

**Comment by Eyeveri** [comment]
!review

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
undocumented changes to security and service. refer to the diff. (branch likely created from a unupdated master.)

**Comment by Eyeveri** [comment]
> undocumented changes to security and service. refer to the diff. (branch likely created from an unupdated master.)

Weird. I'll fix this.

**Comment by Eyeveri** [comment]
Gonna have to resubmit. It isn't letting me fix the rebase thing.

**Pull request closed without merging**
