### PR TITLE
Holopad Fix

### PR DESCRIPTION
**Pull request by Geevies**
* Holopads should work now again.

### CODE REVIEW

**Comment by Geevies** [comment]
!bugfix

**Comment by Geevies** [comment]
!review

**Review by Amunak — APPROVED** [review]
I assume this will eventually be fixed properly?

**Comment by NonQueueingMatt** [comment]
I can't say I'm a fan of the solution.

**Comment by mikomyazaki** [comment]
As discussed on Discord, this is not the problem.

**Comment by mikomyazaki** [comment]
Problem is due to the `ARE_Z_CONNECTED(ZA,ZB)` macro failing in cases where `ZB > ZA` and the atlas subsystem has not fully populated its cache. It should be replaced in all cases with `AreConnectedZLevels(ZA,ZB)` which does have the proper checks.

**Review by Amunak — APPROVED** [review]

**Review by mikomyazaki — APPROVED** [review]

**Pull request merged**
