### PR TITLE
Borg Upgrades

### PR DESCRIPTION
**Pull request by Arrow768**
Adds a anti-theft mode to the borgs to prevent them from leaving NT property

### IC changelog
`NanoTrasen Borgs have been fitted with a state of the art anti-theft module`

### CODE REVIEW

**Comment by VTCobaltblood** [comment]
Don't you think self-destruct is a little too much? Why not a lockdown?

**Comment by ParadoxSpace** [comment]
Can it be disabled?

**Comment by Arrow768** [comment]
Well, it would be a pretty bad anti-theft mode if it just got locked down and someone could easily unlock it.
And yes, there are ways to prevent the borg from blowing up.

There wont be a feedback topic since this is a game design decision for the away missions.
(Which is supported by the headmins, headdevs and admins)

**Comment by VTCobaltblood** [comment]
It'd be very silly for NT to waste property because someone chose to steal it. No anti-theft measures work by literally just destroying the thing in question. These things are pretty expensive, y'know. I think that self-destruct is too shallow and lazy, and that there are other possible options - for example, locking it down in such a manner that it's unmoveable and can only be unlocked from that state by the RD?

**Comment by NiftyBaby** [comment]
This seems pretty goofy and way, way over the top.

**Comment by Pratepresidenten** [comment]
I approve. Safe or bust!

**Comment by MarinaGryphon** [comment]
How was this high priority? How did this get approved when it makes cyborgs explode? It was already brought up that this was heavy-handed and frankly silly, and now it's come to light that it was so untested that cyborgs explode when they do the one thing they *have* to do occasionally, which is recharge.

**Pull request merged**
