### PR TITLE
Resprites departmental voidsuits and ninja suit

### PR DESCRIPTION
**Pull request by kyres1**
Also fixes the syndicate voidsuit inhands. Removes Vaurca voidsuits, but keeps the engineering Vaurca suit by player request.

Full icon sets are below (with the exception of directionals on the species ninja sprites.) 

This is part of my attempt at creating an Aurora-unique set of sprites that can hopefully last for us. Care was taken into making the suits consistent with eachother and with the other voidsuit/RIG designs I've made in the past, of which now sit prettily alongside these. Uniform resprites are next on my to-do, though this was a massive undertaking on its own so I wouldn't expect that soon.

also changelog comes soon

layout
layout

### CODE REVIEW

**Comment by alsoandanswer** [comment]
medical voidsuits should have green/blue visors since purple/white is science color scheme

**Comment by NonQueueingMatt** [comment]
!review

**Comment by kyres1** [comment]
@alsoandanswer 

Medical suits now have cyan visors like the old ones

**Review by fernerr — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by Alberyk** [comment]
There is an issue with one of the dmis, do not merge until it is fixed.

**Pull request merged**
