### PR TITLE
Ports modular tablet sprites from /tg/.

### PR DESCRIPTION
**Pull request by Belsima**
image

### CODE REVIEW

**Comment by Belsima** [comment]
Note that other colors are as of now unobtainable.

**Comment by Lohikar** [comment]
I'll add code for picking the colors randomly tomorrow.

**Comment by Belsima** [comment]
I could do that if it's wanted- I was intending to at one point make a PR increasing some customization.

**Comment by skull132** [comment]
@Belsima @Lohikar you guys gonna do it here or in another PR? Cuz this one can be merged otherwise.

**Comment by Belsima** [comment]
Not here.

**Comment by Lohikar** [comment]
I don't see why not, it's a 1 line change.

**Pull request merged**
