### PR TITLE
Awaysite/Ship File Organization 

### PR DESCRIPTION
**Pull request by WickedCybs**
No longer will we suffer a billion files scattered throughout one folder.

image
thanos-infinity

### CODE REVIEW

**Comment by WickedCybs** [comment]
!dnm

**Comment by WickedCybs** [comment]
Shouldn't be merged before the weapons PR is in. It will cause a merge conflict since the maps are being moved to their new folders. This is also going to be the case for the transit PR so ideally that gets merged once the weapons are in too.

**Comment by WickedCybs** [comment]
image

Weird stuff with the new icon bot but I've tested the only sprites this touches (it moves the magstation files) and everything looks to be in order.

**Review by SleepyGemmy — COMMENTED** [review]
consider naming the folder `away_site` instead of `awaysite`.

**Comment by WickedCybs** [comment]
> consider naming the folder `away_site` instead of `awaysite`.

Sure. Will push those changes once the merge conflicts arrive for me to sort out.

**Comment by WickedCybs** [comment]
Should be all good.

**Comment by WickedCybs** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by WickedCybs** [comment]
https://www.youtube.com/watch?v=tnAoq3_6f5M

**Pull request merged**
