### PR TITLE
Captain Clothes

### PR DESCRIPTION
**Pull request by Geevies**
* Gave the Captain's uniform new sprites.

Standard:
image

Standard Female:
image

White:
image

White Beret:
image

Formal:
image

Formal \w Jacket:
image

Feedback Thread:
https://forums.aurorastation.org/topic/15161-feedback-captains-clothes/

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by KasparoVy** [comment]
Mad spiffy. Nice sprites

**Comment by NonQueueingMatt** [comment]
The white one looks extremely out of place. Blue is fine, I think.

**Review by Arrow768 — APPROVED** [review]

**Review by Chada-1 — APPROVED** [review]

**Comment by Arrow768** [comment]
Merge Conflicts still present.

**Pull request merged**
