### PR TITLE
Rev changes v2

### PR DESCRIPTION
**Pull request by Chada-1**
P. much, just made more Fellows and Contenders spawn at round start in the rev gamemode, also made the number of players required 20 instead of 10 to account for this. Hopefully this makes it harder for things to not take off.

WIll probably wait on the Command role priority thingo until I can think up a more sane way to implement it.

### CODE REVIEW

**Comment by Chada-1** [comment]
!review

**Comment by mikomyazaki** [comment]
> I also plan to make it to where each team starts with a Command member, but I don't know how. If anyone knows how to do that, I'd really appreciate your help with adding that to this PR.

This will require you to change things in /datum/game_mode/proc/post_setup(), and give the antag mode templates some lists that stores preferred roles for post-setup. Then make it seek out those people first.

**Comment by Chada-1** [comment]
> > I also plan to make it to where each team starts with a Command member, but I don't know how. If anyone knows how to do that, I'd really appreciate your help with adding that to this PR.
> 
> This will require you to change things in /datum/game_mode/proc/post_setup(), and give the antag mode templates some lists that stores preferred roles for post-setup. Then make it seek out those people first.

I'll probably hold off on that part actually until I can think up a less invasive and more simple way of implementing it, since like. 1; I have no clue what I'm doing on that front rn.
2; All of the ways I can think of doing it include a full-on masterlist or putting a line or two of code right in the antag drafting which is shared by every mode, which is probably 🙅

**Comment by mikomyazaki** [comment]
> 2; All of the ways I can think of doing it include a full-on masterlist or putting a line or two of code right in the antag drafting which is shared by every mode, which is probably ⛔

Doing this is fine. You just give every mode an empty list and make it skip that step if it is empty. Or override some empty base proc that handles it.

**Review by fernerr — APPROVED** [review]

**Pull request merged**
