### PR TITLE
Moving Travis to byond 512.1452

### PR DESCRIPTION
**Pull request by Sindorman**
512.1452 seems to compile everything *faster*. In comparsing TG compilation reduced from 3 minutes to 30 seconds. Our code from 50 seconds to 20 seconds.

### CODE REVIEW

**Comment by skull132** [comment]
Line 49 of `scripts/dm.sh` should be changed to look like this: `"$DM" $dmepath.mdme | grep -E --invert_match "^included.*\.dmm?$" | tee build_log.txt`

I thiink that'll work.

**Comment by skull132** [comment]
I wouldn't simplify this. If we have a compile error or some such which actually begins with `included` then it'll get hidden as well. Being as strict as we can is a necessity IMO. So please go back to `^included.*\.dmm?$` in the REGEX.

**Comment by skull132** [comment]
Also, rebasing this to master. Because the more jobs that are affected by it, the better.

**Comment by skull132** [comment]
or not, :ree:, apparently bad commits?

**Comment by Sindorman** [comment]
@skull132 Finished. All along problem was that we put `included` instead of `including` which was enough for regex to screw up both `\$` and `$` worked locally on mine.

**Pull request merged**
