### PR TITLE
Adding clogs to the loadout

### PR DESCRIPTION
**Pull request by TheGoret**
Yes, you can even wear socks with them.

### CODE REVIEW

**Comment by TheGoret** [comment]
!review

**Comment by alsoandanswer** [comment]
who...sprited these?

**Comment by Alberyk** [comment]
I kinda find it odd that they are nameds crocs, since it is a reference to the company that makes them.

**Comment by alsoandanswer** [comment]
yeah. rename to rubber clogs. as they should be.

**Comment by TheGoret** [comment]
fuck it, too much efforts

**Pull request closed without merging**
