### PR TITLE
Updates to the Skrell Srom/dreamscape.

### PR DESCRIPTION
**Pull request by Hunttark**
In faithful service to the Skrellian developers, the Srom has received a major overhaul/map improvement.

- Expands explorable areas
- Adds a spiral (cool!)
- Just a general remap, no fixes, just improvements.
- If you have issues, blame @RyverStyx , they requested this.

3204aa81f400124841f9fcd5d31f02f5

### CODE REVIEW

**Comment by Hunttark** [comment]
@RyverStyx

**Comment by RyverStyx** [comment]
!review

**Comment by RyverStyx** [comment]
It seems like you can't actually walk onto the grates from the spawn island. They're acting like walls.

**Comment by Hunttark** [comment]
b8eb134832eccff9cd5ca709c5b8f774

**Review by RyverStyx — APPROVED** [review]
Tested and Skrell Lore approved

**Review by Arrow768 — APPROVED** [review]

**Review by Llywelwyn — APPROVED** [review]
All works but just two thoughts:
- Don't believe it's possible to die in there without some other bug so it shouldn't be problematic, but the bonfires can set you on fire atm if you walk on them.
- The rocks around the edges make it look like the dream is surrounded by darkness because of the shadows they cast, as opposed to how it is now where you can just stare off into the space backdrop. Not sure if intended.
image

**Comment by DreamySkrell** [comment]
image
Srom as seen in game. Ignore white background - it is cause I have view size changed to 128 - command is `Change-View-Range`.

## Mapping comment/request:
In current srom, lights are dim, making the srom dark and atmospheric, dream-like. New srom in this PR has all the lights full-bright, making it look very bright, with every area being brightly lit up (ok I cannot think of any other synonyms for "bright" - you get the idea).

Current srom uses different types of lights, with different colors, as well as power and range values. So "fixing" this, and making new srom nice and dim, is just a matter of bringing the different lights types from current srom into new srom. I'm `dreamy dreamy` on the main discord, and I'm fine with being pinged for more details or etc.

**Pull request merged**
