### PR TITLE
Chemical Category Metabolism Limits

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Overview

A chemical's metabolism is based on how many other chemicals of the same type are in the system. For example, mixing Kelotane and Dermaline together will no longer form a fast acting medication, but instead, scale its metabolism based on other chemicals present in the system.

Basically, KeloDem is less effective than Dermaline, but more effective than Kelotane. It's how it should work. Again, 30u KeloDerm will heal the same amount in this PR, but it will be slower.

# WIP

Needs to be tested, and possibly balanced.

### CODE REVIEW

**Comment by BurgerLUA** [comment]
!wip

**Comment by skull132** [comment]
Just as a general note. This will have Serious Consequences:tm: attached to it. Specifically, most chemical interactions should be looked over.

And it should be done in a fashion where there still is benefit to be received from combining chemicals. Doesn't mean said benefit has to be the same as it is at present, but smart play and experimentation _should_ be rewarded.

**Comment by BurgerLUA** [comment]
How would you like to see this experimentation? I mean, I could add chemicals that affect the metabolism rate of other chemicals, or perhaps new recipes like Bicardine+.

**Comment by BurgerLUA** [comment]
Maybe at another time I will try to implement this again.

**Pull request closed without merging**
