### PR TITLE
Removes the chameleon kit from the protolathe

### PR DESCRIPTION
**Pull request by LadyFowls**
There is no ic reason why this is here nor really use for it outside of meming around

### CODE REVIEW

**Comment by LadyFowls** [comment]
!review

**Comment by furrycactus** [comment]
I like it being there honestly, it's nice to have something that's just for fun somewhere in research.

**Comment by MarinaGryphon** [comment]
It's important in maxing out the illegal tech levels, for one. Two, the holographic gun is actually very useful for circuits as it can't hurt people and doesn't need a firing pin.

**Comment by LadyFowls** [comment]
> This does an ass more than the title implies, ree.
> 
> What's the reasoning for the tech level removals? Energy relay is literally the classical way (resource gated way!) to get illegal tech going.

I was told that relays werent supposed to give illegal tech, hiowever i see the point and can fix that up

**Comment by OneOneThreeEight** [comment]
Just noting that energy glaives aren't attainable through this anymore.

**Pull request merged**
