### PR TITLE
Adds a custom security coat - Attempt at making the firesuit fireproof

### PR DESCRIPTION
**Pull request by Luthhran**
Coat I just made based on the warden jacket, recolored and shape changed. Anyone can use the sprite if they want. - I tried to make the firesuit actually fireproof as I saw an issue saying it wasn't. Tested in local and seemed to work.

### CODE REVIEW

**Comment by skull132** [comment]
A few notes:
First off, this would go into development instead of master. Master is only targeted for bugfixes.

Second, the diff on your code looks really odd. It should be a lot more smaller. Unless you use different line ending conventions...?

Third, dev frozen right now for about 1 or 2 more weeks. So it'll have to wait until the Baymerge PR is shoved through. And may run into conflicts after that.

**Comment by Alberyk** [comment]
The coat is red, and missing icon state , while our sec team is mostly based on blue. And on the top of what skull has said; it is really hard to spot any difference on what you did, besides armor, on the firesuit code.

**Comment by Luthhran** [comment]
I thought the change in the firesuit was big too, but I checked the lines and it seems to only be because one line was added or something, so everything below it moved, sorry for that. I added the 
body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|FEET|ARMS|HANDS	
and
var/suit_temp = T20C
To the firesuit, with the armor. That seemed to work pretty well when I tried it out in local.
Body_parts_covered would theoretically chose which body part the suit would cover from the fire damage, and the var/suit_temp would keep it's temperature down at 20C degrees.

Last point, sorry for the fact that I put it in the wrong branch, I'm not quite used to the way this github works here, as I was working for another server before and we just on-going projects in dev, and everything else in master. If someone wants to check at my lines again to make sure I didn't break something by accident, please do though, I wouldn't want to break the server.

**Comment by skull132** [comment]
Oke, update. Dev freeze is slowly being lifted.

I have rebased the PR to target development (which it should be, master is only for bugfixes). There's now a conflict between decals.dmi and utility.dm. It might be easier if you simply redo the changes?

**Comment by NanakoAC** [comment]
@skull132 i think your rebase thoroughly borked the PR, i cant tell how much of this is things the author actually did

**Comment by skull132** [comment]
Closed due to inactivity.

**Pull request closed without merging**
