### PR TITLE
Card holders actually hold cards

### PR DESCRIPTION
**Pull request by Doxxmedearly**
Card holders can hold cards now. Before they spawned as a deck with no cards, nor the ability to hold them (But you could shuffle the holder for some reason). It can now hold basically a single card-based item.

### CODE REVIEW

**Comment by Doxxmedearly** [comment]
!review

**Comment by Doxxmedearly** [comment]
Why did it request a review from skull what

**Comment by Alberyk** [comment]
You will have to also change the object path in worths_list.dm, line 415

**Comment by Alberyk** [comment]
Also, there is one of this item mapped in the aurora library.

**Comment by alsoandanswer** [comment]
Travis seems to be unhappy because you apparently ballsed something up with the changelog

**Pull request merged**
