### PR TITLE
Dynamic Gamemode

### PR DESCRIPTION
**Pull request by skull132**
Implements the dynamic gamemode, Aurora style.

Players are presented with 2 votes in sequence: one for intensity, one for antag types.

Intensity works as follows. It's a scale of 0 to 3, inclusive. 0 denotes extended: no antags. The rest all will dynamically compose an antagonist set. Each antagonist datum is given an intensity of their own (1 to 3), and so the algorithm will compose an antagonist template set such that the total intensity of the chosen antagonist templates is equal to the intensity of the round. If no such set can be composed, no antags are used.

Voting is also changed. It is no longer a "Winner takes all" system. Instead, antag templates are chosen through weighted selection, with the weight being the amount of votes that specific antag receiving vs the total number of antag votes issued. This means that more voted antags have a higher chance of winning, but will not always get in. This should make it so that voting is a lot more varied, as there is no benefit to hobbling a single antag type.

TODO:
- [ ] The removal of game modes as a concept is mildly untested, but it should be fine. Might need deeper review, though.
- [ ] Testing.
- [ ] Check how dynamic reacts to "start failures"
- [ ] (opt) Improve Antag Type Selection to Account for: required players, required antags, antag readies.
- [ ] (opt) Change intensity type of the antags to be based on the individual antags instead of the "antag teams"
- [ ] (opt) Add the capability to dynamically add antags during a ongoing round (as a replacement for "autotraitor")

There are other things as well. Like reworking the atrocious vote controller and making all antags into datums for more uniform inround spawning. This can be done off the back of this PR, and over time. Small victories, lads, small victories.

### CODE REVIEW

**Comment by skull132** [comment]
!review

**Review by Arrow768 — APPROVED** [review]

**Comment by Arrow768** [comment]
It would imho be useful to log the actually selected rounds via the feedback system.

**Review by Chada-1 — APPROVED** [review]

**Comment by skull132** [comment]
> It would imho be useful to log the actually selected rounds via the feedback system.

Done and added.

Also added extended requiring more than all other intensities combined to pass. Otherwise, dogpiling extended is a very real possibility that we might see.

**Comment by skull132** [comment]
Need to fix a few things tomorrow or the day after, still.

**Comment by skull132** [comment]
Removed super-majority for extended. Hidden the antag requirements. Antag selection now works. We game yet?

**Comment by skull132** [comment]
TODO: do a quick look for processing gamemodes. They won't work for now. Move processing _somewhere_?

**Comment by Yonnimer** [comment]
Told to post this here, it seems that on rounds with malf a second non-malf spawns on the same tile as the malf.

**Review by Arrow768 — APPROVED** [review]

**Comment by listerla** [comment]
I don't think Technomancer has an assigned intensity here? Though I may be misreading; I'm not well-versed in this.

**Comment by NonQueueingMatt** [comment]
Superseded by the other PR.

**Pull request closed without merging**
