### PR TITLE
individualize the window title from other servers

### PR DESCRIPTION
**Pull request by qwertyquerty**
The reasons I think this change should be made:

* It simply looks better
* Many other servers do this
* It will enable me to add Aurorastation support to [ss13rp](https://github.com/qwertyquerty/ss13rp)
* Because why not?

### CODE REVIEW

**Comment by BurgerLUA** [comment]
Screenshots pls

**Comment by qwertyquerty** [comment]
@skull132 can't you just change that after merge?

**Comment by qwertyquerty** [comment]
@skull132 I've fixed your requests

**Comment by skull132** [comment]
@qwertyquerty then why even merge your PR? 🤔 

Anyways, good work now.

**Pull request merged**
