### PR TITLE
BAPI - mapmanip extract-insert

### PR DESCRIPTION
**Pull request by DreamySkrell**
image
image
image

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!build_bapi

**Review by Arrow768 — APPROVED** [review]

**Comment by DreamySkrell** [comment]
do not merge, need to add docs and integrate the other bapi PR into this one

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by DreamySkrell** [comment]
!build_bapi

**Comment by DreamySkrell** [comment]
Was test-merged on live and worked fine. This is ready for actual merge now.

**Pull request merged**
