### PR TITLE
Remove all pets from the SCCV Horizon

### PR DESCRIPTION
**Pull request by Generalcamo**

### CODE REVIEW

**Comment by Generalcamo** [comment]
!review

**Comment by Generalcamo** [comment]
!review

**Review by SleepyGemmy — APPROVED** [review]

**Comment by Roostercat12** [comment]
This has been brought up five million times at this point and quite literally every time the consensus is reached that this is a pointless change that will not benefit the server in any way and, quite frankly, will only serve to piss people off in a situation where quite a few people are already pissed off due to other reasons.

The pets are fine, they provide occasional roleplay such as the XO letting people take care of Ian and so on, and really are not as much of a stretch lore wise as people make them out to be. This is only going to cause even more drama and to be honest, judging by the fact that the only description for the PR is that screenshot, I am willing to say that's almost the point. Causing another big shitfest so you can say you killed LRP is not good for the server, and neither is this PR.

**Comment by Greenjoe12345** [comment]
Yes, I agree the pets all being removed is a bit much

**Comment by MortalRed** [comment]
To be honest, pets have provided nothing but cheap shock when this metal deathtrap of a ship kills them. Just give them to good owners in safer locations, stop putting them through their eternal torment.
Plus then we can also remove the Laz injector from mining, which raises way too many goddamn questions just by existing.

**Comment by Roostercat12** [comment]
The fact remains that there is not really a reason to REMOVE them other than just getting to say that you removed them. It is a completely needless removal.

**Comment by zagoon** [comment]
If your characters don't care about animals I can see why you might think that, but ship pets--particularly Ian and Crusher--have been helpful RP props for my characters numerous times, especially when it comes to bonding with other crewmembers or after a stressful shift where a therapy animal might assist. Maybe Ginny, Punpun, and Ives are just kind of goofy and never see the light of day, but there's value to having real animals aboard and accessible to crew on a ship that's experiencing what is effectively a mental health crisis every other canon event.

I'd rather do something to reduce the likelihood of them becoming a "cheap shock" than see them removed entirely.

**Comment by GMR25** [comment]
I'd be more supportive if this merely removed the 'meme pets': Ginny, Ives, Chauncey, Pun Pun - But the mundane/realistic pets like Ian, Crusher and Columbo should stay.

**Pull request closed without merging**
