### PR TITLE
Fixes infestation spawns happening outside the Horizon

### LINKED ISSUE #13440: Rat event can spawn in space + don't die from low atmos
Can spawn on D2 above the Phoron/Hydrogen/CO2 tanks, probably elsewhere. Also the rats didn't die due to lack of air (ticker issue?)

### PR DESCRIPTION
**Pull request by Doxxmedearly**
Fixes #13440

The space outside the ship specified in the linked issue is a station area, and `get_random_area()` was marking it as a valid spawnpoint. Fixed that. 

The other outside areas all seem to be fine (They are not marked as station areas, so will not be chosen)

### CODE REVIEW

**Comment by Doxxmedearly** [comment]
!review

**Comment by Doxxmedearly** [comment]
!bugfix

**Review by alsoandanswer — APPROVED** [review]

**Comment by mikomyazaki** [comment]
This is more of a note to myself/maintainers - I don't expect you to do this.

This proc is *way* too map-dependent, some of these areas don't even exist on the current map. It should probably have an argument that lets it select whether it can return an exterior area, and such areas should always have a flag / specific set of base_turfs so they can be identified.

**Comment by Doxxmedearly** [comment]
!bugfix

**Comment by NonQueueingMatt** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]
I guess this works.

**Pull request merged**
