### PR TITLE
Balance - Makes Pharmacy Vending Machine Basics Free

### PR DESCRIPTION
**Pull request by HanSolo1519**
Originally backtracked on for thematic reasons, a discussion with curiourbravo made me realize the gameplay importance of bandages in the place where people drag injured people trumps the fluff of corporations squeezing money out of desperate employees.

This makes the bandages, ointments, and inap pens in the medbay lobby vendor free, as it displaced a medlocker with those in them previously, (Also moves these items to the top of the screen)

### CODE REVIEW

**Comment by HanSolo1519** [comment]
!review

**Review by DreamySkrell — APPROVED** [review]

**Comment by DreamySkrell** [comment]
image
bad changelog

**Comment by HanSolo1519** [comment]
> bad changelog

Can you explain what you'd like me to do? I believed it's correct, right doublespaces, name and deleteafter set?

**Comment by DreamySkrell** [comment]
> > bad changelog
> 
> Can you explain what you'd like me to do? I believed it's correct, right doublespaces, name and deleteafter set?

image
from `html\changelogs\__CHANGELOG_README.txt`
the key and important part is that it has a unique name that starts with your username/ckey/name/whatever
like `hansolo-pharmacy-basics-free` or something

sorry, should've explained in the first comment
ping me on discord when done and I'll approve

**Review by Geevies — APPROVED** [review]

**Pull request merged**
