### PR TITLE
Adds tricorne to loadout.

### PR DESCRIPTION
**Pull request by 1Sparky1**
Title. Edited the sprite a bit because it's very old, as well as the rather outdated name and description.

### CODE REVIEW

**Comment by 1Sparky1** [comment]
!review

**Comment by TheDanseMacabre** [comment]
I don't really understand. Why? Tricornes haven't been in use for any purpose except historical re-enactment and costume-wear for centuries in the modern day, let alone in the future. This is an item that was added during, well, the /tg/ era as a one-off joke. Why do we need it in the loadout?

**Comment by SleepyGemmy** [comment]
i agree with Danse. they don't really fit in the setting, especially not in the loadout.

**Comment by 1Sparky1** [comment]
So while I get that it's an outdated item, there are plenty of somewhat outlandish clothing items in the loadout as is (The hat selection this is part of has a few to start with), and while they don't necessarily see much use I don't personally see the harm in them being there.

That said, I did this mostly for the spriting practice, so if this is considered loadout clutter I'll close the PR.

**Pull request closed without merging**
