### PR TITLE
Mining Drone Stuff

### PR DESCRIPTION
**Pull request by Geevies**
* Mining drones now come equipped with an RFD-M, a tethering device, and a stack of purple flags.
* Mining drones can now bump against doors to open them.
* Mining drones now have external airlock access.
* You can now click-drag with the RFD-M to lay down track.
* The charge cost for robots using the RFD-M has been lowered to 200, down from 500.
* Mining drones no longer appear as a unique role on the round join menu.
* Mining drone lights are now much brighter, and illuminate in a circle around the drone.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Review by Chada-1 — APPROVED** [review]

**Comment by Solaris-Shade** [comment]
Do the cyborg rechargers refill the metal rod synthesizer too with this PR. or should I submit a bug report on it?

**Comment by Geevies** [comment]
> 
> 
> Do the cyborg rechargers refill the metal rod synthesizer too with this PR. or should I submit a bug report on it?

image

it recharges synths yeah, no bug report needed

**Review by Alberyk — CHANGES_REQUESTED** [review]
No mining drones at round start. Mining already has a lot of things, if they want drones, they can buy them from the point machine.

**Review by Alberyk — APPROVED** [review]

**Comment by Chada-1** [comment]
I would love it tho if you made existing mining drones that spawn by RNG able to be pinged and enabled by Ghosts @Geevies There's a lot of times that a non-active drone just sits on a rack never discovered when it'd make total sense for it to activate itself and carry on with normal mining procedures, wouldn't happen every round but would be a treat when it did.

**Pull request merged**
