### PR TITLE
Real Time

### PR DESCRIPTION
**Pull request by 1Sparky1**
Suggested [here](https://forums.aurorastation.org/topic/11546-qol-suggestion-make-station-time-consistent-across-rounds-titled-edited/?do=findComment&comment=110743). Makes station time the same as Galactic Standard Time in-game (Central Standard Time in real life.)

- tweak: "Station time is now based of Galactic Standard Time (CST IRL)."
- rscdel: "Removed automated nightlighting. Nightlighting can still be enabled via the lighting control program, and via individual APCs."

### CODE REVIEW

**Comment by 1Sparky1** [comment]
!review

**Comment by skull132** [comment]
I've considered this in the past, but opted against this.

Because we have active daylight scheduling, it seems like a bad idea to force one half of the playerbase "into the darkness" by default.

**Comment by skull132** [comment]
Also, realistically I think the VM uses zulu time :P So it'd be UTC+0 that gets set as the standard, not CST.

**Comment by alsoandanswer** [comment]
Agree with Skull. This also means some people will have PERPETUAL night lighting, and that sucks bawls.

**Comment by 1Sparky1** [comment]
> I've considered this in the past, but opted against this.
> 
> Because we have active daylight scheduling, it seems like a bad idea to force one half of the playerbase "into the darkness" by default.

I hadn't considered this, but wonder if perhaps removing night lighting at the same time would be a better idea. Imho, I don't feel a whole lot is gained from having the lights dim in the evening. If anything, it often causes more issues, as Diona (and I may be misremembering this) need light to survive (So ICly, why would NT endanger their employees like that.)

While the issues this overcomes are easily hand waved, it does feel odd to reference events from an earlier canon round which, according to the station time, will happen in the future. Combined with the fact that people IRL don't generally work the sort of funky hours Aurora characters do. As I said, easily hand waved, but worth considering the trade-off perhaps?

**Comment by 1Sparky1** [comment]
> Also, realistically I think the VM uses zulu time :P So it'd be UTC+0 that gets set as the standard, not CST.

This could be easily changed, so I guess if you agree with my above comment, I can just confirm with the lore team.

**Comment by skull132** [comment]
This has received "I likey" from Kyres.

But as discussed above, a few changes have to be made:
- remove the automatic setting of the day-night cycle. Leave the buttons in for the AI and captain to toggle at will, tho, it's nice to have.
- add a timezone offset (in hours) configuration option, since the server's timezone may not match that of CST.

**Review by skull132 — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
