### PR TITLE
Fixes sweaters

### PR DESCRIPTION
**Pull request by shedya**
Sweater sprites were previously not recolored correctly due to being grey instead of white. This will fix this and allow people to pick brighter colors for sweaters than before (including white, finally).

### CODE REVIEW

**Comment by BurgerLUA** [comment]
Can we get a screenshot of the new tie sprite?

**Comment by shedya** [comment]
Sure
Colored #ffffff, jeans underneath:
image
Colored #ff0000:
image
Previously, it would give you this with the same colors selected:
image
image

**Comment by shedya** [comment]
!review

**Comment by BurgerLUA** [comment]
Use DMImerge to fix the conflicts and I will give an approval.

**Comment by shedya** [comment]
will reopen later

**Pull request closed without merging**
