### PR TITLE
Roof Solars Wiring Fix

### LINKED ISSUE #4311: Wiring to the Surface Level's roof does not line up, surface level solar maintenance not powered.
The Surface Solar Maintenance, the one above the cargo bay, never connects to the powernet. I followed the cables and removed the lattice on the south end of the roof where the cable turns down. Looking down I saw a steel wall below me. I went to the surface level and verified by moving up and down with a jetpack that the wire turns down into an exterior steel wall.

EDIT: Additionally, where the red main line runs past the yellow solar line just outside of the maintenance room, the two wires are actually registering as connected. So if the solars are online they will provide power straight into the main line in addition to just going to their SMES.

### PR DESCRIPTION
**Pull request by flimango**
Fixes roof solars wiring, as pictured, so that they don't transfer power between grids. Fixes #4311

### CODE REVIEW

**Comment by flimango** [comment]
This will hopefully also solve the bugged power cables, though I am not entirely sure what is causing that.

**Comment by flimango** [comment]
It's triggering on this.



I have messed with it a bit. We'll see if it's some other issue.

**Comment by flimango** [comment]
It appears that the cable used in the current wiring has the wrong sprite and faces UP-DOWN, despite appearing LEFT-RIGHT. I replaced it with the proper one. It encountered no issue until I changed it because they didn't overlap, but instead connected, however I noted that they didn't transfer power on live. This explains that.

**Comment by flimango** [comment]
!review

**Comment by skull132** [comment]
DNM this until after August update.

**Comment by Spoopy11** [comment]
I think we could possibly fix this in a better way, that red cable only feeds that single APC and takes power from the smes if it's ever activated. 

It might be better to remove it entirely, and instead perhaps move the cable inside, eliminating the strange windows further south?

**Comment by flimango** [comment]
That’s the solars grid SMES. It feeds to the main grid, which is why it’s laid out that way. It only charges from the solar array, and then outputs to main. The APC is also on main, like with every other one.

**Comment by flimango** [comment]
Going to handle this in a newer, better PR.

**Pull request closed without merging**
