### PR TITLE
Unapologetic Jacket/Coat Buffs

### LINKED ISSUE #10447: Red designer jacket sprites are reversed
The object sprite for the jacket uses the open version when the jacket is buttoned and the closed version when the jacket is unbuttoned.  The actual sprites on the mob are correct, however.
I don't know if this is true of the other designer jackets.

### PR DESCRIPTION
**Pull request by ChevyChevron**
Fixes the obj sprites for the red designer jacket (used the buttoned icon for the unbuttoned state and vice versa) and the Dominian noble coat 5.  Fixes #10447 and also another problem I found while fixing that one.

### CODE REVIEW

**Comment by ChevyChevron** [comment]
!review required

**Review by flpfs — APPROVED** [review]
adds files via upload

**Comment by ChevyChevron** [comment]
image
Anyway, I forgot to actually test this so I'm going to go do that.  Theoretically it should be fine since it changes exactly one file, but mak siccar and all that.

**Comment by ChevyChevron** [comment]
Update: It works and also I think Dominian Noble Coat 5 is an unused asset and thus didn't need fixing.  Wild.

**Comment by alsoandanswer** [comment]
Don't forget to add your changelog. It's in your Aurora.3/html/changelogs folder.

Copypaste example.yml, and edit that accordingly.

**Comment by alsoandanswer** [comment]
Technically, this is a bugfix, so be sure to use !bugfix

**Comment by ChevyChevron** [comment]
Hooray, my changelog worked.  With the help of the various people who've advised me on this process, I am steadily becoming less braindead.  Soon I will become too powerful.

**Review by Geevies — APPROVED** [review]

**Comment by Geevies** [comment]
adds files via upload

**Pull request merged**
