### PR TITLE
Psych Disposals Swap

### PR DESCRIPTION
**Pull request by KingOfThePing**
Replaces the disposals system in the psych office with a small one, in which you cant jump in, per player request.

### CODE REVIEW

**Comment by KingOfThePing** [comment]
!review

**Comment by desvenlafaxine** [comment]
The whole idea was a cheeky joke that the psych could just toss out undesired patients. Kyres made it very clear from his map design.

**Comment by KingOfThePing** [comment]
And you want to tell me what exactly with that? If it is a problem, that psych patients regularly jump down disposals (as it seems like, as per the player who requested this) then it has to be swapped.

**Review by SleepyGemmy — APPROVED** [review]

**Comment by KingOfThePing** [comment]
Closed, since I was told that https://github.com/Aurorastation/Aurora.3/pull/15022 will already adress this.

**Comment by sheeplets** [comment]
> Closed, since I was told that #15022 will already adress this.
walter

**Pull request closed without merging**
