### PR TITLE
Removes the adult section of the library

### LINKED ISSUE #11088: Scientists do not have access to the Crematorium in the Sub-Level
https://gyazo.com/c8a679abc78813d5feb7334a980e235c

Can't hit the button without an "access denied".

### PR DESCRIPTION
**Pull request by fernerr**
At administrative request, the space is now instead a reading room with a fiction bookcase.
Also Fixes #11088

### CODE REVIEW

**Comment by fernerr** [comment]
!review

**Review by Geevies — APPROVED** [review]
a large price to pay for salvation

**Review by Doxxmedearly — APPROVED** [review]
Approving my own creative death.... The world was not ready for Wynter Steele's art to be so freely accessible.

**Comment by alsoandanswer** [comment]
no...

**Pull request merged**
