### PR TITLE
mmi naming

### PR DESCRIPTION
**Pull request by Geevies**
borgs brains will now be their name
it just works
no more SHTHT-439 when you die as a borg
woo

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by Chada-1** [comment]
Thank you v. much, this will make roleplaying as a specific posi/etc much easier 👀

**Comment by NonQueueingMatt** [comment]
Correct me if I'm wrong, but wouldn't this mean that MMIs coming out of a destroyed or gibbed borg have the borg's name?

**Comment by Geevies** [comment]
yeah, it would have what it is, followed by the borg's name
for instance:

Man-Machine Interface [DONGGOBBLER.EXE]

**Pull request merged**
