### PR TITLE
A few new device sprites

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
All ported from Polaris.

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Comment by listerla** [comment]
The sprite for the health analyzer here is only slightly different from the in-use sprite for the vitals monitor. That aside, all looks good.

**Comment by SleepyGemmy** [comment]
here is the spritesheet since icondiffbot is dead.
image

**Comment by Zelmana** [comment]
Holowarrant needs a recolor from secred to secblue

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
what zelm said.

**Comment by TheDanseMacabre** [comment]
>Holowarrant needs a recolor from secred to secblue

The current warrant projector is red. I think it's fine.

**Review by NonQueueingMatt — APPROVED** [review]

**Review by SleepyGemmy — APPROVED** [review]
fair enough.

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
