### PR TITLE
Removes fuel cell augment

### PR DESCRIPTION
**Pull request by Generalcamo**
The fuel cell augment is an extremely weird augment, which allows you to drink Hydrazine or Welding Fuel and gain nutrition instead of getting toxin damage. Not only does this not make sense if you think about it (how is the liquid getting into the fuel cell while ensuring that no other liquid gets into it?), but it opens up other questions in the lore. Honestly flavor wise, this augment is bizarre, and really only used so you can bypass the chef by freaking out your co-workers while you drink welding fuel. It doesn't fit the setting of our server, and that's why I'm making this PR.

### CODE REVIEW

**Comment by Generalcamo** [comment]
!review

**Comment by githubuser4141** [comment]
Could change the flavor text so it's pouring the fuel into a specialized port maybe? Otherwise it's probably a filter somewhere in the esophagus (and you can havewave burning the mouth/throat by saying it's skin-friendly fuel because it's 500 years in the future.)

**Review by Alberyk — CHANGES_REQUESTED** [review]
Something wack is happening with the dme file.

**Comment by NonQueueingMatt** [comment]
Unwanted, and abandoned.

**Pull request closed without merging**
