### PR TITLE
Fixes warding sphere sheath animation

### PR DESCRIPTION
**Pull request by listerla**
No longer juts downwards randomly.

Closes https://github.com/Aurorastation/Aurora.3/issues/12792.

### CODE REVIEW

**Comment by listerla** [comment]
!review

**Comment by listerla** [comment]
!bugfix

**Comment by FayeLovesU** [comment]
I honestly though it was quite cool to see the Warding Sphere 'float' like it did in tthe animation. Made it a bit spookier. Would be sad to see it removed.

**Comment by listerla** [comment]
This isn't floating, nor is it the warding sphere. It's the sheath abruptly jutting 5 pixels down for 6 frames then returning to the original place for 300.

**Comment by FayeLovesU** [comment]
> This isn't floating, nor is it the warding sphere. It's the sheath abruptly jutting 5 pixels down for 6 frames then returning to the original place for 300.

I am aware of this. It looked to me that the sheathe was floating, and I rather liked it.

**Comment by NonQueueingMatt** [comment]
It does look a bit janky to me, admittedly.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
