### PR TITLE
A Star Reborn: Mining Vendor Changes

### PR DESCRIPTION
**Pull request by Geevies**
* Removed cash and lottery tickets from the mining vendors.
* Added 5 deployable ladders and 5 deployable hoist kits to the mining vendor for 200 mining points each.

### CODE REVIEW

**Comment by AmoryBlaine** [comment]
Ew, give them a better name. Scrips works.

**Comment by sheeplets** [comment]
Oh god oh fuck not my GBP please Geeves

**Comment by Geevies** [comment]
!review

**Comment by MarinaGryphon** [comment]
Why remove cash and lottery tickets? Miners should be rewarded for being productive. Just make it more expensive.

**Comment by skull132** [comment]
Maybe make the money be a hackable item? Same for loto tickets.

**Comment by alsoandanswer** [comment]
Technically, it's a mining equipment vendor. So it's dumb to... put money in a mining equipment machine.

**Pull request merged**
