### PR TITLE
Fixes Bugged Modular Laser Component Sprites

### LINKED ISSUE #13575: Capacitor sprite not displayed
Checklist before you submit an issue! Feel free to partially or fully delete this in your eventual report.
* Do a quick key word search of the git for duplicate reports. If you find any, simply post a reply onto that issue instead!
* Please be specific in your description of the issue. Explain the desired result (what should be happening) and the actual result (what is happening). Simply stating that [something happens] is not very helpful at describing what's wrong.
* Have you tried reproducing the issue? If yes, steps to reproduce it would help immensely!
* All additional details help. Such as round ID, an admin you talked to if the issue required immediate fixing, etcetera, etcetera.

Earlier today someone mentioned that the capacitors in science were not showing an image when printed from the protolathe. I mentioned it had happened to myself, and another player mentioned it had happened to them as well. I was asked to submit a report so here it is. I've attached three images below showing what we're seeing. According to players on the discord capacitors _should_ have an image.
Missing capacitor image
Missing capacitor image2
Missing capacitor image3

### PR DESCRIPTION
**Pull request by SleepyGemmy**
title. fixes a couple of bugged modular laser component sprites. fixes #13575.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Comment by SleepyGemmy** [comment]
!bugfix

**Comment by mikomyazaki** [comment]
Do the same for the base type `/obj/item/laser_components` aswell and remove the var entirely.

**Review by Alberyk — APPROVED** [review]

**Review by mikomyazaki — CHANGES_REQUESTED** [review]
Do the same for the base type /obj/item/laser_components aswell and remove the var entirely.

**Comment by SleepyGemmy** [comment]
dnm until tomorrow so i can fix miyazaki's comment.

**Review by mikomyazaki — APPROVED** [review]

**Pull request merged**
