### PR TITLE
Clicky pens

### PR DESCRIPTION
**Pull request by TehFlaminTaco**
Pens can now be clicked. From [This Suggestion](https://forums.aurorastation.org/topic/9390-activate-pens-for-click/)

### IC changelog
All station pens have had clickers installed to increase productivity.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
personally i would add a slightly different sprite for clicked and unclicked but this is ok

**Comment by Arrow768** [comment]
Indeed, it would be pretty nice to have slightly different sprites and maybe toggle a writing state when clicked

**Comment by TehFlaminTaco** [comment]
Based on the actual suggestion post, I opted to avoid multiple states.

**Comment by smallgreenant** [comment]
Note that there are multiple dependent on 'pens' that now click such as crayons and chalk.

**Pull request merged**
