### PR TITLE
Better logging

### PR DESCRIPTION
**Pull request by FluffyGhoster**
This PR implements a better logging infrastructure/module/system.

What this PR **does do**:

- Port in large extents the TG's logging **infrastructure** to our codebase
- Update the existing logging configuration so it can be tuned at runtime for debugging and testing purposes
- Split the various logs in dedicated, configurable files, grouped in round-id folders
- Make the structure a little more sane
- Add some helper macros
- Add the ability to turn on debugging and print to console the logs, and turn it off/back to files, **for dev usage only, not production, unless things really went very bad**
- Unwrap variables at runtime logging

What this PR **does NOT do**:

- Add the most sane logging function for every possible scenario in every possible module/file
- Avoid the already present six quintillions `send_gelf_log` calls that spawn a thread each
- Consolidate the gelf logging
- Adapt the preexisting, esoteric log function calls with multiple parameters to something more sane
- Add additional logging points in the preexisting modules
- Ensure the success of your relationship, that you will have a heir or anything else not stated in the above section

This will likely need an extensive review, some brainstorming sessions and a lot of blood, but it will hopefully make future development/troubleshooting/admining better.

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!wip

**Comment by FluffyGhoster** [comment]
An example of the log outputs as of now, with all units enabled during startup via the ingame verb:
[cnd-b5IL.zip](https://github.com/Aurorastation/Aurora.3/files/11178971/cnd-b5IL.zip)

**Comment by FluffyGhoster** [comment]
it has all the major pieces, so !review

**Review by Arrow768 — CHANGES_REQUESTED** [review]
There are a few things that I noticed while checking this out:

* It looks like the tgui logging is writing into a improper file.
* It looks like the there are still some left overs from the old "href" logging. (i.e. /client/proc/toggle_log_hrefs)
  *  That should be removed and fully integrated into the new log system
* It seems that some logging configurations are missing from the config.txt
  * That should be added to the example config.txt
  * It might be easier/more useful to just use a json file to store the logging config

**Comment by FluffyGhoster** [comment]
> There are a few things that I noticed while checking this out:
> 
> * It looks like the tgui logging is writing into a improper file.
> * It looks like the there are still some left overs from the old "href" logging. (i.e. /client/proc/toggle_log_hrefs)
>   
>   * That should be removed and fully integrated into the new log system
> * It seems that some logging configurations are missing from the config.txt
>   
>   * That should be added to the example config.txt
>   * It might be easier/more useful to just use a json file to store the logging config

Should be all done

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
