### PR TITLE
Borg hyposprays can now inject people in spacesuits

### LINKED ISSUE #10462: Borg hypospray doesn't work through void-/hardsuits
This is a huge problem, since in this case rescue and medical borgs can't administer medicine and stabilize people who are wearing void/hardsuits or in EVA. With brainmed on, it became extremely important to stabilize people as soon as possible or they die before they even see the inside of the medbay. Syringes work through suits, but borgs medicine synthesizer works through the hypospray so it needs work through suits also.

### PR DESCRIPTION
**Pull request by mikomyazaki**
Fixes #10462

Borg Hyposprays now inherit the behavior of hyposprays, they do not need to be a separate type. This means they are not instant and can inject people in spacesuits.

I have (begrudgingly) decided that syringes should stay separate from hyposprays, and so left them alone.

### CODE REVIEW

**Comment by mikomyazaki** [comment]
!bugfix

**Comment by mikomyazaki** [comment]
!review

**Review by Chada-1 — APPROVED** [review]
Thank you sooooo much Mya for finally fixing this... It's been a problem for a veery long time. 👀

**Comment by Amunak** [comment]
> I have (begrudgingly) decided that syringes should stay separate from hyposprays, and so left them alone.

Good decision, I tried to merge it and after 2 hours just wanted to end the suffering in any way.

**Review by Amunak — APPROVED** [review]

**Review by Doxxmedearly — APPROVED** [review]

**Pull request merged**
