### PR TITLE
Ruining Vaurca Christmas

### PR DESCRIPTION
**Pull request by Doxxmedearly**
Removed the k'ois delivery pods as an option for the christmas gifts. Thanks for the memes, oldcode.

### CODE REVIEW

**Comment by Doxxmedearly** [comment]
!review

**Comment by runecap** [comment]
Could you remove Sedantis Rock, Zo'ra Armor, and Puzzleboxes from it too. They're too rare to appear willy-nilly in some dumb company gimmick.

**Comment by Doxxmedearly** [comment]
How many horrible vaurca memes exist in these

**Comment by Geevies** [comment]
!bugfix

**Comment by Geevies** [comment]
These items are an oversight, not meant to be here, downright hazardous. Important to remove ASAP.

**Pull request merged**
