### PR TITLE
Kitchen, Bar, Chapel, Library, and Hydroponics Map Overhaul

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Overview
Massively modifies all locations mentioned in the title to be significantly more optimized and pleasing to the eye.

Screenshots: https://imgur.com/a/N6siVJy

### CODE REVIEW

**Comment by BurgerLUA** [comment]
!wip

**Comment by BurgerLUA** [comment]
I had to manually do a mapmerge because it wasn't loading the map created by mapmerger.

**Comment by BurgerLUA** [comment]
Mapmerge didn't work, AGAIN, so I had to manually copy-paste everything over.

I also re-added main level cryo, but moved it somewhere else. https://i.imgur.com/77ZqgKu.png

**Comment by BurgerLUA** [comment]
!review

**Comment by BurgerLUA** [comment]
Its pretty much done, I just need to go through it with a fine comb.

**Comment by BurgerLUA** [comment]
This is done.

Images of new cryo: https://i.imgur.com/CrPJym7.png

**Comment by sheeplets** [comment]
That side window is massive, I think you're seriously overestimating how much traffic the kitchen gets. I also don't see shutter controls anymore, is that intentional or am I just reading the screenshots wrong? If those go away there won't be anything protecting the chefs from traitors, stray bullets, and miners.

**Comment by BurgerLUA** [comment]
@sheeplets People told me that they wanted the kitchen counter to be larger, so it was made as large as it could.

The shutter controls are at the top in the finished product.

Stray bullets aren't an issue in this design since it's not perpendicular to the hallway.

**Comment by sheeplets** [comment]
@BurgerLUA 
I know because I was one of them. The side window we had before your first rework was big enough, we don't need the entire hallway. All you'd need to do is make the two outermost tables into walls. One at the top and another at the bottom.

**Comment by Arrow768** [comment]
Please remove the double wall at the bottom of the bar.
And verify that you have holopads / newscasters / camera coverage. / intercoms in place

**Comment by BurgerLUA** [comment]
https://i.imgur.com/aO0IBa0.png

Double wall was already gone because it only existed because of the cargo update I did.

Forgot to add cameras, doing that now.

**Comment by BurgerLUA** [comment]
Done

**Comment by BurgerLUA** [comment]
Just a reminder for those who weren't in devchat, this needs to be merged last because of keylength issues. Please do me a huge favor and approve all the mapping related PRs ASAP so I can work on this early and not have to do anything last minute.

**Comment by BurgerLUA** [comment]
Ready to be merged.

**Pull request merged**
