### PR TITLE
Cyclops Ship Tweaks & Fixes

### PR DESCRIPTION
**Pull request by RustingWithYou**
Makes several tweaks to the Cyclops Mining Vessel added in #16738 to make it more functional. 

- Replaces the generic suit cyclers with mining cyclers, and sets them to Hephaestus access.
- Fixes access on lockers, vending machines, APCs and air alarms, as well as changing the latter two to make them look better with 3/4.
- Fixes piping and general atmospheric issues on the ship.
- Adds k'ois to the kitchen for Vaurca, and fixes the ghostroles so that joining as a Vaurca won't immediately fucking kill you.
- Allows Vaurca Bulwarks in the mining crew, and restricts Vaurca Warriors to the security role instead.
- Expands the list of sectors to include Uueoa-Esa and Burszia.

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Comment by DreamySkrell** [comment]
image

Since you are already touching this map, it would be very nice if you added more navpoints to this ship, on the exterior. Currently it only has `1` on the east side, but ideally it should have at least the one on the other west side.

**Comment by DreamySkrell** [comment]
image

Also a very small change, this area only needs to fit the shuttle, it doesn't have to be so huge.

**Comment by furrycactus** [comment]
Another thing I noticed, it would be a good idea to provide access to insulated gloves for Tajara and Unathi as well for the Engineer role.

**Review by NonQueueingMatt — APPROVED** [review]

**Review by furrycactus — APPROVED** [review]

**Review by FluffyGhoster — APPROVED** [review]

**Comment by lavillastrangiato** [comment]
this would fix #17282, #17298, and #17379 for future reference

**Pull request merged**
