### PR TITLE
Fixes a few errors in the contributing file

### PR DESCRIPTION
**Pull request by printer16**
Formats the spans right and gives the proper replacement for non-bold \red. "" in spans causes issues and warning is not a replacement for red.

### CODE REVIEW

**Comment by skull132** [comment]
Both `alert` and `warning` exist, actually. And the difference is this:
```
.alert					{color: #ff0000;}
.warning				{color: #ff0000; font-style: italic;}
```

One is italic, the other is not. In general use, there are three levels of feedback. `notice`, which is neutral info, `warning`, which is the middle ground and is classically italicized, and `danger`, which is bold.

**Comment by printer16** [comment]
Updated to include warning.

**Comment by skull132** [comment]
Leaving as feedback required.

I personally would rather not allow `alert` as a span. The current system that already applies to 80% of the cases should remain consistent in the 3 levels of feedback, IMO. There's no need to muddle the waters with `alert` ontop of `warning`. What do the other devs think?

**Comment by printer16** [comment]
Reverted the addition of alert. Now it just changes " to '.

**Pull request merged**
