### PR TITLE
Adding Hijab's, a variant of the robe, and alien ninja-suits

### PR DESCRIPTION
**Pull request by Fire-and-Glory**
Just adding contained sprites and code for Hijab's and a differently sprited and described variant of the robe Jackboot really liked a while back.

Hijabs (probably) came from Bay, thanks to Alberyk for handing off the robe sprites months ago.

Nanako told me it'd be a good idea to put both the variant and the original robe sprites into their own contained sprites, but I'd probably need to mess with custom-loadout for that and Alberyk already has a PR for that, so, yeah.

EDIT:Also alien ninja suit sprites, yay.

### CODE REVIEW

**Comment by Alberyk** [comment]
Add those to the custom loadout?

**Comment by Fire-and-Glory** [comment]
Your own PR is already updating the custom-loadout list so I need to wait for it to go away first.

**Comment by skull132** [comment]
@Fire-and-Glory You're good to add it there.

**Comment by Fire-and-Glory** [comment]
Done adding things now.

**Pull request merged**
