### PR TITLE
Bigger Explosive Implants

### PR DESCRIPTION
**Pull request by Kaedwuff**
Due to how pathetic the explosive implants are when you actually set them to 'full explosion' I have tweaked them to actually pack a punch instead of just killing the person exploded and making people nearby get some blood on them.

What this means:
I have created a new proc for use in this. The full explosion now uses a variant of iterative explosions that has slightly more precision.

Also, it has a variable strength, discouraging people from using it as anything more than a last ditch attack, because it's not reliably dangerous, just potentially. It's also very unlikely to kill, but it can hurt a lot. After 10 tests of experiencing a point-blank explosion, only once did it deal enough damage to floor me to the point of not being able to stand, but it does cause a lot of scary station damage.

Since it uses iterative explosion method, too, the STRENGTH of the explosion doesn't actually directly relate to how much damage people nearby take. More power means they're more likely to take more damage, but there's a strong element of RNG.

https://forums.aurorastation.org/viewtopic.php?f=21&t=12269 Feedback thread

### CODE REVIEW

**Comment by BurgerLUA** [comment]
I have nothing against you but I feel that this will need a feedback thread for it. I'm About 25% sure that the explosive implant used to be really insane but it was horribly misused. I'm not too much of a fan of giving an explosive implant to traitors that causes 3, let alone 1, total devastation.

**Comment by Kaedwuff** [comment]
Fair point.  Feedback thread has been created.

**Comment by OneOneThreeEight** [comment]
3 devastation (which is a radius of 3, ergo it is 5x5 range) is the average amount that a toxins bomb will have. Devastation being at 2 would be far preferable, requiring someone to be at almost point-blank range to be reasonably killed. The difference between 3x3 vs 5x5 lethality range is quite immense.

**Comment by Kaedwuff** [comment]
That works fine then because I set Devastation range at 2. Not 3. Read the actual code and look at the picture that I made.

**Comment by BurgerLUA** [comment]
It looked like 3 because it still totally destroyed titles at the 3rd range.

**Comment by Arrow768** [comment]
You need to fix the travis error (You modified the example changelog)

**Comment by Kaedwuff** [comment]
Okay I don't really understand how I changed the example file.  It looks the same both ways to me.  How do I fix this?

**Comment by OneOneThreeEight** [comment]
You usually just leave the example.yml file alone, then make a new file with "Xpatch.yml" as the header, while in the same folder, then copypaste the contents of example.yml into the new file.

**Comment by Kaedwuff** [comment]
With help from Lohikar, I have created a new proc for use in this.  The full explosion now uses a variant of iterative explosions that has slightly more precision.

Also, it has a variable strength, discouraging people from using it as anything more than a last ditch, because it's not reliably dangerous, just potentially.

**Comment by Kaedwuff** [comment]
You know you could just ask me to reopen it instead of making #6005.  I sort of assumed since it had been sitting for two months it wasn't going anywhere.

**Comment by Arrow768** [comment]
Well, after your post on the forums it was pretty clear to me that you didnt have any interest in further working on your PRs (given that all your open PRs were closed after that post)

Also, as you never marked your PR as review required it never got a review

**Comment by Kaedwuff** [comment]
I wasn't aware I needed to manually mark it.

I've sort of gotten over rage fit I have that day, but I'm still going to probably take a break from any kind of serious coding. As far as I'm aware this code was finished though so I don't know what I would need to change.

!review

**Comment by dragoslava** [comment]
> I wasn't aware I needed to manually mark it.
> 
> I've sort of gotten over rage fit I had that day, but I'm still going to probably take a break from any kind of serious coding. As far as I'm aware this code was finished though so I don't know what I would need to change.
> 
> !review
> 
> Also, I wasn't so much annoyed that you reopened my PR as that you wrote it down as your work in the changelog after literally copy pasting my stuff.
> 
> pla·gia·rism
> Dictionary result for plagiarism
> /ˈplājəˌrizəm/
> noun
> noun: plagiarism; plural noun: plagiarisms
> 
> the practice of taking someone else's work or ideas and passing them off as one's own.

Please don't edit your msg that has review in it, it causes spam

**Comment by Arrow768** [comment]
5 edits and 5 discord pings later, because you always included the review command.

If you would like to discuss it, feel free to ping me on discord.

- The original PR has been linked in my PR.
- You forum topic has been linked in my PR.

Weather or not you should be in the changelog as PR author is up for discussion as you abandoned your original PR. However, the source is clearly mentioned in the PR.
And if the source is clearly mentioned and quoted, it is not plagiarism

**Comment by Kaedwuff** [comment]
Apologies, I'm not very familiar with GitHub. Removed the offending ping-causer.

**Comment by Sindorman** [comment]
Technically under any GNU or AGPL license of open source any form of copy/paste or code use/borrowing is legal and legit. That'ss up to a person to decide to give credit or not. Although I would give credit if you just asked.

**Pull request merged**
