### PR TITLE
Fixes lazarus injectors.

### LINKED ISSUE #9167: Lazarus Injectors set animals revived to neutral
After some testing and question admins about vars and such, I've learned that lazarus injectors, the items that mining can buy and are used to revive dead animals, set said animal to the "neutral" faction. 
While this *sounds* fine, it actually causes a pretty big problem; If said animal sees a player, like a traitor, who are set to another faction, they instantly go berserk and start attacking everyone, even the person that revived them, with no way to calm them down short of killing them and reviving them again.

This might be alright if it only did it with normally hostile critters, like giant spiders or carp, but it does it with *any* creature revived by it, so if you, say, revive Ian or a cat or something, they will go nuts and attack people, even though they are meant to be completely passive critters.

This also results in a meta-based problem, where you can kill a mouse or something, revive it, and see who it attacks. Whoever it attacks is likely to be a traitor, so we have something like the dogs in the terminator movies sniffing out robots and shit.

A suggestion to fix this would be to have all animals revived by injectors set to passive, not neutral, and maybe make emagging the injectors cause them to revive animals as whatever faction the person who used the injector is part of.

### PR DESCRIPTION
**Pull request by alsoandanswer**
They only do the faction fuckery when emagged/emp'd

EMP causes the lazarus injector to revert the mob's faction to it's original one.

Emag causes the lazarus injector to turn the mob's faction to yours.

Fixes #9167

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!bugfix

**Comment by alsoandanswer** [comment]
!review

**Comment by Doxxmedearly** [comment]
Why is it setting them to their initial faction only when EMP'd?
Also not a fan of keeping the faction "neutral" even with an emag as that doesn't fix the bug so much as weaponize it. It's still buggy behavior; according to the bug report, even non-hostile mobs will attack things. If anything it should just set it to the player faction.

**Comment by alsoandanswer** [comment]
> 
> 
> Why is it setting them to their initial faction only when EMP'd?

normal lazarus behavior is keeping pre-death faction. death does not change faction in any way.
i.e.
let's say you tame a carp. faction goes from "neutral" to "tamed".
if it dies and you revive it with lazarus injector, it stays "tamed".
if it's EMP'd, it will turn back to "neutral"

> Also not a fan of keeping the faction "neutral" even with an emag as that doesn't fix the bug so much as weaponize it. It's still buggy behavior; according to the bug report, even non-hostile mobs will attack things. If anything it should just set it to the player faction.

See original PR comment.

**Comment by Doxxmedearly** [comment]
...How did I fucking miss that. That's what I get for reviewing in the morning. 
Alright, cool. Thanks for humoring my sleep-induced comments.

**Pull request merged**
