### PR TITLE
Scarab Salvager offship remap

### PR DESCRIPTION
**Pull request by hazelrat**
This PR remaps the Scarab Salvager offship to resolve a few issues it had, and improve its layout and gameplay appeal. A few things to note:

This is a WIP, so the template flag is still in. The shuttle dock still doesn't recognize when the shuttle is docked, and my head hurts trying to figure it out, so if anyone has an eye they can lend to figuring out which variable I misplaced, I'd appreciate it!

This is a multi-z level offship. Deck two is the primary deck, and deck one houses the hangar, refineries, and the shuttle. I based the implementation of the z-levels off the bluespace river offsite, as it's the only strong precedent in the code I could find, so it may be unusually implemented. There are map data landmarks in the southwest of both .dmm files. Everything appears fully functional to me.

The old double shuttle of the original map has been merged into a single one, designed to be able to be used for general ferrying in addition to gas harvesting. The shuttle is no longer EVA, and neither is propulsion, so there should be a lot less needless airlock cycling. It still has EVA docking ports for everything besides its own shuttle, but they're at least more centralised.

With help (read: they told me how to do everything and I nodded sagely) from Geeves, this introduces perma_light effects that adapt to the colour of the starlight of the sector they're in. In this case, it's so the centre tiles of the solar arrays aren't dark. 

This gives the ship five suit cyclers, four of which are engineering, and one of which is the freelancer armoured suit. This is in with the intention that it's used with the gauss thumper in the armoury to allow one member of the crew to act like a guard in salvage missions. Given how few tools the rest have, I don't think it should cause the ship to be too resistant to piracy.

Note that the ship doesn't spawn in Haneunim, and this PR doesn't touch its sectors.

### CODE REVIEW

**Comment by hazelrat** [comment]
!wip

**Comment by hazelrat** [comment]
!wip

**Comment by hazelrat** [comment]
!review

**Comment by DreamySkrell** [comment]
image
needs teleporters on the edge of the map

**Comment by DreamySkrell** [comment]
image
remove lattice on the ladder going down

**Comment by DreamySkrell** [comment]
image
remove signs overlapping buttons

I know the signs are outside, but this makes it harder to review and see what is going on

**Comment by DreamySkrell** [comment]
image
image
this

**Comment by DreamySkrell** [comment]
image
don't put catwalks everywhere - they make it harder to maintain the piping and wiring

**Comment by DreamySkrell** [comment]
image
I'm 98% sure this will not do what you want, and all the pipes will connect to the universal connector 
I would be surprised if the propellant line did not connect to the waste and supply pipes

**Comment by DreamySkrell** [comment]
image
instead of setting start_pressure to zero on the map prefab, this should be a new subtype in the code instead

**Comment by DreamySkrell** [comment]
image
missing pipe here

**Comment by DreamySkrell** [comment]
image
to spot similar issues easily, see my forum thread on mapping tips and guides

**Comment by DreamySkrell** [comment]
image
downwards pipes should not go into the floor, but into open space (with a lattice on preferable) like on horizon

**Comment by DreamySkrell** [comment]
image
`connect_types = CONNECT_TYPE_REGULAR|CONNECT_TYPE_SCRUBBER //connects to regular and scrubber pipes`
this scrubber will connect both to scrubber pipe line and also to the fuel line

**Comment by DreamySkrell** [comment]
image
this is a ton of meds for an offship that is not medical-based like IAC or whatever
I would expect a random scarab ship to not be stocked so good with top of the line meds like that

remove the advanced medkit
remove the body scanner

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
as above

**Comment by hazelrat** [comment]
> image image this

I'd prefer to keep this as is, if possible. Heaters have no functional use, but I think they communicate much more clearly that there's thrusters on the other side than do featureless walls. They don't allow light to pass through them, so they don't let you see starlight through the thrusters like they do with glass panes. This is also how it's done on the Horizon.

image


> image don't put catwalks everywhere - they make it harder to maintain the piping and wiring (or even see where they go)

I'd also prefer to keep the catwalks, if possible, too. They're mechanically important - I don't honestly think I can make the engine room more compact than it is, so characters need something to hold onto in the absence of gravity. I also honestly think the room would look weirdly plain and empty without them, and I haven't seen any players complain about pipe visibility in the similar engine room in the current version of the same offship.

image

All other changes have been implemented, plus resolving some additional nonsense piping now that I know how useful it is to adjust what StrongDMM shows. I've shifted the z transitions on the pipes and wires to EVA.
image

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by DreamySkrell** [comment]
image
wrong entry point name here

**Comment by DreamySkrell** [comment]
image
should the smelters and stackers here not had `id` vars set with appropriate consoles?
they do on horizon - do they work without consoles?

**Comment by DreamySkrell** [comment]
image
wrong sensor id here

**Comment by DreamySkrell** [comment]
image
don't change layers of machinery or objects (or really anything in strongdmm)
the dirt is only shown above machinery in strongdmm, and should be applied to the floor actually in the game

if this is annoying to see in when mapping, the layers should be changed in code instead to fix it for other mappers in the future too

**Comment by DreamySkrell** [comment]
image
don't change density of structures and pixel-shift them into walls

**Comment by DreamySkrell** [comment]
> I'd prefer to keep this as is, if possible. Heaters have no functional use, but I think they communicate much more clearly that there's thrusters on the other side than do featureless walls. They don't allow light to pass through them, so they don't let you see starlight through the thrusters like they do with glass panes. This is also how it's done on the Horizon.

that's fine then

**Comment by DreamySkrell** [comment]
> I'd also prefer to keep the catwalks, if possible, too. They're mechanically important - I don't honestly think I can make the engine room more compact than it is, so characters need something to hold onto in the absence of gravity. I also honestly think the room would look weirdly plain and empty without them, and I haven't seen any players complain about pipe visibility in the similar engine room in the current version of the same offship.

image

reduce their number at least then for example in the pic, they really don't need to be on every turf

also pretty sure can just use railings - catwalks everywhere to ignore lack of gravity, feels really gamey and unintended

**Comment by DreamySkrell** [comment]
image
and here with the cabinets

**Comment by hazelrat** [comment]
> image should the smelters and stackers here not had `id` vars set with appropriate consoles? they do on horizon - do they work without consoles?

They link with consoles based on proximity, from what I can tell? They're functional in the current branch.

> > I'd also prefer to keep the catwalks, if possible, too. They're mechanically important - I don't honestly think I can make the engine room more compact than it is, so characters need something to hold onto in the absence of gravity. I also honestly think the room would look weirdly plain and empty without them, and I haven't seen any players complain about pipe visibility in the similar engine room in the current version of the same offship.
> 
> image
> 
> reduce their number at least then for example in the pic, they really don't need to be on every turf
> 
> also pretty sure can just use railings - catwalks everywhere to ignore lack of gravity, feels really gamey and unintended

I'd still really prefer not to do that. I think that example looks very strange and patchwork and doesn't really show the player anything not already reasonably visible in the current version. Catwalks in real life, and in the Horizon's gas mixing that I based this off, are continuous structures. Railings would be usable, but would obstruct movement in the room.  If you still insist on a change like this, I'd prefer to redo the whole room to have full tiled floors + visible pipes and fill in the zero-g gaps with railings - but I'd really rather be done with this PR and focus on other things.

All other changes have been implemented.

**Pull request merged**
