### PR TITLE
Department Radio Colours

### PR DESCRIPTION
**Pull request by Geevies**
* Speaking on the radio now cross-references the records database. If the name of the voice is in the records database, their name and role is shown, and coloured in their department's colour.
* The antag buyable in the Announcements uplink that makes a fake arrivals announcement and generates a fake record for the buyer is no longer restricted to Mercenaries, and costs 4 TC instead of 8 TC now.

A screenshot of how it looks. The role is `[role]` instead of just `role`, but this is just an example.
image

This is probably a pretty divisive PR, but I made it cuz it was pretty fun to make. If people dislike it a lot, closing it is A-okay.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by NonQueueingMatt** [comment]
I'm not sure I approve of this, personally.

**Comment by skull132** [comment]
IMO too much colours. Too easy to confuse with departmental radio channels. No?

**Comment by skull132** [comment]
This is denied. We're getting into the territory of trying to shove too much visual information across, and it gets bad.

**Pull request closed without merging**
