### PR TITLE
Slightly expands Xenoarchaeology to add anomaly storage, and adds an access requirement to a door in the Research hallway

### PR DESCRIPTION
**Pull request by Leudoberct1**
This PR will slightly expand Xenoarchaeology to include anomaly storage, like it used to have on the old map. I have slimmed it down so that it does not consume quite as much space. Incidentally, I have also fixed a vent that was improperly mapped in Xenoarch and had no piping connection.

Picture: https://gyazo.com/f521af7bd3a4f9c1c0eabefb79b3b480

I have also added Research access requirement to a door in the middle of the Research hallway. Previously, this would allow anyone to just walk through the department. This would normally not be an issue due to the actual labs requiring access, but the entrance to Xenoarchaeology in this hallway is an elevator, not an airlock. I do not know of any way to access restrict an elevator, and I have seen multiple people in round just walking straight into Xenoarch through the elevator. Given there can be dangerous anomalies stored in here, that's a bit silly. Adding the access requirement prevents this.

Picture: https://gyazo.com/4a842e8c3c91f5417c80ad8ee53aa81f

Tested on private repository with no issues.

### CODE REVIEW

**Comment by Greenjoe12345** [comment]
i think its fine, but it'll be good to make sure that expanding the firing range out means it isn't sticking out from the second floor, and won't need a roof put over

**Comment by Leudoberct1** [comment]
Already looked, it's covered by xenobotany above.

**Comment by Leudoberct1** [comment]
!review

**Review by SleepyGemmy — APPROVED** [review]

**Comment by kyres1** [comment]
This isolates and restricts traffic from an already low-traffic area to the main hallways. Why not turn the elevator sideways, or just back it up two tiles to facilitate an access-locked door?

**Comment by SleepyGemmy** [comment]
> This isolates and restricts traffic from an already low-traffic area to the main hallways. Why not turn the elevator sideways, or just back it up two tiles to facilitate an access-locked door?

there isn't space to move nor turn the elevator.

**Comment by Leudoberct1** [comment]
I don't know if windoors will mess with the elevator or not, but I could try it. How much traffic does this really restrict though? This area pretty much just provides access to the xenobot and xenobio labs, science spawn room and a small storage room. That, and the elevator down to Xenoarch/firing range. How many non-science people are even frequently using this little 3x15 hallway?

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by Leudoberct1** [comment]
Fixes #17009

**Pull request merged**
