### PR TITLE
Hephaestus and Orion Operations Uniform Changes

### PR DESCRIPTION
**Pull request by RyverStyx**
image
image

### CODE REVIEW

**Comment by RyverStyx** [comment]
!review

**Comment by alsoandanswer** [comment]
Why are you changing the default outfits? You're going to mess up people's existing characters (which should be the case, seeing as Operations uniforms have been unchanged for a couple months now.) Make your alt outfits the replacements, at the very least

**Comment by RyverStyx** [comment]
> Why are you changing the default outfits? You're going to mess up people's existing characters (which should be the case, seeing as Operations uniforms have been unchanged for a couple months now.) Make your alt outfits the replacements, at the very least.
> 
> You should do that for the Orion Tech and Miner you just changed as well.

The vest should not be part of the default outfit since vests are already available in loadout; as mentioned in my last PR. As far as changing the miner outfit it now thematically matches Hephaestus.

**Review by KingOfThePing — APPROVED** [review]

**Comment by alsoandanswer** [comment]
I've taken a closer look at your PR

1. You've changed them as alt outfits, but haven't even put them in the loadout or the code to make them actually available.
2. The vests. They aren't even in the code. Unless I'm mistaken.
3. I understand doing away with the vests for Orion, since they're only limited to cargo. Not for Hephaestus, though. It is one of the prominent distinguishing features that seperates the already all-green engineering Hephaestus uniforms from the Cargo uniforms, further fracturing the department theme.
4. The Cargo Tech uniforms. Why have they been changed to shorts. 
5. You have yet to address this. >Why are you changing the default outfits? You're going to mess up people's existing characters (which should be the case, seeing as Operations uniforms have been unchanged for a couple months now.)

**Comment by RyverStyx** [comment]
> I've taken a closer look at your PR
> 
> 1. You've changed them as alt outfits, but haven't even put them in the loadout or the code to make them actually available.
> 2. The vests. They aren't even in the code. Unless I'm mistaken.
> 3. I understand doing away with the vests for Orion, since they're only limited to cargo. Not for Hephaestus, though. It is one of the prominent distinguishing features that seperates the already all-green engineering Hephaestus uniforms from the Cargo uniforms, further fracturing the department theme.
> 4. The Cargo Tech uniforms. Why have they been changed to shorts.
> 5. You have yet to address this.
> 
> > Why are you changing the default outfits? You're going to mess up people's existing characters (which should be the case, seeing as Operations uniforms have been unchanged for a couple months now.)

1. I was under the impression this was already done.
2. There are vests already in the code.
3. Accessories should not be attached to uniforms as was addressed in my last PR.
4. The shorts are already in game and this PR does not change them.
5. It seems like from previous PR's that others, and yourself, have made that existing character's loadouts do not need to be taken into account.

**Comment by alsoandanswer** [comment]
> > I've taken a closer look at your PR
> > 
> > 1. You've changed them as alt outfits, but haven't even put them in the loadout or the code to make them actually available.
> > 2. The vests. They aren't even in the code. Unless I'm mistaken.
> > 3. I understand doing away with the vests for Orion, since they're only limited to cargo. Not for Hephaestus, though. It is one of the prominent distinguishing features that seperates the already all-green engineering Hephaestus uniforms from the Cargo uniforms, further fracturing the department theme.
> > 4. The Cargo Tech uniforms. Why have they been changed to shorts.
> > 5. You have yet to address this.
> > 
> > > Why are you changing the default outfits? You're going to mess up people's existing characters (which should be the case, seeing as Operations uniforms have been unchanged for a couple months now.)
> 
>     1. I was under the impression this was already done.
> 
>     2. There are vests already in the code.
> 
>     3. Accessories should not be attached to uniforms as was addressed in my last PR.
> 
>     4. The shorts are already in game and this PR does not change them. (Approved by Matt)
> 
>     5. It seems like from previous PR's that others, and yourself, have made that existing character's loadouts do not need to be taken into account.

1. It is not. Please do it.
2.  These specific cargo vests are not in the code, unless you are referring to hazard vests. If so, add them
3. Okay.
4. Upon closer inspection you are actually removing the shorts and replacing it with the old Hephaestus uniforms.
5. I'm just trying to avoid another fiasco on the security uniforms. That's all.

**Comment by RyverStyx** [comment]
> > > I've taken a closer look at your PR
> > > 
> > > 1. You've changed them as alt outfits, but haven't even put them in the loadout or the code to make them actually available.
> > > 2. The vests. They aren't even in the code. Unless I'm mistaken.
> > > 3. I understand doing away with the vests for Orion, since they're only limited to cargo. Not for Hephaestus, though. It is one of the prominent distinguishing features that seperates the already all-green engineering Hephaestus uniforms from the Cargo uniforms, further fracturing the department theme.
> > > 4. The Cargo Tech uniforms. Why have they been changed to shorts.
> > > 5. You have yet to address this.
> > > 
> > > > Why are you changing the default outfits? You're going to mess up people's existing characters (which should be the case, seeing as Operations uniforms have been unchanged for a couple months now.)
> > 
> > 
> > ```
> > 1. I was under the impression this was already done.
> > 
> > 2. There are vests already in the code.
> > 
> > 3. Accessories should not be attached to uniforms as was addressed in my last PR.
> > 
> > 4. The shorts are already in game and this PR does not change them. (Approved by Matt)
> > 
> > 5. It seems like from previous PR's that others, and yourself, have made that existing character's loadouts do not need to be taken into account.
> > ```
> 
> 1. It is not. Please do it.
> 2. These specific cargo vests are not in the code, unless you are referring to hazard vests. If so, add them
> 3. Okay.
> 4. Upon closer inspection you are actually removing the shorts and replacing it with the old Hephaestus uniforms.
> 5. I'm just trying to avoid another fiasco on the security uniforms. That's all.

1. I’ll get this oversight fixed.
2. Not the point of this PR. Seeing as we already have vests I believe any additions would warrant its own PR.

**Review by JohnWildkins — APPROVED** [review]

**Pull request merged**
