### PR TITLE
PDA boop sounds

### PR DESCRIPTION
**Pull request by alsoandanswer**
they boop and beep when you press buttons on them

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by skull132** [comment]
Could you assign a chance to this happening? Like with the keyboard/typing sounds? Also, make sure they're on a similar sound level. _Every_ interaction causing this would be a bad idea.

**Comment by alsoandanswer** [comment]
> Could you assign a chance to this happening? Like with the keyboard/typing sounds? Also, make sure they're on a similar sound level. _Every_ interaction causing this would be a bad idea.

I mean, I think it would sound weird when you press a button and theres a 50/50 chance of a sound actually occuring.

**Comment by alsoandanswer** [comment]
Well I've made the sound quieter. It should be better

**Comment by Arrow768** [comment]
I guess we´ll see how that turns out.

**Pull request merged**
