### PR TITLE
Adjusts the new player options window and adds a map blurb.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
With inspiration taken heavily from Baystation's current window.

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Comment by NonQueueingMatt** [comment]
immagine

immagine

**Comment by Karolis2011** [comment]
What does it show when player joins before map is loaded? Try to join before server loaded map and see what it shows. To acompilish that most efetively - restart server.

Also feedback on UI: by my opinion it looks horendous. Yes, peaple won't like chnage, but putting all buttons in one line takes away somewhat expected constant button locations. Also that wall of text is not pleasant to look and kinda redundant and unwanted by returning players.

Subjective improvements that could improve UX: place actions like join / observe on new line. And maybe make it more tall, than wide.

**Comment by KingOfThePing** [comment]
Pear se, good, but I have a question regarding the asteroid the Aurora is supposed to be on. An in-game item (visible to everyone, in theory) states the following:

serffr

I am talking about the asteroid, not the Aurora II part, though that should be adjusted, too, while we are at it.

**Comment by skull132** [comment]
I'll just keep adding to the clusterfuck that is our on-join pop-ups until I get enough time to remove THEM ALL :^)

**Pull request merged**
