### PR TITLE
Tweaks Headbutts and Grabbing by Species

### PR DESCRIPTION
**Pull request by LordFowl**
Creates the grab_mod species level variable. A higher grab mod means it takes longer for people to upgrade grabs on you, giving you more time to resist, and a lower grab mod means the opposite. Unathi are easier to grab, whereas Dionaea, Skrell, and Vaurca Warriors, and Monkeys are harder to grab.

Headbutt damage is now influenced by mob size. If the attacker's mob size is 10 or higher, then the value of their mob size or 20, whichever is lower, is added to the damage dealt to the target. Unathi deal an additional +5 damage on top of this. Damage done to the attacker is unaffected.

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
While I like this PR,
How exactly is a human, or a Skrell, supposed to wrestle down an Unathi that easily? Without being able to reach their horns?

**Comment by VTCobaltblood** [comment]
Why is it easier to establish a neckhold on Unathi, considering their size? I get just grabbing them by the horns for a passive/aggressive grab, but not neckholds, which are another grab type.

**Comment by Ratvar** [comment]
Shouldn't someone big-sized be more immune to headbutt damage? Maybe spread bighead/smallhead damage bonus in half and add second half to headbutting armor? That'll make it safer to actually use and less severe of a weapon

**Comment by ParadoxSpace** [comment]
Posting on behalf of Loremaster Jackboot who lost his password again.

"The values of grab rates should be inversed per species with unathi being slower to grab and tajara being faster in comparison. Wrestling someone above your weight class is more difficult than someone below. In short: unathi are not easier to put into a pin due to having horns. They are harder to take down in cqc. Grabs represent both grabbing someone as well as pinning them and generally wrestling.

Their headbutts should not do that much damage. The extra +5 should be removed. Loredev requests."

**Comment by LordFowl** [comment]
I disagree with the sentiment that making unathi unilaterally good at every aspect of 'CQC' makes them more flavorful - in fact it makes them less so. This PR does not make them less capable of 'CQC', indeed it makes them very dangerous in CQC, while also evaluating the disadvantages that they would experience.

**Comment by Conspiir** [comment]
What about Unathi that don't have those horns, or if they are fighting people so much smaller than them that they can't reach those horns? I feel like being able to quickly take down a 7', 260lb Unathi just because they have horns is too one-dimensional. By that logic, Tajara and monkeys should be easier to grab because they have a tail, Vaurca should be easier to grab because they have antennae, and Skrell should be easier to grab because they have headtails.

**Comment by LordFowl** [comment]
Monkeys are easy to grab considering you can just pick them up, but considering they are wild animals I've made wrestling them somewhat more difficult, Skrell are slimy frogs, and antennae are not really comparable to horns or even hair. And as I've elucidated before, this is the exact opposite of a one dimensional change.

**Comment by ParadoxSpace** [comment]
Yet again on behalf of Comrade Jackboot,


Making it easier to grab someone makes it easier to defeat them in CQC. A neckgrab is extremely powerful in our codebase. It's not in the vision of how Unathi are meant to be dealt with. A human should not have a reasonable expectation to neckpin a Unathi more than they would another human. Horns are not handlebars by which to floor a Unathi. They are larger and stronger. 

They should not be easier to grab.

Throttle the headbutt damage buff, or don't give it at all.

**Comment by LordFowl** [comment]
Larger and stronger is accounted for in how dangerous they are in close quarters due to their additional damages, so even if one is able to floor them quicker it is still not a riskless proposition. They are not easier to defeat in CQC.

**Comment by LordFowl** [comment]
Headbutts are not the only asset Unathi have at their disposal. It is merely a substantial addition to their already refined list of CQC advantages.

**Comment by skull132** [comment]
We are forgetting that Unathi have claws. Which are the most commonly used weapons in melee combat. I forget, do they also have a strength modifier which modifies their blunt weapon attacks?

**Comment by LordFowl** [comment]
I don't recall that ever being a thing.

**Comment by OneOneThreeEight** [comment]
It definitely is not a thing. They take 20% less brute damage, however, and have claws. They certainly do have CQC dominance.

**Pull request merged**
