### PR TITLE
Adds Sarashi

### PR DESCRIPTION
**Pull request by ParadoxSpace**
Sprites by the surprisingly-talented TheDilShawn
<3

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
!review

**Comment by runecap** [comment]
> if you want to discuss this pr with me
do it on the github pull request, not here
thanks

What aspect of the traditional sarashi would survive/evolve to a point where it could plausibly be used in a workplace environment?

**Comment by ParadoxSpace** [comment]
I'm going to ignore 'workplace environment' because that's not 100% what we model loadout additions after.

**Comment by runecap** [comment]
> I'm going to ignore 'workplace environment' because that's not 100% what we model loadout additions after. Otherwise, we'd need to take out all of the open-toed shoes.
> Otherwise,
> Sarashi are useful as undergarments for various clothings, wrapping the chest and belly in gauze and all of those possible uses, as a substitute bra, for chest binding, fashion. As well, more cultures than just Japan would've developed these.

See no problem then.

**Pull request merged**
