### PR TITLE
Maint access changes

### PR DESCRIPTION
**Pull request by Arrow768**
Removes global maint access from everyone but:
- Heads of Staff (because they are the boss)
- Engineering (because they are qualified)
- Paramedics (becuase they need to access the airlocks in maint from time to time and time is rather important for them)

That does not effect maint access that is mapped in (at the departments), so the departments can access their directly adjacent maint sections.
It only reduces the number of people that have global maint access.

https://forums.aurorastation.org/topic/13225-maint-access-changes/

### CODE REVIEW

**Comment by SonicGotNuked** [comment]
There was an earlier change that gave assistants maint access. It didn't give visitors it though. Would be nice to add to this list.

**Comment by Arrow768** [comment]
> There was an earlier change that gave assistants maint access. It didn't give visitors it though. Would be nice to add to this list.

Assistant maint access is a config options and the code for this config option is not effected by this PR.

**Comment by canon35** [comment]
I don't really see a reason to change up maintenance access. It seems fine as it currently is, plus this change would result in sec not having maintenance access despite being emergency responders like the EMTs.

**Comment by Arrow768** [comment]
This is a reminder that pull requests are only for technical feedback.
If you want to provide something else, that is not technical feedback, you can go to the feedback topic once its set up.

**Comment by Arrow768** [comment]
Merged a bit early so it lines up with the round end.

**Pull request merged**
