### PR TITLE
Removes lean.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
Title. Bad meme.

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Review by TheDanseMacabre — APPROVED** [review]
he beat me to it

**Review by KingOfThePing — APPROVED** [review]
God bless

**Review by SleepyGemmy — APPROVED** [review]
one lean meme too much. rest in peace...

**Review by Ben10083 — APPROVED** [review]
Funny name and will miss it, but at least replacement drugs will be put in around when the NBT releases.

**Review by RyverStyx — APPROVED** [review]

**Comment by Forester40** [comment]
> shit_reference

to be fair, I don't think lean was intentionally added as a reference to the meme, it was added before the meme was popular

**Review by Alberyk — APPROVED** [review]

**Comment by noelle-lavenza** [comment]
It was definitely added on the leading edge of the meme skyrocketing, but it was honestly kind of stupid anyway, you can still just mix cough syrup and soda if you want anyway.

**Pull request merged**
