### PR TITLE
Zeng Hus now have toeless boots in loadout

### PR DESCRIPTION
**Pull request by VTCobaltblood**
Implements https://forums.aurorastation.org/topic/11045-ipc-toeless-jackboots/

### CODE REVIEW

**Comment by VTCobaltblood** [comment]
They aren't jackboots. They're SWAT boots, and I did nothing to the original version. I just fixed the issue with xeno ERT spawning without boots - my logic is that if they're an elite emergency responder, they'd have boots tailored for them so you couldn't aim for the toes. Although I admit that the way I fixed it is somewhat crude and can have fully expected side effects if someone decides to rob a ERT corpse.

**Comment by VTCobaltblood** [comment]
Is it really a silly exception? With Zeng Hus, all species with non-standard feet can get their boots now. Why remove the whitelist restriction if nobody except species with non-standard feet would show up with toeless boots to work?

**Comment by Alberyk** [comment]
They can wear any kind of shoe just fine, unlike vaurca, unathi and tajara.

**Comment by VTCobaltblood** [comment]
wait really? damn no point in this then

**Pull request closed without merging**
