### PR TITLE
Adds Omni-Immunization Reagent

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Overview
Adds Nelocacillin, a special medicine that prevents non-wound based infections from occurring on the person. Has a slow metabolism rate, and is good for cheap immunizations.

I think viruses are disgustingly strong. I think this is a good way to nerf them in some way. Doctors and medical personnel could ask the chemist to produce this and immunize medical personnel, 15u of this stuff should last one hour, 20u is an overdose and actually causes germs to build up.

Since the reagent is pretty useful/powerful, it requires 1 part Spaceacillin, 1 part Sodium, and 0.1 parts phoron, with a catalyst of 5u phoron.

Thread: https://forums.aurorastation.org/viewtopic.php?f=18&t=10967

### CODE REVIEW

**Comment by BurgerLUA** [comment]
Fuck my life I fucked up.

**Comment by flimango** [comment]
How does administering this affect existing viral infections?

**Comment by Pacmandevil** [comment]
I've played on aurora for upwards of a year and have seen virologist a total of two times, it's like psych but can't even contribute to the station in a meaningful way.

this just kinda seems like an "i ded pls restrt" because one Viro in the course of history released a virus that killed you.

**Comment by BurgerLUA** [comment]
I've never been killed by a virus, but I've been in several rounds where the flow has been interrupted several times.

**Comment by Lohikar** [comment]
Make a forum thread.

**Comment by BurgerLUA** [comment]
Thread: https://forums.aurorastation.org/viewtopic.php?f=18&t=10967

**Comment by Bygonehero** [comment]
No.

**Comment by BurgerLUA** [comment]
great feedback

**Comment by LordFowl** [comment]
I don't see this happening unless it is packed in with a larger rework of the virology treatment procedure to better incorporate its mechanics.

**Comment by BurgerLUA** [comment]
Probably considering this is literally spacacilin but with a slower metabolism time and inability to cure. I think a lot of people are grossly ignorant of the code and perhaps a giant rework that explains everything might get people to change their mind.

**Comment by Ornias1993** [comment]
Medical should learn to actually do the correct containment procedures: 
1. Medical personal should grab bio hazard gear until the danger of the virus is known or a vaccine is available
2. Infecter personal should be isolated, if need be by force.
3. Body's should be isolated and/or burned to prevent spread
4. Communal area's should be closed down till further notice
5. Departments should be on lockdown unless there is no other choice till a cure is available.

On all high RP servers for some retarded reason no one playing medical care to actually RP unknown virus outbreak containment.

This is a fix, fixing people's lack of semi-correct roleplay, which is a BIG nono. It is supposed to be a challenge like @skull132 noted.

**Comment by BurgerLUA** [comment]
Closing this for now. Will be introducing this when I eventually take over the throne of Head Developer in 2025.

**Pull request closed without merging**
