### PR TITLE
Destroys SS13 culture: Bags of Holding no more

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
Bags of holding (trash and normal) have been made adminspawn only and refluffed to have names that are not outright references. There is still some utility to having them in the game, though, so they are not being outright removed. If I was to get a better sprite I'd be happy to undo some of these changes, but as it is I don't think they should be spawnable.

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Comment by WickedCybs** [comment]
This can't be happening.

**Review by alsoandanswer — COMMENTED** [review]
aren't these science items?

**Comment by TheDanseMacabre** [comment]
> aren't these science items?

Science can make them. I removed the ability for science to make them.

**Comment by UponASeaOfStars** [comment]
Why not keep them in but just rename/re-desc them to be more immersive? They're kind of the capstone of bluespace research, and very fun to use.

**Comment by TheDanseMacabre** [comment]
> Why not keep them in but just rename/re-desc them to be more immersive? They're kind of the capstone of bluespace research, and very fun to use.

Someone may make a new sprite and if they do I will be doing this.

**Review by SleepyGemmy — APPROVED** [review]

**Review by alsoandanswer — COMMENTED** [review]
If the main problem is the sprite, then I think you can hold off on removing them until a new sprite is available. Or you could port it, either way. My recommendation as a spriter.

Because the alternative would mean that it gets removed and people will forget about it. Which I am vehemently against removing things

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
