### PR TITLE
Adds snake people

### PR DESCRIPTION
**Pull request by Alberyk**
Changes:
-adds snake people as a whitelisted species
-adds tail mechanics, ported from europa station, to the snake people, you can coil it up, people can attack it, stomp the tail and etc
-snake people can spit poison
-snake people can't use shoes
-snake people also have some other features like having a minor brute resist, claws and cuff breaking
-snake people can have different scale colors and eyes colors, but green is the best color without doubt
-also adds snake people

Pictures:
snakepople

Lore:
Snake people come from somewhere beyond the frontier, or something because that is where we put all the things that we don't want to write a lot about, and are a foreigner species to the galaxy. They are a race of mysterious invaders, having already developed faster than light travel, and attacking frontier settlements and ships as raiders . They also seems to refuse any mean of communication or diplomacy with the other sentient species besides attacking them, but somehow they are employed on the station by NanoTrasen.

### CODE REVIEW

**Comment by ToasterStrudes** [comment]
I think we should replace Tajara with this race, I feel it would be a great improvement to the server.

**Comment by Fire-and-Glory** [comment]
But where are the ERP mechanics? 

It's really no good if there's no ERP.

**Comment by Zuhayr** [comment]
It would appreciated if next time you want to flog off Europa features you credit us.

**Comment by Zuhayr** [comment]
Rezzing a dead closed PR to add 'No.'. :thinking:

**Pull request merged**
