### PR TITLE
[WIP] Clothes rework - modular, recolorable clothing

### PR DESCRIPTION
**Pull request by shedya**
As we know, sweaters exist. Sweaters are a great item: you can recolor them, you can wear them on anything and not take up an additional slot. Many people like sweaters. I like sweaters. In fact, I like sweaters so much that I want most of the current in-game clothing to take the sweater model.
My long-term goal is to have every or most "suit" items in the game, like the suits in loadout and command clothing, be replaced with separate clothing elements which you can mix, match and recolor. This would allow people to add much more flavor to how their characters dress, and what their fashion sense is. Also, this comes with a bunch of non-modular clothing becoming recolorable as well.

However, there are a couple of cons:

1. A feature like this opens up a whole new alley for snowflakes to make costumes that aren't really suitable on a space station. In my opinion, this is an IC issue rather than an OOC one, since characters can enforce corporate uniform regulations ICly.
2. I haven't yet looked at how to make multiple accessories be displayed in character setup - meaning that you can't, for example, preview both a tie and a dress shirt at once. They work perfectly in-game, but it's hard to preview them without actually entering the round as your character. You also need to put the second accessory on manually when entering the round. This can be combated by including a jumpsuit or another safe dress option in your loadout in case your outfit actually looks horrible, but this is still an issue.

List of things to do:

- [x] Add recolorable dress shirts  
- [x] Add recolorable pants
- [x] Add recolorable skirts
- [ ] Add a different, more casual skirt variant
- [x] Add recolorable suit jackets - they went in the suit slot
- [x] Add recolorable sweater vests
- [ ] Add recolorable jackets
- [ ] Add recolorable bowties
- [ ] Make military jackets unzippable
- [ ] Add recolorable track pants and jackets
- [ ] Make ties recolorable, with options for short and long
- [ ] Make labcoats recolorable
- [x] Make jumpsuits recolorable
- [ ] Make medical scrubs recolorable
- [ ] Make berets recolorable
- [ ] Make jumpskirts recolorable
- [ ] Make bandanas recolorable
- [ ] Make some other clothing items recolorable
- [ ] Add other modular clothing I haven't yet thought of
- [ ] Rework loadout
- [ ] Make suit jackets buttonable and unbuttonable
- [ ] Add a rolled-up variant of the dress shirt

Feedback: https://forums.aurorastation.org/viewtopic.php?f=21&t=12114

### CODE REVIEW

**Comment by BotBOREALIS** [comment]
Icons with diff:
<details><summary>icons/mob/ties.dmi</summary>

Key | Old | New | Status
--- | --- | --- | ---
dressshirt||dressshirt|Created
dressshirt[1]||![dressshirt[1]](http://images.aurorastation.org/images/8955ffde43f9dc665acadfccb6a83640.png)|Created
dressshirt[2]||![dressshirt[2]](http://images.aurorastation.org/images/36fca22837a776e2193e751b6b59e78a.png)|Created
dressshirt[3]||![dressshirt[3]](http://images.aurorastation.org/images/5d35f03930d8f2ae48f7b75212f85cfb.png)|Created
</details>
<details><summary>icons/obj/clothing/ties.dmi</summary>

Key | Old | New | Status
--- | --- | --- | ---
dressshirt||dressshirt|Created
</details>

**Comment by shedya** [comment]
!wip

**Comment by shedya** [comment]
Attach feedback required tag to this, please

**Comment by OneOneThreeEight** [comment]
You can just make a thread on the forums for this to acquire feedback. Link this PR in that post and it should do fine.

**Comment by shedya** [comment]
I already did that.

**Comment by ToasterStrudes** [comment]
Hey, colored berets would be cool

**Comment by MarinaGryphon** [comment]
Is this a Polaris port?

**Comment by ComradeCorbyn** [comment]
b-b-b-b-bowties?

**Comment by shedya** [comment]
No, this is not a polaris port.
Resuming work on this.

**Comment by shedya** [comment]
Will be making this in smaller scale PRs instead

**Pull request closed without merging**
