### PR TITLE
Adds shoes to burger employees

### PR DESCRIPTION
**Pull request by Catrly**
-Fixes burger employees spawning without shoes.

Mostly just trying to make sure my coding stuff is set up correctly, apologies for baby pr. Trying to isolate issue.

### CODE REVIEW

**Comment by Catrly** [comment]
!review

**Comment by Catrly** [comment]
WHYYYY is it getting unhappy with the workflow approval 😭

**Comment by SleepyGemmy** [comment]
because you are a first time contributor.

**Comment by SleepyGemmy** [comment]
> WHYYYY is it getting unhappy with the workflow approval 😭

because you are a first-time contributor and a developer must manually approve it for the first time.

**Comment by Catrly** [comment]
> > WHYYYY is it getting unhappy with the workflow approval 😭
> 
> because you are a first-time contributor and a developer must manually approve it for the first time.

Holy shit, I am so stupid. Forgot I'd changed git accounts. Thanks lol; was so sure I'd done something wrong.

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
