### PR TITLE
Adds three new accents.

### PR DESCRIPTION
**Pull request by TheStryker**
Adds three new accents with lore descriptions done by Schwann.
image
**Earther:** Accessible to IPCs and  non-offworlder humans.
**Europan:** Accessible to IPCs, non-offworlder humans, and skrell.
**Deep Frontier:** Accessible to both kinds of humans.

### CODE REVIEW

**Comment by TheStryker** [comment]
!review

**Comment by Snakebittenn** [comment]
Unsure why Europans can't be offworlders, given that the gravity is so low that it /does/ naturally make them.

**Comment by TheStryker** [comment]
Right! Europa is a cramped place where tall offworlders wouldn’t be practical. Traces of offworlders can reasonably be stamped out with gravity generators given the strong tourist and research presence in the current era.
Deep Frontier is something that represents the dirt poor or obscure human settlements out in the Frontier. It’s also meant to function as a unique human accent that doesn’t align them with any of the other factions/species as they are in fact human settlements that are distinctly, for lack of a better term, human.

**Comment by alsoandanswer** [comment]
Isn't the earth accent just Sol?

**Comment by TheStryker** [comment]
It *was* like that, but with the new Earth accent, it sets it apart from the rest of Sol by turning it into a catch-all for non-named systems such as Mictlan and any headcanon systems. Earth is pretty unique in the Sol Alliance (and has tons of accents as it is so this is like a narrowed down catch-all).

**Review by Aboshedab — APPROVED** [review]

**Pull request merged**
