### PR TITLE
Fixes vaurca lack of natural insulation

### LINKED ISSUE #4597: Vaurca no longer have natural insulated gloves
Now Vaurca can't do electrical work any more without gloves, they definitely did have 'insulated gloves' naturally and I've been getting shocked even from mild shit. I think this came from the shock-therapy update.

### PR DESCRIPTION
**Pull request by Alberyk**
-fixes #4597

### CODE REVIEW

**Comment by LordFowl** [comment]
This seems ill-advised. Shouldn’t Vaurca have a siemens coefficient of 0? In which case they should be caught by the check above.

**Comment by Alberyk** [comment]
That would make them immune to batons and other things, we had this problem before if I am not wrong.

**Comment by LordFowl** [comment]
Yes, I understand now. I wonder what removed this check initially.

**Comment by Arrow768** [comment]
Should we add tree people to that aswell ?

**Comment by Alberyk** [comment]
Unlike vaurca, I do not recall this being a dionae feature, I was also asked by the vaurca writer to look into this.

**Pull request merged**
