### PR TITLE
Adds modular lasers and gun reliability

### PR DESCRIPTION
**Pull request by printer16**
Adds modular lasers like Fowl was going to do a long time ago. Also adds gun reliability. Needs a lot of sprites, more gun mods, and for me to finish putting the reliability on the prototype weapons. Read https://forums.aurorastation.org/viewtopic.php?f=72&t=6721&p=66302 for more information.

### CODE REVIEW

**Comment by chaoko99** [comment]
fucking sweet; this gives me an excuse to finish making gems for mining to use in the guns.

**Comment by chaoko99** [comment]
Also some kind of heat management would be cool. I'd probably add that myself.

**Comment by printer16** [comment]
Associated thread if you want more information: https://forums.aurorastation.org/viewtopic.php?f=72&t=6721&p=66302

**Comment by printer16** [comment]
I'm going to do a different approach to this in the future.

**Comment by chaoko99** [comment]
Does this function, at any rate?

**Pull request closed without merging**
