### PR TITLE
20 loadout points

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
20 loadout points

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Review by OneOneThreeEight — APPROVED** [review]
20 loadpoints. 

inb4 "bLoAt"

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
The solution to the problem you're having is not to constantly increase loadout points every time we add a dozen of loadout points. I'm fine with making most cosmetic only items free or some other alternative, but let's not go down this rabbit hole of kicking the can down the road for a few months at a time.

**Comment by Cnaym** [comment]
> The solution to the problem you're having is not to constantly increase loadout points every time we add a dozen of loadout points. I'm fine with making most cosmetic only items free or some other alternative, but let's not go down this rabbit hole of kicking the can down the road for a few months at a time.

100% this. Currently you can already pick up multiple item for every slot without running out, this just enables more augments to be stuffed into a single person. Making cosmetics free and the rest based on choice would be a ton better than just giving out more things that will only get abused anway.

**Comment by Arrow768** [comment]
Closed as not wanted after a discussion with the maintainers.
The currently available loadout points are good enough as they are.

**Pull request closed without merging**
