### PR TITLE
Adds ashtrays to the bar and diner.

### PR DESCRIPTION
**Pull request by FirinMaLazors**
TronHoward in the discord requested ashtrays in the service area, so I put one on each booth in the southern part of the bar and one on the freestanding diner table.

### CODE REVIEW

**Comment by FirinMaLazors** [comment]
!review

**Review by fernerr — CHANGES_REQUESTED** [review]
Putting them in the bar booths work, but having one the front of the kitchen would encourage people to smoke there, which I don't feel is appropriate, especially with the kitchen itself being marked as a no-smoking zone.

**Comment by FirinMaLazors** [comment]
@fernerr Will do.  Do you think I should add one to the bar counter?

**Comment by fernerr** [comment]
@FirinMaLazors Go for it.

**Review by fernerr — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
