### PR TITLE
Removes Old Unused Atmospherics Code

### PR DESCRIPTION
**Pull request by SleepyGemmy**
removes "mainspipe.dm" and "mainspipe.dmi" which haven't been used since 2012.
no player facing changes.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Review by KingOfThePing — APPROVED** [review]
Epic

**Comment by KingOfThePing** [comment]
You still need a changelog

**Comment by SleepyGemmy** [comment]
there are no player facing changes.

**Review by Alberyk — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
