### PR TITLE
Service Department Map Change(s)

### PR DESCRIPTION
**Pull request by Hunttark**
feedback thread: https://forums.aurorastation.org/topic/18084-feedback-thread-for-service-remap

---

* The bar lounges have been removed in favor of a central dining hall.
* The Bar has been moved to the starboard side, with additional bar seats and distance from the eating area to prevent convo-clashing.
* The kitchen has remained mostly the same, besides gaining 4 tabletop surfaces.
* Shutters were provided to the exterior windows that can be controlled by either the bar, dining hall or kitchen respectively depending on where the (carp) are at the time.
* Pun Pun has a little bedroom with bananas now.

## screenshots
<details>
<summary>🖼️ click to view</summary>

e7672bac5ce891fae499cc70fb1f8b5c

1dbf5638b6f05f8ad4027d4a6e306c64
</details>

_(edited by SleepyGemmy @ 2023-03-07: added feedback thread link. added a screenshots section.)_

### CODE REVIEW

**Comment by Hunttark** [comment]
Done trying to figure out where I fucked it up, will fix it tomorrow for review

**Comment by Hunttark** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]

**Review by RyverStyx — APPROVED** [review]

**Comment by kyres1** [comment]
This remap is functionally a step backwards to our current layout. Where it has high traffic areas, it's decidedly more cramped, and where lower trafficked areas were, there is now large, open and very chair-populated rooms that can't support much of any one-on-one RP, with the bartender(s) or chef no less.

The back bar lounge is an especially strange addition seeing as it has been condensed into exactly one tile for the bartender to move. This, coupled with the above, really makes none of this remap acceptable in its current state to me.

I went ahead and made a feedback thread here as well, given this is a remap of what is effectively the highest traffic area in the station for all players.

https://forums.aurorastation.org/topic/18084-feedback-thread-for-service-remap/

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
PR undoes some changes to security. refer to the diff.

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
some mapping issues.

---

image

railings reduce usable tabletop space.
image

image

cramped main hallway.
image

image

air alarm won't detect if the actual room is breached.
image

cramped backroom (could be solved by reclaiming the pet bedroom tiles.)
image

stairs under the doors.
image

**Comment by Hunttark** [comment]
> some mapping issues.
> 
> image
> 
> railings reduce usable tabletop space. image
> 
> image
> 
> cramped main hallway. image
> 
> image
> 
> air alarm won't detect if the actual room is breached. image
> 
> cramped backroom (could be solved by reclaiming the pet bedroom tiles.) image
> 
> stairs under the doors. image

A few of these were not errors, especially with air alarms, they are simply on opposing wall sides but given how the sprites will appear, I opted to just move the items to other tiles. It should all be resolved. Checking to make sure security matches master.

**Review by SleepyGemmy — DISMISSED** [review]
PR still undoes some changes to security. refer to the diff.

**Comment by Hunttark** [comment]
> PR still undoes some changes to security. refer to the diff.

referred to dif; fixed

**Review by SleepyGemmy — COMMENTED** [review]
## minor issues
undo the removal of this chair. (it was supposed to be a tongue-in-cheek joke for anyone who finds it.)
image

overlapping. (move it up a tile.)
image

center this piping branch.
image

overlapping.
image

overlapping.
image

overlapping.
image

overlapping.
image

overlapping.
image

## suggestions

this should ideally be full steel tiles with no splines to blend in better.
a row of doors like the one a couple of tiles to the north could be an alternative implementation as well.
image

consider removing these two tables and moving its contents to the table next to it. it would open things up a bit more.
image

consider mirroring this so theres one or two spare tiles to put stuff like the icecream cart etc.
image
like so
image

**Comment by Hunttark** [comment]
> ## minor issues
> undo the removal of this chair. (it was supposed to be a tongue-in-cheek joke for anyone who finds it.) image
> 
> overlapping. (move it up a tile.) image
> 
> center this piping branch. image
> 
> overlapping. image
> 
> overlapping. image
> 
> overlapping. image
> 
> overlapping. image
> 
> overlapping. image
> 
> ## suggestions
> this should ideally be full steel tiles with no splines to blend in better. a row of doors like the one a couple of tiles to the north could be an alternative implementation as well. image
> 
> consider removing these two tables and moving its contents to the table next to it. it would open things up a bit more. image
> 
> consider mirroring this so theres one or two spare tiles to put stuff like the icecream cart etc. image like so image

Fixed; in future if possible please post reviews/feedback in the thread like everyone else, its just easier for me to keep track of what everyone wants and so everyone can respond to it equally.

**Review by SleepyGemmy — COMMENTED** [review]
still overlapping.
image
image

**Comment by Hunttark** [comment]
> still overlapping. image image

Those are on opposing sides.

**Comment by SleepyGemmy** [comment]
> [...]

note that its a different sink, the one in the freezer.

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
- the public areas of the service area should preferably not have a lightswitch.
- the light switch in the bar prep area controls the entire bar section's lights.
- there is no game arcade anymore.
- the buttons in the service area don't work as they are the airlock instead of blast door subtype.
- the bartender monkey can escape their chamber. (missing access requirement.)

---

missing grille.
image

light fixture in shutter.
image

overlap.
image

there is a staircase below this wall.
image

overlap.
image

overlap.
image

ramp under the door.
image

image

dark corner. (add a light fixture.)
image

tile.
image

the maintenance door isn't a maintenance door. also dark corner.
image

missing grate.
image

sign is upside down. (i'm aware of perspective, but i'd rather see the sign as my character would see it.)
image

**Pull request closed without merging**
