### PR TITLE
Beware I Live

### PR DESCRIPTION
**Pull request by LadyFowls**
- rscadd: "Emagging gumball machines now cause quite the horror show."
  - bugfix: "Fixed the gumball machines missing wrench functionality and proper damage mechanics and emag"

### CODE REVIEW

**Comment by LadyFowls** [comment]
!review

**Comment by Kaedwuff** [comment]
It certainly is.. creative, I guess. But I think it might be a little too creative? It doesn't really make much sense that a gumball machine turns into a monster when you swipe it with an emag.

I don't really see the correlation, you're taking something that is purely technological, applying a technological effect to it oh, and getting something that is frankly supernatural as a result. It just doesn't make sense, and I feel like this interaction would be better applied to a more supernatural antagonist like Wizard or cultist.

**Comment by Geevies** [comment]
I suggest just making it start shooting out gumballs like a machine-gun, 10 seconds after being e-magged.

**Comment by SonicGotNuked** [comment]
I looked at it. I saw the sprite. I love it.

Just me... I guess, but still.

**Comment by SueTheCake** [comment]
Gumball machines don't have electronics in them typically to begin with. What precisely is there to emag at all?

**Comment by Alberyk** [comment]
Does not really make any sense when you take all other emag interactions into consideration. This really violates the theme and believability of the item/setting by allowing the emag to create monsters out of nowhere.

**Comment by LadyFowls** [comment]
Not longer relevent

**Pull request closed without merging**
