### PR TITLE
Some Corporate Liaison alt titles

### PR DESCRIPTION
**Pull request by alsoandanswer**
Tell me if any of them can't be added and I'll amend it. Should give some flexibility to some characters.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by Roostercat12** [comment]
Corporate Executive is probably going to lead to confusion/people going mad with non-existent power. Should probably be removed imo.

**Review by KingOfThePing — APPROVED** [review]
Think they are all pretty good additions. Aren't reps behind the command WL anyway, so command players should know that they dont have shit to say.

**Review by NonQueueingMatt — APPROVED** [review]
Will need a wiki update to specify that Corporate Executive does not mean that you are a person with any real power.

**Comment by Greenjoe12345** [comment]
Would union rep be a thing?
Can't imagine the corps would want anything to do with unions and would want to stop them, not give their rep an office

**Review by Arrow768 — APPROVED** [review]
Approved, but DNM until the wiki update is in place.

**Pull request merged**
