### PR TITLE
Makes All Guns Contained Sprites

### PR DESCRIPTION
**Pull request by Geevies**
Pour one out for IconDiff bot.

### CODE REVIEW

**Comment by Geevies** [comment]
Feel free to !review , but I still have to test everything out still.

**Comment by alsoandanswer** [comment]
Jesus christ, Geeves.

**Comment by Geevies** [comment]
Alright, she's ready.

**Comment by mikomyazaki** [comment]
Fernerr is a hero. Should 'every item's base icon state exists' be a unit test maybe?

**Pull request merged**
