### PR TITLE
Replaces old vent sprites

### PR DESCRIPTION
**Pull request by alsoandanswer**
title, ported from tg

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by TheDanseMacabre** [comment]
Seems like a mistake and a downgrade to me for us to be replacing original Aurora sprites which are more compatible with our palette and sprite style (and aren't even old in the first place, let alone in need of replacement) with ill-fitting and overly-busy /tg/ sprites that look out of place on Aurora.

**Comment by alsoandanswer** [comment]
> Seems like a mistake and a downgrade to me for us to be replacing original Aurora sprites which are more compatible with our palette and sprite style (and aren't even old in the first place, let alone in need of replacement) with ill-fitting and overly-busy /tg/ sprites that look out of place on Aurora.

Please read the style guide, 'On "The Aurora Style"' section.

**Comment by Generalcamo** [comment]
Highly obvious, easily accessible fanblades fit more into the "retro futuristic" style that /tg/ is going for; such a thing would be an obvious safety violation on the Horizon, which even corporate would look at and say "this is a bad idea". By the sprites guidelines mentioned, and the theme of the Horizon, it would be better to port sprites from Bay (also used in Polaris and Eris), rather than /tg/, as they fit the style more.

However, Polaris offers a compromise: /tg/'s retro-futuristic vents and scrubbers are used for older/dirtier installations where such a thing would fit (Adhomian mining ships perhaps), while the Bay sprites are used in cleaner areas that would justify this (the clean Horizon). This needs some mapping, but I believe this may be the way to go for our server.

**Comment by alsoandanswer** [comment]
> Highly obvious, easily accessible fanblades fit more into the "retro futuristic" style that /tg/ is going for; such a thing would be an obvious safety violation on the Horizon, which even corporate would look at and say "this is a bad idea". By the sprites guidelines mentioned, and the theme of the Horizon, it would be better to port sprites from Bay (also used in Polaris and Eris), rather than /tg/, as they fit the style more.
> 
> However, Polaris offers a compromise: /tg/'s retro-futuristic vents and scrubbers are used for older/dirtier installations where such a thing would fit (Adhomian mining ships perhaps), while the Bay sprites are used in cleaner areas that would justify this (the clean Horizon). This needs some mapping, but I believe this may be the way to go for our server.

If you're willing to do above, I'll close this PR and approve yours.

**Comment by TheDanseMacabre** [comment]
> Please read the style guide, 'On "The Aurora Style"' section.

Frankly, the "Aurora Style Guide" seems to reflect personal preferences more than it reflects the Aurora style currently extant on the server. And unless it's considered to be the official doctrine of Aurora sprites by the maintainers, I don't really see any relevance on what I've said.

> However, Polaris offers a compromise: /tg/'s retro-futuristic vents and scrubbers are used for older/dirtier installations where such a thing would fit (Adhomian mining ships perhaps), while the Bay sprites are used in cleaner areas that would justify this (the clean Horizon). This needs some mapping, but I believe this may be the way to go for our server.

Once again, I do not see the merit of replacing original Aurora sprites with inferior ported sprites from other servers that do nothing but undermine our visual identity.

**Comment by Generalcamo** [comment]
Inevitable conflict with #15241 due to modifications made to .dmi files; I'm not going to start on my own PR until that is merged, and this PR will be impossible to merge anyway with that one.

**Pull request closed without merging**
