### PR TITLE
Spiderborgs roll out! (Animates old sprites and adds new 'borg stuff)

### PR DESCRIPTION
**Pull request by Chada-1**
This'll share the same project thread as it's the same goal as my last PR. Feedback thread here: https://forums.aurorastation.org/topic/13847-the-full-borgo-sprite-rework/

Addition of the Arachnotronic sprite line which'll replace our current spiderborg sprites. They're bigger, fancier, bulkier spiderbots, and they look _really_ good. There are multi department versions.

Animated all of the treaded and spiked 'borg sprites to have walking animations (Basic, Landmate, Treadmate, Treadhead) and reworked all of the old drones (Maint. Drone, Cons. Drone, Mining Drone) to have the new arachnotronic eye overlays.

Removed the Repo-Icarus-Drone series by popular request, it really doesn't match these in quality at this point and I'm not willing to continue to add onto it as I was going to previously, so the only way to handle it at that point is to pull it out.

https://i.imgur.com/5kv9dJh.png <= An example of the spiderborg here offpowered.
https://i.imgur.com/sfQWDFx.gifv <= An example of it with overlay here. It looks great.
https://imgur.com/OPBJ9NO <= An example of it with overlay here but in engi colors.

### CODE REVIEW

**Comment by Chada-1** [comment]
!wip

**Comment by alsoandanswer** [comment]
I don't see why you have to throw out the old spiderborg variant.

**Comment by Chada-1** [comment]
> I don't see why you have to throw out the old spiderborg variant.

I just don't like the sprite as it is, and I don't think it fits the theme the 'borg sprites are heading towards, if someone wants to make a custom 'borg with the sprite or add-on to it to make it fit in more and be less ugly, that's perfectly fine and all of that but I just don't think it's worth keeping alongside the newer ones in its current state. I wasn't v. content with it even after updating it.

**Comment by alsoandanswer** [comment]
It looks way too much like a maintenance drone than like, an actual heavy duty borg. It's not...big enough.

 Again, other people may actually like the old spiderborgs, so I suggest actually asking around first.

**Comment by Chada-1** [comment]
> It looks way too much like a maintenance drone than like, an actual heavy duty borg. It's not...big enough.
It's not smaller (It's actually more wide than the current one overall), and it's larger than every other type of drone in existence, see them side by side for comparison. I'm not willing to budge here because the quality increase with this swap is staggering and it meets the goal of the rework.
DAa75oH
> Again, other people may actually like the old spiderborgs, so I suggest actually asking around first.
Some people do, but the vast majority of people don't. They avoid the thing because it is **_UGLY_**. It has a lot of detail but it must have been designed to be ugly on purpose, and we already have a sprite meant to fill that niche, the off-brand Android, and it has a really _really_ cool posi-brain animation too. If someone wants to improve it, or to app it as a custom 'borg, or whatever else, that's fine, but I'm not willing to keep it as is and it brings down the net 'borg sprite quality to even have it as an option. 

This rework was never meant to keep all of the sprites, only the ones people loved, people don't love this one and it's hideous. I budged on the Drone because I knew people loved it. I budged on the Heavies because they're v. good sprites. These have neither of those things going for them. I'm sorry. That's why I made a much better sprite to replace it.

**Comment by Chada-1** [comment]
The DNM tag can be removed from this PR but it's still WIP.

**Comment by alsoandanswer** [comment]
Alright fine but make the torso bigger cause currently the legs are bigger than the actual body

**Comment by Chada-1** [comment]
> Alright fine but make the torso bigger cause currently the legs are bigger than the actual body

Alright I can do that part but I'll have to redo a whole lot of overlaying/etc to make it fit. So it'll be a little while until I'm caught back up.

**Comment by Chada-1** [comment]
!review

**Comment by Chada-1** [comment]
That should be my final commit until this is merged. I have nothing I can think of to add at this point 👀 Review away.

**Pull request merged**
