### PR TITLE
Adds a new alt title to janitor: "Custodial Technician"

### PR DESCRIPTION
**Pull request by hollyhocc**
Adds the alt title "Custodial Technician" to janitor, so janitors can make themselves sound ~~more important than~~ as important as they actually are!

That's all it does

### CODE REVIEW

**Comment by hollyhocc** [comment]
!review

**Comment by alsoandanswer** [comment]
https://github.com/Aurorastation/Aurora.3/pull/8324

Denied with precedent.

**Comment by hollyhocc** [comment]
sad

**Comment by hollyhocc** [comment]
68747470733a2f2f692e696d6775722e636f6d2f306a69597a764d2e706e67

**Comment by Arrow768** [comment]
MD to see if we still want to enforce the precedent

**Comment by Arrow768** [comment]
After a brief maintainer discussion we intend to uphold the previous precedent regarding alt titles having at least somewhat differing responsibilities.

**Pull request closed without merging**
