### PR TITLE
Reviving new Human Sprites

### PR DESCRIPTION
**Pull request by Sindorman**
This PR revives https://github.com/Aurorastation/Aurora.3/pull/5967

### CODE REVIEW

**Comment by Sun-Sam-San** [comment]
do the skin tones still make everyone look dead

**Comment by Sindorman** [comment]
@Sun-Sam-San Minimal yes. But you can go from cold to dark cold. Idea is to create two variants: cold(new) and warm(old) base tones which you can tweak.

**Comment by Sun-Sam-San** [comment]
are you going to tweak them to look better for darker characters? because the current skin tones look god awful past like 180, and from what i saw the new ones make everyone past 60 look actually dead

**Comment by Sindorman** [comment]
@Sun-Sam-San They look well with dark skin tones I think 
f5H9lcFjBN

**Comment by Sun-Sam-San** [comment]
they look different than i remember, but yeah they don't look too bad. could you send 170-220 though? still, the skintone we use now is weirdly red past 180. dunno if you could even change it because idk how it works

**Comment by Sun-Sam-San** [comment]
@Sindorman sir please respond

**Comment by Sindorman** [comment]
@Sun-Sam-San I have been really busy. Here are the rest
nfvs6mLIsW

**Comment by Sun-Sam-San** [comment]
> @Sun-Sam-San I have been really busy. Here are the rest
its good. thanks for posting the rest

**Comment by Sindorman** [comment]
Work continues in #7057

**Pull request closed without merging**
