### PR TITLE
Makes the groin into a non-vital organ, changes to stance handling, bloody feet bugfix.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
Antagonists may now remove groins from horny bastards and see them squirm in pain.

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
I would say this is a high priority feature, but the ERP cabal would not allow it. Fear not, as I will terrorize them by toggling Traitor on and delimbing their groins.

**Comment by NonQueueingMatt** [comment]
!review

**Review by Geevies — APPROVED** [review]
image

**Comment by NonQueueingMatt** [comment]
> 
> 
> image

My statement holds true. It is indeed vital in the DMs.

**Review by OneOneThreeEight — APPROVED** [review]
Cock and ball torture (CBT), penis torture or dick torture is a sexual activity involving application of pain or constriction to the penis or testicles. This may involve directly painful activities, such as genital piercing, wax play, genital spanking, squeezing, ball-busting, genital flogging, urethral play, tickle torture, erotic electrostimulation, kneeing or kicking. The recipient of such activities may receive direct physical pleasure via masochism, or emotional pleasure through erotic humiliation, or knowledge that the play is pleasing to a sadistic dominant. Many of these practices carry significant health risks.

**Comment by NonQueueingMatt** [comment]
This PR is now more than an anti-ERP mission.

```
- tweak: "The groin is no longer vital."
  - tweak: "Reworks how stance damage works slightly. Having no feet or no legs means you can no longer walk at all. Behaviour with only one foot unchanged."
  - tweak: "Canes no longer help you when you have no legs or feet."
  - bugfix: "Non-existant feet are no longer bloody."```

**Pull request merged**
