### PR TITLE
Medbay Overhaul Fixes

### PR DESCRIPTION
**Pull request by furrycactus**
Fixed some minor and important issues with the medical overhaul. Tested several times. If anything is wrong, it's nothing I was able to pick up on.

### CODE REVIEW

**Comment by Alberyk** [comment]
Why is it touching the sublevel?

**Comment by furrycactus** [comment]
I noticed a missing lightbulb or two and put them in.

**Comment by Arrow768** [comment]
Needs a few more changes as discussed.

**Comment by furrycactus** [comment]
travis why

**Pull request merged**
