### PR TITLE
Colored starlight bugfix.

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
This PR will make color starlight work properly. Previously, it was not defined correctly and therefore all starlight was colorless. Now starlight is defined on a per-sector basis.

### CODE REVIEW

**Comment by TheDanseMacabre** [comment]
!review

**Comment by TheDanseMacabre** [comment]
!bugfix

**Review by SleepyGemmy — APPROVED** [review]
changelog.

**Comment by WickedCybs** [comment]
Soul

**Review by WickedCybs — APPROVED** [review]

**Pull request merged**
