### PR TITLE
Hivenet Manifest

### PR DESCRIPTION
**Pull request by Geevies**
* Added a hivenet manifest, which lets Vaurca see other Vaurca that're awake.

NOT vaurca lore approved, i have to ask them first

image

### CODE REVIEW

**Comment by GMR25** [comment]
I’d be concerned of this making Vaurcae antags (and Black K’ois victims) very easy to notice, does it only show crew or is there no differentiation?

**Comment by Generalcamo** [comment]
Lii'dra at least aren't shown, so the zombies aren't an issue.

I would be concerned about other non-lii'dra antagonists. The hive net warfare implants might have an obfuscation feature perhaps?

**Comment by GMR25** [comment]
> Lii'dra at least aren't shown, so the zombies aren't an issue.
> 
> I would be concerned about other non-lii'dra antagonists. The hive net warfare implants might have an obfuscation feature perhaps?

There’s some concern to be had as well that any obfuscation would then make said antagonists more obvious in turn, as you’d have Vaurcae seeing the antagonist and then wondering “Why izn’t Hikz on the manifezzt?”

Perhaps if antagonists could freely manipulate it in some form that would be ideal.

**Comment by Geevies** [comment]
!review

**Review by DreamySkrell — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]
Doing the sorting/splicing by hive is probably faster on the React end but eh.

**Pull request merged**
