### PR TITLE
Spelling Issue Fix

### PR DESCRIPTION
**Pull request by BurgerLUA**
Changes colour to color in mental medication.

### CODE REVIEW

**Comment by Pacmandevil** [comment]
delet this

**Comment by BurgerLUA** [comment]
Most of our playerbase is american, and the original code uses "color" as the correct way as spelling things.

**Comment by tedwood3** [comment]
This is gonna be in the April Update, yeah?

**Comment by BurgerLUA** [comment]
Okay, it seems that there was a lot of debate over this and I decided that since we all have African origins, I've decided to use the language "Afrikaans" to determine the correct wording of color, which is kleur.

**Comment by Lohikar** [comment]
\> do not merge
\> merges

**Pull request merged**
