### PR TITLE
Full Odin Remap

### PR DESCRIPTION
**Pull request by TheDocOct**
Ferner set the groundwork with the arrivals remap; I've completed it. The Odin has been significantly compressed and had much of its wasted space/most frequently unused areas trimmed, while trying to maintain a feel of an actual working and living space.

Nu Transfer Wing
image

Nu Representative/Consular waiting lounge
image

Nu Civil Protection/Holding Cell/Security Disarmament Point
image

Nu Bar/Kitchen, and Administrative Checkpoint
image

Nu Central Command Copula/CCIA Offices
image

### CODE REVIEW

**Comment by TheDocOct** [comment]
!review

**Review by fernerr — CHANGES_REQUESTED** [review]
Preemptive change request, so I can walk through it all when I have the time.

**Comment by GMR25** [comment]
This is probably the best place to bring this up, as it's a mapping/spawn issue related to the Odin: 
#9826

**Comment by TheDocOct** [comment]
That is not a mapping issue and is not within the bounds of this PR, or my skillset for that matter. Try poking Geeves or Arrow about it, I dunno.

**Comment by GMR25** [comment]
It's entirely a mapping issue, though. It's derived from the roundstart spawn point being placed on the Odin instead of the station.

**Comment by TheDocOct** [comment]
No. That's not a 'mapping issue', that's intended functionality. All roles except the consular officer/corp rep (because they have their diplomatic shuttle) have the option of spawning from cryogenics, or in the Odin arrivals wing. This problem is derived somewhere in the equipment code that gives visitor their items when they pass through the wardrobmatic, not the mapping of their spawn points.

**Comment by GMR25** [comment]
It would be the only role that happens to roundstart spawn on the Odin, to which the fix is inherently in mapping itself (as the issue wasn't present when it shared assistant's spawn points) rather than reworking the wardrobmatic. Every other role has it's own unique spawn point for roundstart, and setting your join-spawn to arrivals does not change that for them.

**Review by Arrow768 — CHANGES_REQUESTED** [review]
As mentioned on discord:

- Blast door for special ops area -> over to the hallway so the commander can access the ert area directly without having to open all the blast doors.
- Checkpoint - Blast door over the external door (for the look)
- Light with wrong rotation next to the kitchen entry
- Bar - add shutters ?
- Medical - expansion (small surgery room instead of morale office)
- Central Wing - right entrance - Button only controls inner door
- Rename button "crescent checkpoint access" to something like "control wing - aft access" as the actual "checkpoint" is on the right side

**Review by fernerr — APPROVED** [review]
Good to go once my tweaks/fixes have been merged into this branch.

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
