### PR TITLE
[DNM] Everyone Poops

### PR DESCRIPTION
**Pull request by LordFowl**
Introduces waste and dehydration mechanics.

As you consume reagents that provide nutrition, you are also provided waste (Not currently equivalent to the nutrion value of the reagents.). If nutrition + waste > max_nutrition, you will feel the need to relieve yourself, and you will be slowed appropriately, to a max of +4 tally to your movement_delay, depending on how far over you are.

To relieve yourself, you must find a toilet and mount it. Toilets have been refactored into disposal units, and the toilet will automatically convert your waste into a doggy bay full of sterilized, family-friendly fertilizer, which will be sent to the crusher. Waste will also be reduced by 60 units whenever you vomit, similar to nutrition.

Hydration tracks the value of a given mob's hydration, and currently it is reduced the same way nutrition is (moving, running, existing) but at a tenth of the rate, and all crew start at full hydration as opposed to random nutrition. However, whenever you relieve yourself your hydration will be reduced, and there will be many reagents that reduce (and of course increase) your hydration by a given amount. Hydration, unlike nutrition, will have tangible effects (such as dizziness, lethargy, seizures, death, etc.), and as such becomes  a medical concern. Unlike nutrition, crew should not become dehydration in the course of a round by simply existing, or even moving a lot (hence why these reduce hydration at a tenth of the rate as nutrition decreases).

Toilets retain their previous functionalities (swirlies, cisterns), but now function also as limited disposal chutes. Objects of size greater than 2 do not fit, neither do grabbed or dragged mobs.

Waste will result in little additional infrastructure - toilets will be connected to the main disposals loops.

Hydration will result in current sources of water (showers, sinks, water tanks, etc) to be rebalanced so as to not be infinite or practically infinite. Ultimately, the station would receive a central water reservoir and devices to create water from oxygen, hydrogen, and energy. Anything that dispenses water infinitely currently will become connected to this water reservoir, either abstractly or with honest to goodness pipes if I really go crazy.

- [ ] Add in a UI for hydration
- [ ] Modify the nutrition UI to display when you need to poop
- [ ] Code in hydration sources and dehydration sources.
- [ ] Code in maluses for dehydration.
- [ ] Code in the water reservoir system
- [ ] Get into contact with lore-devs concerning species' dehydration rates and maybe even unique facts about their poop.
- [ ] Map changes
- [ ] Testing
- [ ] Balance
- [ ] Changelog

### CODE REVIEW

**Comment by skull132** [comment]
Hydration is debatable. This is a no, however. We don't need to represent the digestive tract this accurately.

**Comment by LordFowl** [comment]
shit

**Comment by OneOneThreeEight** [comment]
What a travesty.

**Comment by mattroks101** [comment]
Interbay rip off!

**Comment by BurgerLUA** [comment]
this will go good with my burrito pr #4079

**Comment by 77seven77seven** [comment]
wtf speed merge

**Pull request closed without merging**
