### PR TITLE
Unapologetic Mind Control Buffs

### PR DESCRIPTION
**Pull request by MarinaGryphon**
* Makes wizard mind slaves more akin to vampire thralls.
* Extends the cleric resurrection time limit to 30 minutes instead of 5.

### CODE REVIEW

**Comment by OneOneThreeEight** [comment]
Should make it 20 minutes, since that is the respawn timer as a ghost

**Comment by Kaedwuff** [comment]
30 seems fine to me.

**Comment by Geevies** [comment]
You should use !review, you dummy.

**Comment by skull132** [comment]
Changelog missing.

**Pull request merged**
