### PR TITLE
More Skrell food and drink

### PR DESCRIPTION
**Pull request by WhatsUpBrotendo**
Adds:

Jylara, a puree snack/junk food item from the Federation, to the snack machine. 
A recipe for creating a "fresh" version of jylara by mixing four dyn leaves.
Skrell alcohol. Just beer and wine for now.

Fixes:

Wulumunusha and Fjylozyn not having proper seed packet sprites.

Credits to Ryverstyx for the alcohol sprites.

image

### CODE REVIEW

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
I think it would be better if these new foods would be made into a new vending machine instead rather then bloating the current vending machines even further.

Something like the Zo'ra Cola vending machines.

**Comment by WhatsUpBrotendo** [comment]
Adding a new vending machine for four new items isn't ideal considering it'd mean taking up more real estate around the ship.

This is how the getmore chocolate corp machine looks now 
image

And this is what it'd look like with these items added
image

I don't see this as being bloated.

**Comment by alsoandanswer** [comment]
It's for precedence, mostly. 

Ideally, the snack machine should have generic items since it'll be on away sites and events.
It'll be pretty weird to see Skrell food in a vending machine for an Unathi planet, for instance.

For places to put the vendors, I suggest putting them near existing ones, either that or replace some Zo'ra cola machines. They're quite plentiful in the NBT map so I think a couple less wouldn't hurt. If you need a sprite for the machine, I can help you make one, just DM me.

**Comment by WhatsUpBrotendo** [comment]
Using your argument, it'd be strange to see any vegan food in the snack machine if we went to a Unathi-dominated planet, which would include more than a few existing items. You could make similar arguments for a lot of the items that are already in the snack machine.

I'd rather not create a brand new vending machine and take up more space around the ship just for four food items, or replace existing vending machines with a new vending machine. If your issue is with them appearing on away sites and events I'd look into creating new vending machines for those cases.

**Review by alsoandanswer — APPROVED** [review]
Sounds like a good idea, honestly. Vendors are a pretty good and easy way to have little tidbits of lore introduced here and there.

**Comment by NonQueueingMatt** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
