### PR TITLE
Cult Tweak + Gamemode Start Failure Message Tweak

### PR DESCRIPTION
**Pull request by Geevies**
* Reduced the players needed to start a game of Cult to 2, down from 4.
* Tweaked gamemode start failure messages to include the name of the gamemode that failed to start, as well as additional info on the number of people eligible to join.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by SleepyGemmy** [comment]
this PR is reverting the changes done by #14608. up to maintainers if they wish for the gamemode to show again.

**Comment by DreamySkrell** [comment]
I'd really suggest to separate these two changes. Cult tweak in one PR, gamemode failure message in another PR.

**Comment by NonQueueingMatt** [comment]
Separate the changes as Dreamy said. You also need to edit the amount of players required or UTs will fail.

**Pull request closed without merging**
