### PR TITLE
Fixes Window Blending 2, Electric Boogaloo

### PR DESCRIPTION
**Pull request by alsoandanswer**
dreamseeker_uVC019Vbjy
dreamseeker_uupQRiOtzN

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!bugfix

**Comment by alsoandanswer** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by SleepyGemmy** [comment]
for anyone curious what this PR does.
image
image
note that the right (the new sprite) blends much better.

**Review by SleepyGemmy — APPROVED** [review]

**Comment by SleepyGemmy** [comment]
for anyone curious what this PR does.
image
image
note that the right (the new sprite) side blends much better.

**Pull request merged**
