### PR TITLE
Fixes food reagents.

### PR DESCRIPTION
**Pull request by MarinaGryphon**
I accidentally had a bunch of duplicate entries. This should merge all of them.

### CODE REVIEW

**Comment by MarinaGryphon** [comment]
!bugfix

**Comment by MarinaGryphon** [comment]
!review

**Comment by skull132** [comment]
> what am I missing and why is this a bugfix and why is this lacking a changelog.

**Comment by MarinaGryphon** [comment]
> > what am I missing and why is this a bugfix and why is this lacking a changelog.

There are no player-facing changes, everything works as it did before save for bugfixes.
The base type `/burger` was not used, so now it is; burgers now use inheritance properly, fixing inconsistencies with taste and stuff.
Accidental duplicate var entries were consolidated into one entry to avoid them overriding each other.
The order of the burger, ratburger, and syntiburger recipes were changed to make them properly work. Before, the plain burger recipe would take precedence.

**Pull request merged**
