### PR TITLE
Add a Vaurca Projector to the loadout and allows Vaurca to take the Nralakk projector

### PR DESCRIPTION
**Pull request by connorjg1**
Adds a Vaurca projector to the loadout which takes after the Skrell Projector, allowing a selection of pre-set locations within Queen Vaur's realm to peer into and loop messages from. Designed to bring a bitesize slice of Vaurca lore from the wiki and onto the vessel. 

Done with approval from the Vaurca lore-team. It's possible I've broken something as I've never done a PR of this scale before but it seemed to work just fine in my testing so here's hoping. 

This also with Skrell/Vaurca team approval allows Vaurca to take the nralakk projector from the loadout.

### CODE REVIEW

**Comment by connorjg1** [comment]
!review

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
This looks like a lot of code is copypasted from the nralakk projector. Make this a subtype of the nralakk projector that instead reuses its code.

**Comment by connorjg1** [comment]
> This looks like a lot of code is copypasted from the nralakk projector. Make this a subtype of the nralakk projector that instead reuses its code.

Addressed

**Review by RyverStyx — APPROVED** [review]

**Comment by connorjg1** [comment]
Closing so I can solve the merge conflict without breaking everything.

**Pull request closed without merging**
