### PR TITLE
White Shoes in the Med Sublevel Begone - Medical Shoes are in

### PR DESCRIPTION
**Pull request by WickedCybs**
There was a pair of white shoes just randomly on the floor of med's staff wing where they get equipment for some reason. This PR removes it.

### CODE REVIEW

**Comment by WickedCybs** [comment]
!review

**Review by fernerr — CHANGES_REQUESTED** [review]
They're just not there randomly, they're there to help imply that it's a changing room of sorts, along with the chair. If you want you could help sell the lived in nature more by changing it into a pair of medical shoes(as they didn't exist when I put them there) and moving their position somewhat.

**Comment by WickedCybs** [comment]
> They're just not there randomly, they're there to help imply that it's a changing room of sorts, along with the chair. If you want you could help sell the lived in nature more by changing it into a pair of medical shoes(as they didn't exist when I put them there) and moving their position somewhat.

Honestly, it was always kind of confusing to me when I played in medical that there would just be white shoes there. Will see about changing it to the purpose-built shoes medical actually wears, changing where it appears may be a bit beyond me but will see about this too.

**Comment by fernerr** [comment]
Feel free to message me if you need any help. For example pixel_x/pixel_y controls where an object is in a turf.

**Comment by WickedCybs** [comment]
!wip

**Comment by WickedCybs** [comment]
Changed the shoes to medical shoes. Not going to change the placement, for now at least. I plan on looking into mapping properly first instead of tweaking the code for stuff.

**Comment by WickedCybs** [comment]
!review

**Review by fernerr — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
