### PR TITLE
Allow branded IPCs wear voidsuits

### PR DESCRIPTION
**Pull request by Sindorman**
- This PR fixes branded IPC not being able to wear a voidsuit(bugfix)

### CODE REVIEW

**Comment by Sindorman** [comment]
!review

**Comment by Lohikar** [comment]
This was intended behavior.

**Comment by Lohikar** [comment]
Still not a bug, it's a tweak/change.

**Comment by Sindorman** [comment]
@Lohikar It is kinda bug as Lore team said that Industrial G1 and G2 should have still be able to wear suit even though it is not required.

**Comment by Lohikar** [comment]
Last I checked the lore team did not get to determine what is a bug and what is not.

When I wrote the code the intent was that industrials would not be able to wear normal suits (partially for balance reasons), instead requiring purpose-built suits that only fit them. This didn't end up happening so I'm not opposed to this change, but either way this is not fixing a bug as this was intended behaviour.

**Comment by Sindorman** [comment]
@skull132 I have remade PR so that it just lets Bishop frame wear voidsuits. And allow all frames wear mercs and wizard voidsuits, this was approved by Cake.

**Pull request merged**
