### PR TITLE
Make Exodus Great Again

### PR DESCRIPTION
**Pull request by furrycactus**
Beginning of the process to catch up the Exodus map on like 3(?) years of developments. This is probably gonna be a bit of a mess.

### CODE REVIEW

**Comment by furrycactus** [comment]
!review

**Comment by Karolis2011** [comment]
I am 99% sure peaple won't love changes.

**Comment by fernerr** [comment]
I've been taking a long look and have seen plenty of the changes, but I would like a brief description of the areas you've touched.

**Comment by skull132** [comment]
Ultimately, just for reference, the TCFL being functional is probably a low priority objective. The emergency shuttle, tho, is a point worth review.

**Comment by fernerr** [comment]
Yeah, agreed.

**Comment by fernerr** [comment]
All issues presented by me have been addressed. With tcfl and emergency shuttle both working.

**Comment by furrycactus** [comment]
A quick summary of the places I touched off the top of my head:

- Engine room tweaked so it uses gas coolers and stuff
- Shields set up in the Bridge substation
- Psychology moved slightly and made bigger to account for the treatment machines
- Chemistry, toxins, xenobotany, other areas like that all given borosilicate windows
- Representative office put near the bridge, detective's office and forensics moved around a little bit
- Red dock and the transfer shuttle changed to match the transfer shuttle on the Aurora map
- Exodus CentComm changed to match Aurora CentComm better
- Supermatter has a catchment zone for when the crystal is ejected to prevent it from looping around and exploding against security or the holodeck
- Toxins test range made more resilient
- Countless cruel and unnecessary blobstart markers removed. I thought it was a bit unkind that a blob could appear literally in the middle of a department, or underneath someone's feet while they're taking a shit in the bathroom. People go there to AFK.
- Windows around the representative's shuttle dock electrified, the cockpit for the shuttle has the same access requirement as their airlock on CentComm. Accounting for it being in a less secure spot on the Exodus, to try and prevent wanton theft of their shuttle "just because". It's still possible, but it can't be done by just anybody.

There's some other things I'm pretty sure, but I can't remember every little thing. I should've documented them as I went. Sorry.

**Comment by skull132** [comment]
Ye duplicate firedoor.

go to `code\game\machinery\doors\firedoor.dm` and change the start of the Initialize proc (line 60+) to look like this:
```dm
/obj/machinery/door/firedoor/Initialize(var/mapload)
	. = ..()
	for(var/obj/machinery/door/firedoor/F in loc)
		if(F != src)
			crash_with("Duplicate firedoors at [x]-[y]-[z]. Deleting one.")
			QDEL_IN(src, 1)
			return .
	var/area/A = get_area(src)
	ASSERT(istype(A))
```
Then compile and run the map. This will create a runtime log at the start. Ultimately tho, you could also commit this log. It'll make discovering these errors in the future easier.

**Pull request merged**
