### PR TITLE
Spiderbots can no longer pull all the things

### LINKED ISSUE #13909: Spiderbots can drag anything (and cannot stop dragging)
image
THere is nothing the spiderbot can't drag, if it is physically possible to do so.

There is also no button for spiderbot to stop pulling.

### PR DESCRIPTION
**Pull request by Afya212**
Title.
Fixes #13909

### CODE REVIEW

**Comment by Afya212** [comment]
!bugfix

**Comment by Afya212** [comment]
!review

**Comment by Afya212** [comment]
> Can they stop pulling?

They always could. Either by click drag on it again or by using the delete hotkey.

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by NonQueueingMatt** [comment]
Not a bugfix, since you changed their mob size.

**Pull request merged**
