### PR TITLE
Crowbar in your pocket be-gone

### PR DESCRIPTION
**Pull request by LynxSolstice**
Nerfs the size of the crowbar so it no longer fits in pockets. That's it.

### CODE REVIEW

**Review by FluffyGhoster — APPROVED** [review]

**Comment by LynxSolstice** [comment]
!review

**Comment by Arrow768** [comment]
Why is this something that's needed?

**Comment by LynxSolstice** [comment]
> Why is this something that's needed?

The crowbar has more melee damage than a maglight, the same damage as a rescue axe, and can fit in pockets, despite the real tool being physically unable to do so.

**Review by NonQueueingMatt — APPROVED** [review]
seems fair

**Pull request merged**
