### PR TITLE
Unto The Somewhat Known - The Coalition Survey Ship

### PR DESCRIPTION
**Pull request by RustingWithYou**
Adds a new away site with ghostroles, the **COC Survey Ship**. This ship is a pan-Coalition scientific survey effort, with a crew from across the COC. 

The crew roles are open to humans & offworlders, IPCs and Tajara. The captain role is human/offworlder only. 

Map done by @courierbravo, with some tweaks & additions by me, Rusting.

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Comment by Greenjoe12345** [comment]
with the shape of that shuttle, will it be able to dock anywhere? I don't know if anyof the Horizon docks would support it.

**Review by DreamySkrell — DISMISSED** [review]
I am pretty sure the automatic airlock spawners will not work when used as docks. As in, they won't automatically close and open when docking/undocking. Any airlock that is used as a dock should be manually mapped in with the tags and etc.

**Comment by RustingWithYou** [comment]
> I am pretty sure the automatic airlock spawners will not work when used as docks. As in, they won't automatically close and open when docking/undocking. Any airlock that is used as a dock should be manually mapped in with the tags and etc.

The airlock has been replaced

**Comment by DreamySkrell** [comment]
> > I am pretty sure the automatic airlock spawners will not work when used as docks. As in, they won't automatically close and open when docking/undocking. Any airlock that is used as a dock should be manually mapped in with the tags and etc.
> 
> The airlock has been replaced

image

There is still this one here.

**Review by NonQueueingMatt — APPROVED** [review]

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
image


1. This shuttle should be updated with the newly added directional shuttle landmarks. It should look roughly as in the screenshot - so right now the position of the landmark is correct, just needs its dir changed.
2. The airlock should be moved forward, so the doors are where the "SHUTTLE" rectangle is in the shuttle landmark sprite. Currently, this shuttle could never properly dock to anything, because, if the doors of the ship and the dock both opened, it would vent air into space.

**Review by DreamySkrell — APPROVED** [review]

**Pull request merged**
