### PR TITLE
Full rename of all real chems to bone apple tea'd versions.

### PR DESCRIPTION
**Pull request by Chada-1**
As a continuation of #9389
As a bonus, any drugs that mentioned their IRL counterpart in their description now describe their predecessor as ancient, and the new ones as modern. The biggest difference here is just the Antihistamine which was given a full new name. They're similar enough that they'll be recognized (most of them) but different enough for us to call our own and not care what the real medicines are/do since these are our sci-fantasy versions just inspired by them.

[Feedback thread here:](https://forums.aurorastation.org/topic/14613-renamed-medical-chems)

### CODE REVIEW

**Comment by Snakebittenn** [comment]
Why is any of this necessary.

**Comment by MarinaGryphon** [comment]
You didn't use mapmerge and therefore your mapping fixes are invalid. Please install the mapmerge commit hook and try again, or use StrongDMM in tgm mode for edits.

**Comment by Chada-1** [comment]
>It was a mistake to use real life chemicals on the grounds of "realism", especially when the chemical doesn't actually act realistically to how it does in real life.

>The solution to this problem is literally just to don't. We should use pretend drugs in our pretend game and we can use them in any way we want."

> A full hearted "Yes". Fuck debates about "THIS ISN'T HOW IT WORKS IN REAL LIFE REEEE!"

None of these apply only to Norepinephrine.
@Snakebittenn

**Comment by tomekkiel** [comment]
Seems unnescessary to me. Would just create unneeded confusion.

**Comment by Snakebittenn** [comment]
Most of these names are still cringe. 'Antihistamine = Antihestamil' does not make literally any sense. A histamine is an organic compound, not a medicine. Most of these need to be changed back.

**Comment by Chada-1** [comment]
> Most of these names are still cringe. 'Antihistamine = Antihestamil' does not make literally any sense. A histamine is an organic compound, not a medicine. Most of these need to be changed back.

Not going to happen. FInd a different name or it stays.

**Comment by Snakebittenn** [comment]
Yes, going to happen. It's a class of medications. Change it back.

**Comment by Chada-1** [comment]
> Yes, going to happen. It's a class of medications. Change it back.

No because if you read the medications description it outright states it's a antihistamine med. It was Diphenhydramine (Benadryl) before. It's literally not going to happen.

**Comment by Snakebittenn** [comment]
It's literally going to happen. Alienating new players trying to learn Medical chemicals for some completely unknown reason is not going to fly here.

**Comment by N8-Toe** [comment]
this will create unnecessary confusion to solve what I believe is a non issue

**Comment by Chada-1** [comment]
> this will create unnecessary confusion to solve what I believe is a non issue

The only real confusion it's going to create is the small period inbetween updating the wiki, which I'll do myself :eyes:
The rest of the changes are close enough to the old names that people will absolutely instantly recognize them.

**Comment by Snakebittenn** [comment]
This should have a feedback thread.

**Comment by Chada-1** [comment]
> This should have a feedback thread.

This shouldn't have a feedback thread anymore than the Inaprovaline reboot.

**Comment by alsoandanswer** [comment]
Despite this being well intentioned, this misses the entire point.

The point was that noneprephine was harder to recognize than inaprovaline, and that was that.

This is completely unnecessary. Please make a feedback thread.

**Comment by Chada-1** [comment]
> Despite this being well intentioned, this misses the entire point.
> 
> The point was that noneprephine was harder to recognize than inaprovaline, and that was that.
> 
> This is completely unnecessary.
That's not what was said by Skull, the actual PR creator, and me. :eyes:

>"It was a mistake to use real life chemicals on the grounds of "realism", especially when the chemical doesn't actually act realistically to how it does in real life.

>"The solution to this problem is literally just to don't. We should use pretend drugs in our pretend game and we can use them in any way we want."

>"A full hearted "Yes". Fuck debates about "THIS ISN'T HOW IT WORKS IN REAL LIFE REEEE!"

These quotes don't say that.

**Comment by furrycactus** [comment]
I can see some merit to renaming the psychiatric medications, because none of them are realistic either and have potentially dangerous implications if taken incorrectly in real life. However, because traumas aren't a thing anymore (for the most part anyway, as far as I'm aware?) we could probably much easier actually tweak their behaviour to be realistic, and mostly for flavour instead of actual mechanical things, with primarily messages in chat and more realistic side effects. 

Antihistamine meanwhile, well, the term "antihistamine" is just a drug class and not a specific chemical or brand name, just like "analgesic" is a drug class for painkillers. It'd be the equivalent of calling paracet/trama/oxy "analgesic". Antihistamine is okay, because it clearly states what it does, it suppresses histamines, which cause things like sneezing, itching, nasal congestion, all those things.

I'm of two minds on this after some consideration. With Norepinephrine, it was hard for it to actually be realistic and also carry out its actual intended purpose, if not actually impossible to do that. With most of these other ones, they can be made actually realistic with minor tweaks like "if you take like 5 paracetamol pills you'll probably get sick" and things like that. Some already are kind of realistic, like oxycodone, it'll fuck you up when you're on it and if you drink with it you'll basically die. We have a more robust framework for side effects now that could easily be utilized to make them more realistic without gimping medical in any way, and we can translate the danger of misuse quite clearly if we're worried about giving younger people the wrong impression with video game medicine pill. But we still have the issue of maybe too much realism vs. fun space game. I don't know. I can see both sides here pretty clear and I'm kind of unsure now.

**Comment by MarinaGryphon** [comment]
> With Norepinephrine, it was hard for it to actually be realistic and also carry out its actual intended purpose, if not actually impossible to do that.

I actually had, and still have, a PR that would do that. However I still think think using the name norepinephrine is kind of dumb.



> With most of these other ones, they can be made actually realistic with minor tweaks like "if you take like 5 paracetamol pills you'll probably get sick" and things like that.

This is easy to implement as well. The liver and kidneys should have the ability to metabolise only a certain amount of chemicals in a certain period, and giving someone too much acetaminophen can cause liver toxicity, as well as combining it with other drugs. These would provide more mechanical depth and combat chem mix metas (or at the very least force players to develop new ones) in a way simply changing the names of chemicals wouldn't.

Effectively, I fail to see what this adds to the server; if the issue is that something is unrealistic, and it's not difficult to make it realistic, how is changing "tramadol" to "traumadil" (which sounds like a medication you'd use for treating traumatic injury, or maybe some kind of tramadol-krokodil cocktail??) fixing the core issue?

**Comment by Chada-1** [comment]
> However, because traumas aren't a thing anymore (for the most part anyway, as far as I'm aware?) we could probably much easier actually tweak their behaviour to be realistic, and mostly for flavour instead of actual mechanical things, with primarily messages in chat and more realistic side effects.

This falls into the same thing that if we didn't have them be real world chems, we can make them more interesting and fun.

> Antihistamine meanwhile, well, the term "antihistamine" is just a drug class and not a specific chemical or brand name.

I agree with this, but it's not that the 'Antihistamine' I renamed isn't an antihistamine, it IS an antihistamine, It's just an actual made up brand now instead of 'Antihistamine but named Benadryl everywhere it appears' (which is how it was), saying it's not an antihistamine because I made up a brand for it just isn't how it is in the code.

> I'm of two minds on this after some consideration. With Norepinephrine, it was hard for it to actually be realistic and also carry out its actual intended purpose, if not actually impossible to do that. But we still have the issue of maybe too much realism vs. fun space game. I don't know. I can see both sides here pretty clear and I'm kind of unsure now.

We can add more interesting and fun side effects if we aren't using actual real world chems is the thing, if I added side effects to Norepenephrin, even if they were a lot of fun, which didn't exist on the actual medicine, I'm basically misrepresenting it as a medicine.

**Comment by Chada-1** [comment]
> How is changing "tramadol" to "traumadil" (which sounds like a medication you'd use for treating traumatic injury, or maybe some kind of tramadol-krokodil cocktail??) fixing the core issue?

The description of Tramadol rn in code literally says it's for that.

**Comment by MarinaGryphon** [comment]
> > How is changing "tramadol" to "traumadil" (which sounds like a medication you'd use for treating traumatic injury, or maybe some kind of tramadol-krokodil cocktail??) fixing the core issue?
> 
> The description of Tramadol rn in code literally says it's for that (Treating traumatic injury) and read the above post.

Tramadol is a painkiller, it is not used for TREATING traumatic injury, it is used to alleviate pain associated with traumatic injury. I read the above post, it has nothing to do with anything I said.

**Comment by Chada-1** [comment]
> > > How is changing "tramadol" to "traumadil" (which sounds like a medication you'd use for treating traumatic injury, or maybe some kind of tramadol-krokodil cocktail??) fixing the core issue?
> > 
> > 
> > The description of Tramadol rn in code literally says it's for that (Treating traumatic injury) and read the above post.
> 
> Tramadol is a painkiller, it is not used for TREATING traumatic injury, it is used to alleviate pain associated with traumatic injury. I read the above post, it has nothing to do with anything I said.

It has to do with what purpose this serves. We can do more than what the drug does IRL if we don't base them directly on actual drugs and the description in code doesn't agree with you, it's p. clearly saying the opposite here. That's the thing. That's the problem.

**Comment by Dhul-Qarnayn** [comment]
Cringus. This isn't needed or asked for at all, and it makes us look like a preschooler trying their hand at recreating the names on mom's pill cabinet. It'd be painful to deal with ingame and we've no way to explain it IC. Where's the feedback thread.

**Comment by MarinaGryphon** [comment]
> It has to do with what purpose this serves. We can do more than what the drug does IRL if we don't base them directly on actual drugs and the description in code doesn't agree with you, it's p. clearly saying the opposite here. That's the thing. That's the problem.

You're arguing that we should change the name based on an inaccurate description, on the premise that at some unspecified time in the future we may change it. I see no reason why that name change should be made pre-emptively without the additional effects being added as well.

**Comment by alsoandanswer** [comment]
i think we've stepped too far in rhetoric here.

barring any real life considerations and whatever the hell's being discussed here

these names sound like nonsense. they're terrible hard to spell and would **suck to actually play in-game.** 
argument could be said about our current ones being nonsense as well, but the fact we have to re-learn them is another nail in the coffin.

this is basically enough to warrant this not being added.

**Comment by Chada-1** [comment]
Making the feedback thread, I guess.

**Comment by Chada-1** [comment]
!review

**Comment by alsoandanswer** [comment]
commenting this at request of Chada1
Discord_VO4SLhhhue

**Comment by skull132** [comment]
Conversation unlocked so that Chada can continue using the bot to administer the PR himself. Anyone who wishes to continue discussing the non-technical aspects of this PR is expected to do so in the [feedback thread](https://forums.aurorastation.org/topic/14613-renamed-medical-chems). Failure to comply will result in a repo ban.

**Comment by Chada-1** [comment]
This PR is in the final stages at this point, but it still needs tweaking/etc before it can be merged, so I'm removing my review tag.
!wip

**Comment by Chada-1** [comment]
!wip

**Comment by skull132** [comment]
And for the sake of transparency:
- All conversation that took place on this PR has been marked as off-topic or outdated/resolved, since it has been migrated over to the [https://forums.aurorastation.org/topic/14613-renamed-medical-chems](feedback thread).
- I have elevated one particular chain of comments for review by maintainers for additional moderator actions.

**Comment by skull132** [comment]
Let's try this like, one more time. !wip

**Comment by Chada-1** [comment]
As of now this PR is ready for review, all of the descriptions are fine tuned according to the people helping me 👀

**Comment by Chada-1** [comment]
!review

**Pull request merged**
