### PR TITLE
The Re-bootening

### PR DESCRIPTION
**Pull request by alsoandanswer**
Removed Thigh-high and Knee-high jackboots. They are a pain in the ass to maintain, and were borderline fetish-bait material. Not like you could notice the difference anyway, it was literally one or two pixels, and our spessmen's legs are already short enough for it to not matter.

Anyway. Tweaks the jackboots and oxfords to match the color palettes of the uniforms better. Also, gives the RD, CMO, and OM oxfords too. Because they're command. And they deserve it.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by FayeLovesU** [comment]
In what world are knee high boots “fetish bait material”? The thigh high boots are kind of impractical and I don’t really care about their removal, but the knee high boots are a good item and I don’t see why they should be removed, nor do I see how they’re somehow “fetish bait.”

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
Don't get rid of the knee high boots: those are fine.

**Comment by SleepyGemmy** [comment]
since the jackboot colour has been mentioned; why are the oxfords being desaturated and the black oxfords being made into a gunmetal grey? they're fine as-is.

**Comment by RyverStyx** [comment]
If anything. Make them recolorable.

**Comment by WickedCybs** [comment]
Why must the actual black options be totally replaced instead of adding the gray boots/shoes as an additional option instead as well? I don't see any benefits to eliminating a common colour that people have already worked into their loadouts for the sake of one or two gray uniforms, which people still ditch gray accessories on or ditch altogether.

**Comment by NewOriginalSchwann** [comment]
I don't know what fetish has the hots for wellingtons, but I do agree that the thigh-high boots can probably go as we don't have hussars on the ship. That aside, I don't get why so many black items, such as the Zavod uniforms and berets, are getting recolored to this odd off-grey color that's more blue than black. They look like they were put in the wash with bleach by mistake.

**Comment by FayeLovesU** [comment]
Removing black boots from the game would fuck with a lot of peoples' loadouts, mine included. Please don't change their color, I do not think anyone likes this strange new grey-ish palette.

**Pull request closed without merging**
