### PR TITLE
Berry Redelightful

### PR DESCRIPTION
**Pull request by Xxxxyobdab**
Adds and changes berry type produce to have unique juices.

Need icons for the strawberry and raspberry plants/produce.

- Strawberry Juice, Plant, Produce, Syrup, Seed
- Raspberry Juice, Plant, Produce, Syrup, Seed
- Black Raspberry Juice, Produce, Syrup, Seed
- Blue Raspberry Juice, Produce, Syrup, Seed
- Deathberry Juice, Syrup
- Glowberry Juice, Syrup
- Ylphaberry Juice, Syrup
- Dirtberry Juice, Syrup
- Blueberry Juice, Syrup
- Poisonberry Syrup

All syrups use the standard mix of (3 units of Simple Syrup + 2 units of juice) to make 5 units of specific syrup.

- Added a Rich Coffee plant
- Add Rich Coffee Beans produce
- Added Dark Coffee Grounds reagent

Fixed recipe for coffee:
  - Was: (Espress + water) but americano already used it so it was a conflict.
  - Now: Coffee grounds + water
Fixed recipe for espresso:
  - Was: (Coffee grounds + water)
  - Now: Dark Coffee Grounds + Water

### CODE REVIEW

**Comment by Xxxxyobdab** [comment]
!review required

**Comment by alsoandanswer** [comment]
Something's wrong with your changelog. You need to do it again.

**Review by Alberyk — DISMISSED** [review]
Do not delete the changelogs or replace one of them with your own. Create a new file for your changelog.

**Comment by Xxxxyobdab** [comment]
oh, well how do you want me to fix that then? Copy paste the current ones. or delete the changelog folder and restore from master then re-add my own?

**Comment by Xxxxyobdab** [comment]
there i think its fixed now

**Review by Arrow768 — APPROVED** [review]

**Review by Arrow768 — APPROVED** [review]

**Review by JohnWildkins — APPROVED** [review]

**Pull request merged**
