### PR TITLE
Temperature Pack Major Buffs

### PR DESCRIPTION
**Pull request by Ben10083**
Temperature Pack temperature changes majorly increased to fix https://github.com/Aurorastation/Aurora.3/issues/16716

10 degrees of temperature for blizzard/volcano pack were far too little, I thought at first temperature code was being weird but appears fine.

### CODE REVIEW

**Comment by Ben10083** [comment]
!review

**Comment by FluffyGhoster** [comment]
MD as this would be a big buff, especially for IPCs that use overheating as a mechanic to limit running around and being exposed to space

**Review by FluffyGhoster — APPROVED** [review]
(Code is fine btw)

**Comment by NobleRow** [comment]
You could have them not work for IPCs somehow if that helps clear things up on that front. Was planning on adding a IPC item in the future for their own cooling anyway.

**Comment by Arrow768** [comment]
You need to ensue that they do not work on any IPC as IOCs have a different system for regulating heat and heat is a major aspect of IPC Balance

**Comment by Ben10083** [comment]
After testing, I see no indication that IPCs are affected by temp pack (their temperature doesnt even change). I did reduce the overall effect the packs do as 50 kelvin _was_ alot and excessive.  Cold/Warm packs are 20, Volcano/Blizzard are 30

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
