### PR TITLE
Removes borgs

### PR DESCRIPTION
**Pull request by LordFowl**
Following a conversation in the Discord, I realized that I don't like borgs and think they're annoying. Typically they're just used to meme, and their lore is pretty wack. Even AIs are better than this.

### CODE REVIEW

**Comment by dragoslava** [comment]
Im abit hesistant on this, however Im gonna talk to kyres about a potential better solution

**Comment by Kaedwuff** [comment]
Assuming this is a serious change and not a joke one, this is really sloppy.  All you've done is removed borgs themselves.  Problems not resolved by this change:

-Why are posibrains still in the game? There is no point in having them in the game if using them just makes you confusedly try and fail to find the activation switch.
-An entire section of robotics is dedicate to borg creation.  It's still there, except now it sits there uselessly for no reason. You'll need to remap robotics.
-You've completely dropkicked a good portion of the malf AI round functionality. You're going to need to rewrite it so that borgs are not essential to their round progression, and provide alternatives to their explicitly borg-centric abilities.

To be honest unless you want to put in a lot of work you can't just remove a piece of the station functionality like this so arbitrarily.  Unlike removing a player species, borg and borg creation are built into the station itself, their ability to spawn is a lot more complicated and far reaching.

**Comment by chaoko99** [comment]
Could always do the goonstation thing and just make them into lawed IPC type things.

**Comment by Kaedwuff** [comment]
> Could always do the goonstation thing and just make them into lawed IPC type things.

Alternatively you could just start enforcing Borg behavior to be less stupid.

**Comment by chaoko99** [comment]
Also fair, but my idea means less spaghet

**Comment by ben10083** [comment]
Does this include robot and cyborg?

**Comment by Kaedwuff** [comment]
> Does this include robot and cyborg?

Yes. Those are just both alternate titles of the cyborg role which he removed, and posibrains along with mmi's have been disabled.

**Comment by HeyBanditoz** [comment]
Include me in the screenshot pls

**Comment by Arrow768** [comment]
If this is actually something serious, then it needs to be done properly and not half-assed.
The points brought up by Kaed stand and a feedback topic is required

**Comment by TehFlaminTaco** [comment]
Low Effort PR made out of salt.

Such a big change *at the very least* needs an in game poll, and a good PR.

**Pull request closed without merging**
