### PR TITLE
Makes use of the terminal sprites for SM and INDRA engine rooms.

### PR DESCRIPTION
**Pull request by furrycactus**
I understand this might be a bit contentious, but I hope this proposal can at least be heard out. 

Essentially it applies the bay-style terminals that were added recently to the engine-specific, non-modular computers (INDRA Core Control/Fuel Injection/Gyrotron/Engineering Camera Monitors/Atmos Monitors) in the monitoring rooms for the Supermatter and INDRA reactor. It adds new subtypes for these consoles instead of outright replacing them, so any consoles that serve the same purpose that are outside of these engine rooms are unaffected and still make use of the holo-screen appearances. My argument is that it provides a better aesthetic for a reactor control room, particularly for the INDRA (I'm a little less sold on the Supermatter one), and given that they're specialised pieces of equipment and only in two places, I don't think it will cause much of a clash with the rest of the ship in terms of art style. If anything I think they fit quite well in their locations, particularly with the tables. Below are some examples.

dreamseeker_E1IHSUvA3z

https://github.com/Aurorastation/Aurora.3/assets/41561534/44e27e8b-e1d4-48d9-ae35-6840bc06cc66

(As I said, I'm a little less sold on the Supermatter one, but I feel that it works particularly well for the INDRA, particularly because these consoles had a RUST-specific screen available, which I've applied to the gyrotron console.)

### CODE REVIEW

**Comment by alsoandanswer** [comment]
Looks fine to me.

**Review by SleepyGemmy — APPROVED** [review]

**Comment by SleepyGemmy** [comment]
!review

**Review by DreamySkrell — APPROVED** [review]
looks nice (code and mapping looks ok too)

**Comment by furrycactus** [comment]
Nice. I'll fix up the CI Suite thing a bit later once I'm feeling a bit better.

**Comment by furrycactus** [comment]
I have no idea why these camera tags are acting up because I didn't touch them but I'll have a lil looksee at them.

**Comment by furrycactus** [comment]
I don't understand why the CI Suite is still failing.

**Comment by furrycactus** [comment]
Okay it's fixed thank god.

**Review by alsoandanswer — APPROVED** [review]

**Pull request merged**
