### PR TITLE
Replaced Flash with Pepperspray for robot modules

### PR DESCRIPTION
**Pull request by ben10083**
Due to the flash no longer being an effective self defense tool, I have replaced it with pepperspray (hopefully did it right, please double check) 

Security, Combat, and Syndicate modules still have the flash, but have pepperspray now.

### CODE REVIEW

**Comment by Alberyk** [comment]
Remove the syndicate and combat module pepperspray.

**Comment by ben10083** [comment]
@Alberyk removed as requested

**Comment by Sindorman** [comment]
But flash is essential to combat other borgs?

**Comment by ben10083** [comment]
Only if a borg is rogue is that needed, not to mention the fact rogue borgs can be blown, borgs need defence against organics more.

**Comment by Sindorman** [comment]
What about Stationbound borgs fighting Syndicate borgs? Or Vice versa?

**Comment by ben10083** [comment]
Super rare ocurrance and if that happens crew has ion and flashes

**Comment by Lohikar** [comment]
I don't think it really makes sense ICly for borgs to have pepperspray. Their flashes can be explained as just a strobe from their existing headlights. Why would a utility unit have a canister of pepperspray?

**Comment by Arrow768** [comment]
Have you tested this ?
-> Especially refilling

**Comment by ben10083** [comment]
I have not gotten the time to do so yet, may you please show me how as well?

**Comment by skull132** [comment]
Needs to be made charge refillable as with the other tools. Also, with the merging of #4946 , it should be considered if this is worth it.

Rolled over to August update (2 weeks from now).

**Comment by ben10083** [comment]
Considering the recent pepper spray buff, the tool will not be useful to borgs compared to the flashed, closing.

**Pull request closed without merging**
