### PR TITLE
Cargo/Mining Map Tweaks

### LINKED ISSUE #4381: Cargo Tagger missing locations.
Cargo tagger for marking crates being sent down the tubes are missing some locations, namely medical locations with the new update. Captain's officer appears to not be on either, but I'm not sure if that was exempt before as well. Other locations not stated may be missing as well, but I'm unsure, I don't use the tagger often.

### LINKED ISSUE #4474: Insufficient Camera Coverage
The following areas have insufficient camera coverage:
Cryo at Cargo:
grafik
Main Hallway south of visitation:
grafik
Medical Cold Storage:
grafik
Firing Range:
grafik
Ladder to the authentication terminal:
grafik
Data compilation Office:
grafik
Cryogentics control room:
grafik

### PR DESCRIPTION
**Pull request by BurgerLUA**
## Mining Map Changes
There is an easier way for paramedics/miners to traverse down zlevels, without the using of a mobile ladder. A new area is built for that purpose. Main level has a ladder going up and down to two different areas. Both areas are guaranteed to be connected to another airlock. Top level is connected to science, bottom level is connected to a cargo elevator. Atmospherics system in mining is more saner. The mining processor was made shorter, and 4 grates are guaranteed to spawn now for each miner slot, and contains it's own maintenance hatch for easy upgrades. Mining also now has its own requests console and disposals delivery destination. The industrial smelter is now twice as fast, however uses three times as much power.

Mining Changes

## Cargo Map Changes
Cargo was modified to be saner for a Cargo technician. The warehouse is now significantly larger, sporting more crates and table space. The crates disposals system was replaced with a less damaging conveyor system. Atmospherics system in cargo is more saner. A new quick delivery system was added in the warehouse, which uses the quick tag system. Putting crates into the conveyor neat the warehouse will send it to the surface delivery system, unless the crate has been labeled. Main level cryo now appropriate reflects the same design as surface cryo, 
Cargo Changes 01
Cargo Changes 02

## Fixes
Fixes #4381
Fixes #4474

### CODE REVIEW

**Comment by BurgerLUA** [comment]
IT'S NOT A BURGER PR WITHOUT A TRAVIS ERROR

**Comment by BurgerLUA** [comment]
It's important to note that miners do not get magboots or drills like in my other PR. This one doesn't touch equipment.

**Comment by Arrow768** [comment]
The camera at the top of the warehouse still uses civilian west

**Comment by Arrow768** [comment]
I have also just tested the delivery system in the warehouse.
If a untagged item is put in, it ends up in the crusher

**Comment by BurgerLUA** [comment]
Fixing this right away.

**Comment by BurgerLUA** [comment]
I was an idiot and used the partial destination tagger, which works differently than the full destination tagger.

**Pull request merged**
