### PR TITLE
Adds Zo'ra Soda

### PR DESCRIPTION
**Pull request by ParadoxSpace**
Adds a few drinks and four vendors to the station.
Zo'ra Soda contains VAAM (V'krexi vomit) which is similar to nicotine. The drinks themselves are energy drinks, particularly High Octane Zorane Might. C'thur Rockin' Raspberry and Royal Jelly (it gets you high) are available as contraband in the vendor.

### CODE REVIEW

**Comment by BotBOREALIS** [comment]
Icons with diff:
<details><summary>icons/obj/drinks.dmi</summary>

Key | Old | New | Status
--- | --- | --- | ---
phoronpassion||phoronpassion|Created
dronefuel||dronefuel|Created
koistwist||koistwist|Created
zoracherry||zoracherry|Created
sourvenomgrass||sourvenomgrass|Created
cthurberry||cthurberry|Created
hozm||hozm|Created
hozm[1]||![hozm[1]](http://images.aurorastation.org/images/ee87b4566203d40459e6b82ccbfc8a1e.png)|Created
hozm[2]||![hozm[2]](http://images.aurorastation.org/images/eb7aee51225fb7889996d756e83ab67c.png)|Created
klaxancrush||klaxancrush|Created
royaljelly||royaljelly|Created
</details>
<details><summary>icons/obj/vending.dmi</summary>

Key | Old | New | Status
--- | --- | --- | ---
zoda||zoda|Created
zoda[1]||![zoda[1]](http://images.aurorastation.org/images/5892df9a5d9888f9b9996f1dfa035154.png)|Created
zoda[2]||![zoda[2]](http://images.aurorastation.org/images/d4c3b0ba71fec62bbeef0ed3e009427d.png)|Created
zoda[3]||![zoda[3]](http://images.aurorastation.org/images/b732b792ec94179566179315c95e21a5.png)|Created
zoda[4]||![zoda[4]](http://images.aurorastation.org/images/6ecf1635d3eb542016e9f63f5ba00bd9.png)|Created
zoda[5]||![zoda[5]](http://images.aurorastation.org/images/b732b792ec94179566179315c95e21a5.png)|Created
zoda[6]||![zoda[6]](http://images.aurorastation.org/images/6ecf1635d3eb542016e9f63f5ba00bd9.png)|Created
zoda[7]||![zoda[7]](http://images.aurorastation.org/images/5892df9a5d9888f9b9996f1dfa035154.png)|Created
zoda-off||zoda-off|Created
zoda-broken||zoda-broken|Created
zora-panel||zora-panel|Created
</details>

**Comment by LordFowl** [comment]
I don't really see the purpose of adding in an entirely new vendor for energy drinks. Or why there have to be so many of them that essentially do the same thing slightly different. If you really are intent on providing legitimacy to the ZZODDAA meme, then just add one to the drink vendor that already exists.

The balance of adding so many cheap stimulants should also be looked into, although I admit I'm not keen on the code for stimulation.

**Comment by BurgerLUA** [comment]
this is the equivalent of adding fanta drinks to vending machines in israel during world war 2

**Comment by ParadoxSpace** [comment]
unga

**Comment by ParadoxSpace** [comment]
chugging it is now not the best idea and prices have increased

**Comment by ParadoxSpace** [comment]
Did you actually look at the PR?
None of them contain phoron.
And they cannot fit in the standard drinks vendor for lore reasons, the standard cola vendor is a product of Robust Softdrinks, whereas Zora Soda is a product of the Getmore Corporation

**Comment by Arrow768** [comment]
You are correct, there is no phoron.
However, some of the names contain the word phoron -> That is what confused me.
If there is no phoron, change it accordingly.

The other points still need to be addressed.
There are way to many drinks that are essentially the same thing, just in a different color.

The corporation that produces the drinks does not matter.
You can find ice tea and bottled water that is not produced by the coca cola company in vending machines owned by the coca cola company.

**Comment by ParadoxSpace** [comment]
I'm not changing the name of Phoron Passion, it's just a catchy flavor name and the examine text literally says there is no phoron. Not to mention the regular Robust Softdrinks literally contains the same amount of drinks that do the exact same thing. The corporation that produces the drinks /does/ matter because Robust Softdrinks and Getmore do not work alongside each other. You're not going to find Pepsi in a Coca-Cola vendor.

**Comment by MarinaGryphon** [comment]
Fowl's complaints sound entirely unreasonable. I see no issue with another drinks vendor. If it's that big of an issue, just restrict it to only having one mapped in the bar and maybe one in maintenance. You're blowing this up into some big issue when it's really just a bikeshed.
`Whichever choice you make, you will also of course have to reduce the number to preferable 1-2 drinks.` This is completely unsubstantiated. It's the exact same as the number the normal Robust Softdrinks vendor has. This just seems like Fowl flexing his dev powers on Paradox.

**Comment by Arrow768** [comment]
I deleted the comment since it was attacking a person and not arguing on the technical aspect.

@ParadoxSpace 
Create a feedback topic in the projects subforum.

**Comment by JackBewt** [comment]
Having a special vendor for the drinks but shunting it in low-traffic areas could appease both sides. It will not take up valuable tilespace in high traffic and high demand areas, and will also reinforce the second-class nature of vaurca that their little entrepreneurial business is put in seedy back alleys,

**Comment by Arrow768** [comment]
Screenshots of the mapping changes please.

**Pull request merged**
