### PR TITLE
New Vaurca Warrior Sprite

### PR DESCRIPTION
**Pull request by 1Sparky1**
Adds a new warrior sprite at the request of Vaurca lore.

image

### CODE REVIEW

**Comment by 1Sparky1** [comment]
!review

**Comment by desvenlafaxine** [comment]
Lore certified.

**Comment by desvenlafaxine** [comment]
Comparison with the old sprite (identical to the Worker's sprite) for reference:
image

**Comment by 1Sparky1** [comment]
Side by side:
image

**Review by DreamySkrell — APPROVED** [review]

**Comment by FluffyGhoster** [comment]
@alsoandanswer your opinion as lead spriter when possible

**Review by Geevies — APPROVED** [review]

**Pull request merged**
