### PR TITLE
Re-adds dionae soup and dionae stew recipes.

### PR DESCRIPTION
**Pull request by MarinaGryphon**
Lost in the shuffle. :pensive:

### CODE REVIEW

**Comment by MarinaGryphon** [comment]
!bugfix

**Comment by MarinaGryphon** [comment]
!review

**Review by Geevies — APPROVED** [review]
!pensive

**Review by NonQueueingMatt — APPROVED** [review]
Diona buffs -1

**Comment by MarinaGryphon** [comment]
> Diona buffs -1

if I were going to remove something intentionally, it would be the meme diona roast, not the actually half-decent stew/soup, smh

**Pull request merged**
