### PR TITLE
Hypospray + surgical tools resprites

### PR DESCRIPTION
**Pull request by nauticall**
This PR gives the hypospray, as well as surgery tools, a new, fresh coat of paint! 

image
_In order from left to right, the tools are the: bone setter, surgical saw (no longer circular saw), retractor, vascular recoupler (renamed from FixOVein), hemostat, scalpel, cautery, bone gel, ATK (unchanged) and surgical drill._

image
_Surgical tray and tray sprites have been updated too._

The surgical tools no longer look like they were made in MS Paint and are now 70% more clickable, hopefully leading to less lives lost because of slippery tools! Rejoice!

They also come with full inhand and in-tray sprites, at the small cost of my sanity.

image
_A monkey has given their life to ensure the hyposprays remain functional and display their icon states properly. For science._

And the hyposprays have been given an overhaul, looking more in-line with modern sprites and standards.

### CODE REVIEW

**Review by atteria — APPROVED** [review]

**Comment by nauticall** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
The bonesetter, hemostat, scalpel, saw, drill and retractor need to have their outlines made consistent with the rest.

The bonesawsaw should definitely retain its old design, or at least have a different one, because it looks too similar to the drill.

Some of these tools definitely need to be shrinked in size. For gameplay reasons, all of the tools should be able to comfortably fit on a 1 tile table when a surgical tray is otherwise unavailable or needed to be manually mapped in.
The accent color should be purple to match the surgical kit, personally.

For the hyposprays, I think the trigger guard for the regular ones should be removed.
It'll make the silhouette more differentiated than the CMO's one.

Otherwise, they look pretty good. It's a definite improvement.

**Review by Alberyk — APPROVED** [review]

**Comment by nauticall** [comment]
image

Updated sprites! They're smaller, more consistent, and address the changes you requested. Hope this works.

**Review by alsoandanswer — APPROVED** [review]
Maybe flip the drill back to it's original orientation. Other than that, good work.

**Pull request merged**
