### PR TITLE
Fixes RFD Not Being Able to Construct Windows

### LINKED ISSUE #14655: Window frames + full windows can't be deconstructed with an RFD
Title.

### LINKED ISSUE #14726: Deconstruction effect lingers
A construction stationbound traitor attempted to deconstruct a window in the location on the below picture using its rapid construction tool. The effect never disappeared.

image

That is hydroponics by the way.

### PR DESCRIPTION
**Pull request by SleepyGemmy**
title.

fixes #14655. fixes #14726.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!bugfix

**Comment by SleepyGemmy** [comment]
need help figuring out why deconstruction doesn't work.

**Comment by SleepyGemmy** [comment]
PR is waiting for reviews, it is **NOT ABANDONED**.

**Comment by SleepyGemmy** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
