### PR TITLE
[WIP] Suggestions Bonanza

### PR DESCRIPTION
**Pull request by LordFowl**
Incorporates the following:
https://forums.aurorastation.org/viewtopic.php?f=18&t=9552
https://forums.aurorastation.org/viewtopic.php?f=18&t=8376
https://forums.aurorastation.org/viewtopic.php?f=18&t=9176
https://forums.aurorastation.org/viewtopic.php?f=18&t=8552
https://forums.aurorastation.org/viewtopic.php?f=18&t=8440
https://forums.aurorastation.org/viewtopic.php?f=18&t=8009
https://forums.aurorastation.org/viewtopic.php?f=18&t=9142
https://forums.aurorastation.org/viewtopic.php?f=18&t=9771
https://forums.aurorastation.org/viewtopic.php?f=18&t=10184
https://forums.aurorastation.org/viewtopic.php?f=18&t=10183

- [ ] Xenoarch changes
- [ ] Diona pod changes
- [ ] Mapping changes
- [ ] Testing
- [ ] Balance
- [ ] Changelog

### CODE REVIEW

**Comment by skull132** [comment]
\> Master

**Comment by LordFowl** [comment]
What are you talking about? Senile old developer.

**Comment by Arrow768** [comment]
I think with the current implementation of the department function, you can just add people to new departments, but you would not remove them from the old department when you change the department ?

**Comment by LordFowl** [comment]
Department is based on string comparison to assignment. A person can only have one assignment, custom or otherwise, unless the records system has glitched in which case there would be two entries anyways.

**Pull request closed without merging**
