### PR TITLE
Butanol Drink Fix

### PR DESCRIPTION
**Pull request by Crosarius**
fixes https://github.com/Aurorastation/Aurora.3/issues/19343
Fixes butanol becoming strength 0 after being ingested by Humans, due to a mistake in handling the strength variable. I've removed the code responsible, and made a small change that makes that part unnecessary anyway. Tested and now working as intended.

### CODE REVIEW

**Comment by Crosarius** [comment]
fixes #19343

**Comment by Llywelwyn** [comment]
if this is done, hit it with `!review` and `!bugfix` so it gets looked at and/or merged quicker <3

**Comment by Crosarius** [comment]
I forgor...

**Comment by Crosarius** [comment]
!review

**Comment by Crosarius** [comment]
!bugfix

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
