### PR TITLE
Holy Blessed Suns! Tajara Now Get Closed Toe Boots Too

### PR DESCRIPTION
**Pull request by WickedCybs**
This PR adds a selection in the Tajara xenoware section which gives fitted variants of common boot types that aren't toeless. Lore-wise, Tajara do wear closed boots as well. Toeless boots only being available was a bit of a gameplay thing and probably making use of what was originally for Unathi.

The change is relatively simple as only a few pixels get changed here to make the footwear appear to match the Tajaran sprite.

Here is an example of the black boots. It represents their unique nature on station as a digitigrade species, though it is a bit hard to notice due to it being a minor change.
image

### CODE REVIEW

**Comment by WickedCybs** [comment]
!review

**Review by Geevies — APPROVED** [review]
you don't understand

it is absolutely vital that their toes are open admin

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by WickedCybs** [comment]
not sure how to unfuck, will make a new PR

**Comment by WickedCybs** [comment]
I was told how to fix the conflict here so going to use this to give it a shot.

**Comment by WickedCybs** [comment]
Finally.

**Pull request merged**
