### PR TITLE
Faction Job Belts

### PR DESCRIPTION
**Pull request by furrycactus**
Adds faction-specific belts for the various jobs on the station, and maps them into departmental equipment lockers.

image
image

### CODE REVIEW

**Comment by furrycactus** [comment]
!review

**Comment by Greenjoe12345** [comment]
Wouldn't it be better to code them into the list the lockers spawn with rather then mapping them onto the horizon on the lockers?

**Comment by furrycactus** [comment]
Maybe. But if any of those lockers are mapped on away sites or ships then that might cause them to spawn there too.

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
I'm pretty opposed to these getting added. Belts are not generic enough to just be corporate variants, because they are extremely tailored to each and every job.

**Comment by furrycactus** [comment]
I am not sure what to say in response here. I feel that they're an extremely small collection of pixels with very little difference between them, the distinction primarily appearing to be their colour as opposed to design. The majority are hard to tell apart or even perceive when part of a uniform's whole, unless their colours are drastically different (which is the current case with the black medical belts and the pastel pinks of Zeng-Hu uniforms).

**Comment by furrycactus** [comment]
I can add faction-coloured variants of the other belts if that's more appealing, like the security and utility ones? Medical/First Responder/Hydroponics/Soulstone all share the same base and that's what I based these ones off of too, so if you want me to keep with theme I can retain the NT/Zeng/PMCG ones shown here for Medical and NT/Idris/Orion for Hydroponics, and then base the other departmental ones off of the other designs if that would be better? I'm not really sure how to improve and make it more appealing if your feedback is just "I don't like these".

**Review by DreamySkrell — CHANGES_REQUESTED** [review]
I think these are cool sprites, but, personally, I do not think we should have corporate-flavored variants of standard equipment. Clothes or uniforms are fine, of course.

Personally, I don't want more corporate-flavored equipment variants like this. I wouldn't want to open up a security locker to see 3 armor vests in different colors, 3 variants of belts, 3 helmets, etc. It is a mess to maintain for devs/spriters, and annoying when actually playing the game. And yes, these belts should be added to lockers in code (or the loadout), and not mapped in manually in strongdmm.

At the very least, sec/med/engie belts should be different, so they are identifiable at a glance what they are. In this PR, a SCC toolbelt will look the same as a SCC security belt, and a SCC medical belt. That is not good.

But honestly, I would advise against working on this more, before figuring out if it is actually wanted by developers/maintainers/staff. Me and Wezzy are just two devs in the team, other devs/staff may have a different opinion. Also we have the #spriter_coordination channel in the main discord, to coordinate spriting - I would suggest to ping a spriter or staff before working on stuff like this.

**Pull request closed without merging**
