### PR TITLE
Security Powercreep (Better Locker Sorting)

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Overview
I've ~~powergamed~~ played security for about 2 weeks now, and I'm noticing some small things that I've been having problems with when it comes to equipment and loadout, so I decided to make a PR for it.

## Better Ordering
For personal & secure security lockers, clothing and generally unneeded stuff are spawned first, meaning that all the equipment you usually need are layered over them. The order from topmost layer to bottommost layer is
- Belts and storage-based accessories
- Tools
- Appearance
- Supply Items
This should make it so that gearing up is easier for plebians who don't know how to alt-click a pile of garbage.

## Extra Outfit
Added the dispatcher's uniform to the available uniforms in the locker because I'm a special snowflake who likes that uniform. There's also 3 pairs of spare jackboots and 1 pair of toeless jackboots in the general equipment locker for security.

### CODE REVIEW

**Comment by Arrow768** [comment]
Additional equipment like station bounced radios, crowbars and maglights are available via cargo.
If you need that equipment then order it via cargo.

They are your go to location if you need to buy anything.
Just use any modular computer, open up the cargo order app and order what you need.
(Coming with the jan update)

**Comment by BurgerLUA** [comment]
@Arrow768 Shipping is expensive and 99% of the time officers will just take flashlights and crowbars from the surface or maintenance using their PDA as a flashlight. I can understand "Just use cargo" for things like ammo and other tools but stuff like flashlights and radios should be plentiful in security.

**Comment by Juani2400** [comment]
There are four maglites, four crowbars and four radios for four officers. While I am aware other staff take them, I don't think this is an issue that needs amending through mapping. 

As said, all this equipment is available in other places, the only issue being, so far, the torches, which are now available through cargo, once the update happens.

**Comment by Arrow768** [comment]
Regarding the comment that shipping is so expensive:
Shipping costs are between 100 and 150 credits (with two exceptions at 1 and 500 credits).
If you feel that this is too much, you can talk to your fellow officers, order together and split the shipping cost amongst you.

**Comment by Arrow768** [comment]
Looks pretty good now.
Altough I am still not sure if the dispatcher suits should be available

**Comment by Arrow768** [comment]
We briefly discussed the dispatcher uniform on discord.
Security already has sufficient Uniforms available and there is no need for another uniform, that we dont even have a role for (Dispatcher).
Please remove the dispatcher uniform from the lockers.

**Pull request merged**
