### PR TITLE
Computer sprites

### PR DESCRIPTION
**Pull request by AgentWhatever**
Constructing a computer now makes sense sprite-wise.
Also edited some fluff text to be more accurate during construction.

### CODE REVIEW

**Comment by Lohikar** [comment]
Screenshot of new sprites please.

**Comment by AgentWhatever** [comment]
https://puu.sh/xUSnT/530d1790a7.png 
https://puu.sh/xUSoF/a863add660.png 
https://puu.sh/xUSpt/438c41870f.png 
https://puu.sh/xUSqv/6693e7de06.png 
https://puu.sh/xUSqZ/83fabcad8b.png

Now on this one I am not entirely sure on the blue coloring, actually. 
https://puu.sh/xUSsP/aaa098badd.png

**Comment by chaoko99** [comment]
Please make a habit of embedding your screenshots.

**Comment by AgentWhatever** [comment]
Embedded the pictures in the previous comment

**Comment by chaoko99** [comment]
Looks good to me.

**Pull request merged**
