### PR TITLE
Homestuck-be-gone

### PR DESCRIPTION
**Pull request by TheDanseMacabre**
The iced tea is a homestuck reference. The iced tea is no longer a homestuck reference. Rejoice!

### CODE REVIEW

**Comment by TehFlaminTaco** [comment]
Not to be picky, but is this too heinous of a reference whilst we still have the physics defying Sord?

**Comment by TheDanseMacabre** [comment]
> Not to be picky, but is this too heinous of a reference whilst we still have the physics defying Sord?

I am removing Sord now.

**Comment by TheDanseMacabre** [comment]
!review

**Comment by TheDocOct** [comment]
Making it Martian because tea is a 'southern' thing seems cheap to me, and reminds me of the tide of painfully-stereotypical-barely-vieled-Southern-US Martians we had in past years. I would honestly rather see it actually from Earth's US region, or perhaps another agrarian source like Elyra or Valley Hale, than reinforce the 'Martians-are-just-cowboys' joke.

**Comment by TheDanseMacabre** [comment]
> Making it Martian because tea is a 'southern' thing seems cheap to me, and reminds me of the tide of painfully-stereotypical-barely-vieled-Southern-US Martians we had in past years. I would honestly rather see it actually from Earth's US region, or perhaps another agrarian source like Elyra or Valley Hale, than reinforce the 'Martians-are-just-cowboys' joke.

I just liked the alliteration. I have no special attachment to the Martian name and theme, and can change it right now

**Comment by TheDocOct** [comment]
👌

**Review by Alberyk — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
