### PR TITLE
Removes ventcrawl blenders

### PR DESCRIPTION
**Pull request by Sniblet**
Unary pumps, outlet injectors, and scrubbers currently turn small simplemobs that interact with them while ventcrawling (borers) into dust with no warning and no interactivity whatsover. You touch the machine, you gib. It doesn't say that this is going to happen anywhere. Just happens, instantly. Bye. See you in twenty minutes.

- This is, for obvious reasons, not fun.
- This is not realistic. If there are spinning blades in the way or something (and not in regular vents??), why are we running through them?

This PR removes the surprise death mechanic and does nothing to replace it. You can probably crawl into scrubbers now, and die of vacuum instead. You can also crawl through unfamiliar vents in maint without fearing that one of them is a funny  die vent.

### CODE REVIEW

**Comment by Sniblet** [comment]
!review required

**Comment by sheeplets** [comment]
Good change, getting vent-blasted sucks. You need a changelog, you can find an example under Aurora.3/html/changelogs/example.yml

**Comment by Arrow768** [comment]
The blender-function was added to curb a specific behaviour.
Given that it gets the maintainer discussion tag

**Review by Arrow768 — APPROVED** [review]

**Review by SleepyGemmy — APPROVED** [review]

**Comment by alsoandanswer** [comment]
Voting against merge

**Comment by Sniblet** [comment]
I don’t know what behavior you’re talking about, but I doubt it’s worse than antagonists randomly and permanently being round removed.

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
