### PR TITLE
Loadout Improvements (round 1)

### PR DESCRIPTION
**Pull request by carpevenenum**
changes:
  - tweak: "The loadout now filters out items that are only allowed for roles you don't have in your preferences."
  
  
image
Here's an example. The holster and other stuff is not shown because none of the allowed roles are in job preferences, but the medical webbing and the drop pouches are because Surgeon is set on high (though it works for low and medium preferences too via epic shitcode).
This should help massively with bloat in sections such as Accessories (with this change, it's usually cut down by almost a half) or Modular Computers.

### CODE REVIEW

**Comment by carpevenenum** [comment]
!review

**Comment by carpevenenum** [comment]
I think, actually, that in this PR the build is failing because there is le epic shitcode, not because it's failing all the time. I'll fix it.

**Comment by carpevenenum** [comment]
I hope travis fucking dies idk help

**Comment by carpevenenum** [comment]
!wip

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]

**Comment by Arrow768** [comment]
Dreamchecker Error:
```

code/modules/mob/abstract/new_player/preferences_setup.dm, line 247, column 3:
--
18 | error: iterating over a /datum/job which cannot be iterated
19 |  
20 | code/modules/mob/abstract/new_player/preferences_setup.dm, line 255, column 3:
21 | error: iterating over a /datum/job which cannot be iterated
22 |  
23 | code/modules/mob/abstract/new_player/preferences_setup.dm, line 263, column 3:
24 | error: iterating over a /datum/job which cannot be iterated


```

**Comment by NonQueueingMatt** [comment]
inactive author

**Pull request closed without merging**
