### PR TITLE
Squash some spawns

### PR DESCRIPTION
**Pull request by FluffyGhoster**
Turned a bunch of spawn procs into addtimers, eventually with function split, for slightly better performance.

Not every spawn can be turned, or it's worth the effort to do so, but this should hit the main (read: frequently used or that can likely happen when we are under load) ones where this change has the most impact, and some easy ones that were found in between the search for the firmer.

A testmerge is suggested before the final merge.

### CODE REVIEW

**Comment by FluffyGhoster** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by mikomyazaki** [comment]
Something in this PR is causing #15942

**Comment by FluffyGhoster** [comment]
@mikomyazaki @Alberyk see how this change goes, it should fix #15942 without making the linter angry

**Comment by NonQueueingMatt** [comment]
Last this was tested it lagged everything to hell, so not desirable for now

**Pull request closed without merging**
