### PR TITLE
Cameras will no longer see more than user

### LINKED ISSUE #8879: Photo Cameras See Through Walls
Taking a picture of a wall will cause you to also photograph the other side of the wall too. 

https://cdn.discordapp.com/attachments/506308729474514946/710640157790830592/unknown.png

### PR DESCRIPTION
**Pull request by Karolis2011**
Fixes #8879

### CODE REVIEW

**Comment by Karolis2011** [comment]
!bugfix

**Comment by Kaedwuff** [comment]
Could you also correct your spelling of the word 'camera' on this PR's title pretty please.

**Comment by Sindorman** [comment]
> Could you also correct your spelling of the word 'camera' on this PR's title pretty please.

that doesn't matter. Does it?

**Comment by Kaedwuff** [comment]
> that doesn't matter. Does it?

It took more time for you to type out that statement questioning the validity of my polite proofreading request then it would have taken for them to actually fix the problem. I don't know why you felt the need to make such an unnecessarily dismissive statement towards me. =\

**Comment by NonQueueingMatt** [comment]
Reopen when ready, and a fix for the lag is given.

**Pull request closed without merging**
