### PR TITLE
Fixes nonfunctional sector blacklist

### PR DESCRIPTION
**Pull request by RustingWithYou**
Fixes the sectors blacklist added in #17733 as it did not work.

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Comment by RustingWithYou** [comment]
!bugfix

**Comment by DreamySkrell** [comment]
The blacklist is functional.

The actual problem is just that `list(A,B,C,A) - list(A)` removes `A` only once from the first list. Sectors sort of can repeat in the `sectors` var, for example `ALL_POSSIBLE_SECTORS` will always have some sectors duplicated cause for example Heumenin is both in corporate and coalition sectors lists.

This PR does fix that though.

**Review by DreamySkrell — APPROVED** [review]

**Comment by FluffyGhoster** [comment]
The proper solution would be to use https://secure.byond.com/docs/ref/index.html#/list/proc/RemoveAll on the list to remove the blacklisted sectors, halving at minimum the list traversals that this produces

**Comment by RustingWithYou** [comment]
> The proper solution would be to use https://secure.byond.com/docs/ref/index.html#/list/proc/RemoveAll on the list to remove the blacklisted sectors, halving at minimum the list traversals that this produces

updated to do it this way

**Comment by FluffyGhoster** [comment]
> updated to do it this way

Remember that due to OpenDream still not having this it will result in a linter error, suppress it with a precompiler conditional that you can yoink from the list_clear_nulls proc and adapt:

```
/proc/list_clear_nulls(list/list_to_clear)
//Sorry, OpenDream doesn't have this proc yet for lists
#if !defined(OPENDREAM)
	return (list_to_clear.RemoveAll(null) > 0)
#else
	return FALSE
#endif
```

**Comment by RustingWithYou** [comment]
> > updated to do it this way
> 
> Remember that due to OpenDream still not having this it will result in a linter error, suppress it with a precompiler conditional that you can yoink from the list_clear_nulls proc and adapt:
> 
> ```
> /proc/list_clear_nulls(list/list_to_clear)
> //Sorry, OpenDream doesn't have this proc yet for lists
> #if !defined(OPENDREAM)
> 	return (list_to_clear.RemoveAll(null) > 0)
> #else
> 	return FALSE
> #endif
> ```

life is suffering.

**Review by FluffyGhoster — APPROVED** [review]

**Pull request merged**
