### PR TITLE
Spring Cleaning Again

### PR DESCRIPTION
**Pull request by alsoandanswer**
Same as the last one, with the fixes included

This will need to be eventually merged at a later date when convenient since this is needed as a prerequisite PR for future Skrell/Unathi events

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by lavillastrangiato** [comment]
So out of curiosity, why not add the genericised versions of the props _alongside_ their original Konyang ones?

**Comment by alsoandanswer** [comment]
> So out of curiosity, why not add the genericised versions of the props _alongside_ their original Konyang ones?

I'm fine with adding them alongside the original Konyang ones. It's just that certain ones have to be changed in order to fit alongside the rest in their new files - namely, to fit the spritesheet sizes and fixing some issues. Mostly minor changes.

Traffic crossing. Original on left, tweaked on right.
image

Street Lamp. Changed because it literally is the desk lamp on a pole.
dreammaker_x7IS1MjOyr

**Comment by alsoandanswer** [comment]
StrongDMM_fRWYyN463w
StrongDMM_SFD31HhXB9

**Comment by Leroyengloys** [comment]
As long as it's merged after the arc, I'm ok with it.

**Pull request closed without merging**
