### PR TITLE
Tweaks tile sprites

### PR DESCRIPTION
**Pull request by alsoandanswer**
OLD :
dreamseeker_1S5WHdcGo7

NEW :
dreamseeker_mHnWO8DQTp

After trying to think about the tiles, I realized that they were way too dark.
So much so, that their brightness matched with the walls, and it all kinda just muddled together.
This increases the brightness of it, so you know where's the floor from the wall.
It also makes looking between white tiles and regular tiles less jarring.

also deletes that stupid annoying extra changelog

dreammaker_qCO3xxMcaY
I think this is a nice, moderate inbetween

This also solves the problem of regular old items and clothing looking way too bright in comparison.

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by Geevies** [comment]
I think it's a downgrade. Loss of quality, and the darker tiles look better imo.

**Comment by TheDanseMacabre** [comment]
Hope this is an April Fool's joke. The new tiles are overwhelmingly well-received. Do not try and remove them because _you_ dislike them - which is what this PR is doing. We have a distinctive look now - there is absolutely no reason to port Polaris' floor sprites to replace ours.

**Comment by alsoandanswer** [comment]
Closed on request of Ferner.

**Pull request closed without merging**
