### PR TITLE
Diona Heat Buff

### PR DESCRIPTION
**Pull request by ParadoxSpace**
They can now be on fire, but a phoron fire would still wipe them out. Also, the chirp emotes no longer double up.

### CODE REVIEW

**Comment by Sindorman** [comment]
They generally regenerate faster than they get damage from fire/heat.

**Comment by ParadoxSpace** [comment]
No, they still slowly die.

**Comment by ParadoxSpace** [comment]
!review

**Comment by Sindorman** [comment]
Not here 
Diona-meme

**Pull request merged**
