### PR TITLE
Head Pins Sprite Fixes

### PR DESCRIPTION
**Pull request by Ben10083**
Fixes https://github.com/Aurorastation/Aurora.3/issues/17610
Hair pins such as flower pins now have proper left and right ear sprites

### CODE REVIEW

**Comment by Ben10083** [comment]
!bugfix

**Comment by Ben10083** [comment]
still need to see why is uses right ear sprite for side profiles 
image
image

**Comment by Ben10083** [comment]
Fix found

**Comment by Ben10083** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]

**Review by FluffyGhoster — APPROVED** [review]

**Pull request merged**
