### PR TITLE
Minor Chaplain Rework

### PR DESCRIPTION
**Pull request by Kaedwuff**
Some quality of life reworks for chaplain

Feedback Thread: https://forums.aurorastation.org/viewtopic.php?f=18&t=11459

Progress:
- [x] Let staves be mounted on ponchos
- [x] Make non-rods stop acting like rods when trying to decult people.
- [ ] Get the back sprite I made to work
- [ ] Implement reassembling obsidian shards to replace the magic null spawner box.
- [ ] Add blacklist to cryo storage for holy water and null items.
- [ ] Sprite null sphere and uncomment it back in.

### CODE REVIEW

**Comment by BotBOREALIS** [comment]
Icons with diff:
<details><summary>icons/mob/back.dmi</summary>

Key | Old | New | Status
--- | --- | --- | ---
nullstaff|nullstaff|nullstaff|Modified
nullstaff[1]|![nullstaff[1]](http://images.aurorastation.org/images/e262faa3028251e4f27a1a38a9e012fb.png)|![nullstaff[1]](http://images.aurorastation.org/images/a68a055919b2aa1835015c89e7538ddc.png)|Modified
nullstaff[2]|![nullstaff[2]](http://images.aurorastation.org/images/6f2957da34ee7eba3848f6b3aa7d96d6.png)|![nullstaff[2]](http://images.aurorastation.org/images/e84ea78bb9f7759a2aa19a6c1605069a.png)|Modified
nullstaff[3]|![nullstaff[3]](http://images.aurorastation.org/images/82c87aff760e4bdad36d3ca2954b2531.png)|![nullstaff[3]](http://images.aurorastation.org/images/f9d1e72dad5a291f86aa20a6f15306b1.png)|Modified
icelance|icelance||Removed
icelance[1]|![icelance[1]](http://images.aurorastation.org/images/874b1e4add02936e5431d20f087d6af1.png)||Removed
icelance[2]|![icelance[2]](http://images.aurorastation.org/images/e951d7cdefd7f48a027cd45acf94b05a.png)||Removed
icelance[3]|![icelance[3]](http://images.aurorastation.org/images/910d90fafd890b3a6c749b0bd06b6934.png)||Removed
icelance100|icelance100||Removed
icelance100[1]|![icelance100[1]](http://images.aurorastation.org/images/874b1e4add02936e5431d20f087d6af1.png)||Removed
icelance100[2]|![icelance100[2]](http://images.aurorastation.org/images/e951d7cdefd7f48a027cd45acf94b05a.png)||Removed
icelance100[3]|![icelance100[3]](http://images.aurorastation.org/images/910d90fafd890b3a6c749b0bd06b6934.png)||Removed
icelance75|icelance75||Removed
icelance75[1]|![icelance75[1]](http://images.aurorastation.org/images/65c5cf4da6620d1486089ce1afdf7a44.png)||Removed
icelance75[2]|![icelance75[2]](http://images.aurorastation.org/images/e951d7cdefd7f48a027cd45acf94b05a.png)||Removed
icelance75[3]|![icelance75[3]](http://images.aurorastation.org/images/910d90fafd890b3a6c749b0bd06b6934.png)||Removed
icelance50|icelance50||Removed
icelance50[1]|![icelance50[1]](http://images.aurorastation.org/images/8e1569299662522076e2304eb0aa9d12.png)||Removed
icelance50[2]|![icelance50[2]](http://images.aurorastation.org/images/e951d7cdefd7f48a027cd45acf94b05a.png)||Removed
icelance50[3]|![icelance50[3]](http://images.aurorastation.org/images/910d90fafd890b3a6c749b0bd06b6934.png)||Removed
icelance25|icelance25||Removed
icelance25[1]|![icelance25[1]](http://images.aurorastation.org/images/8e1569299662522076e2304eb0aa9d12.png)||Removed
icelance25[2]|![icelance25[2]](http://images.aurorastation.org/images/e951d7cdefd7f48a027cd45acf94b05a.png)||Removed
icelance25[3]|![icelance25[3]](http://images.aurorastation.org/images/910d90fafd890b3a6c749b0bd06b6934.png)||Removed
icelance0|icelance0||Removed
icelance0[1]|![icelance0[1]](http://images.aurorastation.org/images/582a6d39d83d0f9eaaa799ff8b1a744c.png)||Removed
icelance0[2]|![icelance0[2]](http://images.aurorastation.org/images/e951d7cdefd7f48a027cd45acf94b05a.png)||Removed
icelance0[3]|![icelance0[3]](http://images.aurorastation.org/images/910d90fafd890b3a6c749b0bd06b6934.png)||Removed
springfield|springfield||Removed
springfield[1]|![springfield[1]](http://images.aurorastation.org/images/5a4054d52c74a5902e777b1c30ee3703.png)||Removed
springfield[2]|![springfield[2]](http://images.aurorastation.org/images/934310783d4bf392a71c2e594ef22ddf.png)||Removed
springfield[3]|![springfield[3]](http://images.aurorastation.org/images/08f591dc01fc869ff30c9fc06a11d4dd.png)||Removed
springfield-openbolt|springfield-openbolt||Removed
springfield-openbolt[1]|![springfield-openbolt[1]](http://images.aurorastation.org/images/5a4054d52c74a5902e777b1c30ee3703.png)||Removed
springfield-openbolt[2]|![springfield-openbolt[2]](http://images.aurorastation.org/images/934310783d4bf392a71c2e594ef22ddf.png)||Removed
springfield-openbolt[3]|![springfield-openbolt[3]](http://images.aurorastation.org/images/08f591dc01fc869ff30c9fc06a11d4dd.png)||Removed
</details>

**Comment by Kaedwuff** [comment]
This version should include the ice lance sprites recently added to master instead of removing them.

**Comment by Arrow768** [comment]
Is there a specific reason why thats not targeting development ?

**Comment by Kaedwuff** [comment]
Because it used to be just a simple utility to make null staffs staves mountable on the backs of ponchos, and feature creeped into a low level chaplain rework because I have no self control.

I'll fix it.

**Comment by skull132** [comment]
Well this is dead.

**Pull request closed without merging**
