### PR TITLE
Kitchen Strikes Back: The Rattening: Like a Balloon: 10000000 Rats Dead

### PR DESCRIPTION
**Pull request by Geevies**
* Kitchen staff are now equipped with Arodentia guns, capable of keeping any well-meaning establishment clear of pests.
* Kitchen staff now have armpit holsters to keep their Arodentia guns in.
* Rats now have their health reduced to reasonable levels.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by VTCobaltblood** [comment]
Why is the kitchen equipped with this, and not janitors? Janitors are the ones who get mousetraps, after all.

**Comment by furrycactus** [comment]
Cooks get mousetraps too, but by all means give them to janitors too, the more the better.

**Comment by Geevies** [comment]
well you see

**Comment by Geevies** [comment]
the thing is

**Comment by Geevies** [comment]
the might've forgotten janitors exist

**Comment by alsoandanswer** [comment]
...is this a joke?

this sounds way too over the top.

**Comment by furrycactus** [comment]
Arodentia guns are completely harmless to anything but pests. And rats are a scourge upon the station that completely warrant their use tbh.

**Comment by alsoandanswer** [comment]
Yeah but...can we at least make an effort to make it like...sorta sci-fi and interesting instead of just RAT GLOCK.

**Comment by furrycactus** [comment]
They're rechargable energy pistols that fire diffuse electrical arcs that make rats pop, that's pretty SciFi.

**Comment by Arrow768** [comment]
On a more serious note: I would most likely be sufficient to reduce the amount of health the rats have to the proposed value.

**Comment by Kaedwuff** [comment]
This is really dumb. Do not give the cheese a rat laser. Their kitchen is full of implements they can use to kill a rat without having one-hit-kill laser beam that gibs every rat with hitscan, splattering blood all over the kitchen floor and food.

This is arming police officers with rocket launchers. Complete excess meme PR.

**Comment by alsoandanswer** [comment]
yeah i think feedback is required here

**Comment by Kaedwuff** [comment]
Giving rat lasers to janitors is also overkill, especially since you have apparently added the feature to supercharge them(?) by emagging.  Put the feedback required tag back and suffer having to listen to community feedback if you are going to insist on implementing disruptive new features to the game.

And yes, it is disruptive, because rats exploding into bloody gibs all over the station because you can't control your memey desire to give more ways to kill them is not, in my opinion, a good addition to the game.

**Comment by Arrow768** [comment]
> And yes, it is disruptive, because rats exploding into bloody gibs all over the station ...

They only explode into gibs when the rat-gun is emagged.
And imho its fair game for that to happen when emagged.

**Comment by Kaedwuff** [comment]
> They only explode into gibs when the rat-gun is emagged.
> And imho its fair game for that to happen when emagged.

Hmm, you're right.  It's not as bad as I thought, then, but...  I still think that this is way too much to be given to janitors at round start.  It makes all other existing forms of mouse traps redundant and pointless.

What if we make it something janitors have to buy in cargo?

**Comment by lolman360** [comment]
brb adding god-emperor of ratkind

**Pull request merged**
