### PR TITLE
[WIP] Massive Kitchen and Bar Overhaul

### PR DESCRIPTION
**Pull request by BurgerLUA**
Massive Kitchen and Bar overhaul created with feedback from the good people at discord as well as edits based on the currently existing kitchen and my tendency to play chef every round.

It's difficult to form words about everything that's changed so here is a screenshot album of the new layout.

Screenshots: https://imgur.com/a/NzVKt

I hated the old kitchen. It was so tiny and every time there was another cook, I would get sad because the old kitchen can really only fit one cook. For christ sakes, my high school's canteen was bigger than the kitchen and it wasn't even upper class or anything.  Another thing I disliked is that it had 0 connection to the bar when those two departments should be working together when it comes to serving food and drinks. Instead, both departments were crammed into a small section.

So I did something about it, and what I made is now a kitchen fit for a top of the line research station, and most important of all, an RP server.

Due to problems with an outdated version of github and the fact that this was a 3+ day project with map changes made, I will have to reimplement all map related changes in the last 3 days. If for whatever reason this is approved almost instantly, DON'T DO it. This thread was created early merely for feedback so I can work on the design while also fixing up everything else.

If you have any questions, concerns, or feedback, please post it here!

### CODE REVIEW

**Comment by LordFowl** [comment]
Kitchen on the current map is too small. Kitchen proposed is far too big. As you indicate it oretty much comfortable fit four chefs, not merely two, which is undesired. I'm not a huge fan of the canteen being a separate room from the kitchen - in fact it contributes greatly to the awkward shape and size of the proposed kitchen. Having the freezer room not directly connected to the food preparation area is also just inconvenient. Red tiling also is not a great look.

Bar is not nearly as problematic - the design is actually quite good. Connecting the kitchen and the bar directly is not a bad idea and could be kept. The game table looks like and seems like just a thing designed to feel space, and doesn't fit in very well. Games are better played at the library. I'd recommend filling the empty space with something more seamless/replacing it with more maint. The backbooths could also be increased in height by one tile so they can seat four instead of two. Pun Pun should start the bar counter/in the bar backroom or else he'll just get stolen round-start/wander into the halls. The bar having it's own speakeasy is ridiculous - there is no need for a multi-z backroom and should be returned to a small storage closet, 3x5 or so. If bartenders or others want a speakeasy it rests upon them to construct it in maint.

Speaking of maint, the dilapidated VIP lounge should be within maint. In construction areas should not be directly connected to any occupied area. The theater storage seems a little lazily done - looks more like a "free costumes here" room than a theater.

Altogether the main bar and the bar-kitchen access is good, but everything else is stricken by excess that should be weaned off.

**Comment by BurgerLUA** [comment]
Currently did a rework on the theatre area, it is now an actual theatre.
https://i.imgur.com/YDQbAY6.png

**Comment by BurgerLUA** [comment]
@LordFowl 

Did a rework of the theatre and the kitchen freezer based on your suggestion.
https://i.imgur.com/YDQbAY6.png
https://i.imgur.com/5XpFd0y.png

**Comment by NortonDK** [comment]
No mulebot access?

**Comment by LordFowl** [comment]
The bar is very good. The stage is an interesting design choice, and I am sure everyone will love the piano - but in all seriousness the opportunity of entertainment in a bar is a good move. For the maint theatre I would mix in some plating and broken tiling in with the wooden floors. The awkward and overly spacious kitchen and the unnecessary sublevel bar backroom however remain in my opinion a significant mark against the overall changes. I would recommend shrinking the kitchen down so it fits 2 chefs but not more, and using the extra space to bring the bar backroom up. The drive-thru would work best if it were not separated from the main kitchen by a door.

**Comment by TheGreatJorge** [comment]
I'm against the sublevel bar area. It just looks like overkill to me, something that doesn't need to / shoudn't be there.
Then I'm also not a fan of the red kitchen floor. It just seems to stick out too much. I'd stay with conventions of white kitchen floors.
Also, the jukebox kind of seems in the entrance way. Maybe put it besides the stage or something? So that you don't run into it when entering the bar.

Also...
`"A self-inserted plaque commemorating of the new construction of the kitchen and bar by Diamond With Flaw."` 
I... am not quite sure the plaque should really be there. I mean. Yeah.

**Comment by BurgerLUA** [comment]
Plaque was a meme in discord channel and will not be there in the finished project

**Comment by BurgerLUA** [comment]
Added mulebot to the kitchen. Carpet was fixed earlier when I figured out the carpet tiles are self-generating.

**Comment by Arrow768** [comment]
Overall, I really like the changes, but there are still a few things that should be addressed:

- Make sure the cameras cover all non-maint areas of the bar (Including the backroom, freezer and lower level)
- In my opinion the red tiles are not a perfect fit for the kitchen, maybe go with the traditional white.
- The "VIP" area on the main level should be integrated with maint and not directly accessible without removing walls, (Similar to the previous theatre, where you have to remove two walls behind the dance floor to get to it)
- Add ringer buttons and terminals (Think about how to integrate the food counter on the left, the main counter and the sublevel; It might be possible to add multiple ringer buttons per terminal)
- There are quite a lot of posters

I think we should give the sublevel and the current size of the kitchen a try.
If it doesn't work out, we can always rework / remove it (similar to the first atmos iteration).
But I believe that it has some amazing potential.

Huge thumbs up to you for seeing a issue and presenting a solution to it.

**Comment by BurgerLUA** [comment]
Removed the red flooring and just left it as white flooring. Going to remove more posters in the bar as this is a professional working environment and most of the posters are lewd animes.

I will add ringers to the bar and canteen. I will look into finding an actual kitchen ringer sound so it doesn't sound like other departments.

**Comment by BurgerLUA** [comment]
Closing this for now. Will likely start up an entirely fresh version of the map from scratch in another PR.

**Pull request closed without merging**
