### PR TITLE
Let there be DRINKS! Tea, cider, and related adjustments. 

### PR DESCRIPTION
**Pull request by Doxxmedearly**
- Adds a bunch of new tea drinks with simple recipes. Most are made by mixing, a few are vendor/dispenser only.
- Tea, green tea, chai tea, and apple cider are available in both hot drinks vendors and the Coffeemaster 3000. They all have dispenser cartridges. 
- New sprites for new recipes and drinks.
- Makes it so the vending machine spits out tea in a disposable cup (like the coffee does) instead of a teacup.
- Discovered that pumpkin spice lattes were vending mixed with coffee due to the reagent_containers/food/drinks/coffee parent path. Adjusted. Worth keeping in mind for next year's addition of seasonal drinks. 
- Some of the latte descriptions were weirdly worded or missing words. Fixed that.
- Reagent color for iced tea was really blue before. Adjusted it to be similar to its sprite. 
- Adding two cans each of hakhma and fatshouter milk to the booze-o-mat to help bartenders fill more requests. More variety, more rp!

### CODE REVIEW

**Comment by Doxxmedearly** [comment]
!review

**Comment by MarinaGryphon** [comment]
I'm going to tell Abo that you called it Chai Tea.

**Comment by Doxxmedearly** [comment]
> 
> 
> I'm going to tell Abo that you called it Chai Tea.

Abo already has a hundred reasons to kill me. This means nothing to me.
Also https://i.gyazo.com/c22c786795aa7cfde25af1d0e5ce97c0.png

**Comment by alsoandanswer** [comment]
Bruh, calling it contracttea instead of bureaucra-tea is a missed chance deadass

**Comment by alsoandanswer** [comment]
Don't forget to change the icon state name of contracttea to bureaucratea so it won't go invisible

**Comment by Doxxmedearly** [comment]
> 
> 
> Don't forget to change the icon state name of contracttea to bureaucratea so it won't go invisible

I was just going to leave it as contracttea since the icon name wasn't changed but this is probably tidier in the long run.

**Pull request merged**
