### PR TITLE
Refactor << to to_world

### PR DESCRIPTION
**Pull request by skull132**
Refactors all instances of `world << x` to use the `to_world()` macro. The only unsolved instance is the `TGS_WORLD_ANNOUNCE` macro. Which cannot be replaced due to recursive macro usage or something? It's weird and requires a bit of testing.

Also removed a whole bunch of dead code (hence the 1.1k deletions). These were usually temporarily commented out things, or debug shit which is not used.

### CODE REVIEW

**Comment by skull132** [comment]
!review

**Comment by LordFowl** [comment]
Since you’re already going crazy could you go a little farther and universalize the to_chat() proc also?

**Comment by skull132** [comment]
> Since you’re already going crazy could you go a little farther and universalize the to_chat() proc also?

Not in this PR. This is relatively safe to change due to the compiler checking most of this, but the to_chat one will require a bit more work.

**Comment by Lohikar** [comment]
You find&replaced SS13SmoothingCutter too btw.

**Pull request merged**
