### PR TITLE
Return of the Paramedic

### PR DESCRIPTION
**Pull request by LynxSolstice**
This PR brings back the more accurate title for First Responders, of Paramedic, to bring it in line with some snippets of the SOP and to be more accurate to the role itself, as both Security Officers and the rare and elusive Firefighting Atmospherics Technician can be considered first responders.

also I just like it better.

Changes any mentions of first responder in gear/access/etc to Paramedic or PARAMEDIC where applicable.

### CODE REVIEW

**Comment by LynxSolstice** [comment]
!review

**Comment by LynxSolstice** [comment]
!wip

**Comment by LynxSolstice** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Review by DreamySkrell — APPROVED** [review]
not a fan of the huuuuge diff but ehh I guess

**Comment by LynxSolstice** [comment]
> This doesn't change the game-start spawn points. A Paramedic just spawned at the elevators in a round where this was test merged.

Fixed in the most recent commit!

**Pull request merged**
