### PR TITLE
Deletes every instance of /weapon

### PR DESCRIPTION
**Pull request by Pacmandevil**
todo:

- [x] Pass travis before fowl's did

- [x] compile before fowl's did

- [x] be better than fowl's due to locally grown Canadian hand labor

- [x] be first

### CODE REVIEW

**Comment by LordFowl** [comment]
here we see the unaffiliated contributor trying to futilely boost their LoC count on the insights so that they might appear notable

**Comment by Pacmandevil** [comment]
if I really wanted to boost LoC count I'd just mess with converting map files to tgm.


This is just brain damage.

**Comment by Pacmandevil** [comment]
Note that this will likely require some config changes.

**Comment by Pacmandevil** [comment]
take a shot every time I have to fix merge conflicts

**Comment by Sindorman** [comment]
Lol, example of find/replace. That is amazing that it has 17379 lines that used weapon.

**Comment by LordFowl** [comment]
this PR is an example of cyberbullying and i am calling the fbi if it gets merged

**Comment by Lohikar** [comment]
Something's wrong with Travis, DNM until it's passing.

**Comment by skull132** [comment]
DNM until a few days before the update. That might be the best time to merge this as to not piss off people.

**Comment by Pacmandevil** [comment]
I'll leave this up to fowl, the superior coder. if need be, and he turns out to be a sham, someone ping me or something and I'll finish it.

**Pull request closed without merging**
