### PR TITLE
Suit Cyclers now store voidsuits on the SCCV Horizon

### PR DESCRIPTION
**Pull request by Generalcamo**
Instead of racks with glass surrounding them, we now store voidsuits directly in cyclers. In my opinion this looks neater, and it also allows for quick and easy refittings when needed, instead of multiple people trying to fight over a single unit:
image

To facilitate this, suit cyclers now store magboots and breath masks. This also allows them to be disinfected if needed. Some code was also cleaned up, and sounds were added for closing and locking the doors on the cyclers.

### CODE REVIEW

**Comment by Generalcamo** [comment]
!review

**Comment by GMR25** [comment]
This looks lovely, but I thought we had the old suit storage units sitting around for this purpose? If I remember those had the cool feature of being able to hide in them.

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by FluffyGhoster** [comment]
image

Is this a rendering artifact of the bot? Why was that room turned into metal foam?

**Comment by Generalcamo** [comment]
> image
> 
> Is this a rendering artifact of the bot? Why was that room turned into metal foam?

Looks like an improper merge was attempted by github. This should be fixed now.

**Review by Alberyk — APPROVED** [review]

**Pull request merged**
