### PR TITLE
Diona Aesthetic

### PR DESCRIPTION
**Pull request by Geevies**
* Added a lot of Diona customization options: Hair, Facial Hair, and Body Markings.

image

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Review by Chada-1 — APPROVED** [review]
👏

**Comment by listerla** [comment]
So - a few concerns to leave.

1. The markings, unlike the existing markings, are not prefixed in name w/ 'Diona' which can make locating them difficult. Minor thing.
2. The 'blinking' ones seem to have no delay on their frames, meaning they blink again the instant the eye opens back up. There should probably be some delay there. Not sure why this is, because the DMI clearly shows that this is not the case.
image
3. The P-Body marking is cut off, with only the lower part of the sprite showing.
image
4. These are almost all remarkably difficult to color to anything except Default Bark 30 tone Dionae. Likely out of scope to fix, but worthy of note as a large amount of Dionae would, according to lore, not follow that color scheme.

**Review by JohnWildkins — APPROVED** [review]
Seems to work. The blinking helmethead blinks at an insane rate, but I guess that's just a problem with body markings?

**Pull request merged**
