### PR TITLE
Remove appendicitis

### PR DESCRIPTION
**Pull request by TheGoret**
Appendicitis is a really annoying thing in the game, and I don't know one person that likes it. It breaks immersion (I know someone that had it 5 times with his character), and doesn't bring up any good RP except getting in the middle of it.

EDIT: The sprite removed in the .dmi file is the infected appendix.

### CODE REVIEW

**Comment by TheGoret** [comment]
!wip

**Comment by TheGoret** [comment]
!review

**Comment by alsoandanswer** [comment]
Feedback thread, please

there is clearly some opposition to this

**Comment by LadyFowls** [comment]
Also merge conflicts

**Comment by TheGoret** [comment]
I'm closing this. i'll remake this properly when I have the time because there's alot of different idaes.

**Pull request closed without merging**
