### PR TITLE
Ghostspawner whitelist check fix

### PR DESCRIPTION
**Pull request by DreamySkrell**
image

there was a `uses_species_whitelist` var, but it was not actually used to check if the spawner would actually be spawnable for the player

### CODE REVIEW

**Comment by DreamySkrell** [comment]
!bugfix

**Comment by DreamySkrell** [comment]
!review

**Comment by Arrow768** [comment]
DNM until I can review this as I am relatively sure there is some check related to the whitelist var.

**Comment by DreamySkrell** [comment]
So... How is it?

**Review by Arrow768 — CHANGES_REQUESTED** [review]
This should be optimised.

Currently it loops through each possible species to check if the player is whitelisted.

This loop should be skipped if we dont use the whitelists for the role -> There is no need to loop through each possible species and perform a whitelist check.

Additionally, the loop can be aborted after we have found the first whitelist.
(The variable `can_spawn_as_any` that is used to track if the player is whitelisted for at least one species cant get any `TRUE`-er after it has been set to `TRUE` the first time.)

**Comment by DreamySkrell** [comment]
Optimized.

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
