### PR TITLE
Add species restrictions to the breacher suit

### PR DESCRIPTION
**Pull request by Alberyk**
Only unathi are able to deploy and wear the breacher suit, both nanotrasen and the original version.

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
isn't the lore here inherited from the bay RIGlore in that rigs except the breacher conform to the wearer, there just isn't sprites?

**Comment by skull132** [comment]
DNM until review and discussion. Won't fit the current pull window.

**Comment by skull132** [comment]
No other RIG differentiates species at this moment. Either make all RIGs follow the same rule, or get this passed the suggestions forum. (Or get lore to wave it.) You can reopen this then.

At the present, though, denied.

**Comment by Alberyk** [comment]
Pull request open once more due to staff related request, I may also try to explain to the lore person how things even work.

**Comment by skull132** [comment]
Decreed by the mods and mins, as they're getting annoyed at sec (Syion) running around in breachers, and authorized by lore. In it goes.

**Pull request merged**
