### PR TITLE
Changed the order of the give prompt

### PR DESCRIPTION
**Pull request by Bedshaped**
I changed the order of no and yes in the give prompt because it always gets really confusing when you're typing and you accidently auto-refuse something. LOOC gets involved and it's always really frustrating.

### CODE REVIEW

**Comment by Bedshaped** [comment]
So why do those old commits keep popping up?

**Comment by skull132** [comment]
Because you haven't rebased your base branch. Usually it'd be clean and exactly 1:1 with the repo here.

Kind of irrelevant at the moment, though. They'll get removed when I squash the pull request into a single commit.

**Comment by NanakoAC** [comment]
Does changing the order help?

I thought it said No if you hit N, and yes if you hit Y

**Comment by Bedshaped** [comment]
It makes the keyboard default to Yes if you accidentally hit enter while you're typing to someone who is trying to give you something.

**Pull request merged**
