### PR TITLE
Adds new synthlore title screens, reworks title logic.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
Leaving the lobby screen list empty now adds all icon states to the lobby screen list. Also, only one dmi plays at a time.

 This means that adding a new title screen is now as simple as just adding it to the dmi. Or making a new dmi for a new category.

Added a new sound when you click things in the menu - more futuristic.

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Comment by alsoandanswer** [comment]
I wonder if it's possible to pick a different selection every time, and maybe make it possible to choose the type of title screen you want

for example i could choose the corporations selection or the synthlore selection

**Comment by NonQueueingMatt** [comment]
No, I want them to all play for now.

**Comment by NonQueueingMatt** [comment]
!wip

**Comment by NonQueueingMatt** [comment]
!review

**Pull request merged**
