### PR TITLE
New Wall Sprites

### PR DESCRIPTION
**Pull request by Lohikar**
Ports a lightened version of Europa's wall sprites to replace our ancient old-/tg/ wall sprites.

Depends on #3502.

### CODE REVIEW

**Comment by Lohikar** [comment]
aaand forgot false-wall states.

**Comment by Zuhayr** [comment]
@SkowronX

**Comment by TheGreatJorge** [comment]
I am not saying these walls look bad. I just think they don't fit along with stuff like APCs, doors... holomaps. I hope this isn't going to end by completely changing the sprite theme we have.

**Comment by Arrow768** [comment]
Indeed. Wall mounted devices look a bit off.
But generally I like it.

**Comment by Lohikar** [comment]
Looks like this is going to need some mapping changes for APCs, Intercoms, and RCs to look proper.

**Comment by Arrow768** [comment]
These changes will be made in a separate PR ?
Or are they going to go into this one ?

**Comment by Lohikar** [comment]
They are going into this one.

**Comment by skull132** [comment]
Merge conflict and I think we're good, unless there's something else to be done here?

**Comment by Lohikar** [comment]
The fire alarm PR should probably be merged first, though this is technically a superset of it.

**Pull request merged**
