### PR TITLE
Engineering Roundstart Changes

### PR DESCRIPTION
**Pull request by furrycactus**
This PR was made after I did some discussing with Kyres1 about his suggestion thread, which can be found here: https://forums.aurorastation.org/viewtopic.php?f=18&t=12095

It effectively eliminates a lot of unnecessary tedium that engineers have to deal with every single round, specifically;
- Having to hack into atmospherics for gas every round.
- Having to drag two sets of shields up to the surface every round, find somewhere to put them, and build some ugly thing that sticks out into the hall.

I also fixed a few things, such as;
- A few ctags in atmospherics that I overlooked in my overhaul of that place.
- The weird incomplete three-door airlock that leads into the engine room.

Pictures:
https://i.imgur.com/oXKAOLh.png
https://i.imgur.com/JazXirv.png
https://i.imgur.com/fZBvcMg.png

This makes the gasses for setting up the engine readily available, so that people don't have to spend time breaking into Atmospherics every round when they shouldn't have to, and it ensures people can still do custom setups by giving variety to the gasses available. It also gives a proper cycling airlock into the engine room, which is also easier to carry the canisters through, instead of having to take them one at a time through three consecutive airlocks. It also greatly reduces the time that shields take to be set up by having them already in a dedicated and properly secure room on the surface. They still need to be wrenched into place and have their settings configured properly however, so apprentices can still learn just as easily. It just eliminates the terrible ordeal of carrying them up and building a spot for them every single shift.

### CODE REVIEW

**Comment by furrycactus** [comment]
Apparently I have that commit that Arrow made about AIs because I based this off of development and made a small mistake.

**Comment by furrycactus** [comment]
!review

**Comment by Sindorman** [comment]
Why do you have Arrow's commit from other PR? Use interactive rebase to drop it.

**Comment by flimango** [comment]
What arrow said. Tying shields into the surface grid is just a necessary evil of our current setup. I might even suggest giving it its own SMES if you’re feeling spicy. From my solars bug fix, there’s a main grid cable running through maint that you can string to the room, off to the left.

**Comment by furrycactus** [comment]
I tried using interactive rebase but I'm bad at git. Just going to close this and re-open it.

**Comment by furrycactus** [comment]
I tried using interactive rebase but I'm bad at git. Just going to close this and re-open it.

**Comment by furrycactus** [comment]
I tried using interactive rebase but I'm bad at git and couldn't do it. Just going to close this and re-open it.

**Comment by furrycactus** [comment]
Tried rebasing but I'm bad at git and couldn't get it to work. Just going to close this and remake it.

**Pull request closed without merging**
