### PR TITLE
New money sprites

### PR DESCRIPTION
**Pull request by alsoandanswer**
what it says on the tin

lottocards now update n' stuff

and you can actually kinda tell how much money from a dolla bill

dreammaker_JGlZx2wYnn

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by Geevies** [comment]
Not gonna lie, it looks like a bit of a visual downgrade. I like the 3D chipism of our current cash sprites. The flat paper money looks iffy. Could you maybe make the new sprites match the current sprites a bit more?
image

**Comment by alsoandanswer** [comment]
!review

**Comment by KingOfThePing** [comment]
Will you add coins someday, too? Burger once worked on that, I believe.

**Comment by alsoandanswer** [comment]
ah man too complex for my small brain

**Comment by Kaedwuff** [comment]
Could you also remove that irritating drumroll sound effect from lottery tickets? ;; Or at least make it only audible to the person using the ticket...

**Pull request merged**
