### PR TITLE
Tricordrazine Soul Readdition

### PR DESCRIPTION
**Pull request by Geevies**
* Tricordrazine is now made by combining dylovene and inaprovaline, no water.
* Tricordrazine now counters the blurry vision chemical side-effect.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Review by alsoandanswer — APPROVED** [review]

**Comment by Geevies** [comment]
> there's already a PR up doing the former part of this PR: #17461.

image

**Comment by lavillastrangiato** [comment]
Please don't. As an experienced medical player I have never ever wanted a situation where I combined the two most useful chemicals to stop someone from dying due to organ failure. Switching the tricord recipe was an extremely useful quality of life change and given that we can get tricord in the sleeper, there's no reason to revert it.

**Review by FluffyGhoster — APPROVED** [review]
Code is fine, but a feedback thread should be opened to gather insight if this change is beneficial or it's preferred for it to require water too so you can use Inaprovaline and Dylovene together

**Pull request closed without merging**
