### PR TITLE
Various tweaks and Medical Bay additions, again

### PR DESCRIPTION
**Pull request by sheeplets**
Holy shit, please work this time. I'm begging you. I have no idea what I'm doing and I'm just praying that I don't break anything.

- Organizes things on a few tables to look cleaner. The store room is now organized, no more turf-tab hunting.
- Removes an out of place ICU floor decal in the GTR.
- Removes the duplicate glove boxes from the OR's, adds another box with the others across from the elevator. Along with surgical masks and a second box of body bags. I like even numbers.
- Removes the racks with safety goggles on them from inside the OR's.
- Relocates one bag of O- blood from each OR to the ICU's supply. Bringing it to a total of six bags (up from four).
- Changes the disposals chute in the Psychiatrist's office from a full-sized one to the slim variant, to prevent further suicide attempts. Per request.
- Removes water cups from Medical and the Brig. You can click the coolers with an empty hand to dispense an infinite number of cups.
- Moves the ringer button in Medical's lobby to just outside the GTR's front door.
- Adds a first aid wall closet into the Medbay lobby. Two stacks of gauze, two stacks of ointment, two inaprovaline injectors, and two dylovene injectors. Your odds of survival during deadpop have very slightly improved.
- Adds a bottle of bicaridine tablets to the medication cabinet in the GTR and First Responders' quarters. For chemically treating AB without surgeons.
- Adds another coagzolug autoinjector to the First Responders' quarters, a total of four (up from three).
- Allows the Rescue Hardsuit to hold blood bags in the suit storage slot. Per request.
- Adds two lifeform stasis beds to the ICU, nerfs their stasis factor (15x→10x). Also added a cheeky window behind a status board to get rid of the blind spot leading into there.

### CODE REVIEW

**Comment by sheeplets** [comment]
!review

**Review by SleepyGemmy — APPROVED** [review]
PR looks good.

**Comment by sheeplets** [comment]
mspaint_dp60soeNDY

**Comment by desvenlafaxine** [comment]
Could you add a Tajara and Unathi specific glove boxes somewhere? It's just a pain to try to hunt them shift clicking ATM

**Comment by Spud5** [comment]
> * Adds two lifeform stasis beds to the ICU, nerfs their stasis factor (15x→10x).

This sounds like a really big change and I think you should make a forum thread about it first.

**Comment by AMcilraith** [comment]
I would appreciate greatly if you added a soporific bottle in the psych locker.

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
