### PR TITLE
Replaces the unathi merc rigs sprites with the baystation version

### PR DESCRIPTION
**Pull request by Alberyk**
What the title says;
rig

### CODE REVIEW

**Comment by Belsima** [comment]
Could we see a comparison?

**Comment by Alberyk** [comment]
oldrig
It is just the old voidsuit sprites.

**Comment by Belsima** [comment]
thank

**Comment by Arrow768** [comment]
After a quick discussion with alberyk:
The main goal here is to provide a visual difference between the voidsuit and the rigsuit

**Pull request merged**
