### PR TITLE
Ports Goonchat from Baystation.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
Ports https://github.com/Baystation12/Baystation12/pull/28879

changes: 
  - rscadd: "Ported a new chat system, Goonchat, that allows for cool things like changing font style, size, spacing, highlighting up to 5 strings in the chat, and DARK MODE."
  - rscadd: "Repeated chat messages can now get compacted. You can disable this in goonchat settings."
  - rscadd: "You can change icon style to any font on your system."
  - tweak: "The game window has been altered a bit to adjust for this."
  - rscdel: "Removed skin style prefs as they are no longer used."

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!wip

**Comment by NonQueueingMatt** [comment]
!review

**Comment by skull132** [comment]
Staff announcements don't work.
Accent tags on radio don't work.

**Comment by NonQueueingMatt** [comment]
> 
> 
> Staff announcements don't work.
> Accent tags on radio don't work.
> Restart notifications not working.
> 
> Basically. Most staff shit doesn't work. I suspect it's everything that does `world <<`?

all fixed

**Comment by Valkrae** [comment]
On slower internet connections, or when a connection is interrupted, Goonchat will commit suicide upon logging in. It won't load, and will completely freeze the chat, making any attempt to play completely untenable.

This is happened numerous times, at peak hours, whenever I attempt to connect to the round.

**Pull request merged**
