### PR TITLE
Jackboot and black glove resprite

### PR DESCRIPTION
**Pull request by alsoandanswer**
Black gloves/ Jackboot resprite by @Imaginos16

### CODE REVIEW

**Comment by alsoandanswer** [comment]
!review

**Comment by SleepyGemmy** [comment]
please post a before- and after comparison, since the icondiffbot isn't working.

**Comment by TheStryker** [comment]
The sprite is good, but they seem too much like a modern boot compared to a jackboot. I think a case could be made for making this an alternate boot instead.
image
image

**Comment by TheDocOct** [comment]
> The sprite is good, but they seem too much like a modern boot compared to a jackboot. I think a case could be made for making this an alternate boot instead. image image

Agreed with this. It looks good, but it's just wildly different. I would prefer making them an alternative pair; duty boots or patrol boots or something.

**Comment by alsoandanswer** [comment]
I'd argue that the problem is not that these boots are too modern, is that our old jackboots are extremely outdated from the fact that we're in the year 2464. I'll concede that some cultures like Dominia probably still use old-fashioned Parade boots, but these are on the job workwear.

I digress, though. The onmob sprite is practically identical to our current ones and I don't think there will be much difference.

**Review by Alberyk — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by Imaginos16** [comment]
Wow, my PR went quite far! Hello from /tg/!

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
Actually, toeless, knee-high and thigh-high jackboots will need their sprite changed to match.

**Pull request merged**
