### PR TITLE
Nozzle spray display fix.

### LINKED ISSUE #15337: Spray says 30 units for 3 tiles
image

Not sure if it is actually using 30 units or if the text is wrong. Whatever the case may be, it should be 10 as before. For reference, you use 5 units for one tile.

### PR DESCRIPTION
**Pull request by 1Sparky1**
Title. Fixes #15337

### CODE REVIEW

**Comment by 1Sparky1** [comment]
!bugfix

**Comment by 1Sparky1** [comment]
!review

**Comment by Geevies** [comment]
not really a fix, since the * spray_size gives you the total u used per spray

**Comment by 1Sparky1** [comment]
> not really a fix, since the * spray_size gives you the total u used per spray

Firstly, if that were the case it would be horribly inefficient to use the larger volume (5*1 vs 10*3). Secondly, as far as I can see in the code, only amount_per_transfer_from_this is used, regardless of the number of tiles.

**Comment by Geevies** [comment]
> > not really a fix, since the * spray_size gives you the total u used per spray
> 
> Firstly, if that were the case it would be horribly inefficient to use the larger volume (5_1 vs 10_3). Secondly, as far as I can see in the code, only amount_per_transfer_from_this is used, regardless of the number of tiles.

it's used by the chemsprayer here, so I guess the fix would be to make this logic only display for the chemsprayer path and have the old text display for the normal path
image

**Comment by 1Sparky1** [comment]
> > > not really a fix, since the * spray_size gives you the total u used per spray
> > 
> > 
> > Firstly, if that were the case it would be horribly inefficient to use the larger volume (5_1 vs 10_3). Secondly, as far as I can see in the code, only amount_per_transfer_from_this is used, regardless of the number of tiles.
> 
> it's used by the chemsprayer here, so I guess the fix would be to make this logic only display for the chemsprayer path and have the old text display for the normal path image

The chemsprayer doesn't have multiple spray sizes, so I think it doesn't need to be considered for this.

**Comment by Geevies** [comment]
> > > > not really a fix, since the * spray_size gives you the total u used per spray
> > > 
> > > 
> > > Firstly, if that were the case it would be horribly inefficient to use the larger volume (5_1 vs 10_3). Secondly, as far as I can see in the code, only amount_per_transfer_from_this is used, regardless of the number of tiles.
> > 
> > 
> > it's used by the chemsprayer here, so I guess the fix would be to make this logic only display for the chemsprayer path and have the old text display for the normal path image
> 
> The chemsprayer doesn't have multiple spray sizes, so I think it doesn't need to be considered for this.

image

**Review by SleepyGemmy — APPROVED** [review]

**Pull request merged**
