### PR TITLE
Changes color of Ya'ssa

### PR DESCRIPTION
**Pull request by Afya212**
Currently with Ya'ssa in light mode, it is very difficult to differentiate it between the black of common. This update changes that.
image
image

### CODE REVIEW

**Comment by Afya212** [comment]
!review

**Comment by WickedCybs** [comment]
I don't think it's difficult at all as it is a rather clear shade of blue similar to tradeband. The pink is very out of place here.

**Comment by Afya212** [comment]
> I don't think it's difficult at all as it is a rather clear shade of blue similar to tradeband. The pink is very out of place here.

Pink was an arbitrary-ish color choice. Personally I can tell when someone is speaking tradeband by color but I cannot at all when someone speaks Ya'ssa.

**Comment by WickedCybs** [comment]
> > I don't think it's difficult at all as it is a rather clear shade of blue similar to tradeband. The pink is very out of place here.
> 
> Pink was an arbitrary-ish color choice. Personally I can tell when someone is speaking tradeband by color but I cannot at all when someone speaks Ya'ssa.

I would suggest not radically changing the colour to something not even a little bit similar then.

**Review by Arrow768 — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
