### PR TITLE
Modular guns rework

### LINKED ISSUE #6504: New SMES units don't work when built.
In the event someone needs to rebuild a SMES unit, they simply don't work. They store or output power, and can't go higher than 0W input and output level if you try to change the settings.

https://prnt.sc/nuhnsa

### PR DESCRIPTION
**Pull request by Sindorman**
This PR:
- Modular guns can no longer accept mods of same types. No more 6 bayonets

- Modular guns can be used in creating turrets.

- Turrets now use max accuracy value between gun or projectile accuracy which is increased too by 25%. Making turrets more accurate than people.

- Turrets now have deploy, retract and rotate sound effects.

### CODE REVIEW

**Comment by VTCobaltblood** [comment]
If modular guns can't accept mods of the same types, you will create many more problems than you fixed. A lot of modular gun builds rely on stacking together reinforced barrels to increase the reliability of a gun. Or, for example, there are little things wrong with stacking stocks to improve accuracy. Not to mention, this makes large guns useless as you will never need 5 *different* gun mods. This is poorly thought through, the problem would be fixed better if *specific* parts couldn't be stacked (such as bayonets, lenses, capacitors, sniping sights, etc.)

**Comment by VTCobaltblood** [comment]
Also I guess fuck nuclearity?

**Comment by ParadoxSpace** [comment]
Stacking surge protectors is basically required if you don't want the gun to literally shit itself on the third fire. This completely ruins modular guns more than firing pins ever did.

**Comment by printer16** [comment]
You should separate the bug fixes from the "updates" as the updates carry quite a bit of weight with them.

**Comment by Sindorman** [comment]
!wip

**Comment by OneOneThreeEight** [comment]
what the fuck. wrong button. ignore that.

**Pull request closed without merging**
