### PR TITLE
Removes Some Unused Map Files

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR removes some unused map files to make maintenance and object path replacements et cetera easier.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Review by RyverStyx — APPROVED** [review]

**Review by alsoandanswer — APPROVED** [review]

**Review by Arrow768 — CHANGES_REQUESTED** [review]
The intention of "Odin departures" is to provide a starting point for events where things take place on a different map.
In these cases it is useful to have a minimal starting map for performance reasons.

If anything is done it should be changed to "generic space dock".

Replacing objects is relatively simple and can be done with a search/replace operating if done correctly (or by opening the map and replacing the paths)

**Comment by SleepyGemmy** [comment]
requested changes addressed.

**Review by JohnWildkins — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
"sol.dmm", "syndicate_base.dmm", "syndicate_shuttle.dmm", "asteroid_outpost.dmm", "pra.dmm" are all used in the spawn map template button in build mode. Either make it generic and able to spawn every template (preferable) or don't remove them.

You'll also need to edit templates_list.json in the config

**Comment by SleepyGemmy** [comment]
!review

**Pull request merged**
