### PR TITLE
Fixes atmos jumpsuit

### PR DESCRIPTION
**Pull request by desvenlafaxine**
Checking sprites I noticed it had a missing pixel. 

imagen

### CODE REVIEW

**Comment by desvenlafaxine** [comment]
!review

**Comment by desvenlafaxine** [comment]
!bugfix

**Comment by WickedCybs** [comment]
Chef suit seems to be changed here too. That a mistake?

**Comment by desvenlafaxine** [comment]
> 
> 
> Chef suit seems to be changed here too. That a mistake?

Probably yes, I was messing up with uniforms and likely made an edit by mistake. It's fixed now.

**Review by WickedCybs — APPROVED** [review]

**Review by Geevies — APPROVED** [review]

**Pull request merged**
