### PR TITLE
Adds a ton of suit slot sprites.

### PR DESCRIPTION
**Pull request by Belsima**
Half a port of https://github.com/PolarisSS13/Polaris/pull/3695, half mirrored belt sprites.

If the gun back sprites aren't wanted, I'll cut it back to purely mirrored belt sprites.

FUCK THIS ISNT DEV

### CODE REVIEW

**Comment by Belsima** [comment]
FUCK THIS ISNT DEV

**Comment by Belsima** [comment]
now this is what i call dev

**Comment by skull132** [comment]
Erm, real quick, are these actively used in code or are you just dumping them here for further use?

**Comment by Lohikar** [comment]
They're used & work. The code always tried to load these icons but they were not present, so did not render.

**Comment by skull132** [comment]
Then merged it gets.

**Pull request merged**
