### PR TITLE
EMP Grenade/Artifact Nerfs

### PR DESCRIPTION
**Pull request by ParadoxSpace**
EMP grenades/artifacts should no longer obliterate an entire map level's worth of things.

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
!review

**Comment by NonQueueingMatt** [comment]
What's the new emp grenade radius like?

**Comment by ParadoxSpace** [comment]
2 tiles of heavy range, 5 of light range. It's still punishing, but you can escape it.

**Comment by Arrow768** [comment]
Feels like a bandaid fix to a larger issue.

**Pull request merged**
