### PR TITLE
SSMD Updates

### LINKED ISSUE #15452: SSMD Ship Issues
- the SSMD ship's shuttle has no interior cycling button.
- the SSMD ship's shuttle's blast door buttons aren't labelled.
- the SSMD ship's medical bay has no hyposprays.

### PR DESCRIPTION
**Pull request by lavillastrangiato**
GitHub, you are stupid.
- Updates airlocks on the SSMD Corvette.
- Updates some access stuff on the SSMD Corvette.
- Replaces some fake objects and 3/4th'd stuff in the SSMD Corvette.
- Adds CO2 tanks!
- Renames the SSMD Corvette to the Sol Reconaissance Corvette.

From @TheDanseMacabre: Edits the text on the ghost roles to match lore.
Also fixes #15452.

### CODE REVIEW

**Comment by lavillastrangiato** [comment]
!review

**Comment by DreamySkrell** [comment]
image
transit area is wrong (shuttle added there to show it can't fit inside the X teleporters)

image
should be more like this

**Comment by DreamySkrell** [comment]
image
entry points are wrong on the shuttle
like here is /aft subtype entry point renamed to fore, cockpit

**Comment by DreamySkrell** [comment]
image
image
do not overlap scrubbers/vents with pipes, except if super super tight
these scrubbers may also connect to to the propellant pipes

**Review by DreamySkrell — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
