### PR TITLE
Gauss thumper penetrates armor

### PR DESCRIPTION
**Pull request by flpfs**
Does less damage, but penetrates armor, I playtested the values and it looks okay, specially since it will be used by the ERT against strong antags.

### CODE REVIEW

**Comment by flpfs** [comment]
!review

**Comment by flpfs** [comment]
https://forums.aurorastation.org/topic/12624-give-the-gauss-thumper-armor-penetration/
Feedback thread

**Comment by alsoandanswer** [comment]
Would you mind sharing more about your playtesting? i.e, can it down a fully equipped security officer, does it instagib them etc. etc.

**Comment by NonQueueingMatt** [comment]
What's the reason for this?

**Review by Alberyk — CHANGES_REQUESTED** [review]
Gauss slugs having more armor penetration than a rifle round is not going to happen.

**Comment by flpfs** [comment]
Gonna close this and come up with a better value

**Pull request closed without merging**
