### PR TITLE
Cult Communication Update

### PR DESCRIPTION
**Pull request by Butterrobber202**
This change will allow Cultists to communicate with each other easily, as if they had a radio. Brings them on par with other team antagonists who already have easy IC communication methods.

### CODE REVIEW

**Comment by Butterrobber202** [comment]
!review

**Review by SleepyGemmy — APPROVED** [review]

**Review by KingOfThePing — APPROVED** [review]

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
Not strictly against this but at this point communication talismans should be removed as they are completely useless now.

**Comment by Butterrobber202** [comment]
> Not strictly against this but at this point communication talismans should be removed as they are completely useless now.

done

**Review by SleepyGemmy — CHANGES_REQUESTED** [review]
remove `#include "code/game/gamemodes/cult/runes/communicate.dm"` from the DME.

**Comment by Butterrobber202** [comment]
> remove `#include "code/game/gamemodes/cult/runes/communicate.dm"` from the DME.

yeah I noticed that. How do I do this.

**Review by SleepyGemmy — APPROVED** [review]

**Pull request merged**
