### PR TITLE
Chemistry Codex

### PR DESCRIPTION
**Pull request by Geevies**
* Chemists now spawn with a chemistry codex.

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Comment by MarinaGryphon** [comment]
Why not just port the actual codex subsystem but lock it behind items like this?

**Comment by Geevies** [comment]
> Why not just port the actual codex subsystem but lock it behind items like this?

I tried porting the codex but it got denied, so I'm doing this instead

**Comment by skull132** [comment]
Closed in favour of #9413

**Pull request closed without merging**
