### PR TITLE
Clerical Module computer records program

### PR DESCRIPTION
**Pull request by Ben10083**
Clerical module now has records program like AI, allowing it to view and edit records similar to AI.

This allows it to do things like update physical status or criminal status

### CODE REVIEW

**Comment by Ben10083** [comment]
!review

**Review by SleepyGemmy — DISMISSED** [review]

**Comment by DreamySkrell** [comment]
Clerical borgs are not part of medical or security department, so they should not be changing med or sec records.

**Review by FluffyGhoster — APPROVED** [review]
The code is fine.

It's not up to us to decide if this goes in or not, just to review that the code won't break anything, and the likes; However, I agree with Dreamy's preference, personally

**Comment by NonQueueingMatt** [comment]
Unwanted for the reason Dreamy brought up.

**Pull request closed without merging**
