### PR TITLE
Point Verdant Clinic

### PR DESCRIPTION
**Pull request by SleepyGemmy**
this PR adds the Point Verdant Clinic and a physician role with 1 slot, balances the ghost roles amount, and balances the available medical supplies.

### todo
- [x] look over medical and robotics ghost role amount.
- [x] balance the supplies.
- [x] make the clinic and pharmacy building more compact?
- [x] remove the new surgery room.
- [x] give the physician a classic doctor fit.
- [x] finalize the description and welcome message.

### changes
- added the Point Verdant Clinic.
- added a physician role.
- added a clinic sign.

### changes since PR creation
- merged the pharmacist role into the new physician role.
- removed 1 KRC doctor role and 1 KRC surgery room.
- removed the new surgery room and moved the recovery room downstairs.
- removed 14 10u inaprovaline pill bottles, 4 inaprovaline bottles, 4 advanced trauma kits, 3 rolls of gauze, 4 bottles of 15u dylovene pills, 1 health analyzer, 7 ointments from the pharmacy's shelves.
- removed 1 advanced first-aid kit, 1 surgery kit, 1 2u corophenidate pill bottle, and 1 assorted pills bottle from behind the pharmacy's counter.
- removed 1 10u mortaphenyl pill bottle, 2 assorted pills bottles, 1 auto-CPR, and 1 defibrillator from the pharmacy's basement.

### CODE REVIEW

**Comment by SleepyGemmy** [comment]
!review

**Comment by DreamySkrell** [comment]
I intentionally did not add a clinic to Point Verdant, cause I think there are many options existing already for fixing people's boo-boos, as well as other reasons:
- The pharmacy has A TON of medical supplies available for selling, including two full surgery kits, a ton of meds, medkits, chemistry lab with a ton of cartridges to make even more meds, etc

- The robotics clinic has operating tables too
- Horizon has the Intrepid with a small medbay on it
- I think all of these above options are more soulful and provide more interesting narrative than a clinic like this. 
- I have also hoped to see the locals being airlifted up to Horizon for treatment - how cool would that be? That can't really happen if they just have a clinic with a surgeon (or if Horizon's surgeon just uses the clinic like they own the place, which they will do)
- I don't think every city/site/ship needs to have the same full set of functionalities. I think it is soulful if some things are lacking, and players need to work around them, or cooperate with other players, ghostroles or crew. 
- There is also more than enough ghostroles on PV, and we don't need even more. They already have a hard time being filled as is.

**Comment by lavillastrangiato** [comment]
I would actually be totally okay with a clinic to Aoyama/PV.

Originally I thought "haha, you would have to be a total goonster to get injured to the point of needing surgery on PV. Who would get a random bone-break?" But because of the nature of SS13, some easy-to-fall zones that are up a z-level, and the nature of randomly getting hit by bikes, it is pretty easy to fall, shatter your ribs, break a leg, get shot by evil fucked up yakuza, accidentally step into sewage water (if you're a ROLE THAT SHOULD BE DOWN THERE), etc. I am sorry to say it is not "soul" to be lifted up to the Horizon if you so much as break a leg. It is butt and ass, not just for the ghostrole but for the crew to constantly have to bring you up, down, up, down if you happened to input wrong and stumble off a ledge.

I think if there was a physician role just added to spawn in the pharmacy or if the pharmacy was more made into a clinic that would be fine, rather than adding a whole new building. There is some stuff in the pharmacy anyway that is best-suited for a doctor to use. The pharmacy has a lot of medicines that don't really need to be duped in a clinic.

**Comment by Leroyengloys** [comment]
I agree with dreamy. PV already has plenty of medicine available, it just requires thinking a bit out of the box. A dedicated doctor's place wouldn't solve much if it did require a new ghostrole, because the role wouldn't be manned half the time. If the issue is a lack of lore know-how on the pharmacist's part on how to treat, we can allow them to have more medical knowledge than the average Horizon pharmacist.

**Comment by furrycactus** [comment]
Just came here to give a single bit of input - a single IV stand would be incredibly beneficial in the clinic. Currently there's a container of Saline Plus in the Pharmacist's basement (which is nice as it can't be made without Phoron and is worse to have than outright blood) but it's almost functionally useless right now as it doesn't restore blood volume unless given in a <2u dosage, which is only realistically achievable with an IV stand. Dumping someone full of thetamycin and spam-injecting saline in 1u intervals with a dirty syringe while someone has critically low blood volume is incredibly frustrating and immersion-breaking, but it's the only real option for treating cases like that.

Also this is just a personal thing, but the girder wall-hole connecting the basement to the 5-Cheung hideout is incredibly soulful and has led to some really enjoyable RP implying 5-Cheung and the Pharmacist are in cahoots and probably supplies their drugs. I'd be sad to see it patched up.

**Pull request closed without merging**
