### PR TITLE
Re-Implements Departmental Security

### PR DESCRIPTION
**Pull request by LadyFowls**
To continue on from Fowls work (God bless him) I have decided to take this on and make sure its added because of the amount of care and work put into this.

### CODE REVIEW

**Comment by NiftyBaby** [comment]
God dammit, here we go again.

**Comment by Mogelix** [comment]
Theres a reason this died, and it involved very loud yelling. I wish you luck in developing, but no luck in developing this project in particulatar.

**Comment by Kaedwuff** [comment]
Always with the sith, there is a master and apprentice...

**Comment by ParadoxSpace** [comment]
> Theres a reason this died, and it involved very loud yelling. I wish you luck in developing, but no luck in developing this project in particulatar.

Are you aware that Fowl leaving is why it died?

**Comment by ben10083** [comment]
I highly recommend the feedback required tag be added, as well as adding a topic under projects

**Comment by VTCobaltblood** [comment]
Is this going to be worked on?

**Comment by GMR25** [comment]
I'd love to see further work on this.

**Pull request closed without merging**
