### PR TITLE
Buddy Tags

### PR DESCRIPTION
**Pull request by Geevies**
* Added buddy tags to the utility loadout. They're small devices that can be attached to uniforms that will beep if they don't have a paired buddy in range.

Ported from: https://github.com/Baystation12/Baystation12/pull/25432

image

### CODE REVIEW

**Comment by Geevies** [comment]
!review

**Review by JohnWildkins — CHANGES_REQUESTED** [review]
Loadout option only spawns one buddy tag, and I'm assuming you need two.

Buddy tags should probably also start with a random ID (rather than all being 1, although w/e). Cool QoL would be to let you set the ID of one buddy tag by clicking on another buddy tag while it's in hand.

**Comment by Geevies** [comment]
ID randomized. I think spawning two isn't needed. Players can collaborate on characters together and spawn with buddy tags for RP purposes. Spawning two just makes it awkward, I feel? Maybe we can adjust it post-merge if it isn't working out.

**Review by JohnWildkins — APPROVED** [review]
Code-wise it's fine then, but as-implemented it'll probably get used like, twice. I don't play though, so I am a bad judge of such things.

**Review by Arrow768 — APPROVED** [review]

**Pull request merged**
