### PR TITLE
INDRA Map Bugfixes

### PR DESCRIPTION
**Pull request by furrycactus**
Addresses some tiny map issues in and around the INDRA Reactor room. 
- Flips the direction of a disposals junction.
- Changes some pipe colours.
- Moves a table and adds a third office chair to the monitoring room.
- Hopefully fixed the problem with dragging objects behind the gyrotron.
- Fixes the gas sensor and gas injectors in the fusion chamber having broken id_tag variables.

### CODE REVIEW

**Comment by furrycactus** [comment]
!bugfix

**Comment by furrycactus** [comment]
!review

**Comment by DreamySkrell** [comment]
image
strongdmm silently fails on this

**Review by DreamySkrell — APPROVED** [review]

**Comment by DreamySkrell** [comment]
> ...
 strongdmm silently fails on this

err-- meant mapdiffbo2 here... but actually it seems that it is checking the old map instead of the new changes
so that is weird

**Review by alsoandanswer — APPROVED** [review]

**Pull request merged**
