### PR TITLE
Airlock rework to feature drone hatches

### PR DESCRIPTION
**Pull request by AgentWhatever**
Re-worked all airlocks to feature drone hatches and animation. Includes firelocks and other stuff.
Didn't touch anything code-wise

### CODE REVIEW

**Comment by AgentWhatever** [comment]
Note that I'm not a coder, so I didn't touch the code layering the current hatch over the airlocks

**Comment by skull132** [comment]
This was actually discussed during the implementation of the door hatches - whether this should be achieved via algorithm or hardcore spriting.

We chose algorithm because it meant we didn't need to worry about pooling up vast amount of sprites for doors that don't need the hatches.

**Comment by AgentWhatever** [comment]
Though the neat thing is that I went trough all of the sprites and corrected some errors and inconsistencies here and there. Plus you only have to run a process that overlays the hatch_open sprite over the airlock, so you can now ditch the code coloring the current hatch and placing it over the airlocks

**Comment by AgentWhatever** [comment]
I'd be happy to update any future airlock additions, because I left the templates in the hatches.dmi

**Comment by skull132** [comment]
Right now, with your mods, _all_ airlocks have hatches, aye?

The thing is. This is memory vs CPU usage. Hatches are cached, meaning one overlay is generated per airlock type, if at all (some may have overlapping colours). And the overlay is simply added and removed from that point onward, never actually deleted and recreated. So the CPU usage is small. Beats the hell out of having n * 2 amount of airlock sprites: one for with hatch, one for without.

**Comment by AgentWhatever** [comment]
All of the airlocks that supposedly have the hatch function are now more or less sprited to permanently have the hatch. It wasn't my idea to have two sets of airlocks running. Just this set replacing the current one

**Comment by AgentWhatever** [comment]
Not to mention the way it is now, that means, without animations, is _[ugly](https://www.youtube.com/watch?v=eHQI6kLDrjc)_

**Comment by NanakoAC** [comment]
jesus fuck no, why did you do this?

Animations can be achieved without incorporating all the sprites into doors. I chose overlays for a reason

What you've done here is completely unnecessary and not at all related to animation. It is an objectively dumb idea. This is why you should ask someone before working on something they touched, i could have told you how to do this better.

**Comment by AgentWhatever** [comment]
How would you overlay an alpha over an existing sprite, then?

**Comment by skull132** [comment]
You'd need to look into if you can animate or flick() an overlay.
You start the animation on the hatch, add it as an overlay for the door, animate the door. Hopefully, they end up being in sync.

**Comment by AgentWhatever** [comment]
Which is why I thought this was the more viable solution as it requires little code or and no timing issues.
Though considering the cache it would be more viable to either do it with overlays or swap the sprites, making most of the airlocks pemantently drone-friendly. The only airlock I haven't seen with a drone hatch is the vault airlock, though.

**Comment by NanakoAC** [comment]
'requires no code' isnt an advantage nor a justification for a poor technical design.
i may make the hatches an unlockable thing in future, and/or a feature that has to be built into it when constructing one. keeping options open is important

**Comment by skull132** [comment]
Closed. Not a valid solution I'm afraid.

**Pull request closed without merging**
