### PR TITLE
Paroxetine Recipe

### PR DESCRIPTION
**Pull request by Geevies**
* Paroxetine's recipe is now 1 mindbreaker, 1 ammonia, 1 copper.

Comment was made in https://github.com/Aurorastation/Aurora.3/pull/9296 but wasn't implemented in time for merge.

### CODE REVIEW

**Comment by Geevies** [comment]
!bugfix

**Comment by Geevies** [comment]
!review

**Comment by alsoandanswer** [comment]
Wiki should be updated first since the issue was that people who tried to follow the wiki couldn't get the recipe.

**Comment by NonQueueingMatt** [comment]
Not really a bugfix imo?

**Pull request merged**
