### PR TITLE
MASSIVE Nerf to Everyone, Especially Unathi and Vaurca

### PR DESCRIPTION
**Pull request by LordFowl**
- [x] Quantify the problem.
- [x] Analyze the solution.
- [x] Put the solution to code.
- [x] Think of ways to screw over Unathi and Vaurca.
- [x] Analyze if this effect applies to medicine.
- [x] Changelog.
- [x] Get Reviewed.

This PR represents a massive nerf to Unathi and Vaurca, along with some smaller nerfs to a variety of our other xenos. This is in an attempt to curb some pretty gross powercreep that has been occurring lately, and to bring them more in line with the humans so as to make the choice more mechanically meaningful and less obvious, allowing people to be motivated more by roleplay than powergaming. Don't believe me? Just watch.

How does this work? Well, this is in reality a bugfix, because powercreep is a bug, especially for the bugs. Essentially, there is a pretty big oversight in every damage proc except the radiation proc which means that a species' damage coefficient was applied to both positive AND negative values. In effect, if a species took 2x brute damage they also healed brute damage twice as much. This definitely impacted most magical, supernatural, and adminbus forms of healing, however I am also fairly certain that it applied to chemical and medical healing as well.

Where did this problem originate? I think I am actually to blame, back when I modified these procs so that brute mod was carried by the human mob and not just the species.

### CODE REVIEW

**Comment by LordFowl** [comment]
!review

**Comment by BurgerLUA** [comment]
Tbh I'm surprised this wasn't found sooner.

**Comment by LordFowl** [comment]
Which is why I think this _might_ not affect chemical healing, although I don't see any reason why it wouldn't.

**Comment by Bygonehero** [comment]
I'm fine with this, but I am not really sure what you are changing? In the case of Vaurca, it means they heal burn damage faster since they take x2 burn? Is that more or less what you are saying?

**Comment by LordFowl** [comment]
This is a bugfix.

**Comment by Bygonehero** [comment]
Sorry, fixing. If they heal burn damage faster than normal then, of course, fix it. The way you worded the title made me think it was something else.

**Pull request merged**
