### PR TITLE
Destroying the Engineering Lobby pt. 1 + Tesla Stuff

### PR DESCRIPTION
**Pull request by furrycactus**
First part of the divine mission to destroy Engineering's lobby, plus some other stuff relating to the Tesla.

- Removes the snack stuff, glasses, donk pockets, microwave, and drink dispenser.
- Touches up the break room on the sublevel so it's not entirely inferior to the lobby as it currently is in every way.
- Adds a smoking lounge so engineers have a place where they're allowed to smoke in their department if they don't want to go outside.
- Teslay Bay was moved a little further north to try and protect it more from Supermatter delaminations. 
- Sublevel storage and the break room were moved a little bit apart from each other.

Looks like this:
https://i.imgur.com/wExUN8D.png
https://i.imgur.com/pwTKVWN.png
https://i.imgur.com/V5DMXkW.png

### CODE REVIEW

**Comment by furrycactus** [comment]
!review

**Comment by JohnWildkins** [comment]
I don't know how I feel about gutting the pseudo-break room up above and buffing the one down below. It certainly makes more _sense_, but I feel like the engineering lobby is a much more natural choice in-gameplay for engineers to hang out, as opposed to going to the out-of-the-way sublevel and down a couple hallways.

**Comment by fernerr** [comment]
I'm in agreeance, engineers should be encouraged to hang out closer to the rest of the station and not be secluded to a sublevel clubhouse. Engineering already feels pretty isolated from the rest of station happenings. I applaud your efforts, but I think this would be a step in the wrong direction.

**Comment by furrycactus** [comment]
I'll do some revisions shortly then.

**Comment by furrycactus** [comment]
Closing because I had to shift all my shit to a new computer and I'm bad at git

**Pull request closed without merging**
