### PR TITLE
Adds a breathing sound when you're in low pressure.

### PR DESCRIPTION
**Pull request by NonQueueingMatt**
Ported from baystation.

### CODE REVIEW

**Comment by NonQueueingMatt** [comment]
!review

**Comment by ToasterStrudes** [comment]
Does this also exclude IPCs? Need to know for much immersion

**Comment by NonQueueingMatt** [comment]
Ipcs dont have lungs

**Comment by runecap** [comment]
Is it optional and auto-off on bugs

**Comment by NonQueueingMatt** [comment]
It's off for bugs by default. Even if it only works in low pressure.

It's not optional. It's such a low-volume sound I don't really think there's any need for it to be optional.

**Pull request merged**
