### PR TITLE
Updates voidsuit inhand sprites

### PR DESCRIPTION
**Pull request by RustingWithYou**
Updates the in-hand sprites for station voidsuits and helmets to better match their appearance.

### CODE REVIEW

**Comment by RustingWithYou** [comment]
!review

**Review by alsoandanswer — CHANGES_REQUESTED** [review]
item_state_slots are depreceated, use contained sprites

**Comment by Generalcamo** [comment]
Station suits are refittable. Contained sprites -do not- support refitting through cyclers. Recommend tabling that for now.

**Comment by NonQueueingMatt** [comment]
Reopen when changes required are made

**Pull request closed without merging**
