### PR TITLE
Janiupgrades + Future Items

### PR DESCRIPTION
**Pull request by Arrow768**
Adds some upgrades to the janitor items:
- The rag can now be stored in the janitor belt
- The mop cleans a bit faster
- The bucket is a bit larger

Adds some upgraded items to be used by a upcoming project.
They still need some sprites.

ToDo:
- [ ] Electrify the mop

### CODE REVIEW

**Comment by LordFowl** [comment]
I'm not really keen on the mop cleaning faster. Imo it's current time is good.

**Comment by MarinaGryphon** [comment]
> I'm not really keen on the mop cleaning faster. Imo it's current time is good.

We're removing most of the mop-and-bucket alternatives in the depression arc PR. This change is fine.

**Comment by alsoandanswer** [comment]
I volunteer to sprite

**Comment by LordFowl** [comment]
> > I'm not really keen on the mop cleaning faster. Imo it's current time is good.
> 
> We're removing most of the mop-and-bucket alternatives in the depression arc PR. This change is fine.

The depression arc is a temporary chsnge and should not be used to justify permanent ones.

**Comment by skull132** [comment]
Stale, closing.

**Pull request closed without merging**
