### PR TITLE
Emergency Access IDScan

### PR DESCRIPTION
**Pull request by NanakoAC**
Disabling IDscan on a door now makes it all-access. It will open for everyone, (assuming its still powered, not bolted, etc)

### CODE REVIEW

**Comment by Arrow768** [comment]
I dont think that this is a bug and it should be left the way it is.
I have used this "feature" from time to time.

Also it makes no sense.
If you have a access requirement for a door and a cardreader
And you disable the cardreader, the door wont magically open to anyone.

If we want to do this, we should do it properly and add a button: Enable emergency access.
This should also come with the yellow flashing lights that we had before so people are aware that emergency access is enabled.

Just my 2 cents.

**Comment by NanakoAC** [comment]
Name a use case for this feature

If you want to disable a door, you can bolt it, or cut the power. 
If you want to stealthily disable a door, you can bolt it and turn off the bolt lights

I can't think of any feature you're using here, that isn't already covered by other aspects of the door code. IT's a useless feature which, imo, isn't working properly. skull mentioned in chat today he thought emergency access was just disabling IDscan on doors

You're disabling the ID scan, which to my mind turns off authentication and allows the door to open to everyone. i fail to see why it would break the door, the argument of what makes sense can be interpreted either way.

Also, the lack of flashing lights has uses. A good AI could use it to set emergency access on doors on the outpost for instance, to let security through without letting raiders know its been done. A syndicate AI could use it to covertly assist traitors while maintaining plausable deniability

**Comment by Arrow768** [comment]
Let me explain how a decent access control system works:
You have a reader unit that reads the card / token / whatever presented to it
That reader unit than transmits that information (id, fingerprint hash, code, whatever) to a controller that is located in a secure area (inside of the door)
The controller then evaluates the information received and opens the door if a permitted id is received.
If someone were to disable the reader
Nothing would happen, because the controller doesnt get a id to evaluate and therefore doesnt open the door.

Ingame you should get the same result as if you were trying to access a door you dont have access to.
Right now it gives you the red blink, but doesnt play the sound.

Lets say there is a sec raid on a outpost. And sec needs to get in quietly.
What prevents the AI from just opening the doors for them ? - Exactly Nothing.

If we change anything, we should:
* Add the id fail sound if someone tries to open a door where the id scan is disabled
* Add the option for the AI to enable emergency access
* (optional) Add a computer that allows to remotely enable emergency access for a airlock

**Comment by skull132** [comment]
DNM until review and discussion. Won't fit the current pull window.

**Pull request closed without merging**
