### PR TITLE
Revert "Mechanically enforces minimum age requirements for jobs"

### PR DESCRIPTION
**Pull request by MarinaGryphon**
Reverts Aurorastation/Aurora.3#7106
This was a bad idea and also fucks up alt-titles like EMT, which is has a requirement of 20 but is fucked over by the requirement for paramedic being 24.

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
Why is this a bad idea?

**Comment by MarinaGryphon** [comment]
> Why is this a bad idea?

First, mechanical enforcement of job age requirements except for head of staff roles are dumb.

It also doesn't properly align with the wiki.

Additionally, it fucks up alt titles because it's per master job, not per sub-job. This means that EMTs, despite having a sensible age requirement of 20, must be 24.

**Comment by TheGoret** [comment]
Or you could just ask it to be fixed instead of removing it.
Also, you're wrong by saying its dumb. The idea is good as we don't have to deal with 18 years old doctors anymore. I can tell you that it happen often with new players, and I'd prefer if I had less to do and that game would support the fact that its impossible to be 18 and a surgeon.

**Comment by NonQueueingMatt** [comment]
It does align with the wiki. Not sure where you got that from.

Since it's apparently reasonable for head of staff roles, why are you reverting the entire PR instead of just removing the age req on every other job?

**Comment by Sindorman** [comment]
Superseded by #7130

**Comment by skull132** [comment]
ded.

**Pull request closed without merging**
