### PR TITLE
Adding more logos to Pencode

### PR DESCRIPTION
**Pull request by Sindorman**
As title says this PR adds extra 6 logos to penwriting.

Added new paper logos for: 

- [logo_nt] - Regular NT logo

-  [logo_nt_small] - Small size NT logo

- [log_zh] - Zeng-Hu, [logo_idris] - Idris

-  [logo_eridani] - Eridani

-  [logo_necro] - Necropolis

-  [logo_hp] - Hephaestus Industries.

- [logo_be] - Beisel

### CODE REVIEW

**Comment by Sindorman** [comment]
!review

**Comment by Sindorman** [comment]
These are all new Logo:
dreamseeker_LYaX9fkx8I


These are new big logos in comparison to regular NT logo:
dreamseeker_MKoXVQBpAM
dreamseeker_0vHenjP67r

**Comment by KingOfThePing** [comment]
Doing god's work again. Very good, impressed how quickly this was done.

**Comment by Sindorman** [comment]
Also added Beisel logo
belogo

**Pull request merged**
