### PR TITLE
Tau Ceti Celebration Event PR

### PR DESCRIPTION
**Pull request by Eyeveri**
This fixes the HAPT shuttle/replaces it and adds the VIP ghost role to the CCIA spawner for this weekends coming event, and for future use.

### CODE REVIEW

**Comment by Eyeveri** [comment]
I will note that this shuttle is not meant to be overmap capable and I will revisit it AFTER the event passes. I am only putting this up now so that it can be fully merged instead of needing a test merge, by the time the event rolls around.

**Comment by Eyeveri** [comment]
!review

**Comment by DreamySkrell** [comment]
image
don't pixelshift vendors into walls and change their density

**Comment by DreamySkrell** [comment]
image
these shuttle walls have defined in code color `"#2E2B2B"` and then in the map prefab it's changed to `"2E2B2B"` - should not be changed in map

**Comment by Eyeveri** [comment]
@DreamySkrell Fixed everything above.

**Comment by DreamySkrell** [comment]
image
what is this docking controller for? remove it if it has no function

**Comment by DreamySkrell** [comment]
image
this shuttle is defined in aurora_shuttles.dm
should be defined in horizon files

**Comment by DreamySkrell** [comment]
image
id's like for doors or the like should mention what shuttle/ship/map they are for
like here it would be "some_shuttle_rapid_deploy"

otherwise there may be conflicts with other maps, if some other ship or whatever has a door with id "rapid_deploy", and its button may open this door (or the other way around)

**Comment by Eyeveri** [comment]
> "some_shuttle_rapid_deploy"

Got it. 

Do you want me to put an actual airlock here, or is this fine? I have it as blastdoors because the passengers here should always be in HAPT Hardsuits.

**Comment by DreamySkrell** [comment]
image
should have a holopad

**Comment by DreamySkrell** [comment]
image
shuttle datum is still defined in two files at the same time 

 should be defined in one place only (horizon files0

**Comment by DreamySkrell** [comment]
image
naming is inconsistent

it's named "Crescent Shuttle" - should have a designation like "ICV Crescent Shuttle" or "HAP Crescent Shuttle" (whatever makes sense for it, idk if it's supposed to be a covert)

in code the type is just `/admin` - should be `/crescent` (since the blast door is already called that), cause we have many "admin-only" shuttles so just calling it "admin" is not very descriptive

same applies to the area - `/area/shuttle/admin`

and all the other blast door buttons (other than from the rapid deploy that was already changed) - right now they have ids `"corvette_exterior"` and `"corvette__bridge_exterior"`

**Comment by DreamySkrell** [comment]
image
add highlighted line so the name and designation for this shuttle can be easily changed in game for adminbus gimmicks

**Comment by DreamySkrell** [comment]
image
the light overlaps with the button and sensor

image
the exterior access button is wrong dir and pixel shift - should be like this

**Comment by DreamySkrell** [comment]
image
airlock components (buttons, controller, sensor) have vars set (access, freq, id_tag) in the map 
should be removed as it is handled by the airlock marker

**Comment by DreamySkrell** [comment]
image
image
the shuttle airlock is set up wrong, and does not open on round start
it does open when docking though, and works when cycling it manually

well, it "works", but it's probably cause there's two controllers fighting for control over the doors: the simple docking controller in the cockpit, and the docking controller in the airlocks

but it should be set up correctly:
1. the docking controller in the cockpit should be moved to the hangar, and set up for example like the intrepid hangar docking controller (its only purpose is to make the shuttle think it's "docked" when in the hangar so the doors automatically open)
2. the docking controller in the airlock should be set up correctly as well, and the marker have shuttle_tag set to "Crescent Shuttle"

**Comment by Eyeveri** [comment]
@DreamySkrell 

I have addressed everything above.

**Review by DreamySkrell — APPROVED** [review]

**Review by Alberyk — APPROVED** [review]

**Review by FluffyGhoster — APPROVED** [review]

**Pull request merged**
