### PR TITLE
Freebooter tweaks and fixes

### PR DESCRIPTION
**Pull request by hazelrat**
Adds several new areas. Previously, freebooter_ship/bridge covered around a dozen separate rooms off a single APC, despite the wires for the APCs of each room still being under the floors. These are now all separate.

Revamps propulsion to fit in with more modern standards. There's now two tiles of 25000kPa CO2 in a multi-tile tank in the starboard nacelle, that feeds all eight thrusters with a line running through the ship, plus a pair of heat gas heaters and some combustibles if you want to get really funny. Balance with this could be iffy, the top speed you can reasonably expect by dumping virtually the entire tank in at 100% thrust limit is around 5Gm/h, but running it that fast will run you dry very quickly. One of the tiles in the CO2 tank is vacuum to drop the pressure a little, and in my testing the crew would still have to carefully moderate fuel usage to keep themselves floating, it's just a much less annoying system to work with than using canisters. If we want to reduce that maximum speed, the best way would just be to knock their thrusters from 8 to 6, though I don't think that's necessary.

image

Fixes improper plating throughout the ship.

Adds some more medical supplies, including pneumalin, soporific, a trauma kit, and a hypospray. All surgical supplies are either ghetto, or can be already made from the autolathe. 

Adds a condiment box, and k'ois bars, to the kitchen.

Added tajaran and unathi insulated gloves.

You can now actually see the distress beacon and bridge blast doors buttons!

Adapted the airlocks to markers, and reworked the shuttle airlock to be much, much faster. The docking port should also line up with the actual airlocks now, and the shuttle should no longer be able to function without power. All thrusters are also connected, now - five thrusters is a *lot*, but they only have the one tiny CO2 tank. The underpipe walls are horrifying, but I don't have it in me to redesign the shuttle.

image

All air alarms *should* have open access, now.

Note: ship still probably needs proper docking ports, but I'm not tackling those right now. If someone else wants to take that upon themselves, it would definitely be useful.

### CODE REVIEW

**Comment by hazelrat** [comment]
!review

**Comment by DreamySkrell** [comment]
image
Remove this navpoint, it doesn't do anything

image
Should be walls between engines and interior - windows on engines is a old mapping style. It's weird to be able to see space through engines.

image
Here it's even weirder cause that one engine on the shuttle is in different dir than the shuttle's main engines.

Looks otherwise.

**Comment by DreamySkrell** [comment]
> One of the tiles in the CO2 tank is vacuum to drop the pressure a little

Oh yeah also it can't be like this as it means roundstart atmos processing (and that is probably why the tests fails)
all tiles in a room should have the same gas composition and pressure

**Comment by hazelrat** [comment]
Changes implemented.

**Comment by DreamySkrell** [comment]
image
oh yeah also remove the fake thruster objects here, replace with walls

**Comment by hazelrat** [comment]
Notable addition, the NT module has been changed to function as an impromptu brig, with the idea that it was hollowed out by the crew to have a dedicated space for friendly sleepovers and persuasive interrogation techniques. Notably, There's a tiny amount of phoron in the two remaining canisters with about 200 moles between them, with the idea that they've only nearly rather than totally run out.

image

**Review by DreamySkrell — APPROVED** [review]

**Review by Geevies — APPROVED** [review]

**Review by NonQueueingMatt — APPROVED** [review]

**Pull request merged**
