### PR TITLE
Kinetic Accelerator Additions

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Overview
I want mining to be able to find some unique, powerful kinetic accelerators while out on the dig. Most of these are pretty high tier (Class B to S, or BS for short) and should be great finds for miners.

I also made it so that you can only pump the assemblies if you have two hands, and some kinetic accelerators are just too heavy to fire with one hand.

## What's inside
Adds 4 new kinetic accelerator cells
- Phoron Loading: Takes sheets of phoron as ammo.
- Uranium Loading: Takes sheets of uranium as ammo.
- Hydrogen Loading: takes sheets of hydrogen as ammo.
- Kinetic Charging: A pump action and charging cell all in one.

Adds 3 new kinetic accelerator barrels
- Phoron: Massive barrel that amplifies the energy using phoron crystals
- Rapid: Rapid fire barrel that deals low damage. For those who want to click more.
- Supermatter: Currently admins can spawn these. They mine as big as the screen. God help us all.

Adds 6 new frames:
- Two are heavy and can fit any addition.
- One has a burst fire option.
- The rest are simple stat modifiers that are meant to complement the new barrels and cells.

Adds a kinetic analyzer. Kinetic analyzers can be purchased from cargo. They display useful information about a kinetic assembly.

### CODE REVIEW

**Comment by BotBOREALIS** [comment]
Icons with diff:
<details><summary>icons/obj/kinetic_accelerators.dmi</summary>

Key | Old | New | Status
--- | --- | --- | ---
barrel01|barrel01|barrel01|Modified
barrel02|barrel02|barrel02|Modified
barrel03|barrel03|barrel03|Modified
barrel04|barrel04|barrel04|Modified
barrel05|barrel05|barrel05|Modified
frameA||frameA|Created
frameB||frameB|Created
frameC||frameC|Created
frameD||frameD|Created
frameE||frameE|Created
frameF||frameF|Created
barrel02_alt||barrel02_alt|Created
barrel05[1]||![barrel05[1]](http://images.aurorastation.org/images/98bf9c4810e4cb6609e1841b9fcf9440.png)|Created
barrel05[2]||![barrel05[2]](http://images.aurorastation.org/images/59e1a66cbe56a1a0af529505e891c727.png)|Created
barrel05[3]||![barrel05[3]](http://images.aurorastation.org/images/6acaa8ebd3725b59a94880a966bff604.png)|Created
barrel05[4]||![barrel05[4]](http://images.aurorastation.org/images/9c3792223a785b5cddefddaec6bba3fd.png)|Created
barrel_phoron||barrel_phoron|Created
barrel_phoron[1]||![barrel_phoron[1]](http://images.aurorastation.org/images/cf9d756199beca9a7fc4a8eb2de8e9cb.png)|Created
barrel_phoron[2]||![barrel_phoron[2]](http://images.aurorastation.org/images/ddfff9a01df105a9f1e68a2fbd130f5f.png)|Created
barrel_phoron[3]||![barrel_phoron[3]](http://images.aurorastation.org/images/5f8b9a76466915b239ee84b18636a9da.png)|Created
barrel_phoron[4]||![barrel_phoron[4]](http://images.aurorastation.org/images/99c2c0106237ef726152d6ae41e61759.png)|Created
barrel_supermatter||barrel_supermatter|Created
barrel_supermatter[1]||![barrel_supermatter[1]](http://images.aurorastation.org/images/b74358f2bade924c2e0b7223ef9866c8.png)|Created
barrel_supermatter[2]||![barrel_supermatter[2]](http://images.aurorastation.org/images/48cbc2a8a904fc9208ceb2b8a5e43d2e.png)|Created
cell_burst||cell_burst|Created
cell_uraniumloader||cell_uraniumloader|Created
cell_phoronloader||cell_phoronloader|Created
cell_hydrogenloader||cell_hydrogenloader|Created
cell_magazine_unloaded||cell_magazine_unloaded|Created
cell_magazine_loaded||cell_magazine_loaded|Created
misc_mag||misc_mag|Created
</details>

**Comment by BurgerLUA** [comment]
!wip

**Comment by BurgerLUA** [comment]
!review

**Comment by BurgerLUA** [comment]
No longer WIP. Tested everything, and everything works.

**Pull request merged**
