### PR TITLE
The manufacturer of NanoMed vending machines is now correctly set to NanoTrasen

### PR DESCRIPTION
**Pull request by Generalcamo**
Extremely simple change, that just changes the TGUI background to reflect the manufacturer of the vending machines.

### CODE REVIEW

**Comment by Generalcamo** [comment]
!review

**Comment by Generalcamo** [comment]
!bugfix

**Review by alsoandanswer — APPROVED** [review]

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]
I don't want this. Reflavour them to Zeng-Hu instead.

**Comment by SleepyGemmy** [comment]
> I don't want this. Reflavour them to Zeng-Hu instead.

it was already set to Zeng-Hu, so the PR should probably be closed in that case.

**Comment by Generalcamo** [comment]
I'll grab a spriter and make a second PR

**Pull request closed without merging**
