### PR TITLE
Ports Europa Fluids from Bay

### PR DESCRIPTION
**Pull request by Geevies**

### CODE REVIEW

**Comment by Geevies** [comment]
image
image
image
image
image

**Comment by KasparoVy** [comment]
TFW this lizardman cranks open the massive ass water tank and bails, flooding the entire toolroom 4noraisin

**Comment by Geevies** [comment]
Skrell actually get positive messages when they're in deep water, and are able to breathe in it.

**Comment by KasparoVy** [comment]
Brilliant, thanks for clearing that up

Makes sense, good fluff

**Comment by Butterrobber202** [comment]
can you get a big info drop on how the water interacts with stuff

**Comment by Geevies** [comment]
Closing due to receiving no reviews.

**Pull request closed without merging**
