### PR TITLE
Suspending different subsystems during explosion

### PR DESCRIPTION
**Pull request by Sindorman**
This PR implements suspending different subsystems during explosions to stop lag/freezes and allow to process explosions first. Currently configured subsystems to be suspended:

- ZAS

- MOBS AI

- Machinery.

### CODE REVIEW

**Comment by Sindorman** [comment]
Results so far are good, creating explosion of 14 tiles range, 7 range of heavy impact, 10 range of light impact does not freeze client as much(depending on specs) and processes explosion pretty fast.

**Comment by Sindorman** [comment]
!review

**Comment by skull132** [comment]
Consider to also add to this list: life.

**Comment by Sindorman** [comment]
> Consider to also add to this list: life.

As we discussed in chat, that will cause players to stay alive until next time `Life()` is called, which will make them temporary be alive while they are supposed to be dead.

**Comment by Nero-07** [comment]
> 
> 
> Consider to also add to this list: life.

Be medical main
"We're losing him! Set off more explosions to buy us time!"
*BOOOOOM*
:D

**Pull request merged**
