### PR TITLE
Adds a Hieroaetherian nation cape, allows Hieroaetherian Skrell to wear Hieroaetherian items, etc

### PR DESCRIPTION
**Pull request by feartheblackout**
see changelog
image
image

### CODE REVIEW

**Comment by feartheblackout** [comment]
!review

**Comment by feartheblackout** [comment]
!wip because i forgot that the cape needs an extended description from lore (oops)

**Comment by feartheblackout** [comment]
@Caelphon @WhatsUpBrotendo needs maintainer approval and a description for the cape if approved

**Comment by WhatsUpBrotendo** [comment]
Here's an extended description for the cape, approved by Cael.

desc_extended = "A relatively new addition to Skrell fashion, these cloaks are meant to identify the origin of the wearer. Since first contact, it has been a popular way for Skrell to distinguish themselves from Skrell from other regions of the Orion Spur, and has become a popular way to denote political ties or support. This cape signifies that the wearer comes from the Consortium of Hieroaetheria. The Consortium and the Federation's strong ties mean that Fed-aligned Skrell generally approve of this cape."

**Comment by feartheblackout** [comment]
!review

**Review by NonQueueingMatt — APPROVED** [review]

**Comment by feartheblackout** [comment]
description updated with the current sprites for the hieroaetherian cape :)

**Review by Geevies — APPROVED** [review]

**Pull request merged**
